### ISSUE TITLE
能否在不包含侧滑菜单的时候，添加一个侧滑返回，边缘finish当前Fragment

### ISSUE THREAD

**Issue by ggchxx** [YoKeyword/Fragmentation#1]
能否在不包含侧滑菜单的时候，添加一个侧滑返回，边缘finish当前Fragment，或者能给一些提示不？谢了

**Comment by YoKeyword** [comment]
@ggchxx 我去尝试下实现的方案哈  :)

**Comment by YoKeyword** [comment]
@ggchxx 我提交了新的一个fragmentation_swipeback库，也在该库里，详情参考新的README   :)

**Comment by ggchxx** [comment]
好的 谢谢楼主
