### ISSUE TITLE
透明Fragment

### ISSUE THREAD

**Issue by duchengzhen** [YoKeyword/Fragmentation#10]
如何显示一个透明的Fragment,源码里直接给设置成了windowBackground

**Comment by YoKeyword** [comment]
@duchengzhen  复写下` int getWindowBackground()`方法，这个方法是取windowBackground背景的，你复写直接返回你的背景资源即可（注：int是资源id，不是color）

这个我回头专门开放个方法吧，现在这个方法名作为更改背景色名字不合适。

**Comment by YoKeyword** [comment]
@duchengzhen 我在检查代码的时候发现，其实你只要给Fragment的根布局设置 background，Fragmentation就不会把背景设为windowBackground的了：
`if (view != null && view.getBackground() == null) {
        int background = getWindowBackground();
        view.setBackgroundResource(background);
}`

但是你想通过设置背景色是透明，并通过该Fragment看到下面的Fragment视图，直接设置透明背景并不会直接起作用，因为透过该Fragment看到的是Activity的背景色或者是windowBackground；因为你start了Fragment后，上一个Fragment的视图就是INVISIBLE的了；

你可以通过以下代码让上一个Fragment的视图暂时变为看见，这样就可以达到通过当前透明Fragment可以看到前一个Fragment的视图了：
`
getPreFragment().getView().setVisibility(View.VISIBLE);
`

**Comment by duchengzhen** [comment]
非常感谢，还是源码和fragment理解不透彻的原因

在 2016-05-20 21:26:44，"YoKey" <notifications@github.com> 写道：


@duchengzhen 我在检查代码的时候发现，其实你只要给Fragment的根布局设置 background，Fragmentation就不会把背景设为windowBackground的了：
if (view != null && view.getBackground() == null) {
int background = getWindowBackground();
view.setBackgroundResource(background);
}

但是你想通过设置背景色是透明，并通过该Fragment看到下面的Fragment视图，直接设置透明背景并不会直接起作用，因为透过该Fragment看到的是Activity的背景色或者是windowBackground；因为你start了Fragment后，上一个Fragment的视图就是INVISIBLE的了；

你可以通过以下代码让上一个Fragment的视图暂时变为看见，这样就可以达到通过当前透明Fragment可以看到前一个Fragment的视图了：

getPreFragment().getView().setVisibility(View.VISIBLE);

**Comment by LittleWaver** [comment]
@YoKeyword 请问，我更新了fragmentation的版本后就没有getPreFragment().getView()方法了，请问该如何设置上一个Fragment为可见的？

**Comment by LittleWaver** [comment]
刚才又查看了下issue，看到了这个方法可以用来实现：extraTransaction().startDontHideSelf(fragment)
