### ISSUE TITLE
为什么在setFramgentResult bundle数据是 普通String可以获取到 而ArrayList确一直没有获取到数据

### ISSUE THREAD

**Issue by CharlesMing** [YoKeyword/Fragmentation#100]
ArrayList对象我是序列化了的  在当前页面可以get到，在onFragmentResult里面get就不行了 对象是获取到了的 但是数据没有获取到

**Comment by YoKeyword** [comment]
数据的传递是基于Fragment的set/getArguments()的，即Bundle的，应该是没问题的；
确保ArrayList<T>的T是parcelable或serializable，取得时候根据不同序列化的方式取数据，看看~

另外实际开发中，在Fragment上，是比较建议用EventBus的~

**Comment by CharlesMing** [comment]
parcelable/serializable 这两个我试过了 不行  我使用EventBus成功了 谢谢

**Comment by YoKeyword** [comment]
OK，你的这个问题，明天我再校验下哈~

**Comment by CharlesMing** [comment]
OK

**Comment by zou1755815609** [comment]
你好，目前遇到需要在fragment里面设置软键盘弹出模式getActivity().getWindow().setSoftInputMode(
				WindowManager.LayoutParams.SOFT_INPUT_STATE_VISIBLE
						| WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
使用这代码无效，在普通fragment里面有效，请问有何解决方案吗

**Comment by YoKeyword** [comment]
抱歉，忙忘了... 哈哈～

我刚试了下ArrayList是可以正常传递的 ,StringArrayList ,ParcelableArrayList 都可以  :)
