### ISSUE TITLE
Fragment already added

### ISSUE THREAD

**Issue by GoAheadComeOn** [YoKeyword/Fragmentation#1001]
你好，bugly上捕获的日志是：Fragment already added: DialogGeneralTwoTitleOneBtn{4cd2c7 #2 InspectionShopSignalFragment}
android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1694)

1 android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1694)
--
2 android.app.BackStackRecord.executeOps(BackStackRecord.java:776)
3 android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2401)
4 android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2196)
5 android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2149)
6 android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2056)
7 android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
8 android.os.Handler.handleCallback(Handler.java:808)
9 android.os.Handler.dispatchMessage(Handler.java:101)
10 android.os.Looper.loop(Looper.java:166)
11 android.app.ActivityThread.main(ActivityThread.java:7425)
12 java.lang.reflect.Method.invoke(Native Method)
13 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
14 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

场景是在fragment中添加dialog，fragment是Fragmentation来管理的dialog是继承自DialogFragment，但是dialog没有使用Fragmentation来管理，DialogFragment的show方法在截图中，请问我这种处理方式有什么问题
![fragment](https://user-images.githubusercontent.com/13044161/45987072-22730b80-c0a2-11e8-96c1-b589bd561875.png)

**Comment by YoKeyword** [comment]
该异常可搜索下， 另外关于DialogFragment 可以阅读下 #1017
