### ISSUE TITLE
建议onBackPressedSupport中，能加多一个是否FinishActivity的复写回调

### ISSUE THREAD

**Issue by hezihaog** [YoKeyword/Fragmentation#1006]
因为onBackPressed被final了，推荐复写onBackPressedSupport。
public void onBackPressedSupport() {
        if (getSupportFragmentManager().getBackStackEntryCount() > 1) {
            pop();
        } else {
            ActivityCompat.finishAfterTransition(mActivity);
        }
    }
else逻辑直接finish调activity了，如果我需要MainActivity最后返回操作是移到后台而不是finish就要抄这段代码过去改else逻辑为moveTaskToBack(true);希望可以增加一个准备finish的回调复写，返回true为直接走finish，false则不做处理，就不用拷贝代码过去改了

**Comment by qianshengta** [comment]
+1

**Comment by beilo** [comment]
onBackPressedSupport..这里面的逻辑不是自己定义的么.自己重写下不就好了么
