### ISSUE TITLE
enqueueDispatchVisible的问题

### ISSUE THREAD

**Issue by ab503044120** [YoKeyword/Fragmentation#1019]
me.yokeyword.fragmentation.helper.internal.VisibleDelegate

private void enqueueDispatchVisible() {
        getHandler().post(new Runnable() {
            @Override
            public void run() {
                dispatchSupportVisible(true);
            }
        });
    }
为什么这里要加post,存在异步操作吗
这里加了会影响懒加载的
用你deme中的例子
wechat-demo的WechatSecondTabFragment
我如果在onLazyInitView里添加
` mViewPager.setCurrentItem(1);`
会造成两个页面同时被加载

如果去掉
     getHandler().post
就回工作正常即进页面只初始化了第二个页面

**Comment by YoKeyword** [comment]
这里为了保证`onCreateView` -> `onLazyInitView()`的生命周期， 因为在ViewPager等不同的Fragment组件结构下，`setUserVisibleHint()`的触发时机会早于`onCreateView()`
