### ISSUE TITLE
onBackPressSupport的问题

### ISSUE THREAD

**Issue by yygutn** [YoKeyword/Fragmentation#1025]
`
class ContainerActivity : SupportActivity() {

    companion object {
        private var mFragment: WeakReference<SupportFragment>? = null
        fun withFragment(fragment: SupportFragment) {
            mFragment = WeakReference(fragment)
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (mFragment?.get() is SupportFragment) {
            val f = mFragment!!.get() as SupportFragment
            loadRootFragment(android.R.id.content, f)
        } else {
            onBackPressed()
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        mFragment?.clear()
        mFragment = null
    }
 }

`

本意是想通过静态方法传递一个Fragment然后作为一个通用的容器, 但是发现 在 Fragment里面调用onBackPressSupport方法无法返回, 但是按返回键是可以的.

非常不解, 因为其他页面也有用到这个方法, 是可以返回的, 这个简单写了个返回就不行,,,,

这是Fragment里面的调用, 没有复写返回方法
`
mToolBar.setNavigationOnClickListener { onBackPressedSupport() }
`

**Comment by yygutn** [comment]
想了下, 应该是 调用 `_mActivity.onBackPressed()` 才对

**Comment by beilo** [comment]
一般start的fragment 你直接pop就好了,
