### ISSUE TITLE
SupportFragmentDelegate.onSaveInstanceState(outState)

### ISSUE THREAD

**Issue by FatPaper** [YoKeyword/Fragmentation#1036]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by FatPaper** [comment]
我想问问SupportFragmentDelegate.onSaveInstanceState将fragment根布局设置成可点击的作用是什么，这个方法导致activity不能处理onTouchEvent

**Comment by FatPaper** [comment]
我貌似写错了，应该是在onActivityCreated里将根布局设置成可点击
`public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        getVisibleDelegate().onActivityCreated(savedInstanceState);

        View view = mFragment.getView();
        if (view != null) {
            mRootViewClickable = view.isClickable();
            view.setClickable(true);
            setBackground(view);
        }


        if (savedInstanceState != null
                || mRootStatus == STATUS_ROOT_ANIM_DISABLE
                || (mFragment.getTag() != null && mFragment.getTag().startsWith("android:switcher:"))
                || (mReplaceMode && !mFirstCreateView)) {
            notifyEnterAnimEnd();
        } else if (mCustomEnterAnim != Integer.MIN_VALUE) {
            fixAnimationListener(mCustomEnterAnim == 0 ?
                    mAnimHelper.getNoneAnim() : AnimationUtils.loadAnimation(_mActivity, mCustomEnterAnim));
        }

        if (mFirstCreateView) {
            mFirstCreateView = false;
        }
    }`

**Comment by YoKeyword** [comment]
@FatPaper 这里是为了防止点击事件的穿透，但这个闲置过程仅限在Fragment动画中，最终会设置回：
````java
 private Runnable mNotifyEnterAnimEndRunnable = new Runnable() {
        @Override
        public void run() {

            if (mRootViewClickable) return;
            ...

            mHandler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    view.setClickable(false);
                }
            }, prePopExitDuration - enterDuration);
        }
    };
````
