### ISSUE TITLE
代码设置软键盘弹出模式

### ISSUE THREAD

**Issue by zou1755815609** [YoKeyword/Fragmentation#104]
你好，目前遇到需要在fragment里面设置软键盘弹出模式getActivity().getWindow().setSoftInputMode(
WindowManager.LayoutParams.SOFT_INPUT_STATE_VISIBLE
| WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
使用这代码无效，在普通fragment里面有效，请问有何解决方案吗

**Comment by YoKeyword** [comment]
在普通Fragment有效的，在SupportFragment应该也是有效的；

你可以参考第二个Demo的MsgFragment的写法，可以达到你的要求;

**在Fragment中动态设置SoftInputMode，应该在onCreateView或之后的生命周期里使用post（Runnable里设置SoftInputMode）， 在该库中，建议直接在onEnterAnimationEnd()里setSoftInputMode(无需post)**
