### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by SixPalms** [YoKeyword/Fragmentation#1043]
bugly上经常汇报出java.lang.IllegalStateException Can not perform this action after onSaveInstanceState
一个貌似随机无法复现的错误，不知什么原因导致的。
以下为bugly信息：

android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
--
2 android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
3 android.support.v4.app.FragmentManagerImpl.popBackStack(FragmentManager.java:802)
4 android.support.v4.app.FragmentationMagician$3.run(FragmentationMagician.java:121)
5 android.support.v4.app.FragmentationMagician.hookStateSaved(FragmentationMagician.java:194)
6 android.support.v4.app.FragmentationMagician.popBackStackAllowingStateLoss(FragmentationMagician.java:118)
7 me.yokeyword.fragmentation.TransactionDelegate.safePopTo(TransactionDelegate.java:578)
8 me.yokeyword.fragmentation.TransactionDelegate.mockPopToAnim(TransactionDelegate.java:608)
9 me.yokeyword.fragmentation.TransactionDelegate.doPopTo(TransactionDelegate.java:565)
10 me.yokeyword.fragmentation.TransactionDelegate.access$1300(TransactionDelegate.java:32)
11 me.yokeyword.fragmentation.TransactionDelegate$11.run(TransactionDelegate.java:293)
12 me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
13 me.yokeyword.fragmentation.queue.ActionQueue.enqueueAction(ActionQueue.java:45)
14 me.yokeyword.fragmentation.queue.ActionQueue.access$000(ActionQueue.java:17)
15 me.yokeyword.fragmentation.queue.ActionQueue$1.run(ActionQueue.java:37)
16 android.os.Handler.handleCallback(Handler.java:809)
17 android.os.Handler.dispatchMessage(Handler.java:102)
18 android.os.Looper.loop(Looper.java:166)
19 android.app.ActivityThread.main(ActivityThread.java:7555)
20 java.lang.reflect.Method.invoke(Native Method)
21 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
22 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by qianshengta** [comment]
我也出现了，不知道问题在哪里

**Comment by wilsonssss** [comment]
![image](https://user-images.githubusercontent.com/4098951/53322449-68185680-3916-11e9-8d18-ac7507c89250.png)

we are facing the same issue, please help @YoKeyword

**Comment by qianshengta** [comment]
Every time you use a "loadRootFragment" or "loadmultifragment"，Call "findChildFragment" first to make sure there are no fragments to load in the stack。like：

```
     if (findFragment(MainFragment.class) == null)
            loadRootFragment(MainFragment.newInstance());
        else
            Logger.e("findFragment(MainFragment.class) != null");
```


```
        if (findChildFragment(HomeFragment.class) == null) {
            mFragments[0] = HomeFragment.newInstance(listener);
            mFragments[1] = InformationFragment.newInstance();
            mFragments[2] = OrderFragment.newInstance();
            mFragments[3] = MineFragment.newInstance();
            current = mFragments[0];
            loadMultipleRootFragment(0, mFragments);
        } else {
            mFragments[0] = findChildFragment(HomeFragment.class);
            mFragments[1] = findChildFragment(InformationFragment.class);
            mFragments[2] = findChildFragment(OrderFragment.class);
            mFragments[3] = findChildFragment(MineFragment.class);
        }
```
You can have a try
@wilsonssss

**Comment by wilsonssss** [comment]
thank you man, we will try @qianshengta

**Comment by YoKeyword** [comment]
PS: v1.3.7 可以镇压`support-27.1.0+`上的这个异常 （当然尽可能避免在 `afterSaveInstanceState`后执行事务）
