### ISSUE TITLE
升级到AndroidX 出错了

### ISSUE THREAD

**Issue by guoheng1996** [YoKeyword/Fragmentation#1046]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs    java.lang.NoSuchFieldError: No field mActive of type Landroid/util/SparseArray; in class Landroidx/fragment/app/FragmentManagerImpl; or its superclasses (declaration of 'androidx.fragment.app.FragmentManagerImpl' appears in /data/app/cn.primedroid.fido.sample-lTFIlev9ug_a-G5ttXwPNg==/split_lib_dependencies_apk.apk)
        at androidx.fragment.app.FragmentationMagician.getActiveFragments(FragmentationMagician.java:153)
        at me.yokeyword.fragmentation.SupportHelper.getPreFragment(SupportHelper.java:95)
        at me.yokeyword.fragmentation.SupportFragmentDelegate$3.run(SupportFragmentDelegate.java:611)
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by moneeWong** [comment]
大佬何时升级到AndroidX

**Comment by CH-Augustine** [comment]
赶紧升级啊大佬，公司项目全指望你呢

**Comment by SixPalms** [comment]
之前也一直使用这个开源项目 但是现在发现问题不能解决的话问题会比较严重 现在感觉最好还是使用activity比较好

**Comment by CH-Augustine** [comment]
Download 下来自己改源码呗，我都是这样干的


| |
王亮
邮箱：nice_ohoh@163.com
|

签名由 网易邮箱大师 定制

在2018年11月27日 22:11，SixPalms 写道：

之前也一直使用这个开源项目 但是现在发现问题不能解决的话问题会比较严重 现在感觉最好还是使用activity比较好

**Comment by krcdxnh** [comment]
其他框架基本上都更新androidx了，项目就差这个不能使用，诶

**Comment by YoKeyword** [comment]
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation/blob/androidx/README_CN.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
