### ISSUE TITLE
fragment内调用startActivityForResult会pop？

### ISSUE THREAD

**Issue by pye52** [YoKeyword/Fragmentation#105]
rootfragment打开一个子fragment A（A与rootfragment不是嵌套关系），在fragment A里调用startActivityForResult，会跳到rootfragment里，查看栈视图也会发现A不见了，于是A里的onActivityResult无法响应（都不见了…怎么响应QAQ）

我在自己的项目里是这样，在demo里修改cyclefragment下mBtnNextWithFinish的onclick方法也是这样-。-

demo_wechat->ui->fragment->third->CycleFragment
73行改成这样
mBtnNextWithFinish.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i = new Intent(Intent.ACTION_GET_CONTENT);
                i.addCategory(Intent.CATEGORY_OPENABLE);
                i.setType("video/*");
                startActivityForResult(i, 1);
            }
        });

**Comment by pye52** [comment]
大概情况就是…无论同级多少个fragment，只要startActivityForResult，就会跳到rootfragment上…

**Comment by YoKeyword** [comment]
@pye52 莫有啊... 我73行改成你写的那样， 可以正常跳转到视频选择页面，返回后还在CycleFragment
😅

**Comment by pye52** [comment]
额…抱歉，发现问题了
那个demo之前提issue的时候改动过，在onpause的时候popto到rootfragment了（我想戳瞎自己眼睛
浪费了你时间不好意思Orz

**Comment by YoKeyword** [comment]
莫事莫事   :)
