### ISSUE TITLE
setSwipeBackEnable

### ISSUE THREAD

**Issue by woxiangxin7779** [YoKeyword/Fragmentation#1051]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by woxiangxin7779** [comment]
public void setSwipeBackEnable(boolean enable) {        

  mSwipeBackLayout.setEnableGesture(enable);     }

在设置 setSwipeBackEnable 里面调用的   mSwipeBackLayout.setEnableGesture 
 但是现在  mSwipeBackLayout为null 这是不是一个bug ? 
设置 setSwipeBackEnable  只是一个标记。在 初始化 mSwipeBackLayout 以后再进行 设置。

**Comment by YoKeyword** [comment]
`SwipeBackLayout`的初始化时机是`onCreate()`，检查下调用时机
