### ISSUE TITLE
你好请教一个空指针的问题

### ISSUE THREAD

**Issue by GoAheadComeOn** [YoKeyword/Fragmentation#1052]
你好我的项目在bugly上面捕获到了一个SwipeRefreshLayout空指针的情况，具体代码在截图中，结合fragment的生命周期和BaseFragment的代码我想破脑袋也不知道为什么我在用户点击list的时候盘点mSwipeRefreshLayout.isRefreshing()，请问能帮忙分析下原因吗0..0
![1111111111111](https://user-images.githubusercontent.com/13044161/49556448-c4cf2b00-f93e-11e8-8e0d-ea386bec9cc5.png)
![2222222222222222](https://user-images.githubusercontent.com/13044161/49556449-c567c180-f93e-11e8-8579-6d824bd5a7f5.png)
![3333333333](https://user-images.githubusercontent.com/13044161/49556450-c567c180-f93e-11e8-85e9-9a2792f6e4d7.png)
![44444444444444](https://user-images.githubusercontent.com/13044161/49556451-c6005800-f93e-11e8-8b86-2e7d4d5be80f.png)

**Comment by SuperKe** [comment]
我这边也出现了这种，有时候会有控件的空指针，头皮发麻没看到原因，请教哈你是如何处理的呢？也是butterknife

**Comment by GoAheadComeOn** [comment]
我也没有头绪，我是在onCreateView里对ButterKnife做绑定的，如果是内存重启的话这里也会重新绑定的，这里也没有做异步操作，我也没想明白

**Comment by fengmlo** [comment]
同样遇到空指针问题，用ButterKnife绑定控件，在Button的点击事件中访问另一个View有一定几率报空指针异常，找不到原因

**Comment by GoAheadComeOn** [comment]
@fengmlo 我也不知道具体原因，可能是类似横竖屏切换view创建。

**Comment by fengmlo** [comment]
我是在Fragment中嵌套Fragment，在onViewCreated中去绑定的View，而且没有横竖屏切换，也没有后台切换的情况，页面一直在前台，这个时候去点击按钮，按钮点击事件中去访问EditText，有少量用户会报空指针。

**Comment by YoKeyword** [comment]
ButterKnife的控件解绑会让View的引用直接指向Null， 此时如果有异步任务的回调是操作View的话，即会发生空指针， 按这个思路可以排查下问题
