### ISSUE TITLE
Cannot access android.support.v4.app.BaseFragmentActivityApi16

### ISSUE THREAD

**Issue by zengjianxiong** [YoKeyword/Fragmentation#1053]
appcompat-v7 升级到28就出现Cannot access android.support.v4.app.BaseFragmentActivityApi16这个问题

**Comment by LeslieKoma** [comment]
> appcompat-v7 升级到28就出现Cannot access android.support.v4.app.BaseFragmentActivityApi16这个问题

你现在还出现这个问题吗？

**Comment by zengjianxiong** [comment]
![image](https://user-images.githubusercontent.com/13110953/49635705-92efbe80-fa3b-11e8-8e6f-faba24912385.png)
刚刚了一下还是有这个错误提示，好像是不影响编译，但是不知道有什么未知影响，只好降到27

**Comment by wsgaowxh** [comment]
> > appcompat-v7 升级到28就出现Cannot access android.support.v4.app.BaseFragmentActivityApi16这个问题
> 
> 你现在还出现这个问题吗？

您好，我也遇到这个问题了，使用的是2019年3月1日master分支的Lib，v7包降低到27就可以了，28的版本就会这样

**Comment by callhh** [comment]
遇到了同样问题，请问可以解决么？爆红看着难受~~

**Comment by WangcWj** [comment]
怎么解决啊?

**Comment by zengjianxiong** [comment]
> 怎么解决啊?
不知道 我现在不报红

**Comment by WangcWj** [comment]
莫名其妙的吗?

**Comment by YingRongQian** [comment]
有知道怎么解决的吗？

**Comment by zengjianxiong** [comment]
> 有知道怎么解决的吗？

 尝试一下 exclude group: 'com.android.support'

**Comment by YingRongQian** [comment]
> > 有知道怎么解决的吗？
> 
> 尝试一下 exclude group: 'com.android.support'

我把我本地的support包版本和compileSdkVersion一致就好了

**Comment by zengjianxiong** [comment]
> > > 有知道怎么解决的吗？
> > 
> > 
> > 尝试一下 exclude group: 'com.android.support'
> 
> 我把我本地的support包版本和compileSdkVersion一致就好了

我的也是莫名其妙的就好了

**Comment by RainYeS** [comment]
我把我本地的支持包版本和compileSdkVersion一致就好了

**Comment by Longalei** [comment]
supportLibVersion版本不一致，28.0上FragmentActivity直接继承ComponentActivity。而其下是BaseFragmentActivityApi16
