### ISSUE TITLE
getSwipeBackLayout().addSwipeListener(new SwipeBackLayout.OnSwipeListener()没有回调！！

### ISSUE THREAD

**Issue by lan888** [YoKeyword/Fragmentation#1057]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
无法复现，建议断点调试下
