### ISSUE TITLE
在一个Fragment中添加多个子Fragment好像会很卡，日志会报主线程工作太多的警告

### ISSUE THREAD

**Issue by AndroidXiaonan** [YoKeyword/Fragmentation#1058]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
首先架构上建议wechat Demo的方式，另外可以通过懒加载、减少层级来优化， 另外对一些模块可以再分一些Activity承载，不一定需要严格的单Activity
