### ISSUE TITLE
DialogFragment 一直出现在最上层  无论怎么start 切换页面

### ISSUE THREAD

**Issue by JohnsonJLi** [YoKeyword/Fragmentation#1059]
自己封装了 DialogFragment  APP内全部弹窗都用这个dialog
这些天把项目换成单activity, 发现弹窗一直出现在最上层. 
部分情况下 , 已经到了下一个页面可是上个页面的dialog还显示在最上层
dialog用的地方比较多 求大神指点

**Comment by JohnsonJLi** [comment]
APP中有一个功能 
APP进入后台或息屏后 n秒之后 需要重新登录,所以会start到登录页面
如果当前页面有DialogFragment的情况下 进入后台或者息屏 就会出现 在登录页面显示上个页面的Dialog

**Comment by Gundam0079** [comment]
我也想问这个  DialogFragment 一直出现在 Fragment栈顶是个比较囧的问题      希望是每个弹框显示在自己的fragment上
