### ISSUE TITLE
如果不使用进入动画，那么onEnterAnimationEnd会被执行两次

### ISSUE THREAD

**Issue by gavinboy** [YoKeyword/Fragmentation#106]
第一次是在onActivityCreated里面调用，第二次是在动画listener里面调用
所以SupportFragment的initAnim是不是应该这么写：
`if(!mEnterAnimFlag){
            mAnimHelper.enterAnim.setAnimationListener(new DebounceAnimListener(this));
        }`

**Comment by YoKeyword** [comment]
@gavinboy 太感谢了，确实是个BUG， 解决方式可以看commit:  [d011ea7](https://github.com/YoKeyword/Fragmentation/commit/d011ea72208f3445709d797c290feb92e6143a52)

大致原因是getNoAnim()得到的是同一个对象，这样操作的也是同一个对象～

太感谢了🙏    😊

**Comment by gavinboy** [comment]
@YoKeyword  能详细说明一下为什么得到同一个对象就会调用两次吗？

**Comment by YoKeyword** [comment]
````
mAnimHelper.enterAnim.setAnimationListener(new DebounceAnimListener(this));
````
这句代码给enterAnim设定的Listener，之前的代码，enterAnim的NoAnim对象其实也是popEnterAnim,exitAnim所指向的对象，所以popEnterAnim,exitAnim也同时绑定了这个Listener，所以其实不仅在加载Fragment时会调用一次onEnterAnimationEnd，其实在离开Fragment的时候，也会调用上一个Fragment的onEnterAnimationEnd()；

同时
````
 if (mAnimHelper.enterAnim == mAnimHelper.getNoAnim()) {
            mEnterAnimFlag = true;
 }
````
这行代码是不需要的，因为Listener里已经会调用了onEnterAnimationEnd()，所以删除了，这里也是调用2次的原因，不过在把AnimatorHelper 里的 if (noAnim == null) {....}删除之后，这行代码就没意义了，永远不会走进去，所以也索性删除了 😊
