### ISSUE TITLE
项目用到了多module，两个不相互的依赖的子module如何获取使用findChildFragment

### ISSUE THREAD

**Issue by zwonb** [YoKeyword/Fragmentation#1065]
项目用到了多module，两个不相互的依赖的子module如何获取使用findChildFragment
Class.forName 也不无法强转具体类型，因为没有依赖module 怎么破？

**Comment by YoKeyword** [comment]
2个Module更建议使用2个宿主Activity隔离，  module通信可以参考路由等方案
