### ISSUE TITLE
Pop failure!

### ISSUE THREAD

**Issue by mny459** [YoKeyword/Fragmentation#1069]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version :1.3.6
* Support-v4 version: 
* Logs
```
E/Fragmentation: Pop failure! Can't find FragmentTag:(包名省略).DeviceOperationFragment in the FragmentManager's Stack.
```
* Screenshots

![返回栈中Fragment](https://user-images.githubusercontent.com/24559456/50584458-9e9f9b00-0eaa-11e9-805e-befb4ac97905.png)

求教原因
**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by RockyQu** [comment]
怎么解决的？
