### ISSUE TITLE
请问SupportFragment的生命周期

### ISSUE THREAD

**Issue by leibown** [YoKeyword/Fragmentation#107]
我想问下：
fragmentA.start(fragmentB);
用这种启动方式时，fragmentA所要执行的生命周期方法是什么，还有当fragmentB退出返回到fragmentA时fragmentA所要执行的生命周期方法是什么呀？谢谢

**Comment by leibown** [comment]
现在我测试是fragmentA在启动fragmentB时，fragmentA是不会执行onPause方法的，fragmentB退出返回时，fragmentA也不会执行onResume方法

**Comment by YoKeyword** [comment]
Fragment的add+show/hide 启动一个新Fragment时，回调onHiddenChanged()方法；
onResume和onPause方法是跟随宿主Activity的；

另外提醒：如果在ViewPager+Adapter中使用Fragment，Fragment之间的切换是回调setUserVisibleHint()
