### ISSUE TITLE
我有一个webview页面，返回时闪屏

### ISSUE THREAD

**Issue by OsbornWJ** [YoKeyword/Fragmentation#1074]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by cocowobo** [comment]
我使用的了一些内置了webview的 页面,没有闪烁.我的app虽然没有很多机型跑过,但是手头的机型没出现返回webview.闪烁
