### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by adaonder** [YoKeyword/Fragmentation#1075]
# AndroidX

Error: Didn't find class "android.support.constraint.ConstraintLayout"

Because this library andrpid api 28 not updated

**Comment by leeyun** [comment]
检查下gradel.proprties中是否有开启兼容模式android.useAndroidX=true

**Comment by apefuu** [comment]
https://github.com/apefuu/fragmentation-androidx 
I finished it

**Comment by YoKeyword** [comment]
[androidx support](https://github.com/YoKeyword/Fragmentation#how-do-i-use-fragmentation)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
@apefuu Thx
