### ISSUE TITLE
两个fragment互相通过singleTask的方式启动，回退栈异常

### ISSUE THREAD

**Issue by JoahYau** [YoKeyword/Fragmentation#1076]
* Library version：1.3.6
* Support-v4 version：25.4.0
* Logs
* Screenshots：
![image](https://user-images.githubusercontent.com/17685583/51291944-f52cdd80-1a43-11e9-825a-4c6e50601f3c.png)
![image](https://user-images.githubusercontent.com/17685583/51292038-56ed4780-1a44-11e9-938a-5ec2fb73cbaa.png)

两个fragment通过SingleTask方式相互启动时（A.start(B, singleTask; B.start(A, singleTask);），会出现这种带星号的情况（100%），然后一路点返回，不带星号的fragment全部出栈后，显示黑色的界面。

请问带星号这种是什么原因引起的？应该怎样处理？

**Comment by xwdz** [comment]
带星号则说明在`loadRootFragment`没有将该Fragment加入回退栈，也是导致出栈后黑屏的原因。
将`loadRootFragment(id, xxx.newInstance(), true, false);`第三个参数标记为true即可。
