### ISSUE TITLE
onEnterAnimationEnd 有些情况不会执行

### ISSUE THREAD

**Issue by gavinboy** [YoKeyword/Fragmentation#108]
当onCreateAnimation走到`super.onCreateAnimation 这个分支时，相当于返回一个null，导致onEnterAnimationEnd不执行

**Comment by YoKeyword** [comment]
你的场景是在 哪种情况 走到了 super.onCreateAnimation呢?

**Comment by gavinboy** [comment]
PageChildFragment

**Comment by YoKeyword** [comment]
哦 想起来了～ 这个之前也有小伙伴告诉我～ 
虽然onEnterAnimationEnd()在ViewPager里是无意义的，ViewPager里的Fragment本身是无动画的；
不过确实应该也需要去调用，感谢提醒 🙏

**Comment by YoKeyword** [comment]
已修复～  在super.onCreateAnimation前把mNoneEnterAnimFlag字段(原mEnterAnimFlag字段)标识为true即可～
