### ISSUE TITLE
onCreateView不存在

### ISSUE THREAD

**Issue by MayIGetKepler** [YoKeyword/Fragmentation#1080]
项目升级到AndroidX，不能重写onCreateView方法
![image](https://user-images.githubusercontent.com/45789654/51727053-25f4be80-20a5-11e9-971d-167e6d20bfc2.png)

**Comment by MayIGetKepler** [comment]
问题出在ButterKnife，自己没搞清楚，见笑了

**Comment by yang8807** [comment]
怎么解决的？
