### ISSUE TITLE
微信demo中回退栈的问题

### ISSUE THREAD

**Issue by crmemo** [YoKeyword/Fragmentation#1084]
你好，在1.3.6微信demo中，进入DetailFragment界面，然后按右下角的button并快速按手机back键返回，重复这两个操作若干次后发现MainFragment到了栈顶，导致在DetailFragment中按回退键响应的是MainFragment。

![bcbabd21c22d89f409a993796b108ed](https://user-images.githubusercontent.com/43345798/51836677-0a571580-233c-11e9-960c-3611512ba875.jpg)

![image](https://user-images.githubusercontent.com/43345798/51836699-17740480-233c-11e9-9e34-890d557dd519.png)

**Comment by cocowobo** [comment]
你是不是手机卡炖,然后运行两个事务之间的顺序错误,导致了上述情况的发生.我的手机怎么也试不出来,可能运行比较快吧.感觉你这就是两个异步任务执行,时长有误.

**Comment by cocowobo** [comment]
我快速点击导致了多个detailFragment一次叠加,这种问题我通过快速点击拦截处理了.在我的项目中

**Comment by crmemo** [comment]
> 我快速点击导致了多个detailFragment一次叠加,这种问题我通过快速点击拦截处理了.在我的项目中

我用小米mix2（有虚拟导航键）和vivo nex（全面屏手势）测试了下都有这个问题，应该不是性能的问题，操作就是点击蓝色按钮再快速返回有概率出现。

你可以试一下从进入demo->微信demo->更多->detail->点击蓝色按钮->一直回退到app主页->再从新回到detail界面，然后mainfragment就在栈顶了。

**Comment by ckpkover** [comment]
在防知乎demo，商店左侧的分类，我快速点击切换，会挂掉。。。可能是测试机太老？

**Comment by crmemo** [comment]
#1066 是androidx的问题
