### ISSUE TITLE
loadRootFragment加载Fragment后使用findFragment却找不到这个Fragment

### ISSUE THREAD

**Issue by qianshengta** [YoKeyword/Fragmentation#1085]
* Library version ： 1.3.6
* Support-v4 version  ： 28.0.0
* Logs
* Screenshots
我在使用这个库后，就开始出现
**The specified child already has a parent. You must call removeView() on the child's parent first**
这个错误，后来跟别的开发者交流，他们建议我在每次loadRootFragment之前都先findFragment/findChildFragment下，如果得到的是空的再加载，否则就不去加载，他们认为我这个可能是重复加载了的问题。我也这样做了，但是我测试后发现
```
   loadRootFragment(MainFragment.newInstance());
        if (findFragment(MainFragment.class) == null)
            loadRootFragment(MainFragment.newInstance());
```
我在loadRootFragment了MainFragment之后，使用findFragment(MainFragment.class) 判断，他还是得到的是空的，还是会去走if之后的loadRootFragment(MainFragment.newInstance());，依然会报
|**The specified child already has a parent. You must call removeView() on the child's parent first**

**(注：这个错误不是在我加载界面的时候报出来的，而是我在点击手机虚拟返回按键，finish掉这个Activity后报的，)**

使用场景是我Activity在loadRootFragment(MainFragment.newInstance());后，点击按钮启动Activity2，
Activity2中会调用
```
   //以下是测试代码，真正项目不会这样去写的
   loadRootFragment(MainFragment.newInstance());
        if (findFragment(MainFragment.class) == null)
            loadRootFragment(MainFragment.newInstance());
```

到目前为止一切正常，但是我点击虚拟返回按键后，就是有异常
|**The specified child already has a parent. You must call removeView() on the child's parent first**

**Comment by cocowobo** [comment]
深入查看源码,loadRootFragment(MainFragment.newInstance()); ,不是立即生效的.是事务,所以你立即判断肯定是空,你请延时1秒查看就不空了

**Comment by YoKeyword** [comment]
可以使用`post( () -> your fragment action)`
