### ISSUE TITLE
内存不足导致fragment被回收后，showHideFragment没任何反应，没有切换页面

### ISSUE THREAD

**Issue by qianshengta** [YoKeyword/Fragmentation#1087]
* Library version  **1.3.6**
* Support-v4 version  **28.0.0**
* Logs
* Screenshots

我的界面是一个主界面，下面四个tab+FrameLayout，使用loadMultipleRootFragment，然后通过showHideFragment切换。
我的问题是这样的，在app到后台后，我去运行其他软件，在一段时间，应该是内存不足导致app的界面被回收了。然后我将这个app从后台切的前台，这时候点击下面的tab，就是使用showHideFragment的时候，没有任何反应，界面没有切换。但是我点击当前页面的按钮，使用 baseActivity.start();开启其他页面却是正常的。

```

        mFragments = new ISupportFragment[4];
        if (findChildFragment(HomeFragment.class) == null) {
            mFragments[0] = HomeFragment.newInstance(listener);
            mFragments[1] = InformationFragment.newInstance();
            mFragments[2] = OrderFragment.newInstance();
            mFragments[3] = MineFragment.newInstance();
            current = mFragments[0];
            loadMultipleRootFragment(0, mFragments);
        }
 switch (view.getId()) {
            case R.id.main_rb_home:
                showHideFragment(mFragments[0], current);
                current = mFragments[0];
                mainRbHome.setChecked(true);
                break;
            case R.id.main_rb_information:
                showHideFragment(mFragments[1], current);
                current = mFragments[1];
                mainRbInformation.setChecked(true);
                break;
            case R.id.main_rb_order:
                showHideFragment(mFragments[2], current);
                current = mFragments[2];
                mainRbOrder.setChecked(true);
                break;
            case R.id.main_rb_mine:
                showHideFragment(mFragments[3], current);
                current = mFragments[3];
                mainRbMine.setChecked(true);
                break;
        }
```

**Comment by ckpkover** [comment]
这个不是很明显？

        SupportFragment firstFragment = findFragment(ZhihuFirstFragment.class);
        if (firstFragment == null) {
            mFragments[FIRST] = ZhihuFirstFragment.newInstance();
            mFragments[SECOND] = ZhihuSecondFragment.newInstance();
            mFragments[THIRD] = ZhihuThirdFragment.newInstance();
            mFragments[FOURTH] = ZhihuFourthFragment.newInstance();

            loadMultipleRootFragment(R.id.fl_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD],
                    mFragments[FOURTH]);
        } else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题

            // 这里我们需要拿到mFragments的引用
            mFragments[FIRST] = firstFragment;
            mFragments[SECOND] = findFragment(ZhihuSecondFragment.class);
            mFragments[THIRD] = findFragment(ZhihuThirdFragment.class);
            mFragments[FOURTH] = findFragment(ZhihuFourthFragment.class);
        }

**Comment by qianshengta** [comment]
嗯 因为这句话
 **// 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题**
我以为库里已经做了处理了 所以我就没加上了，后来补进去了就好了

**Comment by ckpkover** [comment]
这个库稳定性怎么样？关注这个库很久了，只是没有深入研究。有没有很难处理的奇怪bug?
