### ISSUE TITLE
_mActivity 类型不太合理

### ISSUE THREAD

**Issue by vzhilong** [YoKeyword/Fragmentation#1088]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

比如我在SupportFragment中，无法调用SupportActivity的方法，但是根据代码判断其实SupportFragment._mActivity就是SupportActivity类型。

**Comment by YoKeyword** [comment]
v1.3.7已优化为`SupportActivity`  :)
