### ISSUE TITLE
Handle back from child fragment!!!

### ISSUE THREAD

**Issue by AnkurJagani** [YoKeyword/Fragmentation#109]
In MainActivity below is code for handling notification(s).

```javascript
@Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        try {
            String contactNumber = intent.getStringExtra("contactNumber");
            if (AppGlobal.isStringValid(contactNumber)) {
                start(ChatFragment.newInstance(contactNumber));
            }
        } catch (Exception e) {
            AppGlobal.printLog(e);
        }
    }
```

In ChatFragment below is code for custom implemented back button.
```javascript
     case R.id.rlBack: 
                hideSoftInput();
                pop();
                break;

```

**Expected Result:** 
1. I need to display root fragment of same tab. e.g. Should display `RecentChats` while back  from `ChatFragment`. 

**Current Result:**
1. It is closing app.

**Query:**
1. Is there any method we can give parent fragment to child fragment? e.g. Assign `RecentChatFragment.java` to `ChatFragment.java`

_Thanks in advance._

**Comment by YoKeyword** [comment]
Hi, can you show me your "Stack Dialog" or "Stack Log"?   (`showFragmentStackHierarchyView()` or `logFragmentStackHierarchy(TAG)`)

`pop()`  should not cause app to close.

I think you can refer to the second demo.（demo_wechat）
![image](https://cloud.githubusercontent.com/assets/9691640/19181143/99bad730-8c9d-11e6-8da7-344c34a9de2a.png)

**Comment by AnkurJagani** [comment]
This is when it is normal.

![device-2016-10-07-165859](https://cloud.githubusercontent.com/assets/7710697/19188510/c09505f8-8caf-11e6-9118-ed0a29e104b2.png)

This is when i comes from notification bar.

![device-2016-10-07-170045](https://cloud.githubusercontent.com/assets/7710697/19188522/d1ab8d80-8caf-11e6-860b-6518cb01b4d7.png)

Please let me if you need any thing else.

**Comment by YoKeyword** [comment]
````java  
//  MainActivity.java:
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);

        // 1. show ChatContainerFragment
        showHideFragment(chatContainerFragment, preContrainerFragment);

        // 2. EventBus -> ChatListFragment
        EventBus.getDefault().post(new StartChatFragmentEvent());
    }

//  ChatListFragment.java: 
    @Subscribe
    public void onEvent(StartChatFragmentEvent event){
       start(ChatFragment.newInstance(xx));
    }
````
> loadRootX()..，the target is child fragment.
startX()，popX()，find/getX()..，the target is brother fragment.
popChildX()，find/getChildX()..，the target is child fragment.


For communication between Fragments, I recommend using EventBus.
