### ISSUE TITLE
在xml里面静态放个子fragment，返回时该xml对应的fragment没有出场动画了

### ISSUE THREAD

**Issue by terry111zc** [YoKeyword/Fragmentation#1091]
Fragment A的布局文件为

- <LinearLayout
-                     android:layout_width="match_parent"
-                     android:layout_height="wrap_content"
-                     android:background="@color/white"
-                     android:orientation="vertical">
-                     <fragment
-                         android:id="@+id/headFragment"
-                         android:name="com.***.HeadFragment"
-                         android:layout_width="match_parent"
-                         android:layout_height="wrap_content" />
- 
-                 </LinearLayout>

其中HeadFragment里面没有做耗时操作；
当退出Fragment A时，没有出场动画了，如果把xml里的HeadFragment删除掉，返回就有动画了，请问一下，这个有可能是什么问题呢？

**Comment by ckpkover** [comment]
估计是
HeadFragment没有被管理起来
