### ISSUE TITLE
removeTopFragment函数没有必要

### ISSUE THREAD

**Issue by weikaiyun** [YoKeyword/Fragmentation#1094]
最近研究了一下 FragmentManager 源代码，发现在Fragmentation框架里：

/**
     * Pop
     */
    void pop(final FragmentManager fm) {
        enqueue(fm, new Action(Action.ACTION_POP, fm) {
            @Override
            public void run() {
                handleAfterSaveInStateTransactionException(fm, "pop()");
                FragmentationMagician.popBackStackAllowingStateLoss(fm);
                removeTopFragment(fm);
            }
        });
    }

    private void removeTopFragment(FragmentManager fm) {
        try { // Safe popBackStack()
            ISupportFragment top = SupportHelper.getBackStackTopFragment(fm);
            if (top != null) {
                fm.beginTransaction()
                        .setTransition(FragmentTransaction.TRANSIT_FRAGMENT_CLOSE)
                        .remove((Fragment) top)
                        .commitAllowingStateLoss();
            }
        } catch (Exception ignored) {

        }
    }

在pop()函数里调用removeTopFragment是没有必要的，FragmentationMagician.popBackStackAllowingStateLoss(fm)已经实现了pop操作，不知道为啥还要remove 求解释

**Comment by she246** [comment]
你好，最近我想把这个框架使用到这个项目中，正在学习分析，有些地方想请教一下，能否加个好友

**Comment by weikaiyun** [comment]
可以啊 可以一起讨论学习  加微信吧  18671819740
