### ISSUE TITLE
我在使用的时候,view层级太多,start时报空

### ISSUE THREAD

**Issue by Richair** [YoKeyword/Fragmentation#1096]
比如我当前一个主的Fragement ,里边有4个子A  B  C  D,A下边有两个子Fragment A1  A2,A1下边又包含两个子Fragment A11  A12,这个时候我想从A11开启一个新的Fragment 调用 start();方法直接包空指针!

**Comment by YoKeyword** [comment]
栈层级问题，检查栈层级，参考Demo或[wiki](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager)

**Comment by YoKeyword** [comment]
栈层级问题，建议排查栈层级，参考Demo、[wiki](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager)
