### ISSUE TITLE
大哥，赶紧来支持一下androidx

### ISSUE THREAD

**Issue by xiaoyunfei** [YoKeyword/Fragmentation#1097]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

android.support 包后续google就不对它提供更新了，建议换成androidX

**Comment by DzwsGo** [comment]
同求支持

**Comment by TyraelYoung** [comment]
不支持androidx。。。没法用

**Comment by YoKeyword** [comment]
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation/blob/androidx/README_CN.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
