### ISSUE TITLE
Activity中的Fragment启动新的Fragment,新的Fragment闪一下,但是不会出现

### ISSUE THREAD

**Issue by xuqinghao1991** [YoKeyword/Fragmentation#1098]
框架版本:1.3.6
Bundle bundle = new Bundle();
TeacherDuXueDetaiFragment teacherDuXueDetaiFragment = TeacherDuXueDetaiFragment.newInstance();
teacherDuXueDetaiFragment.setArguments(bundle);
start(teacherDuXueDetaiFragment);或者
startWithPopTo(teacherDuXueDetaiFragment, TeacherDuXueDetaiFragment.class, false);
都不行,请问是怎么回事

**Comment by hustsqh** [comment]
我也遇到这个问题，你有解决办法了吗？

**Comment by xuqinghao1991** [comment]
TeacherDuXueDetaiFragment teacherDuXueDetaiFragment = TeacherDuXueDetaiFragment.newInstance();
                                    teacherDuXueDetaiFragment.setArguments(bundle);
                                    ((MainFragment) getParentFragment().getParentFragment()).startBrotherFragment(teacherDuXueDetaiFragment);

**Comment by xuqinghao1991** [comment]
> 我也遇到这个问题，你有解决办法了吗？

 TeacherDuXueDetaiFragment teacherDuXueDetaiFragment = TeacherDuXueDetaiFragment.newInstance();
                                    teacherDuXueDetaiFragment.setArguments(bundle);
                                    ((MainFragment) getParentFragment().getParentFragment()).startBrotherFragment(teacherDuXueDetaiFragment);

**Comment by hustsqh** [comment]
我的是startWithPopTo和startWithPop出问题，改了源码，可以了，但是fragment退出动画没了，需要再研究一下。

**Comment by hustsqh** [comment]
> 我的是startWithPopTo和startWithPop出问题，改了源码，可以了，但是fragment退出动画没了，需要再研究一下。

`
    /**
     * Start the target Fragment and pop itself
     */
    void startWithPop(final FragmentManager fm, final ISupportFragment from, final ISupportFragment to) {
        enqueue(fm, new Action(Action.ACTION_POP_MOCK) {
            @Override
            public void run() {
                ISupportFragment top = getTopFragmentForStart(from, fm);
                if (top == null) {
                    Log.d(TAG,"There is no Fragment in the FragmentManager, maybe you need to call loadRootFragment");
                    throw new NullPointerException("There is no Fragment in the FragmentManager, maybe you need to call loadRootFragment() first!");
                }

                int containerId = top.getSupportDelegate().mContainerId;
                bindContainerId(containerId, to);

                handleAfterSaveInStateTransactionException(fm, "popTo()");
                FragmentationMagician.popBackStackAllowingStateLoss(fm);
                FragmentationMagician.executePendingTransactionsAllowingStateLoss(fm);
                removeTopFragment(fm);
//                top.getSupportDelegate().mLockAnim = true;
//                if (!FragmentationMagician.isStateSaved(fm)) {
//                    mockStartWithPopAnim(SupportHelper.getTopFragment(fm), to, top.getSupportDelegate().mAnimHelper.popExitAnim);
//                }
//                Log.d(TAG, "run: removeTopFragment");
//
//                FragmentationMagician.popBackStackAllowingStateLoss(fm);
//                FragmentationMagician.executePendingTransactionsAllowingStateLoss(fm);
//                mHandler.post(new Runnable() {
//                    @Override
//                    public void run() {
//                        FragmentationMagician.reorderIndices(fm);
//                    }
//                });
            }
        });
`

**Comment by YoKeyword** [comment]
栈层级问题， 建议检查栈层级，参考Demo
