### ISSUE TITLE
关闭fragment的动画怎么改呀

### ISSUE THREAD

**Issue by Spoon2014** [YoKeyword/Fragmentation#11]
关闭fragment的动画怎么改呀

**Comment by YoKeyword** [comment]
Activity的复写onCreateFragmentAnimator() 可以控制Activity内全部Fragment的动画；
Fragment里复写onCreateFragmentAnimation() 可以控制该Fragment的动画（优先级比Activity的高）

动画对象是：FragmentAnimator， 它有4个属性：
enter:  Fragment的进栈动画
exit:  Fragment的出栈动画(pop时的)
popEnter:  下一个Fragment出栈时，该Fragment从hide状态变为show状态时的动画
popExit：下一个Fragment进栈时，该Fragment的从show变为hide状态时的动画
