### ISSUE TITLE
可以把文档写的更全一些。👍 

### ISSUE THREAD

**Issue by wushaoge** [YoKeyword/Fragmentation#110]
可以把文档写的更全一些。只看懂了loadRootFragment、loadMultipleRootFragment、startWithPop、start,其他的startWithSharedElement、startForResultWithSharedElement..没太懂什么意思 👍

**Comment by YoKeyword** [comment]
嗯嗯 感谢建议，会争取把文档描述清晰简洁～
可以参考demo，三个demo中 大部分Fragment场景上都有示例 ：)
