### ISSUE TITLE
ButterKnife空指针问题

### ISSUE THREAD

**Issue by SuperKe** [YoKeyword/Fragmentation#1101]
在onCreateView中bindView在onSupportVisible请求接口，有可能会报控件空指针

**Comment by YoKeyword** [comment]
`onSupportVisible()`是post到主线程消息队列的，时机晚于`onCreateView `

> 在onCreateView中bindView在onSupportVisible **请求接口**

“请求接口” 排查是否因关闭页面，而请求还在发送中，导致解绑View的butterKnife导致空指针； 

解决方案：在关闭页面是取消请求
