### ISSUE TITLE
你好，我是傅令杰，在慕课网讲课用的您的框架，带来了几千粉丝。我想帮咱开源社区做点贡献，也是责任。可否让我开个分支，把依赖全部替换成androidx，这样也节省了你很多心力了，分支就叫fragmentation-androidx，您看可以吗

### ISSUE THREAD

**Issue by apefuu** [YoKeyword/Fragmentation#1107]
### 这里有几点必须要做的
- 现在全面拥抱androidx了，重构工作不算太麻烦，作为公司主架构，觉得可以胜任
- 我现在至少有好几千个学生，我都会推荐他们您的库，但是现在遇到androidx的不兼容问题，挺尴尬的
- 很希望能为大家做点贡献，一点点就好，比如完成fragmentation-androidx的重构

**Comment by oarage** [comment]
傅老师您好，我在慕课网上买了您的课程，跟着您使用了fragmention，现在个问题挺急的，但作者还没有回复，请您空了帮我解惑：

前提：Activity通过start() 或 extraTransaction().setTag(tag).start() 打开了5个fragment
大致的任务栈如下：Activity
                                ->fragment1
                                ->fragment2
                                ->fragment3
                                ->fragment4
                                ->fragment5
                                
在第5个fragment中点击按钮，跳转到第6个fragment，同时关闭3,4,5这三个fragment
执行后任务栈如下：Activity
                                ->fragment1
                                ->fragment2      
                                ->fragment6

我的实现方式：
A、因为关闭fragment只能从最顶层一个一个的pop，我关闭fragment3，4，5的时候通过调用三次pop，然后再打开fragment6
问题：这样会造成有三次关闭动画和一次打开动画，效果不好，pass掉

B、让Activity通过extraTransaction().setTag(tag).start() 方式打开fragment，并为每个fragment设置tag
     点击按钮返回的时候，找到fragment2的tag，然后再调用extraTransaction().popTo(tag, false)，最后再打开fragment6
问题：这次只有一次关闭动画和一次打开动画，动画依然不自然

我要的效果是点击按钮的时候，先打开fragment6，然后再在后台静默关闭fragment3,4,5，请问这样如何实现？

**Comment by oarage** [comment]
我们目前项目是混合开发，使用的是多Activity+多Fragment实现的，除架构外全部使用H5开发，打开关闭Fragment都是通过js控制的，上面的那个问题，我是在第5个Fragment中，先关关最后三个Fragment,然后再调用的 window.location.href = 'detail/detail' 来跳转到第6个Fragment

**Comment by apefuu** [comment]
> 傅老师您好，我是您慕课网上的学生，跟着您使用了fragmention，现在有个问题，但作者还没有回复，请您空了帮我解惑：
> 
> 前提：Activity通过start() 或 extraTransaction().setTag(tag).start() 打开了5个fragment
> 大致的任务栈如下：Activity
> ->fragment1
> ->fragment2
> ->fragment3
> ->fragment4
> ->fragment5
> 
> 在第5个fragment中点击按钮，跳转到第6个fragment，同时关闭3,4,5这三个fragment
> 执行后任务栈如下：Activity
> ->fragment1
> ->fragment2
> ->fragment6
> 
> 我的实现方式：
> 方式一、因为关闭fragment只能从最顶层一个一个的pop，我关闭fragment3，4，5的时候通过调用三次pop，然后再打开fragment6
> 问题：这样会造成有三次关闭动画和一次打开动画，效果不好，pass掉
> 
> 方式二、让Activity通过extraTransaction().setTag(tag).start() 方式打开fragment，并为每个fragment设置tag ，点击按钮的时候，先找到fragment2的tag，然后再调用extraTransaction().popTo(tag, false)，最后再打开fragment6
> 问题：这次只有一次关闭动画和一次打开动画，动画依然不自然，pass掉
> 
> 我要的效果是点击按钮的时候，先打开fragment6，然后再在后台静默关闭fragment3,4,5，请问这样如何实现？

其实我的做法会比较简单粗暴，当然是图简单，作者肯定不希望这么做……我会在每次start的时候在MemoryStore加一个Stack，然后以自己的方式取出想要kill掉的fragment。当然，这里附带到还要清除一下Fragmentation的返回栈。我已经把androidx完全替换集成了，所以fork了一个androidx的库

**Comment by apefuu** [comment]
@作者 你好，我已经完全替换集成androidx了，顺便cleanup了一下你的代码。我fork了一下你的库并且提交了修改，有空了你去看看，如果合适，我可以删掉我的库然后merge进你的新branch里

**Comment by qinyang1018** [comment]
@oarage  有个popTo你可以看下

**Comment by oarage** [comment]
> @oarage 有个popTo你可以看下，不知道是不是你要的效果

嗯，谢谢回复，我的第二种方案就是使用的popTo来做的，相比较第一种方案要好一点，但是还存在关闭多个界面并打开新界面的时候，有一次关闭动画和一次打开动画的问题

**Comment by oarage** [comment]
> > 傅老师您好，我是您慕课网上的学生，跟着您使用了fragmention，现在有个问题，但作者还没有回复，请您空了帮我解惑：
> > 前提：Activity通过start() 或 extraTransaction().setTag(tag).start() 打开了5个fragment
> > 大致的任务栈如下：Activity
> > ->fragment1
> > ->fragment2
> > ->fragment3
> > ->fragment4
> > ->fragment5
> > 在第5个fragment中点击按钮，跳转到第6个fragment，同时关闭3,4,5这三个fragment
> > 执行后任务栈如下：Activity
> > ->fragment1
> > ->fragment2
> > ->fragment6
> > 我的实现方式：
> > 方式一、因为关闭fragment只能从最顶层一个一个的pop，我关闭fragment3，4，5的时候通过调用三次pop，然后再打开fragment6
> > 问题：这样会造成有三次关闭动画和一次打开动画，效果不好，pass掉
> > 方式二、让Activity通过extraTransaction().setTag(tag).start() 方式打开fragment，并为每个fragment设置tag ，点击按钮的时候，先找到fragment2的tag，然后再调用extraTransaction().popTo(tag, false)，最后再打开fragment6
> > 问题：这次只有一次关闭动画和一次打开动画，动画依然不自然，pass掉
> > 我要的效果是点击按钮的时候，先打开fragment6，然后再在后台静默关闭fragment3,4,5，请问这样如何实现？
> 
> 其实我的做法会比较简单粗暴，当然是图简单，作者肯定不希望这么做……我会在每次start的时候在MemoryStore加一个Stack，然后以自己的方式取出想要kill掉的fragment。当然，这里附带到还要清除一下Fragmentation的返回栈。我已经把androidx完全替换集成了，所以fork了一个androidx的库

@apefuu 傅老师，我按您说的操作了一下，发现能达到我需要的效果，但是删除Fragmention返回栈这一步不知道如何做，能贴下具体的代码吗？
我的代码如下：

private val mFmtTagStack = Stack<String>()

添加Fragment：
    val tag = generateFmtTag()
    mFmtTagStack.add(tag)
    extraTransaction()
          .setTag(tag)
           .start(WebPageFmt.show(mAppId, event.url))

删除Fragment：
        if (supportFragmentManager.backStackEntryCount > 1) {
            mFmtTagStack.pop()
            pop()
        } else {
            mFmtTagStack.clear()
            finish()
        }           

点击按钮，删除前三个fragment并打开新的Fragment6时：
        if (event.closeCount < supportFragmentManager.backStackEntryCount) {
                    if (event.closeCount > 1) {
                        val removeTags = ArrayList<String>()
                        for (i in 1..event.closeCount) {
                            removeTags.add(mFmtTagStack.pop())
                        }
                        for (tag in removeTags) {
                            val findFragment = SupportHelper.findFragment<WebPageFmt>(supportFragmentManager, tag)
                            supportFragmentManager.beginTransaction()
                                    .remove(findFragment)
                                    .commit()
                            //TODO 删除对应的Fragmention回退栈        
                        }
                        printInfo()
                    } else {
                        doBack()
                    }
                } else {
                    finish()
                }

**Comment by qinyang1018** [comment]
@oarage  不好意思 昨天看的有些急没看见你还要做新的跳转 那你尝试用下startWithPopTo

**Comment by oarage** [comment]
> @oarage 不好意思 昨天看的有些急没看见你还要做新的跳转 那你尝试用下startWithPopTo

@qinyang1018 你好，我目前流程是通过js来控制Fragment打开与关闭的，而且整个app关键代码只有两个类，一个WebpageActivity 和WebPageFragment ，每个模块打开一个WebPageActivity和多个WebPageFragment，这样的话我整个app里面只有一个WebPageFragment，startWithPopTo就使用不了了。

以我目前的状况，最完美的实现方式就是像傅令杰那样，自己维护一个Fragment的tag任务栈，每次start的时候同时设置tag并加入到tag任务栈中，当我要启动Fragment6并关闭Fragment3，4，5的时候，我可以通过start方法来打开Fragment6，并且静默关闭Fragment3，4，5。这样动画也比较自然。

上面的我实现后，只剩下最后一个问题了，就是自己关闭Fragment3，4，5的时候，不知道怎么删除对应的Fragmention的任务栈

**Comment by qinyang1018** [comment]
@oarage   hello  类似的需求之前我没有处理过，刚才看了下源码，只能说下自己的想法。你可以参考下
```
  FragmentationMagician.popBackStackAllowingStateLoss(fm, fragmentTag, flag);
```
是不是可以模拟源码中pop时的出栈方式呢？
[看下这个类是否对你有帮助  578行](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java)

**Comment by oarage** [comment]
> @oarage hello 类似的需求之前我没有处理过，刚才看了下源码，只能说下自己的想法。你可以参考下
> 
> ```
>   FragmentationMagician.popBackStackAllowingStateLoss(fm, fragmentTag, flag);
> ```
> 是不是可以模拟源码中pop时的清除回退栈方式呢？
> [看下这个类是否对你有帮助 578行](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java)

@qinyang1018 对对对，是这个，谢谢了，我再看看

**Comment by oarage** [comment]
> > @oarage hello 类似的需求之前我没有处理过，刚才看了下源码，只能说下自己的想法。你可以参考下
> > ```
> >   FragmentationMagician.popBackStackAllowingStateLoss(fm, fragmentTag, flag);
> > ```
> > 是不是可以模拟源码中pop时的清除回退栈方式呢？
> > [看下这个类是否对你有帮助 578行](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java)
> 
> @qinyang1018 对对对，是这个，谢谢了，我再看看

我现在是先打开Fragment6，然后过1000ms再静默关闭Fragment3，4，5
现在用下面的方法：
FragmentationMagician.popBackStackAllowingStateLoss(fm, fragmentTag, flag);
很奇怪，我看了源码，flag有两个值，
0：我传这个之后打印fragmention的栈是对的，但是页面出问题了，显示空白页
1(FragmentManager.POP_BACK_STACK_INCLUSIVE):传这个值后，Fragmentions会把我后打开的Fragment也关闭掉

**Comment by qinyang1018** [comment]
@oarage 我也没太细看  但我认为应该先结束在跳转吧？ 你这样应该存在事务的问题
[看看这个](https://github.com/YoKeyword/Fragmentation/blob/6a2406043a0443c91471dd90c99243900848bed7/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java#L185)

**Comment by ruanbaojun1105** [comment]
建议关掉此issue,有广告之嫌。

**Comment by YoKeyword** [comment]
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation/blob/androidx/README_CN.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
