### ISSUE TITLE
作者您好，我帮您把androidx全部集成了，https://github.com/apefuu/fragmentation-androidx 您看看

### ISSUE THREAD

**Issue by apefuu** [YoKeyword/Fragmentation#1108]
这是地址 https://github.com/apefuu/fragmentation-androidx

**Comment by qinyang1018** [comment]
之前就已经有人提过androidx的pr了  但是右右一直没上线 所以到现在也没有merge进来

**Comment by Aprilzzd** [comment]
优秀啊

**Comment by zhangjingfeng520** [comment]
请问如何依赖您的库 @apefuu

**Comment by Kimger** [comment]
你单纯处理mActive并不能解决适配androidx的问题，改成HashMap以后，回退栈的逻辑也需要修改的，你现在这样回退栈会有问题

**Comment by baiseng** [comment]
> 这是地址 https://github.com/apefuu/fragmentation-androidx

请问具体如何依赖使用

**Comment by apefuu** [comment]
> > 这是地址 https://github.com/apefuu/fragmentation-androidx
> 
> 请问具体如何依赖使用

这里我没有上传到jcenter，所以你clone下来，直接引用module就好

**Comment by apefuu** [comment]
> HashMap

确实是这样的，这个得之后去适配，或者改好merge进主分支里

**Comment by tyzero** [comment]
https://github.com/YoKeyword/Fragmentation/pull/1066
有Pr了，作者估计很忙没合并。。

**Comment by pingerx** [comment]
Fragmentation兼容AndroidX库：https://github.com/pingerx/Fragmentation

**Comment by TianGuisen** [comment]
@pingerx 下不下来啊.
ERROR: Failed to resolve: com.pingerx:fragmentation:andx.1.0.0
Show in Project Structure dialog
Affected Modules: app

**Comment by kevin321happy** [comment]
ViewPage+Fragment的情况下在Fragment栈中出现了SupportRequestManagerFragment？

**Comment by huhao1987** [comment]
> 你单纯处理mActive并不能解决适配androidx的问题，改成HashMap以后，回退栈的逻辑也需要修改的，你现在这样回退栈会有问题


这个问题可以暂时先把appcompat设置成1.0.2，这个版本的fragment还没使用hashmap，虽然只是临时解决办法，但是最少可以少改点代码

**Comment by nihaohebin** [comment]
java.lang.NoSuchFieldError: No instance field mActive of type Landroid/util/SparseArray; in class Landroidx/fragment/app/FragmentManagerImpl; or its superclasses (declaration of 'androidx.fragment.app.FragmentManagerImpl' appears in /data/app/com.atgc.mycs-QAe_Xfcb2Xw9xCXrHX6vMw==/base.apk)
        at androidx.fragment.app.FragmentationMagician.getActiveFragments(FragmentationMagician.java:153)
        at me.yokeyword.fragmentation.SupportHelper.findStackFragment(SupportHelper.java:139)
        at me.yokeyword.fragmentation.SupportHelper.findFragment(SupportHelper.java:114)

改了后开始出bug了，栈视图也是乱的。求大神解决一下。

**Comment by YoKeyword** [comment]
@apefuu 非常感谢，已接收 @privatez 的PR commits，
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation/blob/androidx/README_CN.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
