### ISSUE TITLE
fragment间传递参数

### ISSUE THREAD

**Issue by microDD** [YoKeyword/Fragmentation#111]
当两个fragment是通过show 和 hide 操作时，怎么从一个Fragment传递参数到另一个Fragment呢？因为setArguments() 在hide和show时无法使用，通过Activity间接传递又不太好，除了添加set和get方法外，还有什么好方法吗？

**Comment by YoKeyword** [comment]
再次安利一波EventBus ：)
Fragment之间交互建议用EventBus，Fragment的特性决定了 可以通过EventBus安全简洁的通信

**Comment by microDD** [comment]
but EventBus 会产生相当多的Event类呀...

**Comment by YoKeyword** [comment]
核心是高度解耦啊！ 
Event完全可以接收啊，等同于bean，而且数目大大小于bean数

**Comment by microDD** [comment]
谢啦，貌似也没什么好方法了。
