### ISSUE TITLE
Activity被销毁重走onCreate方法时会报错

### ISSUE THREAD

**Issue by CoderLinJ** [YoKeyword/Fragmentation#1110]
2390
2019-03-19 16:22:27

#402 java.lang.NullPointerException
Attempt to invoke virtual method 'void android.support.v4.app.Fragment.setNextAnim(int)' on a null object reference
出错堆栈

1	android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:773)
2	android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
3	android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
4	android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
5	android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
6	android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
7	android.os.Handler.handleCallback(Handler.java:873)
8	android.os.Handler.dispatchMessage(Handler.java:99)
9	android.os.Looper.loop(Looper.java:201)
10	android.app.ActivityThread.main(ActivityThread.java:6806)
11	java.lang.reflect.Method.invoke(Native Method)
12	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
13	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by YoKeyword** [comment]
v1.3.7
