### ISSUE TITLE
Depricated API usage

### ISSUE THREAD

**Issue by sathishmscict** [YoKeyword/Fragmentation#1111]
# Issues Guideline

Depricated api usage

* Library version : 1.3.6

* Logs
Deprecated API usage
MySupportFragment
Overrides deprecated method in 'androidx.fragment.app.Fragment'
'onAttach(android.app.Activity)' is deprecated
'enqueueAction(java.lang.Runnable)' is deprecated

* Screenshots

![image](https://user-images.githubusercontent.com/18158746/54666051-b92efb00-4b0e-11e9-9028-9989c3d75c10.png)

**Comment by YoKeyword** [comment]
[Click here](https://github.com/YoKeyword/Fragmentation#how-do-i-use-fragmentation)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
