### ISSUE TITLE
关于华为强制适配android Q版本问题

### ISSUE THREAD

**Issue by zuojianjian** [YoKeyword/Fragmentation#1113]
华为强制式适配android Q对现有框架不会有影响吧？
![微信截图_20190329181956](https://user-images.githubusercontent.com/20851340/55226757-b93aa380-5250-11e9-9242-f79e7be679d8.png)

**Comment by beilo** [comment]
应该没问题  这个主要是gradle中 compileSdkVersion targetSdkVersion升级到对应的版本。但是要做不少适配的功能和测试
