### ISSUE TITLE
不兼容androidx   dagger2注入报错  找不到v4包下的fragment

### ISSUE THREAD

**Issue by afeinoupcar** [YoKeyword/Fragmentation#1114]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation#how-do-i-use-fragmentation)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
