### ISSUE TITLE
Pop failure! Can't find MyFragment in the FragmentManager's Stack.

### ISSUE THREAD

**Issue by yangxiaoge** [YoKeyword/Fragmentation#112]
场景如下:  首页底部有4个 tab 按钮(默认展示第一个tab下的container对应fragment) , 当第一次进入首页时,
此时4个tab只有第一个是被点击过的,其他没有点击(也就是没有加载对应fragment), 如果我点击第一个tab页面内一个button想要跳转到其他tab页的子fragment(此时就报错:标题的错误),这时只会跳转到对应tab页下的container对应fragment! 急求解决办法  我的QQ号: 364804051

**Comment by YoKeyword** [comment]
操作了错误的栈层级啦～   QQ上说吧～
