### ISSUE TITLE
作者您好，咱们的项目什么时候适配androidX

### ISSUE THREAD

**Issue by Lvfulongmy** [YoKeyword/Fragmentation#1121]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by AskViky** [comment]
fragmentation底层用的support库，app上层用的androidx，结果SupportActivityDelegate.startWithPop()时新旧fragment出现重叠问题

**Comment by BuZhiheng** [comment]
对啊，啥时候适配androidx啊

**Comment by YoKeyword** [comment]
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation#how-do-i-use-fragmentation)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
