### ISSUE TITLE
java.lang.NullPointerException:Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference

### ISSUE THREAD

**Issue by sea5241** [YoKeyword/Fragmentation#1122]
java.lang.NullPointerException:Attempt to invoke virtual method 'int me.yokeyword.fragmentation.anim.FragmentAnimator.getEnter()' on a null object reference
--
6 me.yokeyword.fragmentation.helper.internal.AnimatorHelper.initEnterAnim(AnimatorHelper.java:63)
7 me.yokeyword.fragmentation.helper.internal.AnimatorHelper.notifyChanged(AnimatorHelper.java:29)
8 me.yokeyword.fragmentation.helper.internal.AnimatorHelper.<init>(AnimatorHelper.java:24)
9 me.yokeyword.fragmentation.SupportFragmentDelegate.onCreate(SupportFragmentDelegate.java:120)

用bugly收集日志会有这个报错，感觉是不是需要在获取到
mFragmentAnimator = savedInstanceState.getParcelable(TransactionDelegate.FRAGMENTATION_STATE_SAVE_ANIMATOR);
判断一下mFragmentAnimator是不是空的，是的话赋值，或者在使用mFragmentAnimator的时候判断空

**Comment by YoKeyword** [comment]
v1.3.7
