### ISSUE TITLE
你用的那个版本？@tyzero 真的升级到的1.1不行了，退回来好了^-^

### ISSUE THREAD

**Issue by snpmyn** [YoKeyword/Fragmentation#1125]
@tyzero 真的升级到的1.1不行了，退回来好了^-^

_Originally posted by @yuxiujuan in https://github.com/YoKeyword/Fragmentation/issues/1067#issuecomment-486203467_

**Comment by snpmyn** [comment]
你用的那个版本？

**Comment by tyzero** [comment]
旧版迟早不行。
我现在用这个pull request

https://github.com/YoKeyword/Fragmentation/pull/1066

顺便求up主早点回归，合并pr
@YoKeyword

**Comment by snpmyn** [comment]
你好！我下载源码后，为啥引用不到FragmentManagerImpl ？这个你遇到过吗？

**Comment by snpmyn** [comment]
解决了，谢谢！

**Comment by yxf0448** [comment]
> 解决了，谢谢！
你好怎么解决的呀？

**Comment by yxf0448** [comment]
> 解决了，谢谢！

你好请问怎么解决的呀？

**Comment by snpmyn** [comment]
FragmentManagerImpl的包名改为  androidx.app.fragment

**Comment by snpmyn** [comment]
> > 解决了，谢谢！
> 
> 你好请问怎么解决的呀？

FragmentManagerImpl的包名改为 androidx.app.fragment

**Comment by YoKeyword** [comment]
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation#how-do-i-use-fragmentation)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````

**Comment by snpmyn** [comment]
终于等到作者了。
