### ISSUE TITLE
作者 ,FragmentationMagician 的getActiveFragments方法能提供几个重载方法吗

### ISSUE THREAD

**Issue by wucomi** [YoKeyword/Fragmentation#1126]
fragmentManagerImpl.mActive

support之前版本是ArrayList,之后版本是SparseArray.
AndroidX是HashMap

**Comment by YoKeyword** [comment]
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation#how-do-i-use-fragmentation)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
