### ISSUE TITLE
使用SwipeBackFragment.start()出现的问题

### ISSUE THREAD

**Issue by OS9527** [YoKeyword/Fragmentation#113]
使用SwipeBackFragment.start(fragment),载入新fragment之后，侧滑退出不会触发上一个activity的onResume() 生命周期~~~(可能是我没用好吧,我自己开启事物，replace的时候是可以正常执行生命周期方法的)

**Comment by YoKeyword** [comment]
onResume()是在重新回到当前Activity时回调， Fragment之间的各种切换都是在宿主Activity之上的，Activity本身是一直可见的，是不会回调onResume哒～
