### ISSUE TITLE
侧滑时，滑到一半，取消侧滑，再点击返回键，右边会出现空白

### ISSUE THREAD

**Issue by Hell-And** [YoKeyword/Fragmentation#1130]
侧滑时，滑到一半，取消侧滑，再点击返回键，右边会出现空白
![Screenshot_2019-05-29-16-55-20-819_com whxh mobil](https://user-images.githubusercontent.com/24486325/58544144-4f7c4d00-8233-11e9-98dd-363c8abde0ad.png)

**Comment by cocowobo** [comment]
偶发，还是必发。偶发，就有可能你的手机debug造成的卡顿，瞬间，是会导致view绘制中断的

**Comment by Hell-And** [comment]
> 偶发，还是必发。偶发，就有可能你的手机调试造成的卡顿，瞬间，是会导致视图绘制中断的

必发 ，不过我已经找到问题了，开始我Support和SwipeBack都是 implements实现的，然后将Support改成继承就没这个问题了

**Comment by cocowobo** [comment]
你这骚操作呀，

**Comment by Hell-And** [comment]
> 我也遇到了这种情况，fragmentationx：1.0.1版本，你具体是怎么修复的啊？

我是因为都是使用的implement的Support和SwipeBack造成的，改成extend就好了

**Comment by ssyRo156** [comment]
原因在于 computeScroll 做了x轴偏移
![image](https://user-images.githubusercontent.com/18351963/126971129-8f5b07b8-e0ca-4ce5-82ed-f2a32c241d8e.png)

解决方法： 在基类Fragment onViewCreated 添加监听滑动state == 0 ， onDestroyView 取消滑动监听 如下：
![image](https://user-images.githubusercontent.com/18351963/127082456-ce3accd3-0a3e-4165-864f-58609f83cc25.png)


![image](https://user-images.githubusercontent.com/18351963/126971461-c1cfb2b0-3fa3-42b4-9af2-85457ccb1a40.png)
