### ISSUE TITLE
建议 支持 androidx 的分支和 master 分支保持同一版本号

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#1133]
# Issues Guideline

rt

**Comment by YoKeyword** [comment]
@zhenian Fragmentation的一个特别点是： 兼容support库的任意版本，所有可能存在一些commit是兼容`support 27.x / 28.0`等版本的，此时androidx可能并不需要修复； 反之可能存在兼容androidx的commit

所以考虑上述原因，版本号没有做统一  :)
