### ISSUE TITLE
Can't build project when use fragmentationx

### ISSUE THREAD

**Issue by HuuNguyen312** [YoKeyword/Fragmentation#1134]
# Issues Guideline
Hi @YoKeyword ,

I use your demo project with build.gralde,

    + implementation 'me.yokeyword:fragmentationx:1.0.0'
    + implementation 'me.yokeyword:fragmentationx-swipeback:1.0.0'
    + implementation 'me.yokeyword:eventbus-activity-scope:1.1.0'

    // Remove: 
    - api project(':fragmentation')
    - api project(':fragmentation_swipeback')
    - api project(':eventbus_activity_scope')

I can't build this project.

* Screenshots
![Capture](https://user-images.githubusercontent.com/9895294/59247951-30c28100-8c4b-11e9-8399-5ae5966ec6f6.PNG)

Please help me resolve it.
Thanks

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by mahramane** [comment]
Hi
Add fragmentationx_core library to Gradle. Then create the supportActivity and supportFragment class yourself.
[https://github.com/YoKeyword/Fragmentation/tree/androidx/fragmentation/src/main/java/me/yokeyword/fragmentation](url)
Of course, the androidx library version is not fully completed right now :(
@YoKeyword please update it.

**Comment by HuuNguyen312** [comment]
Hi @mahramane 

It's mean that fragmentationx doesn't include fragmentationx_core :(

**Comment by zhupengxiang** [comment]
![image](https://user-images.githubusercontent.com/17894209/59401768-6479e400-8dce-11e9-9f25-1abebb0fcfac.png)

I also encountered the same problem @HuuNguyen312

**Comment by senthelazy** [comment]
Well, I have the similar problem after import me.yokeyword.fragmentation.SupportActivity

Build Output shows:
**error: cannot access ISupportActivity
class file for me.yokeyword.fragmentation.ISupportActivity not found**

**Comment by YoKeyword** [comment]
I've fixed the dependency   :)
````gradle
implementation 'me.yokeyword:fragmentationx:1.0.1'
implementation 'me.yokeyword:fragmentationx-swipeback:1.0.1'
````

**Comment by HuuNguyen312** [comment]
Thank you :D
