### ISSUE TITLE
集成androidx后好多飘红

### ISSUE THREAD

**Issue by dary123** [YoKeyword/Fragmentation#1137]
![微信截图_20190613111526](https://user-images.githubusercontent.com/12826258/59401465-5a0b1a80-8dcd-11e9-8195-4025544e5f9f.png)
使用的是androidx分支：
// 如果想使用SwipeBack 滑动边缘退出Fragment/Activity功能，完整的添加规则如下：
    api 'me.yokeyword:fragmentationx:latest.release'
// swipeback基于fragmentation, 如果是自定制SupportActivity/Fragment，则参照SwipeBackActivity/Fragment实现即可
    api 'me.yokeyword:fragmentationx-swipeback:latest.release'
// Activity作用域的EventBus，通信更安全
    api 'me.yokeyword:eventbus-activity-scope:latest.release'

目前最新版是1.0.0

![微信截图_20190613111505](https://user-images.githubusercontent.com/12826258/59401462-57102a00-8dcd-11e9-9c2b-4688af9f694b.png)

**Comment by zhupengxiang** [comment]
我也有问题  ISupportfragment拿不到  导致的  我看里面是api 引用的fragment_core库

**Comment by senthelazy** [comment]
加 implementation 'me.yokeyword:fragmentationx-core:1.0.0'
试试

**Comment by zhupengxiang** [comment]
关键core是不给直接继承supportactivity用的

**Comment by YoKeyword** [comment]
依赖已经修复：
````gradle
implementation 'me.yokeyword:fragmentationx:1.0.1'
implementation 'me.yokeyword:fragmentationx-swipeback:1.0.1'
````
