### ISSUE TITLE
加载多个根Fragment建议

### ISSUE THREAD

**Issue by wk37** [YoKeyword/Fragmentation#114]
加载多个根Fragment目前只有loadMultipleRootTransaction()方法，建议重载此方法，把最后一个  可变参数  换成 list 和 数组

**Comment by YoKeyword** [comment]
现在的方法支持最后一个参数传入多个Fragment 以及 Fragment数组，List的话和数组差不多～

````java
  loadMultipleRootFragment(R.id.fl_tab_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD]);
// or
loadMultipleRootFragment(R.id.fl_tab_container, FIRST, mFragments);
````

**Comment by wk37** [comment]
感谢回答。另外关于 Fragment 的恢复机制，你demo里面是根据类名来的
            `mFragments[FIRST] = findFragment(ZhihuFirstFragment.class);`
            ` mFragments[SECOND] = findFragment(ZhihuSecondFragment.class);`
            `mFragments[THIRD] = findFragment(ZhihuThirdFragment.class);`
            `mFragments[FOURTH] = findFragment(ZhihuFourthFragment.class);`
但这四个 基础的 Fragment 其实内容差不多，如果我把他们弄成一个 泛型类 BaseTagFargment，实例化如下
         `if (savedInstanceState == null) { `
           ` for (int i = 0; i < 5 ; i++) {  `
            `    //  实例化 对象时 把 i  作为 TAG 传进去，用于标记不同对象  `
            `    mFragments[  i  ] = BaseFragment.newInstance(  i  );  `
           ` }  `
          `  loadMultipleRootFragment(R.id.main_framelayout, 1, mFragments); ` 
        `}else {  `
        `    //  此 ？？？ 处如何恢复  `
       `     mFragments[0] = findFragment(   ???   );  `
      `  }`

**Comment by YoKeyword** [comment]
不要这样写～
初始化时需要指明你new的Fragment，不能是BaseFragment；
找回时通过Class名找回是从安全角度考虑的，建议写明Class～即使FragmentManager有getFragments方法，但是在找回时还是建议通过class来进行进一步校验

**Comment by wk37** [comment]
好吧，只有接受建议了，谢谢
