### ISSUE TITLE
程序后台死亡，点击图标启动恢复流程，白屏

### ISSUE THREAD

**Issue by cocowobo** [YoKeyword/Fragmentation#1140]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

首先楼主的bug的，可以这么做

在首页activity中使用loadRootFragment 加载fragment的时候，这样写，
        if (findFragment(ZhuYeFragment.class) == null) {
            loadRootFragment(R.id.fl_container, ZhuYeFragment.newInstance());
        }
然后软件推到后台，进入系统设置 应用权限管理，然后把存储权限关了(首先你要已经请求了权限)，这个时候回到桌面，点击图标启动，你就会看到你没见过的白屏，点击stack红点，可以看到栈里面已经有了fragment了，但是却是白屏
这种写法是在@YoKeyword的demo中就是这样写的，YoKeyword说在库中处理了fragment的恢复问题，但是为什么恢复了后是白屏。我看了好久也不知道为什么。现在我只能将就着写成
    //if (findFragment(ZhuYeFragment.class) == null) {
     loadRootFragment(R.id.fl_container, ZhuYeFragment.newInstance());
     //}
这样不判断null，会在上面的模拟情况下出现重复加载fragment，但是没办法呀，多希望@YoKeyword大佬给出点解决方案，毕竟大佬对fragment太熟悉了

**Comment by ruanbaojun1105** [comment]
我也出现这问题 。。。大佬请帮忙~

**Comment by zhupengxiang** [comment]
我也是莫名其妙的白屏了  qiuji求解
![image](https://user-images.githubusercontent.com/17894209/60001567-5020cb80-9699-11e9-8c67-01117a1df82f.png)

**Comment by zhupengxiang** [comment]
@YoKeyword

**Comment by ruanbaojun1105** [comment]
我的情况是正常使用没问题，内存被系统清理后回到程序viewpager的5个fragment就白屏.....

**Comment by qinglok** [comment]
https://github.com/YoKeyword/Fragmentation/issues/1140#issue-456764086
我在Fragmentation中自带的Demo试了，没出现问题，并且该Demo也没有申请任何权限

我通常这么写, compileSdkVersion 28    targetSdkVersion 28
onCreate(Bundle saveInstance){
    if(saveInstance == null){
        loadRootFragment(R.id.fl_container, new Fragment());
    }
}

**Comment by cocowobo** [comment]
楼上你肯定不会出现这个问题，一般我们也没法模仿出后台杀死恢复的流程，我上面提出的关闭存储权限的方法完美复现。并且也是用的Demo，你没有请求权限坑定是没法复现这个的。

**Comment by zhupengxiang** [comment]
我的白屏什么情况  哥哥们

**Comment by qinglok** [comment]
我是开了“不保留活动”的，可以模拟出被回收的状态。
至于你们的白屏，还是要看源码才能分析。

**Comment by cocowobo** [comment]
开了 “不保留活动” 的，是不可以模拟出被回收的状态，我必须否定楼上的哥们，如果你只是因为开了 “不保留活动” 的，而以为你没有白屏的可能的话，那你就考虑的太少了，你可以按照我的逻辑去操作，这种白屏必显。

**Comment by qinyang1018** [comment]
@cocowobo   hello 无意间看到这个issues，所以尝试了下  我使用的是判断 `savedInstanceState==null`
没有出现你这个问题。 不知道你为什么要用class来判断呢？
```
       if (savedInstanceState == null) {
            loadRootFragment(R.id.fl_container, MainFragment.newInstance());
        }
```

**Comment by cocowobo** [comment]
@qinyang1018 首先你判断savedInstanceState 不等于空，是为了在有数据恢复的时候多走一次loadRootFragment，我使用class 来判断，是和你一样的作用，
同时你可以在作者的demo看到，作者的框架自己恢复了fragment，
现在问题是。作者的恢复fragment有问题，无法正确恢复，导致白屏

**Comment by qinyang1018** [comment]
@cocowobo   了解 ，但是我按你说的流程确实没有复现白屏的问题，会不会是兼容性的问题呢

**Comment by zhangjianwei1** [comment]
像是这种的话我也遇到了，好像是操作定位一些权限的时候，再次打开会出现重新加载的情况，这时候fragment还存在，但是视图已经被销毁了，我只能是不判断那个，每次进入都让他重新加载一次

**Comment by qienanxiang** [comment]
我之前也是偶尔会有白屏，一直没有办法重现，看到楼上说的自己修改权限，的确重现了，然后下载demo看了一下代码（发现自己else写法有问题），做了修改，重新修改权限，不在出现空白了，以下是demo的源码：
```
SupportFragment firstFragment = findFragment(ZhihuFirstFragment.class);
if (firstFragment == null) {
            mFragments[FIRST] = ZhihuFirstFragment.newInstance();
            mFragments[SECOND] = ZhihuSecondFragment.newInstance();
            mFragments[THIRD] = ZhihuThirdFragment.newInstance();
            mFragments[FOURTH] = ZhihuFourthFragment.newInstance();

            loadMultipleRootFragment(R.id.fl_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD],
                    mFragments[FOURTH]);
        } else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题
            // 这里我们需要拿到mFragments的引用
            mFragments[FIRST] = firstFragment;
            mFragments[SECOND] = findFragment(ZhihuSecondFragment.class);
            mFragments[THIRD] = findFragment(ZhihuThirdFragment.class);
            mFragments[FOURTH] = findFragment(ZhihuFourthFragment.class);
        }
```

**Comment by cocowobo** [comment]
@ruanbaojun1105  @zhupengxiang @qinglok @qinyang1018 @zhangjianwei1 
哎。此bug关闭，花费了不知多少次的调试，从去年调试到今年，源码层层递进，
各种调试手段检测尽出。终于发现在恢复过程中，被恢复的fragment突然执行了preDestoryView。
想尽办法回溯是哪里调用了 恢复后又销毁，直到看到自己再baseactivyt中有一个两年前植入的代码。
 
    /** 初始化预先执行的命令代码 */
    private void initRun() {
        //判断程序奔溃先移除掉以前的fragment 放到setContentView后
        List<Fragment> fragments = getSupportFragmentManager().getFragments();
        if (fragments != null) {
            for (Fragment fragment : fragments) {
                getSupportFragmentManager()
                        .beginTransaction()
                        .remove(fragment)
                        .commit();
            }
        }
    }


这串代码在oncreate后执行。妈耶。神操作，2年前从哪里扒拉来的粗暴处理逻辑，竟然把我埋了2年的坑。。。。。。。
bug先挂几天，然后关闭，
也就是说在主页activity中，oncreate的时候只要判断fragment不为空，就不用再loadRootFragment

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (findFragment(ZhuYeFragment.class) == null) {
            loadRootFragment(R.id.fl_container, ZhuYeFragment.newInstance());
        } else {
            //不用处理，当前activity已经在super中恢复了fragment。
            //你自己只需要执行下view的状态的恢复即可
        }
    }

坑自己呀

**Comment by zhupengxiang** [comment]
@qienanxiang   这个跟demo没什么区别啊  

![image](https://user-images.githubusercontent.com/17894209/61626309-91fc5c00-acaf-11e9-807b-3949e1db0e3e.png)

不知道为什么我的这个偶尔会重叠  大佬们能帮忙看看哪的问题吗？ 主页的tab切换有时候会重叠

**Comment by cocowobo** [comment]
@zhupengxiang 偶尔重叠。就不知道为啥了，你都fragment的控制器是不是有问题。

**Comment by zhupengxiang** [comment]
这不应该跟我截图的切换有关吗  就这么点代码   我也不知道哪的问题

**Comment by RockyQu** [comment]
@zhupengxiang 是不是主页这几个来回切重叠？fragment要加背景色，不加背景色就重叠

**Comment by zhupengxiang** [comment]
@RockyQu   我也不知道哪的问题   反正就切换  点击就重叠了   这个库不就是解决重叠问题的吗  怎么还会重叠

**Comment by RockyQu** [comment]
@zhupengxiang 可能是我写的不对，刚想到我之前没加判断
