### ISSUE TITLE
fragment的启动模式问题

### ISSUE THREAD

**Issue by zhangluya** [YoKeyword/Fragmentation#116]
A正常启动B 在B中singleTask启动A，此时A中的所有成员变量变为null

**Comment by YoKeyword** [comment]
@zhangluya Hi，
这个commit会让 onNewBundle()接收不到正确的Bundle~
````java
  HomeFragment fragment = HomeFragment.newInstance();
                Bundle bun = new Bundle();
                bun.putString("key", "value");
                fragment.putNewBundle(bun);
                start(fragment, SINGLETASK);
````
目前代码在HomeFragment的onNewBundle(Bundle args)里接收到的Bundle是上面设置的'key':'value'～
如果merge了你的Request，会导致onNewBundle里接收不到'key':'value'  囧～

你遇到什么问题呢，导致哪种不正确的现象？

**Comment by zhangluya** [comment]
嗯嗯，我是把putNewBundle封装到了内部，感觉这样不会产生迷惑，例如我正常启动一个fragment需要Bundle bun = new
Bundle();

                bun.putString("key", "value");
                fragment.setAarguments(bun);
                start(fragment, SINGLETASK);

而通过SINGLETASK启动
却要putNewBundle()。那样改了之后无论是正常启动还是通过模式启动都可以这样调用fragment.setAarguments(bun);

                start(fragment, SINGLETASK);方便一些，哈哈。

并且我还发现了这个问题：A正常启动B
在B中singleTask启动A，此时A中的所有成员变量变为null。我改了handleLaunchMode这个方法之后就没有这个问题了


2016-10-14 15:43 GMT+08:00 YoKey <notifications@github.com>:

**Comment by YoKeyword** [comment]
哦哦，原来是想在launchMode下 设置数据也走原始的setArguments()，可以是可以哒，不过要兼容旧版本的putNewBundle()； 回会我研究下能否兼容，能兼容的话就采用这个方案，确实走同一套setArguments对使用者来说比较简单～  感谢建议🙏

> 并且我还发现了这个问题：A正常启动B
在B中singleTask启动A，此时A中的所有成员变量变为null。

这个我没懂，我模拟了这个场景，没发现问题。  哪些成员变量被置为了null？  
onNewBundle()里的Bundle当前版本是putNewBundle的Bundle，不包含Fragment的Arguments

**Comment by zhangluya** [comment]
就是Afragment 启动
BFragment,然后在BFragment中以singleTask启动AFragment，启动到AFragment中后，当AFragment回调onNewBundle时，AFragment中的所有成员变量都变成null了。

在 2016年10月14日 下午4:30，YoKey <notifications@github.com>写道：

**Comment by YoKeyword** [comment]
不会啊，我按你的场景模拟了下，都是正常的，没有null情况...
而且代码上，仅仅调用其onNewBundle，其他什么事都没干～

**Comment by zhangluya** [comment]
太神奇了吧……

2016年10月14日 下午7:29，"YoKey" <notifications@github.com>写道：

**Comment by YoKeyword** [comment]
我的模拟场景是：
Flow_Demo里，HomeFragment启动DetailFragment，然后DetailFragment点击后singleTask模式启动HomeFragment， HomeFragment里的onNewBundle里打印了各种变量，都是正常的～ 囧

**Comment by zhangluya** [comment]
我整理了一份demo出来，你有时间看一下，为什么我打印都是null？？？发​
 FragmentationTest.zip
<https://drive.google.com/file/d/0B9hNhlzaBHQwSTJvUmVXMGdJb1k/view?usp=drive_web>
​附件了

2016-10-14 19:55 GMT+08:00 YoKey <notifications@github.com>:

**Comment by YoKeyword** [comment]
好哒～

**Comment by YoKeyword** [comment]
太感谢了 🙏～

确实有这个BUG，因为之前回调新new的Fragment的onNewBundle，而新new的并不是栈内的那个，现在已经修复了～

Merge了你的PR，同时为了兼容旧版本，同时支持setArguments()和putNewBundle()两种方式，putNewBundle()被标记了过时～

另外参考**Activity**的onNewIntent()内的intent和getIntent()是不同的对象，所以Fragmentation内的onNewBundle(args)内的args和getArguments()也是不同的对象。

**Comment by zhangluya** [comment]
哈哈，不用客气，这个库也给了我很大的帮助。是的，我调试的时候也发现了回调的是新new的fragment的onNewBundle，既然这样，那为什么栈内的那个fragment的onNewBundle也确实被触发了。

在 2016年10月14日 下午10:38，YoKey <notifications@github.com>写道：
