### ISSUE TITLE
Fragmentation popTo方法在有Runnable的情况下includeSelf失效

### ISSUE THREAD

**Issue by gavinboy** [YoKeyword/Fragmentation#118]
if (afterPopTransactionRunnable != null) {
            if (targetFragment == fromFragment) {
                mHandler.post(afterPopTransactionRunnable);
                return;
            }

```
        hackPopToAnim(targetFragment, fromFragment);

        popToFix(fragmentClass, flag, fragmentManager);
        mHandler.post(afterPopTransactionRunnable);
    } 
```

在Runnable不为null的情况下，直接return 了

**Comment by YoKeyword** [comment]
Runnable不为null的情况下，直接return 

这种情况是：   要在出栈的FragmentA已经在栈顶，还执行了popTo(A,false,xxx)

第二个参数includeSelf的true代表包括A一起出栈， false代表不包括A （即只出栈A上面的Fragments）

源码里在你贴的这段代码上面有 includeSelf的逻辑判断，你再看下，是否理解错了  :)
