### ISSUE TITLE
建议取消SwipeBackActivity

### ISSUE THREAD

**Issue by Liam6666** [YoKeyword/Fragmentation#1188]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by cocowobo** [comment]
这个玩意属于自己继承的.不继承则不用
且SwipeBackActivity存在一些bug

**Comment by JantHsueh** [comment]
@cocowobo  SwipeBackActivity确实有问题，我已经在新的版本进行修复。详情可查看  #1237

**Comment by weikaiyun** [comment]
> 这个玩意属于自己继承的.不继承则不用
> 且SwipeBackActivity存在一些bug

我弄了个简化版本 只有fragment跳转管理 剔除个人觉得繁琐的代码 基本大家都可以看懂，然后在源代码基础上自行定制即可。我觉得原来这个库的核心功能是很好的，但是太大 太全不见得是好事。
这个是简化的库 直接取源代码使用就好。希望对你有用。因为我其实在实际使用中只是用到了跳转，然后我觉得动画可以自行处理呀 原来的库动画监听一大串 反正我是没明白 就弄掉了。然后懒加载 我觉得使用setMaxLifeCycle就好啊 直接在resume里处理就好 也不需要原来的库里面的supportViewDelegate.
https://github.com/weikaiyun/EasyFragmentation
