### ISSUE TITLE
多级SwipeBackFragment问题

### ISSUE THREAD

**Issue by Synaric** [YoKeyword/Fragmentation#119]
假设跳转关系是：HomeFragment -> AFragment -> BFragment，A和B都是SwipeBackSampleFragment，按照SwipeBackSampleFragment里的逻辑，BFragment退栈后，AFragment里就可以滑动DrawerLayout了。

**Comment by YoKeyword** [comment]
额，没明白你的意思～  遇到什么问题呢～

**Comment by Synaric** [comment]
问题已经解决了，提个优化而已 = =
流式demo中：
使用SwipeBackFragment一般都是要禁止DrawerLayout的，我看到你的SwipeBackSampleFragment这个例子加入了这个处理，但是这只适用于单次滑动退出。
假如栈情况是HomeFragment -> AFragment -> BFragment，并且A和B都是滑动退出的界面，那么BFragment滑动退出后，按照MainActivity这段代码：
`    @Override
    public void onLockDrawLayout(boolean lock) {
        showFragmentStackHierarchyView();
        if (lock) {
            mDrawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
        } else {
            mDrawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED);
        }
    }`
DrawerLayout又被激活了，A的滑动退出就可能有问题。
多级的SwipeBackFragment效果可以参考虾米

**Comment by YoKeyword** [comment]
哦哦， 感谢建议！
因为是Demo，之前只是粗糙的展现使用方式，交互细节没多想哈～
以后再优化Demo  😄
