### ISSUE TITLE
onLazyInitView和onSupportVisible不回调

### ISSUE THREAD

**Issue by Break369** [YoKeyword/Fragmentation#1195]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**
场景，fragment嵌套fragment（A,B,C,D,E），viewpager的缓存页默认，进入其中的第二层的fragment(D)，然后，按手机的home键，至于后台，然后回来app界面，点击tab进入A fragment，然后再点击进入C fragment。则C fragment不回调onLazyInitView和onSupportVisible

**Comment by cocowobo** [comment]
重建则一定会走,你的c的fragment是否没有重建,属于缓存,而且缓存应该走onSupportVisible,建议你自己好好追踪下源码

**Comment by Break369** [comment]
VisibleDelegate方法中，onPause()走            mInvisibleWhenLeave = true，然后，按照以上描述流程，进入c fragment，走到dispatchSupportVisible，
然后走到checkAddState，return，所以在进入c的时候，不走onLazyInitView()。

不过我这边找到了一个处理方法，进行了手动回调，获取mInvisibleWhenLeave 的字段进行判断手动回调，则可以解决这个问题。

**Comment by Break369** [comment]
@cocowobo
