### ISSUE TITLE
跳转到新的fragment 参数没带过去

### ISSUE THREAD

**Issue by Spoon2014** [YoKeyword/Fragmentation#12]
我在adapter中跳转到新的fragment 参数没带过去 ,有空给看看呗
ReceiptDetailsPage fragment = mFragment.findFragment(ReceiptDetailsPage.class);
if (fragment == null) {
	 fragment = ReceiptDetailsPage.newInstance();
}else{
	Bundle newBundle = new Bundle();
	newBundle.putSerializable("RECEIPT_DATA_TO_HTML", dataToHtml);
	// 传递的bundle数据，会调用目标Fragment的onNewBundle(Bundle newBundle)方法
	 fragment.putNewBundle(newBundle);
}
// homeFragment以SingleTask方式启动
mFragment.start(fragment,SupportFragment.SINGLETASK);

**Comment by YoKeyword** [comment]
@Spoon2014 你是在ReceiptDetailsPage这个Fragment里的
`protected void onNewBundle(Bundle args) {}`
里接受的数据吗？ SINGLETASK模式启动已存在的Fragment会回调该Fragment的onNewBundle方法

如果还有问题 可以加我QQ: 328903522   :)
