### ISSUE TITLE
在BaseActivity使用onCreateFragmentAnimator()方法，return null;报空指针异常。

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#120]
在BaseActivity使用onCreateFragmentAnimator()方法，return null;报空指针异常。

是这样的，我记得你的框架里Activity，fragment都有onCreateFragmentAnimator方法，我在自己的BaseActivity中复写这个方法，之前是 return new FragmentAnimator(0, 0, 0, 0);，貌似没问题，后来在BaseFragment中直接return null; 也没问题，所以就在BaseActivity使用onCreateFragmentAnimator()方法中return null; 结果报空指针，那我想请问，在你的这个框架里，取消掉所有Activity之间的动画，或者只取消某两个Activity之前的动画的正确姿势应该是怎样的呢？

**Comment by YoKeyword** [comment]
fragment的onCreateFragmentAnimator如果return null的话，就会找Activity里的onCreateFragmentAnimator～

Activity里的onCreateFragmentAnimator是不能返回null，的确实会报空指针，下个版本做下安全性校验～

PS ： 无动画，可以用库提供的一个类new DefaultNoAnimator()～

Activity的`onCreateFragmentAnimator`是设定其内所有Fragments的动画，如果其中的某个Fragment内部又复写了`onCreateFragmentAnimator`，则以Fragment内部复写的为先。

**Activity**之间的动画和库没关系 ＝，＝     只能管理**Fragment**之间的动画～

````java
// Activity.java:  取消所有Fragments之间的动画
@Override
protected FragmentAnimator onCreateFragmentAnimator() {
        return new DefaultNoAnimator();
}
````

````java
// 目标Fragment.java :  取消目标Fragment的4个动画
@Override
protected FragmentAnimator onCreateFragmentAnimator() {
        return new DefaultNoAnimator();
}
````
 更细致的动画控制，需要从FragmentAnimator的4个参数入手了～

**Comment by leguang** [comment]
明白了，谢谢，你可以关闭这个issue了

**Comment by leguang** [comment]
3Q^_^
