### ISSUE TITLE
onBackPressedSupport问题

### ISSUE THREAD

**Issue by romantiskt** [YoKeyword/Fragmentation#121]
在activity中通过 loadRootFragment(R.id.fl_groupon_container, MarketInfoNewFragment.newInstance()); 
添加同级fragment ,然后在fragment中start(fragment A)一个新的fragment A  , 按返回键不会回调 fragment A 中的 onBackPressedSupport ,请问按返回键 会回调哪个方法呢

**Comment by YoKeyword** [comment]
loadRootFragment加载的同级Fragment， 比如A ，  A是不能直接去start其他Fragment的！

一般是用A的父Fragment去start(仿微信的demo是这样)， 或者用A的子Fragment去start(仿知乎Demo)

同级Fragment切记不能去直接start， 只建议show/hide！   具体原因思考下栈视图就明白了～

**Comment by romantiskt** [comment]
问题解决了 ,是因为我在 目标fragment中又有嵌套子fragment, 而未使用childFragmentmanager的原因.
