### ISSUE TITLE
超级大BUG！！！

### ISSUE THREAD

**Issue by darkSuperman** [YoKeyword/Fragmentation#1211]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version ：版本是androidx的，'me.yokeyword:fragmentationx:1.0.1'
* Support-v4 version
* Logs ：暂无日志
* Screenshots ：暂无截图

我描述下产生这个BUG的场景：
 我用的是单activity+多fragment。
 MainAcitity . loadRootFragment ( MainFragment )
栈视图
 MainFragment 
 ——HomeFragment
         ——AFragment
HomeFramgment中用了ViewPager，然后ViewPager嵌套了AFragment,
然后AFragment用getParentFragment().getParentFragment().startBrotherFragment(BFragment)
跳转到BFragment，BFragment点了一下左侧边缘就界面就会消失，然后栈视图显示它还是存在，然后就不能启动BFragment了，必须要按返回键让BFragment弹栈才可以。
BFragment继承的是SupportFragment，尝试过继承 SwipeBackFragment，使用setSwipeBackEnable(false)方法没用！！！;

**Comment by ruanbaojun1105** [comment]
sb
