### ISSUE TITLE
建议Fragment再加两个回调函数

### ISSUE THREAD

**Issue by kingyangcn** [YoKeyword/Fragmentation#122]
建议Fragment再加两个回调函数：
onHide()
onShow()
很多情况下会有这方面的需求。

**Comment by YoKeyword** [comment]
感谢建议！
最早的时候有这2个方法，后来考虑到Fragment本身的onHiddenChanged(boolean)更灵活点，所以移除了；可能暂时不考虑加入这2个方法。
🙏

**Comment by kingyangcn** [comment]
@YoKeyword 啊啊，我学艺不精哈。没想到onHiddenChanged可以实现这些需求，感谢指点。顺便再赞一下这库，很棒！
