### ISSUE TITLE
建议可能的话加入RxLifecycle库的兼容

### ISSUE THREAD

**Issue by woniu0936** [YoKeyword/Fragmentation#124]
RxLifecycle库只用的时候就是要继承他的RxAppCompatActivity和RxFragment，使用Fragmentation也需要继承SupportActivity和SupportFragment，我想两个都用，所以如果可以的话，希望做一下兼容，谢谢

**Comment by YoKeyword** [comment]
了解，毕竟Java继承的机会只有一次； 
回头我评估下如果改成`implements` ＋ 委托者模式的情况下，对于使用者是否依然可以足够简单等等因素。

PS：RxLifecycle其实做了兼容，可以不用继承它的RxXXX组件，通过在使用Rx的地方主动声明绑定也是可以的。

**Comment by linheimx** [comment]
继承的侵入性很强，做成工具类的形式，去操作fragment，这就完美了。

**Comment by woniu0936** [comment]
@YoKeyword 好的，谢谢提醒，我看看

**Comment by woniu0936** [comment]
偶然看到，挺有意思，如果有和我一样困惑的，暂时可以先试试这个方式 https://github.com/wsaxx/AndroidPracticeCode/blob/c26da7e248492fe143d330a10e538f408bc8fc88/androidhelper/src/main/java/com/wsaxx/helper/app/rxlifecycle/RxAppCompatActivity.java

**Comment by YoKeyword** [comment]
@linheimx 是的，不过需要评估下做出来的委托工具类，其使用复杂度怎么样，回头思考下 😄

**Comment by liangfeng093** [comment]
> 偶然看到，挺有意思，如果有和我一样困惑的，暂时可以先试试这个方式 https://github.com/wsaxx/AndroidPracticeCode/blob/c26da7e248492fe143d330a10e538f408bc8fc88/androidhelper/src/main/java/com/wsaxx/helper/app/rxlifecycle/RxAppCompatActivity.java

链接挂了，404
