### ISSUE TITLE
滑到一半，取消侧滑，再点击返回键，右边会出现空白。

### ISSUE THREAD

**Issue by Tang3210** [YoKeyword/Fragmentation#1244]
原因：添加 api  'androidx.lifecycle:lifecycle-extensions:2.2.0'这个库，版本是2.2.0时，是必现的，请问有没有什么解决办法
效果图是跟这个一样的 #1130

**Comment by Tang3210** [comment]
已解决
把api 'androidx.lifecycle:lifecycle-extensions:2.2.0'  换成
api 'androidx.lifecycle:lifecycle-viewmodel:2.2.0'
api 'androidx.lifecycle:lifecycle-livedata:2.2.0'

![a](https://user-images.githubusercontent.com/47552566/81542538-61ed8900-93a7-11ea-8a99-3933e099835f.jpg)
官方也已经弃用此依赖

**Comment by ssyRo156** [comment]
https://github.com/YoKeyword/Fragmentation/issues/1130#issuecomment-886559697 小问题解决了，去这里看
