### ISSUE TITLE
EasyFragmentation

### ISSUE THREAD

**Issue by weikaiyun** [YoKeyword/Fragmentation#1247]
原库作者已经不再维护，然后我现在弄了个简化版本，基本感觉大家都可以看懂，里面只有fragment跳转管理功能。这个简化版本的代码基本全部来自于原库，但是剔除了我觉得比较繁琐的部分。这个是新库的链接 https://github.com/weikaiyun/EasyFragmentation 欢迎大家直接使用源代码，然后在此基础上定制使用，希望对大家能有所帮助。

**Comment by wwddd66** [comment]
> 原库作者已经不再维护，然后我现在弄了个简化版本，基本感觉大家都可以看懂，里面只有fragment跳转管理功能。这个简化版本的代码基本全部来自于原库，但是剔除了我觉得比较繁琐的部分。这个是新库的链接 [https://github.com/weikaiyun/EasyFragmentation，](https://github.com/weikaiyun/EasyFragmentation%EF%BC%8C) 欢迎大家直接使用源代码，然后在此基础上定制使用，希望对大家能有所帮助。

404

**Comment by weikaiyun** [comment]
> > 原库作者已经不再维护，然后我现在弄了个简化版本，基本感觉大家都可以看懂，里面只有fragment跳转管理功能。这个简化版本的代码基本全部来自于原库，但是剔除了我觉得比较繁琐的部分。这个是新库的链接 [https://github.com/weikaiyun/EasyFragmentation，](https://github.com/weikaiyun/EasyFragmentation%EF%BC%8C) 欢迎大家直接使用源代码，然后在此基础上定制使用，希望对大家能有所帮助。
> 
> 404

https://github.com/weikaiyun/EasyFragmentation
