### ISSUE TITLE
viewpager嵌套viewpager，中第二个viewpager中的onLazyInitView和onSupportVisible步骤

### ISSUE THREAD

**Issue by moonstr** [YoKeyword/Fragmentation#1249]
implementation 'me.yokeyword:fragmentationx:1.0.2'第一个viewpager中四个fragment，第一个fragment中内含viewpager中三个fragment，来回切换第二个viewpager第二个viewpager中的fragment就不走
onLazyInitView和onSupportVisible了

**Comment by StaticCoder** [comment]
咋解决的啊
