### ISSUE TITLE
普通类里面怎么打开指定的fragment？

### ISSUE THREAD

**Issue by adminLiu-s** [YoKeyword/Fragmentation#125]
普通类里面怎么打开指定的fragment，比如说我封装了一个推送的类，收到指定消息就根据标示点击跳转到指定fragment

**Comment by YoKeyword** [comment]
这种需求下，一个方案是启动一个Activity，里面去启动该Fragment；实现简单

另一种，在当前最栈顶的Fragment直接start； 如果是知乎那种栈结构就比较复杂了

**Comment by adminLiu-s** [comment]
但我的那个类是推送的，在另一个进程，app已经完全退出的情况下，想要开启指定fragment

**Comment by YoKeyword** [comment]
所以 最简单的还是第一种方案；
或者打开时，启动你的MainActivity把主页的Fragment都加载后，再加载指定Fragment，这样指定Fragment出栈后 会回到主页

**Comment by adminLiu-s** [comment]
嗯，好的，去试试
