### ISSUE TITLE
请教问两个问题

### ISSUE THREAD

**Issue by xiang23** [YoKeyword/Fragmentation#127]
我在项目中的写法是多模块Activity＋多Fragment ,现在A Activity中start了一些fragment 跳转到B Activity需要先POP掉A所拥有的fragment再finsh 掉 A吗？我在一个BaseFragment中直接重写 onHiddenChanged 判断hidden然后hideSoftInput，如果一个没有弹出输入法的fragment继承它会不会产生问题？

**Comment by xiang23** [comment]
顺便再问一个问题，我想在Activity间也实现跟Fragmentation一样的转场动画。我使用了overridePendingTransition(R.anim.h_fragment_enter,R.anim.h_fragment_exit);（这两个动画文件是Fragmentation中的）但是效果明显没有Fragment中的好，有什么好的解决方案吗？

**Comment by YoKeyword** [comment]
第一个问题 宿主AC finish后，其内的FG都会被销毁

第二个  不会产生问题

第三个动画问题嘛 你可以先自己喜欢的动画效果的app反编译 拿到其动画  ：）

**Comment by xiang23** [comment]
动画现在主要想跟Fragmentation一样。。。直接那么用overridePendingTransition(R.anim.h_fragment_enter,R.anim.h_fragment_exit);效果感觉有偏差。。

**Comment by YoKeyword** [comment]
AC的动画完全自定义需要用style  在theme里指定其动画，有四个属性，可以查下

overxxx这个方法只能指定两个属性，所以有偏差

**Comment by xiang23** [comment]
好的，谢谢大大
