### ISSUE TITLE
Fragment not attached to Activity.

### ISSUE THREAD

**Issue by iboying** [YoKeyword/Fragmentation#128]
描述：我把大部分的逻辑放到了`onEnterAnimationEnd`中执行，但是上报了很多crash，`Fragment not attached to Activity.`，因为我使用了`getResources()`，可能动画结束执行代码的时候还没有`attached to Activity`，这块要怎么处理好呢？谢谢

**Comment by YoKeyword** [comment]
getResources()的源码：
````java
final public Resources getResources() {
        if (mHost == null) {
            throw new IllegalStateException("Fragment " + this + " not attached to Activity");
        }
        return mHost.getContext().getResources();
}
````

这意味着Fragment已经和宿主Activity detach了， 你检查下这些逻辑操作中是否有异步任务，然后回调调用了`getResources()`等需要用到宿主Activity的方法；

解决方案的话：1、在Fragment销毁时，取消异步任务 
或者 2、回调后 判断 `if(isAdded)`

**Comment by iboying** [comment]
对，有异步任务，我是当动画结束后，会设置监听器、调用接口，然后调用成功后载入图表，图表的显示我使用的getResources()来设置颜色，所以造成了这个问题，十分感谢
