### ISSUE TITLE
Can not perform this action after onSaveInstanceState错误

### ISSUE THREAD

**Issue by kzqsky** [YoKeyword/Fragmentation#130]
为什么不把commit()方法替换成 commitAllowingStateLoss()？

**Comment by YoKeyword** [comment]
见 #103
 commitAllowingStateLoss()可能会导致你的commit()无效，而这个错误是完全可以避免的 :)

**Comment by hcadoid** [comment]
我的也出现了，我在一个Activity中发送EvenBus到Fragment中去通知切换Fragment操作出现，这要怎么避免呢？

**Comment by YoKeyword** [comment]
举一个我项目的栗子：
````java
   @Subscribe
    public void onReplaceFragment(ReplaceFragmentEvent event) {
        if (isResumed() && !isHidden()) {
            replaceFragment();
        } else {
            mNeedReplaceFragment = true;
        }
    }

    @Override
    public void onResume() {
        super.onResume();
         if (mNeedReplaceFragment && !isHidden()) {
            replaceFragment();
            mNeedReplaceFragment = false;
        }
    }
````

**Comment by hcadoid** [comment]
Fragment stat是add hide形式，那你们的项目做页面的统计，生命周期都是不成对的，怎么做呢 ，之前试的Dmeo好像是f1 start f2后,在退出f2后，f1的Resume就不走了。

**Comment by YoKeyword** [comment]
生命周期肯定是成对哒～   start,add/hide形式  切换／进出Fragment是回调onHiddenChanged()方法

onResume等方法是跟随宿主Activity的。

**Comment by hcadoid** [comment]
像微信Demo里面，如果3个TAB切换，是不走onResume onPause 等方法的，如果做统计页面，只能onHiddenChanged做？ 那如果在跳转到另外的Activity中，再回来其实onHiddenChanged是不调用的，因为已经在显示了，此时是走宿主Activity的onResume等。。 那统计不好做啊，有没有像 Activity一样方便的？

**Comment by YoKeyword** [comment]
如果想统计Fragment的话，onHiddenChanged()＋onResume() 结合着做

**Comment by ethanhua** [comment]
我也出现了这个问题 但是我只是在个别地方会出这个错 我现在的处理办法是 在# 报错切换fragment的代码处**做你推荐的这种处理
@Subscribe
    public void onReplaceFragment(ReplaceFragmentEvent event) {
        if (isResumed() && !isHidden()) {
            replaceFragment();
        } else {
            mNeedReplaceFragment = true;
        }
    }

    @Override
    public void onResume() {
        super.onResume();
         if (mNeedReplaceFragment && !isHidden()) {
            replaceFragment();
            mNeedReplaceFragment = false;
        }
    }
没有报错的地方没有处理，还有我觉得不可理解的是 报这种错的一般都是同一处代码？既然不是所有切换fragment的地方都会等概率出现这种activity销毁重建

**Comment by YoKeyword** [comment]
@ethanhua 
> 在你离开当前Activity等情况下，系统会调用onSaveInstanceState()帮你保存当前Activity&Fragment的一些状态数据等，而在离开后（onSaveInstanceState()已经被执行），你又去执行Fragment的相关事务方法后，就会抛出该异常

你看了这个原因后 应该就明白了  :)

**Comment by ethanhua** [comment]
@YoKeyword 嗯 你说的这个错误的原理我知道 我的意思是说 这个activity销毁重建的概率 怎么恰恰发生在我的项目中的同一处代码处（某个列表页 点击某个条目 跳转到详情页） 其他切换fragment的地方没有报这个错 也只能理解为刚好有个用户的手机在退回桌面后切回app时点击这个操作时发生了activity销毁重建了吧，，那是不是所有切换fragment的地方都需要做这种处理？

**Comment by YoKeyword** [comment]
@ethanhua 这个异常和 AC销毁是没关系的，在离开AC时，比如进入下一个AC，或者回到桌面等，都立即会调用`onSaveInstanceState()`，在直到该AC重新`onResume()`期间，调用Fragment事务方法，必报此异常！

你需要检查你调用Fragment事务的地方，是否可能会出现这种情况，排查下   :)

**Comment by ethanhua** [comment]
@YoKeyword  嗯 你说得对 我以为只有在销毁之前才会去调用onSaveInstacenState， 你说的在直到该AC重新onResume期间 具体是指到该ac执行onResume方法吗？ 我这边出现这种问题的场景是 点击某个列表的一个条目 跳到另一个fragment，但都能点击这个列表的条目了 应该整个ac执行完onResume了吧

**Comment by YoKeyword** [comment]
@ethanhua  在Activity不可见到下次可见之前（onResume()之前）； 
你检查下是否是跳转时AC不可见，然后FG再进行加载导致了这个异常～

**Comment by pye52** [comment]
@YoKeyword 请问下你的项目是在basefragment里注册eventbus的事件么？
我是在唯一的activity里注册这个启动fragment的事件的
最近报这个错的几率高了很多…(而且都集中在6.0的机型上，应该是和版本号无关的啊，在我自己的测试机上就一直没出现过)
我已经在事件处理过程中做了是否在前台的判断了…如不在前台，就不start fragment，但还是会有这个问题…

**Comment by pye52** [comment]
@ethanhua 我也是出现了这个问题…recyclerview的某一个item点击的时候就报错了，请问你是怎么解决的呢？

**Comment by YoKeyword** [comment]
> 请问下你的项目是在basefragment里注册eventbus的事件么？

首先EventBus尽量按需在合适的实际去注册，EventBus的使用虽然很简单，但是建议科学使用；
基本都是V4包下的类，应该和机型版本无关；

下面是我在类似场景下的避免报`Can not perform this action after onSaveInstanceState`的简化代码：
````java
   @Subscribe
    public void onReplaceFragment(ReplaceFragmentEvent event) {
        // 这2个条件都成立时！
        if (isResumed() && !isHidden()) {
            replaceFragment();
        } else {
            mNeedReplaceFragment = true;
        }
    }

   @Override
    public void onResume() {
        super.onResume();
        if (mNeedReplaceFragment  && !isHidden()) {
            replaceFragment();
            mNeedReplaceFragment = false;
        }
    }
````

**Comment by pye52** [comment]
@YoKeyword 我是参考你demo_wechat里的方式，在mainfragment里处理start事件
如果按照你贴的
```java
@Subscribe
    public void onReplaceFragment(ReplaceFragmentEvent event) {
        // 注意： 这2个条件需要同时成立！
        if (isResumed() && !isHidden()) {
            replaceFragment();
        } else {
            mNeedReplaceFragment = true;
        }
    }
   @Override
    public void onResume() {
        super.onResume();
        if (mNeedReplaceFragment  && !isHidden()) {
            replaceFragment();
            mNeedReplaceFragment = false;
        }
    }
```
那么在以下场景就不起作用了
则mainfragment -> fragmentA，此时点击fragmentA的按钮，发送事件打开fragmentB，由于mainfragment的ishidden = trye，就无法打开fragmentB了

**Comment by YoKeyword** [comment]
@pye52  
> mainfragment的ishidden = true，就无法打开fragmentB了

没理解，该异常的是 宿主AC已经调`onSaveInstanceState()`之后再去执行FG事务，和`isHidden`是不是true没必然联系；

 `onHiddenChanged()`的回调方法和`onResume(),onPause()`是没关系的；

`onHiddenChanged()`被回调必然说明着该FG以及宿主AC是在`onResume()`状态，此时去`start`是安全的。

**Comment by pye52** [comment]
@YoKeyword 
[Demo](https://github.com/pye52/FragmentationDemo)
这是我根据自己项目的大致框架做的一个demo，流程如下:
mainactvitiy 中有一个rootfragment(fragmentA)
fragmentA点击列表项可以打开fragmentB (相当于QQ最近会话列表里打开一个聊天窗口)
fragmentB可以打开fragmentC (聊天窗口打开群信息查看群成员)
fragmentC可以打开另一个B (在成员列表中打开其中一个的聊天窗口)，也可以打开D (进入成员的详细信息页面)
fragmentD可以打开另一个D (在详细信息页面可以打开该成员的聊天窗口)

但无论从哪里打开B，都会将A与B之间的fragment出栈，保证从B返回一定会回到A，且B只有一个:
```java
final SupportFragment fragment = event.getFragment();
        if (fragment instanceof FragmentB) {
            popTo(FragmentA.class, false, new Runnable() {
                @Override
                public void run() {
                    // TODO 就是这里很容易报"Can not perform this action after onSaveInstanceState"
                    start(fragment);
                }
            });
            return;
        }

        start(fragment);
```

**Comment by YoKeyword** [comment]
@pye52 你的Demo我无法复现....

还有你的栈层级明明只有一层，为何要用EventBus，A启动B直接start，B启动C也是直接在B里start，**EventBus要在必要的地方使用**，不能过度使用，EventBus的代码是一种可读性较差的代码

另外根据你的需求，建议使用 start(B, SingleTask)的方式启动B～

**Comment by pye52** [comment]
@YoKeyword 其实我也无法复现…但是我把demo给几个朋友安装，就有说卡死的(报错之后界面会卡住，且打开哪个fragment都是一片空白)
我也试过start(B, SingleTask)，但是当在B打开C，C再打开B的时候，会发现直接闪到B了，动画没了QAQ
其实用eventbus是因为在adapter里不用留一个接口给外层，能直接post到A上启动fragment 😄 
没想到这个方式会出问题，只好想想其他办法了 🤕 
非常感谢你的建议~

**Comment by YoKeyword** [comment]
@pye52 建议你在你的App里集成类似 bugtags这种，可以监测到崩溃前的行为，进而分析～  

毕竟第一优先是.... 先复现啊 😂～

**Comment by pye52** [comment]
@YoKeyword 原来有这种好东西😂万分感谢
另外 @ethanhua 的描述似乎和我的问题有点类似，能交流下嘛？

**Comment by ethanhua** [comment]
@pye52  我的解决方案是针对我出问题的场景 当点击的时候监测当前fragment如果不在前台就延迟200ms左右再去startfragment 目前还没有报什么crash上传上来，至于原因我现在也不明白 既然都能点击了 就应该表示当前fragment在前台😭

**Comment by ethanhua** [comment]
@YoKeyword  @pye52  可能的解释是虽然当前fragment在前台 但是他的宿主activity不在前台，而在处于onsaveInstance状态中？

**Comment by YoKeyword** [comment]
@ethanhua  @pye52  Fragment事务(commit()下)并不是立即执行的，而是放到主线程的任务队列队尾，在未来某个时机才会执行;

库中的start内部是`commit()`，此外还有`commitAllowingStateLoss()`，但是该方法有可能丢失此次commit（在此次离开时恰巧AC被强杀时）；`commitAllowingStateLoss()`是可以作为解决手段的，但一般是作为最后的手段。

此外`commit()`后接`executePendingTransactions()`是可以让异步变同步，将之前的事务都立即执行。

从24.0.0开始后，添加了`commitNow()`，这个是立即执行你当前这条commit，但是会队列前面的事务是不会执行的，所以`commitNow()`是不允许和`addToBackStack()`一起使用的，因为这样栈内的顺序无法保证。

PS：最近在做0.8版本，鉴于这个异常在单AC多FG还是容易引起的情况，可能会提供允许`commitAllowingStateLoss()`的start,pop()方法

**Comment by pye52** [comment]
@ethanhua 😭我能想到的解决方式是将出现问题的fragment改为activity启动，保证万无一失，但是这样工作量大了，感谢你提供的思路

@YoKeyword 😭期待0.8版本，现在虽然解决方案似乎很多，但还要逐个试，而且问题在我这里还无法重现…真是像赌博一样的开发

**Comment by weiyf** [comment]
我也遇到了， 场景是在华为EMUI6.0系统下，点击按钮申请权限，然后startFragment，就会导致这个错误。但是在原生模拟器上没发现这错误。

**Comment by YoKeyword** [comment]
@weiyf   必现吗？ 点击按钮申请权限当前Activity会离开吗？

> 新的0.8版本可改变start()的commit()方式，可以选择commitAllowingStateLoss()或commitImmediate()  作为最后手段避免这个问题
不过还是建议复现该问题，查明原因用科学方式解决～

**Comment by weiyf** [comment]
@YoKeyword 是的，必现，我手上目前只有华为的机子，没法测试别的机型，至少原生系统是不会出现这种情况，估计是华为用dialogFragment重写了获取权限的提示框，我尝试过postdelay 200毫秒再执行start()方法，就不会报错。

**Comment by YoKeyword** [comment]
@weiyf `onSaveInstanceState()`一般来说在onStop()之前调用.

你试试在start()后，立即执行
`fragmentManager.executePendingTransactions()`试下

**Comment by YoKeyword** [comment]
0.8已经发布，可以自定义commit模式。

如果实在棘手，可以使用如下方式解决：
````java
 supportFragment.transaction()
                .commitAllowingStateLoss() / commitImmediate();
// 接着执行start()
 start(supportFragment);
````

**Comment by weiyf** [comment]
@YoKeyword 使用`fragmentManager.executePendingTransactions()`还是报错，更新新版后使用新版方法start之后没有问题，正常。

**Comment by YoKeyword** [comment]
@weiyf  那可以确定是 先执行了`onSaveInstanceState()`，后执行的Fragment事务～

遇到这种棘手的场景，就用最后手段吧：
````java
start(supportFragment.transaction().commitAllowingStateLoss());
````

先关闭该Issue了，楼有点高，再有该问题，继续讨论～
