### ISSUE TITLE
你好  我利用rxbus进行跳转会报错，不知道是因为rxbus引起的，还是遇见了bug

### ISSUE THREAD

**Issue by qinyang1018** [YoKeyword/Fragmentation#131]
<img width="1021" alt="qq20161103-0" src="https://cloud.githubusercontent.com/assets/15726024/19959252/45070a94-a1e0-11e6-8b04-6c196149339a.png">

**Comment by YoKeyword** [comment]
从日志上看是FragmentManager为空了， 检查下对应的行，看看FragmentManager为何为空
