### ISSUE TITLE
demo中的知乎模块的shopFragment

### ISSUE THREAD

**Issue by zhupengxiang** [YoKeyword/Fragmentation#132]
demo中的知乎模块的shopFragment  就是左面菜品列表  我想问下用主界面的loadMultipleRootFragment这个方式实现可以么

还有个问题 我看所有fragment的操作都要跟savedInstanceState联系起来 必须要这样么  我想说以前从来没有关注过这个

**Comment by YoKeyword** [comment]
1、  不能， loadMultipleRootFragment是为了解决同级TabFragment的问题的， 虽然ShopFragment也是同级，但场景和交互不一样，所以建议自己拓展（当然下个大版本可能会考虑这种情况 😏）

2、跟Fragment关联的 都是在onCreate等创建类的生命周期里， 需要处理这个问题；在页面重启（比如旋转屏幕），重新走了onCreate()，而原来的Fragment系统帮你保存顺便帮你恢复了，此时栈里依然有这个Fragment，而你的onCreate里又去加载一次Fragment，造成重复加载，可能会导致重叠的

**Comment by Destiny01** [comment]
还是这种shopFragment列表，但是切换的是不同的Fragment，这种该怎么处理呢，而且数据会加载两次！

**Comment by zhupengxiang** [comment]
@YoKeyword    好的  谢谢
