### ISSUE TITLE
右滑看见桌面

### ISSUE THREAD

**Issue by Saqrag** [YoKeyword/Fragmentation#133]
我在小米4c android5.1系统上试过，正常。但是在红米2 android4.4系统上测试，从一个Activity推出到上一个Activity，右滑时下面看到手机桌面，右滑结束回到上一个activity。这个怎么解决？ 感谢

**Comment by YoKeyword** [comment]
上一个Activity内的布局填充个颜色看看，  SwipeActivity这块是参照开源库[SwipeBackLayout](https://github.com/ikew0ng/SwipeBackLayout)  你检查下是否使用上的细节有问题

**Comment by Saqrag** [comment]
你好，我在4.0以上的设备上基本都试过，只有4.4.4设备由此问题。而且只有Activity有问题，Fragment没有问题。我估计是动画的原因，在4.4.4设备从一个Activity返回到上一个Activity时,上一个Activity有返回动画。而这动画是从屏幕外流入到屏幕。所以右滑的时候上一个Activity在屏幕外头。因为Fragment没有返回动画所以不影响。  但是我在网上找了很多方法就是禁不了4.4.4设备地动画。

**Comment by YoKeyword** [comment]
我之前也测过红米4.4当时是正常的，我刚也试了一台红米4.4，是正常的；

你在Demo里的FirstSwipeBackFragment这个类里的onClick()方法里替换成：
`startActivity(new Intent(_mActivity, SwipeBackSampleActivity.class));`

然后在第一个Demo里抽屉菜单里选择打开"SwipeBackActivity+Fragment"菜单，然后点击界面再打开一个SwipeBackSampleActivity，然后侧滑看看～

**Comment by Saqrag** [comment]
不好意思，我当初引用的是SwipeBackFragment库，在浏览的时候问错地方了。我刚刚用您的方法试了一下Fragmentation库没有问题。然后试了一下SwipeBackFragment库，在Demo的FirstSwipeBackFragment的onClick()方法中分别调用startActivity(new Intent(_mActivity, MainActivity.class))和startActivity(new Intent(_mActivity, TestActivity.class)),TestActivity时我建的测试Activity,均有上述问题

**Comment by YoKeyword** [comment]
好的 我先关闭这边的issue

**Comment by Saqrag** [comment]
嗯嗯  麻烦了



Saqrag
在 YoKey <notifications@github.com>，2016年11月22日 10:41写道：

好的 我先关闭这边的issue

**Comment by chengzhijun0706** [comment]
我在vivo x710 系统是4.4也出现右滑显示桌面的问题
![image](https://cloud.githubusercontent.com/assets/13751034/21605056/93853322-d1e1-11e6-81ee-edcf9616675c.png)
下图是我从一个activity打开另一个activity的时候，下面的activity先闪出了屏幕
![image](https://cloud.githubusercontent.com/assets/13751034/21605123/f528605e-d1e1-11e6-967d-ece3ab4abf44.png)
我录制了一个视频
[WeChatSight20.mp4.zip](https://github.com/YoKeyword/Fragmentation/files/682040/WeChatSight20.mp4.zip)

**Comment by YoKeyword** [comment]
解决办法： [看这个Issue](https://github.com/YoKeyword/SwipeBackFragment/issues/6)

**Comment by chengzhijun0706** [comment]
问题解决了，谢谢了
