### ISSUE TITLE
进入fragment，开启网络请求，点击返回键，网络请求回调，更新ui，有空指针异常

### ISSUE THREAD

**Issue by sunjie798893816** [YoKeyword/Fragmentation#134]
使用的黄油刀，很多地方都有这个问题，页面还在loadding状态，突然点击返回，一会就回空指针

**Comment by YoKeyword** [comment]
这个和是否使用Fragment没什么关系，这是个经典的问题～

你在关闭Fragment时，要取消网络请求，或者更新UI时判断Fragment是否时attach状态（建议采用取消网络请求的方式， 可以考虑RxJava，很轻松解决）

同样不仅是Fragment，你用Activity时也需要这么做！
