### ISSUE TITLE
0.7.13 popto 无效?

### ISSUE THREAD

**Issue by qiyulan** [YoKeyword/Fragmentation#136]
═══════════════════════════════════
栈顶			LessonBuyFragment
↓			NewStudentFragment
↓			StudentListFragment
栈底			SupportRequestManagerFragment
 ══════════════════════════════════

执行 popTo(StudentListFragment.class,false); 或 _mActivity.popTo(StudentListFragment.class,false); 均没有任何反应

**Comment by YoKeyword** [comment]
这4个Fragment是怎么加载的呢？   同级的还是流式的

**Comment by qiyulan** [comment]
是使用 replaceFragment(SupportFragment,true) 加载的

2016-11-04 16:59 GMT+08:00 YoKey <notifications@github.com>:

**Comment by YoKeyword** [comment]
我刚模拟了你的场景：
A: replaceFragment(B, true)   B :replaceFragment(C, true)  C :replaceFragment(D, true)

然后D里popTo(B,false)  可以正常返回到B

**Comment by qiyulan** [comment]
StudentListFragment 是通过 activity 内 replaceLoadRootFragment(R.id.fragment,SupportFragment , false); 加载的

StudentListFragment 使用  replaceFragment(NewStudentFragment,true)加载了 NewStudentFragment

NewStudentFragment 使用 replaceFragment(LessonBuyFragment,true) 加载 LessonBuyFragment

LessonBuyFragment 调用  popTo(StudentListFragment.class,false); 无效
现在使用 popTo(NewStudentFragment.class, true); 是有效的

不知道是不是因为我的理解出现了错误.

**Comment by YoKeyword** [comment]
好乱...   你想达到什么效果呢

**Comment by qiyulan** [comment]
A 是 通过  activity 内 replaceLoadRootFragment(false) 加入的
A->B B->C C->D 都是通过  replaceFragment(fragment,true) 加载的

在 D 中使用 popTo(A,false) 无效,使用 popTo(B,true) 有效

**Comment by YoKeyword** [comment]
我想应该是 replaceLoadRootFragment(A，false) 没有加入回退栈，导致了popTo(A,false)无效

**Comment by qiyulan** [comment]
嗯嗯 那应该是我使用的错误
