### ISSUE TITLE
不支持fragment沉浸式？

### ISSUE THREAD

**Issue by SuperMan42** [YoKeyword/Fragmentation#137]

**Comment by YoKeyword** [comment]
库中这块没做任何处理

安卓中多FG的场景下沉浸状态栏 带固定颜色是可以的
但是一旦使用design包里的coord  就会有莫名bug  (你会发现知乎的带图片详情页也没做沉浸)

有解决方案，不过有点繁琐，以后有成熟的方案会分享下，目前我用的是临时方案

**Comment by Ludejin** [comment]
重新reset下toolbar的高度和padding是可以的，我就是这么解决的！

**Comment by YoKeyword** [comment]
@Ludejin  ＋1    我目前也是这种方式， 虽然感觉不是很优雅

**Comment by Ludejin** [comment]
@YoKeyword 嗯嗯，不是很优雅，如果有更好的方案希望分享下！嘻嘻！

**Comment by Gliop** [comment]
哈哈哈 大大按錯啦!!
肯定要支持的
原來之前支持過 又看到這篇想再按支持

2016-11-08 9:18 GMT+08:00 Jin丶 <notifications@github.com>:

**Comment by leguang** [comment]
@YoKeyword 请问一下你们所说的沉浸式或者透明状态栏不优雅的fragment的实现方案是指？
我现在也发现整个问题了，之前注意在4.4上的问题。

**Comment by YoKeyword** [comment]
现在不优雅得方案是  获取状态栏高度 然后手动给布局设置padding或margin

**Comment by leguang** [comment]
哦哦，谢谢，也只能是这么做了。
