### ISSUE TITLE
页面跳转做动画的时候，看到之前的页面

### ISSUE THREAD

**Issue by galileolvpo** [YoKeyword/Fragmentation#138]
![111](https://cloud.githubusercontent.com/assets/18024983/20049077/bac79302-a4fb-11e6-8553-7f1726da16f7.png)

up，我从红色框的页面跳转到绿色框的页面做动画的时候，可以看到蓝色框的页面，求解！

**Comment by YoKeyword** [comment]
你的场景应该是 栈顶FG A跳新FG B时，可以看到FG A 之前的那个FG的视图吧

好像正常情况应该不会发生这种情况 ＝。＝

或者贴下这2个Fragment跳转部分的代码？

**Comment by galileolvpo** [comment]
问题是解决了
还是上面的图，我从蓝色框的这个 子FG，跳转到红色FG用的 
RxBus.getDefault().post(new StartBrotherEvent(supportFragment));
在红色FG 跳转用的 start() ,这样会看到之前的蓝色FG页面，并且之后跳页面动画都会看到蓝色FG页面
刚才红色FG 跳转用了RxBus的方式，就ok了、 =。=
