### ISSUE TITLE
关于切换fragment，popwindow问题

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#139]
你好，我现在有这个场景，在切换底部TAB的fargment的某个tab上展示popwindow,这个popwindow在切换底部tab或者点击其他区域不消失。但是目前切换到不是底部的其他fragment也是跟随展示，这要怎么办？作者有处理过类似的吗？

**Comment by hcadoid** [comment]
popwindow 和 dialog估计是处理不了，只能先写个View了。

**Comment by YoKeyword** [comment]
popwindow默认好像是点击外侧区域 不会消失
解决方式的话 一种是setTouch啥的一个方法
一种是 主动调用其dissmiss  建议用第二种

**Comment by hcadoid** [comment]
我现在的业务就是不消失，但是start()另外的fragment的时候还是显示的。这种感觉用pop和dialog都不行了。

**Comment by Hell-And** [comment]
请问有没有碰到popwindow设置背景变暗后，弹出popwindow时会显示上一个activity或者fragment的界面。视图穿透了
