### ISSUE TITLE
proguard

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [YoKeyword/Fragmentation#14]
When i open proguard ，There are many issues
Like This:
 buildTypes {
        release {
            debuggable false
            minifyEnabled true  //是否开启混淆
            shrinkResources true //此属性配合minifyEnabled混淆使用
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            minifyEnabled true  //是否开启混淆
            shrinkResources true //此属性配合minifyEnabled混淆使用
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

**Comment by YoKeyword** [comment]
没明白你的意思，是提醒我把Library的buildTypes移除吗？  下次commit会把buildTypes、versionCode/Name移除   :)

**Comment by Lee-Wang-Jing** [comment]
开启混淆之后报错，这样就好了
![image](https://cloud.githubusercontent.com/assets/10808039/15490373/f428b10c-2199-11e6-8a10-da223f49a8f3.png)

**Comment by YoKeyword** [comment]
这样啊，太感谢啦，感谢指出 👍

**Comment by darylsze** [comment]
你這樣和整個library 沒做proguard 一樣，不如直接把proguard關了吧…

**Comment by YoKeyword** [comment]
@darylsze 后来并没有使用该方案， 仅keep了`FragmentManagerImpl`   :)
