### ISSUE TITLE
RT

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#141]
请问下，我在第一个Act1中，假如Act1中的F1-F2-F3-跳转到了Act2中,Act2中要销毁的时候，要重新再Act1中start fargment，同时要销毁其他的之前的fragment,这要怎么做，感觉处理起事务会很危险。。
现在的微信支付页面可能就是那个Act2。。。

**Comment by hcadoid** [comment]
还有种情况是：我在第一个Act1中，假如Act1中的F1-F2-F3-跳转到了Act2中,Act2中要销毁的时候，要重新再开启的Act3,此时需要把Act1中F都出栈，也会导致提交事务出问题。

**Comment by YoKeyword** [comment]
在AC1上使用popTo(F1,true,new Runnable(){在这里start新FG或其它操作})

**Comment by hcadoid** [comment]
你说的意思是：Act2销毁的同时，通知Act1调用上面的方法？  因为现在项目如果改的没有那么快都转Fargment。可能更多的是上面的第二种情况怎么处理：在Act2销毁的时候或者Act2销毁跳转到Act3中，那怎么让Act1中F全部出栈呢，发EventBus去通知Act1，可能也或导致事务提交失败的BUG，难道又要判断然后在onResume中处理，感觉太繁琐。

**Comment by YoKeyword** [comment]
> 通知AC1，然后设置标志位，最后在onResume中处理  
这个是跑不掉的，不然会报`Can not perform this action after onSaveInstanceState`

繁琐是有些，不过这种需求应该不会很多～

**Comment by hcadoid** [comment]
是的，现在只能先这样处理。我们的项目也不好做多Activity+多Fragment,因为很多模块都关联上了。谢谢你的回答。
