### ISSUE TITLE
Fragment already added:

### ISSUE THREAD

**Issue by weilixing00** [YoKeyword/Fragmentation#144]
当首页底部切换的几个tab页面有几个入口时,重复点击就报这个错.

**Comment by YoKeyword** [comment]
重复add啦～  可以参考下第2个demo

**Comment by weilixing00** [comment]
但是自己并没有用过add,主页跳转用的Eventbus, demo看过,但不是一样的场景

**Comment by YoKeyword** [comment]
start/  loadRoot方法内部 是add，  我想应该能定位到具体哪行代码，检查下重复add的原因

**Comment by weilixing00** [comment]
好的  谢谢  我看看
