### ISSUE TITLE
Attempt to write to field 'int android.support.v4.app.Fragment.mNextAnim' on a null object reference问题？

### ISSUE THREAD

**Issue by Destiny01** [YoKeyword/Fragmentation#145]

**Comment by YoKeyword** [comment]
先排插下动画原因： B页面的Fragment把转场动画都去掉

**Comment by Destiny01** [comment]
不是动画原因，1、在A页面的第一个Fragment跳转B页面的时候，B页面返回，直接返回到主页面了；
2、在A页面的第二个Fragment跳转B页面的时候，app直接报错崩溃Attempt to write to field 'int android.support.v4.app.Fragment.mNextAnim' on a null object reference

**Comment by Destiny01** [comment]
从主页面上的Fragment上到B页面返回没有这问题

**Comment by Destiny01** [comment]
A页面无论进入哪一个Activity，返回的时候都会报这个错误Attempt to write to field 'int android.support.v4.app.Fragment.mNextAnim' on a null object reference

**Comment by Destiny01** [comment]
已解决！
