### ISSUE TITLE
假如我用demo2的话，我看到作者你是用mainfragment装三个fragment。

### ISSUE THREAD

**Issue by catroom** [YoKeyword/Fragmentation#146]
是不是有点故意嵌套了。我就是想一个activity管理三个fragment而已。假如这么做的话，我getactvity会不会出问题。。假如想用一个mainactvity装三个fargement是不是要自己改一下。。求作者指教下。。

**Comment by YoKeyword** [comment]
你打开多个页面 然后观察下栈视图 就明白为何这么设计栈层级了

如果你的Activity下仅仅是几个同级的Fragment，是没必要这么嵌套的，但是如果你的单AC下有不同层级的Fragment，那嵌套是无法避免的

**Comment by catroom** [comment]
是啊，因为一般人都是主页面有fragment，我全程就是3个fragment

**Comment by YoKeyword** [comment]
😂   这个库主要是为重度使用Fragment，单Activity多Fragment之类的结构设计的

你的需求不涉及到不同栈层级 可以放到Activity里～

**Comment by catroom** [comment]
恩。我改改就用，直接去掉mainfragment用吧
