### ISSUE TITLE
stat()后的生命周期变化。

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#147]
类似微信的Demo，在底部的几个tab切换，在跳转到其他Fragment时候，stat()方法，这几个tab的生命周期都是不走的？？
有什么办法知道呢，比如：在第3个tab下，点击通知mainFragment去start(),之后第三个tab的fragment的没有调用到onResume或者onHiddenChanged方法，回来也是没调用onHiddenChanged，怎么知道生命周期变化呢。。

**Comment by YoKeyword** [comment]
`onResume()` `onStart()`是跟随宿主Activity的`onResume()` `onStart()`

`onHiddenChanged()`是同一栈层级跳转时，才有可能回调的

对应你的问题即：mainFragment去start()  mainFragment的`onHiddenChanged()`才会回调，其子FG是不会回调的，不过你可以通过EventBus等分发下
