### ISSUE TITLE
使用startWidthPop方法为什么界面会白一下

### ISSUE THREAD

**Issue by tenny1225** [YoKeyword/Fragmentation#148]
使用startWidthPop方法为什么界面会白一下

**Comment by YoKeyword** [comment]
什么场景呢   是任何情况下startWithFinish都会白一下还是某个特定场景下会这样
目前startWithFinish() 暂不支持最根部的fragment

**Comment by tenny1225** [comment]
@YoKeyword 不管是在activity和fragment使用startWidthPop都会出现这种情况，我看demo里面的recycleFragment不会出现这种情况，是因为使用了eventbus，不知道为什么，求解

**Comment by YoKeyword** [comment]
额 和Eventbus没啥关系的… 你再细看下demo  

你可以先写几个简单的demo页试试 (根部fg启动第二个fg不要使用startWithFinish)
