### ISSUE TITLE
如何监听fragment切换动画

### ISSUE THREAD

**Issue by duchengzhen** [YoKeyword/Fragmentation#15]
如果在fragment的onCreateView()或onViewCreated()方法中直接显示ProgressDialog或加载List,在过场动画的执行的时候会突然很明显的卡壳一下.有没有好办法解决?

**Comment by YoKeyword** [comment]
嗯 确实，在复杂Fragment页面，第一次start该Fragment时，动画会卡。
不管是通过事务的setCustomAnimations() 还是Fragment的onCreateAnimation() 这几种设置转场动画方式都有这个问题。 

生命周期顺序：onCreate -> onCreateView -> onCreateAnimation -> onActivityCreated

有种思路是给EnterAnim设置监听方法，在动画结束后再初始化View逻辑和请求异步数据（只在onCreateView里初始化Toolbar的标题等少量控件，避免动画过程中的Fragment页面是空白）

稍晚一会我会push针对这个的commit，添加addOnEnterAnimListener方法

**Comment by YoKeyword** [comment]
@duchengzhen 已更新，请pull最新的代码；  用例演示见：Demo的 DetailFragment
感谢你的反馈  :)
