### ISSUE TITLE
hideSoftInput问题

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#150]
你好，我在进页面调用了showSoftInput(editText);但是在离开页面的时候hideSoftInput 不掉！！

退出页面： setFramgentResult(RESULT_OK, bundle);
        pop();

在onHiddenChanged或者销毁页面隐藏无效。。。

**Comment by YoKeyword** [comment]
强制 调用hideSoftInput()试试，  还没遇到无法收起输入法的问题

**Comment by hcadoid** [comment]
强制调用过了，我是在页面隐藏的时候就调用了，但是没用，在其他页面又是可以的，感觉不出2个页面哪里有什么不同，但是就是hide不掉，现在用其他手段处理了。。

**Comment by YoKeyword** [comment]
这个页面肯定有毒……

**Comment by hcadoid** [comment]
哈哈，可能是的。。有时间我要好好观察下，实在不行就重新写次看看
