### ISSUE TITLE
怎么使用一个Activity多个Fragment的时候，状态栏各种变色

### ISSUE THREAD

**Issue by Sabirjan** [YoKeyword/Fragmentation#156]
怎么使用一个Activity多个Fragment的时候，状态栏各种变色（图片背景，颜色等）...

比如：类似这样的：

首页（Activity）
状态栏纯颜色

 某个详细页面（Fragment）
页面里面的某个图片的Blur样式

有没有参考的Demo

**Comment by Sabirjan** [comment]
没有用toolbar的情况下

**Comment by YoKeyword** [comment]
对于变 纯色和 图片，和Activity的方式无异。

但是要注意，在单AC多Fragment的情况下，状态栏是图片的情况下，需要特殊处理，可以参考
https://github.com/YoKeyword/Fragmentation/issues/137
