### ISSUE TITLE
Activity里面怎么获取当前的Fragment

### ISSUE THREAD

**Issue by Sabirjan** [YoKeyword/Fragmentation#157]
A Fragment 里 进入Fragment B后，点击返回按钮，我们在Activity的KeyDown事件里面获取getTopFragment() ，返回 B，而不是A。。。怎么获取A Fragment

**Comment by YoKeyword** [comment]
使用：
````java
AFragment a = findFragment(A.class);
````

**Comment by Sabirjan** [comment]
A-启动-->B-启动-->C  返回的时候 ，我们怎么判断当前的Fragment是 B

**Comment by Sabirjan** [comment]
这个方法getPreFragment 我怎么找不到啊

**Comment by YoKeyword** [comment]
C返回时，会回调B的`onHiddenChanged()` ，可以在B的该方法里执行你需要的操作

`getPreFragment()`是SupporFragment的方法，SupportAC里没有该方法。

**Comment by Sabirjan** [comment]
我把自己的问题通过getSupportFragmentManager().getBackStackEntryCount()==2这个方法来解决了。。。
等于2的时候，返回了我想要的Fragment
我的客户端层次结构比较复杂。。。谢谢你~！
-------------------------------------------------

**Comment by YoKeyword** [comment]
刚push了0.8.1版本 给 SupportActivity添加如下方法，可能对你有用：
````java
registerFragmentLifecycleCallbacks(FragmentLifecycleCallbacks callback){
    public void onFragmentSupportVisible(SupportFragment fragment) {}
    public void onFragmentAttached(SupportFragment fragment) {}
    public void onFragmentCreated(SupportFragment fragment, Bundle savedInstanceState) {}
    public void onFragmentHiddenChanged(SupportFragment fragment, boolean hidden) {}
    // ... 略 其他生命周期方法
}
````
一旦Fragment的生命周期被回调，FragmentLifecycleCallbacks里对应的方法也会被回调
