### ISSUE TITLE
showHideFragment()方法的问题

### ISSUE THREAD

**Issue by shlockfan** [YoKeyword/Fragmentation#158]
如果想用showHideFragment的方法就要知道哪个fragment可见，但是不一定都是用BottomBar这个控件（直接返回了可见和点击的），最好直接就是个showFragment的方法，在显示某个fragment之前隐藏所有的Fragment，而不必要知道当前哪个可见的需要隐藏

**Comment by YoKeyword** [comment]
从性能和资源角度来看，showHideFragment()处理好，可以避免不要的浪费

不过你的提议感觉也是有道理的，应该更自由，稍后会提供该方法 （正好在添加另外一项特性，会一并放入）

**Comment by YoKeyword** [comment]
刚commit了0.8.1， 提供了showHideFragment(SupportFragment showFragment) 接收一个参数，库内部帮你隐藏上一个Fragment

**Comment by shlockfan** [comment]
辛苦了，thanks for a beautiful library
