### ISSUE TITLE
如何选择一个好的方案兼容性为底部Tab添加角标呢

### ISSUE THREAD

**Issue by jan27th** [YoKeyword/Fragmentation#159]

**Comment by YoKeyword** [comment]
我实际项目是自己实现，在BottomBar上添加角标功能即可

另外Github上应该也有类似的开源项目，也可以直接拿来用

**Comment by jan27th** [comment]
谢谢，我自己在上面添加过角标，但效果以及更大的扩展性很一般，哈哈 也是我水平有限，也看到过star很高的BottomBar 但写法各不相同，想看下大神分享下这方面的实现@YoKeyword

**Comment by YoKeyword** [comment]
我刚push了一个commit，给WechatDemo里的BottomBar添加了：
演示性的设置未读消息角标 的方法：
````java
BottomBarTab tab = bottomBar.getItem(position);
tab.setUnreadCount(num);   // 设置未读消息数量
// int nume = tab.getUnreadCount(); 获取未读消息数量
````

**Comment by jan27th** [comment]
多谢大神，你的方案感觉灰常简单 学习了
