### ISSUE TITLE
你好，请问一下compile 'me.yokeyword:fragmentation-swipeback:0.3.0'和你的另一个项目compile 'me.yokeyword:swipebackfragment:0.1.1'有什么区别吗？

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#16]
请问一下compile 'me.yokeyword:fragmentation-swipeback:0.3.0'和你的另一个项目compile 'me.yokeyword:swipebackfragment:0.1.1'有什么区别吗？
我在Fragmentation中最好引用哪个？

**Comment by YoKeyword** [comment]
@leguang 如果你有用Fragmentation库的话（它是帮助你深度使用Fragment的封装库），并且想在Fragmentation的基础上使用滑动返回功能，你需要再依赖fragmentation-swipeback这个库；

如果你没有使用Fragmentation库，是自己处理Fragment的一些操作，想让Fragment具备滑动返回功能，就只需依赖swipebackfragment这个库即可     :)

**Comment by leguang** [comment]
非常感谢，向你学习
