### ISSUE TITLE
Bug : Tab显示异常

### ISSUE THREAD

**Issue by metromancn** [YoKeyword/Fragmentation#160]
首先感谢YoKeyword的Fragmentation，我们在新版本"地铁通-MetroMan"中使用了这个框架的0.7.13版本，今天看到0.8发布了，恭喜，顺便说下这个框架太棒了。
http://android.myapp.com/myapp/detail.htm?apkName=com.xinlukou.metroman

然后提一个BUG：
比如我们有Tab1, Tab2, Tab3，希望app启动后的首页面是Tab2，使用了这个方法。
loadMultipleRootFragment(R.id.container, Tab2, mFragments[Tab1], mFragments[Tab2], mFragments[Tab3]);
这个方法确实显示了Tab2，但是BottomView还是Focus在Tab1上，需要再次调用mBottomBar.setCurrentItem(Tab2);才行。

**Comment by YoKeyword** [comment]
😄  感谢反馈，因为BottomBar这个组件不是Fragmentaion的一部分，只是一个小组件，所以手动调用是不可避免的哈～

另外，如果在使用过程中有任何痛点或者问题 随时提issue哈 😊～

**Comment by metromancn** [comment]
原来如此，感谢大神回复。
