### ISSUE TITLE
SupportActivity的start方法属性调用不到

### ISSUE THREAD

**Issue by Marsboxiao** [YoKeyword/Fragmentation#161]
今天刚刚知道Fragmentation，感觉非常的好，想要研究一下，发现在start方法，@SupportFragment.LaunchMode，属性由于在其他的class之中，导致无法正常调用。

**Comment by YoKeyword** [comment]
在SupportActivity里start(A.class, SupportFragment.SINGLETASK)  这样就可以啦
调用SupportFragment.xxx即可～
