### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by pye52** [YoKeyword/Fragmentation#162]
按返回键回到桌面，点击任务栏的图标进入app
再打开fragment就会有报错了，但是点击桌面的图标进入就没事…
[demo](https://github.com/pye52/FragmentationDemo)

**Comment by pye52** [comment]
额…解决了，onstop的时候把eventbus的事件注销掉，onresume再注册回来就好了…
已经用rxbus代替eventbus…

不过想知道一下为什么会发生这种问题，是任务栏启动的act已经不是原来那个act了？

**Comment by YoKeyword** [comment]
先提醒下rxbus是有些小坑的～

首先还是保证在onStop后不要再执行Fragment事务～

> 任务栏启动的act已经不是原来那个act了？
安卓上 第一次使用**包管理器**打开后（包括使用AS安装），点Home回到桌面，此时 在任务栏打开和从桌面图标打开 行为是不一样的...

**Comment by pye52** [comment]
额，问题出现在，从任务栏回到主界面再打开fragment的话必定会报错
这时候onstop应该是没有执行的(或者说是上一个mainact的onstop执行了，新的mainact执行了onresume)
由于是从oncreate的时候注册的eventbus，可能是将event发送到上一个mainact了？
> 退出后，以后就正常了
请问意思是只要将app完整退出之后，从任务栏打开和从桌面图标打开的行为都是一样了么？

**Comment by YoKeyword** [comment]
任务栏 本身是一个app  你到任务栏的界面 就代表你的app走了onStop   建议这种东西打log调试…

**Comment by pye52** [comment]
额…可能你理解错了，流程是这样

mainact => fragmentA (没问题)
mainact => 桌面 => 通过任务栏回到mainact => fragmentA (报错)
mainact => 桌面 => 通过桌面图标回到mainact => fragmentA (没问题)

在打开fragmentA的时候都能确定没有onstop

**Comment by YoKeyword** [comment]
... 转晕了  我刚运行你的demo，没复现你描述的崩溃情况～
是已经解决了吗～

**Comment by pye52** [comment]
抱歉…是我弄复杂了，我录个图

**Comment by pye52** [comment]
[gif](http://hoop8.com/1612A/YsDJKi5l.gif)

(1)从任务栏打开的act，会经过oncreate
(2)从桌面图标打开的act，只会走onresume

解决办法：
将act设置为singletask就可以了…
如不设置singletask，那么在onstop的时候解绑eventbus的事件，在onstart时后再绑定

**Comment by YoKeyword** [comment]
那个不是任务栏，是通知栏～
你点返回键退出了app，然后从通知栏打开，走onCreate()是正常的...

总之解决了就好...
