### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#164]
在线上版本统计来看，出现在了TAB切换的时候，用的是内部的showHideFragment方法

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	android.support.v4.app.m.x(Unknown Source)
	android.support.v4.app.m.a(Unknown Source)
	android.support.v4.app.g.a(Unknown Source)
	android.support.v4.app.g.a(Unknown Source)
	me.yokeyword.fragmentation.a.a(Unknown Source)
	me.yokeyword.fragmentation.SupportFragment.a(Unknown Source)
ui.main.fragment.MainFragment$2.a(Unknown Source)
view.bottomNavigation.BottomNavigationBar.a(Unknown Source)
	view.bottomNavigation.BottomNavigationBar.a(Unknown Source)
	view.bottomNavigation.BottomNavigationBar.a(Unknown Source)
bottomNavigation.BottomNavigationBar$1.onClick(Unknown Source)
	android.view.View.performClick(View.java:4457)
	android.view.View$PerformClick.run(View.java:18491)
	android.os.Handler.handleCallback(Handler.java:733)
	android.os.Handler.dispatchMessage(Handler.java:95)
	android.os.Looper.loop(Looper.java:136)
	android.app.ActivityThread.main(ActivityThread.java:5336)
	java.lang.reflect.Method.invokeNative(Native Method)
	java.lang.reflect.Method.invoke(Method.java:515)
	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
	dalvik.system.NativeStart.main(Native Method)

**Comment by YoKeyword** [comment]
该异常是Activity在回调`onSaveInstanceState()`后再进行Fragment事务导致的；

1、出现该异常的概率是低还是高，如果是高，则需要检查代码是否在`onSaveInstanceState()`后执行了Fragment事务，需要避免这种行为，应当下次回到该Activity时再去执行～

2、如果概率比较低，我相信是极低概率发生的。比如会发现是用户点击某个按钮后爆了该异常，而理论上用户可以点击的情况下，应该不会调用`onSaveInstanceState()`，因为`onSaveInstanceState()`是在onPause()后onStop()前调用～
而此时发生该异常的原因可能是 某些机型 在某些特殊情况导致的，因为showHideFragment()方法的提交方式是 `commit()`，这是一个异步方法，这个异步过程导致了该异常～  当然这种发生概率极低～

如果是第2种，此时建议使用 官方提供的“最后的方案”，使用`commitAllowingStateLoss()`方式提交，目前当前0.8.1还不支持设置showHideFragment()的commit方式； start()已经支持～  

稍后会考虑这个问题，支持设置commit方式~

**Comment by shingohu** [comment]
@YoKeyword 你好 我的是在loadMultipleRootTransaction的时候出现同样的问题,我跟到源码里面看了这里没有更改为commitAllowingStateLoss

**Comment by YoKeyword** [comment]
确认下 是否在执行`loadMultipleRootTransaction()`的时候，Activity在“离开”状态（即已调用onSaveInstanceState()方法）

loadRoot系列方法应该不会有 我在2楼描述的 那种特殊场景～

**Comment by shingohu** [comment]
@YoKeyword 
hello 帮忙看下怎么处理
![image](https://cloud.githubusercontent.com/assets/4944887/20916511/1ce1102c-bbc7-11e6-8411-13e6aa9f6501.png)




java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1533)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1551)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
	at me.yokeyword.fragmentation.Fragmentation.loadMultipleRootTransaction(Fragmentation.java:104)
	at me.yokeyword.fragmentation.SupportFragment.loadMultipleRootFragment(SupportFragment.java:535)
	at cn.com.bigknow.trade.pos.Immediate.app.fragment.TJFragment.initFragments(TJFragment.java:54)
	at cn.com.bigknow.trade.pos.Immediate.app.fragment.TJFragment.onEnterAnimationEnd(TJFragment.java:45)
	at me.yokeyword.fragmentation.SupportFragment$1.run(SupportFragment.java:438)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5616)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by YoKeyword** [comment]
@shingohu 是必现的异常吗

**Comment by shingohu** [comment]
@YoKeyword 后台记录应该不是的,主Activity loadMultipleRootFragment没问题,出问题的是主Activity里面的Fragment 嵌套loadMultipleRootFragment 出问题,bugtag统计还算频繁吧

**Comment by YoKeyword** [comment]
问一下， 你的主Activity里面的Fragment的初始化是否有 **申请权限** 的操作

**Comment by shingohu** [comment]
代码中没有任何申请权限的操作

**Comment by shingohu** [comment]
@YoKeyword 有没有什么办法临时处理下,或者开放一个loadMultipleRootFragment的方法出来,使用commitAllowingStateLoss提交

**Comment by YoKeyword** [comment]
@shingohu 好的，我需要归纳下这个问题的原因，最近发现这个异常并没有想象中的简单，一些理论上不可能发生的场景有时也报了该异常。 

一种猜测是 国产ROM的申请权限等悬浮框引起的，另一种则和某些机型某些ROM有关，需要深度调研下，鉴于这些不可控的场景，我可能会对库的一些commit机制重新设计，保证可以避免这个坑。


先给你提供一个临时的解决方案：
````java
    private boolean initable = true;
    private boolean mInited;

    @Override
    protected void onEnterAnimationEnd(Bundle savedInstanceState) {
        if (!mInited && initable) {
            mInited = true;
            initFragments();
        }
    }

    @Override
    public void onResume() {
        super.onResume();
        if (!mInited) {
            mInited = true;
            initFragments();
        }
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        initable = false;
    }
````

**Comment by shingohu** [comment]
好的 万分感谢

**Comment by shingohu** [comment]
这个不是需要判断savedInstanceState是否为空的？initFragments没有传入啊

**Comment by YoKeyword** [comment]
全局变量保存下，如果不急，可以等新版本，最迟明天 :)

**Comment by shingohu** [comment]
好的,等你好消息

**Comment by YoKeyword** [comment]
@shingohu 
嗯 好的，感谢提供信息～

已经Push 0.8.4版本，`commit()`都改为`commitAllowingStateLoss()`，提升特殊情况下的稳定性；

对于一般情况（开发者自己的代码原因，导致事务在`onSaveInstanceState()`后提交，为了使开发者留意该异常，会打印如下的Log异常警告：
````
// 该行提示下个版本添加
E/Fragmentation: Please beginTransaction in onPostResume() after the Activity returns.

W/System.err: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState!
W/System.err: at me.yokeyword.fragmentation.Fragmentation.supportCommit(Fragmentation.java:311)
W/System.err: at me.yokeyword.fragmentation.Fragmentation.loadMultipleRootTransaction(Fragmentation.java:104)
略
````
