### ISSUE TITLE
在HomeFragment点击进入了N个Fragment，怎么返回到HomeFragment?

### ISSUE THREAD

**Issue by CharlesMing** [YoKeyword/Fragmentation#165]
在HomeFragment点击进入了N个Fragment，怎么返回到HomeFragment？

**Comment by YoKeyword** [comment]
可以`HomeFragment.popTo(HomeFragment.class ,false)`

不过建议在HomeFragment的父层处理：
若HomeFragment的父亲是Fragment调用`popToChild(HomeFragment.class ,false)`
若HomeFragment的父亲不是Fragment而是Activity，则调用`SupportActivity.popTo(HomeFragment.class ,false)`

**Comment by CharlesMing** [comment]
使用popTo可以返回到HomeFragment，但是我怎么获取返回的值呢?我使用setFramgentResult和putNewBundle不行...

**Comment by YoKeyword** [comment]
嗯 当前setFramgentResult()不支持popTo方式～ 仅推荐在简单场景使用

跨Fragment的交互，建议用EventBus

这块打算未来使用一种观察者模式来实现类似事件总线的东西来代替

**Comment by CharlesMing** [comment]
OK 时刻保持关注

**Comment by YoKeyword** [comment]
对了，忘说了～
`putNewBundle()`是可以把数据带给HomeFragment的，使用SingleTask模式启动即可：
````java
HomeFragment fragment = findFragment(HomeFragment.class);
Bundle newBundle = new Bundle();
// newBundle.putxx 数据
start(fragment, SupportFragment.SINGLETASK);
````
在HomeFragment的onNewBundle()可接收到数据:
````java
    @Override
    protected void onNewBundle(Bundle args) {
        // args 即数据
    }
````

**Comment by CharlesMing** [comment]
原来是这么使用的，研究了半天。

**Comment by AqiuBeats** [comment]
@YoKeyword 我使用popToChild(HomeFragment.class ,false)的方式跳转到主页面,但转场动画失效了,返回的时候有点突兀,是什么原因呢>?

**Comment by YoKeyword** [comment]
@AqiuBeats popTo系列方法 确实没有动画， 原因是pop很多个Fragment时会卡顿，而且有其他不可控原因...

**Comment by AqiuBeats** [comment]
@YoKeyword 我如果使用start(LiveFragment.newInstance(), SINGLETASK)返回主界面也和popTo一样的效果,也是没有动画的,这种返回方式允许吗?

**Comment by YoKeyword** [comment]
嗯 一样的 正常…  这两个方法以前版本有动画 
后来因确实容易导致一些问题 就把动画移除了
