### ISSUE TITLE
Pop Fragment后recyclerview刷新无效

### ISSUE THREAD

**Issue by LichFaker** [YoKeyword/Fragmentation#166]
从Fragment A跳转到Fragment B，回退后刷新A上的数据，但是界面没有更新，点击了跳转的按钮后界面才正常更新

**Comment by YoKeyword** [comment]
这个正常情况下应该没问题的～

可以把回退后刷新的代码贴一下吗？

**Comment by LichFaker** [comment]
sorry，不是框架的问题，是因为用了buck编译，有缓存没有更新，重启IDE后运行就正常了
