### ISSUE TITLE
如何监听fragment是否在前台

### ISSUE THREAD

**Issue by shuiyouwen** [YoKeyword/Fragmentation#168]
我需要知道fragment是否被用户可见，然后搞一些事情。。
于是我尝试用onHiddenChanged方法去做fragment是否可见的回调逻辑，但是这方法只有在调用show hind方法时才会生效，而我使用框架的start方法是通过add取添加fragment的，所以不生效。。
想问下有什么办法可以知道fragment是否被用户可见
谢谢！^ ^

**Comment by YoKeyword** [comment]
0.8.X的新特性之一： onSupportVisible()/onSupportInvisible()
当Fragment对用户可见（真正的可见）时回调～

**Comment by shuiyouwen** [comment]
3q ^ ^.

**Comment by shuiyouwen** [comment]
fragment第一次加载的时候onSupportVisible()也会被调用，这会导致我在界面可见时的逻辑在fragment第一次加载的时候调用两次。
我想的是设置flag来保证逻辑只被调用一次。。想问问 除此之外还有别的方法吗

**Comment by YoKeyword** [comment]
没有诶，自己设个flag吧～
不然onSupportVisible()的意义就不准确了～

**Comment by shuiyouwen** [comment]
好的，谢谢
