### ISSUE TITLE
popTo(Class fragmentClass, boolean includeSelf, Runnable afterTransaction)

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#169]
popTo(ReplenishClassFragment.class, false, new Runnable() {
            @Override
            public void run() {
                start(ReplenishRecordFragment.newInstance(classId));
            }
        });
a-b-c  c完成后，把b和c同时出栈，开始d.   上面的ReplenishClassFragment是a  ReplenishRecordFragment是d.
报错下:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.support.v4.app.FragmentManager.getFragments()' on a null object reference

不是这样操作的吗？？还是popTo(Class fragmentClass, boolean includeSelf, Runnable afterTransaction)只能在d的初始化里面去使用？

感觉startWithPop又不同同时出栈多个？

**Comment by YoKeyword** [comment]
我猜测你在C里使用了popTo()， 即:
````java
c.popTo(a.class, false, () ->{
   // 注意这里， 此时你的C已经出栈销毁了（FragmentManager=null）
   // 继续调用start (这里因为在C里调用，即c.start(XXX))自然就报错了
   start(XXX);
})
````

你可以在Runnable里使用a.start(XXX)； 一般的话建议在C的父亲里使用popToChild()

> startWithPop()  是启动新的Fragment，同时关闭自己；等同于 
````java
activity.startActivity(B);
activity.finish();
````

**Comment by hcadoid** [comment]
是的，我所有的页面都是同级的，c里面确实使用的是popTo销毁后开启d,那popTo(Class fragmentClass, boolean includeSelf, Runnable afterTransaction)的使用场景是在哪里？ 

我现在是在c先pop掉了a以上的，之后再d返回的时候在销毁中间的b的，可以实现就是动画效果没有了。

**Comment by YoKeyword** [comment]
`popTo(Class fragmentClass, boolean includeSelf, Runnable afterTransaction)`使用场景是 出栈多个Fragment，并且出栈后想立即进行下一个Fragment事务~

popTo因一个性能问题移除了动画效果～

**Comment by hcadoid** [comment]
好的，作者有遇到下面的bug吗？ 我在monkey测试的发现，我看网上有些解决方案，fragment里面处理了吗
java.lang.IllegalStateException: Activity has been destroyed
	android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
	android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:617)
	android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:139)
	android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
	android.support.v4.view.ViewPager.populate(ViewPager.java:952)
	android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
	android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	android.view.Choreographer.doCallbacks(Choreographer.java:574)
	android.view.Choreographer.doFrame(Choreographer.java:543)
	android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	android.os.Handler.handleCallback(Handler.java:733)
	android.os.Handler.dispatchMessage(Handler.java:95)
	android.os.Looper.loop(Looper.java:136)
	android.app.ActivityThread.main(ActivityThread.java:5032)
	java.lang.reflect.Method.invokeNative(Native Method)
	java.lang.reflect.Method.invoke(Method.java:515)
	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	dalvik.system.NativeStart.main(Native Method)

**Comment by YoKeyword** [comment]
宿主都已经销毁啦， 再操作Fragment就会报该错误；
自己留意下，在离开Activity时及时把异步任务停止。

**Comment by hcadoid** [comment]
全局一个Activity,Activity的没有异步，fragment中的异步都在onDestroyView取消了，看问题是出现在getChildFragmentManager的ViewPager切换的子Fragment里面，这里面的子Fragment是在onDestroy取消异步的一些请求的，应该也不是导致这个错误，我再观察下。
