### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by Hiram-Y** [YoKeyword/Fragmentation#170]
能加个qq好友吗？我打算用这个用到商业项目上，类似于京东金融的聚合app，方便以后有问题能够急事请教您

**Comment by leguang** [comment]
哈哈，我也要加。
这位仁兄回答issue是很积极的，基本有问必答，很及时。

**Comment by YoKeyword** [comment]
😂   QQ：328903522    （ 仅限Fragmentation相关的交流）
