### ISSUE TITLE
EventBusIndex 没有提交吧？

### ISSUE THREAD

**Issue by xiaoshi316** [YoKeyword/Fragmentation#171]
me.yokeyword.sample.EventBusIndex  这个类是否是忘记提交了呢？

**Comment by jp1017** [comment]
编译下就会生成的...

**Comment by YoKeyword** [comment]
这个Index类是EventBus3.0的新特性 你编译下即可生成

**Comment by xiaoshi316** [comment]
谢谢啦！囧， 没用过这个EventBus3.0 ，谢谢啦。

**Comment by xiaoshi316** [comment]
谢谢啦，已经生成！


发自网易邮箱大师
在2016年12月13日 09:50，YoKey 写道:

这个Index类是EventBus3.0的新特性 你编译下即可生成

**Comment by xiaoshi316** [comment]
谢谢啦，已经生成
发自网易邮箱大师
在2016年12月13日 09:49，蒋朋 写道:

编译下就会生成的...
