### ISSUE TITLE
BottomBar和fragment中控件同时点击时，事件处理出现问题

### ISSUE THREAD

**Issue by huangdh2** [YoKeyword/Fragmentation#173]
在fragment中有一系列的控件，对应不同功能。当同时点击fragment中控件和BottomBar切换视图时，会出现fragment覆盖或者卡死的情况。该现象在demo实例仿知乎里面也会出现，同时点击BottomBar的商店和新闻列表的一个item，直接卡死程序

**Comment by YoKeyword** [comment]
感谢反馈 是防抖机制在同时点击处理fg事务时 失效了 待会看下
点下back就会恢复

**Comment by huangdh2** [comment]
我现在使用的是0.7.13版本，0.8的目前不清楚是否会有类似情况

**Comment by YoKeyword** [comment]
🙏  已经发现问题的原因了：
在同一时间操作AB事务，当A的栈层级比B高时（体现在Demo上就是 A是切换Tab，B是子Fragment点击跳转），此时会执行A后，B的动画会被阻塞住，在下次回到B时才会执行；

而Fragmentation的防抖动逻辑放到了start时，而在动画结束时取消防抖动；
所有虽然B已经在栈内，但是因为B的动画还没开始，所以就没有取消防抖动，从而导致防抖动失效，点击无响应的问题，刚刚push了新版本0.8.5，已经修复～

另外同时点击不同栈层级的可能会导致Fragment覆盖，该问题是官方Fragment自身的机制，这个没有办法； 毕竟同时点击按钮的这种操作行为不属于正常行为 😅～

**Comment by YoKeyword** [comment]
新的版本虽然解决了 切换的问题 但是引发了一些其他的同时点击问题， 暂时还是建议回滚到0.8.4

周末会重新解决该问题 ！

**Comment by YoKeyword** [comment]
Hi，建议升级到0.9，解决多点触控问题~
 该大版本主要:
 * 修复了存在的BUG
* 提升兼容性
* 解决多点触控
* 完善SharedElement
