### ISSUE TITLE
嵌套ViewPager出现FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by LichFaker** [YoKeyword/Fragmentation#174]
外层布局Tab切换，其中一个`Fragment` A中也存在tab，使用`Viewpager`，当A中的`Viewpager`正在刷新数据时，切换外层tab，出现异常`FragmentManager is already executing transactions`，初步估计是`transactions`冲突引起，我将其中一个`transactions`做延迟处理后，暂未出现异常

**Comment by YoKeyword** [comment]
嗯 这种场景需要自己处理下 其实有提供了一个enqueueAction的方法 使任务放到主线程队尾

**Comment by ZuYun** [comment]
原因是第一次getFragmentManager()获取到的FragmentManager，只提供给activity那一层使用。 
在viewPager那一层只能使用getChildFragmentManager()获取FragmentManager来处理子fragment。

试试getChildFragmentManager()吧
