### ISSUE TITLE
ripple无效问题

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#175]
当start()时，ripple的点击效果无效了?

**Comment by YoKeyword** [comment]
start时，当前Fragment会立即处于hidden状态，即View本身已经隐藏了，看到的仅仅是转场动画；ripple本质是属性动画，而v4包的Fragment转场动画是View动画，所以ripple看起来是没有效果～

其实我觉得这个不必担心，因为Fragment的跳转非常快速，点击的ripple效果也不能来得及看清～
如果实在很在意，可以自定义普通的selector～

**Comment by hcadoid** [comment]
好吧，只能取舍了。
还有个问题是对于0.8X的库拦截了Can not perform this action after onSaveInstanceState异常。
举个例子：
拿你Demo来说，我在微信的里面，跳转到一个新的Activity中，其次在跳转到微信的Act(不是singleTask模式)而是默认的开启个新的，此时微信里面跳转Fragment就会进去到这个异常里面Please beginTransaction in onPostResume() after the Activity returns!
这种情况的话，没能满足真实的场景。

**Comment by YoKeyword** [comment]
这个是因为EventBus的原因，WeChat里的Demo的Fragment跳转是通过EventBus分发的，**你在新的AC里跳转FG时，旧的AC也收到了Event**，旧的也立即进行了跳转，但是旧AC已经是不可见状态了～ 

真实场景下EventBus科学使用可以避免这个问题～

**Comment by hcadoid** [comment]
哦，对谢谢回答

**Comment by sumaro** [comment]
@YoKeyword 有没有什么办法解决start()时，ripple的点击效果无效的问题,我这边使用startDontHideself()会导致在多级fragment中bottomsheet会失效

**Comment by YoKeyword** [comment]
Fragment的机制是无法让官方Ripple显示的，`startDontHideself()`不建议使用，因为它会让启动方Fragment不hide，这样会导致后续的绘制压力越来越大，打开多个页面时会明显掉帧甚至卡死

如果非要追求Ripple， 可以在点击时展示Ripple，Ripple效果结束时再跳转，有相关3方库可以实现， 当然自己实现也很简单
