### ISSUE TITLE
有个问题请教下

### ISSUE THREAD

**Issue by shlockfan** [YoKeyword/Fragmentation#176]
虽然不是用博主的库，但是是维护很久的老项目了不便更改，首页使用fragment add hide show方法做了类似三个tab切换的效果。当三个都切换一遍，再点击回第一个，这时跳到其它页面（二级页面）用addToBackStack方法，当这个二级页面要关闭时调用popBackStack，此时出现第三个fragment闪了一下，然后才出现第一个，正常首页的第三个应该是hide的状态，为什么会这样?

**Comment by YoKeyword** [comment]
猜测应该是栈层级问题，暂时命名 Tab Fragment:ABC， 二级Fragment: D
下面2种栈设计方案是建议的：

1、A是一个空容器Fragment，原A的内容放到Fragment E这个子Fragment里，由E跳D，ABC依然同级，DE是同级，同时DE是A的子Fragment

2、ABC之上创建父FragmentS，点击A时，由S跳E，这样SE是同级，ABC同级，ABC是S的子Fragment

**Comment by shlockfan** [comment]
我用了你建议的第二种方法，但是现在ABC的fragment就没有生命周期了，当E被pop时，我希望ABC里有类似可见时刷新消息数的操作因为S只是盖在ABC上所以pop之后ABC里什么都没执行

**Comment by YoKeyword** [comment]
第一种方案最简单 具体还要看你的场景
你说的问题原因是 onHiddenChanged只在同级栈内进出时回调  比如S会收到 然后你需要分发给ABC 
建议看下相关文章
