### ISSUE TITLE
pop和start同时操作，卡死

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#177]
类似 #173  的问题，用的是0.8.5的，但是在pop和start同时操作的时候，2个页面属于同级，会出现页面卡死。

**Comment by YoKeyword** [comment]
诶？  防抖动理论上不会有问题了啊~

同级的pop和start同时执行？ 是个矛盾的事务流啊 有先后顺序的话 后一个操作应该放到使用enqueueAction里执行 即放到队列尾
什么需求呢 ？ 
代码贴下看看

**Comment by hcadoid** [comment]
是测试那里的跑money提出的bug，我测试确实有这个问题， 就是在同一个页面，有一个返回键，一个跳转的按钮，返回的操作就是pop ,跳转就是start ，2个事务同时就卡死了

**Comment by YoKeyword** [comment]
嗯 重现了，现在防抖动在入场动画的时候开启 动画end时关闭

应该是start pop很快速度执行时  入场动画没有走end

感谢反馈 周末会解决下 今晚和明天有事不在电脑旁

同时会思考怎样万全保证 正常解除防抖动

**Comment by hcadoid** [comment]
是的，fragment有很多这样极限问题，由于这个我又测试了页面有Dialog的情况，在同时返回的时候，弹出的Dialog，如果Dialog处理一些敏感的就会崩溃，我也在考虑这要怎么做仿抖动。ps:即使在页面销毁Dialog隐藏也是会极端出现。

**Comment by YoKeyword** [comment]
这块我会重点测极限情况的, 防抖动的加入还是为了稳定支持转场动画,所以还是需要一个万全的方案

dialog的宿主是AC 和fg事务应该无关啊  另外当前库不建议用dialogFagment，因为还没考虑这个

**Comment by hcadoid** [comment]
不是dialogFagment，就是dialog,就是因为dialog是跟随宿主的Activity的，但是dialog处理是fragment的逻辑，极端情况下会出现F销毁，但是 dialog没有消失，就会出问题。这可能需要我们自己去做仿抖动操作的了。

**Comment by YoKeyword** [comment]
建议 先回滚到0.8.4的版本  那个版本的处理方式会更稳定
我这边readme也更改下

**Comment by YoKeyword** [comment]
还是要库来做的 防抖动机制需要完善

**Comment by hcadoid** [comment]
dialog就是上面说的可以替换上面的跳转button, 其实就是多点触控的问题导致，现在是用android:splitMotionEvents=”false”把这个操作禁止可以避免。大家遇到这个问题也可以这样做。

**Comment by YoKeyword** [comment]
push了 0.8.6， 防抖动应该不会再失效了，这次的原因是极快速度先start再pop,导致入栈动画只执行了`onAnimationStart`而没有执行`onAnimationEnd`，从而引起防抖动失效～

但是同时也发现了如果极快速度先pop再start，这样会有问题，因为官方Fragment天生不支持 同一个Fragment内调用pop接着start， 接下来会尽快解决该问题， 0.9版本会着重优化当前的一些API，Fix一些极端情况的BUG～

**Comment by YoKeyword** [comment]
push了0.9.0，  多点触控完全解决了～ 同时该大版本主要修复了存在的BUG，提升了兼容性，建议升级～
