### ISSUE TITLE
关于系统配置改变后activity销毁重建的问题

### ISSUE THREAD

**Issue by ethanhua** [YoKeyword/Fragmentation#178]
机型：小米5 android6.0
问题1：
在打开app并进行一系列fragment跳转后停留在fragmentB,然后在设置里面改变语言或者字体后 从最近任务栏点击进入之前打开的activity 并不能恢复到framgnetB 而是activity的第一个fragment，此处fragmentmanager为何没有去恢复之前创建过的一系列fragment？
问题2：
在问题1中如果能正确恢复到fragmentB,但是也会重新去走fragment的生命周期，会去重新执行网络请求，重新加载之前加载完的各种资源，这样会不会对用户体验不太好？楼主对于这种
http://www.jianshu.com/p/53bfd7206c66 处理方式有何见解？

**Comment by YoKeyword** [comment]
1、 系统会帮你保存离开前的Fragment，恢复时按栈内顺序恢复，你的情况可以通过打印栈内Fragments来观察

2、如果你指的是旋转屏幕等引起的页面被强杀， 视图必然会重新销毁创建，因为页面的展示都不同了，对于已经加载的数据，你完全可以使用你引用的链接方式来恢复；或者通过onSaveInstanceState来保存恢复

**Comment by ethanhua** [comment]
@YoKeyword  切换语言后从最近任务栏中点击App 打印日志的结果如下： 
   aty ondestory -> fragmentA ondestoryview ->fragmentB ondestoryview ->aty oncreate->fragmentA oncreateview->fragmentB oncreateview->aty ondestory->fragment A,B ondestrotyview 页面表现为点击后闪了一下 没有进入到App中 为什么aty在销毁重建后会再次销毁掉？ strictmode 日志显示我的主activity在同一时间段有两个实例：StrictMode: class com.luling.yuki.activity.MainActivity; instances=2; limit=1

**Comment by YoKeyword** [comment]
建议 重新问题简化  写一个小Demo，然后观察
