### ISSUE TITLE
有几个使用小问题，希望能帮助一下。

### ISSUE THREAD

**Issue by Marsboxiao** [YoKeyword/Fragmentation#179]
1.我的需求是一个tablayout和viewpager，这个正常的话，他是有个缓存的，但是网上说有个懒加载的方法，但是项目里提供了一个懒加载的方法，有点懵了，不知道应该怎么写了。如果方便的话，麻烦您给说一下应该怎么写，或者给点思路。。。
2.还有一些方法像onSupportVisible，onSupportInvisible，isSupportVisible用法比较模糊，dome里也又点乱，这些方法找不到使用的地方，可以的话麻烦给说一下，这些调用方法使用的例子。

**Comment by YoKeyword** [comment]
onLazyInitView()  就是懒加载方法，适用于你的场景

onSupportVisible 是该Fragment对 用户 可见时回调，该方法是Fragment的`onHiddeChanged` + `setUserVisibleHint`的结合方法：
1、因为在ViewPager下`setUserVisibleHint`起作用，`onHiddeChanged`无作用；  在add/show/hide时`onHiddeChanged`起作用，`setUserVisibleHint`无作用；
2、`onHiddeChanged`等系统的回调方法，只在同一栈层级起作用，比如子FragmentA的父FragmentB `start`一个FragmentC， 当C `pop`时，B可以接收到`onHiddeChanged`的回调，但是子FragmentA是不会回调任何方法的；而有了onSupportVisible，只要Fragment对用户是可见的，就会回调，即C `pop`时，A B都会回调onSupportVisible

onSupportInvisible同理，isSupportVisible获取是否对用户可看

**Comment by Marsboxiao** [comment]
谢谢作者，我大概是明白了。
