### ISSUE TITLE
如何解决fragment重复加载问题？

### ISSUE THREAD

**Issue by lylzwsy** [YoKeyword/Fragmentation#18]
我根据你的demo调用的。
  MainFragment_ mainFragment = findFragment(MainFragment_.class);
                        if (mainFragment == null) {
                            popTo(MainFragment_.class, false, new Runnable() {
                                @Override
                                public void run() {
                                    start(MainFragment_.newInstance());
                                }
                            });
                        } else {
                            // 如果已经在栈内,则以SingleTask模式start
                            start(mainFragment, SupportFragment.SINGLETASK);
                        }

首页好像是不自动加载了，但是切换到其它同级Fragment时候，每次都要重新加载，用Fragmentation可以解决吗？求解答，急~~万分感谢！

**Comment by YoKeyword** [comment]
@lylzwsy 看你的描述，你的是同级的使用场景，不是流程式的；（类知乎）你想做到这个效果的话需要这样：

我假设你还有另外2个同级模块，AFragment和BFragment，那么你的Activity层的Fragment栈内应该只有3个Fragment，Main、A、B。 这3个Fragment仅仅是容器作用，MainFragment里的内容是它的子Fragment，向里面流程式跳转的话，就是子Fragment之间的跳转；
你可以想象各个模块之间的切换是很复杂的，嵌套关系要理清。

我的README里有提到，目前该版本暂不能帮你恢复 同级 以及 Fragment嵌套的情况，所以如果你想在这种同级的场景下使用的话，你需要做以下2点：
1、你需要在MainActivity里自己做 内存重启 时的恢复工作（MainFragment、AFragment、BFragment的恢复）
2、你需要在MainFragment、AFragment、BFragment里自己做 内存重启 时的恢复工作（参考SupportActivity）

综上，如果你一定需要这样需求的话，就需要这么做；我的Demo可以看到是流程式的；不需要任何额外的处理，库已经帮助处理好了

最后，下个版本0.7可能会解决 Fragment嵌套、同级的恢复问题（已经找到封装思路，还在尝试封装中）

:)

**Comment by YoKeyword** [comment]
@lylzwsy 同时还一种方案是我比较提倡的，就是少量模块Activity+多Fragment，首页还是MainActivity+3个模块Fragment，每个模块点击的话就是跳转Activity，然后该Activity是单Activity+多Fragment的结构
3个模块都是这样处理  那么你的app就是4 Activity+多Fragments，  这样处理的话代码复杂程度和Fragment之间的嵌套逻辑会降到最低，同时app质量和性能又比较高，你可以酌情考虑  :)

**Comment by lylzwsy** [comment]
非常感谢你。  我再继续研究研究。  同时也期待你的0.7版本！加油。
