### ISSUE TITLE
部分机型出现already added错误

### ISSUE THREAD

**Issue by leibown** [YoKeyword/Fragmentation#180]
我自己在实测当中，没有出现过这个错误，但是在友盟中会发现每天都会出现10个左右的这样错误，我已经在BaseFragment里面做了这样的处理
![add](https://cloud.githubusercontent.com/assets/13811174/21336542/20cb627a-c6a1-11e6-8a04-f5703e9f65e0.png)
但是还是会出现这样的错误，
![homefragment](https://cloud.githubusercontent.com/assets/13811174/21336584/5c33e1b6-c6a1-11e6-8a60-09b2abec53ba.png) 子Fragment都是通过发送通知到HomeFragment，然后由HomeFragment执行跳转动作的。

**Comment by YoKeyword** [comment]
RxBus的接收好像有点问题，这个Event.StartFromHomeFragment是否多次post／send了，这样的话订阅者里每次接收到这个事件就会start新的Fragment～

这个异常很容易排查，就是重复start了同一个Fragment实例，你再检查下代码

**Comment by leibown** [comment]
为什么我在start方法里面这样写，然后isAdded打印出来的还是false呢~同一个fragment的实例，刚刚调用了start方法，结果打印出来还是false，为什么呢？
![1231231312313131](https://cloud.githubusercontent.com/assets/13811174/21337693/7527ade8-c6aa-11e6-8670-f332e074d9ac.png)

**Comment by YoKeyword** [comment]
start方法内部是fragmentManager加载的 会把事务提交到主线程队尾 并不是立即执行 
你把log放到handler里执行就可以看到被add了

**Comment by leibown** [comment]
非常感谢！！知道原因咯！！！非常非常感谢~
