### ISSUE TITLE
android studio 更新2.3 Beta1后出错

### ISSUE THREAD

**Issue by solomon2** [YoKeyword/Fragmentation#181]
android studio 更新2.3 Beta1后 ，	android-sdk-build-tools	升级25.0.2

然后SupportActivity无法找到继承的AppCompatActivity，导致无法使用。

**Comment by YoKeyword** [comment]
查看下相关配置是否有问题， AppCompatActivity是supportV7包里的类，我在使用最新的v7-25.1.0中，没发现错误。

**Comment by YoKeyword** [comment]
可能是EventBus3.0的Index 你们没有正确生成。。。 你注释掉:

app里build.gradle:  注释掉
apt {
    arguments {
        eventBusIndex "me.yokeyword.sample.EventBusIndex"
    }
}
App类下的：
 @Override
    public void onCreate() {
        super.onCreate();

        // 下面代码注释掉
        EventBus.builder()
                .addIndex(new EventBusIndex())
                .logNoSubscriberMessages(false)
                .installDefaultEventBus();
    }
注释掉上述代码试试

下版本我还是把Index特性移除吧。。
