### ISSUE TITLE
关于懒加载的问题

### ISSUE THREAD

**Issue by dyfan** [YoKeyword/Fragmentation#182]
看到您这边新增加了懒加载的方式，这个懒加载目前，是只适用于vieepager，还是在viewpager的情况下都可以适用这个懒加载的方式

**Comment by YoKeyword** [comment]
懒加载 适用于 同级 以及 ViewPager， 是二合一的懒加载，基本我们常用懒加载的场景都会正常工作～

onSupportVisible()同理，是真正意义上 对 用户可见时 ，回调的方法～

**Comment by dyfan** [comment]
感谢这么晚的回复，谢谢。
