### ISSUE TITLE
升级SDK版本25.1.0之后 转场动画完成时的监听方法失效了,页面上有的控件点击事假也失效了,换回24.1.0版本之后恢复正常

### ISSUE THREAD

**Issue by liuzeze** [YoKeyword/Fragmentation#183]

**Comment by YoKeyword** [comment]
OK 感谢反馈，正好在做0.9版本，主要修复多点触控、内存泄漏等问题； 25.1.0源码我稍后看下，保证兼容～

**Comment by YoKeyword** [comment]
push了0.9.0， 该大版本主要:
* 修复了存在的BUG
* 提升兼容性
* 解决多点触控
* 完善SharedElement
