### ISSUE TITLE
升级0.8.6后的问题....

### ISSUE THREAD

**Issue by adminLiu-s** [YoKeyword/Fragmentation#186]
这是我从0.7.10->0.8.6后的依赖库：
compile 'me.yokeyword:fragmentation:0.8.6'
compile 'me.yokeyword:fragmentation-swipeback:0.7.9'

首先就是报错一堆（这是肯定的，一些API没改），但fragmentation中的类找不到了，supportfragment等等都找不到

**Comment by YoKeyword** [comment]
clean下 然后再build下

**Comment by adminLiu-s** [comment]
clear build无数次了。。。。

**Comment by YoKeyword** [comment]
我感觉是EventBus3.0的Index 你们没有正确生成。。。   你注释掉:
````
app里build.gradle:  注释掉
apt {
    arguments {
        eventBusIndex "me.yokeyword.sample.EventBusIndex"
    }
}
````
````java
App类下的：
 @Override
    public void onCreate() {
        super.onCreate();

        // 下面代码注释掉
        EventBus.builder()
                .addIndex(new EventBusIndex())
                .logNoSubscriberMessages(false)
                .installDefaultEventBus();
    }
````
注释掉上述代码试试

下版本我还是把Index特性移除吧。。

**Comment by adminLiu-s** [comment]
我用的是rxbus。。。。。没加这个

**Comment by YoKeyword** [comment]
额。。我还以为demo..  － －！
0.8的环境升级了：看这里，确保环境对的
[0be0ba4](https://github.com/YoKeyword/Fragmentation/commit/0be0ba48b13dce91d0f248f4abec6025a2c4a141), [6a256d8](https://github.com/YoKeyword/Fragmentation/commit/6a256d8bba817fc5df34a03a77ca1f46baf3f5e7)

**Comment by adminLiu-s** [comment]
所以我项目的各个编译，库版本都要改成一样的吗

**Comment by YoKeyword** [comment]
...我忙晕了 － －！    没关系的
你再检查下环境吧；  看看为何没有build出fragmentation的类

**Comment by YoKeyword** [comment]
建议升级0.9, 该大版本主要:
修复了存在的BUG
提升兼容性
解决多点触控
完善SharedElement

**Comment by adminLiu-s** [comment]
还是没搞定...大神能不能给个联系方式

**Comment by YoKeyword** [comment]
QQ: 328903522 备注Fragmentaion
