### ISSUE TITLE
demo中setSharedElementEnter过渡动画启动fragment后，原图片消失

### ISSUE THREAD

**Issue by keyguan** [YoKeyword/Fragmentation#187]
android 5.0系统，用demo8.6测试。setSharedElementEnter过渡动画启动fragment后，原图片消失。

![wechatimg11](https://cloud.githubusercontent.com/assets/6700343/21448576/5470874c-c91f-11e6-8c42-0262f674ed7e.jpeg)
![wechatimg12](https://cloud.githubusercontent.com/assets/6700343/21448578/547108e8-c91f-11e6-9a0a-133358222758.jpeg)
![wechatimg13](https://cloud.githubusercontent.com/assets/6700343/21448577/54708d28-c91f-11e6-8514-8c4add443820.jpeg)

**Comment by YoKeyword** [comment]
support v4包的版本是多少呢？

**Comment by YoKeyword** [comment]
感谢反馈！
发现确实在support-v4-25.1.0之前， 在5.0上 使用add方式加载Fragment(即库中的start)，使用ShareElement时，返回时会图片白屏；

所以:
* 在25.1.0＋版本时： 
进行addShareElement时，判断为 >= LOLLIPOP
* 低于25.1.0版本时：
进行addShareElement时，判断为 > LOLLIPOP

> PS: 25.1.0开始 ，对于ShareElement, 官方的Fragment已经完全支持add(即库中的start)的方式了！
现在可以拉最新的commit编译来查看效果；  0.9版本这两天会发布~
