### ISSUE TITLE
loadRootFragment(AFragment)

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#189]
loadRootFragment(AFragment)， AFragment如何去start一个子Fragment？`start`方法传入的是`getFragmentManager()`start出来的是一个同级fragment，start一个子fragment需要传入`getChildFragmentManager()`。但是没有发现类似的方法？

**Comment by YoKeyword** [comment]
启动子栈 就是的方法就是 `loadRootFragment(containerId, 子Fragment)`

start是启动同级的Fragment， loadXX是装载子Fragment

**Comment by weiyf** [comment]
@YoKeyword 我还有一个疑问，如果使用`loadRootFragment(AFragment)`方法, 点击返回键时，调用`getBackStackEntryCount()`方法返回的个数是2,（包括了AFragment），但是使用`loadMultipleRootFragment(多个Fragment)`，点击返回键`getBackStackEntryCount()`方法只返回1（不包括当前show的Fragment），我看你的demo的流式交互是使用loadRootFragment方法加载第一个Fragment，然后其他使用`popTo()`方法。

**Comment by YoKeyword** [comment]
返回键的事件可以通过`onBackPressedSupport()`重写，默认<=1时 finish()， 否则pop() ；

`fm.getBackStackEntryCount()`返回的是当前fm的栈层级里的Fragment数量

**Comment by weiyf** [comment]
`loadRootFragment()`是有`addToBackStack()`，但是`loadMultipleRootFragment()`没有`addToBackStack()`?

**Comment by YoKeyword** [comment]
对的`loadMultipleRootFragment ()`，是同级概念， 一般是我们app的首页 多个TabFragment ，是不需要加入回退栈的

**Comment by weiyf** [comment]
谢谢解答。
