### ISSUE TITLE
快速点击还是会启动多个

### ISSUE THREAD

**Issue by zyyoona7** [YoKeyword/Fragmentation#19]
用了最新版，在项目中使用发现快速点击还是有启动多种情况的问题。我log的结果是动画执行完毕，页面已经启动还没完全显示的时候，可以点击到下面的fragment

**Comment by YoKeyword** [comment]
@zyyoona7  是可以点击到下面那个Fragment是吗？

**Comment by YoKeyword** [comment]
@zyyoona7  这个BUG我想我可能知道是什么原因了～
有一种情况转场动画的onAnimationStart的方法不会调用：在目标Fragment的enter无动画时，（库里是把动画设为时间0） 所以导致了该BUG，我马上push对该BUG的commit    :)

**Comment by YoKeyword** [comment]
@zyyoona7 已经解决，请pull最新的版本；
防抖动 之前是在目标Fragment的onCreate开始后判断的，现在从点击那一刻开始判断，应该不会出现快速点击启动多次情况了。

感谢你的反馈哈 :)

**Comment by zyyoona7** [comment]
最新代码没有多个问题了，昨天就是你说的这种情况，瞬间启动了多个，因为有动画，所以感觉上是可以点击下面的一样，感谢分享

**Comment by YoKeyword** [comment]
@zyyoona7  :)
