### ISSUE TITLE
问个单Activity+多Fragment选择的问题

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#190]
很感谢开源这么方便的库，首先我们一款APP已经更新到了单Activity+多Fragment架构，因为层级没有那么复杂，所以果断改了。。。

但是还有款页面比较复杂的层级结构的APP，我在想单Activity+多Fragment架构是不是已经不适用了？ 虽然库已经做了保存还原的操作，但是是不是如果层级太多进行现场保存与还原消耗的资源可能更大？只能是考虑多Activity多Fragment的页面架构了。 我们层级可能上升到了10层以上的程度或者更多（哈哈 真心想骂无脑的CP设计）

大神你们APP是怎么考虑的？

**Comment by YoKeyword** [comment]
我是一直建议多AC＋多FG的：
1、开发成本低，利于维护
2、坑少
3、最灵活

另外不能为了单AC而单AC，毕竟层级复杂的情况下，通信是个问题，最大的问题是通信的复杂程度导致难以维护～  以及在图片等资源较多较复杂的情况下，单AC的图片资源释放较难处理～

**Comment by hcadoid** [comment]
确实，层级复杂不管是AC还是FG都是很难通信的，EventBus都用烂了，但是也没办法跨层级交互还是这个方便。。我们的页面图片确实很多，而且很大，前端上传都没有限制大小，图片框架目前用的是Fresco，好处就是用RecyclerView时候可以自行合理的回收资源。 我们现在没有主动去释放图片资源，都是自动gc。   目前有个模块我想构建成外层还是用Ac里面有7-8个页面用FG，都是图片很多的页面。  那单AC或者多AC、多FG的图片处理释放有什么不一样吗？

**Comment by YoKeyword** [comment]
在FG的情况下，资源的占用、回收，Fresco确实是最强大；多多观察监测注意下即可～

**Comment by hcadoid** [comment]
谢谢解答
