### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ncworm** [YoKeyword/Fragmentation#192]
加的东西太多，反而丢失最初的初衷

**Comment by YoKeyword** [comment]
感谢建议！ 🙏
### 0.8添加:
* `onSupportVisible()` ：该方法是 **真正对用户可见时** 回调，在复杂Fragment嵌套中，有了该方法，不必判断是否是hidden&onResume状态、onHiddenChanged()状态是否要传给子Fragment等等令人抓狂的逻辑判断；  该方法在实际开发中，很有用，所以加上

* `onLazyInitView ()`：统一懒加载方法

* `transaction()`: 
````java
 supportFragment.transaction()
                .setTag(tag)
                //.addSharedElement(xx).setLaunchMode(SINGLETASK).withPop(true).forResult(1)
                .commit();
// 接着执行start()
 start(supportFragment);
````
该方法主要为了提供自定义 Tag， 毕竟复用Fragment时，之前Tag是类名，这样就会重复； transaction()的方式有更大的拓展性，避免以后出现各种startXX方法，这次0.9版本就移除了`startWithSharedElement()`等2个方法

* `FragmentLifecycleCallbacks`： 25.1.0的v4包，也有一个这个类，可见该Callback是需要的，库中提供一个更强大的`FragmentLifecycleCallbacks`，可以做更多的事

### 0.9
没有添加新的API


PS:  因为库的定位是简化复杂Fragment App的开发，所以0.8添加的几个方法是为了简化开发过程

如果你感觉到哪些API是不必要的，欢迎告知哈～

**Comment by YoKeyword** [comment]
目前来看，应该不会再添加API了，基本该有的都有了，后续工作主要是优化、简化API了，这次0.9版本就是主要做该项工作～
