### ISSUE TITLE
不好意思，还是Fragment already added这个错误

### ISSUE THREAD

**Issue by leibown** [YoKeyword/Fragmentation#193]
​我现在在我启动的地方已经做了这样的处理，为什么还是会出FragmentIsAdd错误呢，报错的Fragment都是从这个地方跳转的，这个RxBus接收器是在HomeFragment里面的。这些重复的Fragment我怀疑是不是App崩溃过后保存的呢？
![1](https://cloud.githubusercontent.com/assets/13811174/21474486/eda3f466-cb5a-11e6-9eb2-8fd38ba01b2e.png)
我使用Fragment都是这样重新new的。
![2](https://cloud.githubusercontent.com/assets/13811174/21474498/1f8fa006-cb5b-11e6-929c-522925fcda8d.png)
再次打扰不好意思。

**Comment by YoKeyword** [comment]
应该是你start了同一个Fragment实例，  复现下，看为何会 start 2次同一个实例～

**Comment by leibown** [comment]
我自己测试时从来没有出现这个错误，这个友盟上面的，每天都有好几十个这样的错误。

**Comment by YoKeyword** [comment]
RxBus 慎用啊...  坑挺大的...

**Comment by leibown** [comment]
好的，谢谢

**Comment by YoKeyword** [comment]
另外建议看下发送方， 是否有可能发送2次～
接收方的话，可以start前做下面的判断：
````java
if(!fragment.isAdd()){
    start(fragment);
}
````

**Comment by leibown** [comment]
![3](https://cloud.githubusercontent.com/assets/13811174/21474857/d609cc86-cb5f-11e6-9598-8791152233e2.png)
我已经在BaseFragment里面做了这个处理的，而且我在接收方还用了一个Fragment的集合来装需要启动的Fragment，如果这个集合中没有这个Fragment我才让这个Fragment启动的
![4](https://cloud.githubusercontent.com/assets/13811174/21474914/90837f94-cb60-11e6-88cb-6b4788406aff.png)

**Comment by YoKeyword** [comment]
这样的话，我想应该是连续接受同一事件2次，这两次的事件几乎是同时接收的

 因为start加载Fragment是commit提交方式，所以是一个异步的，该事务会放到主线程队尾，所以第二次事件接收到时，第一次接收的Fragment还没来得及被FragmentMnaager加载，所以isAdded()返回了false，进而又start了一次。

因为可以肯定是连续收到了同一事件2次，所以严格检查发送方的代码，另外post(fragment)方式改为post(Fragment.newIntance())保证创建的实例是新的， 不过源头上还是杜绝发生post2次的问题~

复现的话，有可能是内存重启引起的，可以打开开发者模式 -> 不保留活动  来模拟
