### ISSUE TITLE
0.9.0   pop 的 bug

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#194]
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >
    <FrameLayout
        android:id="@+id/f1"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent" />
    <FrameLayout
        android:id="@+id/f2"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent" />
</RelativeLayout>
```

f2 中的 SupportFragment pop  导致 f1 也 pop

**Comment by YoKeyword** [comment]
知乎Demo第4个Tab，里面的布局和你的场景类似，你可以参考下； 

你可能需要复写f2的`onBackPressedSupport()`，该方法是传递性的，从最子栈的栈顶依次传递，一旦中间有任何Fragment拦截返回ture，就被消费掉；

因为AC下的Fragment可能的存在多个不同的栈内，所以back事件相比较Activity要复杂些，理清栈内结构即可～

**Comment by zhenian** [comment]
```
    private SupportFragment menuFragment;

    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        if (savedInstanceState == null) {
            loadRootFragment(R.id. f1,BaseLayoutFragment.newInstance());
            menuFragment = MenuFragment.newInstanceType1();
            replaceLoadRootFragment(R.id.f2,menuFragment,false);
        }
    }

    private void closeMenu(){
        if(menuFragment!=null){
            menuFragment.pop();
        }
        menuFragment = null;
    }

```
调用 closeMenu() 时， BaseLayoutFragment 在 0.8.6 不受影响的正常的。但是 0.9.0 会到 BaseLayoutFragment 同时 pop 了

**Comment by YoKeyword** [comment]
`closeMenu()`是通过某个按钮调用的，还是Back键触发的？

`onBackPressedSupport()`哪个Fragment有复写该方法，提供下代码哈～

0.9对pop方法进行了重构，添加防抖动、onFragmentResult方法优化， 其他逻辑应该没什么更改～

**Comment by zhenian** [comment]
closeMenu()是通过某个按钮调用！非 Back键触发。

所有 Fragment 都 没有 Override  onBackPressedSupport

**Comment by YoKeyword** [comment]
你的这行代码：
` replaceLoadRootFragment(R.id.f2,menuFragment,false);`
这个方法的第三个参数代表是否加入回退栈，如果menuFragment是可以出栈的应该入参为 true~

如果非要为false的话，出栈方式应该是：
`menuFragment.getFragmentManager().beginTransaction().remove(menuFragment).commit();`

**Comment by zhenian** [comment]
变 为``` replaceLoadRootFragment(R.id.f2,menuFragment, true); ```，正常了。

---------

这样的话，SupportFragment 的``` pop() ```的定义语义有些少问题了。按 wiki 中的说明
``` replaceLoadRootFragment ``` 第三个参数为 false 的时，调用 ``` pop() ``` 的话，应该是空操作，或者出错，或者提示。而不是 ``` pop() ``` 整个栈顶的 Fragment 。

不然，有点反直觉。

**Comment by YoKeyword** [comment]
`pop()`的话当前还是类似官方`popBackStack`的理解，`pop`源码其实就是一个加了防抖动功能的`popBackStackImmediate()`，对于不加入回退栈的Fragment，本身`popBackStack`就不能将其出栈，标准做法是`remove`。

现在版本库 对replace支持比较弱，下个版本应该会多考虑这块～
