### ISSUE TITLE
建议swipeback方式换一下

### ISSUE THREAD

**Issue by tuzhenlei** [YoKeyword/Fragmentation#196]
众所周知，android:windowIsTranslucent设为true时候会出现各种乱七八糟的bug，亲测，所以建议不用swipebacklayout库的那种方式，而采用如：https://github.com/XBeats/and_swipeback，的这种方式。顺便说一下，作者你的fragmentation的库非常好用

**Comment by leguang** [comment]
你推荐的这个库也可以实现Fragment的侧滑退出吗？

**Comment by YoKeyword** [comment]
@tuzhenlei  对的 android:windowIsTranslucent的方式 最明显的BUG就是打开Activity页面过多时，会越来越卡～ 打开多个Fragment倒是不受影响～

本来这次更新时，想把Fragment的侧滑返回优化成类似微信那种有视觉差的滑动效果，因为时间关系没做～
回头闲暇时会把这个效果加上，Activity的原理也换成你提的那个库的方式~

@leguang 那个库只支持Activity.  不过Fragment的侧滑是和android:windowIsTranslucent不影响的，回头有空会更新下～

**Comment by tuzhenlei** [comment]
@YoKeyword android:windowIsTranslucent还有一个明显的bug是sufaceview的“掏空”问题——在播放的时候会有一段时间把activity“掏空”，可以看到底下的那层activity，做视频类的APP会感觉比较明显。所以有空还是先优化avtivity 的swipe back 比较好，可以把swipeback的滑动监听放出来。还有 您库中fragment 的swipe back 非常强大，所以觉得切换的动画效果可以不着急。
@leguang 如 @YoKeyword 所说 ，那个库只支持Activity，但是YoKeyword 的库在fragment上用起来非常方便和强大。

**Comment by YoKeyword** [comment]
@tuzhenlei @leguang 
1.0.0已放出，可以通过implements ISupportActivity/Fragment ＋ Delegate形式自己实现自定义SupportActivity/Fragment

然后可以再拓展自己的SwipeBackActivity/SwipeBackFragment 🍺 :)
