### ISSUE TITLE
startForResult无反应

### ISSUE THREAD

**Issue by lylzwsy** [YoKeyword/Fragmentation#197]
架构是类似微信的，底部4个按钮，属于1级Fragment
然后在第1个页面标题栏顶部有个按钮，点击后，需要跳转到一个Fragment，这个Fragment是用来选择查询条件的，选择条件后，按确定按钮，调用了setFragmentResult(RESULT_OK, bundle);
但是1级Fragment中的startForResult却没捕捉到这个，请问下可能是什么原因造成的？

**Comment by YoKeyword** [comment]
这个Fragment应该是你4个TabFragment的父Fragment  `startForResult()`的吧，所以呢会回调父Fragment的`onFragmentResult()`

记住谁启动，回调给谁的原则即可～   父Fragment拿到回调后再传递给子Fragment；  这种跨层级的交互，使用EventBus会更方便，但是要设计好EventBus，不能滥用，避免难以维护～
