### ISSUE TITLE
提供的统一懒加载方法是不是有点不友好

### ISSUE THREAD

**Issue by yaozs** [YoKeyword/Fragmentation#198]
这样的懒加载方法就强制使用者书写两个fragment，感觉没必要，提供方法在界面未显示时不加载数据什么的就可以吧

**Comment by YoKeyword** [comment]
啊？  没明白你的意思～    
> 强制书写2个fragment
这个是什么意思呢？

````java
    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState){
        // todo 
 }
````
这个方法会在 当前Fragment 第一次对用户可见时，回调～ 即我们说的懒加载

**Comment by yaozs** [comment]
就是我认为懒加载的话都在这一个fragment处理就可以，没必要重新再提供一个
 public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);
        if (savedInstanceState == null) {
            loadRootFragment(R.id.fl_first_container, FirstHomeFragment.newInstance());
        }
    }
现在就是需要再次创建一个fragment去适配他的加载，我的想法就是这个接口直接可以处理有数据时的操作，在当前页面就可以加载数据了，只需要判断一下他是不是第一次初始化。
https://github.com/xmagicj/LazyFragment
这个项目的lazy方法我认为可以参考下，我想说的就是这个意思

**Comment by YoKeyword** [comment]
额 Fragmentation中的懒加载就是你描述的功能啊  而且不仅兼容了ViewPager下的懒加载，还兼容了同级Fragment的懒加载～

这个懒加载方法是所有Fragment都有的，至于
````java
public void onLazyInitView(@Nullable Bundle savedInstanceState) {
   super.onLazyInitView(savedInstanceState);
   if (savedInstanceState == null) {
       loadRootFragment(R.id.fl_first_container, FirstHomeFragment.newInstance());
   }
}
````
其中的saveInstanceState是该Fragment是否处于被强杀恢复的状态，在做嵌套Fragment的栈架构时，是有必要的，大部分情况下，如果你没有什么复杂嵌套，你可以不用关心saveInstanceState这个参数

感兴趣的话 可以看下实现懒加载部分的源码～

**Comment by YoKeyword** [comment]
感谢反馈！
 `onLazyInitView()`在ViewPager里确实有这个BUG，在ViewPager里切换虽然Fragment没有被销毁实例，只是被销毁视图，但是当恢复视图时，确实应该再次调用` `onLazyInitView()`，这样更符合我们平时的场景

有个isFirstVisible的标志位，在`onActivityCreated()`里初始化应该就好了，白天会把该BUG修复~

**Comment by yaozs** [comment]
我更新了0.9.1

**Comment by YoKeyword** [comment]
🙏  push了0.9.2  这次应该是修复了  :)

**Comment by yaozs** [comment]
sorry，还是木有修复， 下载我那个demo调试下吧，一直有问题，加油，嘿嘿

**Comment by YoKeyword** [comment]
我在各种场景都模拟了下，  你的Demo也跑过了，没问题啊～  你再看看？

**Comment by yaozs** [comment]
你的qq是多少，或者微信，明天我加你，然后给你看运行的问题

**Comment by YoKeyword** [comment]
QQ：328903522
你的Demo我改成0.9.2   从log上看打印是正常的

**Comment by yaozs** [comment]
ok了，这次bug修复彻底完成了
