### ISSUE TITLE
是否可以用RxLifecycle里的RxFragment代替Fragment，不会有影响吧

### ISSUE THREAD

**Issue by zhongyuanwu** [YoKeyword/Fragmentation#199]

**Comment by YoKeyword** [comment]
https://github.com/wsaxx/AndroidPracticeCode/blob/c26da7e248492fe143d330a10e538f408bc8fc88/androidhelper/src/main/java/com/wsaxx/helper/app/rxlifecycle/RxAppCompatActivity.java

见 #124
