### ISSUE TITLE
viewpager+fragment  

### ISSUE THREAD

**Issue by theLastScorpio** [YoKeyword/Fragmentation#2]
onDestroyView  怎么进行 状态 保持 与恢复？？？

**Comment by YoKeyword** [comment]
@theLastScorpio 这里我假设你用的FragmentPagerAdapter   ViewPager＋Fragment工作时，会帮你预加载前一个、后一个Fragment，当划到下一个Fragment时，当前Fragment的上一个Fragment就会被销毁视图，即调用了onDestoryView，当再回来时，会调用onCreateView，而不会调用onCreate。
所以从这个信息，我们知道，一些不需要刷新的数据不要在onCreateView以及后续的生命周期里初始化，有可能的话在onCreate里获取，或者使用全局变量  :)

**Comment by theLastScorpio** [comment]
en 知道了 onDestroyView()  setArguments(Bundle) 来保存数据 我感觉这样 会比较好
然后当 activity 重建的时候  这样 又会比较蛋疼了。。。

**Comment by YoKeyword** [comment]
@theLastScorpio 是的 这个做法数据有被污染的可能～  还是建议通过生命周期解决数据的保存 :)

**Comment by theLastScorpio** [comment]
thanks a lot
