### ISSUE TITLE
同级别实现不重复加载

### ISSUE THREAD

**Issue by lylzwsy** [YoKeyword/Fragmentation#20]
你好，我同级别的实现不重复加载。
现在遇到一个问题。
我有MainFragment/BFragment/CFragment/DFragment
在普通的切换时候已经实现了不重复加载。通过add/show来控制实现的。
但是现在我的CFragment中，需要传递一个Type，来区分CFragment要去加载什么数据。
第一次，进入时候是正常的。  
CFragment中有一个按钮，可以选择Type，我点击该按钮，选择另外一个类型时候，这个时候需要重新刷新该页面，这块控制逻辑有点懵了。。
感谢您抽出宝贵时间指教下。
 public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                Bundle bundle = new Bundle();
                Fragment fragment = null;
                FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
                mSpinnerAdapter.setCheckPos(position);
                switch (position) {
                    case 1:
                            bundle.putSerializable("mType", MaopaoListFragment.Type.friends);
                            maopaoListFragment = new MaopaoListFragment_().newInstance(MaopaoListFragment.Type.friends);
                            maopaoListFragment.setArguments(bundle);
                            ft.add(R.id.container, maopaoListFragment, strings[position]);
                        break;

                    case 2:
                            bundle.putSerializable("mType", MaopaoListFragment.Type.hot);
                            maopaoListFragment = new MaopaoListFragment_().newInstance(MaopaoListFragment.Type.hot);
                            maopaoListFragment.setArguments(bundle);
                            ft.add(R.id.container, maopaoListFragment, strings[position]);
                        break;

                    case 0:
                    default:
                            bundle.putSerializable("mType", MaopaoListFragment.Type.time);
                            maopaoListFragment = new MaopaoListFragment_().newInstance(MaopaoListFragment.Type.time);
                            maopaoListFragment.setArguments(bundle);
                            ft.add(R.id.container, maopaoListFragment, strings[position]);
                        break;
                }

**Comment by YoKeyword** [comment]
这是与库无关的问题哈    加我的QQ交流吧: 328903522
