### ISSUE TITLE
SupportFragment支持放置高德地图吗？如何放置？

### ISSUE THREAD

**Issue by lichun-nick** [YoKeyword/Fragmentation#200]
放置高德地图需要考虑MapView的生命周期问题。但是我放上后貌似有内存溢出现象。

**Comment by YoKeyword** [comment]
在Activity上，我们知道MapView需要在`onResume` `onPause`等生命周期里去 resume/pause。

而在Fragment，除了`onResume`,`onPause`，还有`onHiddenChanged()`(或者`setUserVisibleHint()`，如果你的地图放在ViewPager下的话)的生命周期去处理）

从0.8起，库中提供了`onSupportVisisble()`, `onSupportInvisible()`2个 对用户 可见，不可见的support生命周期，你可以仅使用这2个生命周期来resume/pause地图控件即可。 :)

**Comment by lichun-nick** [comment]
public class MapMainFragment extends SupportFragment implements LocationSource, AMapLocationListener {

    private View view;
    private MapView mMapView;
    private AMap mAmap;
    private AMapLocationClient locationClient;
    private OnLocationChangedListener mListener;


    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        if(view == null){
            view = inflater.inflate(R.layout.fragment_map,null);
            mMapView = (MapView) view.findViewById(R.id.map);
            mMapView.onCreate(savedInstanceState);
            //初始化地图控制器
            if(mAmap == null){
                mAmap = mMapView.getMap();
                initAMap();
            }
        }
        else{
            if(view.getParent() != null){
                ((ViewGroup) view.getParent()).removeView(view);
            }
        }

        return view;
    }

    //初始化AMap对象
    private void initAMap() {
        mAmap.setLocationSource(this);
        mAmap.getUiSettings().setMyLocationButtonEnabled(true);
        mAmap.setTrafficEnabled(true);
        mAmap.setMyLocationEnabled(true);
        mAmap.setMyLocationType(AMap.LOCATION_TYPE_LOCATE);
    }

    /*@Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mMapView.onSaveInstanceState(outState);
    }*/

    @Override
    public void onSupportVisible() {
        super.onSupportVisible();
        mMapView.onResume();
    }

    @Override
    public void onSupportInvisible() {
        super.onSupportInvisible();
        mMapView.onPause();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        mMapView.onDestroy();
    }

    @Override
    public void activate(OnLocationChangedListener listener) {
        this.mListener = listener;
        startLocation();//开始定位
    }

    /**开始定位，首先设置定位参数
     *此方法为每隔固定时间会发起一次定位请求，为了减少电量消耗或网络流量消耗，
     *注意设置合适的定位时间的间隔（最小间隔支持为2000ms），并且在合适时间调用stopLocation()方法来取消定位请求
     *在定位结束后，在合适的生命周期调用onDestroy()方法
     *在单次定位情况下，定位无论成功与否，都无需调用stopLocation()方法移除请求，定位sdk内部会移除
     */
    private void startLocation() {
        AMapLocationClientOption clientOption;
        if(locationClient == null){
            locationClient = new AMapLocationClient(getActivity());
            clientOption = new AMapLocationClientOption();
            locationClient.setLocationListener(this);//设置定位监听
            clientOption.setLocationMode(AMapLocationClientOption.AMapLocationMode.Hight_Accuracy);//设置为高精度模式
            clientOption.setNeedAddress(true);//设置返回地址信息
            clientOption.setLocationCacheEnable(true);//开启缓存机制
            clientOption.setWifiScan(true);//强制刷新WIFI
            clientOption.setInterval(2000);//每隔2s进行定位
            clientOption.setMockEnable(false);
            locationClient.setLocationOption(clientOption);//设置定位参数
        }
        locationClient.startLocation();
    }

    @Override
    public void deactivate() {
        mListener = null;
        if(locationClient != null){
            locationClient.stopLocation();
            locationClient.onDestroy();
        }
        locationClient = null;
    }


    /**
     * 定位结果回调
     * @param aMapLocation
     */
    @Override
    public void onLocationChanged(AMapLocation aMapLocation) {
        if(mListener != null && aMapLocation != null){
            if( aMapLocation.getErrorCode() == 0){
                mListener.onLocationChanged(aMapLocation);//显示系统小蓝点
                LatLng mylocation = new LatLng(aMapLocation.getLatitude(),
                        aMapLocation.getLongitude());
                mAmap.moveCamera(CameraUpdateFactory.zoomTo(15));
            }else{
                String errText = "定位失败," + aMapLocation.getErrorCode() + ": "
                        + aMapLocation.getErrorInfo();
                LogUtil.i(errText);
            }
        }
    }

}
高德地图不显示。。。。。。，而且有内存溢出。

**Comment by jp1017** [comment]
@lichun-nick 不用这个库，直接在Fragment里面可以显示地图吗？

**Comment by YoKeyword** [comment]
你指的`内存溢出`是GC后不回收内存吗？ 我之前App接入的是百度地图， 涨的内存是可以通过GC回收的～

另外, 同问直接在Fragment可以显示吗～

 > PS : 你的地图控件是在ViewPager里的话，要更新到0.9.3版本，Fixed了ViewPager里supportVisible可能不回调的问题

**Comment by lichun-nick** [comment]
哦，我用Block检测的，目前还不清楚是不是GC不能回收。不过显示每次走到mMapView.onCreate(savedInstanceState);这儿就Block

**Comment by lichun-nick** [comment]
fragment 我需要试一下

**Comment by jp1017** [comment]
> mMapView.onCreate(savedInstanceState);这儿就Block

这里我也Block, 地图的锅， 只是阻塞主线程，内存没泄露，，，，

**Comment by lichun-nick** [comment]
好的，请教一下，我上面写的代码没有问题吧？

**Comment by YoKeyword** [comment]
@lichun-nick 你的地图在什么场景使用的呢？  ViewPager ？  主页同级的情况？ 还是普通的单页面？

**Comment by lichun-nick** [comment]
我的地图是在主页同级，一个Activity添加不同的SupportFragment

**Comment by YoKeyword** [comment]
@lichun-nick 你的Fragment onCreateView写法好像有点问题，改成下面试试

````java
public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
    view = inflater.inflate(R.layout.fragment_map,container,false);
    mMapView = (MapView) view.findViewById(R.id.map);
    mMapView.onCreate(savedInstanceState);
    //初始化地图控制器
    if(mAmap == null){
        mAmap = mMapView.getMap();
        initAMap();
    }
    return view;
}
````
