### ISSUE TITLE
library source does not match the bytecode for class SupportFragment

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#201]
现在引入库，SupportFragment类里面为什么会出现：library source does not match the bytecode for class SupportFragment的提示呢？之前0.7好像没这提示

**Comment by YoKeyword** [comment]
Gradle不能同步是吗？   你看下AS定位到哪行～

`isSupportHidden()`这个方法从0.8开始不再暴露给外部使用，你看下是否定位到这里，把该行注释掉，再同步看看～

> isSupportHidden()方法不再暴露给外部使用，懒加载请直接用onLazyInitView(Bundle saveInstanceState)；

**Comment by hcadoid** [comment]
正常的用法好像没什么问题，但是就点进去到SupportFragment里面，提示了红色的警号，不知道有没有影响。

**Comment by YoKeyword** [comment]
哦哦 进去看下源码是不是0.9的代码 是的话就莫有问题～
不放心的话 可以清理下外部引用库 和 gradle里下载的 fragmentaion的各个版本的包，重新依赖下～

**Comment by hcadoid** [comment]
在SupportActivity等引用到@SupportFragment.LaunchMode的注解都是报红了，以及SupportTransaction里的注解，我以project包的形式就没问题。直接compile 'me.yokeyword:fragmentation:0.9.0'有问题。但是编译和代码都能跑。

**Comment by YoKeyword** [comment]
那还是建议把  [你的User目录]/.gradle/caches/modules-2/files-2.1/下的me.yokeyword  文件夹删掉 重新编译生成下

**Comment by hcadoid** [comment]
是全部删除了重新编译的

**Comment by YoKeyword** [comment]
建议先更新至0.9.3～    如果还这样可能是Android Studio的问题...

**Comment by hcadoid** [comment]
@YoKeyword 你那里没出现吗？把project的依赖去掉，引用compile 'me.yokeyword:fragmentation:0.9.3'来用？ 这是stackoverflow上的描述，说不是IDE问题和本地缓存问题。。http://stackoverflow.com/questions/36753524/library-source-does-not-match-the-bytecode-for-class?answertab=votes#tab-top

**Comment by YoKeyword** [comment]
我看了下 这个提示不用关心的～  不会影响使用哒
Source源码注解编译成class文件时，并不会保留到class文件里，这个提示不用担心，idea插件提示问题～
