### ISSUE TITLE
怎么在fragment里解决键盘弹起顶起布局

### ISSUE THREAD

**Issue by istarvip** [YoKeyword/Fragmentation#202]
我在onSupportVisible和onCreateView里都设置了_mActivity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN);
没有效果。
清单文件里在activity设置
android:configChanges="orientation|keyboardHidden"
android:windowSoftInputMode="adjustPan|stateAlwaysHidden|stateHidden"
只有第一次起作用，进入其他fragment后点击输入框又将布局顶起了

**Comment by YoKeyword** [comment]
SoftInputMode是和Activity绑定的， 你可以通过java代码设置 等同 你manifest里配置的属性，
在`onSupportVisible`里设置， 在`onSupportInvisible`里重置设置
