### ISSUE TITLE
怎么跳转到指定Fragment?

### ISSUE THREAD

**Issue by Blankeer** [YoKeyword/Fragmentation#205]
我现在遇到的情况是，收到推送，点击通知栏推送之后打开文章详情页面，我的构架和demo里微信的构架类似。
我想到的办法就是启动MainActivity，通过传递putExtra过去，然后在Main里读取出来，再启动文章fragment。
求解答。
谢谢.

**Comment by YoKeyword** [comment]
这样是可以的， 缺点是可能代码写的有点繁琐～

还一种有些限制但很方便的方式，存在一个容器Activity，点击通知后，把需要的Fragment塞到这个Activity里；

> 有计划 出一个新module : Fragmentation的路由模块，方便各种跳转需求～

**Comment by Blankeer** [comment]
谢谢回答。
我用我那个思路实现了，先传递数据到Activity，再通过EventBus postSticky出去，再判断start到target Fragment.
ps:库挺好用的，但必须得extends SupportActivity/SupportFragment，能不能把Fragmentation的功能独立出来，采用Interface+组合方式会不会好点？个人想法。
谢谢！

**Comment by YoKeyword** [comment]
Interface方式 有考虑过，不过工作量有点大，重要的是 使用者要委托很多方法，使用起来挺麻烦的～
所以暂时不会考虑的 :)
