### ISSUE TITLE
大神您好，能帮忙看看我的fragment overlap问题吗

### ISSUE THREAD

**Issue by DanteAndroid** [YoKeyword/Fragmentation#206]
意料之中的，我在使用frament hide & show 的过程中遇到了overlap。但是Google看了大量的文章，尝试过，发现没有能根治我的问题的。我尝试过的方法有：
- 加背景色（很显然这只是workaround， 一叶障目）
- 使用Linearlayout替代Container的Framelayout（对我没用，改了之后反而看不到新的fragment了）
- 判断savedInstance，如果不为空才add、show新的fragment。（没用）
- 其他忘记了的。

如果可以的话，直接拉取一下[我的项目](https://github.com/DanteAndroid/beauty)运行。

## Code:
项目结构是 MainActivity + fragments，通过 drawer 的 menu 来切换显示隐藏 fragment
[设置当前fragment代码](https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/base/BaseActivity.java#L125)，[初始化fragment代码](https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/MainActivity.java#L173)

## Reproduce
进入app，点击"收藏"，点击"妹子"，然后旋转屏幕，点击"收藏"

希望能指导一下~

**Comment by YoKeyword** [comment]
有点忙，大致看了下发现：
[这里判断findFragment的代码](https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/base/BaseActivity.java#L135)，传入的id有问题，试试：
`findFragmentByTag(String.valueOf(id))`

另外一点建议，可以考虑简化维护Fragment的逻辑

**Comment by DanteAndroid** [comment]
其实我本来是用id的，后来看您说用tag比较好，就改成String了。但是。。用id没法find吗

**Comment by YoKeyword** [comment]
在加载Fragment时，add(id,fragment,tag) 第三个参数是TAG， id是Fragment内部分配的，所以我们一般是拿不到id, 需要通过tag
