### ISSUE TITLE
fragment出栈问题

### ISSUE THREAD

**Issue by dyfan** [YoKeyword/Fragmentation#207]
您好，先前用过您的库，最近这个项目没有使用您的库。但是有一个问题，想问一下您。
fragment出栈之后，回到先前的fragment，先前的fragment会重新走生命周期方法，也就代表这会重新请求一次网络或者实例化一次数据，我想不让他做这个操作，或者怎么去保存先前的fragment的状态。

**Comment by YoKeyword** [comment]
`fragment出栈之后，回到先前的fragment` 
我猜你可能指的是replace方式添加的Fragment，replace会销毁视图，回来时走onCreateView()`等后续生命周期， 你可以把数据作为全局变量，`onCreateView`里根据条件只做赋值操作即可～

**Comment by dyfan** [comment]
谢谢解释。我关闭了。
