### ISSUE TITLE
求解replace的问题

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#208]
Activity以replaceLoadRootFragment（int containerId, SupportFragment toFragment，false）方式加载了FragmentMain。
FragmentA、FragmentB、FragmentC都是3个都是以replaceFragment(SupportFragment toFragment, false)可以相互替换，开始是以FragmentMain(里面有些网络请求+判断要替换的页面)作为替换。
在其中的FragmentA/B/C中，去start方式开启一个FragmentD，回退的话，并没有去退出FragmentD。而是调用了上一层的。

我的业务是Activity其中的可以有3个相互替换的Fragment，后面正常start就可以了。
是replace没有加入回退栈？那如果replaceLoadRootFragment和replaceFragment方式都是加入回退栈，那返回时候替换的会返回吗（我需要的是替换的不能再返回了。）

**Comment by YoKeyword** [comment]
首先 `replaceFragment()` `replaceLoadRootFragment ()`最后一个boolean类型的参数代表是否加入回退栈

其次不建议同一栈层级内replace和add(start)同时存在， 安全的方式是replace外面包一层父Fragment，使用load/start启动，这样保证同一栈层级内的统一性

 另外回退事件，可以复写`onBackPressedSupport()`拦截～  

建议使用时多观察栈视图

**Comment by hcadoid** [comment]
如上述，看了栈视图，start FragmentD是在同一栈层级内，此时显示是有2个Fragment，在Activity中复写了onBackPressedSupport ，代码是这样判断的：getBackStackEntryCount>1 pop() 否则就finish()提示用户退出应用。

在外层在包层父Fragment感觉太多层嵌套了。。。上面说的replaceLoadRootFragment加载的FragmentMain不能作为父的吗

**Comment by hcadoid** [comment]
或者以loadRootFragment方式加载根的Fragment,后用replaceFragment方式替换根的Fragment,之后在start,不知API支持吗

**Comment by YoKeyword** [comment]
如果是根部是replace方式加载的 上面用start 应该是没有问题的～
