### ISSUE TITLE
使用动画卡顿

### ISSUE THREAD

**Issue by shuiyouwen** [YoKeyword/Fragmentation#215]
我发现使用动画的时候，一些有网络请求的界面就会卡顿。
我的所有网络请求的操作和界面的更新都在onLazyInitView中处理的。
有什么招吗~~

**Comment by YoKeyword** [comment]
在动画结束后初始化繁重的任务，使用`onEnterAnimationEnd()`

[Wiki里有说明](https://github.com/YoKeyword/Fragmentation/wiki/4.--%E9%98%B2%E6%AD%A2%E5%8A%A8%E7%94%BB%E5%8D%A1%E9%A1%BF%E3%80%81%E6%87%92%E5%8A%A0%E8%BD%BD)
