### ISSUE TITLE
loadMultipleRootFragment

### ISSUE THREAD

**Issue by krait8064** [YoKeyword/Fragmentation#217]
本人小白新入门，问题略蠢，请不吝赐教。为啥**root fragment**会有多个而不是唯一，如**acitivity**作为fragment的根一般。请您举例子说明一下，不甚感激！

**Comment by YoKeyword** [comment]
一个Fragment跳Fragment是流式
微信 QQ主页多Tab是同级的关系， 具体看下推荐阅读和DEMO
