### ISSUE TITLE
blueprint

### ISSUE THREAD

**Issue by krait8064** [YoKeyword/Fragmentation#218]
*楼主，你好！*
  能不能加一张图片在README.MD里面，用来描述这个项目的*bluprint*，打算做多少，计划进行到了哪里，大概的概述而已。俗话说高屋建瓴，这样更方便大家阅读理解，您说是吗？不盛感激！

如果方便的话可否将邮箱或者微信联系方式留下，我需要经常提问提问了。初入android，有点好奇心旺盛，问题很多，正在重写你的代码，加深Fragment的理解。怎奈问题很多，无法理解，想要随时提问。

**Comment by YoKeyword** [comment]
一直在进行维护，致力轻松实现高性能 易编写的Fragment App；

近期私人时间比较少，年后闲时会在readme上写上计划 短期计划是：
* 查看栈视图 悬浮球功能
* 对replace加载方式 封装优化
* 路由功能
* ...

邮箱 github主页有 有问题可以发邮件~
