### ISSUE TITLE
Fragment上所有组件无法点击

### ISSUE THREAD

**Issue by Ludejin** [YoKeyword/Fragmentation#22]
先启动一个Activity
![image](https://cloud.githubusercontent.com/assets/10751355/15670920/77d9a612-275a-11e6-94ba-dbb5808fde25.png)
在这个Activity默认开始登陆界面（一个Activity多个Fragment实现登录、注册流程）
![image](https://cloud.githubusercontent.com/assets/10751355/15670935/8b3bdd38-275a-11e6-9e9d-526499774c42.png)
发现LoginFragment界面是出来了，但是所有组件都不能点击，输入框也不能获取焦点。研究了大半天，没找出个所以然，不知道这是不是个bug。

**Comment by YoKeyword** [comment]
@Ludejin 感谢反馈，是用的最新的0.6.5吗
应该是防手抖机制的BUG，我找下原因先 :)

**Comment by Ludejin** [comment]
@YoKeyword 不好意思之前没有说明，我用的是0.6.4，昨晚通过多次测试和调试，发现我Activity和Fragment都是继承SwipeBack，所以我觉得应该是添加了两层SwipeBackLayout导致，后来LoginFragment继承自SupporFragment，然后就没问题了。

**Comment by YoKeyword** [comment]
@Ludejin 哦哦，我的Demo里有SwipeBack的例子，没发现问题，你可以看下，如果真是某种BUG，非常欢迎反馈哈  :)
