### ISSUE TITLE
多继承问题

### ISSUE THREAD

**Issue by wzasd** [YoKeyword/Fragmentation#224]
项目中可能要实现Rxjava的功能，我想使用Rxlifecycle这个openlib，但是需要继承RxAppCompatActivity/RxFragment，有木有什么好的办法啊。目前我想到是把你的SupperAcivity这个类提出来做一个baseactivity，然后用你的supperActivity继承RxAppCompatActivity，但是很不符合Geek精神啊，有木有一个更好的办法呢？请指教！

**Comment by YoKeyword** [comment]
https://github.com/wsaxx/AndroidPracticeCode/blob/c26da7e248492fe143d330a10e538f408bc8fc88/androidhelper/src/main/java/com/wsaxx/helper/app/rxlifecycle/RxAppCompatActivity.java

见 #124

**Comment by wzasd** [comment]
好的，感谢回复，作者加油！！这个开源框架很棒
