### ISSUE TITLE
Fragment already added

### ISSUE THREAD

**Issue by YuanHongGitHub** [YoKeyword/Fragmentation#225]
```
Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
	Uri uri = Uri.fromParts("package", getContext().getPackageName(), null);
	intent.setData(uri);
	startActivity(intent);
```
当进入从软件进入系统设置界面（申请权限的特殊情况会用到）关闭权限后，然后通过软件缩略图重新进入app时，会显示主界面，而不是之前的fragment，此时再进入之前的fragment就会提示Fragment already added的错误，请问，要怎么解决啊！?

**Comment by YoKeyword** [comment]
重复加载了已经存在的Fragment了～

调试下App是否因内存不足被强杀了，onCreate()是否重新走了～

**Comment by YuanHongGitHub** [comment]
栈视图里面有两个mainfragment(主activity加载的根fragment)
结构是这样的：
v MainFragment
    tabFragmentA
    tabFragmentB
    tabFragmentC
    tabFragmentD
Fragment1(由MainFragment跳转)
Fragment2(由Fragment1跳转)
v MainFragment
    tabFragmentA
    tabFragmentB
    tabFragmentC
    tabFragmentD

在此Fragment2里面申请的权限，然后手动进入设置界面，当取消权限，
    1：按返回键时直接退出到了桌面
    2：通过缩略图进入
进入后，就会出现上述栈视图，重新加载了，而且之前的mainfragment没有清理掉，请问要怎么解决啊！？

**Comment by YoKeyword** [comment]
> 通过软件缩略图重新进入app时，会显示主界面，而不是之前的fragment
> 按返回键时直接退出到了桌面
从上面2个描述，我猜测你的App回来时可能崩溃了。。。 所以才有了后面的异常   你调试下看看哈

**Comment by YuanHongGitHub** [comment]
不是，这个是6.0系统的，当你修改权限后整个app会重新启动（有的app会有不同的解决方案，微信就是重启app的），重启后栈内会保存上次非正常退出的所有fragment，我想问下，怎么清理之前的fragment啊

**Comment by YuanHongGitHub** [comment]
你的qq或者微信是多少啊？

**Comment by YuanHongGitHub** [comment]
https://segmentfault.com/q/1010000007930966?_ea=1540704       http://blog.csdn.net/jspping/article/details/54288639
这是刚刚群友提供的，我想的是在activity 的onResume的时候检查栈内fragment的信息，若存在fragment则清理掉，只是，这个要怎么实现啊？

**Comment by YoKeyword** [comment]
QQ: 328903522

我觉得不应该清理掉  而是做好恢复

**Comment by YuanHongGitHub** [comment]
谢谢，我在activity里面没有判断，加了之后就好了，谢啦!!☆⌒(*＾-゜)v
