### ISSUE TITLE
界面丢失严重

### ISSUE THREAD

**Issue by jttttttttttttt** [YoKeyword/Fragmentation#226]
我使用的框架界面是仿知乎的那个，底部选中栏有4个，进入首界面先不点后几个，比如我先分享东西到微信，然后返回的时候，点击选中栏其他界面，会有界面丢失的情况，包括我刷模拟器的时候，只要有几个先不点，总有界面缺失的情况！！

**Comment by YoKeyword** [comment]
我用Demo实验了下，第一个Tab里直接跳转打电话页面（模拟打开微信分享的场景）， 然后返回后，其他Tab页 界面没有问题， 建议你比对下Demo检查下代码 调试下哈～

**Comment by YoKeyword** [comment]
建议多观察栈视图来调试哈～
另外如果不是产品的交互特殊，不建议用仿知乎的栈设计， 更建议用微信Demo的栈设计，知乎的栈设计嵌套关系较复杂，还附带一些懒加载，如果没处理好，可能会产生空白，不加载等情况～
