### ISSUE TITLE
Fragmentation: Please beginTransaction in onPostResume() after the Activity returns!

### ISSUE THREAD

**Issue by istarvip** [YoKeyword/Fragmentation#227]
![image](https://cloud.githubusercontent.com/assets/12675437/22101514/b7331926-de6e-11e6-8ffc-04ea3d4d624e.png)
刚开始好好的，过会打开任意页面就空白了

**Comment by YoKeyword** [comment]
该异常是Activity在回调onSaveInstanceState()后(即离开该Activity后)，再Fragment事务start()导致的；

需要避免这种行为，应当下次回到该Activity时再去执行～即：回调onPostResume()时再执行事务～

**Comment by istarvip** [comment]
![image](https://cloud.githubusercontent.com/assets/12675437/22103954/1803668a-de78-11e6-83a8-b75af5a8895e.png)
是这重新加载跟布局吗

**Comment by YoKeyword** [comment]
找到异常提示的地方 把事务延迟到下次回到AC时调用
