### ISSUE TITLE
Activity必须要继承SupportActivity，Fragment继承SupportFragment吗？

### ISSUE THREAD

**Issue by androidXiaoHao** [YoKeyword/Fragmentation#228]
项目中都会有自己的BaseActivity等，并且BaseActivity中也写了很多逻辑。如果想使用您的Fragmentation库的话，冲突了怎么办啊？

**Comment by YoKeyword** [comment]
是的，必须要继承；之前有想过使用“实现”的方式，不过代价就是对于开发者使用起来就烦琐不少～

你可以让自己的BaseActivity/BaseFragment来继承SupportActivity/SupportFragment来解决～

**Comment by androidXiaoHao** [comment]
好的，多谢
