### ISSUE TITLE
关于  懒加载  与   onSupportVisible()和onSupportInvisible()方法的区别

### ISSUE THREAD

**Issue by androidXiaoHao** [YoKeyword/Fragmentation#229]
您好，正如题目上面所说的，我感觉懒加载就是为了解决当页面可见时才去进行网络请求加载数据，节省流量。关于onSupportVisible()和onSupportInvisible()这两个方法也是为了判断可见或者不可见时  可以进行一些操作。那么懒加载的作用不就和这两个方法的用途效果是一样的了吗？

**Comment by YoKeyword** [comment]
`onLazyInitView()`懒加载一般我们会常用的；

`onSupportVisible()`这个方法是当Fragment真正可见时触发，这个类似Activity的`onResume()`方法，实际上使用Fragment时也是经常需要的。

因为Fragment的特性：Fragment可见需要根据`onResume()`＋`onHiddenChanged()`/`setUserVisibleHint()`在2种不同的情况判断这3个方法来识别是否对用户可见；

很明显这2种情况的判断有些烦琐，所以Fragmentation里就加了`onSupportVisible()`和`onSupportInvisible()`方法来轻松代替类似Activity的`onResume()`的方法
