### ISSUE TITLE
fragment的部分类容被状态栏遮挡

### ISSUE THREAD

**Issue by lzqjfly** [YoKeyword/Fragmentation#23]
主界面的Activity有中的Fragment没有全屏展示，但是新的fragment全屏展示了，有部分类容被状态栏挡住了。主Activity侧滑时背景是黑色，也在主题中设置了<item name="android:windowIsTranslucent">true</item>

**Comment by YoKeyword** [comment]
@lzqjfly Fragment内的根布局 不要设置android:fitsSystemWindows="true"，如果设置请在Activity内的根布局里设置；
