### ISSUE TITLE
将support包的版本提高到25.1.1会出现莫名其妙的问题

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#230]
将support包的版本提高到25.1.1会出现莫名其妙的问题

**Comment by weiyf** [comment]
我将demo clone下来， 改了support包版本到25.1.1，也会出现莫名其妙的问题， 主要体现在仿微信demo和仿知乎demo。

**Comment by YoKeyword** [comment]
感谢反馈🙏， 大致看了下： 25.1.1的v4包在`loadMultipleRootTransaction()`时，事务会被"阻塞“；

刚提交一个commit修复了该问题： 在load后，`executePendingTransactions()`立即执行待定事务；

没有发新版，这个应该不急哈，我这两天有空会添加 栈视图悬浮球的功能，到时一起发新版哈～
