### ISSUE TITLE
我的as版本更新最新的2.3 beta3 发现严重卡顿‘

### ISSUE THREAD

**Issue by douya40** [YoKeyword/Fragmentation#231]
我的as版本更新了一下发现严重卡顿‘,基本不能正常使用，什么情况呢，急解决呀

**Comment by YoKeyword** [comment]
如果你使用了25.1.1的官方support包，升级到0.10.0即可， 25.1.1有个同时加载多Fragment会阻塞事务队列的问题； 0.10.0解决了该问题
