### ISSUE TITLE
获取正在显示的Fragment

### ISSUE THREAD

**Issue by Blankeer** [YoKeyword/Fragmentation#234]
通过查看源码，Fragmention#getActiveFragment方法可以达到要求，但是外部无法调用。
建议公开SupportActitivy#getFragmentation方法。
😥

**Comment by YoKeyword** [comment]
好的  下个版本会暴露出来；  

现在暂时不打算发新版本， 要不你先把`getActiveFragment()` 复制出来先顶替用着？   

发新版本的时候再@你～

**Comment by Blankeer** [comment]
ok,thinks.
