### ISSUE TITLE
SupportFragment中InputMethodManager导致内存泄漏

### ISSUE THREAD

**Issue by xialei92** [YoKeyword/Fragmentation#235]
* DiscoveryFragment has leaked:
* GC ROOT android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper.mMainLooper
* references android.os.Looper.mThread
* references thread java.lang.Thread.localValues (named 'main')
* references java.lang.ThreadLocal$Values.table
* references array java.lang.Object[].[3]
* references android.support.v7.widget.GapWorker.mRecyclerViews
* references java.util.ArrayList.array
* references array java.lang.Object[].[2]
* references android.support.v7.widget.RecyclerView.mContext
* references com.coolchat.aha.ui.common.MainActivity.mFragmentManager
* references android.support.v4.app.FragmentManagerImpl.mAdded
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* references com.coolchat.aha.ui.common.MainFragment.mDiscoveryFragment
* leaks com.coolchat.aha.ui.discovery.DiscoveryFragment instance

* Retaining: 745 KB.
* Reference Key: b43c77cb-3d7d-4eda-b2d4-f45bffcfe5e2
* Device: samsung samsung SM-G9350 hero2qltezc
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5 00f37f5
* Durations: watch=646520ms, gc=183ms, heap dump=4424ms, analysis=58480ms

* Details:
* Instance of android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper
|   mActive = false
|   mParentInputMethodManager = android.view.inputmethod.InputMethodManager@319171600 (0x13062c10)
|   mH = com.android.internal.view.IInputConnectionWrapper$MyHandler@319571872 (0x130c47a0)
|   mInputConnection = java.lang.ref.WeakReference@319571840 (0x130c4780)
|   mMainLooper = android.os.Looper@315101888 (0x12c812c0)
|   mDescriptor = java.lang.String@1900871792 (0x714d0070)
|   mObject = 547712040960
|   mOwner = android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper@320127856 (0x1314c370)
|   shadow$_klass_ = android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper
|   shadow$_monitor_ = 0
* Instance of android.os.Looper
|   static $staticOverhead = byte[24]@1906332305 (0x71a05291)
|   static sThreadLocal = java.lang.ThreadLocal@1903796584 (0x7179a168)
|   static sMainLooper = android.os.Looper@315101888 (0x12c812c0)
|   static TAG = java.lang.String@1899480576 (0x7137c600)
|   mLogging = null
|   mPackageName = java.lang.String@1899211432 (0x7133aaa8)
|   mQueue = android.os.MessageQueue@315098016 (0x12c803a0)
|   mSlowLapTimeEvent = -1
|   mThread = java.lang.Thread@2012618680 (0x77f61fb8)
|   shadow$_klass_ = android.os.Looper
|   shadow$_monitor_ = 0
* Instance of java.lang.Thread
|   static NANOS_PER_MILLI = 1000000
|   static defaultUncaughtHandler = com.tendcloud.tenddata.ft$a@315461472 (0x12cd8f60)
|   static count = 14868
|   static MAX_PRIORITY = 10
|   static $staticOverhead = byte[48]@1906263737 (0x719f46b9)
|   static NORM_PRIORITY = 5
|   static MIN_PRIORITY = 1
|   contextClassLoader = dalvik.system.PathClassLoader@315407840 (0x12ccbde0)
|   daemon = false
|   group = java.lang.ThreadGroup@1903537344 (0x7175acc0)
|   hasBeenStarted = false
|   id = 1
|   inheritableValues = null
|   interruptActions = java.util.ArrayList@2013570240 (0x7804a4c0)
|   localValues = java.lang.ThreadLocal$Values@2013570264 (0x7804a4d8)
|   lock = java.lang.Object@2013570296 (0x7804a4f8)
|   name = java.lang.String@2013570304 (0x7804a500)
|   nativePeer = 548297198080
|   parkBlocker = null
|   parkState = 1
|   priority = 5
|   stackSize = 0
|   target = null
|   uncaughtHandler = null
|   shadow$_klass_ = java.lang.Thread
|   shadow$_monitor_ = 0
* Instance of java.lang.ThreadLocal$Values
|   static $staticOverhead = byte[16]@1904166857 (0x717f47c9)
|   static INITIAL_SIZE = 16
|   static TOMBSTONE = java.lang.Object@1903748472 (0x7178e578)
|   clean = 16
|   mask = 127
|   maximumLoad = 42
|   size = 19
|   table = java.lang.Object[128]@329355264 (0x13a19000)
|   tombstones = 12
|   shadow$_klass_ = java.lang.ThreadLocal$Values
|   shadow$_monitor_ = 0
* Array of java.lang.Object[]
|   [0] = java.lang.ref.WeakReference@1903744080 (0x7178d450)
|   [1] = android.os.StrictMode$AndroidBlockGuardPolicy@315315312 (0x12cb5470)
|   [2] = java.lang.ref.WeakReference@322302944 (0x1335f3e0)
|   [3] = android.support.v7.widget.GapWorker@322303104 (0x1335f480)
|   [4] = null
|   [5] = null
|   [6] = null
|   [7] = null
|   [8] = null
|   [9] = null
|   [10] = java.lang.Object@1903748472 (0x7178e578)
|   [11] = null
|   [12] = java.lang.ref.WeakReference@1903796600 (0x7179a178)
|   [13] = android.os.Looper@315101888 (0x12c812c0)
|   [14] = java.lang.Object@1903748472 (0x7178e578)
|   [15] = null
|   [16] = null
|   [17] = null
|   [18] = null
|   [19] = null
|   [20] = null
|   [21] = null
|   [22] = null
|   [23] = null
|   [24] = java.lang.ref.WeakReference@2012921872 (0x77fac010)
|   [25] = android.graphics.Rect@315445728 (0x12cd51e0)
|   [26] = java.lang.ref.WeakReference@1903805720 (0x7179c518)
|   [27] = java.lang.ref.WeakReference@336030688 (0x14076be0)
|   [28] = java.lang.ref.WeakReference@1903746568 (0x7178de08)
|   [29] = char[20]@2013570496 (0x7804a5c0)
|   [30] = java.lang.Object@1903748472 (0x7178e578)
|   [31] = null
|   [32] = null
|   [33] = null
|   [34] = null
|   [35] = null
|   [36] = null
|   [37] = null
|   [38] = null
|   [39] = null
|   [40] = java.lang.ref.WeakReference@1903816912 (0x7179f0d0)
|   [41] = android.view.FocusFinder@315736704 (0x12d1c280)
|   [42] = java.lang.ref.WeakReference@1903746592 (0x7178de20)
|   [43] = java.lang.RealToString@2013570472 (0x7804a5a8)
|   [44] = java.lang.Object@1903748472 (0x7178e578)
|   [45] = null
|   [46] = null
|   [47] = null
|   [48] = null
|   [49] = null
|   [50] = null
|   [51] = null
|   [52] = null
|   [53] = null
|   [54] = java.lang.Object@1903748472 (0x7178e578)
|   [55] = null
|   [56] = java.lang.ref.WeakReference@1903749240 (0x7178e878)
|   [57] = java.util.Formatter$CachedDecimalFormat@321560672 (0x132aa060)
|   [58] = java.lang.ref.WeakReference@326673504 (0x1378a460)
|   [59] = android.database.sqlite.SQLiteSession@326676064 (0x1378ae60)
|   [60] = java.lang.Object@1903748472 (0x7178e578)
|   [61] = null
|   [62] = null
|   [63] = null
|   [64] = java.lang.ref.WeakReference@323969568 (0x134f6220)
|   [65] = java.util.HashMap@322311024 (0x13361370)
|   [66] = java.lang.ref.WeakReference@2012909344 (0x77fa8f20)
|   [67] = android.view.Choreographer@319182464 (0x13065680)
|   [68] = java.lang.ref.WeakReference@1903817632 (0x7179f3a0)
|   [69] = com.android.server.NetworkManagementSocketTagger$SocketTags@316150640 (0x12d81370)
|   [70] = java.lang.Object@1903748472 (0x7178e578)
|   [71] = null
|   [72] = java.lang.Object@1903748472 (0x7178e578)
|   [73] = null
|   [74] = null
|   [75] = null
|   [76] = null
|   [77] = null
|   [78] = java.lang.Object@1903748472 (0x7178e578)
|   [79] = null
|   [80] = java.lang.ref.WeakReference@2012909136 (0x77fa8e50)
|   [81] = android.view.ViewRootImpl$RunQueue@315175728 (0x12c93330)
|   [82] = java.lang.ref.WeakReference@326072736 (0x136f79a0)
|   [83] = android.graphics.Matrix@325502432 (0x1366c5e0)
|   [84] = null
|   [85] = null
|   [86] = java.lang.Object@1903748472 (0x7178e578)
|   [87] = null
|   [88] = null
|   [89] = null
|   [90] = null
|   [91] = null
|   [92] = java.lang.ref.WeakReference@326072768 (0x136f79c0)
|   [93] = android.graphics.RectF@326072832 (0x136f7a00)
|   [94] = null
|   [95] = null
|   [96] = null
|   [97] = null
|   [98] = java.lang.ref.WeakReference@1903763216 (0x71791f10)
|   [99] = android.animation.ValueAnimator$AnimationHandler@318016768 (0x12f48d00)
|   [100] = java.lang.Object@1903748472 (0x7178e578)
|   [101] = null
|   [102] = null
|   [103] = null
|   [104] = null
|   [105] = null
|   [106] = null
|   [107] = null
|   [108] = null
|   [109] = null
|   [110] = null
|   [111] = null
|   [112] = null
|   [113] = null
|   [114] = java.lang.Object@1903748472 (0x7178e578)
|   [115] = null
|   [116] = null
|   [117] = null
|   [118] = null
|   [119] = null
|   [120] = java.lang.ref.WeakReference@319662592 (0x130daa00)
|   [121] = org.greenrobot.eventbus.EventBus$PostingThreadState@323405152 (0x1346c560)
|   [122] = null
|   [123] = null
|   [124] = java.lang.ref.WeakReference@2012921120 (0x77fabd20)
|   [125] = android.os.StrictMode$AndroidBlockGuardPolicy@315315312 (0x12cb5470)
|   [126] = null
|   [127] = null
* Instance of android.support.v7.widget.GapWorker
|   static $staticOverhead = byte[16]@322440193 (0x13380c01)
|   static sTaskComparator = android.support.v7.widget.GapWorker$1@324801856 (0x135c1540)
|   static sGapWorker = java.lang.ThreadLocal@324801840 (0x135c1530)
|   mFrameIntervalNs = 16666666
|   mPostTimeNs = 0
|   mRecyclerViews = java.util.ArrayList@322303136 (0x1335f4a0)
|   mTasks = java.util.ArrayList@322303168 (0x1335f4c0)
|   shadow$_klass_ = android.support.v7.widget.GapWorker
|   shadow$_monitor_ = 0
* Instance of java.util.ArrayList
|   static $staticOverhead = byte[16]@1904302721 (0x71815a81)
|   static MIN_CAPACITY_INCREMENT = 12
|   static serialVersionUID = 8683452581122892189
|   array = java.lang.Object[12]@322291200 (0x1335c600)
|   size = 6
|   modCount = 70
|   shadow$_klass_ = java.util.ArrayList
|   shadow$_monitor_ = 0
* Array of java.lang.Object[]
|   [0] = android.support.v7.widget.RecyclerView@327421952 (0x13841000)
|   [1] = android.support.v7.widget.RecyclerView@329022464 (0x139c7c00)
|   [2] = android.support.v7.widget.RecyclerView@332073984 (0x13cb0c00)
|   [3] = android.support.v7.widget.RecyclerView@332420096 (0x13d05400)
|   [4] = android.support.v7.widget.RecyclerView@332556288 (0x13d26800)
|   [5] = android.support.v7.widget.RecyclerView@332614656 (0x13d34c00)
|   [6] = null
|   [7] = null
|   [8] = null
|   [9] = null
|   [10] = null
|   [11] = null
* Instance of android.support.v7.widget.RecyclerView
|   static TRACE_CREATE_VIEW_TAG = java.lang.String@320151712 (0x131520a0)
|   static FORCE_ABS_FOCUS_SEARCH_DIRECTION = false
|   static TRACE_HANDLE_ADAPTER_UPDATES_TAG = java.lang.String@320539

**Comment by YoKeyword** [comment]
> InputMethodManager的相关对象没有传递下去的话，通过检测的确会发现前一个Activity出现内存泄漏。但是实际上，InputMethodManager对象并不是完全归前一个Activity持有，只是暂时性的指向了它，InputMethodManager的对象是被整个APP循环的使用。

> 另外，InputMethodManager是通过单例实现的，不会造成内存的叠加，所以个人觉得InputMethodManager可能并不会造成实质的内存泄漏。
