### ISSUE TITLE
升级0.10.1之后开启stackView之后出现问题。

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#237]
升级0.10.1之后开启stackView之后，项目中使用DataBinding, 在Activity中使用`DataBindingUtil.setContentView(this, layoutResId)`返回的`ViewDataBinding`为空，注释掉stackView之后无此问题。

**Comment by YoKeyword** [comment]
感谢指出，确实没考虑到DataBinding的情况，等回头我看看修复下 :)

**Comment by YoKeyword** [comment]
已Fix， 下版本生效 :)
