### ISSUE TITLE
onEnterAnimationEnd时候还是有一下卡顿

### ISSUE THREAD

**Issue by zyyoona7** [YoKeyword/Fragmentation#24]
onEnterAnimationEnd()去加载缓存数据的时候就会在动画结束了但视图还没改变完成的时候会卡顿一下。

**Comment by YoKeyword** [comment]
@zyyoona7 不知道你是如何使用的，我的使用场景下，几乎不会卡顿：
`  public View onCreateView(...) {
        ...
        initView(); // 这里仅给toolbar设置标题，返回箭头
        return view;
    }

    @Override
    protected void onEnterAnimationEnd() {
        super.onEnterAnimationEnd();
        initLazyView(); // 这里设置Listener、Adapter、请求数据等等
    }`

各种重操作放到initLazyView里  :)

**Comment by zyyoona7** [comment]
我也是这样写的，我在`initLazyView(); // 这里设置Listener、Adapter、请求数据等等`做网络请求都没问题，就是直接初始化FragmentPagerAdapter并且给viewPager设置offset数据10以上就会卡顿现象(我是在机顶盒开发上用的)。我也在查找原因，还有fragmentation可以+hide,show吗？

**Comment by YoKeyword** [comment]
@zyyoona7 我为的初始化FragmentPagerAdapter也是放在initLazyView()里的，这样动画结束后才初始化Adapter，应该不会出现卡顿；

哈哈，刚刚push了0.7的版本，JCenter和README马上更新，你可以pull最新的代码看下 demo,仿知乎的，支持恢复复杂嵌套Fragment、同级Fragment（类似微信主页的show hide）等等，以及全新的类似事件分发机制的onBackPressSupport（0.6版本该方法有问题），以及实验性支持SharedElement的MD过度动画  :)

**Comment by zyyoona7** [comment]
so cool，马上pull
