### ISSUE TITLE
部分机型上启动某个页面时白屏

### ISSUE THREAD

**Issue by zgh0711** [YoKeyword/Fragmentation#241]
@YoKeyword 您好！
        我现在在开发中的一个项目中使用了您的这个库，用起来感觉良好，项目基本功能也基本开发完了，然而在测试的时候发现部分机型在启动某个页面的时候会白屏，但有时候退出来第二次再开的话又好了，
        这是客户那边测试的反馈，然而我这边测试的时候并没有出现这种情况，请问下有可能是什么原因导致的。
        项目中fragment的使用基本都是和您的demo上一样的，那个白屏的界面是嵌套在另一个fragment之上的，所以用的是您demo中的eventbus发通知，让根fragment去启动。
        库的版本是0.9.3，surpport 版本25.1.0，基本情况就是这样。
        望解答，谢谢！

**Comment by YoKeyword** [comment]
你好，

首先排除： 宿主Activity在Task栈内有超过1个的情况，因为这样会导致发Event时，2个Activity的同Fragment都接收到了事件，都跳转，而栈底的Activity因为处于不可见状态（ onSaveInstanceState已被回调），所以此时就会出现白屏；   解决方案： 宿主如果可以的话，启动模式设置为SingleTask

另外，查看下出现白屏页面时的栈视图，从栈视图分析是否出现异常； 记得同时模拟下内存重启时的场景（打开开发者模式的 “不保留活动”来模拟）

**Comment by zgh0711** [comment]
@YoKeyword 
说下我整个APP的大概流程，先通过一个SplashActivity来启动MainActivity，在MainActivity中根据身份的不同来加载不同的根布局
```
// TODO: 2017/1/4 此处需要根据身份的不同加载不同的界面
        if (MyApplication.mainUser != null) {
            if ("customer".equals(MyApplication.mainUser.role)) {
                if (savedInstanceState == null) {
                    loadRootFragment(R.id.fl_container, CsMainFragment.newInstance());
                }
            } else if ("staff".equals(MyApplication.mainUser.role)) {
                if (savedInstanceState == null) {
                    loadRootFragment(R.id.fl_container, JgMainFragment.newInstance());
                }
            }
        }
```
然后在CsMainFragment和JgMainFragment中都有4个tab，现在是发现在CsMainFragment的第一个tab中点击按钮启动一个fragment的时候会白屏，
CsMainFragment 中的启动代码为
```
@Subscribe
    public void onStartBrother(StartBrotherEvent event) {
        _mActivity.logFragmentStackHierarchy("parent");
        start(event.targetFragment);
    }
```
很奇怪的一个问题就是这里在启动之前并没有打出栈视图。
启动之后的栈视图如下：
```
═══════════════════════════════════════════════════════════
                     	栈顶			AddStoreCarsFragment
                     
                     	栈底			CsMainFragment
                     
                     				子栈顶		CsOptionsFragment
                     
                     				↓			CsStoreFragment
                     
                     				↓			CsApplyFragment
                     
                     				子栈底		CsHomePageFragment
                     
                     ════════════════════════════════════════════════════════════
```
AddStoreCarsFragment为要启动的fragment，在某些机型上会白屏，我现在没有白屏的机器，还是拿的自己的不会白屏的机器测的，CsMainFragment子栈里的4个fragment为4个tab页面。
也就是说在CsHomePageFragment中点击按钮，发通知到CsMainFragment启动AddStoreCarsFragment的时候可能会白屏。

还有另一个地方也可以启动AddStoreCarsFragment界面，就是在CsStoreFragment这个界面，在CsStoreFragment这个页面的顶部bar上有个添加按钮，点击启动，启动后栈视图如下：
```
                        栈顶			AddStoreCarsFragment
                     
                     	栈底			CsMainFragment
                     
                     				子栈顶		CsOptionsFragment
                     
                     				↓			CsStoreFragment
                     
                     				子栈顶		CsStoreListFragment
                     
                     				子栈底		CsStoreListFragment
                     
                     				↓			CsApplyFragment
                     
                     				子栈底		CsHomePageFragment
```
其中CsStoreListFragment是CsStoreFragment的子容器，用来显示列表，有4个tab，用的viewpager。
CsStoreFragment只是充当一个容器的作用，启动AddStoreCarsFragment的按钮是在CsStoreFragment上。
启动时同样是发通知到CsMainFragment。

上面的就是具体的情况了，那么activity其实是只有一个MainActivity，只不过我没有设置启动模式，是否有必要将启动模式设置为singleTask，现在我自己手机上的 不保留活动 也打开了，还是没出问题。
现在出问题的机型有三星，oppo，小米1，5，然而我自己的红米note却没有出问题，简直了，，，

顺便前面提到的在eventbus的接收通知方法里面打印log没打出来要怎么办呢？

**Comment by YoKeyword** [comment]
1、如果白屏情况是这样的：  跳转白屏，然后点了返回再跳转还白屏，  而退出App后重新打开就正常的话，很有可能是MainActivity可能在Task里有2个， 此时SingleTask是必要的； 还一种就是不使用EventBus.getDefault()，而是new EventBus()，作用域是该Activity以及其Fragments;

2、不保留活动方法是：  进入App页面 点击Home回到桌面，再重新进入，如果你看到屏幕白了一瞬间，就代表页面被强制重启了

3、Log问题 不行就断点调试下；

第1点很重要，2种解决方案，最方便的还是SingleTask

**Comment by zgh0711** [comment]
感谢解答！
现在在打开“不保留活动”的情况下，从桌面回来的确实是白了一下再显示出来的。
你说这种情况代表页面被强制重启了，那么弱弱的问下，强制重启会带来什么问题呢，要怎么解决和避免？

**Comment by YoKeyword** [comment]
强制重启模拟的是：手机内存不足会强制收回Activity甚至是App整个进程， 但是不用太担心，因为系统会帮我们保存数据，在下次重启时帮我们恢复；  

`onSaveInstanceState()`就是保存数据的回调， 'onCreate(Bundle saveInstanceState)'的`saveInstanceState`就是恢复的数据， 被重启后saveInstanceState是不为空的；

所以我们要在必要的时候对关键数据进行保存， 然后在`onCreate()`里恢复取出来，具体要看业务场景了， 可以搜索相关知识看看

**Comment by zgh0711** [comment]
哦哦，谢谢！
