### ISSUE TITLE
Blank page. Please beginTransaction in onPostResume() after the Activity returns!

### ISSUE THREAD

**Issue by jk2K** [YoKeyword/Fragmentation#242]
My App Structure
![image](https://cloud.githubusercontent.com/assets/4025839/23298986/bdbff53a-faba-11e6-8d9a-712fdf3b33e3.png)

BottomBar has FragmentLazy1, FragmentLazy2, FragmentLazy3

## Code and Steps to reproduce
I click a button of Activity1, I want to go back to FragmentLazy2 and select tab FragmentLazy3 automatically.

Example Code
```
demoButton.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        activity1.finish();

        // use Event Bus for notifying MainActivity to select FragmentLazy3
        EventBus.getDefault().post(new TabEvent(TabEvent.MINE_POSITION));
    }
});


// here is the final code when receive event
MainActivity.showHideFragment(mFragments[position], mFragments[prePosition]);
```

## Expected result
selected tab FragmentLazy3, Fragment3 load

## Actual result
selected tab  FragmentLazy3, but FragmentLazy3 is blank, Fragment3 not load, got exception `Please beginTransaction in onPostResume() after the Activity returns!`

If I manually select FragmentLazy2, then manually select FragmentLazy3, the Fragment3 can be loaded successfully

Is there any problem with my code?

thanks

**Comment by YoKeyword** [comment]
Hi,
[Here](http://stackoverflow.com/questions/12450024/can-not-perform-this-action-after-onsaveinstancestate-why-am-i-getting-this)

And you can try to do this:
````java
    private boolean mNeedBeginTransaction;

    @Subscribe
    public void onEvent(TabEvent event){
        if(isSupportVisible()){
            MainActivity.showHideFragment(mFragments[position], mFragments[prePosition]);
        }else{
            mNeedBeginTransaction = true;
        }
    }

    @Override
    public void onSupportVisible() {
        super.onSupportVisible();
        if(mNeedBeginTransaction){
            MainActivity.showHideFragment(mFragments[position], mFragments[prePosition]);
            mNeedBeginTransaction = false;
        }
    }
````

**Comment by jk2K** [comment]
extremely grateful
