### ISSUE TITLE
fragment被回收?

### ISSUE THREAD

**Issue by supersugar** [YoKeyword/Fragmentation#243]
你好,我在用Fragmentation的时候,主页面是底部tab栏,对应三个fragment,就像这样:

if (savedInstanceState == null) {
  mFragments[FIRST] = HomeFragment.newInstance();
  mFragments[SECOND] = DiscoveryFragment.newInstance();
  mFragments[THIRD] = MyFragment.newInstance();
  loadMultipleRootFragment(R.id.fl_container, FIRST, mFragments[FIRST], mFragments[SECOND], mFragments[THIRD]);
}

但是有时候,不确定怎么操作,可能手机放了一会儿,可能重新在as编译运行项目后,问题出来了:
mFragments[]这个数组还在,但是里面没东西了,三个fragment都丢了,好像被回收了一样

而且另外一个地方,我使用ViewPager,在adapter中的getItem()方法中,会用一个map存好加载的Fragment,但是不知道什么情况下,也会出现map里面的fragment都不见的这种事

不知道作者能不能分析一下原因,或者有没有好的解决办法呢?求赐教~

**Comment by supersugar** [comment]
> mBottomBar.setOnTabSelectedListener(new BottomBar.OnTabSelectedListener() {
            @Override
            public void onTabSelected(int position, int prePosition) {
                showHideFragment(mFragments[position], mFragments[prePosition]);
            }
            @Override
            public void onTabUnselected(int position) {
            }
            @Override
            public void onTabReselected(int position) {
            }
        });
    }

就是这个地方showHideFragment(mFragments[position], mFragments[prePosition]);
在有些时候mFragments不会为null,但是数量变为0了,里面的fragment都没了,这时候点击底部的tab栏,就不能切换页面了,始终留在当前页

**Comment by YoKeyword** [comment]
````java
if (savedInstanceState == null) {
   mFragments[FIRST] = HomeFragment.newInstance();
   ...
}else{
  // 这里写了吗？
  mFragment(FIRST) = findFragment(HomeFragment.class);
}
````
如上，else里是否调用找回的代码？

你的情况应该是内存不足，系统回收了页面资源，回来时在恢复页面时你没有找回Fragment绑到mFragments里，导致的数组为空

**Comment by LichFaker** [comment]
同样遇到这个问题；
复现： 打开应用，修改系统的字体显示大小，从后台恢复应用；
我使用的是`showHide`方法，在最终`commitAllowingStateLoss`返回了-1，导致页面不能切换

**Comment by YoKeyword** [comment]
嗯 字体大小修改 也会导致页面重启；

你先看下是否确定做了Fragment的恢复绑定，更严谨的写法：
````java
fragment = findFragment(HomeFragment.class);
if (fragment == null) {
   mFragments[FIRST] = HomeFragment.newInstance();
   ...
}else{
  mFragment[FIRST] = fragment;
}
````

**Comment by LichFaker** [comment]
@YoKeyword 确定在`createView`中做了Fragment的恢复绑，得到的`findFragment`一直是`null`，但已重新实例化赋值

**Comment by YoKeyword** [comment]
@LichFaker 为`nul`l， 说明被杀之前该Fragment确实没有加入该Fragment的栈内（看下是否栈层级问题，`findFragment` or `findChildFragment`）

**Comment by LichFaker** [comment]
@YoKeyword 确实是层级问题，另外，tab页无法切换是因为加载了两个相同的Fragment，换成不同后问题解决
