### ISSUE TITLE
在使用loadMultipleRootFragment出现一点问题

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#244]
下面两张图是使用`loadMultipleRootFragment`时的情况，同样一个fragment，同样一个布局，放在第一个tab的时候是没有问题的，但是点击切换到非第一个tab的时候就会出现图二的情况，布局顶到statusbar上了，用的方法是`showHideFragment`

![o f974 t3 lpl cyr2b z5](https://cloud.githubusercontent.com/assets/12067656/23539960/65eb9242-0019-11e7-9b23-b294192c7764.png)

![vqd 5 np0 fb wrww jm9](https://cloud.githubusercontent.com/assets/12067656/23539897/104f904a-0019-11e7-875e-0af122d3f04e.png)

但是我使用正常的fragment用法来切换fragment，没有用`loadMultipleRootFragment`和`showHideFragment`出来的结果是正常的。

![rc 6cv t2yv 6km i3inr](https://cloud.githubusercontent.com/assets/12067656/23539849/c2f1ae5a-0018-11e7-8783-f0422ba72c26.png)

**Comment by YoKeyword** [comment]
是否使用了`android:fitsSystemWindows=true`属性, 或`CoordinatorLayout`的布局， 同级的情况下，用了上述的属性、布局，会导致StatusBar位置、高度不正常； 这是官方的问题，解决方式在特定布局设置Padding，这个[Issue](https://github.com/YoKeyword/Fragmentation/issues/137)里有提到该问题

**Comment by weiyf** [comment]
@YoKeyword 不是这个问题，现在是同样的fragment，在第一个和非第一个出现的两种情况，但是我用`getSupportFragmentManager().beginTransaction().replace()`这种方式，在第几个都是正常的。

**Comment by YoKeyword** [comment]
`replace()` ?     你试试add, show/hide;
因为`loadMultipleRootFragment()`内部是add(),  `showHideFragment()`内部是show()+hide();

**Comment by weiyf** [comment]
@YoKeyword 刚测试了一下， 发现并不是`loadMultipleRootFragment()`的问题，是如果只有一个fragment就正常，但是多于一个fragment就出现上面顶上去的效果，就算是`loadRootFragment()`之后再start同一个fragment也会出现这种情况。（下图是点击返回键瞬间的截图）
![e 3ohi1 5ywg i29x2wplm](https://cloud.githubusercontent.com/assets/12067656/23596307/3a7582ce-0264-11e7-809e-5bf155b77c64.png)

**Comment by YoKeyword** [comment]
你会发现正好差了一个StatusBar的高度，  Fragment和StatusBar在某些情况有不兼容问题，官方的问题；

我目前遇到该问题时 一般是使用了`CoordinatorLayout`， 我的解决方式是：给根View设置一个StatusBar高度的PaddingTop
