### ISSUE TITLE
仿知乎效果，showHideFragment()导致其他页面不显示，只能用start()的方式

### ISSUE THREAD

**Issue by androidXiaoHao** [YoKeyword/Fragmentation#245]
作者您好，在使用过程中遇到这样的问题，类似知乎效果，单Activity+多Fragment的形式，宿主Activity中加载四个fragment，底部导航栏我是直接用一个线性布局来做的，没有使用作者demo中的BottomBar，如下图
![demo123](https://cloud.githubusercontent.com/assets/16314954/23540132/78a70528-001a-11e7-8e1f-42a1a36761a9.png)
当点击底部导航栏中的四个按钮时加载不同的fragment，代码如下
![demo321](https://cloud.githubusercontent.com/assets/16314954/23540365/c84e9afe-001b-11e7-81c7-6a53ffffe6d8.png)
是哪里使用的姿势不对吗？希望作者能抽时间帮看看，在线等啊

**Comment by YoKeyword** [comment]
先明确用的哪种栈设计，  然后看下操作的栈层级是否正确～

`showHideFragment()`不建议使用单参数的方法， 建议使用`showHideFragment(showFragment,hideFragment)`两参数的方法

> 单参数的方法，下版本会标记为 过时

**Comment by androidXiaoHao** [comment]
就像上面效果图那样，底部导航栏就是一个线性布局包裹四个按钮，点击不同的按钮显示不同的fragment页面。在处理按钮的点击事件中，如果用showHideFragment(showFragment,hideFragment)两参的方法，比如说当我点击了分类按钮，那么第二个参数该怎么搞啊（也就是这个hideFragment）？我看了作者您的例子中是这样用的
![desc2](https://cloud.githubusercontent.com/assets/16314954/23686670/ed1abbb0-03e5-11e7-8ea5-b610b32e4fee.png)


说明：我在activity中是这样添加fragment的  
![desc](https://cloud.githubusercontent.com/assets/16314954/23686370/31c8b84a-03e4-11e7-978d-5d95ed66b85c.png)

**Comment by YoKeyword** [comment]
hideFragment，其实就是你在调用`showHideFragment()`之前，正在显示的那个Fragment，这个其实本来就需要用一个变量来标记index的，这个变量同时要做（`onSaveInstanceState()`）保存和恢复，保证页面重启后恢复到正确的index
