### ISSUE TITLE
请问如何在activity里面刷新另外一个fragment

### ISSUE THREAD

**Issue by stoneLee81** [YoKeyword/Fragmentation#247]
我在activity里面申明了同一个fragment，但UI不同，我现在需求是，大开另一个界面时，需要在activity里面，替换其中一个fragment,但没找到列子中DEMO，不知道如何处理，请问有类似方法么？

**Comment by stoneLee81** [comment]
mFragments[FIRST] = PaletteFragment.newInstance(wrapped1);
            mFragments[SECOND] = PaletteFragment.newInstance(wrapped2);
            mFragments[THIRD] = PaletteFragment.newInstance(wrapped3);

在activity里面，类似这样，一个fragment，不同界面，但现在需要在activity里面代码刷新第二个

**Comment by YoKeyword** [comment]
````java
@Subscribe
public void onRefresh(Event event){
     if(mFrom == wrapped2){
         // 刷新
     }
}
````
