### ISSUE TITLE
横竖屏切换时有点小问题

### ISSUE THREAD

**Issue by 452MJ** [YoKeyword/Fragmentation#248]
我发现从A跳到B，在B里面作横竖屏的切换，会对A的布局有影响

![1](https://cloud.githubusercontent.com/assets/13673008/23644392/1be650fc-0342-11e7-8cab-0310c8a75322.png)
![2](https://cloud.githubusercontent.com/assets/13673008/23644397/20ff72b2-0342-11e7-8f02-ff0b0c42f457.png)
![3](https://cloud.githubusercontent.com/assets/13673008/23644606/173f94ae-0343-11e7-804a-fc7da9f06336.png)

```
 <style name="AppTheme" parent="BaseTheme">
        <item name="android:windowBackground">@color/transparent</item>
        <item name="android:listDivider">@drawable/divider</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:fitsSystemWindows">true</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
 </style>
```

我已经在全局Styles中设置了android:fitsSystemWindows为true，用CoordinatorLayout来装载所有Fragment

**Comment by 452MJ** [comment]
方向一改变，前一个FG的状态栏就出现了问题

**Comment by 452MJ** [comment]
不用转屏的时候一切都还好，我也参考#137 自己加了paddingmargin。

**Comment by YoKeyword** [comment]
Fragment与StatusBar（CoordinatorLayout下）存在冲突， 目前我使用的就是padding的方式； 

可能暂时我也没完美办法推荐给你了～

**Comment by 452MJ** [comment]
@YoKeyword 这个padding我也加了，只是不明白在B中转屏为什么会影响到A。暂时我也只好取消沉浸栏的设计了

**Comment by feng612266** [comment]
> 
> 
> 不用转屏的时候一切都还好，我也参考#137 自己加了paddingmargin。

你好,#137 页面404打不开了
