### ISSUE TITLE
hide和show的时候怎么加动画？

### ISSUE THREAD

**Issue by zyyoona7** [YoKeyword/Fragmentation#25]
0.7用着相当爽啊，解决了我很多问题，但是想在hide和show的时候也有转场动画。自己扩展了一下，但是`setFragmentClickable()`状态有时不对

**Comment by YoKeyword** [comment]
@zyyoona7 同级的情况吗？  show和hide不需要动画啊 ，这种场景正常下也不能加动画的，因为动画是在add时Fragment才会回调动画的，而对于已经add的Fragment的show,hide是不会调用动画相关的。所有这里从官方Fragment的设计上就不建议在同级下加动画。

如果你在拓展时，导致防抖动失效，调用下SupportActivity的setFragmentClickable()即可。
其实目前库的封装应该是能满足绝大多数的使用场景了，对了现在写了wiki，有需要可以大致查看下 :)

**Comment by zyyoona7** [comment]
@YoKeyword 搜嘎了解了，wiki我都看了。主要现在做机顶盒，为了达到产品不要loading的效果才把以前的add做成同级。
