### ISSUE TITLE
多AC+多FG切换问题

### ISSUE THREAD

**Issue by 56858752** [YoKeyword/Fragmentation#250]
您好，我采用的是多AC+多FG模式。底部菜单按钮有直接点击打开AC的动作，当点击底部button时弹出ac，然后back或者close这个AC，返回到之前的FG，但底部的选项卡显示得不对。虽然我用标志位这种方式去解决了，但总觉得不好，不够优雅。不知道您有没有好的方法提供。谢谢。

（另：本来想录制GIF图片的，但没找到工具，请问你的demo图片用什么模拟器弄的）

**Comment by YoKeyword** [comment]
可以封装下底部菜单，标志位的逻辑放到底部菜单空间里，页面内组件化～

PS：录制GIF我用的[AndroidTools](https://github.com/mortenjust/androidtool-mac)，很好用
