### ISSUE TITLE
关于viewpager中懒加载的问题

### ISSUE THREAD

**Issue by zgh0711** [YoKeyword/Fragmentation#252]
@YoKeyword 您好：
        最近在做项目的时候发现一个问题，具体情况如下：
有一个页面使用的viewpager加tablayout，一共四个 tab ，首先在父容器中for循环初始化4个fragment，因为四个fragment都是列表，界面基本一样，所以是共用的一个页面，
 ```
    private void initData() {
        tabTitles.add("当前");
        tabTitles.add("未融");
        tabTitles.add("已融");
        tabTitles.add("历史");

        for (int i = 0; i < tabTitles.size(); i++) {
            Fragment tabFragment = CsStoreListFragment.newInstance(i);
            mFragments.add(tabFragment);
        }
    }

    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);
        mAdapter = new CsStoreTabAdapter(getChildFragmentManager(), mFragments, tabTitles);
        mViewPager.setAdapter(mAdapter);
        mTabLayout.setupWithViewPager(mViewPager);
    }
```
然后在列表页面CsStoreListFragment中：
   
   ```
 public static CsStoreListFragment newInstance(int position) {
        Bundle args = new Bundle();
        if (position >= 0) {
            args.putInt("tab_index", position);
        }
        CsStoreListFragment fragment = new CsStoreListFragment();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Bundle args = getArguments();
        if (args != null) {
            tab_index = args.getInt("tab_index");
        }
    }
```
在这个页面中使用懒加载请求列表数据。
```
@Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);
        recyclerViewEvent();
        initData();
    }
```
initData()就是请求列表数据的方法。现在的问题是这个懒加载，在第一次的时候是正常的，即进入页面，从tab1滑到tab4是一切正常，但是当从tab4往回滑了之后就开始出现 viewpager的预加载的情况了，就是从tab4滑到tab3的时候，从log中看到调用了tab2的数据请求方法。然后后面不管怎么滑就是viewpager的预加载，懒加载并没有起作用。

请问下我这种情况的话要怎么解决这个问题，谢谢。

**Comment by guokaihua** [comment]
setOffscreenPageLimit 默认为1。   设置为4 让几个页面滑动时都不销毁，就只会执行一次 预加载

**Comment by YoKeyword** [comment]
懒加载的'onLazyInitView()'的概念是：第一次可见该Fragment时会触发'onLazyInitView()'，

除此之外在ViewPager里还会： 
如 @guokaihua 所说 setOffscreenPageLimit 默认为1，即ViewPager会默认预加载相邻1个Fragment，当切换到第3个TAB时，第一个TAB会被销毁视图(onDestroyView)，再次重回第一个TAB时，会再触发'onLazyInitView()'

**Comment by zgh0711** [comment]
viewpager的特性我知道，这种预加载的特性有时候其实挺烦人的，只要想不要预加载，
起初以为懒加载可以起到这作用，结果现在看来好像没有很好的办法解决这个问题。
如@guokaihua 所说的将 setOffscreenPageLimit设为4其实也不符合我们项目的要求，设成4的话一次要请求的数据量就有些大了，反而更不好。

**Comment by guokaihua** [comment]
@zgh0711 可以网上参考BaseLazyFragment，设置为4，也可以实现具体滑动到哪个页面 就加载哪个页面的数据。

**Comment by YoKeyword** [comment]
@zgh0711  听你的需求，懒加载`onLazyInitView()`可以满足你的需求啊～

@guokaihua 设置4个的方案，也可以用的，但是如果资源比较敏感，这种方案不推荐～

**Comment by zgh0711** [comment]
@YoKeyword  在初次进入的时候，懒加载确实是正常起作用了，我现在的情况是从 tab1 滑到后面的 tab4，然后再从 tab4 往回滑的时候，就会出现预请求数据的情况。

我四个 tab 的数据请求方法都是写在 `initData()`方法里面，将 `initData()`放在`onLazyInitView()`里面，
```
private void initData() {
        if (tab_index >= 0) {
            switch (tab_index) {
                case 0://当前
                    url = Urls.BASE_URL + Urls.STOCK_CUSTOMER_CURRENT;
                    requestData(url, limit, 0, TYPE_REFRESH);
                    break;
                case 1://未融
                    url = Urls.BASE_URL + Urls.STOCK_CUSTOMER_NOLOAN;
                    requestData(url, limit, 0, TYPE_REFRESH);
                    break;
                case 2://已融
                    url = Urls.BASE_URL + Urls.STOCK_CUSTOMER_LOANED;
                    requestData(url, limit, 0, TYPE_REFRESH);
                    break;
                case 3: //历史
                    url = Urls.BASE_URL + Urls.STOCK_CUSTOMER_HISTORY;
                    requestData(url, limit, 0, TYPE_REFRESH);
                    break;
            }
        }
    }
```
根据tab的位置来调整 url 请求数据，现在的情况是当我从 tab4 往回滑到 tab3 的时候，从log上看到是请求的是 tab2 的数据，而从 tab3 滑到 tab2 的时候，同时请求了 tab2 和 tab1的数据，从 tab2到tab1的时候就只请求了 tab1，
前面也找了 @guokaihua 说的那个BaseLazyFragment，发现也不行，还不如咱们的 `onLazyInitView()` 好用。情况就是如此，望解惑！

**Comment by xushaun** [comment]
@YoKeyword 
懒加载的'onLazyInitView()'的概念是：第一次可见该Fragment时会触发'onLazyInitView()'
请问你上面说的这句话是什么意思，第一次可见该Fragment不是会触发onCreateView()方法吗？onLazyInitView()方法有什么意义吗？

**Comment by YoKeyword** [comment]
@zgh0711  才看到这个Issue回复...， 如果不想重新请求数据， 可以将数据才做全局变量， 当切换ViewPager视图重新创建时：
````java
 if(mData==null){
    initData();
 }
 
 UI.setData(mData);
````

**Comment by zgh0711** [comment]
嗯，这个思路倒是可以解决我的问题，谢谢！
