### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by luXiuKun** [YoKeyword/Fragmentation#254]
if (savedInstanceState == null) {
            mFragments[HOME] = HomeFragment.newInstance();
            mFragments[TRAINING] = TrainingFragment.newInstance();
            mFragments[EVENT] = EventFragment.newInstance();
            mFragments[MESSAGE] = MessageFragment.newInstance();
            mFragments[MYSELF] = MySelfFragment.newInstance();

            loadMultipleRootFragment(R.id.frag_container, HOME,
                    mFragments[HOME],
                    mFragments[TRAINING],
                    mFragments[EVENT],
                    mFragments[MESSAGE],
                    mFragments[MYSELF]);

        } else {
            CURRENT_TABPOSTION = savedInstanceState.getInt(CURRENT_TAB_KEY);
            OLD_TABPOSTION = savedInstanceState.getInt(OLD_TAB_KEY);
            mFragments[HOME] = findFragment(HomeFragment.class);
            mFragments[TRAINING] = findFragment(TrainingFragment.class);
            mFragments[EVENT] = findFragment(EventFragment.class);
            mFragments[MESSAGE] = findFragment(MessageFragment.class);
            mFragments[MYSELF] = findFragment(MySelfFragment.class);
            setCurrentFrag(OLD_TABPOSTION,CURRENT_TABPOSTION);
        }

private void setCurrentFrag(int oldTabpostion, int currentTabpostion) {

        if (oldTabpostion != currentTabpostion){
            showHideFragment(mFragments[currentTabpostion],mFragments[oldTabpostion]);
            OLD_TABPOSTION = CURRENT_TABPOSTION;
        }

    }

 @Override
    protected void onSaveInstanceState(Bundle outState) {
        outState.putInt(CURRENT_TAB_KEY,CURRENT_TABPOSTION);
        outState.putInt(OLD_TAB_KEY,OLD_TABPOSTION);
        super.onSaveInstanceState(outState);

    }

这种情景，第一次加载，出现 首页的fragment，oldpostion和currentpostion都为0，按下home键，执行onSaveInstanceState，进行状态存储，在acticity没有被销毁我又回来了，savedInstanceState 不为空，获取状态，这时old和current都为0，我该怎么操作ragment？showhide不能用了，start?

**Comment by YoKeyword** [comment]
在点击某个Tab时，先给currentTabPosition赋值，再执行`showHideFragment()`，这样逻辑就对了；

可以参照Demo里BottomBar的position管理逻辑~

**Comment by luXiuKun** [comment]
是的，我是这样做的，我的意思是 第一次进入old和current相等的情况，这时肯定只有一个fragment存在，现在我是判断的 相等情况用的showHide一个参数，不相等用的两个参数，我看其他问题里你说showhide一个参数的过时了

**Comment by YoKeyword** [comment]
切换逻辑可以参考下微信Demo，里面有相应处理
