### ISSUE TITLE
Android4.4.4 vivoY27 运行找不到DefaultHorizontalAnimator

### ISSUE THREAD

**Issue by qingshangming** [YoKeyword/Fragmentation#255]
我试了两个4.4.4系统的都找不到DefaultHorizontalAnimator  请问这是什么原因

**Comment by qingshangming** [comment]
java.lang.NoClassDefFoundError: me.yokeyword.fragmentation.anim.DefaultHorizontalAnimator

**Comment by qingshangming** [comment]
@Override
    public FragmentAnimator onCreateFragmentAnimator() {
        // 设置横向(和安卓4.x动画相同)

        return new DefaultHorizontalAnimator();
    }
找不到这个类

**Comment by YoKeyword** [comment]
检查下依赖的环境，引用库，  这个类是Fragmentation内部的类，依赖成功的话肯定可以找到这个类的
