### ISSUE TITLE
Fragment的SharedElement的兼容性问题

### ISSUE THREAD

**Issue by justinvoi** [YoKeyword/Fragmentation#256]
在官方在25.1.0上正常，而在高版本 25.2.0， 25.3.0进入时候共享元素动画失效，你把支持库版本改高运行知乎demo就能看见效果。
换用原生的替换fragment方式就没问题。

**Comment by YoKeyword** [comment]
Fragmentation内的SharedElement内部是以`add`方式添加的Fragment， `add`方式在25.0-25.1记得是有效正常的，25.0以下是不支持的，25.2开始官方的support包确实又出现了问题~ 
建议等官方来修复～

`replace`方式加载Fragment时SharedElement是一直正常的

**Comment by weiyf** [comment]
进入时候共享元素动画失效这个问题到25.4.0都还没有修复，谁英文好点的，去提个issues (｀・ω・´)

**Comment by YoKeyword** [comment]
@weiyf  哈哈，`add()`方式加载，24还是25的某个版本是好的， 后面的版本 入场动画 就失效了，出场是正常的

`replace()`倒是一直正常的...

**Comment by weiyf** [comment]
得去提个issues， 无奈英文不好。
