### ISSUE TITLE
点击事件穿透问题

### ISSUE THREAD

**Issue by ethanhua** [YoKeyword/Fragmentation#259]
我现在有一个需求就是 有两个fragment A和B，B是在A之后启动的 但B是透明的 现在需要点击B时 A对应区域的控件响应此点击事件 但是fragmentation库屏蔽了fragment事件间的穿透 现在A无法响应到点击事件 库相关代码如下：
![image](https://cloud.githubusercontent.com/assets/22186185/24133847/326b10c0-0e3b-11e7-80d9-e76c2156e70d.png)

希望此处可以设计为可配置选项（是否穿透点击事件）

**Comment by YoKeyword** [comment]
复写下B的`onActivityCreated()`方法：
````java
    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        View view = getView();
        if (view != null) {
            view.setClickable(false);
        }
    }

````

下版本应该会把库中的`setClickable(true)`移除，该方法以前加的，应该没用了～

**Comment by ethanhua** [comment]
ok
