### ISSUE TITLE
popBackStack使用

### ISSUE THREAD

**Issue by gpfduoduo** [YoKeyword/Fragmentation#26]
阅读了您在简书上的文章，有几个问题咨询一下：
1、按照你的说法 remove是有问题的，为什么startWithPop中调用了fragmentManager.beginTransaction().remove(from).commit();接口
2、startWithPop中调用了handleBack(); handleBack()中调用了fragmentManager.popBackStack();
紧接着在startWithPop中调用了事物处理，FragmentTransaction ft = fragmentManager.beginTransaction()
                                                .setTransition(
                                                        FragmentTransaction.TRANSIT_FRAGMENT_OPEN)
                                                .add(from.getContainerId(), to, toName)
                                                .addToBackStack(toName);

按照你文章的说法:"如果你想在出栈后，立刻beginTransaction()开始一项事务，你应该把事务的代码post到主线程的消息队列里',但是您的startWithPop没有通过post方法。
是不是只有调用popBackStackImmediate才使用post方法，因为：popBackStackImmediate是立刻出栈，popBackStack是放在主线程尾部

**Comment by YoKeyword** [comment]
@gpfduoduo 
1、 remove在对加入回退栈的Fragment是不能出栈的，这个是肯定的；但是它能让Fragment的视图从容器内移除，其实仅仅是为了视觉效果，startWithPop方法是为了让动画显示正常封装的方法，如果直接pop然后加载Fragment，此时的视觉效果是，当前Fragment伴随出栈动画出栈，然后目标Fragment伴随进栈动画进栈，这样视觉上和Activity的start并finish是不一致的；这个方法就是保证和Activity一致的封装方法；

2、 handleBack()中调用了fragmentManager.popBackStack(); 是为了配合上面说的remove()，因为Fragment事务并不是立即执行的，所有这时如果使用Immediately的方法，视觉上的动画会有问题，记得是闪烁，所有这里也是为了让这系列的动画正常执行而选择使用的popBackStack  :)

**Comment by gpfduoduo** [comment]
@YoKeyword  
谢谢了。
1、remove这个体会到了，调用remove方法之后，不管我调用多少次，getBackStackEntryCount()这个方法的个数不会变化。
2、popBackStack和popBackStackImmediate：除了动画方面的考虑。是不是因为他们两个的区别（一个放在主线程的尾部，一个立即执行），从而导致了调用immediately方法，如果立即执行事务，必须使用post方法，而popBackStack则不需要。不知道我理解的对不对…… 
再次表示感谢……

**Comment by YoKeyword** [comment]
@gpfduoduo 你的理解是对的；
库中你看到popBackStackImmediate()后跟了post / postDelay，是因为动画的原因；动画结束后，再执行其它事务方法，否则会在一些情况异常；
因为我的库中无动画的处理方式不同，所以用了post，如果你的动画是通过setCustomAnimations设定的，或者不设定，则直接跟事务即可，不需要post

至于popBackStack，因为它在出栈多个Fragment时问题比较大，难以监控，所以我一般不会选择该方法；出单个Fragment时，则很正常；handleBack()中我的顺序是remove -> popBackStack，这样即保证了正常执行的事务顺序，显示动画又不会发生闪烁（popBackStackImmediate会闪烁），所以选择popBackStack（说的可能有点乱，见谅。。。）

**Comment by gpfduoduo** [comment]
@YoKeyword 
谢谢了……
