### ISSUE TITLE
fragment 里面如果是二维码扫描。黑屏问题

### ISSUE THREAD

**Issue by wcnmtx** [YoKeyword/Fragmentation#262]
我把msgFragment 里面的内容改成一个二维码扫描。发现界面黑屏。是不是之前的界面挡住了？

**Comment by YoKeyword** [comment]
二维码没试过， 不过偏重量级的控件可以考虑放到Activity，你可以先用Activity解决下哈 :)

**Comment by wcnmtx** [comment]
后面我查看

**Comment by wcnmtx** [comment]
你好。问题找到了。是这样的。我虽然用了权限管理，我查看软件授权信息的时候，竟然发现它并没有授权，机型是小米5。有点坑爹。
