### ISSUE TITLE
你好 请问在一个fragmen中有一个Viewpager  viewpager中又加载了若干个fragment 然后在viewpager里面的fragment 不能通过start启动其他fragment是因为什么呢 请教一下

### ISSUE THREAD

**Issue by Anber-wei** [YoKeyword/Fragmentation#268]

**Comment by Anber-wei** [comment]
新手小白一只 栈什么的还不太理解呢 就想知道 viewpager中的fragment有什么办法可以启动外面的fragment 呢 感谢回复

**Comment by YoKeyword** [comment]
2种方式：
1、 给viewPager内的Fragment一个ParentFragment， 由这个ParentFragment启动外面的Fragment

2、viewPager内的Fragment是一个空壳，由Fragment内的ChildFragment启动

具体看Demo，对应WeChatDemo，知乎Demo
