### ISSUE TITLE
子fragment pop问题

### ISSUE THREAD

**Issue by ethanhua** [YoKeyword/Fragmentation#269]
版本 0.10.1
fragmentA  -> LoadRootFragmentB > FragmentB  中 startFragmentC -> 在FragmentC中 replaceFragment( D,false) -> 在FragmentD中 的按钮点击事件中 调用pop方法 
结果：
1.页面无任何反应 打印当前fragment栈的个数 发现已经被pop掉了 但是页面没有返回去显示FragmentB 而是无任何反应 
2.如果调用 改pop方法为调用getFragmentManager().beginTransaction().remove(this).commit(); 页面会出现空白 而不是FragmentB页面

**Comment by YoKeyword** [comment]
`start()`和`replace()`不能在同一栈层级内混用！！ （`start()`内部是`add()`）

所以你可以开一个子Fragment栈或父Fragment栈来`replace()`

**Comment by ethanhua** [comment]
为什么不能在同一栈层级混用？是现在还不支持吗？

**Comment by YoKeyword** [comment]
是官方Fragment不支持，会造成内部的栈混乱

**Comment by ethanhua** [comment]
谢谢作者解答 但是我还是不明白
1  为什么同一栈内 add和replace混用会造成混乱? 之前add到栈内的那个fragment用新的fragment替换掉不就行了吗？
2  如果开启一个子fragment栈或者父fragment栈来实现我的需求（点击返回可以后退到之前fragment的前一个fragment）又觉得平白多用一个fragment不太好

**Comment by YoKeyword** [comment]
1、 `add()`进去的Fragment如果没有加入回退栈的话，可以使用`replace()`替换，一旦有加入回退栈的行为就不是简单的`replace()`可以解决的了

2、混合使用 是特殊场景下的需求，强烈建议分栈层级，不然即使看着实现，但是一旦页面重启或其它情况，栈内就混乱从而导致崩溃～

**Comment by ethanhua** [comment]
好的 谢谢作者 解答问题速度这么给力
