### ISSUE TITLE
我用你demo中的仿知乎的那个，做了app主页，要实现"再按一次退出应用"的效果，应该怎么做呢？

### ISSUE THREAD

**Issue by zhengxiaochuan** [YoKeyword/Fragmentation#27]
如题

**Comment by YoKeyword** [comment]
@zhengxiaochuan 库中Fragment有一个onBackPressedSupport() 方法，按Back键触发，该方法优先级大于Activity中的onBackPressedSupport()方法；

在需要提示“再按一次退出”的Fragment页面上复写该方法，返回true (代表消费该事件，不再往上传递)
