### ISSUE TITLE
关于fragment路由

### ISSUE THREAD

**Issue by KeqingLI** [YoKeyword/Fragmentation#271]
你好 ARouter的跳转是面向跳转过程的 就目前ARouter的版本 只能获取到fragment实例 并不能处罚其拦截器工作 请提供一点思路

**Comment by YoKeyword** [comment]
按我之前的设想，是打算做更智能的Fragment Router； 时间关系先建议使用ARouter，在你模块化项目时可以满足需求；

目前确实是面向过程的，可以通过协议拿到 目标SupportFragment 对象，然后调用方来决定是以`start()`还是`loadRooutFragment()`启动目标Fragment。 
也就是说ARouter提供了任意模块的Fragment，具体怎么加载是调用方自己的事了。
