### ISSUE TITLE
how to handler visible each fragment in ViewPager

### ISSUE THREAD

**Issue by ngochuu90** [YoKeyword/Fragmentation#272]
Hi @YoKeyword 

I have a ViewPager that consists of 4 Fragment.
When I start App, `onSupportVisible` is called in 4 Fragment

How to handler visible each fragment in ViewPager

**Comment by YoKeyword** [comment]
Hi, @ngochuu90 

`onSupportVisible()` is callback when the Fragment visible to the user。
（`onSupportVisible()` is a combination of `onHiddenChanged()` and `setUserVisibleHint()`）

**Comment by ngochuu90** [comment]
Thanks for your answer.

But `onSupportVisible()` was called four fragments at the same time.
I want to handler `visible `each fragment in ViewPager.
For example: Viewpager include: Fragment A, B, C, D
When viewpager setCurrentItem(A). `onSupportVisible()` is not called in B, C, D
When viewpager setCurrentItem(B). `onSupportVisible()` is not called in B
When viewpager setCurrentItem(C). `onSupportVisible()` is not called in C
....

Looking forward to receiving your help. Thank you

**Comment by YoKeyword** [comment]
Which version do you use?  

v0.10.1:  As you would expect:
> When viewpager setCurrentItem(A). onSupportVisible() is called in A, is not called in B, C, D
When viewpager setCurrentItem(B). onSupportVisible() is called in B
When viewpager setCurrentItem(C). onSupportVisible() is called in C
....

<img width="504" alt="1" src="https://cloud.githubusercontent.com/assets/9691640/24588088/39b5def6-17f4-11e7-8611-ac69cce9e2fe.png">

**Comment by ngochuu90** [comment]
It seems I have some confusion. Thanks for your support. Great Library

**Comment by ngochuu90** [comment]
My problem:

D is blank fragment.  In D, I `loadRootFragment(Fragment E)` in `onCreateview()`
`onSupportVisible() `is not called in D, but is called in E

**Comment by YoKeyword** [comment]
Thx！
I got it and fix it.
