### ISSUE TITLE
把app退到后台时，去改变系统的语言设置

### ISSUE THREAD

**Issue by qinyang1018** [YoKeyword/Fragmentation#274]
把app退到后台时，去改变系统的语言设置切换到其他语言，在回到app时会崩溃，是getActivity()为null了 。这种应该怎么处理呢，有什么好的办法吗？  
我目前的处理办法是在判断语言被改变后主动去重启整个app

**Comment by YoKeyword** [comment]
...  不建议这么处理！ 

首先，可以通过打开开发者选项里的“不保留活动”模拟页面重启的情况；
其次`getActivity()=null`，说明Fragment还没来得及attach到宿主Activity上，所以为null

最后建议使用SupportFragment的_mActivity来代替getActivity()

**Comment by qinyang1018** [comment]
好的  我试试看
