### ISSUE TITLE
关于过度绘制

### ISSUE THREAD

**Issue by summer0906** [YoKeyword/Fragmentation#275]
单Activity实例配合多个Fragment入栈, 会导致入栈越深, 布局层次越深,从而导致了过度绘制
有没有什么好的优化办法呢?
公司APP现在是Mainactivity
->HomeFragment
&emsp;->FragmentA
&emsp;&emsp;&emsp;->FragmentD
&emsp;&emsp;&emsp;->FragmentF
&emsp;->FragmentB
&emsp;->FragmentC

**Comment by YoKeyword** [comment]
首先是选用合适的栈设计，比如推荐用WeChatDemo的栈设计，而不是知乎的～

另外单Activity多FG只是技术上的噱头，没必要为了单AC而单AC，如果必要，多模块AC才是最优解

**Comment by summer0906** [comment]
感谢
