### ISSUE TITLE
查找存在的 Fragment 的问题

### ISSUE THREAD

**Issue by BCsl** [YoKeyword/Fragmentation#276]
FragmentationDelegate 类有段注释 ：

> 如果是 查找Fragment时,则有可能是在FragmentPagerAdapter/FragmentStatePagerAdapter中,这种情况下,它们的Tag是以android:switcher开头,所以这里我们使用下面的方式

描述并不是十分准确，对于 FragmentPagerAdapter 来说才是以 android:switcher ，FragmentStatePagerAdapter 则为 null 的，当然这不是我的问题，我的问题是，根据我的业务来说，我的一个 FragmentStatePagerAdapter 里面，有 N 个 Fragment，类型都为 1，因为它们的逻辑一样，但展示形式实际上不一样，我是通过 新建 Fragment 的 arguments 来区别，这样就可以少些写 Fragment 实现类。而我看你的库在内存恢复的时候，则通过类名来比较来恢复 Fragment的，显然是不可靠的，因为有多个类名一样的 Fragment，而我又不能通过 tag（为 null ） 和 id（一样为 Viewpager 的 id） 来查找，我看到 mWho 变量是不一样的，但这个变量值和 mIndex 变量有关，感觉不太适用，现在是通过在 FragmentStatePagerAdapter#instantiateItem 方法中获得已经在内存中的 Fragment，不知道有没有好的方法？

**Comment by YoKeyword** [comment]
首先感谢指出 注释存在问题～ `FragmentStatePagerAdapter `确实是无Tag的；
 
其次FragmentStatePagerAdapter内在内存重启时并不需要特殊处理，来找到被销毁前的“Fragment”，因为Adapter已经帮你保存了,可以看其`saveState()`以及`restoreState()`等相关方法；

库本身是不帮你恢复Fragment的，只是修复了v4包24.0版本以下的可能导致的重叠问题（当然FragmentPagerAdapter系列不需要处理）, 你提到的注释对应的方法是`findStackFragment()`，它用作启动模式，而 FragmentPagerAdapter系列方法的第一级子Fragment不存在启动模式的概念，所以是没影响的。

另外一提，对于类似你的情况，可以使用如下方式手动设置Tag：（FragmentPagerAdapter内的第一级Fragment无意义，所以仅支持start/replace系列方法）
````java
 supportFragment.transaction()
                .setTag(tag)
                .commit();
// 接着执行start()
 start(supportFragment);
````

**Comment by BCsl** [comment]
感谢回复，我再思考下
