### ISSUE TITLE
onBackPressedSupport没有触发

### ISSUE THREAD

**Issue by 112721933** [YoKeyword/Fragmentation#277]
你好，我APP的首页是类似知乎首页，下面有多个tab，我参照你的demo也是用懒加载的方式，先是用loadMultipleRootFragment方法加载ContainerFragment，在ContainerFragment里面再用loadRootFragment加载HomeFragment，在HomeFragment用start()方法打开另一个XXXFragment，打开是正常的，但是点击返回键直接就退出应用了，后来发现是HomeFragment的onBackPressedSupport方法没有触发，直接就触发了ContainerFragment的onBackPressedSupport方法，然后就退出了，还有调试的时候发现XXXFragment的getParentFragment是ContainerFragment而不是HomeFragment，我已经跟你的仔细对比过了，还是找不到问题，能帮忙分析下是什么原因吗？

**Comment by YoKeyword** [comment]
HI，
1、`onBackPressedSupport`的机制是该Fragment或者其父Fragment处理过`onBackPressedSupport`并返回true， 则默认的back事件都会自孩子到父亲，自栈顶到栈低的找处理该BACK事件的Fragment；（有点难描述，看代码：ContainerFragment里可以这么写：）
````java
    @Override
    public boolean onBackPressedSupport() {
        if (getChildFragmentManager().getBackStackEntryCount() > 1) {
            popChild();
        } else {
            // 这里处理在ContainerFragment栈级的Back事件 （可见Demo的BaseMainFragment）
        }
        return true;
    }
````

2、XXXFragment是Home Fragment  `start()`的，start系列均是同级关系， `loadXX()`系列方法是加载根本子Fragment，是父子关系

**Comment by 112721933** [comment]
明白了，谢谢回复
