### ISSUE TITLE
startWithPop动画问题

### ISSUE THREAD

**Issue by 652028815** [YoKeyword/Fragmentation#278]
能解答下startWithPop动画是怎么处理的吗，demo中的效果是跟start方法的动画一致，但是我这边的效果却是先pop的动画，接着是start的动画。看了下startWithPop的源码，也没看出所以然来。

**Comment by YoKeyword** [comment]
你项目中使用`startWithPop ()`处的代码截图看下～

> `startWithPop ()`有个限制是，调用该方法的Fragment之前必须要有一个Fragment

**Comment by 652028815** [comment]
rootfragment是有的，顺序是rootfragment，fragmentA，fragmentB，在fragmentA中startwithpop

**Comment by 652028815** [comment]
截图传不上来，代码很简单，就是view.setOnclickListener->startWithPop();

**Comment by 652028815** [comment]
截图传不上来，代码很简单，就是view.setOnclickListener->startWithPop();

**Comment by 652028815** [comment]
private void handlerFinish(SupportFragment preFragment, SupportFragment from, SupportFragment to)

**Comment by YoKeyword** [comment]
FragmentationDelegate里的`startWithPop()`里是解决动画问题的；

可以看下源码～  不过既然Demo里正常，可以考虑下是否是栈层级，或者使用方式不正确

**Comment by 652028815** [comment]
源码没怎么看懂，可以讲解下大概思路吗？

**Comment by YoKeyword** [comment]
先出栈再进栈， 出栈时找到上一个Fragment的View，把View展现到出栈的那个Fragment上，视觉上就动画看着正常了

**Comment by 652028815** [comment]
还有一个问题，有这样一种情形，正在请求接口，按Home键，然后执行了onSaveInstanceState，接口请求完毕后接着fragment出栈，然后就直接crash了，有好的解决办法么？

**Comment by YoKeyword** [comment]
虽然库中对commit()系列方法做了commitAllowStateLossing()处理，但是pop()方法不存在类似方法

所以异步任务回调的Fragment，要考虑你说的这个问题的：
对于这种情况要类似如下处理：
````java
// 异步任务回调
onSuccess() -> popSafe();

void popSafe(){
     if(isSupportVisible()){
           pop();
     }else{
           flag = true;
     }
}

@Override
public void onSupportVisible(){
    if(flag){
         flag = false;
         pop();
    }
}
````

我突然想起 也许可以在库里把pop()之类方法的实现弄成上述形式，这样使用者就不必变心是否安全了～
我回头再考虑下

**Comment by 652028815** [comment]
技术大大，赞一个！
