### ISSUE TITLE
你好，请问使用您的框架后，如何让fragment只创建一次？

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#28]
你好，请问使用您的框架后，如何让fragment只创建一次？

我现在的需求类似于你仿知乎的主页，底部有个底部导航BottomBar， 用的是一个第三方的。现在来回切换的时候总是重新创建，请求网络。我现在想只在第一次点击开的时候创建fragment，请求网络获取数据，以后再点击到这一项的时候只要show。我看了你的代码有有个showHideFragment(mFragments[position], mFragments[prePosition]);
我用的这个BottomBar在点击选中回调public void onTabSelected(int position, boolean wasSelected) 
没有int prePosition这种参数。

请问我要怎么来隐藏之前的fragment，是用getTopFragment();吗？

   bottomNavigation.setOnTabSelectedListener(new AHBottomNavigation.OnTabSelectedListener() {
            @Override
            public void onTabSelected(int position, boolean wasSelected) {
                switch (position) {
                    case 0:
                        YaLiJiFragment fragment0 = findFragment(YaLiJiFragment.class);
                        if (fragment0 == null) {
                            popTo(YaLiJiFragment.class, false, new Runnable() {
                                @Override
                                public void run() {
                                    start(YaLiJiFragment.newInstance());
                                }
                            });
                        } else {
                            // 如果已经在栈内,则以SingleTask模式start
                            start(fragment0, SupportFragment.SINGLETASK);
                        }

                        break;

                    case 1:

                        WannengjiFragment fragment1 = findFragment(WannengjiFragment.class);
                        if (fragment1 == null) {
                            popTo(YaLiJiFragment.class, false, new Runnable() {
                                @Override
                                public void run() {
                                    start(WannengjiFragment.newInstance());
                                }
                            });
                        } else {
                            // 如果已经在栈内,则以SingleTask模式start
                            start(fragment1, SupportFragment.SINGLETASK);
                        }

                        break;

                    case 2:

                        LaboratoryStatisticFragment fragment3 = findFragment(LaboratoryStatisticFragment.class);
                        if (fragment3 == null) {
                            popTo(YaLiJiFragment.class, false, new Runnable() {
                                @Override
                                public void run() {
                                    start(LaboratoryStatisticFragment.newInstance());
                                }
                            });
                        } else {
                            // 如果已经在栈内,则以SingleTask模式start
                            start(fragment3, SupportFragment.SINGLETASK);
                        }
                        break;
                }
            }
        });

**Comment by YoKeyword** [comment]
@leguang prePosition这个需要你自己记录下，我的这个参数是我封装的Bottombar里记录的；
你自己定义个position用来记录当前选中的TabFragment的下标，然后维护这个下标即可～可参照Bottombar这个类的纪录方式  ：）
（ps：记得在onSaveInstanceState里保存，以及onCreate中恢复，以免页面被强杀后导致丢失position的状态）

**Comment by leguang** [comment]
明白，我试试
你的这一次升级让你的这个Fragmentation框架更丰满了，同时取消掉setContainerId();是明智的。之前那样不是很优雅。等下加班试试，若有问题还会来打扰你。这是第二次提问了。谢谢

**Comment by YoKeyword** [comment]
@leguang 嗯嗯，感谢支持！ 持续维护中～

**Comment by leguang** [comment]
@YoKeyword 
已经改好了，完美解决，后期再压力测试一下，有问题反馈给你。再次感谢。吃饭去耶……
