### ISSUE TITLE
弹出所有栈,启动新fragment, 用popTo无法实现

### ISSUE THREAD

**Issue by yangjieK** [YoKeyword/Fragmentation#280]

**Comment by YoKeyword** [comment]
`popTo(rootFragment, true, new Runnable{ start(新Fragment) })`
因为涉及到事务的连续执行，所以需要调用3个入参的方法；

如果不正确，看下是否是栈层级问题，是不是该调用`popToChild()`

**Comment by yangjieK** [comment]
public void popTo(String targetFragmentTag, boolean includeTargetFragment, Runnable afterPopTransactionRunnable)  我用popTo(null,true,new Runnable{ start(新Fragment)), 我发现你里面对null做了过滤

**Comment by YoKeyword** [comment]
肯定不能传null啊 ＝。＝ 

第一个参数代表 要pop到的TargetFragment， 第二个参数是 是否连TargetFragment一起pop， 第三个参数是 如果出栈后还需立即做Fragment事务，就放到其runnable里
