### ISSUE TITLE
Please beginTransaction in onPostResume() after the Activity returns!

### ISSUE THREAD

**Issue by huangdh2** [YoKeyword/Fragmentation#281]
在程序启动以后，有一定概率出现该问题，同时界面跳转，但是一片空白，返回后重新跳转正常`java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState!
W/System.err:     at me.yokeyword.fragmentation.FragmentationDelegate.supportCommit(FragmentationDelegate.java:309)
W/System.err:     at me.yokeyword.fragmentation.FragmentationDelegate.start(FragmentationDelegate.java:271)
 W/System.err:     at me.yokeyword.fragmentation.FragmentationDelegate.dispatchStartTransaction(FragmentationDelegate.java:169)
W/System.err:     at me.yokeyword.fragmentation.SupportFragment.start(SupportFragment.java:577)
W/System.err:     at me.yokeyword.fragmentation.SupportFragment.start(SupportFragment.java:572)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
W/System.err:     at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
W/System.err:     at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
W/System.err:     at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
W/System.err:     at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
W/System.err:     at card.mineFragemt.MineMainFragment.onClick(MineMainFragment.java:150)
W/System.err:     at android.view.View.performClick(View.java:4875)
W/System.err:     at android.view.View$PerformClick.run(View.java:20341)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
W/System.err:     at android.os.Looper.loop(Looper.java:224)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5911)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)`

**Comment by YoKeyword** [comment]
可能性：
EventBus发送了event，而超过1个的Activity里同时有Fragment接收，而必然有一个Activity是在后台的，不可见的Fragment是不允许执行事务的； （超过1个Activity的情况很有可能是你手抖启动2次）

对于Activity作用域内的Event，一种建议是 把EventClass创建在Activity内部类，可以避免上述问题发生
