### ISSUE TITLE
How to load new fragment when switch item Navigation View

### ISSUE THREAD

**Issue by astechplay** [YoKeyword/Fragmentation#282]
Hi @YoKeyword . Thanks for creating awesome library, I use your library in almost my projects.
I have an issue that how to remove old fragment and load new fragment in backstack.
For example:
I have a navigation view which have 3 item: 
- Menu Item 1 -> switch to Fragment A and keep views.
- Menu Item 2 -> everytime I click to this item, I want to load new Fragment B to root container. I mean I want to remove old Fragment B (if exitst) and load new fragment B.
- Menu Item 3-> switch to Fragment C and keep views.
I use this code to switch between fragment A and C:
`showHideFragment(fragment, mFragments[prePosition]);`

But when I switch to fragment B, I do not know how to load new fragment B(onCreateView of fragment B will called) everytime I switch to Menu Item 3.
Thank you!

**Comment by YoKeyword** [comment]
Hi, @astechplay 
````java
-> ContainerFragment
	->   AFragment

	->   BContainerFragment(`replaceRootFragment(B,false)`)
		 ->   BFragment	 

	->	 CFragment
````

Or in BContainerFragment: (Please be sure to update to 0.10.3)
````java
       if (findChildFragment(B) == null) {
            loadRootFragment(id, B);
        } else {
            popToChild(B.class, true, () -> {
                    loadRootFragment(id, B);
                });
        }
````

**Comment by astechplay** [comment]
You saved my day! Really helpful. Thank you!
