### ISSUE TITLE
在onLazyInitView问题

### ISSUE THREAD

**Issue by jiahuahuang** [YoKeyword/Fragmentation#284]
在onLazyInitView中使用我写好的rx系列的东西，导致在跳转界面之后全部结束了事件流  这个是什么原因导致的？  怎么去处理他

**Comment by YoKeyword** [comment]
结束事件流说明2种情况：
走了`onComplete()` 或者 `onError()`，可以断点调试下看看

**Comment by jiahuahuang** [comment]
就是走了onComplete(),但是我不知道是因为什么原因导致的，目前我是自己在oncreate方法中写了一个子类的onIcreate方法  没有走你的onLazyInitView去做一个事件处理  这样就是完全正常，源码没有细看，暂时还不清楚是什么原因导致的。

**Comment by YoKeyword** [comment]
`onLazyInitView ()` 是在Fragment第一次对用户可见时触发， 如果可以，贴上你`onLazyInitView ()`下的代码

**Comment by jiahuahuang** [comment]
@Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState)
    {
        super.onLazyInitView(savedInstanceState);
        initViews(savedInstanceState);
        initData();
        initEvent();
    }
 @Override
    protected void initEvent()
    {
        super.initEvent();
        RxView.clicks(mBinding.rlSettings)
                .compose(bindUntilEvent(FragmentEvent.PAUSE))
                .throttleFirst(Config.TIME_THROTTLE, TimeUnit.MILLISECONDS)
                .subscribe(aVoid -> action2setting(), onError, onCompleted);
    }

    }

onCompleted在fragment中会被触发

**Comment by YoKeyword** [comment]
用了DataBinding?

**Comment by jiahuahuang** [comment]
是的。用了databinding，第一次进入显示界面触发了，并且可以正常弹无限弹吐司，但是只要走过onPause方法，onCompleted就会触发.

**Comment by jiahuahuang** [comment]
我现在有点怀疑是因为onLazyInitView实现是在onResumed实现的  然后bindToLifecycle在自动绑定生命周期的时候直接就给我绑定在了onResumed和onPause上，因为这个源码比较生涩，我没有仔细看，只是测试了没问题就使用上了。

**Comment by jiahuahuang** [comment]
刚刚确定了一下，确实是因为自动绑定生命周期的时候，直接给我绑定在了onResumed和onPause上，现在我指定绑定在compose(bindUntilEvent(FragmentEvent.DESTROY_VIEW))。这样运行就是正常的，是我的锅。麻烦了

**Comment by YoKeyword** [comment]
OK  解决就好～
