### ISSUE TITLE
java.lang.RuntimeException:Unknown animation name: x

### ISSUE THREAD

**Issue by LichFaker** [YoKeyword/Fragmentation#285]
如题，出现该异常。
说明： 在使用`onEnterAnimationEnd`前没有出现该异常，使用后出现，使用的是v4下的`Fragment`

**Comment by YoKeyword** [comment]
> java.lang.RuntimeException:Unknown animation name: x

这个就是提示的 x 吗？

你的`minSDKVersion` 是多少呢？

**Comment by LichFaker** [comment]
@YoKeyword `minSdkVersion ` 是14，有使用[腾讯的资源混淆库](https://github.com/shwenzhang/AndResGuard)， 但是已经将用到的animation添加到白名单中

**Comment by YoKeyword** [comment]
从 x 这个名字来看，很可能是 混淆的问题， 下面是Fragmentation内的动画资源:
<img width="241" alt="1" src="https://cloud.githubusercontent.com/assets/9691640/24889722/3b673438-1e9e-11e7-90b7-7f48a096ccc6.png">

**Comment by LichFaker** [comment]
反编译看过，除了`no_anim.xml` 和 `pop_exit_no_anim.xml`，其他都没有被混淆，像前面所说的，之前没有出现这个问题，但是混淆是一直在用的。我先将所有动画资源添加白名单，测试观察一段时间， 到时再回复 :)

**Comment by LichFaker** [comment]
该问题还是会出现，而且是偶现，排除混淆导致的问题，应该是兼容性问题。
编译后的包在公司测试机上测试均没有该问题，后台异常监控系统检测统计问题出现了43次，从版本显示上来看，均发生在使用了`onEnterAnimationEnd`方法后。
Google发现[相似问题](http://stackoverflow.com/questions/17760299/android-fragmenttransaction-custom-animation-unknown-animator-name-translate)

**Comment by YoKeyword** [comment]
@LichFaker  
stackoverflow的这个问题是：`Unknown Animator Name: Translate`
Animator是针对 系统Fragment的（它的动画都是Animator），而不是support-v4包下的Fragment（它的动画是Animation）

`AnimationUtils`源码:
````java
private static Animation createAnimationFromXml(Context c, XmlPullParser parser,
            AnimationSet parent, AttributeSet attrs) throws XmlPullParserException, IOException {
            ...
            String  name = parser.getName();

            if (name.equals("set")) {
                anim = new AnimationSet(c, attrs);
                createAnimationFromXml(c, parser, (AnimationSet)anim, attrs);
            } else if (name.equals("alpha")) {
                anim = new AlphaAnimation(c, attrs);
            } else if (name.equals("scale")) {
                anim = new ScaleAnimation(c, attrs);
            }  else if (name.equals("rotate")) {
                anim = new RotateAnimation(c, attrs);
            }  else if (name.equals("translate")) {
                anim = new TranslateAnimation(c, attrs);
            } else {
                throw new RuntimeException("Unknown animation name: " + parser.getName());
            }
            ...
        }
        return anim;
    }
````
如上，AnimationUtils 仅支持动画xml的set，alpha等标签，而库中的动画文件确实没有<x>标签（你的异常：`Unkown animation name: x`） ，所以应该还是混淆产生的问题
