### ISSUE TITLE
PopTo 为什么不remove targetfragment?  startWithPop()函数中使用remove 当前Fragment

### ISSUE THREAD

**Issue by yangjieK** [YoKeyword/Fragmentation#286]
startWithPop 也用pop 同时也在事务中添加remove 动作. popTo()怎么不添加remove被弹出fragment?

**Comment by YoKeyword** [comment]
额，没太理解你的意思；

startWithPop内部的remove是为了在视觉上达到理想的动画效果而做的特殊处理，本质等同于： pop() + start()

**Comment by yangjieK** [comment]
![image](https://cloud.githubusercontent.com/assets/4345445/24904023/b9c96a1a-1ee1-11e7-85b1-ccc84fb22af6.png)
这是 popTo()函数 的代码段;


这是startWithPop, 在pop之前执行了一段remove.. 为什么呢?
![image](https://cloud.githubusercontent.com/assets/4345445/24904069/e30444ae-1ee1-11e7-82ba-159deaf0adff.png)

**Comment by YoKeyword** [comment]
对于加入回退栈的Fragment, `remove`是不能让其出栈的，但是可以将视图从容器中移除，是为了保证视觉上的正常才这样处理的

> 不是很好描述，你会发现如果移除remove代码，视觉上就不对了

**Comment by yangjieK** [comment]
popTo时 为什么不也remove 回退栈的Fragment?

**Comment by YoKeyword** [comment]
`remove`是不能让加入回退栈的Fragment出栈的
