### ISSUE TITLE
fragment生命周期重写的不完善

### ISSUE THREAD

**Issue by nuli1228588792** [YoKeyword/Fragmentation#287]
当mianActivity的启动模式为singleTask或者singleInstance时，首次启动 mianActivity，加载fragment时会执行onSupportVisible方法，但是当mianActivity 跳转到其他的activity再进入mianActivity时，fragment的onSupportVisible方法就不会执行了，只执行 onResume 方法。而且mianActivity有多个rootFragment时，mianActivity 跳转到其他的activity再进入mianActivity时，多个rootFragment 不管是不是hidden状态，都会在同一时间执行 onResume 方法，感觉作者把fragment生命周期加进去后，都把fragment的生命周期弄乱了

**Comment by YoKeyword** [comment]
1、库中添加3个support生命周期，`onLazyInitView()`，`onSupportVisivble()`，`onSupportInvisible()`，这3个的添加完全是不影响Fragment原有的所有生命周期的；

****
> 当mianActivity的启动模式为singleTask或者singleInstance时，首次启动 mianActivity，加载fragment时会执行onSupportVisible方法，但是当mianActivity 跳转到其他的activity再进入mianActivity时，fragment的onSupportVisible方法就不会执行了

2、我测了下`singleTask`和`singleInstance`，在你说的情况下MainActivity可见时都会触发`onSupportVisible`

****
> mianActivity 跳转到其他的activity再进入mianActivity时，多个rootFragment 不管是不是hidden状态，都会在同一时间执行 onResume 方法

3、重新进入MainActivity，会回调MainActivity的`onResume`生命周期，从而其内的所有Fragments都会走`onResume`，这个是正常的，Activity的几个生命周期本来就会影响其内部的Fragment对应生命周期，可以查看官方文档: [Fragment](https://developer.android.com/reference/android/support/v4/app/Fragment.html)

**Comment by nuli1228588792** [comment]
但是当mianActivity 跳转到其他的activity再进入mianActivity时，fragment的onSupportVisible方法就不会执行了,不是返回mianActivity ，而是start  mianActivity

**Comment by YoKeyword** [comment]
@nuli1228588792   是的， 我刚测过了，是正常的，  你用的哪个版本？

MainActivity的Fragment是类似哪个Demo的栈视图？

**Comment by nuli1228588792** [comment]
@YoKeyword 我用的10版本的，MainActivity的Fragment是类似知乎的底部四个按钮的demo，而且mianActivity 重新启动的时候，所有的 rootFragment 都回调 onResume 方法是不是不太合理呢，因为只有一个fragment是可见的，其他的fragment都是隐藏的

**Comment by YoKeyword** [comment]
> mianActivity 重新启动的时候，所有的 rootFragment 都回调 onResume 方法是不是不太合理呢

这个是官方的设计，这个设计你细想，是很合理的～

我测试的就是知乎的Demo，MainActivity设置为singleTask,singleInstance，然后跳转到EnterAC，再通过startAC跳转到MainActivity，`onSupportVisible`正常执行

**Comment by nuli1228588792** [comment]
@YoKeyword 知乎的Demo 好像只有一个 MainActivity吧，我是仿照知乎的demo，但是是多个activity

**Comment by YoKeyword** [comment]
嗯，我是从MainAC跳的EnterAC， 一样的，  没问题， 你在MainAC里注册监听再试试？！

````
        registerFragmentLifecycleCallbacks(new FragmentLifecycleCallbacks() {

            @Override
            public void onFragmentSupportVisible(SupportFragment fragment) {
                Log.i("MainActivity", "onFragmentSupportVisible--->" + fragment.getClass().getSimpleName());
            }
        });
````

**Comment by nuli1228588792** [comment]
@YoKeyword  你在MainAC重新启动的时候 ，在intent 里传一个值，让MainAC跳到指定的 rootFragment，而不是之前的show的fragment，指定的rootFragment 就不会回调onSupportVisible方法了

**Comment by YoKeyword** [comment]
In Mainfest.xml:
````java
<activity
     android:name=".demo_zhihu.MainActivity"
     android:launchMode="singleTask"/>
````

In EnterActivity:
````java
Intent intent = new Intent(EnterActivity.this, me.yokeyword.sample.demo_zhihu.MainActivity.class);
intent.putExtra("test", "test");
startActivity(intent);
````

In MainActivity:(demo_zhihu包)
````java
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        // 跳到 我的
        mBottomBar.setCurrentItem(FOURTH);
    }
````
Log:  （从EnterAC重新startAC到MainActivity时）
<img width="622" alt="1" src="https://cloud.githubusercontent.com/assets/9691640/24900575/e46fb220-1ed6-11e7-8b7c-4c056fe8c5b8.png">

**Comment by nuli1228588792** [comment]
@YoKeyword  我在

@Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        // 跳到 我的
      getSupportFragmentManager().beginTransaction()
					.show(mFragments[1])
					.hide(mFragments[0])
					.hide(mFragments[2])
					.hide(mFragments[3])
					.commit();
    }
直接调的这个方法，我没有用你的那个mBottomBar 控件，我是用的radioGroup ，没有调showHideFragment(SupportFragment showFragment, SupportFragment hideFragment) 这个方法，所以 onSupportVisible 没有执行，@YoKeyword  你有解决方法吗？

**Comment by YoKeyword** [comment]
那原因可能就在这里了，建议使用`showHideFragment(SupportFragment showFragment, SupportFragment hideFragment)`方法， 没用BottomBar的话，记录下当前Fragment的Index即可 :)

**Comment by nuli1228588792** [comment]
@YoKeyword 我看你这个showHideFragment方法跟我写的其实原理一样啊，但是为什么就不回调了呢

**Comment by nuli1228588792** [comment]
@YoKeyword  我刚才换成了showHideFragment 方法，但是还是没有回调 onSupportVisible 方法，不知道是什么原因

**Comment by YoKeyword** [comment]
因为Fragment事务的特殊性，你试试把你的方法放到Handle里执行：
````java
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        handler.post(()-> 执行事务 );
    }
````
