### ISSUE TITLE
fragment出栈动画卡顿

### ISSUE THREAD

**Issue by summer0906** [YoKeyword/Fragmentation#289]
当fragment销毁时,在onDestroy方法中对地图进行销毁会导致动画卡顿,使用的是高德地图.
@Override
public void onDestroy() {
&emsp;&emsp;super.onDestroy();
&emsp;&emsp;mMapView.onDestroy();
&emsp;&emsp;mLocationClient.stopLocation();
&emsp;&emsp;mLocationClient.onDestroy();
 }

如果不做地图的销毁不会出现卡顿,有没有什么好的方法可以避免卡顿并且销毁地图

**Comment by YoKeyword** [comment]
地图销毁应该是要在主线程做一些耗时操作的，Fragment的`onDestroy()`方法是在Fragment出场动画执行时一起回调的，所以导致卡顿；  地图的销毁操作应该当到`onDestroyView()`里：
````java
@Override
public void onDestroyView() {
  mMapView.onDestroy();
  mLocationClient.stopLocation();
  mLocationClient.onDestroy();
  super.onDestroyView();
}
````

这样会执行完`onDestroyView()`再执行动画，就不再卡顿了

**Comment by summer0906** [comment]
如果放置在onDestroyView里,就会导致动画还未开始,地图销毁屏幕闪一下然后开始动画.不过这样确实不会导致卡顿

**Comment by YoKeyword** [comment]
闪一下？   我之前地图控件销毁时并不会闪烁， 地图控件的销毁在Fragment中放到onDestroyView里是最合适的
