### ISSUE TITLE
java.lang.IllegalStateException: Fragment already added: ContactHostFragment 

### ISSUE THREAD

**Issue by yangjieK** [YoKeyword/Fragmentation#291]
Step 1; Activity-> loadRootFragment( new ContactHostFragment()) 
 ContactHostFragment 包含ViewPager,ViewPager have Fragment1 and Fragment2 and Fragment3;

Step 2; 在ContactHostFragment 里面 点击某视图,执行start(new ContactFragment());

![image](https://cloud.githubusercontent.com/assets/4345445/24953762/1dfcc900-1faf-11e7-92e5-5576ec6c6cf8.png)

在step2中我并没有做 重复添加ContactHostFragment的动作, 然而
![image](https://cloud.githubusercontent.com/assets/4345445/24953828/689c94a4-1faf-11e7-91e2-ca2152cf91b7.png)
该Fragment源码中,final int numOps = mOps.size(); 
numOps 有两个动作 1.添加 ContactHostFragment ;2 隐藏ContactHostFragment

**Comment by yangjieK** [comment]
![image](https://cloud.githubusercontent.com/assets/4345445/24987483/cd10580c-2032-11e7-94f1-b47812d24914.png)
我发现以上错误的原因, 是 SupportFragment再次调用 start(this) ; this 是ContactHostFragment.

该bug怎么解决?

**Comment by yangjieK** [comment]
Sorry , this is my test bug. I forget to clear the codes

**Comment by YoKeyword** [comment]
在出现异常之前，先查看下栈视图，看看是否正常？
