### ISSUE TITLE
loadMultipleRootFragment()问题

### ISSUE THREAD

**Issue by RoyXing** [YoKeyword/Fragmentation#292]
你好 我用loadMultipleRootFragment 加载多个fragment 
fragment可以逻辑可以正常执行
但是fragment显示不出来
断点 代码也都走了
fragment是用dagger注入的

**Comment by RoyXing** [comment]
补充一下 应该是只能显示出当前被选中的页面 其它的显示不出来

**Comment by YoKeyword** [comment]
在`loadMultipleRootFragment ()`情况下，切换Fragment需要建议用`showHideFragment()`，同时看下栈视图是否正常

最好和Demo比较下是否有不同之处～

**Comment by RoyXing** [comment]
@YoKeyword 我用的就是showHideFragment() 库中提供的那个工具我也有用 fragment都在栈中

**Comment by YoKeyword** [comment]
嗯，排查下外部原因，先和Demo比较下
