### ISSUE TITLE
关于fragment切换的问题

### ISSUE THREAD

**Issue by zhangle1** [YoKeyword/Fragmentation#294]
比如作者你的那个知乎demo  ， 
我想切换进入详情页 ，但是底部又去掉应该怎么做比较好?

**Comment by zhangle1** [comment]
ViewGroup.MarginLayoutParams p = (ViewGroup.MarginLayoutParams) mFlContainer.getLayoutParams() p.setMargins(0, 0, 0, 0);
 mFlContainer.requestLayout();
我有点想这么改 但是不知道有没有问题

**Comment by YoKeyword** [comment]
@zhangle1  给BottomBar提供一个`hide()`方法，然后通过接口或事件通知让其隐藏即可～
