### ISSUE TITLE
Fragmentation作为插件运行时崩溃

### ISSUE THREAD

**Issue by fanOfDemo** [YoKeyword/Fragmentation#295]
java.lang.IllegalAccessError: Illegal class access: 'android.support.v4.app.FragmentTransactionBugFixHack' attempting to access 'android.support.v4.app.FragmentManagerImpl' (declaration of 'android.support.v4.app.FragmentTransactionBugFixHack' appears in /data/user/0/com.xxx.demo/files/plugins/xxxx/xxxxx.jar)
                                                                             at android.support.v4.app.FragmentTransactionBugFixHack.isStateSaved(FragmentTransactionBugFixHack.java:27)

**Comment by YoKeyword** [comment]
FragmentTransactionBugFixHack 这个类是个"Hack"的类，它被放到和v4包Fragment相同的目录：
`'android.support.v4.app`  你看下是否和这个有关系

**Comment by fanOfDemo** [comment]
初步判断是因为，我的V4包是在宿主中被打包的，而这个"Hack"类却又被插件打包了，导致系统认为不在一个包体下，所以报错无法引用，暂时的处理只能先删了Hack类，测试没发现什么异常，不知作者是否有这方面的讲解文章，还请不吝赐教

**Comment by YoKeyword** [comment]
如果你没用到  同时出栈Fragment并再入栈其他Fragment等之类的复杂事务， Hack可以移除的；

不过建议下个版本主工程把Hack类集成哈～
