### ISSUE TITLE
关于Fragment中startForResult方法的问题

### ISSUE THREAD

**Issue by doudoubin** [YoKeyword/Fragmentation#296]
当Fragment利用startForResult方法打开多个Fragment时，会出现onFragmentResult方法中只能接收到最先打开的一个界面返回过来的数据，其他界面的数据会依次被栈下方的Fragment接收，但是Activity的startActivityForResult方法则不会出现这种情况；
应该是实现原理的不同造成的，但是有时候会有这种需求，希望大神可以完善。

**Comment by YoKeyword** [comment]
@nianxinbaiwan 能举例描述吗？  
打开多个Fragment是： A打开B，B打开C，C打开D
还是
A可以打开B，C，D这种？

**Comment by nianxinbaiwan** [comment]
A同时打开BCD这种

**Comment by YoKeyword** [comment]
````java
void onClick(View view){
     startForResult(AFragment, 1);
     startForResult(BFragment, 2);
     startForResult(CFragment, 3);
}
````
是这个意思吗？

**Comment by doudoubin** [comment]
恩,就是这个意思

**Comment by YoKeyword** [comment]
嗯，实现机制确实不同； 库中是把这个信息放到下一个Fragment中保存的～ 

这个考虑下版本更改实现方式吧， 暂时建议使用Activity作用域的EventBus来 通知、回调事件
