### ISSUE TITLE
关于showHideFragment(fragments[0]);的过时问题

### ISSUE THREAD

**Issue by likealeodog** [YoKeyword/Fragmentation#297]
过时原因是 建议使用更明确的{@link #showHideFragment(SupportFragment, SupportFragment)}
但是，即使不去遍历碎片集合了，不去采用隐藏所有的其他碎片，显示当前碎片的方式，对于明确的需要隐藏的碎片，其实还是需要遍历，比如RadioGroup的使用场景。在切换的时候，你并不知道之前你正在显示的碎片是哪个，因为我们只关心它的切换，不关心具体去切换谁。之所以会这么想，可能是因为我之前其实很少使用hide和show的方式去做碎片的切换，实际上都用replace，将碎片缓存，保证relpace不会被销毁掉，也就不用关心之前show的碎片了，现在使用这种方式，我不知道该用怎样的一种优雅的不去遍历的形式的找到之前的碎片，难道要使用临时碎片变量去持有最新的show的碎片引用，然后切换时再赋值给新的show碎片？目前就暂时只能想到这种方式是最快的查找切换形式了。
然后，我看到FragmentationDelegate中的
getActiveFragment(SupportFragment parentFragment, FragmentManager fragmentManager)函数要
但是这个函数是默认修饰符，非同包下的子类是访问不了的，现在，我就想问问有没有什么好的办法来解决这个问题？

**Comment by YoKeyword** [comment]
@likealeodog   过时的原因是： 如果你的嵌套比较复杂并且参杂其他的普通Fragment，单参数的`showHideFragment()`可能不会正常工作；

`showHideFragment(show, hide)`，并不需要临时Fragment变量去持有， 因为我们会用一个数组Fragments来保存所有的TabFragment，供后续的使用了操作；

`replace`当然也是可以的，但是如果你的页面不是特别特别复杂，占内存， `show/hide`其实是更好的方式；

`getActiveFragment()`之前也有小伙伴提过想要暴露该方法， 目前暂时不会暴露，建议拷贝过去作为Util类使用～
后续应该会有一个比较大的结构调整，这种方法会放到一个Helper类；

**Comment by likealeodog** [comment]
但是有没有什么好的办法去直接获取到目前所正在显示的碎片？难道需要自己去遍历数组然后isSupportVisibility去选择？

**Comment by likealeodog** [comment]
还有一个额外话，因为我找不到人问了。。。就是LayoutInflater.from(context).inflate的耗时问题，想请教下这个耗时有没有办法去解决？因为一般情况下它都存在于主线程的，而它在第一次加载的时候，有可能会有延迟，我这里测试出来最大的一个有200多ms，这要是多了岂不是直接ANR？而且界面卡顿用户体验也不好啊

**Comment by YoKeyword** [comment]
其实我们一般都会 记录正在显示的Fragment 的Index的， 比如Demo里这个Index我封装到了BottomBar里；

动画过程中你去inflate当然会卡顿， 你可以在非动画时间去inflate~

**Comment by likealeodog** [comment]
也不是动画时间啊 就是Fragment的onCreateView()中的inflate的去加载，导致我的主页要间隔1秒左右才会显示出来，有没有办法优化？
记录index也行 要是能直接省略掉hideFragment的传入就好了，自动隐藏切换，期待

**Comment by likealeodog** [comment]
还有个，SupportActivity中showHideFragment函数没有过时...

**Comment by YoKeyword** [comment]
你可以预加载， 即：已进入Activity，就把Fragment加入到栈内，这样就直接走了`onCreateView`, 这样带来的问题是Activity进入速度会慢点，但是Fragment不会空白一会

`showHideFragment()`单参数的是可以用的，只是在一些比较复杂和特殊的场景可能会有问题，但是绝大多数情况可以直接用的，SupportActivity里的应该是忘记标记了 - -!

**Comment by likealeodog** [comment]
就是进入Activity太慢，碎片空白倒是没出现。。。好吧 当前问题已经可以解决了 谢谢 我关闭了
