### ISSUE TITLE
Demo MenuListFragment重复新建子菜单

### ISSUE THREAD

**Issue by s3hengwu** [YoKeyword/Fragmentation#298]
每次点击菜单列表，都是重新实例化了fragment: 
ContentFragment fragment = ContentFragment.newInstance(mMenus.get(position));
怎么还是显示之前那个呢？
比如我第一次加载了“小菜”右边的菜单，下次点击进来还是原来的那个页面。

**Comment by YoKeyword** [comment]
第一次newInstance后，将ContentFragment作为全局变量保存即可
