### ISSUE TITLE
getTopFrament()方法存在bug

### ISSUE THREAD

**Issue by LinkZhang** [YoKeyword/Fragmentation#3]
fragmentManager.getFragments()返回的fragment序列可能与实际的顺序不一致，导致无法获取正确的栈顶fragment

**Comment by YoKeyword** [comment]
@LinkZhang getTopFragment方法里是
` SupportFragment getTopFragment(FragmentManager fragmentManager) {
        List<Fragment> fragmentList = fragmentManager.getFragments();
        if (fragmentList != null) {
            for (int i = fragmentList.size() - 1; i >= 0; i--) {
                Fragment fragment = fragmentList.get(i);
                if (fragment != null && fragment instanceof SupportFragment) {
                    return (SupportFragment) fragment;
                }
            }
        }
        return null;
    }
`
应该是你的场景下栈内找不到SupportFragment了；
另外谢谢你提醒，我会把每次开始Fragment事务时hack fix栈的顺序代码，放到popTo后，确保不会出现栈内顺序BUG
:)

**Comment by YoKeyword** [comment]
@LinkZhang 多多反馈哈 有任何问题随时提出 :)

**Comment by LinkZhang** [comment]
@YoKeyword 场景大概是这样连续pop多个fragment(A,B)再add(C)，发现C在getfragments()里的位置是2，再add fragment分配的位置是0,1；导致获取的栈顶fragment是C而不是新add的。本以为是异步操作引起的，放在runnable里也没起作用,后来把getTopFragmeng()改成以下代码正常了
```
int count = fragmentManager.getBackStackEntryCount();
if (count >0) {
     String tag = fragmentManager.getBackStackEntryAt(fragmentManager.getBackStackEntryCount() - 1).getName();
     Fragment fragment = fragmentManager.findFragmentByTag(tag);
     if (fragment != null && fragment instanceof BaseFragment) {
          return (BaseFragment)fragment;
      }
}
return null;

**Comment by YoKeyword** [comment]
@LinkZhang :+1: 非常非常感谢，这样处理确实最安全 ，明天我更新下哈，顺便把hack fix栈顺序的代码添加到pop后的地方，确保更安全~ :)

**Comment by YoKeyword** [comment]
@LinkZhang 另外再问下 是通过Fragmentation里的popTo方法来pop多个Fragment(A,B)然后通过start(C)的吗？     如果pop后接着start是连续的，你应该调用
`popTo(Class fragmentClass, boolean includeSelf, Runnable afterTransaction)`
这个方法，这方法是让你在pop之后紧接着开始下一项事务，比如start(C)

**Comment by LinkZhang** [comment]
@YoKeyword popTo()这个方法好像不能连to也pop，我需要清空所有fragment,所以我增加了一个popAll方法
```
 public void popAll(Runnable runnable){
        mActivity.preparePopMultiple();
        int count = mFragmentManager.getBackStackEntryCount();
        while (count>0){
            mFragmentManager.popBackStackImmediate();
            count--;
        }
        mActivity.popFinish();

        if (runnable!=null) {
            mHandler.post(runnable);
        }
    }
```

调用这个方法的确执行的是先pop后add,虽然BackStack已经为空了，但getFragments()并不为空，还是会出现新add的fragment顺序错误的问题，所以getTopFragment()通过顺序来取栈顶fragment会有问题

**Comment by YoKeyword** [comment]
@LinkZhang 我不理解为什么要这么处理 连续pop单个Fragment，我以前好像是测试过，是不安全的，会引起一些异常～     你现在的状况 BackSack为空 getFragments()不为空 说明出栈已经异常了
`popTo(第一个Fragment，true，new Runnable(你的后续事物)) `  这个方法我一直用的，目前没发现问题
你检查下 代码 用这个方法试试， 发生栈内异常就很危险了，应该从解决栈内异常解决这个问题 :)

**Comment by LinkZhang** [comment]
@YoKeyword 是吗，一直没什么异常，我改成这样应该可以吧
```
 public void popAll(Runnable runnable){
        mActivity.preparePopMultiple();
        int count = mFragmentManager.getBackStackEntryCount();
        if (count>0) {
            mFragmentManager.popBackStackImmediate(mFragmentManager.getBackStackEntryAt(0).getName(), mFragmentManager.POP_BACK_STACK_INCLUSIVE);
        }
        mActivity.popFinish();

        if (runnable!=null) {
            mHandler.post(runnable);
        }
    }
```

不过，我刚刚测试了一下，getFragments()的顺序还是不对，getFragments里的顺序真的可以标记fragment的真实顺序？

**Comment by YoKeyword** [comment]
@LinkZhang 异常不是报错，而是一些隐患
你getFragments的时机稍微延迟点打印下，Fragment相关的一些调试都需要稍微延迟下，我早上更新了getTopFragment方法，换成了你的方式，以及HackFix的方法，放倒了popFix里
`
private void popBackFix(Class<?> fragmentClass, int flag, final FragmentManager fragmentManager) {
        mActivity.preparePopMultiple();
        fragmentManager.popBackStackImmediate(fragmentClass.getName(), flag);
        mActivity.popFinish();

        mHandler.post(new Runnable() {
            @Override
            public void run() {
                FragmentTransactionBugFixHack.reorderIndices(fragmentManager);
            }
        });
    }
`
