### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by HeZaiJin** [YoKeyword/Fragmentation#30]
您好。
demo中，进入startForResult页面后，旋转screen方向，返回，二级详情页面的数据就没有了，但是再次旋转screen（停留在详情页面），数据又恢复了。

**Comment by YoKeyword** [comment]
@HeZaiJin 是DetailFragment页面是吧，那个页面好像是因为Design库23.3版本的CoordinatorLayout引起的，最早用的23.1的时候，这个BUG是不存在的；

你可以试试虽然没数据，但是滑动Toolbar到顶部或底部，数据又会回来....

然而在我实际项目中，几个用到CoordinatorLayout的页面，布局比Demo复杂(demo里仅仅内容是个TextView)，反而没遇到这个问题。

所以这个不是库的BUG，不过回头会想办法把demo里的这个CoordinatorLayout问题解决下 
感谢你的反馈哈  :)

**Comment by HeZaiJin** [comment]
谢谢回复！
