### ISSUE TITLE
关于 onSupportVisible 方法

### ISSUE THREAD

**Issue by nuli1228588792** [YoKeyword/Fragmentation#300]
我在一个activity里 TabLayout 结合viewPager使用时，每个viewpager显示一个fragment，左右滑动viewpager时，fragment的onSupportVisible 方法会有回调，但是点击TabLayout  的tab时，onSupportVisible 方法就回调了，请作者帮忙看一下呗

**Comment by nuli1228588792** [comment]
抱歉，写错了， 我这 点击Tab时ViewPager切换Fragment，没有触发onSupportVisible() 方法，所以在请教你的

**Comment by YoKeyword** [comment]
用的什么版本？  用的是FragmentPagerAdapter还是FragmentPagerStateAdapter ?

**Comment by nuli1228588792** [comment]
FragmentPagerStateAdapter

**Comment by YoKeyword** [comment]
Fragmentation版本用的哪个？

**Comment by nuli1228588792** [comment]
0.10.3

**Comment by YoKeyword** [comment]
@nuli1228588792  我试了下正常无嵌套场景以及 zhihuDemo里的场景， 都可以正常触发`onSupportVisible()`

你的场景是有复杂嵌套吗？  有的话栈视图贴一下，最好能描述栈层级层级

**Comment by nuli1228588792** [comment]
我刚才log了一下，有回调，是我搞错了，不好意思

**Comment by nuli1228588792** [comment]
@Override
	protected void initLazyView(Bundle savedInstanceState) {
		initTabAddViewPager(savedInstanceState);
	}
private void initTabAddViewPager(Bundle savedInstanceState) {
		adapter = new UserSharePageAdapter(getChildFragmentManager(), host);
		if (savedInstanceState == null) {
			useableFindFragment = UseableFindFragment.newInstance();
			overdueFindFragment = OverdueFindFragment.newInstance();
		} else {
			useableFindFragment = findChildFragment(UseableFindFragment.class);
			overdueFindFragment = findChildFragment(OverdueFindFragment.class);
			if (useableFindFragment==null){
				useableFindFragment=UseableFindFragment.newInstance();
			}
			if (overdueFindFragment==null){
				overdueFindFragment = OverdueFindFragment.newInstance();
			}
		}
		adapter.fragments.clear();
	         adapter.fragments.add(useableFindFragment);
		adapter.fragments.add(overdueFindFragment);
		adapter.notifyDataSetChanged();
		viewPager.setOffscreenPageLimit(1);
		viewPager.setAdapter(adapter);
		tabLayout.setupWithViewPager(viewPager);
		tabLayout.setTabMode(TabLayout.MODE_FIXED);
		tabLayout.setTabGravity(TabLayout.GRAVITY_FILL);

		viewPager.addOnPageChangeListener(pageListener);

	}

我在模仿 zhihuDemo的APP中，APP刚启动后，点击切换底部按钮的时候initLazyView 方法回调，添加俩个fragment，但是偶尔的时候点击这个按钮的时候 ，APP会崩掉，抛出这个  java.lang.IllegalStateException: Fragment already added异常 ，而且我追踪 异常 日志，竟然没有我这得代码，全是说Android 里边的代码，大神你知道这是怎么回事吗？ 我的fragment是继承的SupportFragment

**Comment by YoKeyword** [comment]
重复add了， 简单的做法是:
````java
if(!fragment.isAdded()){
     // todo       
}
````
