### ISSUE TITLE
程序主界面带tab的界面，启动时默认启动第一个fragment，但是点击tab进行切换时，偶现白屏。

### ISSUE THREAD

**Issue by huangdh2** [YoKeyword/Fragmentation#301]
04-21 17:04:15.577 1715-1715/com.compnay I/ViewRootImpl: finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=1 eventTime = 593784738 downTime = 593784738 title= com.compnay/com.compnay.activity.MainUserActivity
04-21 17:04:15.628 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 0, left = 0xd487d984d487d980, right = 0x1d82f51ec
04-21 17:04:15.628 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0x18d487d984, right = 0x262e277600000000
04-21 17:04:15.628 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 4, left = 0xd487da04d487d9f8, right = 0x44343315f
04-21 17:04:15.628 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0xd82f50c8d487da04, right = 0x18d82f503c
04-21 17:04:15.646 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 0, left = 0xd487d984d487d980, right = 0x1d82f51ec
04-21 17:04:15.646 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0x18d487d984, right = 0x262e277600000000
04-21 17:04:15.646 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 4, left = 0xd487d8fcd487d8f0, right = 0x44343315f
04-21 17:04:15.646 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0xd82f50c8d487d8fc, right = 0x18d82f503c
04-21 17:04:15.662 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 0, left = 0xd487d984d487d980, right = 0x1d82f51ec
04-21 17:04:15.662 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0x18d487d984, right = 0x262e277600000000
04-21 17:04:15.662 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 4, left = 0xd487da04d487d9f8, right = 0x44343315f
04-21 17:04:15.662 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0xd82f50c8d487da04, right = 0x18d82f503c
04-21 17:04:15.680 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 0, left = 0xd487d984d487d980, right = 0x1d82f51ec
04-21 17:04:15.680 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0x18d487d984, right = 0x262e277600000000
04-21 17:04:15.681 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 4, left = 0xd487d8fcd487d8f0, right = 0x44343315f
04-21 17:04:15.681 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0xd82f50c8d487d8fc, right = 0x18d82f503c
04-21 17:04:15.697 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 0, left = 0xd487d984d487d980, right = 0x1d82f51ec
04-21 17:04:15.697 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0x18d487d984, right = 0x262e277600000000
04-21 17:04:15.697 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 4, left = 0xd487da04d487d9f8, right = 0x44343315f
04-21 17:04:15.697 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0xd82f50c8d487da04, right = 0x18d82f503c
04-21 17:04:15.704 1715-1715/com.compnay D/SettingsInterface:  from settings cache , name = sound_effects_enabled , value = 0
04-21 17:04:15.704 1715-1715/com.compnay I/MainUserActivity: positon:2
04-21 17:04:15.706 1715-1715/com.compnay I/MainUserActivity: positon:2
04-21 17:04:15.721 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 0, left = 0xd487d9fcd487d9f8, right = 0x1d82f51ec
04-21 17:04:15.721 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0x18d487d9fc, right = 0x262e277600000000
04-21 17:04:15.721 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 4, left = 0xd487da34d487da28, right = 0x44343315f
04-21 17:04:15.721 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0xd82f50c8d487da34, right = 0x18d82f503c
04-21 17:04:15.734 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 0, left = 0xd487da2cd487da28, right = 0x1d82f5174
04-21 17:04:15.734 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0x18d487da2c, right = 0x262e277600000000
04-21 17:04:15.734 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 4, left = 0xd487d98cd487d980, right = 0x44343315f
04-21 17:04:15.734 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0xd82f5050d487d98c, right = 0x18d82f4fc4
04-21 17:04:15.734 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 0, left = 0xd487da2cd487da28, right = 0x1d82f5174
04-21 17:04:15.734 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0x18d487da2c, right = 0x262e277600000000
04-21 17:04:15.735 1715-1774/com.compnay D/skia_ne: SkTQSort: depth = 2, left = 0xd6c1f268d6c1f260, right = 0x3d47dae84
04-21 17:04:15.735 1715-1774/com.compnay D/skia_ne: SkTInsertionSort: left = 0xd82f5050d6c1f268, right = 0xcd82f4fc4

**Comment by huangdh2** [comment]
log日志都是正常的，情况，就这么几行。按返回键时，需要返回多按几次才有反应

**Comment by YoKeyword** [comment]
先看下自己的栈结构是Demo的哪种，然后对比下，看看哪里有问题

**Comment by winrainbow** [comment]
@huangdh2 您好，想问下  D/skia_ne: SkTInsertionSort: left = 0x18d487da2c, right = 0x262e277600000000 这是什么地方打印出来的？我用乐视手机调试时，一用到dialogFramgent就会打印这个，怎么关掉这个打印？谢谢~

**Comment by YoKeyword** [comment]
@winrainbow 一些定制ROM确实会打印一些奇怪的日志，比如魅族...  据我所知，并无什么影响，所以可以忽略 :)
