### ISSUE TITLE
fragment嵌套后的动画问题

### ISSUE THREAD

**Issue by MrXemo** [YoKeyword/Fragmentation#303]
我使用一个fragment 用 ViewPager 装载了三个fragment。  当父fragment执行进入动画时，子fragment一直处于不可见状态。  同样，执行退出动画时子fragment也是已经是不可见状态了。 导致进出动画时都是白屏的，请问一下应该怎么解决这个问题。

**Comment by YoKeyword** [comment]
FragmentPagerAdapter的构造函数内FragmentManager传的是什么？

你的场景需要传`getChildFragmentManager()`

**Comment by MrXemo** [comment]
的确是传getChildFragmentManager()

**Comment by YoKeyword** [comment]
Demo中WeChat，Zhihu Demo都有类似场景，你比较排查下

**Comment by MrXemo** [comment]
Demo中的类型场景是属于首页tab中的  没有进出动画比较  而且我在按照demo中实现了一次也是这种情况

**Comment by YoKeyword** [comment]
我刚在Demo中任意Fragment去`start(viewPagerFragment)`， viewPagerFragment内的子Fragment界面正常

**Comment by MrXemo** [comment]
子Fragment界面正常的  主要指得是子Fragment在父fragment的退出的过渡动画前变不可见了，只留下一个空白的父Framentz在执行动画

**Comment by YoKeyword** [comment]
@MrXemo  印象中官方的v4包在ViewPager嵌套这种情况，子Fragment在父Fragment退出时也会空白；

原因在于此时子Fragment的转场Animation返回null，所以相当于无动画，所以页面显示是空白了；

我已提交了解决的代码， 还没发布新版，Animation部分打算重构放入一个Delegate里，明天发布v0.10.4

**Comment by MrXemo** [comment]
解决了，谢谢
