### ISSUE TITLE
startForResult的问题

### ISSUE THREAD

**Issue by zs1973** [YoKeyword/Fragmentation#304]
我在A fragment里面 打开了B fragment 然后在B里面startForResult到 C fragment ，C fragment关闭之后B收不到信息。在A的onFragmentResult里面却能收到。我看栈的信息是这样的    A->C->B

**Comment by YoKeyword** [comment]
A -> C -> B  的话， 说明栈结构已经是异常了；    出现这个问题的原因也是这个栈顺序异常导致的， 先排查下为何导致栈顺序错乱

**Comment by zs1973** [comment]
我具体看了下我这边写的代码  和demo一致，  这个栈顺序的错乱是有时出现有时正常，错乱的时候居多。

**Comment by zs1973** [comment]
主页是这样的
          |A Fragment      
father|B Fragment           
          |C  Fragment
SupportRequestManagerFragment（Glide里面的）
brotherA 
brotherB   startForResult
brotherC   onFragmentResult
正常为  father->SupportRequestManagerFragment->brotherA->brotherB->brotherC
异常为   father->SupportRequestManagerFragment->brotherA->brotherC->brotherB

**Comment by YoKeyword** [comment]
额，可以栈视图截图吗？  这个描述我看得不是很明白...

**Comment by zs1973** [comment]
方便给个邮箱吗 我给你发个我的安装包  debug模式的

**Comment by YoKeyword** [comment]
留下QQ吧

**Comment by zs1973** [comment]
305562245

**Comment by 112721933** [comment]
我的也是一模一样的情况，请问是怎么解决的？使用的版本是1.1.6 @YoKeyword

**Comment by YoKeyword** [comment]
@112721933  @zs1973 引起该问题的原因是 栈视图顺序异常， 排查下异常原因，然后保证栈内正常即可
