### ISSUE TITLE
pop() to backstack problem in Android Api>22 (Android 6) 

### ISSUE THREAD

**Issue by arashsammak** [YoKeyword/Fragmentation#306]
when i press  pressback button for device or in toolbar, don't work! in android 6. what is problem?

**Comment by YoKeyword** [comment]
Hi. 
NavigationButton? 

Maybe you need to setNavigationOnClickListener for the toolbar.

````java
toolbar.setNavigationOnClickListener( (v) -> { //eg: pop(); } );
````
