### ISSUE TITLE
showHideFragment 建议可加动画

### ISSUE THREAD

**Issue by treycc** [YoKeyword/Fragmentation#308]
比如我要实现网易新闻评论也那种，开始进入就是start，再次进入就是showhide，但是shouhide没有动画，及只能用事务自己添加达到add和show动画是一样的，但是感觉加不加没啥意义，所有事务统一处理可能有点意义。
还有就是swipeback，之前issues也有提过，建议非侵入性的比较好，https://github.com/oubowu/SlideBack
这个方式及有slidr无侵入、配置性高，又不用设置背景透明。

**Comment by YoKeyword** [comment]
1、网易新闻评论的界面，应该是一个带动画的View，并不是Fragment， Fragment设置的动画是针对进栈出栈的场景的，对show/hide无效。 
所以，如果你想实现那种场景的话，用一个View是快捷的方式，毕竟评论那个页面没有什么特殊的生命周期，仅仅是显示和隐藏.

2、swipeback问题，那个issue还是open状态，前段时间稍微看了下，给Fragment添加了视觉差功能；
SlideBack这个库的README提到，存在下面问题：
> 存在问题
旋转屏幕后上一个Activity的布局也会随之旋转，但是ToolBar比例还是维持旋转之前的比例，无从下手
沉浸式状态栏支持有问题
多个滑动页面快速返回有空指针问题，只能等页面取点焦点的时候才能滑动

结合存在的问题，以及鉴于Fragmentation的适用场景是单AC或者多模块AC＋多FG，所以替换实现方式这个优先级可能会往后推。

PS：目前库的短期计划是，提供 'implements'代替'extends'的 核心库， 可以不使用继承的方式实现Fragmentation的功能，降低侵入性。 `SupportFragment`,`SupportActivity`将作为拓展库
这样可以拥有更多灵活性，可以自己集成想要的SlideBack的实现 :)

**Comment by treycc** [comment]
谢谢解答
