### ISSUE TITLE
按返回键返回上一页，为什么不走生命流程了

### ISSUE THREAD

**Issue by lizhaoXXX** [YoKeyword/Fragmentation#309]
我是一个activity+多个fragment，当我从一个Afragment按返回键，返回前一个Bfragment的时候，
Bfragment不走生命流程，数据没有得到刷新，我需要的是数据刷新的。

**Comment by YoKeyword** [comment]
返回时，BFragment执行pop()操作，会回调A的`onHiddenChanged()`方法。

`onResume()`这样的生命周期是跟随宿主Activity的，宿主Activity执行这些生命周期时，其内Fragments会跟随执行。
