### ISSUE TITLE
你好，SwipeBackActivity这个用在我项目里，只有简单的Activity（比如Activity里没有fragment）才可以侧滑退出效果。

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#31]
@YoKeyword 
你好，SwipeBackActivity这个用在我项目里，只有简单的Activity（比如Activity里没有fragment）才可以侧滑退出。
于是我尝试着在你项目里的三个Activity全加上SwipeBackActivity，
同时都加了getSwipeBackLayout().setEdgeOrientation(SwipeBackLayout.EDGE_ALL);
三个Activity也都设置了 <item name="android:windowIsTranslucent">true</item>
只有EnterActivity和flow.MainActivity这两个Activity有侧滑效果，唯独仿知乎的那个Activity没有侧滑退出效果。我的项目也是类似你仿知乎的demo，内嵌很多平级fragment，也没有侧滑退出效果，但是简单的Activity就有侧滑退出效果。我用的系统版本是4.2的真机和系统版本是4.4的模拟器，两者都如上所述。
你有空可以看看是不是有这个问题。
我估计是滑动事件被拦截了还怎么个原因。^_^

**Comment by YoKeyword** [comment]
@leguang 嗯，因为默认的是：Activity内栈内Fragment数 <= 1 时，Activity才会响应滑动事件，所以导致仿知乎Demo滑动会无效（仿知乎demo里栈内初始化时，Activity下的栈内就有4个Fragment，所以滑动无效）

这个地方的设计确实有点问题，我已经push了新的版本；在SwipeBackActivity内增加了boolean swipeBackPriority()方法：
`/**
     * 限制SwipeBack的条件,默认栈内Fragment数 <= 1时 , 优先滑动退出Activity , 而不是Fragment
     *
     * @return true: Activity可以滑动退出, 并且总是优先;  false: Activity不允许滑动退出
     */
    public boolean swipeBackPriority() {
        return getSupportFragmentManager().getBackStackEntryCount() <= 1;
    }`

你可以通过复写该方法，比如在你的需求中，总是需要滑动退出Activity，那么复写该方法，并直接返回ture即可  

感谢你的反馈哈  🙏
