### ISSUE TITLE
有没有人用这个框架加载过融云的的 会话列表 ？

### ISSUE THREAD

**Issue by zs1973** [YoKeyword/Fragmentation#310]
怎么把才能把ConversationListFragment 变成 SupportFragment的子类呢？

**Comment by YoKeyword** [comment]
创建一个继承SupportFragment的ConversationContainerFragment
方法1: xml布局里:
````xml
<fragment 
class:"xxx.ConversationListFragment"/>
````

方法2: 通过getChildFragmentManager将融云的ConversationListFragment 加载add进来

推荐方法1，像View一样加载进来即可。

**Comment by wangbo4020** [comment]
对，这也是个通用的问题，像系统自带的一些Fragment的子类也需要用作者的这个方法。
本来想把SupportFragment复制出来，把它改名为SupportListFragment并且继承ListFragment，但是后来想想这对之后的维护也是麻烦，就没弄了。
后来想了个方法，把SupportFragment里面的代码拿出来做一个类，然后使用组合模式使用，可能好一点点，但是感觉还打不到预想的方便。
所以想作者有没有更好的建议。

**Comment by YoKeyword** [comment]
目前短期打算是用实现 ＋ 委托 代替现在的继承方式，毕竟Java只有一次继承机会， 会把Fragmentation库分成2个库：fragmentation-core, fragmentation。

前者提供 实现＋委托形式 让使用者拼装任意Fragment； 后者是提供默认的SupportFragment,SupportActivity的库

在实现之前，如果想把系统的其他Fragment（比如ListFragment等）转变成SupportFragment，那么建议： 创建继承自SupportFragment的ContainerFragment，将普通Fragment作为其子Fragment，封装下即可

**Comment by wangbo4020** [comment]
懂了，谢谢。
```
public class ContainerFragment<F extends Fragment> extends SupportFragment {

    public ContainerFragment() {
        super();
    }

    public ContainerFragment(F f) {
        super();
        setContentFragment(f);
    }

    public void setContentFragment(F f) {
        getChildFragmentManager().beginTransaction().add(f, "child").commit();
    }
}
```
这样看起来好像可以...
