### ISSUE TITLE
点击事件无效

### ISSUE THREAD

**Issue by Horrarndoo** [YoKeyword/Fragmentation#311]
if (savedInstanceState == null) {
            loadRootFragment(R.id.fl_container, ForgetPasswordFragment.newInstance());
        }
只要加载了RootFragment，Activity和Fragment的点击事件都无效了，这个是什么情况啊

**Comment by YoKeyword** [comment]
@Horrarndoo 用的哪个版本的Fragmentation， 以及哪个版本的support-v4包？

**Comment by Horrarndoo** [comment]
@YoKeyword Fragmentation:0.7.13  support-v4:25.3.0

**Comment by YoKeyword** [comment]
额，support-v4包25.1, 25.2内部机制有些改动，Fragmentation有2个版本对此做了兼容。

升级到最新版0.10.4吧，一些性能优化、解决多点触控等问题， 升级成本很低，不兼容改动应该就2处左右,对照wiki，升级下即可

**Comment by Horrarndoo** [comment]
@YoKeyword 谢谢大神
