### ISSUE TITLE
问下如果登录界面是用fragment的应该怎么切换，比较合理

### ISSUE THREAD

**Issue by zhangle1** [YoKeyword/Fragmentation#312]
问下如果登录界面是用fragment的应该怎么切换，比较合理. 
作者我正在用你的库 很好用哈

**Comment by YoKeyword** [comment]
登录界面是个出现频次较低的页面， 个人建议放到单独的Activity里，多模块Activity是一种更方便管理的方式

如果实在追求单Activity的话，登录界面作为一个Fragment正常控制即可

**Comment by zhangle1** [comment]
了解 多谢
