### ISSUE TITLE
Fragmentation swipeBack

### ISSUE THREAD

**Issue by ldavinciy** [YoKeyword/Fragmentation#313]
在侧滑返回时 点击返回 上一个界面出现一半 
Demo 重现
![2017-05-04 at 1 49](https://cloud.githubusercontent.com/assets/18651043/25691793/a4a91878-30d0-11e7-8194-38cea3e13646.gif)

**Comment by YoKeyword** [comment]
@ldavinciy 是的，确实滑动过程中，点击BACK键会出现这个问题

v0.7.10 给SwipeBackFragment添加滑动视觉差功能造成的BUG，我稍后修复这个问题，感谢反馈 :)

**Comment by YoKeyword** [comment]
@ldavinciy 已修复， 和主库版本号保持一致: v0.10.4

现在一起操作的话，在滑动超过半屏时点击BACK，视觉效果有点瑕疵；
微信的从聊天页面这么操作时，也会出现同样的瑕疵；  结合一般情况下用户几乎不会这么操作，所以可以暂时忽略这个瑕疵 :)

**Comment by ldavinciy** [comment]
66666大神加一,虽然我通过滑动是 屏蔽返回 做出来了,但是会引起其他的连锁问题,这下就不用我自己修改了
