### ISSUE TITLE
实现按两次返回键的效果，即“再按一次退出应用哦”

### ISSUE THREAD

**Issue by xgeeek** [YoKeyword/Fragmentation#314]
我是类似知乎的效果，一个activity。怎么实现，我在主activity重写onkeydown，fragment的返回就监听不到。

**Comment by YoKeyword** [comment]
Demo里有示例写法：  建议使用`onBackPressedSupport()` 代替onkeydown
````java
   @Override
    public void onBackPressedSupport() {
        super.onBackPressedSupport();

    }
````
详细用法见Demo，[wiki](https://github.com/YoKeyword/Fragmentation/wiki/6.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-Back%E9%94%AE%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E6%9C%BA%E5%88%B6)

**Comment by xgeeek** [comment]
兄弟，我是监听返回键（onkeydown）实现按两次返回键才退出应用，我现在该怎么实现这个效果

**Comment by xgeeek** [comment]
好吧，我只看了知乎的代码，没注意其他的两个有这个效果。谢谢。
