### ISSUE TITLE
快速点击两下的时候 只移除一个fragment

### ISSUE THREAD

**Issue by zhangle1** [YoKeyword/Fragmentation#315]
这是为啥...

**Comment by zhangle1** [comment]
if (now < mShareElementDebounceTime) return;
        mShareElementDebounceTime = System.currentTimeMillis() + from.getExitAnimDuration();
 看了下 是这里做了判断，能否提供下支持快速删除

**Comment by YoKeyword** [comment]
库中做了防手抖的处理， 因为Fragment的特殊性，防手抖是需要做的。

如果你的Fragment 都无转场动画，可以去掉这个防手抖处理；  一旦有转场动画的加入，为了稳定性，这个防手抖还是需要的。
````java
@Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        // 防抖动(防止点击速度过快)
        if (!mFragmentClickable) return true; // 移除这句代码，将无防手抖功能

        return super.dispatchTouchEvent(ev);
    }
````
