### ISSUE TITLE
按返回键可以执行动画。FragmentA界面有个按钮，点击时执行poptochild， 这时为什么不执行动画。

### ISSUE THREAD

**Issue by xgeeek** [YoKeyword/Fragmentation#316]

**Comment by YoKeyword** [comment]
`popTo()`,`popToChild()`出栈多个带动画的Fragment时会存在性能问题，以及如果再立即执行事务可能会引起不稳定事务的棘手问题， 所以不执行动画

**Comment by xgeeek** [comment]
能做到不管出栈多少个，只让栈顶的那个带动画嘛，不知道lz能不能实习。

**Comment by YoKeyword** [comment]
肯定是可以做到的，但是这并不能解决我说的第二个问题：

假设这样的场景，栈内[A,B,C,D]， 我想`popTo(B,true)`后立即`start(E)`，如果有动画，此时动画执行中，就E就进栈了，但是此时ABCD并未从栈内完全移除，所以会导致FragmentManager管理Fragment的某些Lis导致异常，栈内顺序错乱的情况；

要保证完全不出错，就需要保证，动画结束后再start，但是视觉上就很怪，所以不考虑这种方式...

 综上如果仅仅是`popTo()`，而不是popTo(xx,xx, start新Fragment)，有动画也无妨，但是并不能保证一定是这种使用场景，所以移除了动画；

其实结合各大单AC多FG的App，大多数确实无动画，由动画的话，也是属于仅仅第一种情况的场景，目前我还没想到两全其美的方式，所以如果很在意，可以fork下，自己在特定场景下，让其带动画；或者使用Activity来曲线实现这个效果
