### ISSUE TITLE
Activity销毁后重启的问题请教

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#318]
在Activity被销毁后在重启，内的多个Fragment会依次恢复，我在Fragment的onEnterAnimationEnd里进行请求数据操作，这样在恢复多个Fragment的时候会导致所有的不可见的Fragment也会重新执行onEnterAnimationEnd，再次请求数据，一下子全部执行了，会不会不太友好，这个您在项目怎么处理的？

**Comment by YoKeyword** [comment]
可以这样处理：
````java
    @Override
    protected void onEnterAnimationEnd(Bundle savedInstanceState) {
        super.onEnterAnimationEnd(savedInstanceState);
        if (savedInstanceState == null) {
            requestDatas();
        }
    }

    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);
        if (savedInstanceState != null) {
            requestDatas();
        }
    }
````

**Comment by hcadoid** [comment]
这样更麻烦吧，会有几个问题吧。1.每个页面的数据都要去保存？ 2.在 onEnterAnimationEnd做了一些监听事件的重启后，如果这样判断，销毁下次会失效。

**Comment by YoKeyword** [comment]
你的需求是 **请求数据**， 代码中也是写的`requestDatas()`...  并不是所有初始化动作都放入其中， 另外一说多模块Activity＋多FG 可以让内存、资源占用更合理

**Comment by hcadoid** [comment]
是的，那请求的数据在每个页面都是要在onSaveInstanceState里保存一份。。。

**Comment by YoKeyword** [comment]
@hcadoid   不用的，被杀死说明：Activity长时间停留在不可见状态，此时数据很可能已经失去实时性了，需要重新请求数据， 所以下次恢复时走了 `onLazyInitView()`里的`requestDatas`，重新请求即可

**Comment by hcadoid** [comment]
哦，好谢谢明白了，是要2个方法结合一起用，刚没看仔细。。还以为onLazyInitView只在ViewPager中才有作用。

**Comment by hcadoid** [comment]
你好，还有个问题，按你说的普通的没问题，但是在frgament中有Viewpager子类fragment，父类fra在requestDatas请求数据，成功后在设置Viewpager的Adapter，子类是onLazyInitView中加载数据的， 重启恢复后，先执行了父类requestDatas，导致子类Fragment的显示空白。

**Comment by YoKeyword** [comment]
重启后，先执行了父类`requestDatas`， 异步拿到结果后再绑定Adapter，此时子Fragment会被重新添加到父FragmentManager中，继而显示；  这个过程有问题？

**Comment by hcadoid** [comment]
viewpager下的fragment显示空白了。
1.FragmentA(viewpager下FragmentA_a)-->start FragmentB 。如果Activity销毁重启。返回， 会先执行FragmentA_a的下onLazyInitView，在执行FragmentA下的requestDatas。 可以显示正常，但FragmentA下的menu不显示了（正在查找原因）
2,.FragmentA(viewpager下FragmentA_a)   当前页面Activity销毁  重启后，会先执行FragmentA的requestDatas，后执行FragmentA_a的onLazyInitView()。完了后FragmentA_a显示空白了。FragmentA下的menu显示正常。

**Comment by YoKeyword** [comment]
@hcadoid 我模拟了下2种场景，均正常，你再调试下，看看什么问题吧
