### ISSUE TITLE
CrashHandler: java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by bowei1995621** [YoKeyword/Fragmentation#322]
在装有WebView的Fragment页面，home建退至主屏后，直接报这个错误

**Comment by YoKeyword** [comment]
栈溢出了...，  检查下可疑的方法吧

**Comment by bowei1995621** [comment]
版本是0.10.x 错误提示在
fragmentaction.helper.internal包下的ResultRecord类中

@Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(requestCode);
        dest.writeInt(resultCode);
//        dest.writeBundle(resultBundle);  
//上一行出错，注释掉就好了，但是这样好像又没办法获取一些数据了
    }

可能是我这边某些地方有问题，我再找找看
