### ISSUE TITLE
子fragement如何隐藏底部导航栏

### ISSUE THREAD

**Issue by ydBen** [YoKeyword/Fragmentation#325]
attachToSwipeBack(view)和这个方法有关系吗   但是这个方法导入lib之后也无法引用   希望尽快得到您的帮助

**Comment by reader102207487** [comment]
..

**Comment by YoKeyword** [comment]
没关系；

Demo中底部导航栏是BottomBar，一种方式是控制BottomBar的显示和隐藏，BttomBar有`show`/`hide`方法（可能有些问题，需要自己调整下）

或者你想要的是WeChat_demo的栈设计，只有主页显示BottomBar
