### ISSUE TITLE
遇见Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by qinyang1018** [YoKeyword/Fragmentation#326]
![image](https://cloud.githubusercontent.com/assets/15726024/26022907/863fe0c8-37e3-11e7-9795-b130f77eabde.png)

![image](https://cloud.githubusercontent.com/assets/15726024/26022912/96aaac5e-37e3-11e7-914b-74b55339ad40.png)

目前遇见的问题，不是每个手机都有此情况   目前发现出现在下面这台机器上
![image](https://cloud.githubusercontent.com/assets/15726024/26022921/b21bc77a-37e3-11e7-9252-c6a73b66945e.png)
代码中执行了pop()方法

**Comment by YoKeyword** [comment]
见 #317  , 详细可看[这篇文章](http://www.jianshu.com/p/d9143a92ad94)
