### ISSUE TITLE
2、SupportActivity提供registerFragmentLifecycleCallbacks()来监控其下所有Fragment的生命周期；

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#328]
麻烦问一下，这个registerFragmentLifecycleCallbacks()方法在哪儿里？我在SupportActivity里没找到，这个如何使用？现在恰好有一个场景需要。谢谢。

**Comment by YoKeyword** [comment]
@leguang  从0.8开始，SupportActivity有这个方法的，直接调用即可，建议用最新版本；
可见Demo中3个MainActivity，都有示例～

**Comment by YoKeyword** [comment]
其实官方从25.0开始，对FragmentManager也提供了相同作用的方法，作用域是FM对应的栈层级；
库中register方法兼容所有support-v4版本，并且是对Activity下所有Fragment的监听

**Comment by xiaobailong24** [comment]
@YoKeyword 您好，看了官方的FragmentManager的registerFragmentLifecycleCallbacks() 和 unregisterFragmentLifecycleCallbacks() 方法，其中注释有一句是：**All registered callbacks will be automatically unregistered when this FragmentManager is destroyed.** 
请问 callbacks 是否真的会被自动注销？我测试当 **FragmentManager.isDestroyed(0 == true** 并没有t调到 unregisterFragmentLifecycleCallbacks 方法里。
求解，感谢！

**Comment by YoKeyword** [comment]
@xiaobailong24 FragmentLifecycleCallbacks是FragmentManager的一个普通对象， 在FM销毁时，callbacks也会被销毁， 即unregister

@leguang 另外，因为官方v4从25.1+开始新增 FragmentLifecycleCallbacks方法，所以Fragmentation库在下个大版本会移除库内的FragmentLifecycleCallbacks  :)

**Comment by xiaobailong24** [comment]
@YoKeyword 但是源码里registerFragmentLifecycleCallbacks()是将 FragmentLifecycleCallbacks 加入 mLifecycleCallbacks 集合； unregisterFragmentLifecycleCallbacks() 将 FragmentLifecycleCallbacks 移除 mLifecycleCallbacks 集合。如果只registerFragmentLifecycleCallbacks 而不  unregisterFragmentLifecycleCallbacks ，当Activity销毁时会不会有 内存泄漏的风险？

**Comment by YoKeyword** [comment]
这个不用担心的，mLifecycleCallbacks是个List，是FM内的一个变量，没有生命周期的概念，所以当FM销毁，mLifecycleCallbacks的引用、对象都会被销毁的

**Comment by xiaobailong24** [comment]
@YoKeyword 非常感谢！
