### ISSUE TITLE
这样的界面用您的项目该如何实现

### ISSUE THREAD

**Issue by stoneLee81** [YoKeyword/Fragmentation#329]
是否可以提供一个思路，VIEWPAGE里包含recycleview和map，点击上面的ICON，可以让VIEWPAGER让LIST和地图切换
![1](https://cloud.githubusercontent.com/assets/18001708/26059721/5459548a-39b5-11e7-889f-1652df2cabea.jpg)
![2](https://cloud.githubusercontent.com/assets/18001708/26059722/55adaa70-39b5-11e7-8d54-599c363a8a2b.jpg)

**Comment by YoKeyword** [comment]
假定：ViewPager的所在父Fragment为A，FARTHER AWAY对应的Fragment为B， RecyclerView所在的Fragment为C，Map所在Fragment为D

A内有B，C和D是B的孩子Fragment， 切换RecyclerView和Map等同于切换C和D

**Comment by stoneLee81** [comment]
不太明白，你意思是用replace，还是hide?

**Comment by stoneLee81** [comment]
知道如何处理了，谢谢
