### ISSUE TITLE
关于项目上传到jcenter的一些问题

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#33]
您好，您的项目我也有在使用，我想问一个非项目相关的问题，最近我在为把自己的项目上传到jcenter发愁，我看到您项目中也包含了javadoc注释，并且已经上传到jcenter了。有几个问题想请教一下您：
1. 在项目中包含注释在生成javadoc这个task中失败该如何解决，我查了一下资料说是java8的问题。
2. 如果在项目中有android.support.v4这个包，运行bintrayUpload也会报错，找不到一些support的类。
3. 还有些时候会出现build/poms/pom-default.xml (没有那个文件或目录)这种错误。
打扰了，谢谢

**Comment by YoKeyword** [comment]
@weiyf 我是使用的https://github.com/novoda/bintray-release 这个库；让你可以很方便上传到Jcenter，有问题基本都可以从它的issues找到答案

另外还可以使用jitpack，这个可以让你非常非常简单快速的发布  :)  
希望能帮到你 :)
