### ISSUE TITLE
Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.

### ISSUE THREAD

**Issue by lizhaoXXX** [YoKeyword/Fragmentation#330]
我在使用这个的过程中，老是出现这样的警告。请问我该怎样排查，谢谢。

问题：
I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
W/art: Suspending all threads took: 133.087ms
W/art: Suspending all threads took: 9.704ms
W/art: Suspending all threads took: 30.303ms

描述：
我在Application中，只是使用了Litepal和Fragmentation，然后在运行项目的时候就出现上面的问题。
所以，在初始化Fragmentation的时候，需不需要开启一个子线程。
谢谢。

**Comment by YoKeyword** [comment]
Fragmentation是一个轻量库，初始化速度可以忽略，不用担心

你的这个问题，是在主线程执行了较耗时的操作，可以排查下出现该Log时的相关代码
