### ISSUE TITLE
Please beginTransaction in onPostResume() after the Activity returns!

### ISSUE THREAD

**Issue by guangshao** [YoKeyword/Fragmentation#331]
你好:
       我这边的触发场景是在 app启动后,切换除去, 再从QQ的应用宝下载网页打开APP , 这个时候APP在start() 报这样的错误 , 有什么解决办法吗??

**Comment by YoKeyword** [comment]
见 #317 , 详细可看[这篇文章](http://www.jianshu.com/p/d9143a92ad94)

**Comment by guangshao** [comment]
谢谢   @YoKeyword
