### ISSUE TITLE
父fragment没有正常分发可见性给子fragment

### ISSUE THREAD

**Issue by yuanrunmao** [YoKeyword/Fragmentation#332]
ViewPager和Fragment配合使用，每一个Fragment页面又由若干个子fragment组成。

现象：当ViewPager一页接着一页切换时，父Fragment能正常将其可见性分发给子fragment。但是如果通过setCurrentItem(int) 跳页切换时，新的页面可见了却没有通知到其子framgent。比如目前处于第1页，指定切换到第3页，第一页不可见的状态能正常分发，而第3页可见了，其子framgent却没有收到可见的回调。

调试了一下代码，看到 mSupportFragment.isResumed() 的判断，fragment的mState为CREATED，所以没跑进去。

![fragmentation](https://cloud.githubusercontent.com/assets/8710607/26095571/aca7fe5c-3a50-11e7-85f5-484160a0d6ca.PNG)

**Comment by YoKeyword** [comment]
感谢反馈，我稍后看下 :)

**Comment by YoKeyword** [comment]
已Fix  :)
