### ISSUE TITLE
优化体验

### ISSUE THREAD

**Issue by xsslong** [YoKeyword/Fragmentation#333]
<item name="android:windowIsTranslucent">true</item>这个设置再某些手机上体验不是很好, 会出现底下的界面先透明, 在出现的现象, 希望以后能优化

**Comment by YoKeyword** [comment]
> true这个设置再某些手机上体验不是很好

这个true指的是什么呢？

**Comment by xsslong** [comment]
使用SwipeBack 滑动边缘退出, 在Activity的theme添加窗口透明设置为true时, 在滑动边缘退出时, 会先看到桌面(底层Activity变得透明透明), 再看到底层Activity的界面, 这都感觉很怪

**Comment by YoKeyword** [comment]
见[这条issue](https://github.com/YoKeyword/SwipeBackFragment/issues/6)

**Comment by xsslong** [comment]
解决了 用您提供方式解决了, 太感谢了
