### ISSUE TITLE
有碰到在fragment中startActivityForResult,但没有回调onActivityResult

### ISSUE THREAD

**Issue by luXiuKun** [YoKeyword/Fragmentation#335]
startActivityForResult(new Intent(getActivity(),SelectCityAct.class),0x001);

 SelectCityAct.this.setResult(RESULT_OK,intent);
SelectCityAct.this.finish();

没感觉有什么问题啊

**Comment by YoKeyword** [comment]
如果你是在Fragment中直接`startActivityForResult ()`，那么会回调你Fragment内的`onActivityResult ()`；

如果是`mActivity.startActivityForResult ()`，那么会回调Activity内的`onActivityResult ()`

**Comment by luXiuKun** [comment]
我是在fragment中，就是没回调 fragment中的 onActivityResult;

 @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        LogUtil.e(TAG,"onActivityResult");
    }

**Comment by YoKeyword** [comment]
在挺老版本的support-v4中，这种情况不会回调，但是很早Google就修复该BUG了；
你再检查下代码...

**Comment by luXiuKun** [comment]
找到了，mainavtivity里的super.onactivityresult()不小心删了
