### ISSUE TITLE
Fragment切换背景颜色的问题

### ISSUE THREAD

**Issue by Wade-Cai** [YoKeyword/Fragmentation#336]
比如我用竖向的转场动画转场的话，我默认背景是使用Theme的android:windowbackground（比如我用略灰）作为背景,这样切换的话会有一层灰色突兀效果，如果我设置全局背景和Toolbar一样的颜色，那么竖向转场动画是解决了，横向动画就会出现我设置的颜色，请问有解决办法吗？谢谢

**Comment by YoKeyword** [comment]
灰色突兀，这个不是很理解；

库中提供的竖向专场动画是带有Alpha变化的，是这个变化让你的转场在视觉上突兀？
如果是这样的话，可以自定义动画。
