### ISSUE TITLE
SwipeBackFragment

### ISSUE THREAD

**Issue by ydBen** [YoKeyword/Fragmentation#339]
直接拷贝Wechat部分  SwipeBackFragment无法引入 如何引入SwipeBackFragment

**Comment by YoKeyword** [comment]
// 如果想使用SwipeBack 滑动边缘退出Fragment/Activity功能，请再添加下面的库
compile 'me.yokeyword:fragmentation-swipeback:0.10.4'

**Comment by ydBen** [comment]
好的   谢谢~
