### ISSUE TITLE
跳转问题

### ISSUE THREAD

**Issue by feng0403** [YoKeyword/Fragmentation#34]
![2016-07-01 16 59 22](https://cloud.githubusercontent.com/assets/6883475/16516899/42d0c624-3fad-11e6-82f3-cab5a20a7ad4.jpg)

请问有没有什么办法  从一个Dialog直接跳转到CycleFragment
无论这个dialog是在应用的哪个界面弹出来的
谢谢

**Comment by YoKeyword** [comment]
@feng0403 你的需求是：不管在哪个Fragment，你都想直接跳转到目标Fragment是吗？ 
2种情况：
1、当前Fragment和目标在同一个栈层级下，使用SingleTask可以跳转到目标Fragment，不过该目标Fragment所处的栈之上的Fragment会被出栈

2、 如果是不同栈层级.... 还是建议重新加载一个目标Fragment吧...

最后，你的需求有些奇怪，如果你的情况是第2种，建议重新思考下如何规划栈层级关系，避免这种设计  :)

**Comment by feng0403** [comment]
我的需求是这样的： 收到一个服务器推送的通知，弹出一个Dialog，点击后跳转到某个Fragment。
这个Fragment所处层级，类似上图的CycleFragment

**Comment by YoKeyword** [comment]
@feng0403  这样啊，那你需要判断下
比如启动上述的CycleFragment，你首先是先切到MultiThirdFragment这里，然后通过它的getChildTopFragment.start(CycleFragment,SingleTask) 这样就到了CycleFragment

总体思路就是：先到目标Fragment的父Fragment，再通过getChild相关操作找到目标同级的Fragment，然后再通过start跳转   :)
