### ISSUE TITLE
fragment跳转动画 Fresco的影响？

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#341]
在Fragment跳转，在有跳转动画时，用Fresco加载图片的页面，对图片有短暂的不显示，

![qq 20170523153308](https://cloud.githubusercontent.com/assets/10434110/26342992/db7d9986-3fcc-11e7-9376-f29c6d5b5c43.png)

**Comment by hcadoid** [comment]
之前Activity中用Fresco对5.0共享元素动画也支持不好，是不是用Fresco对跳转动画处理要独立去兼容。

**Comment by YoKeyword** [comment]
fresco的问题，我回头看看；

曲线解决的方式：跳转动画设置为竖向动画...

**Comment by hcadoid** [comment]
好的，竖向应该也是一样的，我看知乎用的也是Fresco,他们不知道有没有解决，但是他们把进场动画设置的很短，基本上没有，眨眼功夫看不出来。

**Comment by YoKeyword** [comment]
应该是离场动画会导致不显示， 进场动画没影响的， 所以竖向动画从感官上看不出这个问题...

知乎没有离场动画，只有一些页面有进场动画，所以没这个问题

**Comment by hcadoid** [comment]
这个问题的原因是什么？ 今天我给fresco提了个issue，希望他们也看看，  我发现只有在7.0的手机上会出现。  用Glide正常 。  但是我如果不用你的框架，只是简单的setCustomAnimations动画也是没有问题的。

 FragmentTransaction transaction =  getFragmentManager().beginTransaction();
                transaction.setCustomAnimations(
                        R.anim.h_fragment_enter,
                        R.anim.h_fragment_exit,
                        R.anim.h_fragment_pop_enter,
                        R.anim.h_fragment_pop_exit
                );
                transaction.add(R.id.fl_container, OtherFragment.newInstance());
                transaction.addToBackStack(null);
                transaction.commit();

**Comment by YoKeyword** [comment]
确实7.0+ 在动画过程中图片会先被释放导致空白， 暂时先看Fresco的解决方案了

另外 我测试7.0＋ 不使用Fragmentation，使用`setCustomAnimations `，也是依旧空白

**Comment by andlike** [comment]
有解决方案了吗

**Comment by ffyliu** [comment]
有解决方案了吗？
