### ISSUE TITLE
fragment跳转问题

### ISSUE THREAD

**Issue by Horrarndoo** [YoKeyword/Fragmentation#342]
假设现在有ABC三个fragment，A通过start到B的时候，A的onSupportVisible()会执行一次，这里是正常的。然后B通过startWithPop到C的时候，A的onSupportInvisible()和onSupportVisible()都会执行一次，这就有点不正常了，因为现在是B pop到C，A应该还是不可见状态才对吧？请问有什么方法解决这个问题吗？

**Comment by YoKeyword** [comment]
`startWithPop ()`是个特殊的方法，因为FragmentManager内部管理的是一个非常严格的栈。

所以库内部的实现为：  先｀pop()｀ ， 再｀start()`， 这就是为何B`startWithPop(C)`时A会被回调｀`onSupportVisible()`和`onSupportInvisible()`的原因。

目前我还没找到特别好的解决方式，毕竟其内部是个非常严格的栈，如果你一定需要解决，可以：
B `start(C)`， 在C回退时： C `popTo(A,false)/popTo(B,true)`  ，  即用`start`代替`startWithPop`，在C出栈时直接出栈到A来曲线解决  ：）

**Comment by YoKeyword** [comment]
@Horrarndoo [这个issue](https://github.com/YoKeyword/Fragmentation/issues/407#issuecomment-313283807)里提供了解决方案

**Comment by Horrarndoo** [comment]
@YoKeyword 额不好意思，之前忘记回复了，我也是采取您推荐的方法处理的
