### ISSUE TITLE
java.lang.ClassCastException: android.support.transition.Fade cannot be cast to android.transition.Transition

### ISSUE THREAD

**Issue by NAH4E5553** [YoKeyword/Fragmentation#343]
知乎日报demo 中由FirstHomeFragment  跳到FirstDetailFragment 在6.0、7.0机子中闪退

**Comment by YoKeyword** [comment]
Fade这个类你使用了`android.support.transition`下的了， 改用`android.transition`包下的即可

**Comment by NAH4E5553** [comment]
受教了，多谢

**Comment by islamelhady** [comment]
This issue has been fixed in the upcoming Fragment 1.2.0-beta01 release.
