### ISSUE TITLE
Fragment 切换问题

### ISSUE THREAD

**Issue by bleedyao** [YoKeyword/Fragmentation#344]
同样使用 startWithPop 方法切换 Fragment，Demo 中可以流畅的切换，我的却是前一个 Fragment 先销毁，后一个 Fragment 再进来，会出现切换的时候标题栏显示背景颜色，请问这个怎么解决。
注：start 效果一样。

**Comment by YoKeyword** [comment]
> startWithPop内部实现是这样的，假设A startWithPop B， A先出栈，B再进栈，如果你不进行任何处理A和B的出栈和进栈动画显示是不正常的（你可以自己实现下看看），之所以动画看起来正常是因为A之前的那个FG会暂时显示A的界面，整个动画结束后，会复原，这样就达到一个很正常的start并且关闭当前FG的动画效果

你的场景中 调用`startWithPop()`的Fragment 之前是否还存在另一个Fragment？

**Comment by bleedyao** [comment]
我测试了，之前有 start 开启的 fragment，之后再调用 startWithPop 显示动画就基本正常了。

**Comment by YoKeyword** [comment]
`startWithPop ()`是一个妥协的方法，鉴于Fragment的管理是非常严格的栈， 所以很难完全实现类似Activity的`startActivity() + finish()`的效果

可以换一种实现方式： `A.startWithPop(B) `替换为`A.start(B)`，然后记录一个flag，在下次回到B并回退时，`pop()`替换为`popTo(A.class,true)`，即可。  我也在考虑是否把库中的这个实现替换为该方式 :)

**Comment by YoKeyword** [comment]
下个大版本更换了动画兼容机制，`startWithPop()` `popTo()` 都可以正常显示、定制动画了， 可以关注下，其他特性完成后会升个大版本  :)
