### ISSUE TITLE
同时点两个按钮同时跳转（切换）两个不同fragment的问题

### ISSUE THREAD

**Issue by wdeo3601** [YoKeyword/Fragmentation#345]
app里有4个主fragment，依附在Mainactivity（A、B、C、D）。4个主 Fragment由底部的bottomBar来控制切换

现在 fragmentD 中 有一个按钮点击，跳转到 fragmentE（E是fragmentD中的子fragment，当 E 可见时，bottomBar 要隐藏掉）。

我点击 fragmentD 中的按钮跳转到 fragmentE 的同时，点击底部 bottomBar切换到 fragmentA。此时就出现问题了，bottomBar的显示隐藏出现异常

    情况一：跳转到 E ，比 切换到 A 快
        此时页面显示 A ，但切换到 D 页面时，显示的是 E 页面，而此时 bottomBar 是显示状态。
    情况二：切换到 A ，比 跳转到 E 快
        此时页面显示 A ，bottomBar 没有显示。

能不能做一个限制之类的，比如当同时提交事务的间隔在500ms之内时，就丢弃掉一个事务？

**Comment by wdeo3601** [comment]
onSupportVisible() 这个方法，我的处理显示隐藏bpttpmBar的逻辑是放在这个方法里的，这个方法并不可靠。

 我测试的由 FragmentD 同时点击两个按钮跳转到不需要 bottomBar 的FragmentE、F ，此时 E、F 的
onSupportVisible() 执行了，现在点返回键从 F 返回到 E 页面，而此时 D 的 onSupportVisible() 执行了，这是不和逻辑的，此时显示的是 E页面

**Comment by YoKeyword** [comment]
@wdeo3601 
我刚看了下，发现多点触控下，是官方Fragment的`onHiddenChanged()`的回调异常导致`onSupportVisible()`被调用， 在你描述的场景下，从F返回到E时，D回调了`onHiddenChanged(false)`....

事务500ms限制是不可行的，因为有时我们确实需要连续执行事务，其实有一种简单的处理方式：
在application或activity引用的Theme加入以下属性 ：
`<item name="android:splitMotionEvents">false</item>`

**Comment by wdeo3601** [comment]
@YoKeyword 谢谢，豁然开朗。。 我的路还很长啊
