### ISSUE TITLE
共享元素过渡动画的问题

### ISSUE THREAD

**Issue by pye52** [YoKeyword/Fragmentation#346]
目前在两个项目上用fragmentation都遇到一个问题
不论是从supportactivity还是supportfragment，共享元素的过渡动画都会变得很奇怪
动画只播放了一小段，界面就完全呈现出来了

**Comment by YoKeyword** [comment]
共享元素的动画慎用， 官方`add()`上的共享元素在最近的每个v4版本表现都不同， 建议不使用。

如果非要使用的话，建议考虑把需要动画的Fragment放到SupportFragment里（即作为子Fragment），在子栈内直接使用`FragmentManager.beginTransaction().replace().addSharedElement()`方式正常使用Fragment即可

**Comment by pye52** [comment]
明白，非常感谢~:smile:
