### ISSUE TITLE
怎么动态改变bottombar的切换

### ISSUE THREAD

**Issue by isqing** [YoKeyword/Fragmentation#348]
我的mainFragment下建了4个fragment，当我的第四个fragment有个值变化时，第一个fragment要替换成其他的fragment，当4个fragment切换时调的mainFragment的生命周期是什么

**Comment by YoKeyword** [comment]
4个子Fragment是Tab的吗？  如果是的话，子Fragment的切换时，不会触发父Fragment的生命周期

Tab同级的情况下，第4个变化时，如果想让第1个替换掉，给Fragment1 一个容器FragmentC，1作为C的子Fragment(`C.replaceLoadRootFragment(containerId,1,false)`)，需要替换时，`C.replaceLoadRootFragment(containerId,target,false)`

**Comment by isqing** [comment]
解决了，非常感谢
