### ISSUE TITLE
微信的 底部fragment 好像可以左右滑动额 

### ISSUE THREAD

**Issue by slyang520** [YoKeyword/Fragmentation#35]
微信的 底部fragment 好像可以左右滑动额

**Comment by YoKeyword** [comment]
@slyang520 是的 微信是使用ViewPager，更简单。  我的Demo里没使用，因为第二个tab里是个ViewPager，滑动会冲突，主要是为了演示比微信更复杂的情况，所以用了demo那种设计 :)
