### ISSUE TITLE
FragmentAnimator 不支持 ObjectAnimator 吗

### ISSUE THREAD

**Issue by xiaoGuy** [YoKeyword/Fragmentation#351]
new FragmentAnimator() 的时候使用的是 R.animator.xxx 资源
运行的时候异常：
>java.lang.RuntimeException: Unknown animation name: objectAnimation

**Comment by YoKeyword** [comment]
不支持，原因是v4包的Fragment的动画不支持...   app包内的Fragment是支持的，但是因为不同安卓版本特性不同，所以我们一般使用v4包的Fragment
