### ISSUE TITLE
模块类似微信，MainFragment中的foursfragment，点击foursfragment中的一个按钮进入Loginfragment,  然后登录之后返回到Main fragment,怎样重新让Main fragment CreateView,然后更改底部导航栏的内容 

### ISSUE THREAD

**Issue by cccccs** [YoKeyword/Fragmentation#352]

**Comment by cccccs** [comment]
同时想问一下start()方法的机制，我log的时候发现foursfragment进入loginfragment不会调用onPause等方法，只会回调onsupportinvisible方法,想知道一下实现机制    
当然感觉如果login使用Activity应该会简单一些

**Comment by YoKeyword** [comment]
`start()`方法的机制是 `add()` + `show(),hide()`， 所以会回调`onHiddenChanged()`方法,`onSupportVisible()`方法是当Fragment对用户可见/不可见时触发

如果MainFragment的UI登录前后改变很大，考虑用2个Fragment来相互替换。
如果仅仅更改UI，你可以在MainFragment拿到回调时，替换对应UI即可

Login建议使用Activity来实现，因为Login是个功能独立的模块，Activity更好。

**Comment by cccccs** [comment]
谢谢 请问mainfragment里是怎样获得回调   我的foursfragment 启动loginfragment是按照你的demo foursfragment继承OnLoginSuccessListener 然后可以更改foursfragment中账号显示信息 但是现在我是想更改mainfragment底部导航栏的内容请问改该如何回调？
我看你另一个页面fragmentA startForResult 到fragmentB 然后更改了A的toolbar内容 但是现在点击事件是在mainfragment 中的foursfragment 而并不是mainfragment中 这样感觉也不能用你那种方法更改mainfragment中的UI了

**Comment by YoKeyword** [comment]
如果是MainFragment和LoginFragment是同级的， 那么`startForResult()`启动的方式可以在LoginFragment中`setFragmentResult()`， 而后在MainFragment的`onFragmentResult()`里接收到回调

具体可以参考Demo的DetailFragment , ModifyDetailFragment

**Comment by cccccs** [comment]
谢谢 不过如果我在foursfragment中直接使用startfragment的话，foursfragment就会和loginfragment同级 又因为mainfragment是foursfragment的父级 所以mainfragment就不能使用onfragmentresult了 
最后我模仿你的startbrotherevent的写法 又写了一个startbrotherresevent事件 然后foursfragment中的点击事件使用eventbus使mainfragment启动loginfragment 然后这样的话mainfragment和loginfragment就同级了然后就可以改变底边栏了
   有种自己站在巨人的肩上的感觉 希望早日能实现滑动隐藏bottombar的功能 今日也把其它开源的底边栏换成了你源码中的那个 简单并且容易根据需求改写  再次感谢

**Comment by cccccs** [comment]
上边有两个地方说的不太详细
谢谢 不过如果我在foursfragment中直接使用startforresult的话，foursfragment就会和loginfragment同级 又因为mainfragment是foursfragment的父级 所以mainfragment就不能使用onfragmentresult了
最后我模仿你的startbrotherevent的写法 又写了一个startbrotherresevent事件 然后foursfragment中的点击事件使用eventbus 使mainfragment以startforresult的方式启动loginfragment 然后这样的话mainfragment和loginfragment就同级了然后就可以改变底边栏了  有种自己站在巨人的肩上的感觉 
希望早日能实现滑动隐藏bottombar的功能 今日也把其它开源的底边栏换成了你源码中的那个 简单并且容易根据需求改写 再次感谢
