### ISSUE TITLE
如果想把项目转成kotlin开发，还能使用你的这个库么？

### ISSUE THREAD

**Issue by zhzhh7378** [YoKeyword/Fragmentation#353]

**Comment by YoKeyword** [comment]
kotlin和Java可以很宽松的混编， 不影响的

**Comment by gejw0623** [comment]
完全没问题，我现在就是用kotlin开发的

**Comment by yangyiRunning** [comment]
@zhzhh7378   

Java Kolin 互转， https://github.com/MindorksOpenSource/from-java-to-kotlin/blob/master/README-ZH.md

不用谢我叫雷锋

**Comment by yangyiRunning** [comment]
@zhzhh7378

Java Kotlin 互转， https://github.com/MindorksOpenSource/from-java-to-kotlin/blob/master/README-ZH.md

不用谢我叫雷锋
