### ISSUE TITLE
建议：必须继承SupportActivity，SupportFragment？

### ISSUE THREAD

**Issue by DesignQu** [YoKeyword/Fragmentation#354]
这个地方是否可改成接口形式的，解决Java单继承问题，因为一般APP会会有自己的框架部分，我不能更改底层框架

**Comment by YoKeyword** [comment]
这个在下个大版本的任务列表中，目前正在抽离，抽离完成后@下你     ：）

**Comment by wfxphoebus** [comment]
楼主，有没有时间计划？

**Comment by YoKeyword** [comment]
@wfxphoebus 尽量这周 :)

**Comment by weiyf** [comment]
坐等大版本更新。😬

**Comment by YoKeyword** [comment]
@DesignQu @weiyf @wfxphoebus  
1.0.0已放出，可以通过`implements ISupportActivity/Fragment` ＋ `Delegate`形式自己实现`自定义SupportActivity/Fragment`

可以参考Fragmentation中的`SupportActivity/Fragment`中的实现方式  🍺  :)

**Comment by DesignQu** [comment]
谢谢，太好了
