### ISSUE TITLE
侧滑返回问题  

### ISSUE THREAD

**Issue by Mr-PolarBear** [YoKeyword/Fragmentation#355]
大佬你好, 我在使用你的项目的时候 发现当快速打开2个页面 并且快速侧滑结束这个2个页面  多次之后 程序就卡住了  我以为自己写法有问题  
 看了下大佬的demo也有这个问题  在仿微信页面 发现  点击item再点击 红色按钮   然后快速侧滑关闭2个页面 然后就卡住了  查看栈视图   Item详情的fragment还在    
是因为侧滑太快 ,没能2个fragment都结束?
请教有解决办法吗?

**Comment by YoKeyword** [comment]
用的哪个版本的库？ 

> 点击item再点击 红色按钮

这个红色按钮是啥？

**Comment by Mr-PolarBear** [comment]
你好  说错了 是蓝色按钮     
这个在任何能连续侧滑2次的地方都会出现  快速侧滑  2次 就卡住了  然后点击返回实体键  会回复正常

**Comment by YoKeyword** [comment]
用的哪个版本的库？

**Comment by Mr-PolarBear** [comment]
0.10.5

**Comment by YoKeyword** [comment]
感谢反馈 🙏

原因是pop()内部有个防抖动机制，是为了解决ShareElements共享动画情况下，连续返回导致显示异常的BUG，连续快速返回时，可能某次返回无效引起的。
````java
private void debouncePop(SupportFragment from, FragmentManager fragmentManager) {
        ...
        long now = System.currentTimeMillis();
        if (now < mShareElementDebounceTime) return; // 原因在这里
        mShareElementDebounceTime = System.currentTimeMillis() + from.getExitAnimDuration();
        ...
    }
````

稍后我会Fix该问题  :)

**Comment by Mr-PolarBear** [comment]
Good

**Comment by YoKeyword** [comment]
已Fix, 0.10.7    :)
