### ISSUE TITLE
继承supportActivity后，界面上部分被actionbar遮住一部分是怎么回事？

### ISSUE THREAD

**Issue by jiahongyu0529** [YoKeyword/Fragmentation#356]
原来的baseactivity继承的是appcompatactivity，后来改成supportActivity之后，原来正常的fragment界面整体被actionbar遮住了一部分，这是怎么回事？

**Comment by YoKeyword** [comment]
`SwipeBackActivity/Fragment`会给布局加一个SwipeLayout，但是`SupportActivity, SupportFragment `没有对布局做什么处理

被ActionBar遮挡，说明布局在ActionBar下面，可以尝试调用`setSupportActionBar()`解决
