### ISSUE TITLE
多次loadRootFragment

### ISSUE THREAD

**Issue by zhangchaojiong** [YoKeyword/Fragmentation#357]
我想清空栈，然后重新 loadRootFragment一个新的Fragment 作为根Fragment。 

那么我直接调用  loadRootFragment(R.id.fl_container, MainFragment.newInstance()); 
在 R.id.fl_container 之前已经加载的Fragment 是否会自动出栈？

**Comment by YoKeyword** [comment]
不会的，需要将它们出栈并push一个新的Fragment即可：
 `popTo(RootFragment.class, true, new Runnable(){ ()-> loadRootFragment(NewRootFragment) })` 即可

**Comment by zhangchaojiong** [comment]
`popTo(RootFragment.class, true, new Runnable(){ ()-> loadRootFragment(NewRootFragment) })`
根据上面这一条代码，是出栈到`RootFragment`（`RootFragment`还在栈内）
这时候调用`loadRootFragment(NewRootFragment)`会重新加载根fragment。那么`RootFragment`是否还存在？还是被`NewRootFragment`覆盖了?

**Comment by YoKeyword** [comment]
`popTo(rootFragment,boolean)`的第二个boolean参数，代表是否连同第一个参数rootFragment一起出栈：
ture: 代表 rootFragment也出栈， false: rootFragment之上的Fragment都出栈，不包括rootFragment

**Comment by zhangchaojiong** [comment]
> OK 知道了，3Q。

**Comment by zhangchaojiong** [comment]
> boolean includeSelf 这一个参数的名字，我以为是包括自身出栈。
>  我觉得改成boolean  includeTarget 合适一点。 啊哈哈

**Comment by YoKeyword** [comment]
啊哈哈，你应该用的旧版本，新版本：`popTo(Class<?> targetFragmentClass, boolean includeTargetFragment)`

建议用新版 :)

**Comment by zhangchaojiong** [comment]
> 好的！
