### ISSUE TITLE
使用fragmentation做复杂app时，出来嵌套过深的问题

### ISSUE THREAD

**Issue by GongZiZhang** [YoKeyword/Fragmentation#358]
由于fragment的层层嵌套，导致就算底层的view布局只有一层嵌套，但从整体的界面上来看，却是已经嵌套了多层，这样在有些复杂布局上，很容易出现性能卡顿问题

**Comment by YoKeyword** [comment]
其实不用特别担心， 嵌套过深带来的问题是，遍历绘制的时间增加，但是，前提是其内布局是Visible状态，如果是GONE状态，基本是可以忽略的。

而我们启动新的Fragment时，会把上一个Fragment hide，即GONE，所以看起来我们是在一个FrameLayou里一直add Fragment，但是其绘制并不会产生卡顿， 可以使用Demo循环启动CycleFragment来试验。

另外，虽然性能的影响并不大，但是，我们在设计栈结构时，还是尽量能科学合理，减少层级，便于开发维护， 其实一般来说，你会发现你的App基本都是1－3层的， 这样的嵌套层级并不算深   :)

**Comment by wogenhaosini** [comment]
其实还是有影响的 

下图是不使用Fragmentation过度绘制分析

![dbdf2b20-c0db-4064-ab41-1ab178971f0d](https://user-images.githubusercontent.com/10138880/27224725-4afc78ae-52c9-11e7-8a40-f22bbbaeff7a.png)

下图是我使用Fragmentation过度绘制分析

![Uploading 1FE03077-CCBD-4D89-82F7-DBFF1C5B3FC7.png…]()

区别很大。

**Comment by YoKeyword** [comment]
会多一层， 是为了保证动画视觉上正常，如果Fragment没有动画，则可以根布局设定为透明，这样就不会多绘制这一层。

Fragment上的图片控制建议Fresco

**Comment by YoKeyword** [comment]
下个版本，对于ViewPager下／`loadMultipleRootFragment`加载的Fragment会进行优化，移除多的这一层 :)
