### ISSUE TITLE
Disable Navigation Drawer

### ISSUE THREAD

**Issue by ThunderRoid** [YoKeyword/Fragmentation#36]
Hi,
When "BaseBackFragment" is extended by a fragment, the BACK Button is shown on the TOOLBAR, but if the user swipe from the left edge of the screen the NAVIGATION DRAWER pops open.

Can you implement a method of something so that what the "BaseBackFragment" is extended, the NAVIGATION DRAWER will be disabled, and when the user presses the BACK button the NAVIGATION DRAWER will be enabled.

Thanks so much for this awesome library.

![screenshot_20160705-152844](https://cloud.githubusercontent.com/assets/3328263/16580306/9135b84a-42c5-11e6-9881-25071bc681fc.png)
![screenshot_20160705-153004](https://cloud.githubusercontent.com/assets/3328263/16580307/91371726-42c5-11e6-9a4d-936104224711.png)

**Comment by YoKeyword** [comment]
@ThunderRoid Hi,
You can refer to "BaseMainFragment.OnFragmentOpenDrawerListener" and "SwipeBackSampleFragment.OnLockDrawLayoutListener".

sample:
````java
public class BaseBackFragment extends BaseFragment {
    private BaseMainFragment.OnFragmentOpenDrawerListener mOpenDraweListener;
    private SwipeBackSampleFragment.OnLockDrawLayoutListener mLockDraweListener;

    protected void initToolbarNav(Toolbar toolbar) {
          ....
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof BaseMainFragment.OnFragmentOpenDrawerListener) {
            mOpenDraweListener = (BaseMainFragment.OnFragmentOpenDrawerListener) context;
        }
        if (context instanceof SwipeBackSampleFragment.OnLockDrawLayoutListener) {
            mLockDraweListener = (SwipeBackSampleFragment.OnLockDrawLayoutListener) context;
        }
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (mLockDraweListener != null) {
            mLockDraweListener.onLockDrawLayout(true);
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        if (mLockDraweListener != null) {
            mLockDraweListener.onLockDrawLayout(false);
        }
        mLockDraweListener = null;
        mOpenDraweListener = null;
    }

    @Override
    public boolean onBackPressedSupport() {
        if (mOpenDraweListener != null) {
            mOpenDraweListener.onOpenDrawer();
        }
        return true;
    }
}
````

**Comment by ThunderRoid** [comment]
Did this in the MainActivity, and it worked. Thanks a lot mate.

` @Override
    public void OnLockDrawLayoutListener (boolean lock) {
        if(lock)
            mDrawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
        else
            mDrawer.setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED);
    }`
