### ISSUE TITLE
使用SupportActivity不能使用共享元素

### ISSUE THREAD

**Issue by xyzcwd02** [YoKeyword/Fragmentation#360]
使用SupportActivity就不能使用共享元素跳转activity了，没效果了

**Comment by xyzcwd02** [comment]
是返回的时候没有效果

**Comment by YoKeyword** [comment]
库中共享元素是基于`add()`方式加载Fragment的， 官方最近几个v4版本对这个`add`特性支持的不是很稳定。

后续会支持`replace()`方式的共享元素 :)

**Comment by xyzcwd02** [comment]
是返回的时候如果是SupportActivity就没效果，换成AppCompatActivity就有效果，还没加fragment

**Comment by YoKeyword** [comment]
@xyzcwd02 哦哦，你试下`ActivityCompat.finishAfterTransition(this);`来代替`finish()`方法：
即：
````java
    @Override
    public void onBackPressedSupport() {
        if (getSupportFragmentManager().getBackStackEntryCount() > 1) {
            pop();
        } else {
            ActivityCompat.finishAfterTransition(this); // 替换finish
        }
    }
````

共享元素之前没有考虑到.

**Comment by xyzcwd02** [comment]
厉害，学习了

**Comment by YoKeyword** [comment]
放出了1.0.0，库中使用了`ActivityCompat.finishAfterTransition(this);`替代`finish()`  🍺 :)
