### ISSUE TITLE
Tab切换时onSupportVisible回调失败问题

### ISSUE THREAD

**Issue by kyleduo** [YoKeyword/Fragmentation#361]
应用首页使用Tab结构，切换到某个Tab时，异步任务进行权限申请，出现权限对话框（Activity应该是onPause状态，但是Fragment已经可以看到了）。此时该Tab的onSupportVisible没有回调。
关闭权限申请对话框之后，onSupportVisible也不会回调，只有重新切换Tab才会。

**Comment by YoKeyword** [comment]
`onSupportVisible`/`onSupportInvisible`分别对应Fragment对用户可见/不可见

弹框时你看下调用的生命周期是什么， `onSupportVisible`/`onSupportInvisible`分别和`onResume`/`onPause`有关系

**Comment by kyleduo** [comment]
`onResume`之后，就是`onPause`，没有`onSupportVisible`

**Comment by YoKeyword** [comment]
一般的对话框是不走`onPause`,`onResume`生命周期的 ,权限的不确定， 你看下，如果不走生命周期，`onSupportVIsible``onSupportInvisible`不走是正常的
