### ISSUE TITLE
loadMultipleRootFragment的排序显示问题

### ISSUE THREAD

**Issue by JoyHong** [YoKeyword/Fragmentation#362]
你好，我用这个方法进行根Fragment加载
loadMultipleRootFragment(R.id.fl_root_content, 0, FragmentA, FragmentB, FragmentC, FragmentD, FragmentE);
然后当FragmentD显示的时候，我调用start方法，新起一个FragmentF，然后再pop()，却显示的是FragmentE，而不是FragmentD。
这个是bug?

**Comment by YoKeyword** [comment]
Fragment和Activity在使用上最大不同的地方在于：Fragment层级概念。

D是不能直接`start` F的，应该通过根Fragment来`start` F，或者D的子Fragment `start` F
