### ISSUE TITLE
loadMultipleRootFragment 问题

### ISSUE THREAD

**Issue by zhangchaojiong** [YoKeyword/Fragmentation#363]
我在Activity 使用loadMultipleRootFragment 加载多个根Fragment，首先我的activity 是用了slidemenu，结果使用了 loadMultipleRootFragment  加载的那 几个根Fragment ，都接受不到 所有的 手势事件，包括点击，滑动.. 请问是怎么回事？

**Comment by zhangchaojiong** [comment]
我使用原始的用法：
```
 transaction.hide(mainFragment);
transaction.show(connectFragment);
```
界面是可以点击操作的。如果使用
`showHideFragment(mainFragment, connectFragment);`
界面出现后，无法点击。所有控件都失去事件。

**Comment by zhangchaojiong** [comment]
如果我使用：
```
 loadRootFragment(R.id.main_content,mFragments[SECOND]);
            loadRootFragment(R.id.main_content,mFragments[FIRST]);
            showHideFragment(mFragments[FIRST],mFragments[SECOND]);
```
去替代：
` loadMultipleRootFragment(R.id.main_content, FIRST, mFragments[FIRST], mFragments[SECOND]);`

就完美解决这个问题了。代码运行的很好。
由于项目赶，没有去研究这两个接口里面的原理，所以很好奇，这两个接口的区别是什么呢？

**Comment by YoKeyword** [comment]
诶？ `showHideFragment()`方法内部就是单纯的，`show()`+`hide()`， 可以参照下Demo2，虽然用的BottomBar，不过和你的场景应该类似的

**Comment by YoKeyword** [comment]
`loadMultipleRootFragment`加载多个Fragment，不加入回退栈， `loadRootFragment `加载一个Fragment，加入回退栈

**Comment by zhangchaojiong** [comment]
我是用：
```
 loadRootFragment(R.id.main_content,mFragments[SECOND]);
            loadRootFragment(R.id.main_content,mFragments[FIRST]);
            showHideFragment(mFragments[FIRST],mFragments[SECOND]);
```

去替代了：
```
loadMultipleRootFragment(R.id.main_content, FIRST, mFragments[FIRST], mFragments[SECOND]);
         showHideFragment(mFragments[FIRST],mFragments[SECOND]);
```
结果就能正常使用！真是神奇。。虽然我app 需求上没有没有回退问题需要处理。可我还是想用loadMultipleRootFragment 去实现。。

**Comment by YoKeyword** [comment]
Demo你可否正常使用？  Demo2 ，3使用的`loadMultipleRootFragment `+`showHideFragment `

**Comment by zhangchaojiong** [comment]
Demo可以正常使用。。可是我在FragmentActivity 上有另外的 SlideMenuFragment（侧边栏） ，就无法使用了。不知道是什么原因导致的。

**Comment by YoKeyword** [comment]
最近发布了1.0版本，可以用新版再试试 :)

**Comment by zhangchaojiong** [comment]
ok
