### ISSUE TITLE
关于loadRootFragment/replaceLoadRootFragment退栈问题

### ISSUE THREAD

**Issue by jeonhei** [YoKeyword/Fragmentation#366]
我在做大屏幕APP 涉及到这种设计 就是屏幕上的某一区域是通过事件触发加载的（类似dialog形式） 而使用loadRootFragment/replaceLoadRootFragment等方法加载时却不能设置动画也不能自定义transaction 导致非常突兀 而且也不能使用pop退栈 现在只能使用原始API replace/remove 但又带来另一个问题就是使用原始API加载的fragment start(anotherFragment)失效 望解决

**Comment by YoKeyword** [comment]
pop是可以出栈的，Support默认栈内Fragment数量＝1时，直接关掉Activity，复写下即可： 
````java
// 复写
@Override
 public void onBackPressedSupport() {
        if (getSupportFragmentManager().getBackStackEntryCount() > 1) {
            pop();
        } else {
            // finish();   
        }
    }
````
或者直接在根Fragment上复写`onBackPressedSupport()`，reture true

动画问题，库的处理是根Fragment直接屏蔽动画，这个近期1.0版本，会移除该设定  :)

**Comment by jeonhei** [comment]
嗯 已经解决 目前是用一个空白的fragment去先覆盖区域 然后用它来控制显示内容的fragment
