### ISSUE TITLE
关于添加RxPermissions的问题

### ISSUE THREAD

**Issue by Holybird01** [YoKeyword/Fragmentation#367]
求助：我在项目中使用HomeActivity继承了SupportActivity,由于需要引入了动态权限获取的RxPermissions。但是实际测试时发现并没有出现系统询问权限的弹窗，而是直接返回了false，看了一天没找到头绪，麻烦大神们帮我看看这个问题

**Comment by YoKeyword** [comment]
继承普通的`AppCompatActivity`，会弹出吗？   `SupportActivity`继承自`AppCompatActivity`，里面的代码不多，你可以看下源码， 应该和`SupportActivity`没什么关系

**Comment by lk666** [comment]
看看你的targetApi以及buildApi 是否都 >= 23，不然的话是这样直接返回false的，因为AppCompat的checkPermissions方法是23才引入的

**Comment by YoKeyword** [comment]
库中targeApi是22， 不过APK是跟着主工程的配置走的

**Comment by YoKeyword** [comment]
1.0.0已放出，可以通过implements ISupportActivity/Fragment ＋ Delegate形式自己实现自定义SupportActivity/Fragment

可以参考Fragmentation Module中的SupportActivity/Fragment中的实现方式 🍺 :)

**Comment by flztsj** [comment]
@lk666  你那边RxPermissions使用OK吗？

**Comment by Holybird01** [comment]
修改好了，是引入的问题，真不好意思，您的代码没有问题，是因为rxpermission我使用的是旧版的，所以在这个工程上运行没反应，换成最新版的就没问题了，麻烦您了，一直帮我看这个问题
