### ISSUE TITLE
你好，一个Activity =  TabLayout + ViewPager + 多个Fragment 使用场景问题

### ISSUE THREAD

**Issue by GitHubAFeng** [YoKeyword/Fragmentation#370]
例如一个Activity =  TabLayout + ViewPager + 多个Fragment 的首页布局，如下在加载Fragment时怎么处理 
R.id.fl_tab_container 这个根布局呢？因为这个些Fragment都是Adapter管理的，不知道怎么处理loadMultipleRootFragment 方法里面这个根布局的层级关系。
我看Demo中没有配合ViewPager使用的场景，一时不知道怎么处理。
            loadMultipleRootFragment(R.id.fl_tab_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD]);

**Comment by YoKeyword** [comment]
ViewPager下，直接给ViewPager设置FragmentAdapter即可，不需要用库中的任何方法  :)

**Comment by GitHubAFeng** [comment]
呃，不调用 loadMultipleRootFragment  方法 似乎也能使用其它 API

**Comment by ljf1172361058** [comment]
如果是viewPager+ FragmentAdapter,不需要用loadMultipleRootFragment,那么是不是意味着start()这种的方法也不能调用呢?我调用直接报错,提示 please call loadRootFragment() first!。
请问懒加载,回退事件这种方法也会受影响么

**Comment by YoKeyword** [comment]
@ljf1172361058  `loadMultipleRootFragment`，`ViewPager`情况均属于同级未加入回退栈的场景，是一种特殊场景，避免让其内的Fragment直接`start`， 具体看[这篇wiki](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager#%E5%90%8C%E7%BA%A7%E6%9C%AA%E5%8A%A0%E5%85%A5%E5%9B%9E%E9%80%80%E6%A0%88%E7%9A%84fragments)

**Comment by ljf1172361058** [comment]
现在是首页activity,里面包含viewpage+多fragment,然后其中某个fragement中包含了很多需要进入到其他fragment的菜单,按照wiki上来说,这一层级的fragment没有加入到回退栈,不能直接start,需要用父或子fragment去start,而实际情况是目前这个fragment并没有父或子fragment,难道是要用首页activity去start?或者如何设置它的子fragment
