### ISSUE TITLE
问一下，想在fragment中实现activity的四种启动模式怎么做

### ISSUE THREAD

**Issue by GongZiZhang** [YoKeyword/Fragmentation#373]
比如activity的栈顶模式，我想某个fragment是这种启动模式的，应该怎么设置？

**Comment by YoKeyword** [comment]
使用`start(final SupportFragment toFragment, @LaunchMode int launchMode) `即可

**Comment by GongZiZhang** [comment]
在有viewpagerfragment内的fragment点击列表跳转到其他其他fragment时，使用singtop模式跳转失败，我用demo试了，也跳转不成功

**Comment by YoKeyword** [comment]
Viewpager内的Fragment应保持干净（保证只有通过FragmentPagerAdapter加载进的Fragment），如果你想让其内的Fragment跳转到新的Fragment，应该让其父Fragment去start， 可见第二个Demo
