### ISSUE TITLE
onLazyInitView ViewPage + Fragment

### ISSUE THREAD

**Issue by xiemuyou** [YoKeyword/Fragmentation#374]
您好!
刚使用您写的fragmentation,感觉好强大的样子
但是有些不懂得地方,请教一下
HomeActivity
        |
        |-AFragment
        |               |
	|		|--A1Fragment
	|		|
	|		|--A2Fragment
	|
	|-BFragment
	|
	|-CFragment
        |               |
	|		|--C1Fragment
	|		|
	|		|--C2Fragment
	|		|
	|		|--C3Fragment	
	|		|
	|		|--C4Fragment	
	|
	|-DFragment
	
这是首页的页面结构,
其中C1Fragment 跟 C2Fragment是复用的一个Fragment,
C3Fragment 跟 C4Fragment是复用的另外一个Fragment
现在考虑用Framgneation 实现懒加载,请问用怎么样的结构来实现比较符合Fragmentation 设计的初衷呢.
谢谢

**Comment by YoKeyword** [comment]
ViewPager内的Fragment正常使用FragmentPagerAdapter加载即可，没有特殊的要求，可以看下第二个Demo，应该和你的场景接近 :)

**Comment by xiemuyou** [comment]
那我如果需要在C1 , C2 , C3 , C4 切换页面的时候保存状态.
需要怎么实现呢.

**Comment by YoKeyword** [comment]
如果是ViewPager内的C1－C4，  可以使用`viewPager.setOffscreenPageLimit(3)`来达到切换时不销毁Fragment视图，达到保存页面的状态

**Comment by xiemuyou** [comment]
谢谢
完美的解决了我的问题
