### ISSUE TITLE
请问enqueueAction移除后,有替代方法吗？

### ISSUE THREAD

**Issue by zichen-jiao** [YoKeyword/Fragmentation#377]

**Comment by YoKeyword** [comment]
现在可以直接执行事务方法了，但是不建议在`onCreate()`,`onCreateView()`里执行事务， 建议在`onViewCreated()`或者`onActivityCreated()`里执行事务  :)

**Comment by YoKeyword** [comment]
`handler.post(()-> 事务)`代替即可  :)

**Comment by YoKeyword** [comment]
@zichen-jiao  稍后会发布v1.0.1，  经过旧版本support包的测试`enqueueAction() `还是需要的...

**Comment by YoKeyword** [comment]
@zhangluya  已添加回来，v1.0.1 🍺  :)
