### ISSUE TITLE
replaceLoadRootFragment 替代方法

### ISSUE THREAD

**Issue by Qixingchen** [YoKeyword/Fragmentation#378]
V1.0.0 中移除了 replaceLoadRootFragment, wiki 上说明 统一使用 loadRootFragment()
请问如果使用 loadRootFragment() 来实现 replaceLoadRootFragment 呢?

**Comment by YoKeyword** [comment]
嗯，使用`loadRootFragment ()`代替`replaceLoadRootFragment ()`，直接替换方法即可 :)

**Comment by Qixingchen** [comment]
replaceLoadRootFragment 使用的是三参数的版本 containerId,toFragment,addToBackStack  
replaceLoadRootFragment (layoutID,fragment,false)  
对应到 loadRootFragment  使用 四参数的版本   
loadRootFragment(layoutID, fragment, false, false);  
  

在第二次调用 loadRootFragment 时,视图产生了重叠,没有移除前一次的 fragment.

**Comment by YoKeyword** [comment]
@Qixingchen Oh! 我的问题，`loadRootFragment `内部应该是replace而不是add，稍后给出v1.0.1

**Comment by YoKeyword** [comment]
@Qixingchen  已修复， v1.0.1   🍺

**Comment by Qixingchen** [comment]
好的 已经使用上
