### ISSUE TITLE
App启动优化

### ISSUE THREAD

**Issue by wang9090980** [YoKeyword/Fragmentation#379]
您好：
     Fragmentation在Application里面初始化，应用第一次启动的时候，启动速度如何优化呢？

**Comment by YoKeyword** [comment]
Fragmentation在Application里的初始化，你看源码就会发现，仅仅是设置了几个值而已， 是个非常轻量的库   :)

**Comment by wang9090980** [comment]
好的，谢谢，正在认真仔细读Fragmentation源码。我发现demo里面，列表item快速点击跳转，启动多个重复Fragment的问题。是需要设置什么参数吗？

**Comment by YoKeyword** [comment]
可以使用防抖动手段来处理快速点击问题，比如rxjava， butterknife或者自己处理

多点同时触控的问题，可以通过给Activity设置Theme: 
`  <item name="android:splitMotionEvents">false</item>` 来关闭多点触控

**Comment by wang9090980** [comment]
明白了，谢谢
