### ISSUE TITLE
How to refresh bootombar again?

### ISSUE THREAD

**Issue by AnkurJagani** [YoKeyword/Fragmentation#38]
I am initiating my one of fragment by below code. (i.e. WishList Frgagment) 

` mFragments[FOURTH] = WishListContainerFragment.newInstance();`

   

i have five tabs in bottombar for your refrence.

    public class WishListContainerFragment extends BaseLazyMainFragment {

     public static WishListContainerFragment newInstance() {
        Bundle args = new Bundle();
        WishListContainerFragment fragment = new WishListContainerFragment();
        fragment.setArguments(args);
        return fragment;
     }

     @Nullable
     @Override
     public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable    Bundle savedInstanceState) {
         View view = inflater.inflate(R.layout.multi_container_fragment, container, false);
        return view;
     }

      @Override
     protected void initLazyView(@Nullable Bundle savedInstanceState) {
        /*Need to call every time when user presses on same tab.*/
        if (savedInstanceState == null) {
            boolean isUserLoggedIn = AppGlobal.getBooleanPreference(_mActivity, AppConstant.PREF_IS_USER_LOGGED_IN);
            if (isUserLoggedIn){
                loadRootFragment(R.id.fl_child_container, WishListFragmentNew.newInstance());
            }else{
                loadRootFragment(R.id.fl_child_container, LoginContainerFragment.newInstance());
            }
        }
    } 
      }

Now i want to call  initLazyView every time when user presses on same tab. How should i achieve that?

or is there any other recommendation by you for archiving same thing?  i want to replace rootContainerFragment on same tab, based on some situations. for example user logged in or not.

Please reply asap. Thanks in advance.

**Comment by YoKeyword** [comment]
@AnkurJagani Hi,
````java
   @Override
    protected void initLazyView(@Nullable Bundle savedInstanceState) {
         /*Need to call every time when user presses on same tab.*/
        if (savedInstanceState == null) {
            boolean isUserLoggedIn = AppGlobal.getBooleanPreference(_mActivity, AppConstant.PREF_IS_USER_LOGGED_IN);
            if (isUserLoggedIn) {
                if (findChildFragment(LoginContainerFragment.class) != null) {
                    popTo(LoginContainerFragment.class, true, new Runnable() {
                        @Override
                        public void run() {
                            loadRootFragment(R.id.fl_child_container, WishListFragmentNew.newInstance());
                        }
                    });
                }
            } else {
                if (findChildFragment(WishListFragmentNew.class) != null) {
                    popTo(WishListFragmentNew.class, true, new Runnable() {
                        @Override
                        public void run() {
                            loadRootFragment(R.id.fl_child_container, LoginContainerFragment.newInstance());
                        }
                    });
                }
            }
        }
    }

    /**
     * @see https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_zhihu/MainActivity.java/#L117
     */
    @Subscribe
    public void reselectedTabEvent(TabSelectedEvent event) {
        initLazyView(null);
    }
````

**Comment by AnkurJagani** [comment]
Thankx a lot.

**Comment by AnkurJagani** [comment]
But still there is problem when i am login for first time and double tap on same tab. 

`java.lang.IllegalArgumentException: No view found for id 0x7f0d0124 (com.comnet.com.sg.Verified:id/fl_child_container) for fragment WishListFragmentNew{424e3250 #0 id=0x7f0d0124 com.comnet.com.sg.Verified.moduleMore.WishListFragmentNew}`

**Comment by YoKeyword** [comment]
I just remodified the code.

Do u have  FrameLayout which id is  fl_child_container in your WishListContainerFragment ?

**Comment by YoKeyword** [comment]
Still here?  Maybe I can close the issues...

**Comment by AnkurJagani** [comment]
ohh sorry to late you know. issue got solved already. thanx for help.
