### ISSUE TITLE
Activity has been destroyed

### ISSUE THREAD

**Issue by zhangchaojiong** [YoKeyword/Fragmentation#380]
频繁打开app。释放fragment，然后重新addFragment 。执行`showHideFragment `会出现Activity has been destroyed。
后面我在onDestroyView 添加一下代码：
```
 try {
            Field childFragmentManager = Fragment.class.getDeclaredField("mChildFragmentManager");
            childFragmentManager.setAccessible(true);
            childFragmentManager.set(this, null);


        } catch (NoSuchFieldException e) {
            throw new RuntimeException(e);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
```
还是没有起效果。
后面我在showHideFragment 前面添加：
```
 public void showMainFragment() {
        if(isFinishing()) return;
      showHideFragment （XX）；
}
```
就执行得很好！！
请问什么原因？

**Comment by YoKeyword** [comment]
你给出的第一个代码块里的代码，是解决很早v4版本时的一个BUG的解决方式， 后面的v4版本修复了～

通过你描述的异常`Activity has been destroyed`，说明你在执行事务时，宿主Activity已经销毁了，而`if(isFinishing()) return;`因为判断了宿主Activity是否销毁，所以不会有问题

**Comment by zhangchaojiong** [comment]
有什么办法来替代   ` if(isFinishing()) return;`  
如果每一次 要执行`showHideFragment `前都要加判断将会很麻烦。

**Comment by YoKeyword** [comment]
执行事务时，FragmentManager会判断宿主状态，你出现该异常说明，在执行`showHideFragment()`时宿主已经被销毁了。

检查下代码，看`showHideFragment()`是否是个异步回调任务，导致在回调执行前，宿主已经被销毁。

处理方式是 在宿主销毁时，及时停止异步任务

**Comment by zhangchaojiong** [comment]
我调用了`finish（）；` 然后我是在ondestroy 去取消回调。但是activity 在finishing 的时候（也就是还没有finish 完。正在finish中）  这时候还没有执行ondestroy，接着回调依旧有效，那么数据一回来，执行`showHideFragment `就出现了问题

**Comment by YoKeyword** [comment]
在`finish()`时 取消回调就可以了
