### ISSUE TITLE
你好 demo跑不起来

### ISSUE THREAD

**Issue by maxin94** [YoKeyword/Fragmentation#381]
![image](https://user-images.githubusercontent.com/19199019/27618127-1a6e9c12-5bed-11e7-9724-6e293296f632.png)

**Comment by YoKeyword** [comment]
昨天把support包降级到v25.3.1， 有小伙伴翻译25.4.0的包不好拉下来（25.4.0开始support包被托管到googleMaven）

v25.3.1的 mActive是ArrayList，稍等，我更到25.4.0

**Comment by maxin94** [comment]
thx
