### ISSUE TITLE
同一个转场动画，为啥在activity和fragment上效果不一样啊？

### ISSUE THREAD

**Issue by zhangz89** [YoKeyword/Fragmentation#382]
activity是通过manifest中的theme设置；fragment是通过对于的supportActivity中的onCreateFragmentAnimator()设置，但是activity切换到activity和fragment切换到fragment两个动画明显不一样；activity的更顺畅

**Comment by YoKeyword** [comment]
@zhangz89 Fragment动画时，`onCreateView`等生命周期里的逻辑是同时执行的，因为v4包的Fragment用的Animation，所以都在主线程执行，会导致卡顿情况

库中提供了`onEnterAnimationEnd()`回调，在入场动画结束时回调，在此执行复杂的业务逻辑、UI逻辑，会保证动画的流畅执行

另外未来发布的support-26.0.0，支持了Animator动画，在5.0+的设备上，动画不再跑在主线程，所以官方发布26.0.0正式版后， 我这边会同步支持 :)
