### ISSUE TITLE
您好，想问一下，升级版本(1.0.1)后的一个严重问题(onSupportVisible和onLazyInitView的调用顺序)

### ISSUE THREAD

**Issue by chysx** [YoKeyword/Fragmentation#383]
我之前用的版本是0.10.1，fragment的调用顺序是先调用onLazyInitView，然后再调用onSupportVisible，我也是根据这个顺序来写业务逻辑的，但是今天升级到1.0.1版本后，发现很多页面都抛出空指针，打log发现是因为，升级版本后，先调用的onSupportVisible，然后再调用的是onLazyInitView，不知道目前升级的版本的处理是故意为之呢，还是别的其他原因

**Comment by YoKeyword** [comment]
这个调用时机是从0.10.4调整的，原因是 假设我同时使用 `onLazyInitView `和`onSupportVisible `，即第一次可见时我期望做A，以后可见时期望做B， 如下代码会更合理：
````java
boolean firstVisible = true;

onLazyInitView(){
    doA();
    firstVisible = false;
}

onSupportVisible(){
    if(firstVisible) return;
    doB();
}
````
如果是之前的调用顺序: `onLazyInitView ` -> `onSupportVisible` ,  你会发现 doA(), doB()都会调用...

所以调用时机做了调整  :)

**Comment by chysx** [comment]
好的，非常感谢
