### ISSUE TITLE
tablayout + viewpager 的页面，升级1.0.1后，viewpager滑到底，再回来重新加载页面的时候出现空白，页面没有显示出来

### ISSUE THREAD

**Issue by zgh0711** [YoKeyword/Fragmentation#384]
如题描述。原版本是0.10.3，就写了一个很简单的测试页面，底部tabLayout（用的FlycoTabLayout），4个tab，结合 viewpager 使用，0.10.3 版本下一切正常。
今天看到 Fragmentation 有更新，就更新了下，结果发现 viewpager 重新加载页面的时候就空白了，不知道更新到1.0.1 后需要做什么其他的处理才能让界面正常显示呢？

如果要看具体代码才能知道是哪里的问题的话可以去 https://github.com/zgh0711/AndroidDevTemplate  这里看，与这个问题相关的几个文件分别是 BaseFragment，BaseListFragment，ListFragment，MainActivity，
麻烦帮忙看看是哪里的问题，谢谢！

**Comment by YoKeyword** [comment]
原因是你UI逻辑放在`onLazyInitView()`， 重新切回时没有再调用该方法

按我之前的想法是`onLazyInitView()`应该在Fragment销毁之前(`onDestroy`)只调用一次， 
1.0版本之前是在`onDestroyView`后重置标记位，所以再次调用`onCreateView`时会再次调用`onLazyInitView()`

但是现在想来`onLazyInitView()`应该还是要按之前的逻辑，现在虽然意义上合理，但是对开发造成了不便...   稍后更新v1.0.2 恢复之前的逻辑～

**Comment by zgh0711** [comment]
哦哦，那就坐等更新了哈

**Comment by YoKeyword** [comment]
@zgh0711  更新了v1.0.2， 恢复了`onLazyInitView`的逻辑  🍺   :)

**Comment by zgh0711** [comment]
嗯嗯，看到了，大神辛苦了

**Comment by zgh0711** [comment]
@YoKeyword  升级到1.0.2后，从 tab4 回到 tab1 的时候，tab1 还是会空白，但是如果来回多点击几次的话，tab1 又会恢复正常，而 tab4 也会有时候出现空白。您可以把我那代码跑一下看看效果，帮忙看下要怎么解决，谢谢！

**Comment by YoKeyword** [comment]
@zgh0711  我看了下 调用时机的问题， `onLazyInitView()`先于`onCreateView()`执行，我调整下，O了@你 :)

**Comment by YoKeyword** [comment]
@zgh0711 已经修复， v1.0.3， 为了兼容replace正常执行相关生命周期引发的问题  🍺  :)

**Comment by zgh0711** [comment]
嗯，这次应该是好了，页面正常显示了。感谢大神！
