### ISSUE TITLE
混淆

### ISSUE THREAD

**Issue by Gavin9** [YoKeyword/Fragmentation#385]
大神   有没有混淆规则啊！

**Comment by YoKeyword** [comment]
不需要混淆 :)

**Comment by YoKeyword** [comment]
@Gavin9 
Ohhhh！  v1.0开始，因为兼容v4包的原因，还是有一条混淆规则的：
`-keep class * extends android.support.v4.app.FragmentManager{ *; }`

**Comment by Gavin9** [comment]
thankyou！
