### ISSUE TITLE
你好，请问下有没有直接退出全部已加载的SupportFragment

### ISSUE THREAD

**Issue by OaixGnauh** [YoKeyword/Fragmentation#387]
有个需求，需要退出全部Fragment后重新载入（同级类似QQ的和同级下嵌套的）。
现在用的popTo()一个个推到栈顶，然后再重新载入Fragment。但是在1.0.1中会报错(0.10.3可以使用)，所以退回了0.10.3。
但总感觉自己逻辑哪里不对。

` //主页
popTo(Main_1_Function.class, false);
popTo(Main_2_Study.class, false);
popTo(Main_3_Sociality.class, false);
popTo(Main_4_Friend.class, false);
popTo(Main_5_Personal.class, false);

//会话
popTo(Inside_Main_3_HuiHua.class, false);
popTo(Inside_Main_3_QunLiao.class, false);
popTo(Inside_Main_3_TongXunLu.class, false);

//新闻
popTo(Main_1_Fun_News.class,false);

initFragment(null);
`

**Comment by YoKeyword** [comment]
为什么不直接pop 主页、会话、新闻的父Fragment呢？

````java
popTo(ParentFragment.class, ture, runnable(-> start(ParentFragment) ))
````
