### ISSUE TITLE
从fragment跳转到新的activity并且pop当前fragment

### ISSUE THREAD

**Issue by zhangz89** [YoKeyword/Fragmentation#388]
A Activity：LoginFragment（登录） -》CommFragment（通讯）-》LoginResultFragment（结果），结果界面点击确定，跳转到新的B Activity，这个时候要同时pop 通讯和结果界面， 能做到吗？
从通讯到结果界面可以使用startwithpop，但是从结果界面跳转到新的activity，有什么方法？

**Comment by YoKeyword** [comment]
你可以这么操作：

````java
final LoginFragment fragment =findFragment(LoginFragment.class);

popTo(LoginFragment.class, false, new Runnable() {
        @Override
        public void run() {
             fragment.startActivity(new Intent(_mActivity, BActivity.class));
        }
});
````

**Comment by zhangz89** [comment]
@YoKeyword 可以实现正常跳转，但是从BActivity返回的时候，可以很明显的看到结果界面显示一小段时间，然后才回到登录界面

**Comment by YoKeyword** [comment]
目前2种可能会发生你说的情况：
1、BActivity还没完全进入就点击了返回
2、还未完全进入就触碰了BActivity的触摸事件

第2种情况可以修复，原因是AimationListener有时不会及时、甚至不触发`onAimationEnd()`方法

**Comment by zhangz89** [comment]
@YoKeyword 我是进入BActivity很久以后才按返回的，还是会出现，这两种情况都不符合吧？

**Comment by YoKeyword** [comment]
v1.0.4已放出，` popTo()动画进一步优化` ,该问题已修复  🍺
