### ISSUE TITLE
多个Fragment复用同一个layout，并loadRootFragment到同一个containerId，popTo（TransactionDelegate.mockPopAnim）时崩溃

### ISSUE THREAD

**Issue by harv** [YoKeyword/Fragmentation#389]
https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java#L493
获取 container 会始终得到~~第一个 loadRootFragment 进去的 fragment 中的~~同一个container，导致后面 removeViewInLayout 失败
进而 https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java#L531
报错 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by YoKeyword** [comment]
> loadRootFragment到同一个containerId

是指多次load吗？

最好可以描述下场景 :)

**Comment by harv** [comment]
和demo中的知乎类似，有ZhihuFirstFragment，ZhihuSecondFragment.. 区别在于这些Fragment使用了同一个layout xml

**Comment by YoKeyword** [comment]
共用同一个布局文件没影响的，  看你的描述， 你是load不同Fragment到不同的ContianerId,然后再popTo时出现了问题吗？

可以的话，贴下load, pop处的代码

**Comment by harv** [comment]
public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);

        if (findChildFragment(SectionFragment.class) == null) {
            Bundle args = new Bundle();
            args.putString("title", getResources().getString(R.string.menu_section));
            args.putBoolean("showMenu", true);
            loadRootFragment(R.id.fl_container, SectionFragment.newInstance(args));
        }
    }

    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);

        if (findChildFragment(HotFragment.class) == null) {
            Bundle args = new Bundle();
            args.putString("title", getResources().getString(R.string.menu_hot));
            loadRootFragment(R.id.fl_container, HotFragment.newInstance(args));
        }
    }

        SupportFragment currentFragment = mFragments.get(mCurrentItemId);
        switch (mCurrentItemId) {
            case R.id.menu_hot:
                currentFragment.popToChild(HotFragment.class, false);
                break;
            case R.id.menu_section:
                currentFragment.popToChild(SectionFragment.class, false);
                break;
            ...
        }

统一布局的统一ContianerId（R.id.fl_container）

**Comment by harv** [comment]
又试了下，的确是2个Fragment里得到的这2个view（container）是同一个，导致第二个Fragment里removeViewInLayout失败了

**Comment by YoKeyword** [comment]
👍 赞！  我这边应该可以处理：
`View view = mActivity.findViewById(from.getSupportDelegate().mContainerId)` 替换为:
````java
View view = findViewById(fromF, from.getSupportDelegate().mContainerId);

private View findViewById(Fragment fragment, int containerId) {
        Fragment parentFragment = fragment.getParentFragment();
        if (parentFragment != null) {
            if (parentFragment.getView() != null) {
                return parentFragment.getView().findViewById(containerId);
            } else {
                return findViewById(parentFragment, containerId);
            }
        } else {
            return mActivity.findViewById(containerId);
        }
    }
````

**Comment by YoKeyword** [comment]
v1.0.4上传了，已修复 🍺
