### ISSUE TITLE
SwipeBackLayout小修改

### ISSUE THREAD

**Issue by duchengzhen** [YoKeyword/Fragmentation#390]
SwipeBackLayout中:
`

    public void attachToFragment(SwipeBackFragment swipeBackFragment, View view) {
        addView(view);
        setFragment(swipeBackFragment, view);
    }

`
这里SwipeBackFragment参数类型可以改为ISupportFragment

**Comment by YoKeyword** [comment]
@duchengzhen  Oh！ 是的，遗漏了， 可以提个PR哈   🍺

**Comment by YoKeyword** [comment]
v1.0.4已放出，SwipeBack库多余引用问题移除了， 同时提供了Interface + Delegate  🍺
