### ISSUE TITLE
_mActivity null in SupportFragment after the system kills processes when it needs to free up RAM

### ISSUE THREAD

**Issue by ngochuu90** [YoKeyword/Fragmentation#392]
Hi @YoKeyword 

`_mActivity` null in SupportFragment  after application is killed because another app needs memory
I tested using the "`Terminate Application`" function in Android Studio

- The first time: App is running --> tap the Home button --> `Terminate Application` --> restart App from backstack -->App works normally
- Continue: --> tap the Home button --> `Terminate Application` --> restart App from backstack -->`_Activity `is null

**Comment by YoKeyword** [comment]
Hi @ngochuu90 

If App is killed, fragment will re-attach to Activity when it comes back, then _mActivity is not null.  
Before fragment was attached, _mActivity is null

**Comment by ngochuu90** [comment]
I init Adapter in onLazyInit
`MyAdapter mAdapter = new MyAdapter(_mActivity)`

Can you help me to solve this problem

**Comment by YoKeyword** [comment]
Which version do you use?

**Comment by ngochuu90** [comment]
I'm using the latest version: 1.0.3

**Comment by YoKeyword** [comment]
In my demo:  (`me.yokeyword.sample.demo_zhihu.ui.fragment.second.child.ViewPagerFragment `,`FirstPagerFragment`)


No matter how many times : App is running --> tap the Home button --> Terminate Application(`adb shell am kill me.yokeyword.sample`) --> restart App from backstack -->App works  **always** normally

**Comment by ngochuu90** [comment]
Version 1.0.3 has something incompatible with dagger 2.
Each Terminate Application, the number of times "onLazyInit" is recalled increases
For example, after 3 times "Terminate Application", "onLazyInit" is called 3 times
When I revert to version 0.10.7, everything works well

**Comment by YoKeyword** [comment]
It seems that you have repeatedly loaded Fragment when it comes back

In my demo:
````java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
       ...
        if (findFragment(HomeFragment.class) == null) {
            loadRootFragment(R.id.fl_container, HomeFragment.newInstance());
        }
        ...
    }
````

**Comment by ngochuu90** [comment]
This is the key to solving the issue. I just check `savedInstanceState == null` like Demo v0.10.7
Thank for your support.
