### ISSUE TITLE
1.0之后切换fragment，布局延伸至状态栏的问题

### ISSUE THREAD

**Issue by wdeo3601** [YoKeyword/Fragmentation#393]
之前版本无问题，当我升级到1.0.3之后，主界面其中有一个 tab 页需要眼神布局到状态栏、其他3页不需要，当点击底部bottombar切换时，底部bottombar会向下或向上移动（因为状态栏高度的问题），好像没有重新测量绘制一样

**Comment by YoKeyword** [comment]
@wdeo3601 确定之前版本没问题吗？   你的问题是布局会上移／下移一个状态栏的高度吗？  这个是Fragment本身适配状态栏时存在的一个BUG，之前库版本应该也存在的

解决方案可以看下：https://github.com/YoKeyword/Fragmentation/issues/137

**Comment by wdeo3601** [comment]
@YoKeyword 确定是新版本出现问题，我现在还回 0.10.7 就没事

**Comment by YoKeyword** [comment]
我这边diff了下， 1.0和0.10没有动过相关的代码 囧，  或者考虑换个方案？
