### ISSUE TITLE
下载下来导入报错啊

### ISSUE THREAD

**Issue by fangithubgithub** [YoKeyword/Fragmentation#395]
Error:(75, 53) 错误: 不兼容的类型: ArrayList<Fragment>无法转换为SparseArray<Fragment>

**Comment by fangithubgithub** [comment]
@SuppressWarnings("unchecked")
    public static List<Fragment> getActiveFragments(FragmentManager fragmentManager) {
        if (!(fragmentManager instanceof FragmentManagerImpl))
            return Collections.EMPTY_LIST;
        if (sSupportLessThan25dot4) return fragmentManager.getFragments();

        try {
            FragmentManagerImpl fragmentManagerImpl = (FragmentManagerImpl) fragmentManager;
            return getActiveList                                      //(fragmentManagerImpl.mActive);//报错
        } catch (Exception e) {
            e.printStackTrace();
        }
        return fragmentManager.getFragments();
    }

**Comment by YoKeyword** [comment]
Demo编译环境需要 support-25.4.0

**Comment by fangithubgithub** [comment]
//(fragmentManagerImpl.mActive);//报错
    } catch (Exception e) {    //support-25.4.0支持啊

**Comment by YoKeyword** [comment]
检查下fragmenation-core是否成功引用了v4-25.4.0，  mActive从25.4.0开始由 ArrayList -> SpareArray，所以编译环境一定要确保是v4-25.4.0

或者Demo引用由`compile project·`改为`compile 'me.yokeyword.fragmentation'`，这样的话demo任何v4版本都可以

**Comment by fangithubgithub** [comment]
好的我一了解
