### ISSUE TITLE
内存不足时，SuppotFragment嵌套的SuppotFragment被销毁了

### ISSUE THREAD

**Issue by hegaojian** [YoKeyword/Fragmentation#396]
场景： 首页 SupportActivity A 包含4个SupportFragment ,第三个fragment中还嵌套了2个SupportFragment, 在低端机手机中，若内存不足，或因某种意外原因崩溃回来后，发现fragment3 页面显示一片空白，它包含的2个SupportFragment 被销毁了
请问大佬，我该怎么用什么方法恢复，或者让他重新加载一遍？

**Comment by YoKeyword** [comment]
通过`load`加载的根Fragment需要判断:
````java
if(findFragment(Root.class) == null){
    loadRootFragment(root);
}
````

Fragment重启时会重新走一遍生命周期，页面空白：可能是你的数据没有加载出来，比如数据不是通过Arguments传递的， 或者加载的数据需要保存恢复，而你没有去保存等等

建议通过下面的方法模拟场景，调试下 :)
> 模拟方式：  开发者模式 -> 打开不保留活动， 然后回到桌面，再回App可以模拟销毁重启的场景

**Comment by hegaojian** [comment]
大佬，弄好了，我使用你的 if(findFragment(Root.class) == null){ 这个判断，若为null，我重新加载一遍就好了，非常感谢！
