### ISSUE TITLE
下载你的项目 会发现没有settings.gradle 会导致项目跑不起来 加上后编译需要编译好久

### ISSUE THREAD

**Issue by ysk152** [YoKeyword/Fragmentation#397]
上传到github的简化过度了 搞得下下来啥都缺

**Comment by YoKeyword** [comment]
settings.gradle这个文件是有的，可以看git文件 

项目依赖了support-25.4.0，自25.4.0开始google把support包放到了自己的maven上了:`maven {url "https://maven.google.com"}`
![image](https://user-images.githubusercontent.com/9691640/27724936-b06b60c8-5da6-11e7-8f30-f100ddc95823.png)

编译较久的话，应该是拉取 25.4.0的support库比较慢，拉取需要翻墙 :)

**Comment by ysk152** [comment]
并且没有 settings.gradle  导致下载下来 项目无法运行 这样会吧小白挡到门外的

**Comment by YoKeyword** [comment]
@ysk152 看图... settings.gradle有的...
![image](https://user-images.githubusercontent.com/9691640/27727127-b6c64452-5daf-11e7-9ec5-d7e11374f26f.png)

翻不了墙的话，把demo里的support包改成任意低版本，比如25.3.1，然后
````java
 compile project(':fragmentation')
 compile project(':fragmentation_swipeback')
````` 
替换为
````java
compile 'me.yokeyword:fragmentation:1.0.4'
compile 'me.yokeyword:fragmentation-swipeback:1.0.4'
````

**Comment by ysk152** [comment]
![qq 20170630162920](https://user-images.githubusercontent.com/16794106/27727533-755c6986-5db1-11e7-953b-14bc72bc2da0.png)
下载后的解压文件里确实没有  你changshi尝试一下

**Comment by LonelyMushroom** [comment]
@ysk152 
![image](https://user-images.githubusercontent.com/19225489/27728671-62124522-5db5-11e7-8acf-1ac20521616b.png)
这是我刚刚下载的
![image](https://user-images.githubusercontent.com/19225489/27728682-6c339f06-5db5-11e7-8699-04f1c5c585ac.png)
这里是有settings.gradle的.
麻烦你看下是不是杀毒软件导致,或者换个浏览器还有压缩工具试下,如果实在不行的话你尝试用soucetree这个工具将项目完整的clone下来也行.欢迎反馈.

**Comment by ysk152** [comment]
好的 谢谢@LonelyMushroom
