### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by glassweichao** [YoKeyword/Fragmentation#398]
请问有遇到过这个问题吗？
是否需要替换commit 为 commitAllowingStateLoss

**Comment by LonelyMushroom** [comment]
@glassweichao 能否将你使用的代码片段贴上来,好帮你定位

**Comment by YoKeyword** [comment]
@glassweichao 
见 #317 , 详细可看[这篇文章](http://www.jianshu.com/p/d9143a92ad94)
