### ISSUE TITLE
有两个bug不知道能否修复

### ISSUE THREAD

**Issue by damingwangguan** [YoKeyword/Fragmentation#40]
1，如果添加了viewTreeoberser,就是那个监听viewtree创建完成的事件，会导致fragment的动画不能正常显示；
2，如果在onhidedchanged 里操作view会让fragment动画不能正常展示，（会有个奇怪的延迟）

**Comment by YoKeyword** [comment]
@damingwangguan 能附上代码吗？ 你的描述不是很容易理解，最好是在demo的基础上操作的代码~

**Comment by damingwangguan** [comment]
感谢，正是你说的这种情况，我的解决方法也是延迟操作，ViewTreeObserver的问题，是因为我需要获取weiget的高度，而在fragment里没有合适的时机进行获取，只好加了一个监听，我当时加的是ongloalxxxx的监听器，结果是动画不出来还是滑动返回不响应（好像是其中某一个）。

**Comment by YoKeyword** [comment]
@damingwangguan 好的 第一种情况我回头留意下看看什么情况~  感谢反馈
