### ISSUE TITLE
提交一个代码问题

### ISSUE THREAD

**Issue by li13738051517** [YoKeyword/Fragmentation#400]
你好, yokeyword .
当我让阅读你的frageentation_core时.

    @SuppressWarnings("unchecked")
    private static List<Fragment> getActiveList(SparseArray<Fragment> active) {
        if (active == null) {
            return Collections.EMPTY_LIST;
        }
        final int count = active.size();
        ArrayList<Fragment> fragments = new ArrayList<>(count);
        for (int i = 0; i < count; i++) {
            fragments.add(active.valueAt(i));
        }
        return fragments;
    }

   return getActiveList(fragmentManagerImpl.mActive); mactivte  ------>mactivite ArraylIst

so ..............你可能需要这些写
     private static List<Fragment> getActiveList(ArrayList<Fragment> active) {
        if (active == null) {
            return Collections.EMPTY_LIST;
        }
        final int count = active.size();
        ArrayList<Fragment> fragments = new ArrayList<>(count);
        for (int i = 0; i < count; i++) {
            fragments.add(active.get(i));
        }
        return fragments;
    }

例外非常感谢你 提供了这样的一个开源作品  .

**Comment by YoKeyword** [comment]
@li13738051517 
从support-25.4.0开始，v4包里的mActive由ArrayList换成了SparseArray，所以是为了兼容25.4.0

````java
 public static List<Fragment> getActiveFragments(FragmentManager fragmentManager) {
        if (!(fragmentManager instanceof FragmentManagerImpl))
            return Collections.EMPTY_LIST;
        // For pre-25.4.0
        if (sSupportLessThan25dot4) return fragmentManager.getFragments();

        // For compat 25.4.0+
        try {
            FragmentManagerImpl fragmentManagerImpl = (FragmentManagerImpl) fragmentManager;
            // Since v4-25.4.0，mActive: ArrayList -> SparseArray
            return getActiveList(fragmentManagerImpl.mActive);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return fragmentManager.getFragments();
    }
````

我刚推上去几个注释 🍺， Demo编译的环境需要25.4.0，如果是自己项目依赖Fragmentation的话，则任何v4版本都是可以的  :)
