### ISSUE TITLE
loadMultipleRootFragment 诡异问题

### ISSUE THREAD

**Issue by shingohu** [YoKeyword/Fragmentation#402]
使用loadMultipleRootFragment 加载同级别Fragment,某种情况会出现诡异问题
仿微信交互方式
当第二个Tab中Fragment中使用SwipeRefreshLayout下拉刷新时,若此时正在刷新,切换到第一个Tab,此时第一个Fragment被第二个覆盖了，第三个,第四个Tab界面也很诡异

重现步骤(demo中知乎demo)
1.修改ZhihuSecondFragment中的布局,在布局外直接套一层SwipeRefreshLayout
2.切换到ZhihuSecondFragment Tab,下来刷新
3.切换到其它Tab

同样方式修改微信demo中第二个tab 一样存在此问题

**Comment by YoKeyword** [comment]
@shingohu 是修改zhihu_fragment_second.xml吗？ 我真没有复现

不过很有可能是`SwipeRefreshLayout`的问题，这东西经常出现莫名其妙的层级、视觉问题，我这边用的v25.3.1的v4包

**Comment by shingohu** [comment]
@YoKeyword 是的 修改demo中的zhihu_fragment_second.xml 
方便留个qq或者邮箱 我发给你APK看下？

**Comment by YoKeyword** [comment]
OK   我的QQ: 328903522  :)

**Comment by YoKeyword** [comment]
已解决 🍺
不要在Fragment中把`SwipeRefreshLayout`作为根布局，用FrameLayout等 包一下`SwipeRefreshLayout`即可
