### ISSUE TITLE
下载1.0.4build失败

### ISSUE THREAD

**Issue by timtolead** [YoKeyword/Fragmentation#404]
Error:(5, 0) CreateProcess error=2, 系统找不到指定的文件。
<a href="openFile:C:\Users\hao\AndroidStudioProjects\Fragmentation-master\demo\build.gradle">Open File</a>

**Comment by YoKeyword** [comment]
@timtolead 信息太少...
1.0.4拉不下来？   
是运行Demo build失败，还是项目依赖1.0.4时build失败？

**Comment by timtolead** [comment]
下载1.0.4压缩包，直接运行demo的时候build失败

**Comment by YoKeyword** [comment]
项目依赖了support-25.4.0，自25.4.0开始google把support包放到了自己的maven上了:
maven {url "https://maven.google.com"}
所以拉取v4-25.4.0需要翻墙...

Demo编译环境至少v4-25.4.0，如果自己项目通过gradle依赖的话，任何版本support-v4包都可以

**Comment by timtolead** [comment]
明白了 谢谢！

**Comment by Jacky-Xu** [comment]
@YoKeyword  任何版本support-v4包都可以，并不可以，报错提示不兼容类型ArrayList<Fragment>转换成SparseArray<Fragment>

**Comment by YoKeyword** [comment]
@Jacky-Xu 哪个版本？    是compile依赖的吗？    是否有开启混淆

**Comment by Jacky-Xu** [comment]
compile 'com.android.support:support-v4:25.3.1' 依赖这个版本，没有开启混淆

**Comment by YoKeyword** [comment]
@Jacky-Xu README上的demo是否可以正常运行？

**Comment by Jacky-Xu** [comment]
@YoKeyword  maven {url "https://maven.google.com"} 翻不了墙，公司限制了网。demo也运行不起来。

**Comment by YoKeyword** [comment]
@Jacky-Xu 加下我QQ看下吧 328903522

**Comment by LoveqLRC** [comment]
这样会存在兼容问题吗?`provided 'com.android.support:appcompat-v7:26+' ` 改成`26+`

**Comment by LoveqLRC** [comment]
The same issues，要不换个版本，或者提供一下下载方式,这墙翻起来不方便。

**Comment by YoKeyword** [comment]
@LoveqLRC 
编译Demo项目必须要25.4.0的版本，因为为了兼容各个版本v4的问题， 如果是自己的项目compile的话，哪个v4版本都可以

另一种不要25.4.0版本 运行Demo项目的方式是，把demo的build.gradle:
````xml
// compile project(':fragmentation')
// compile project(':fragmentation_swipeback')
更换为
compile 'me.yokeyword:fragmentation:1.0.7'
compile 'me.yokeyword:fragmentation-swipeback:1.0.7'
````
 然后把fragmentation, fragmentation-core, fragment-swipeback 这3个Module移除

**Comment by LoveqLRC** [comment]
@YoKeyword Well done

**Comment by YoKeyword** [comment]
另外，` CreateProcess error=2, 系统找不到指定的文件`的错误是因为没有装git，而Demo的build.gradle里有git命令
````java
static def gitLatestTag() {
    def cmd = 'git describe --abbrev=0 --tags'
    def result = cmd.execute().text.trim()
    return result
}
````

我刚提交了一个commit，`try-catch`了该方法，应该不会出现"找不到指定文件的问题"了
