### ISSUE TITLE
fragment中能否增加dispatchTouchEvent，dispatchKeyEvent等回调

### ISSUE THREAD

**Issue by zhangz89** [YoKeyword/Fragmentation#405]
在Activity中的这些可以通过判断当前栈顶的fragment，然后传递给fragment，在fragment中去处理这些；便于在fragment中开发业务

**Comment by YoKeyword** [comment]
v1.0开始不需要强制继承SupportActivity/Fragment， 你可以复制其内部的委托方法到自定义的YoutSupportFragment中，自己增加`dispatchTouchEvent，dispatchKeyEvent`等回调  :)

另外不知道你是否需要的是BACK事件，Fragmentation对回退事件有支持方案，可见[wiki Back键的事件传递机制](https://github.com/YoKeyword/Fragmentation/wiki/6.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-Back%E9%94%AE%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E6%9C%BA%E5%88%B6)
