### ISSUE TITLE
A Fragment跳到B Fragment为什么不会触发A的onPause，onStop等回调？

### ISSUE THREAD

**Issue by zhangz89** [YoKeyword/Fragmentation#407]
从A跳到B，居然没触发一个回调啊，比如event bus注册与取消，我想在fragment显示的时候注册，不在栈顶的时候取消

**Comment by YoKeyword** [comment]
`start()`内部是`add() + show() + hide()` 方式加载的Fragment，所以A启动B，仅会回调A的：
`onHiddenChanged(true)` 以及 库提供的`onSupportInvisible()`

在这种情况下，`onResume()`,`onPause()`仅会跟随宿主Activity的回调而回调

**Comment by zhangz89** [comment]
@YoKeyword  Fragment A start跳到B触发一次onHiddenChanged，B startwithpop 到C 又会触发 A的onHiddenChanged两次；这个算不算BUG？

**Comment by YoKeyword** [comment]
原因是Fragment和Activity不同，是非常严格的栈，所以`startWithPop()`不可能先`start(C)`再把B `pop()`， 其内部是先`pop()` B ，再`start(C)`，这样就导致A会show然后紧接着hide，从而触发`onHiddenChanged `两次

解决方案已经找到，`startWithPop()`过程中，A的`onHiddenChanged()`方法库在内部拦截掉， 下个版本解决该问题
