### ISSUE TITLE
Attempt to invoke virtual method 'android.view.animation.Animation me.yokeyword.fragmentation.helper.internal.AnimatorHelper.getViewPagerChildFragmentAnimFixed(android.support.v4.app.Fragment, boolean)' on a null object reference

### ISSUE THREAD

**Issue by cnSpyro** [YoKeyword/Fragmentation#408]
这是怎么回事，我把FragmentPagerAdapter改成FragmentStatePagerAdapter就出现这个问题了

**Comment by YoKeyword** [comment]
从Log来看是因为在执行`onCreateAnimation()`时，AnimatorHelper对象为空，AnimatorHelper是在`onCreate()`中初始化的， Fragment生命周期：`onCreate()`->...->`onCreateAnimation()`

所以讲道理应该不会出现null问题，Demo中`FragmentPagerAdapter`改成`FragmentStatePagerAdapter`也没问题

可以把详细Log贴一下，或者在崩溃的Fragment上断点调试下，看下生命周期执行情况 :)

**Comment by jiahongyu0529** [comment]
我没设置动画啊，可以关掉吗？

**Comment by YoKeyword** [comment]
现在出现的问题是 看起来 Fragment生命周期执行顺序有问题，而且奇怪的是`FragmentPagerAdapter `没事，改成`FragmentStatePagerAdapter `有问题

建议在崩溃的Fragment上断点调试下，看下生命周期执行情况，或者和Demo: `ViewPagerFragment`里使用方式对比下，排查下

**Comment by jiahongyu0529** [comment]
我看了好像是，commit方法是在Activity的onSaveInstanceState()之后调用的，这样会出错，因为onSaveInstanceState
方法是在该Activity即将被销毁前调用，来保存Activity数据的，如果在保存玩状态后再给它添加Fragment就会出错。解决办法就
是把commit（）方法替换成 commitAllowingStateLoss()就行了

**Comment by jiahongyu0529** [comment]
这个方法在SupportFragmentDelegate的processRestoreInstanceState（Bundle savedInstanceState）里面

**Comment by jiahongyu0529** [comment]
请问下新版本会改嘛？

**Comment by YoKeyword** [comment]
嗯，是可以把`commit()`改成`commitAllowingStateLoss()`的

问题是：`processRestoreInstanceState()`里的代码会在 **页面被回收后重启时**调用，而重启时宿主Activity应该是不会调用`onSaveInstanceState()`的 （这个方法会在Activity不可见、可能会被回收等情况下触发）

你的问题可能类似`Can not perform this action after onSaveInstanceState` 
可以见 #317 , 详细可看这篇文章

**Comment by YoKeyword** [comment]
v1.0.5放出，顺手把`processRestoreInstanceState()`的`commit()`改成`commitAllowingStateLoss()`

但是这个只是治标不治本的方法，建议还是从`Can not perform this action after onSaveInstanceState`的问题上着手解决问题
