### ISSUE TITLE
关于loadMultipleRootFragment方法的bug

### ISSUE THREAD

**Issue by nuli1228588792** [YoKeyword/Fragmentation#409]
我在mainAct 里 用的
 loadMultipleRootFragment(R.id.fl_main_content, 3,mFragments[FIRST],mFragments[SECOND],
 mFragments[THIRD], mFragments[FOURTH]);
方法加载根fragment，我显示的fragment 位置是3，但是mFragments[FIRST] 的onSupportInvisible 方法会回调，其他生命周期的方法却不回调，我在 onSupportInvisible 里有代码，造成了空指针，直接崩溃

**Comment by YoKeyword** [comment]
`onSupportInvisible()`基于官方的`onHiddenChanged()`，这种情况下`onHiddenChanged()`先于`onCreateView()`执行，造成了View的空指针问题

这个库可以对`onSupportInvisible()`做安全处理，下版本兼容， 暂时可以先判断处理：
````java
if(view != null){
   // do
}
````

**Comment by YoKeyword** [comment]
v1.0.5已经放出，做了安全处理，保证`onSupportInvisible()`会在`onCreateView()`后执行

但是官方的`onHiddenChanged()`没办法，在该场景下，它还是会在`onCreateView()`前执行
