### ISSUE TITLE
RunTimeException

### ISSUE THREAD

**Issue by rogerou** [YoKeyword/Fragmentation#41]
<pre><code>
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.everytime/com.everytime.ui.main.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean android.support.v4.app.BackStackRecord.mAddToBackStack' on a null object reference
</pre></code>

好像是只要在App上次是崩溃的情况下，再进去就会发生这样的情况，卸载了再重装也会这样 ，很奇怪。
<pre><code>
if (savedInstanceState == null) {
            loadRootFragment(R.id.container, TopicFragment.newInstance());
        }

</pre></code>
这里是调用代码的地方

**Comment by YoKeyword** [comment]
@rogerou  使用前务必浏览下wiki，以及尽量阅读下我的简书的2篇文章；再根据Demo配合参考用法，3个demo基本概括了目前所有的架构场景；
你的问题可以详细描述吗？  摸不到头脑啊~

**Comment by rogerou** [comment]
@YoKeyword 我也觉得很奇怪，就是App是崩溃情况下结束的再次启动就会这样，我现在去看看Wiki

**Comment by rogerou** [comment]
@YoKeyword  然后现在又可以了，有点怀疑和InstanRun有关系

**Comment by YoKeyword** [comment]
@rogerou  额，InstanRun是有不少BUG的~
你先解决app崩溃问题哈~

**Comment by rogerou** [comment]
@YoKeyword  谢拉
