### ISSUE TITLE
网络加载过程中点击切换会嵌套原来的，加载完了原来的才消失怎么解决？

### ISSUE THREAD

**Issue by xbdcc** [YoKeyword/Fragmentation#411]
private void initView() {
        mTaskFragment = new TaskFragment();
        mDefectFragment = new DefectFragment();
        mSettingFragment = new SettingFragment();
        loadMultipleRootFragment(R.id.content, 0, mTaskFragment, mDefectFragment, mSettingFragment);
        showTab(INDEX_TASK);
        mNavigation.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);
        mNavigation.setSelectedItemId(R.id.navigation_task);
    }

    /**
     * 点击显示对应Tab
     * @param index
     */
    private void showTab(int index) {
        showFragment = index;
        showHideFragment(getTargetFragment(showFragment), getTargetFragment(hideFragment));
        hideFragment = showFragment;
    }

用的loadMultipleRootFragment加载所有进去，然后点击tab隐藏原来显示当前。mTaskFragment下拉刷新进行网络操作，同时点击DefectFragment的tab，DefectFragment布局中会显示原来的布局里的东西，直到原来加载完了才消失。求解如何解，以使用最新fragmentation依赖1.0.4试了一样。

**Comment by YoKeyword** [comment]
@xbdcc 下拉刷新控件是否用的`SwipeRefreshLayout`？  并且Fragment的根布局是`SwipeRefreshLayout`

**Comment by xbdcc** [comment]
是的，Fragment下拉刷新根布局都是SwipeRefreshLayout

**Comment by YoKeyword** [comment]
根布局不可以是`SwipeRefreshLayout `，用`FrameLayout`包一下吧， 这个是`SwipeRefreshLayout`的BUG
