### ISSUE TITLE
有没有人针对这个框架做了MVP模式的封装？

### ISSUE THREAD

**Issue by zs1973** [YoKeyword/Fragmentation#412]
有没有人针对这个框架做了MVP模式的封装？求交流
QQ:305562245

**Comment by zs1973** [comment]
想了解一下不继承SupportActivity的委托+代理的实现模式

**Comment by YoKeyword** [comment]
在自己的BaseActivity/Fragment里 实现＋委托实现即可， 最简单的方式是把SupportActivity/Fragment里的代码copy到自己的Base里 :)

**Comment by zs1973** [comment]
大大  需要写自己的代理么

**Comment by YoKeyword** [comment]
@zs1973  直接拷贝过来即可， 建议继承自己的`BaseActivity/Fragment`再impl `ISupportActivity/Fragment`， 避免混合在自己的`Base`里直接拷贝
