### ISSUE TITLE
百度地图在fragment下的问题

### ISSUE THREAD

**Issue by AIlll** [YoKeyword/Fragmentation#413]
普通的单页面，为什么无法显示地图呢 ，简单的地图都不能显示，  还有就是从0.7版本升级到现在的最新版1.0.5  会有什么冲突吗

**Comment by AIlll** [comment]
地图已经解决，是我自己的问题，再次请问下低版本升级到高版本会不会出现冲突，因为以前是别人写的，一直没升级

**Comment by YoKeyword** [comment]
@AIlll  一些方法的作用域有所改变， 改变不大， 建议升级，优化、Fix了一些问题

可以看下[1.0改动](https://github.com/YoKeyword/Fragmentation/wiki) 以及[历史版本改动](https://github.com/YoKeyword/Fragmentation/wiki/9%E3%80%81%E5%8E%86%E5%8F%B2%E7%89%88%E6%9C%AC%E4%BB%8B%E7%BB%8D)

**Comment by AIlll** [comment]
@YoKeyword 地图是能显示了   但是还有个问题   我是主Acticity下有四个同级fragment，地图是放在第二个fragment下，启动app，除了默认显示的第一个fragment，其他三个都是空白，但是按下home键再进入app，又都正常了，地图也能显示，这是什么原因

**Comment by YoKeyword** [comment]
建议先把版本升上来，0.7版本略老，难以排查问题....

**Comment by AIlll** [comment]
@YoKeyword 现在已经升级了  是这种情况

**Comment by YoKeyword** [comment]
你的场景和第二个或第三个Demo类似， 你可以先看下Demo，如果没啥思路，再把相关代码贴一下

**Comment by AIlll** [comment]
@YoKeyword  fragment配合databinding使用会有什么问题吗

**Comment by YoKeyword** [comment]
和databinding是兼容的 :)

**Comment by AIlll** [comment]
@YoKeyword   真的头疼，同级fragment显示就是不正常，第一个能显示但是也不正常，其他几个就没法显示，找了好久不知道原因在哪  ，要不断重启APP才有可能正常。也看了demo，就那么几句代码，错不了，以前这样用也没出过这个问题，唉

**Comment by YoKeyword** [comment]
加载Fragment处的代码贴出来看下

**Comment by AIlll** [comment]
@YoKeyword `loadMultipleRootFragment(R.id.fl_main_content, MAP, mFragments[HOME], mFragments[MAP], mFragments[MONITOR],
                mFragments[USER]);

mFragments[HOME] = new HomeFragment();
        mFragments[MAP] = new MapFragment();
        List<Station> stations = CacheManager.getStations();
        if (stations != null && stations.size() == 1) {
            mFragments[MONITOR] = StationFragment.Instance(stations.get(0), true);
        } else {
            mFragments[MONITOR] = new MonitorFragment();
        }
        mFragments[USER] = new UserFragment();

navigationController = mBind.homeTab.material()
                .addItem(R.mipmap.home, "主页", 0xFF57ace6)
                .addItem(R.mipmap.ic_map_unselect, "地图", 0xFF57ace6)
                .addItem(R.mipmap.monitor, "监控", 0xFF57ace6)
                .addItem(R.mipmap.user, "我的", 0xFF57ace6)
                .build();
        navigationController.addTabItemSelectedListener(new OnTabItemSelectedListener() {
            @Override
            public void onSelected(int index, int old) {
                KLog.d("选择了：" + index + "---old:" + old);
                if (index == 3) {
                    boolean b = checkUser();
                    if (b) {
                        Intent intent = new Intent(MainActivity.this, LoginActivity.class);
                        startActivity(intent);
                    }
                }
                showHideFragment(mFragments[index], mFragments[old]);
            }

            @Override
            public void onRepeat(int i) {
            }
        });

`

**Comment by YoKeyword** [comment]
@AIlll  简化下场景排查下吧：  把加载的几个Fragment换成只显示一个TextView的简化Fragment，然后试试

**Comment by LonelyMushroom** [comment]
@AIlll 我怀疑是你的4个fragment可能有点瑕疵,如果可以的话你先按照作者的方法看看是不是可行,然后再一步步删除代码,进行排除.如果还是不行的话就将fragment的代码贴下出来

**Comment by YoKeyword** [comment]
@AIlll 可以尝试升级到v1.1.0， `commit`机制优化了
