### ISSUE TITLE
How to parsing value between fragment??

### ISSUE THREAD

**Issue by Widiyanto** [YoKeyword/Fragmentation#414]

**Comment by YoKeyword** [comment]
You can pass datas when you `start` Fragment:
````java
TargetFragment target = new TargetFragment();
Bundle args = new Bundle();
args.putXX()...
target.setArguments(args);

start(target);
````

##
If both Fragments have been loaded, you can directly call the fragment's public methods:
````java
TargetFragment target = (TargetFragment)findFragment(TragetFragment.class);
target.doSth(xxx);
````
Or you can associate them with an Activity: [Developers](https://developer.android.com/training/basics/fragments/communicating.html)

Or use the "EventBus" to abstract these communications.
