### ISSUE TITLE
发现一个大BUG,描述如下

### ISSUE THREAD

**Issue by douya40** [YoKeyword/Fragmentation#415]
二个页面进行跳转，在第一个页面的点击事件，在第二个页面的与第一个页面相同位置点击依然有效

**Comment by YoKeyword** [comment]
什么版本呢？  Demo上是否能复现

**Comment by Mrxxy** [comment]
同样的问题，我也遇到了，版本是v1.0.5，具体描述就是 必现A->B，在B界面空白处点击会触发A界面的点击事件，跳到C，升级到v1.0.6后问题依然存在，之前使用版本v0.10.1未出现此问题

**Comment by YoKeyword** [comment]
@Mrxxy  1.0之前是通过在`onActivityCreated()`里设置 `getView().setClickable(true)`来避免穿透点击的

1.0之后依旧会设置 `getView().setClickable(true)`，但是在Fragment入场结束后会复原Clickable，这样的话理论上 除非上个Fragment的离场动画时间 大于 下一个Fragment的转场动画时间， 否则应该不会出现穿透点击问题。

你的场景下是否 A的popExitAnim时间 > B的enterAnim时间呢？  我这边Demo无法复现，如果确实还有问题，还是不能把clickable复原...

**Comment by Mrxxy** [comment]
使用动画为默认动画，之前一直使用0.10.1和0.10.3，前几天升级到1.0.5后才发现这个问题

**Comment by YoKeyword** [comment]
@Mrxxy  好的，感谢反馈， 如果和动画时间没关系的话，可能存在兼容问题， 下个版本还是不复原clickable了

**Comment by Mrxxy** [comment]
@YoKeyword 十分感谢

**Comment by YoKeyword** [comment]
@douya40 @Mrxxy    v1.0.7已放出，不再复原clickable   🍺  :)

**Comment by douya40** [comment]
好的。我们测试下。谢谢

**Comment by Mrxxy** [comment]
已修复 @YoKeyword
