### ISSUE TITLE
知乎Demo中ZhihuThirdFragment使用懒加载会造成ShopFragment的onSupportVisible被调用2次

### ISSUE THREAD

**Issue by harv** [YoKeyword/Fragmentation#416]
首次打开ZhihuThirdFragment时，懒加载ShopFragment。ZhihuThirdFragment 会在https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/helper/internal/VisibleDelegate.java#L157 调用ShopFragment的dispatchSupportVisible，同时由于此时ShopFragment自己也会调用dispatchSupportVisible，造成onSupportVisible被调用2次。

而没有使用懒加载的ZhihuSecondFragment，没有这个问题。

**Comment by YoKeyword** [comment]
@harv  是的，确实嵌套场景下第一次visible时调用了2次， 明天我处理下   :)

**Comment by YoKeyword** [comment]
v1.0.6 已Fix，`dispatchSupportVisible()`内部的调用顺序问题  🍺  :)
