### ISSUE TITLE
Translate the demo app to english

### ISSUE THREAD

**Issue by fvermeulen** [YoKeyword/Fragmentation#417]
Hey it would be cool to have the demo app in english. I think that would help the app and a lot of users of your library.

**Comment by YoKeyword** [comment]
Yeah, i will soon translate the Demo to English  :)

**Comment by fvermeulen** [comment]
cool thanks for that

only a quick question and i don't want to bomb you with issues, but i couldn't find a solution till now.

i want to switch to another fragment from my viewmodel. I use databinding mvvm. Can you help me?

**Comment by YoKeyword** [comment]
In [googlesamples](https://github.com/googlesamples/android-architecture-components), another fragment is switched by View(Fragment): 
 [RepoFragment](https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/ui/repo/RepoFragment.java#L94) and [NavigationController](https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/ui/common/NavigationController.java#L57)

**Comment by YoKeyword** [comment]
🍺🍺   [Translate the demo app to english](https://github.com/YoKeyword/Fragmentation/commit/b1bad2f71b65d5b571209d2db459dde33e925605)
