### ISSUE TITLE
应用从后台从新进入界面之后，Fragment就切换失败。

### ISSUE THREAD

**Issue by zs1973** [YoKeyword/Fragmentation#418]
把应用切换到后台，基本上半个小时多吧，然后重新进入界面，切换Fragment就不行了

**Comment by YoKeyword** [comment]
看描述，应该是没有做 页面内强杀后重启的 相关处理，你可以页面App被强杀的场景：
打开 开发者选项 -> 不保留活动 ，  进入App 退出到桌面，再回到App即可模拟强杀 恢复的场景， 再调试

**Comment by zs1973** [comment]
对的  不保留后台活动 可以复现这个场景

**Comment by zs1973** [comment]
我看您的demo里面没有做强杀处理呀，demo被强杀之后进去还可以用

**Comment by zs1973** [comment]
看了下demo 搞好了。  不过demo里面那种方式，如果从一个Act的Fragment 里面跳转到另一个Act，然后再返回第一个Act，第一个Act里面的Fragment会被重新绘制。

**Comment by YoKeyword** [comment]
@zs1973   被杀恢复时 肯定会重新绘制的， 毕竟资源都被回收，再恢复时要重新走生命周期的 :)
