### ISSUE TITLE
ViewPager跳页切换Fragment可见被调用三次

### ISSUE THREAD

**Issue by yuanrunmao** [YoKeyword/Fragmentation#419]
Fragmentation版本为 1.0.6，ViewPager 和 Fragment 配合使用，mOffscreenPageLimit 为默认值1。

当 ViewPager 一页接着一页切换时，onSupportVisible() 被回调一次；

但跳页切换时，例如当前在第 1 页，直接跳到第 6 页，再跳回第 1 页，第 1 页的 onSupportVisible() 方法被调用了三次。

**Comment by YoKeyword** [comment]
@yuanrunmao 
我这边在`FragmentPagerAdapter`,`FragmentStatePagerAdapter`下模拟描述场景， 没有复现，调用次数均为1次。

**Comment by yuanrunmao** [comment]
@YoKeyword 
很抱歉，我没有描述清楚。我这边的场景是每个 ViewPager 页面（fragment）由若干个子fragment组成

刚才打印了调用次数，发现父页面（fragment）的 onSupportVisible() 的调用次数只有一次，但是子 fragment 却调用了两次（标题的“三次”应有误 Orz...）

我是看到子 fragment 里的 view 报 NPE 才发现这个问题的，可能是可见性分发了两次，第一次 view 还没准备好

**Comment by YoKeyword** [comment]
@yuanrunmao 
我猜是因为 你在`onCreateView()`／`onViewCreated()`/`onActivityCreated()`里加载的子Fragment，因为FragmentPagerAdapter的销毁视图机制，导致第1个切到第6个时，第一个Fragment的视图销毁了，再切回时又创建视图（再次回调`onCreateView()`...），从而重复加载了子Fragment

解决方式：
````java
if (findChildFragment(ChildFragment.class) == null) {  // 避免重复加载子Fragment
      loadRootFragment(R.id.container, ChildFragment.newInstance());
}
````

**Comment by yuanrunmao** [comment]
@YoKeyword 
的确如此。问题已解决，感谢！
