### ISSUE TITLE
请问有没有给DialogFragment之类的其他fragment做Fragmentation适配的计划？

### ISSUE THREAD

**Issue by woniu0936** [YoKeyword/Fragmentation#420]

**Comment by YoKeyword** [comment]
@woniu0936  v1.0开始 不需要强制继承 `SupportFragment`， 可以通过 `impl ISupportFragment`+ `FragmentDelegate` 实现自己的“SupportFragment”

所以其它Fragment均可以通过实现＋委托来兼容  :)

**Comment by woniu0936** [comment]
这个厉害了，大赞，我还在使用0.10.6回头抽时间切过来

**Comment by woniu0936** [comment]
@YoKeyword 能给个邮箱吗？自己封装SupportDialogFragment的时候出现问题了，想发给您，麻烦您指教一下

**Comment by woniu0936** [comment]
@YoKeyword 能给个邮箱吗？自己封装SupportDialogFragment的时候出现问题了，想发给您，麻烦您指教一下

**Comment by YoKeyword** [comment]
@woniu0936  yokeyword@gmail.com

**Comment by woniu0936** [comment]
已发送，非常非常感谢 @YoKeyword
