### ISSUE TITLE
question：在你的wiki里面看到一段话，想请教一下

### ISSUE THREAD

**Issue by woniu0936** [YoKeyword/Fragmentation#421]
在你的wiki里面看到这段话：`使用1.0后，在onCreate(),onCreateView()中加载Fragment的事务（比如loadRootFragment()），请迁移到onViewCreated()或者onActivityCreated()中, 对于Fragment中执行start()，如果你需要在onCreateXX()创建类生命周期内执行，请放到enquequeAction()里执行`
但是我发现你的demo里面，MainActivity中loadMultipleRootFragment()还是在onCreate方法里面调用

**Comment by YoKeyword** [comment]
在Activity里，是可以放在`onCreate()`里的 （因为也没有`onViewCreated()` `onActivityCreated()`...）

wiki的这句意思是，在Fragment中， `load`应该放在`onViewCreated()`或者`onActivityCreated()`中， 因为在这2个生命周期时，Fragment确保是已经绑定了View

**Comment by woniu0936** [comment]
哦，明白了，谢谢指教
