### ISSUE TITLE
如果想在子类的fragment调用onresume（）

### ISSUE THREAD

**Issue by 18094159215** [YoKeyword/Fragmentation#425]
@Override
    public void onResume() {
        super.onResume();
        getVisibleDelegate().onResume();
        dispatchFragmentLifecycle(LifecycleHelper.LIFECYLCE_ONRESUME, null, false);
    }
dispatchFragmentLifecycle是private没法调用

**Comment by YoKeyword** [comment]
v1.0以后， 移除了FragmentLifecycle，因为从25.2.0开始，google的v4包提供了它自己的FragmentLifecycle

所以如果是实现自己的SupportFragment， 建议直接拷贝项目里的SupportFragment即可
