### ISSUE TITLE
loadMultipleRootFragment十个子fragment，进入的时候会卡顿

### ISSUE THREAD

**Issue by zhangz89** [YoKeyword/Fragmentation#427]
loadMultipleRootFragment十个子fragment，每个子fragment目前onCreateView没有任何耗时的操作；请问如何优化卡顿的现象？

**Comment by YoKeyword** [comment]
如果你是从1个Fragment `start`到这个有10个子Fragment的Fragment，可以把`loadMultipleRootFragment()` 放到`onEnterAnimationEnd()`方法中加载，这样会在动画结束后加载这10个Fragment，这样视觉上不会卡顿

另外对于10个量级的子Fragment要考虑下`ViewPager`+`FragmentPagerAdapter`或 `FragmentTabHost`是否会更适合该场景

**Comment by zhangz89** [comment]
@YoKeyword ，另一个问题，无论第一次，还是showHideFragment；getTopChildFragment() 为啥每次都是最后一个fragment？

**Comment by YoKeyword** [comment]
Fragment是非常严格的栈， 不管你是`loadMultipleRootFragment()`还是通过 `ViewPager`+`FragmentPageAdapter`加载的Fragment，  都是根据加载顺序一个个进栈的

`showHideFragment()`仅仅是切换Fragment的显示与否，并不会进栈、出栈，所以不影响栈内的顺序， 所以`getTopChildFragment()`总是返回最后进栈的那个Fragment

可以通过悬浮球的栈视图来观察下，看下就明白了
