### ISSUE TITLE
关于新版1.0不强制继承SupportActivity/SupportFragment的咨询

### ISSUE THREAD

**Issue by Kira8CC** [YoKeyword/Fragmentation#428]
新版不需要强制继承SupportActivity/SupportFragment了，可以通过implements ISupportActivity/Fragment ＋ Delegate形式自己实现自定义SupportActivity/Fragment (可拷贝SupportActivity/Fragment到自己的Support里)

关于这种委托我不是很明白具体怎么操作，是否在demo里也有这种的写法

**Comment by YoKeyword** [comment]
#401 ， demo可见`MySuportActvity`/ `MySupportFragment`（这两个实现里 有部分方法没有实现），完整版直接拷贝`SupportActivity/Fragment`
