### ISSUE TITLE
I want control processRestoreInstanceState on SupportFragmentDelegate.class   

### ISSUE THREAD

**Issue by yangjieK** [YoKeyword/Fragmentation#429]
Hi YoKey 

I need control processRestore,but how to do it?

 /**
     * 内存重启后,是否让Fragmentation帮你恢复子Fragment状态
     */
    protected boolean restoreInstanceState() {
        return false;
    }

**Comment by yangjieK** [comment]
This new version 1.07  cant be controled it

**Comment by YoKeyword** [comment]
Hi @yangjieK 

Why you need to control this method?

I think it does not need to be controlled.  Fragment state should be restored at recovery time.

If you want to `beginTransaction` after recovery, you can continue in `onCreateView()`, `onViewCreated()` or `onActivityCreated()`
