### ISSUE TITLE
打开新页面直接使用DialogFragment这种方式怎么样？

### ISSUE THREAD

**Issue by WinsonTse** [YoKeyword/Fragmentation#43]
发现你的代码在打开一个新fragment(要加入回退栈)的时候，会隐藏from这个fragment，这样做可以避免过度绘制。用DialogFragment的show方法的话，也能做到同样的效果，不用隐藏from的fragment了，而且不用指定containerId，只要把style指定成全屏的就行。不知道这种方式会不会更好。

**Comment by YoKeyword** [comment]
hide还一个原因是为了在回退时可以触发onHiddenChanged()回调方法；
对于DialogFragment本意是Dialog的替代，而不是Fragment的替代，使用场景还是很大不同的  :)

**Comment by WinsonTse** [comment]
好的，谢谢解答。反正我觉得这个比新版知乎好，知乎的很多地方都没hide，造成一些页面过度绘制很严重。我也一直想用单activity的方式，但是在网上很少见到相关的文章。

**Comment by YoKeyword** [comment]
嗯啊，单AC坑比较多，需要不少耐心～

**Comment by WinsonTse** [comment]
额-_-才发现from fragment在打开to fragment如果加入回退栈了，并且hide了from，这时候pop掉to fragment，from直接就显示出来了。。。好神奇的体验

**Comment by YoKeyword** [comment]
哈哈，感兴趣可以看看源码～

**Comment by WinsonTse** [comment]
```
case OP_HIDE: {
                    Fragment f = op.fragment;
                    f.mNextAnim = popEnterAnim;
                    mManager.showFragment(f,
                            FragmentManagerImpl.reverseTransit(transition), transitionStyle);
                } break;
```
看了源码，果然，在回退的时候，如果状态是hide，会调用showFragment，不错的用法。哈哈
