### ISSUE TITLE
BottomBar 的一些疑问

### ISSUE THREAD

**Issue by LoveqLRC** [YoKeyword/Fragmentation#430]
最近在看`Demo`程序，有几点疑问
1. `BottomBar` 为什么要再嵌套一个`mTabLayout`。
2. `BottomBar`如果不绑定`listener`就不能切换`tab`图标的颜色了，这样感觉不是很好。
3. 关于`onSaveInstanceState`和`onRestoreInstanceState`的处理，第一次见，有相关`blog`或资料吗？想知道这样设计的原因。

**Comment by 42plus** [comment]
`mTabLayout = new LinearLayout(context);` 用生成个linearlayout ori=horiz做底部tab使用，这样命名棒棒哒
onsave存和onrestore取 都是android.view.view的  应该是存取当前选择的哪个“tab”

**Comment by LoveqLRC** [comment]
问题`BottomBar `本来就是`LinearLayout`了，完全没有必要再嵌套一个`mTabLayout `

**Comment by YoKeyword** [comment]
1、`mTabLayout`是个历史原因，一开始`BottomBar`上方有一条线， 后来移除了，但`mTabLayout`也忘了删～啊哈哈

2、`BottomBar`是个随手写的切换控件，不是很严谨，可以自己拓展

3、`onSaveInstanceState`和`onRestoreInstanceState`的设计是为了： 在页面/app 资源不足时，被系统释放掉后， 再次回到该页面时保证数据完整性的设计

以BottomBar分析，正如 @42plus 所说，   在释放前，系统回调`onSaveInstanceState`，此时保存下 当前切换的tab的index， 在恢复时回调`onRestoreInstanceState`，从里面取出这个index，进而恢复到释放前的状态

**Comment by LoveqLRC** [comment]
@YoKeyword  Thank you for your answer
