### ISSUE TITLE
切换Tab 被ondestory 没有恢复 要viewpage.setOffscreenPageLimit才行，但是栈里显示fragment依然存在

### ISSUE THREAD

**Issue by 42plus** [YoKeyword/Fragmentation#431]
Tab切换时被ondestory，再切换会ondestory的fragment也没有恢复，要viewpage.setOffscreenPageLimit才行，但是栈里显示fragment依然存在。
   当我把我写的tab从父到子都放在demo里运行，就可以做到当tab切换，debug时也发现确实进了fragment的ondestory了，但是切换回去依然还是当时状态。这个是怎么做到……我是不是漏掉了什么东西？

**Comment by 42plus** [comment]
我看了以前的issues 我是在父fragment的oncreateview里加载的，用的是
`        SupportFragment firstFragment = findFragment(TixingFragment.class);
        if (firstFragment == null) {
            mfragments[0] = TixingFragment.newInstance();
            mfragments[1] = LuyinFragment.newInstance();
            mfragments[2] = ToupiaoFragment.newInstance();
            loadMultipleRootFragment(R.id.viewPager, 0,
                    (ISupportFragment) mfragments[0],
                    (ISupportFragment)mfragments[1],
                    (ISupportFragment)mfragments[2]);
        } else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题
            // 这里我们需要拿到mFragments的引用,也可以通过getChildFragmentManager.findFragmentByTag自行进行判断查找(效率更高些),用下面的方法查找更方便些
            mfragments[0] = firstFragment;
            mfragments[1] = findFragment(LuyinFragment.class);
            mfragments[2] = findFragment(ToupiaoFragment.class);
        }`
在相应的继承自FragmentPagerAdapter里，geiitem里再次switch(position)
这样的话，我在stack里面看到的双份的子fragment（血崩）
不管我是否loadrootmutil，viewpage都会在固定的tab下对固定距离外的fragment进行ondestory（这个机制一直存在，这个我懂），但是为什么您的demo即使ondestory还健壮的蹦跳中而我的就又要重载……

**Comment by YoKeyword** [comment]
FragmentPagerAdapter的机制是 `OffscreenPageLimit`外的Fragment离开时会调用`onDestroyView`，回来时调用`onCreateView()`， 但是`onCreate()`,`onDestroy()`仅在初始化和出栈时调用

如果你想在切换回来时，UI依然保持离开前的状态，只需要把数据作为全局变量，`onViewCreated()`/`onActivityCreated()`这么处理即可：
````java
onActivityCreated(){
   if(mData==null){
       // 请求数据
   }
   ui.bind(mData);
}
````

**Comment by 42plus** [comment]
但是，例如在demo的wechat里面，WechatSecondTabFragment的子FirstPageFragment做了recyclayout，也是在oncreateview里面做完的，只是你在Mainfragment里使用onActivityCreated，loadroot了他们的父类，就这样是不是就ok了。
