### ISSUE TITLE
除了demo这个模块之外的三个模块的依赖是不是写错了

### ISSUE THREAD

**Issue by FrankKwok** [YoKeyword/Fragmentation#432]
`provided 'com.android.support:appcompat-v7:25.4.0'`,没有25.4.0这个版本吧

**Comment by LoveqLRC** [comment]
same issue  [404](https://github.com/YoKeyword/Fragmentation/issues/404)

**Comment by FrankKwok** [comment]
明白了，没有翻墙的原因
