### ISSUE TITLE
锁屏，onSupportVisible，onSupportInvisible重复调用一次

### ISSUE THREAD

**Issue by zhangz89** [YoKeyword/Fragmentation#433]
在fragment中执行锁屏操作：
onSupportInvisible、onSupportVisible、onSupportInvisible
为什么会多回调了一次onSupportVisible和onSupportInvisible？

**Comment by YoKeyword** [comment]
什么机型、 ROM、安卓版本？

我手机几台机器锁屏情况下 调用正常

**Comment by zhangz89** [comment]
找到原因了，因为装了360应用，有自定义锁屏，这种情况下，在插着usb线的时候，activity锁屏会触发onpause-》onresume-》onpause，真流氓
