### ISSUE TITLE
该库0.9.5版本会和ButterKnife8.7.0版本产生冲突

### ISSUE THREAD

**Issue by w1570187062** [YoKeyword/Fragmentation#436]
会导致部分Fragment中OnClick事件无法响应，fragment内容显示异常,最新版本不会

**Comment by YoKeyword** [comment]
应该和防抖动处理机制不同有关，1.0以下最高版本是v0.10.7，可以直接升级 

建议升级到最新版v1.0.7，有一些机制改动可以参考[wiki](https://github.com/YoKeyword/Fragmentation/wiki)
