### ISSUE TITLE
1.0.7里,通过 fragment 的onCreateFragmentAnimator方法重写自定义动画无效

### ISSUE THREAD

**Issue by heiyeliuying** [YoKeyword/Fragmentation#437]
1.0.7里,通过 fragment 的onCreateFragmentAnimator方法重写自定义动画无效

**Comment by YoKeyword** [comment]
该Fragment怎么被加载的，`ViewPager`和`loadMultipleRootFragment`以及`loadRootFragment(第4参数为false)`加载Fragment时，Fragment是没有动画的

**Comment by heiyeliuying** [comment]
在 Activity 中通过 loadRootFragment(R.id.fragment_id,fragment)加载的.动画一直执行的是 Activity 中复写onCreateFragmentAnimator时指定的动画.

**Comment by YoKeyword** [comment]
`loadRootFragment(R.id.fragment_id,fragment)` 2个参数的该方法，默认load的Fragment是不带任何动画的，如果你想显示动画，使用下面的方法代替:
````java
loadRootFragment(id, fragment, true//是否加入回退栈, true//是否允许显示动画)
````
