### ISSUE TITLE
你好，在你的新版本中是在Activity中创建一开始就创建几个fragment，能否不这么做？

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#44]
@YoKeyword 
你好，在你的新版本中是在Activity中创建一开始就创建几个fragment，能否不这么做？
你的思路是一进Activity就通过以下代码创建了几个fragment

`if (savedInstanceState == null) {
            mFragments[FIRST] = MultiFirstFragment.newInstance();
            mFragments[SECOND] = MultiSecondFragment.newInstance();
            mFragments[THIRD] = MultiThirdFragment.newInstance();
            mFragments[FOURTH] = MultiFourthFragment.newInstance();

            loadMultipleRootFragment(R.id.fl_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD],
                    mFragments[FOURTH]);
        } else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题

            // 这里我们需要拿到mFragments的引用,也可以通过getSupportFragmentManager.getFragments()自行进行判断查找(效率更高些),用下面的方法查找更方便些
            mFragments[FIRST] = findFragment(MultiFirstFragment.class);
            mFragments[SECOND] = findFragment(MultiSecondFragment.class);
            mFragments[THIRD] = findFragment(MultiThirdFragment.class);
            mFragments[FOURTH] = findFragment(MultiFourthFragment.class);
        }`

然后根据底部的BottomBar来切换，通过代码`showHideFragment(mFragments[position], mFragments[prePosition]);`来隐藏或者显示以达到切换fragment的目的。你这里是做了Fragment的恢复。
但是假如这里面的每个fragment都有网络请求，那样就会一进Activity就都访问了网络，这样不是很好，有的fragment可能用户压根就不会点击进去，所以白白耗费了流量。是否有个比较好的法子，懒加载的方式，用户点击了才底部相应的icon才创建这个fragment。这样会好一些。不知道是不是我的理解有错误，或者你还有一套新的方案我不知道的。支持你

**Comment by n272367953** [comment]
围观一下



272367953@qq.com
 
发件人： leguang
发送时间： 2016-07-20 11:15
收件人： YoKeyword/Fragmentation
主题： [YoKeyword/Fragmentation] 你好，在你的新版本中是在Activity中创建一开始就创建几个fragment，能否不这么做？ (#44)
@YoKeyword 
你好，在你的新版本中是在Activity中创建一开始就创建几个fragment，能否不这么做？
你的思路是一进Activity就通过以下代码创建了几个fragment
` if (savedInstanceState == null) {
mFragments[FIRST] = MultiFirstFragment.newInstance();
mFragments[SECOND] = MultiSecondFragment.newInstance();
mFragments[THIRD] = MultiThirdFragment.newInstance();
mFragments[FOURTH] = MultiFourthFragment.newInstance();
        loadMultipleRootFragment(R.id.fl_container, FIRST,
                mFragments[FIRST],
                mFragments[SECOND],
                mFragments[THIRD],
                mFragments[FOURTH]);
    } else {
        // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题
        // 这里我们需要拿到mFragments的引用,也可以通过getSupportFragmentManager.getFragments()自行进行判断查找(效率更高些),用下面的方法查找更方便些
        mFragments[FIRST] = findFragment(MultiFirstFragment.class);
        mFragments[SECOND] = findFragment(MultiSecondFragment.class);
        mFragments[THIRD] = findFragment(MultiThirdFragment.class);
        mFragments[FOURTH] = findFragment(MultiFourthFragment.class);
    }`

然后根据底部的BottomBar来切换，通过代码showHideFragment(mFragments[position], mFragments[prePosition]);来隐藏或者显示以达到切换fragment的。你这里是做了Fragment的恢复。
但是假如这里面的每个fragment都有网络请求，那样就会一进Activity就都访问了网络，这样不是很好，有的fragment可能用户压根就不会点击进去，所以白白耗费了流量。是否有个比较好的法子，懒加载的方式，用户点击了才底部相应的icon才创建这个fragment。这样会好一些。不知道是不是我的理解有错误，或者你还有一套新的方案我不知道的。支持你

**Comment by wjehovah** [comment]
wiki 第7条 有写

**Comment by YoKeyword** [comment]
Demo中的其实就是懒加载方式，一开始仅仅把Fragment加载进来，并不做计算请求等操作，最有第一次切换到对应TabFragment时，才开始加载请求数据；详情见BaseLazyMainFragment这个懒加载基类

当然你也可以在切换时才加载Fragment，不过体验上要差点~

另外你可以查看下最新的Demo，有个仿QQ交互的Demo，它和仿知乎的Demo都是懒加载  :)

**Comment by leguang** [comment]
@YoKeyword
嗯，你更新了代码，我看的是之前的版本的代码，所以没看到懒加载这部分。这样也可以
但是我有个问题，现在你的懒加载实现是以一个标记mInited配合onHiddenChanged(boolean hidden) 函数来实现的，为什么不直接在showHideFragment()这个函数里做判断，如果创建过这个fragment就直接隐藏显示，没有创建过就创建fragment再显示呢？也就是说
`  if (savedInstanceState == null) {
            mFragments[FIRST] = WechatFirstTabFragment.newInstance();
            mFragments[SECOND] = WechatSecondTabFragment.newInstance();
            mFragments[THIRD] = WechatThirdTabFragment.newInstance();

            loadMultipleRootFragment(R.id.fl_tab_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD]);
        } else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题
            // 这里我们需要拿到mFragments的引用,也可以通过getChildFragmentManager.getFragments()自行进行判断查找(效率更高些),用下面的方法查找更方便些
            mFragments[FIRST] = findChildFragment(WechatFirstTabFragment.class);
            mFragments[SECOND] = findChildFragment(WechatSecondTabFragment.class);
            mFragments[THIRD] = findChildFragment(WechatThirdTabFragment.class);
        }`
这段代码中你为什么一开始就要先把这些fragment全部实例化一下呢？是不是因为你现在框架的恢复机制使然？还是说考虑到可能有的人就喜欢一开始就全部实例化，那样后面点击就里面有数据了
哈哈，我问题有点多，先后都问了你好几个问题了，都不好意思了

**Comment by YoKeyword** [comment]
@leguang 懒加载的代码其实一直都有～
你说的方案当然也是可以的，这个库没做任何限制，你可以随意使用任意方案哈～

你说的方案是完全靠动态加载init，而我的做法是先把Fragment都加载进来，然后通过懒加载init数据。
你说的方案：优点：一开始占用资源更低  ／ 缺点：第一次切换tab会感觉到延迟
我用的方案：优点：Fragment栈内顺序可控，切换tab瞬间完成  ／缺点：一开始内存资源比较大一些（一开始就加载进来了，但仅仅是Fragment本身，数据啥的都没初始化，其实占用的资源很低），还有就是代码判断写起来，略繁琐

两种其实差不多的，看你喜好哈～
不要客气，互相交流嘛～

**Comment by leguang** [comment]
@YoKeyword
明白，试过了，可行，你可以关闭这个问题了
谢谢你回复^_^
