### ISSUE TITLE
请问loadMultipleRootFragment的适用场景是什么?

### ISSUE THREAD

**Issue by ljf1172361058** [YoKeyword/Fragmentation#440]
如果我只是在一个activity中跳转到某个fragment去还需要用这个方法么？还是说可以直接用start()方法呢？

**Comment by yygutn** [comment]
首先得loadroot，然后你就可以随心所欲了

**Comment by YoKeyword** [comment]
是的，先使用`loadRootFragment(containerId, fragment)`

Fragment有一个栈层级的概念，因为你加载第一个Fragment，即开辟一个新栈，故根Fragment需要使用`load`， 如果以后想再这个层级的栈内再添加Fragment，使用`start()`   可以理解为`load`是操作子Fragment，`start()`是操作兄弟Fragment

**Comment by ljf1172361058** [comment]
谢谢各位的解答
