### ISSUE TITLE
空白界面出现

### ISSUE THREAD

**Issue by zxp0505** [YoKeyword/Fragmentation#444]
你好 有时候会出现空白界面  有 A B CD四个fragment 进行 showHideFragment（）进行操作展示  从A-->A1 （loadRootFragment(R.id.container, A1);）操作加载A1   A1界面 有viewpager内部有A2fragment 在A2界面start（）操作进入A3界面 A3界面有个recycleview  和返回按钮  这样操作 快速点击recycleview但还没刷新完成界面 迅速点击返回按钮 调用  ((SupportFragment) getParentFragment()).popChild(); 有时候会出现空白   使用版本  compile 'me.yokeyword:fragmentation:0.10.3'

**Comment by YoKeyword** [comment]
你的场景和 知乎Demo第二个Tab一样，  可以试试Demo， 如果没问题先排查写法问题，如果都没问题可以考虑升级到最新版 :)

**Comment by lqxue** [comment]
@YoKeyword MainFragment上面有一个AFragment,我在AFragment执行popTo(MainFragment::class.java, false),会出现白屏,但是当MianFragment上面有AFragment和BFragment的时候,在BFragment里面执行popTo(MainFragment::class.java, false),就不会出现白屏,是什么原因

**Comment by YoKeyword** [comment]
@lqxue 空白问题多是因为栈层级有问题引起的， 栈视图贴下，说明哪个是A 哪个是B

**Comment by weijun501** [comment]
我页面fragment跳转一直使用EventBus.getDefault().post(new StartBrotherEvent(fragment))，这样子跳转，没有使用start，或者popTo，从A-->跳转B出现B页面空白。 @YoKeyword

**Comment by YoKeyword** [comment]
@weijun501 
贴下栈视图并说明下

另外空白场景时一定要看下Logcat，是否有Error级别的Log的提示，若有 贴出来

**Comment by weijun501** [comment]
@YoKeyword 
Fragmentation: Please beginTransaction in onPostResume() after the Activity returns!  打印了这样的一个日志，这个问题不是每次都会出现，时有时无。

**Comment by YoKeyword** [comment]
@weijun501  这个提示的话，是因为你`start`的这个Fragment的宿主Activity处于不可见状态（即：已经调用了`onPause`）

我猜测： 你的Task里有2个Activity，内部有同一个Fragment，在监听同一个Event，当某个页面发送了这个Event， 这两个Fragment同时触发并执行`start`，但是因为某个Activity内的该Fragment处于不可见状态，所以导致报了这个错， 同时界面空白

解决方式很多： 
1、使用 `getParentFragment()`等方式拿到要`start`的那层栈的Fragment直接`start`

2、或使用接口方式回调`start`，这样作用域是Activity，保证安全

3、或定义一个Activity作用域的EventBus：
````java
Activity: 
acEventBus = new EventBus();
public EventBus getActivityEventBus(){
    return acEventBus;
}
````
其内的Fragment通过该EventBus去注册：` getActivityEventBus.register(this);`

4、如果是因为手抖启动了2个相同Activity，做下防手抖处理即可

**Comment by shaddockzy** [comment]
主界面一个Activity 里面加载4个 Fragent  A B C D   A中又持有a1,a2（fragment）   在mainActivity中用LoadMutil这个方法加载A B C D 使用hideshow方法切换 偶发刚进入界面时快速切换（A B 中有比较多的网络操作）后面的 B C D Fragment不显示出现白屏 的情况。没发现报错信息。

**Comment by YoKeyword** [comment]
@shaddockzy 栈视图贴一下，同时调试下BCD的关键生命周期回调情况

**Comment by shaddockzy** [comment]
@YoKeyword 为了和您的Fragmentions对应，我特地采用了和你的Simple一样的栈结构  就是和 weichatSimple一一致的结构，差别在于我的第一个fragment含有两个Tab.a1,a2; 并且我有四个Fragment   我打开APP快速切换时会产生 Fragment B C D 不显示的问题。 和一楼出现的现象类似。此时如果把app挂起 (点击home) 会产生界面出现。

**Comment by shaddockzy** [comment]
@YoKeyword APP 长时间在后台挂起后打开 更容易产生Ｂ C D 不显示的问题。 A 是一直显示的  hideAndShow的时刻A和其持有的a1,a2常在  BCD 空白。

**Comment by YoKeyword** [comment]
@shaddockzy 无法复现，你的空白问题和他们应该是不一样

感觉可能和写法有关系，如果可以把你的Demo贴一下，gist或者上传到Github都可以

**Comment by honglei92** [comment]
> @lqxue @zxp0505
> 空白问题多是因为栈层级有问题引起的，记住一个原则： 不要在未加入回退栈的层级内去`start()`其它Fragment， 比如ViewPager、`loadMultiRootFragment()`、`FragmentTabHost`内部的Fragment不可以直接`start`，这种情况下其内的栈应该保持干净，如果想启动其它Fragment，应该由它们的父Fragment或子Fragment去`start`
> 
> 另外栈视图贴下，说明哪个是A 哪个是B

help me a lot
