### ISSUE TITLE
你好，关于加载Fragment的根布局是LinearLayout的时候，侧滑会出现奇异现象。

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#446]
你好，关于加载Fragment的根布局是LinearLayout的时候，侧滑会出现奇异现象。
如果根布局是FramLayout，那Fragment的侧滑退出都很完美，但是如果是LinearLayout，那Fragment的侧滑会瞬间消失，再次侧滑就会出异常。但是根布局用其他的布局，比如RelativeLayout什么的都很好。
我已经让自己的项目+阁下的项目分别在华为和小米手机上都试过了，会出现这种情况。
这个你可以考虑在文档中注明一下，避免不必要的 踩坑。

**Comment by YoKeyword** [comment]
@leguang  我这边没有复现，测试机一直有华为和小米

Demo中很多可以侧滑的Fragment都是`LinearLayout`作为其根布局的，比如微信Demo中可以滑动的Fragment几乎都是`LinearLayout`，滑动起来表现正常

**Comment by leguang** [comment]
@YoKeyword
 抱歉，可能我描述的有歧义，我想说的是加载这个fragment的容器布局，不是指fragment的视图根布局。

比如你把你Demo中的demo_flow中的MainActivity的布局文件activity_main.xml中的
```
   <FrameLayout
        android:id="@+id/fl_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".demo_flow.MainActivity">
    </FrameLayout>
````
改成LinearLayout

你再试试这个demo_flow中的SwipeBackFragment，侧滑一下就可以看到了。

再比如，你把demo_wechat中的MainActivity的布局文件activity_main.xml中的
```
<FrameLayout
    android:id="@+id/fl_container"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
```
改成LinearLayout

你再试试这个demo_wechat中的MsgFragment，侧滑一下就可以看到了。

**Comment by YoKeyword** [comment]
额... 当然会这样 ，侧翻返回时2个Fragment都会同时出现，而因为是LinearLayout所以布局位置肯定会异常， 这个完全没有办法...

为什么会有 LinearLayout作为容器的需求....  我觉得不需要在文档上说明，因为除非及其特别的情况才会用LinearLayout作为容器 :)

**Comment by zhukai123** [comment]
呃,真的会有这个坑. 找了一下午没找到原因~  确实应该小小提示一下,感谢作者
