### ISSUE TITLE
有几个问题求大神帮忙解决下

### ISSUE THREAD

**Issue by Greathfs** [YoKeyword/Fragmentation#447]
1.应用采用的是Activity+多Fragment形式
   Activity左上角有个Logo，点击后需要清空回退栈，并且显示HomeFragment，也就是一开始加载的RootFragment，这个怎么实现呢？
2.Fragmnet切换动画的问题
  Fragment切换动画时，两个Fragment之间会有一部分重叠，我使用的是左右切换的哪个动画，这个怎么处理比较好呢

**Comment by YoKeyword** [comment]
1、在RootFragment的那层栈里，任意Fragment： `popTo(RootFragment.class ,false)`即可

2、重叠应该是进栈的Fragment根布局是透明的background，改为不透明即可

**Comment by Greathfs** [comment]
大神 那个重叠的问题有什么好点的解决办法吗？我的Fragment背景要用Activity的背景，所以我的Fragment背景都是透明的

**Comment by YoKeyword** [comment]
在SupportActivity中全局设置其Fragments的背景色:
````java
getSupportDelegate().setDefaultFragmentBackground(android.R.color.white);
````

**Comment by Greathfs** [comment]
/**
 * Created by HFS on 2017/7/13.
 * 无MVP的Activity基类
 */

public abstract class SimpleActivity extends SupportActivity {

    protected SupportActivity mContext;
    private Unbinder mUnBinder;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(getLayoutId());
        mUnBinder = ButterKnife.bind(this);
        getSupportDelegate().setDefaultFragmentBackground(android.R.color.white);
        mContext = this;
        onViewCreated();
        App.getInstance().addActivity(this);
        initViewAndData();

    }

    protected void onViewCreated() {

    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        App.getInstance().removeActivity(this);
        mUnBinder.unbind();
    }

    protected void showMsg(String msg) {
        Toast.makeText(this, msg, Toast.LENGTH_SHORT).show();
    }

    protected abstract int getLayoutId();

    protected abstract void initViewAndData();
}

大佬 我设置了，切换动画时还是有重叠，感觉Fragment的背景还是透明的

**Comment by YoKeyword** [comment]
你是否对Fragment的根布局直接设置了`background`，如果是的话`setDefaultFragmentBackground `不会起作用的

内部是： 如果你没有对根布局设置`background`，会取`setDefaultFragmentBackground`设置的颜色，如果没有调用该方法，那么会取Activity theme的 `windowBackground`

对应源码：
````java
public void setBackground(View view) {
        if (...
                view.getBackground() != null) {
            return;
        }

        int defaultBg = mSupport.getSupportDelegate().getDefaultFragmentBackground();
        if (defaultBg == 0) {
            int background = getWindowBackground();  // 取theme的windowbackground
            view.setBackgroundResource(background);
        } else {
            view.setBackgroundResource(defaultBg);
        }
    }
````

**Comment by Greathfs** [comment]
我把Fragment的background去掉了，但是这样的话我Fragment背景就变成白色的了，就不会显示Activity的背景图了，有点懵。。。

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/28650432-859b2adc-72ae-11e7-9bc9-accc1aa4c26d.png)

**Comment by YoKeyword** [comment]
`setDefaultFragmentBackground (背景图资源id)`
