### ISSUE TITLE
popToChild如何实现动画效果?

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#45]
popToChild如何实现动画效果?

**Comment by YoKeyword** [comment]
@weiyf 在commit https://github.com/YoKeyword/Fragmentation/commit/6986939c8aa0836ea10fe3b48445fd025991ea16 之前的版本中，popTo系列方法是有动画的，实现代码见：https://github.com/YoKeyword/Fragmentation/commit/6986939c8aa0836ea10fe3b48445fd025991ea16#diff-9f17012d9b91c3b6766b2f6aee9be8b2L471 

考虑到2点，移除了该方法：
1、如果使用popToX(xx, afterRunnable) 即出栈后立即进行执行其他事物方法，库并不知道你是否需要立刻跳转其他Fragment，如果是立即跳转其他Fragment，此时为保证显示正确，此处不应该有出栈动画；因为这个不确定因素，索性移除了所有popToX的动画

2、第二点也是最重要的，如果popToX的Fragment数量过多，比如20多个，会明显感觉到明显出栈的速度降低了很多

综上，移除了动画效果，如果你实在需要这个功能，你可以参考上面的commit

**Comment by weiyf** [comment]
好的, 谢谢您的解答.
