### ISSUE TITLE
在线等，挺急的

### ISSUE THREAD

**Issue by caopeng000** [YoKeyword/Fragmentation#454]
在看您仿微信交互Demo中，把一些初始化根布局的操作都放到了MainFragment里面去。其实也可以放到MainActivity去的，为什么要这么设计代码呢。有什么优点吗

**Comment by YoKeyword** [comment]
不要在未加入回退栈的层级内去start()其它Fragment， 比如`ViewPager`、`loadMultiRootFragment()`、`FragmentTabHost`内部的Fragment不可以直接start，这种情况下其内的栈应该保持干净，如果想启动其它Fragment，应该由它们的父Fragment或子Fragment去`start`

这是一种嵌套Fragment的科学栈设计，微信Demo采用的是父Fragment去start，这样更简单； 用子Fragment去start的是知乎Demo，明显知乎Demo嵌套会复杂些
