### ISSUE TITLE
跳转动画问题

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#455]
之前用的1.0X以下的，准备升级到1.0.8 最新，发现一些问题：
一
1，loadRootFragment(R.id.fl_container, ExamApplyMainFragment.newInstance(gradeUnitId));
2，ExamApplyMainFragment重写onCreateFragmentAnimator   return new DefaultNoAnimator();
3，start到下个fragment,ExamApplyMainFragment会出现window的背景，而本身的内容不可见。
二。
loadRootFragment(R.id.fl_container, ExamApplyMainFragment.newInstance(gradeUnitId),false,true);//第四个参数,ExamApplyMainFragment的onEnterAnimationEnd不执行。。。是这样的？？

三。先前的_mActivity是SupportActivity,现在都改成FragmentActivity了，我Fragment操作了Toolbar,((AppCompatActivity)_mActivity).setSupportActionBar(toolbar);
 ActionBar actionBar=((AppCompatActivity)_mActivity).getSupportActionBar();
现在要进行强制转换了？ 或者 实现自己的基类？

**Comment by YoKeyword** [comment]
@hcadoid 
一、 `ExamApplyMainFragment`的popExitAnim你应该设置了无动画， 1.0之前是库在无动画时专门加了个300ms的时长， 但是在一些特殊情况这个设定会有问题，所以移除了这个设定

v1.0后，使用者需要自己设置一个和下个Fragment进栈动画时长相同时间的动画（可以参考[pop_exit_no_anim](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/res/anim/pop_exit_no_anim.xml)的写法）  这样也更合理，毕竟既然设置了无动画，那么下个Fragment进栈时，上个Fragment自然就立即hide了

二、这是个BUG，稍后修复

三、是的，因为v1.0不需要强制继承`SupportActivity`，为了更通用，默认的`_mActivity`确实是`FragmentActivity`类型， 你可以强转或者在自己的基类里，设置自己`AppCompatActivity `类型的mActivity

**Comment by YoKeyword** [comment]
v1.0.9 已修复 问题2
