### ISSUE TITLE
知乎跳转  ((SupportFragment) getParentFragment()).start(DetailFragment.newInstance(mAdapter.getItem(position).getTitle()));

### ISSUE THREAD

**Issue by caopeng000** [YoKeyword/Fragmentation#456]
场景就是，Viewpager里的一个fragment点击listview的条目跳转到下个fragment。

我这使用的也是你这样的  ((SupportFragment) getParentFragment()).start，为什么我的getParentFragment是空的

如果在已关闭的issues下继续提问能看到吗

**Comment by YoKeyword** [comment]
`getParentFragment`是空可能是：
1、确实没有父Fragment
2、此时当前Fragment还没被加载，没有被加载的情况下`getParentFragment`是空

你可以通过`getFragmentManager.getFragments()`来查看栈内Fragment的情况

已关闭的issues继续提问是 可以看到的

**Comment by caopeng000** [comment]
在我这种场景下你的就能找到父Fragment（知乎的FirstPagerFragment）   
mAdapter.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(int position, View view, RecyclerView.ViewHolder vh) {
                // 这里的DetailFragment在flow包里
                // 这里是父Fragment启动,要注意 栈层级
                ((SupportFragment) getParentFragment()).start(DetailFragment.newInstance(mAdapter.getItem(position).getTitle()));
            }
        });

**Comment by caopeng000** [comment]
解决了谢谢
