### ISSUE TITLE
搞不懂onLazyInitView 懒加载怎么比onCreateView跑得还快？

### ISSUE THREAD

**Issue by limjiregister** [YoKeyword/Fragmentation#457]
搞不懂onLazyInitView 懒加载怎么比onCreateView跑得还快？我在onLazyInitView的方法给viewPager添加适配器，竟然，没有上面onCreateView请求的数据没穿过来。

**Comment by YoKeyword** [comment]
> ### Issues
> Following information can help us to resolve the issue faster.
>* Library version
>* Support-v4 version
>* Logs
>* Screenshots

Fragmentation版本多少

**Comment by limjiregister** [comment]
compile 'me.yokeyword:fragmentation:1.0.8'


`	public static RootFragment newInstance() {

		return new RootFragment();

	}

	@Nullable
	@Override
	public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

		View view = inflater.inflate(R.layout.root_layout, container, false);

		initView(view);
		loadDatas();

		return view;
	}`


我是在MainActivity 加载rootFragment的，然后，在rootFragment简单加载数据布局文件，然后，在onLazyInitView 配置 数据的话，就直接空指针。我就想知道，是不是这个方法运行比较快，不能在这类配置数据。

`	@Override
	public void onLazyInitView(@Nullable Bundle savedInstanceState) {
		super.onLazyInitView(savedInstanceState);

		viewPager.setAdapter(new MyViewPagerAdapter(getChildFragmentManager(), tabNames));

		String[] datas = new String[titles.size()];
		tabLayout.setViewPager(viewPager, titles.toArray(datas));


	}`

**Comment by YoKeyword** [comment]
`onLazyInitView ()`应该要比`onCreateView()`慢的， 你的场景：
MainActivity `load` RootFragment，  然后发现RootFragment的`onLazyInitView`比较快？

空指针排查下是否是View没有正确被`findViewById`

**Comment by limjiregister** [comment]
不会是findViewById 这个。都 在我的适配器，是没有数据造成的空指针。而且，onCreateView这个方法里面的东西，都不运行，因为onLazyInitView已经挂了。说明，onLazyInitView比onCreateView 快吧。现在，我没用onLazyInitView这个方法了。


我把 
viewPager.setAdapter(new MyViewPagerAdapter(getChildFragmentManager(), tabNames));

	String[] datas = new String[titles.size()];
	tabLayout.setViewPager(viewPager, titles.toArray(datas));

这些放到loadData那个方法下，就正常。

**Comment by YoKeyword** [comment]
从源码上，你的这种情况不可能 `onLazyInitView`比`onCreateView`快

再确定你的场景就是简单的：MainActivity加载RootFragment，出问题的是RootFragment的`onLazyInitView`？

**Comment by limjiregister** [comment]
可以大概看看吧，http://git.oschina.net/angularjsDemo/FragmentationDemo

**Comment by YoKeyword** [comment]
`TabName tabNames;`  空指针是因为这个tabNames为null

这个对象是`loadDatas()`返回的，是个耗时异步任务，`onCreateView `后执行了`onLazyInitView `，但是`loadDatas()`还没请求到结果，所以tabNames为null， 最终报错的应该是[这个地方](http://git.oschina.net/angularjsDemo/FragmentationDemo/blob/master/app/src/main/java/com/fragment/fragmentationdemo/adapter/MyViewPagerAdapter.java#L31)

**Comment by limjiregister** [comment]
是这样的。但是懒加载，还是很快啊。按照这样说，正常不应该在这里配置数据吧？我看你的例子，因为是 写好的数据。所以，问题不大....

**Comment by YoKeyword** [comment]
懒加载你可能理解错了， 懒加载代表： 用户第一次可见这个Fragment时会触发这个方法， 比如ViewPager加载了2个Fragment， 第二个Fragment会一进来就走`onCreateView`， 不走`onLazyInitView`， 只有当你第一次切换到第二个Fragment时才会触发`onLazyInitView`

在你的场景RootFragment被加载后，立即对用户可见了，所以就直接触发`onLazyInitView`

**Comment by limjiregister** [comment]
好的。我理解理解。用了你找个项目后，感觉使用fragment做界面思路清晰了些。只是，每个fragment都有个newInstance（）的方法，例子没有传参的？！

**Comment by YoKeyword** [comment]
`ModifyDetailFragment`等等 里是有传参的， 这方面正常使用即可，  多使用栈视图，来让栈的概念更清晰 :)
