### ISSUE TITLE
 FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#458]
场景描述：
MainFragment中有4个TAB，在其中一个TAB下的fragment中startActivityA，
ActivityA中的onCreate中发送Event
 new Handler().post(new Runnable() {
            @Override
            public void run() {
                EventBus.getDefault().post(new MainPopEvent());
            }
        });
MainFragment中接受：（防止事务失败做了判断）
  @Subscribe(threadMode = ThreadMode.MAIN)
    public void onPopPageEvent(MainPopEvent event) {
        if(isResumed()){
            popTo(MainFragment.class,false);
        }else{
            mNeedPopFragment=true;
        }
    }
 @Override
    public void onResume() {
        super.onResume();
        //处理事务提交问题
        transactionFragment();
        。。。
    }
  private void transactionFragment() {
        if(mNeedPopFragment){//销毁Main上的所有Fragment事务
            mNeedPopFragment=false;
            popTo(MainFragment.class,false);
        }
    }
在ActivityA 销毁的时候 MainFragment的onReume执行了popTo,导致。。 以前的版本都是这样写的，没有问题，升级后出现。

**Comment by YoKeyword** [comment]
Fragment的机制，在生命周期内如果执行事务，不允许`fm.executePendingTransactions()`，所以在当前版本要避免这个异常，你需要把`transactionFragment()`post到Handler队列里去

1.0后为了 防止多点触控问题，对所有事务`commit`后都`executePendingTransactions()`，现在来看有点得不偿失，晚上我会放出新版本，改回1.0之前的方式

**Comment by hcadoid** [comment]
好的 ，  之前看你简书上处理Can not perform this action after onSaveInstanceState的坑是这样建议写的，之后项目里也有多处是这样操作的。

**Comment by YoKeyword** [comment]
v1.0.9已经取消`executePendingTransactions()`机制，同时做了判断，能更好的避免该异常

这个之前没问题是因为v4-25.3.0之前是可以在生命周期内执行事务的，但是25.3.0后，google在**每个**生命周期里都禁止直接`executePendingTransactions`，😂:
````java
 // FragmentManager.java:
 public void dispatchResume() {
        mStateSaved = false;
        mExecutingActions = true;  // true...
        moveToState(Fragment.RESUMED, false); // 这里调用 onResume()
        mExecutingActions = false;
}
````
