### ISSUE TITLE
怎么给某一个fragment加指定动画？

### ISSUE THREAD

**Issue by xiongke15117937934** [YoKeyword/Fragmentation#459]
1，主activity`  new DefaultHorizontalAnimator();`
2.某一个fragment设置`new DefaultNoAnimator()` 但是我想要fragment退出没有动画，进入时正常的 可是始终退出都有水平动画？

**Comment by LonelyMushroom** [comment]
@xiongke15117937934 https://github.com/YoKeyword/Fragmentation/wiki/5.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-%E8%BD%AC%E5%9C%BA%E5%8A%A8%E7%94%BB

**Comment by xiongke15117937934** [comment]
还是老样子啊，写了也不行。

**Comment by YoKeyword** [comment]
启动目标Fragment时做下处理:
````java
// 目标Fragment 无退出动画 
FragmentAnimator targetFA = new DefaultHorizontalAnimator(); 
targetFA.setExit(R.anim.anim_none);
 fragment.setFragmentAnimator(targetFA);
  // 当前Fragment的popEnter动画也需要设置无动画，否则目标Fragment退出时，当前Fragment依然会有动画 FragmentAnimator fA = getFragmentAnimator();
 fA.setPopEnter(R.anim.anim_none); 
setFragmentAnimator(fA);  
start(fragment);

// 复原当前Fragment的popEnter动画 （如果有需要的话）
@Override public void onHiddenChanged(boolean hidden) {
     super.onHiddenChanged(hidden);
     if (!hidden && getFragmentAnimator().getPopEnter() == R.anim.anim_none) {
         setFragmentAnimator(new DefaultHorizontalAnimator());
     } 
}
````

anim_none.xml:
````xml
<?xml version="1.0" encoding="utf-8"?>
 <translate xmlns:android="http://schemas.android.com/apk/res/android"
      android:duration="0"> 
</translate>
````

**Comment by xiongke15117937934** [comment]
最后我是这么写的，可是我觉得太麻烦了，有没有简单的写法。
子fragment跳转地方`   FragmentAnimator targetFA = new DefaultNoAnimator();
                    pictureFragment.setFragmentAnimator(targetFA);
                    mActivity.setFragmentAnimator(targetFA);
                    mActivity.start(pictureFragment);`
目标fragment
```
 @Override
    public void onDestroyView() {
        super.onDestroyView();
        mActivity.setFragmentAnimator(new DefaultHorizontalAnimator());
    }
```

**Comment by xiongke15117937934** [comment]
我是对最外层activity的framLayout做的替换，不子的fragment

**Comment by YoKeyword** [comment]
没太好的方法， 不用这个库的话用官方实现你的需求的话也麻烦... 
不过你的写法，会让目标进入时也无动画，好像不符合你的需求，更细致的控制某个动画可以参考我提供的写法

不过我相信你的这个需求是低频，特殊情况下才有这种需求，所以麻烦就麻烦些吧 :)
