### ISSUE TITLE
back from other activity,fragment activity show slow

### ISSUE THREAD

**Issue by yuchangfu** [YoKeyword/Fragmentation#46]
A activity is a SupportActivity,A open an Activity B,B is a normal Activity.
When at B press back key,A show slow（probably 3 sec).
I debug all A activity function onResume() cost 3~5ms, onPostResum() cost 300~400ms
Does any one know what cause this problem?

**Comment by YoKeyword** [comment]
@yuchangfu 😅  大家说中文吧～ 我英语说起来要捉急...

这个和库没啥关系哈，建议你检查下是否做了什么异常耗时操作，我在实际项目中从其它Activity返回SupportActivity时，一切正常，和普通Activity一样，你可以从库的源码看到，并没有做什么操作～

**Comment by yuchangfu** [comment]
我也没看到哪儿有影响，现象是A 页面的onPostResume完成很久了，A 页面才显示，感觉哪儿有延时似的

**Comment by YoKeyword** [comment]
A页面超级复杂吗或者有超级多的Fragment吗？
你可以看下那个流式的demo，抽屉菜单有个SwipeBackActivity的菜单，是打开一个新Activity，你在打开那个Activity前打开100个循环Fragment，然后返回，我这边看到的是非常流畅。

或者你在回退到A前，A已经被系统强杀了？
