### ISSUE TITLE
一个问题，源自于懒加载，位置：VisibleDelegate

### ISSUE THREAD

**Issue by HouXiaohu** [YoKeyword/Fragmentation#460]
153行代码如下：
   if (visible) {
            mSupportF.onSupportVisible();  // 154

            if (mIsFirstVisible) {
                mIsFirstVisible = false;
                mSupportF.onLazyInitView(mSaveInstanceState);  //158
            }
//160
        } else {
            mSupportF.onSupportInvisible();
        }
其中，154的位置，我这边存在这样一个问题，我的initData 方法是提供给用户初始化view的，然后我将它放在了onLazyInitView 方法中，之后我再onSupportVisible 中，去调用view的一些方法，发现view都没有初始化，找了半天，发现这段代码和我理想中不太一样。154  行代码可以放在 160 行，作者您觉得呢？

**Comment by LonelyMushroom** [comment]
@HouXiaohu initData 你可以放在oncreateView或者onviewcreate里面

**Comment by HouXiaohu** [comment]
@LonelyMushroom  感谢你的回复，我这边是一个viewpager嵌套的几个fragment，如您所说，如果我放在onViewCreate 里面或者onCreateView中，我不就没有懒加载了吗？

**Comment by HouXiaohu** [comment]
@LonelyMushroom  我只是觉得，如果位置互换一下，这样也安全，像我原以为生命周期是这样：
onLazyinitView()  -> onSupportVisible    但是最后发现是  onSupportVisible -> onLazyInitView()

**Comment by HouXiaohu** [comment]
@LonelyMushroom 我有一些这样的场景，别的fragment更改了一个数据，需要切换回这个fragment时及时展示出来，但是如果不是替换形式开启的fragment，onResume 不会调用，那我该如何展示？ 然后我就依靠了这个方法

**Comment by YoKeyword** [comment]
我认为 调用顺序不换会更好，原因可以见 #383 

你的需求我认为这样的写法会更好：
````java
    boolean mFirstVisible = true;

    @Override
    public void onSupportVisible() {
        super.onSupportVisible();
        if (mFirstVisible) {
            mFirstVisible = false;
            // 第一次可见，即等同于 onLazyInitView()
            // 初始化View等逻辑
        } else {
           // 后续可见时触发，在此放心调用view的方法
        }
    }

````

**Comment by LonelyMushroom** [comment]
@HouXiaohu 作者已经给了方法了,我确实没考虑到viewpage这一方面,疏忽了.

**Comment by HouXiaohu** [comment]
@LonelyMushroom  @YoKeyword  感谢，没看见之前的提问
