### ISSUE TITLE
栈视图查看问题

### ISSUE THREAD

**Issue by caopeng000** [YoKeyword/Fragmentation#462]
为什么我的栈视图没有层级概念呢。每次开启新的界面都是和他的父fragment是相同层级。而不是那种点击的层级

**Comment by LonelyMushroom** [comment]
@caopeng000 可是,你至少贴张图片和代码块吧....  你是不是在父fgstart的

**Comment by caopeng000** [comment]
之前用的Viewpager的是supportManager，替换成childManager就没问题了。已经解决了
