### ISSUE TITLE
为什么要新增ZhihuFirstFragment，ZhihuFourthFragment这些没有实际意义的fragment呢

### ISSUE THREAD

**Issue by caopeng000** [YoKeyword/Fragmentation#463]
为什么要新增ZhihuFirstFragment，ZhihuFourthFragment这些没有实际意义的fragment呢？
是因为要更好的看下栈层级结构吗？

**Comment by LonelyMushroom** [comment]
更清晰的展示栈视图,但是其实我也没这么弄  hahhhhh,等作者回复吧.也有可能是用于start fg,因为start fg 是要有fg在回退栈里面,如果是viewpage 你不弄个父fg 可能会有空白的bug,这只是我的理解.参考这个https://github.com/YoKeyword/Fragmentation/issues/444

**Comment by YoKeyword** [comment]
[看下这篇wiki](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager#%E5%90%8C%E7%BA%A7%E6%9C%AA%E5%8A%A0%E5%85%A5%E5%9B%9E%E9%80%80%E6%A0%88%E7%9A%84fragments)

同级未加入回退栈的Fragment避免直接`start`，要么由父Fragment去`start`（参考微信Demo的MainFragment），  要么是子Fragment（参考知乎Demo的ZhihuFirstFragment）
，
这样才是正确的栈结构，一般情况下我们会使用父Fragment去`start`，即微信Demo的栈设计是更普遍的

PS： 多看下wiki和Demo，思考下，Fragment的关键就是栈层级
