### ISSUE TITLE
Fragment 之间传递 Listener

### ISSUE THREAD

**Issue by zhangchaojiong** [YoKeyword/Fragmentation#467]
Fragment A 跳转到 Fragment B，使用方法：start(SupportFragment fragment)，那么如何在A 传递一个接口到B 去？

**Comment by zhangchaojiong** [comment]
如果使用
```
SupportFragment  fragmentB = FragmentB.newInstance（）； fragmentB .setListenter(new XX()); 
  start(fragmentB ) ;
```
有什么问题么？

**Comment by LonelyMushroom** [comment]
有点不大理解,没见过传监听的,一般来说都是B有一个监听,然后你A启动后调用这个监听.可能是我孤陋寡闻没听过传递监听的说法,你能说下你的需求吗?

**Comment by zhangchaojiong** [comment]
就是A启动B，那么当B有数据变化的时候。回调通知A。 这时候A就必须传递一个监听到B去？难道不是这样子？

**Comment by YoKeyword** [comment]
@zhangchaojiong  
````java
SupportFragment  fragmentB = FragmentB.newInstance（）； 
fragmentB .setListenter(new XX()); 
start(fragmentB ) ;
````

这样是不可以的， 因为当BFragment被强杀恢复后，Listener将会丢失

有两种方式可以实现你的需求：
1、通过Activity实现接口方式，[这样](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_flow/ui/fragment/account/LoginFragment.java#L39)
> 缺点：层级较多时，维护起来麻烦

2、EventBus，通讯非常简单
> 缺点：太解耦

3、通过其共同父Fragment的`onAttachFragment(child)`来传递处理, v4-24.0.0+ 支持该方法

**Comment by zhangchaojiong** [comment]
这样子的话fragmentA 也有可能别强杀掉，接收不到B 的回调！我的需求场景是 A 跳转到一个 图片查看的界面B，在B的界面可以有删除动作。必须要回调，去更换A界面的notify 列表信息。如果通过B界面的setResult 去 做的话。返回到A界面。我得做一下A 的notify动作。导致不能在B界面做一个 缩放图片的动作回到A。

我想到一个好方法 吧B 做成DialogFragment。这样子 B的生成周期就会和A 绑定在一块。共存亡。

**Comment by YoKeyword** [comment]
@zhangchaojiong   DialogFragment并不是解决这个问题的关键

首先，毫无疑问，最简单实现你的需求是EventBus

1和3的方案取决于你A和B的父亲是谁，如果是Activity，那么用1， 如果是Fragment那么用3

另外注意` onAttachFragment（child）`是子Fragment `attach`时回调父Fragment的

处理传递Listener的关键是：在被杀恢复后，是否可以重新绑定上监听

**Comment by zhangchaojiong** [comment]
@YoKeyword 讲解的非常棒！
我这边还是有点疑问要请教你。例如前面的使用EventBus 的话，如若 fragment A 被系统回收了。就算fragment B发出信息了（解决listener问题）。fragment A也是接收不到的。这个怎么办。我想让它俩 要回收的话就一起回收。 

我起初以为使用DialogFragment是 可以和宿主fragment 相同的生命周期，共存亡。结果发现不是。其实dialogFragment 也是做为一个兄弟fragment压入栈内的。

最后的结果是不是只能通过setResult 解决这个问题。。请问大神还有没有其他的指点？

私人问题 fragment的一些问题：
1.parentFragment 被回收。它的childFrament 一定会被系统回收吗？

非常感谢

**Comment by YoKeyword** [comment]
回收的最小单位是Activity， 即若Activity内的某个Fragment被回收了，那么其他Fragment一定会被回收！

恢复时 恢复顺序为：Activity -> Activity子Fragment -> 子Fragment的子Fragment
栈内恢复顺序为： 栈底Fragment -> 栈顶Fragment
