### ISSUE TITLE
   findFragment() 的定义问题

### ISSUE THREAD

**Issue by zhangchaojiong** [YoKeyword/Fragmentation#468]
在activity A 中   findFragment() ，能找到Activity B里面的fragment吗？（当然 activity B 里面的Fragment 也是继承 SupportFragment）

**Comment by YoKeyword** [comment]
@zhangchaojiong  当然不能...   不仅Activity之间独立， 不同栈层级的Fragment都是独立的

如： AFragment有子FragmentAA， AFragment的同级FragmentB有子FragmentBB，AA和BB是互相独立的，即使他们实例化自同一个Fragment类

**Comment by zhangchaojiong** [comment]
了解！
如： AFragment有子FragmentAA， AFragment的同级FragmentB有子FragmentBB，AA和BB是互相独立的，即使他们实例化自同一个Fragment类

那这样子话在 FragmentAA 找不到  FragmentBB 的引用是吧！ 只有通过在FragmentAA 
 中 getParentFragment().findFragment(FragmentB.class).findChildFragment(FragmentBB.class) 才能找到？

**Comment by YoKeyword** [comment]
@zhangchaojiong   对的， 所以这同时也就导致不同栈内的通信比较麻烦
