### ISSUE TITLE
我从0.10.9升级到1.0.9,怎么查看fragment栈视图没了?怎么都调不出来

### ISSUE THREAD

**Issue by colder112** [YoKeyword/Fragmentation#470]
我从0.10.9升级到1.0.9,怎么查看fragment栈视图没了?怎么都调不出来

**Comment by LonelyMushroom** [comment]
请参考这个issues https://github.com/YoKeyword/Fragmentation/issues/464

**Comment by colder112** [comment]
嗯,解决了,谢谢
