### ISSUE TITLE
侧滑退出Activity的时候下面那个activity是黑色的，等侧滑结束后才显示出来

### ISSUE THREAD

**Issue by xwc520** [YoKeyword/Fragmentation#471]

**Comment by YoKeyword** [comment]
Activity主题是否设置了透明：
````xml
<item name="android:windowIsTranslucent">true</item>
````

**Comment by xwc520** [comment]
加上这个之后好了但是activity的启动动画就变了，必须要加这个吗？

**Comment by YoKeyword** [comment]
库中是借鉴SwipeBackLayout的实现机制， 必须要加～

Activity动画应该是不受影响的， 可以排查下原因

**Comment by cheng1992zhen** [comment]
<style name="StartStyle" parent="AppTheme.Base">
        <item name="android:windowBackground">@mipmap/bg_splash</item>
    </style>

加上<item name="android:windowIsTranslucent">true</item>我的闪屏页就变成透明了，闪屏不见了

**Comment by cheng1992zhen** [comment]
我解决了  我给闪屏页单独加了  <style name="StartStyle" parent="AppTheme.Base">
        <item name="android:windowBackground">@drawable/splash</item>
        <item name="android:windowIsTranslucent">false</item>
    </style>


然后AppTheme.Base依旧设置 <item name="android:windowIsTranslucent">true</item>就可以了
