### ISSUE TITLE
升级到1.0+ 了，API可以承诺稳定么？ Roadmap 是如何的？

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#472]
作为`Fragmentation` 的老用户了，从`0.7.8`用到`0.10.5`，再上来看到，已经去到了`1.0.9`。

期间， api 多次不兼容变更进行重大修改调整。

作为一个 修复和增强官方 API 的库， api 变更有时候是必须的，但是能不能考虑一个稳定的升级方案。
兼容现有旧版本的 api，慢慢淘汰，而不是一个版本出来就要调整相关的代码。

所以，如题：升级到1.0+ 了，API可以承诺稳定么？ Roadmap 是如何的？

**Comment by YoKeyword** [comment]
@zhenian 
既然是v1.0，肯定是可以保证API的绝对稳定，保证向下兼容的；

Roadmap：
* 保证API的简洁
* 优化动画相关
* 更强的拓展性、兼容性

其实只有2个版本有不兼容API改动：

#### v0.8, 该版本的不兼容API主要是拼写错误、提供更安全的替代方法
>1、修正了`setFragmentResult(bundle)`的拼写错误问题。（原：`setFramgentResult`）；
>2、`isSupportHidden()`方法不再暴露给外部使用，懒加载请直接用`onLazyInitView(Bundle saveInstanceState)`；
>3、SupportActivity的`onBackPressed()`标记为final，不可被继承，但是可以调用，请使用`onBackPressedSupport()`代替；

#### v1.0： 简化API
>1、移除库中的`FragmentLifecycleCallbacks`（自support-25.1.0开始，官方新增了FragmentLifecycleCallbacks）
>2、移除`replaceLoadRootFragment()`，统一使用`loadRootFragment()`
>3、增加`extraTransaction()`处理自定义tag、添加SharedElements、不加入回退栈的相关事务（替代原`transaction()`）

其中：
第1条：是因为官方自25.1.0开始 提供了 `FragmentLifecycleCallbacks`，所以库为了简洁，将该系列API移除

第2条：为了简化思想，移除不必要了`replaceLoadRootFragment()`

第3条：`transaction()`是v0.8时新增的API，但是设计的并不理想，故用`extraTransaction()`替代，这一条也是改变最大的，但是多数用户可能不会用到这项API

**Comment by zhenian** [comment]
@YoKeyword 秒回。 Thank you.
