### ISSUE TITLE
能否在当前 fragment pop()或者侧滑关闭的时候,给出一个回调函数?

### ISSUE THREAD

**Issue by heiyeliuying** [YoKeyword/Fragmentation#474]
首先非常感谢作者的这个库,极大的减轻了我管理 fragment 的工作量.

我的问题是,能否在当前 fragment pop()或者侧滑关闭的时候,给出一个回调函数?虽然 pop 时,会调用前一个 Fragment的 onhidden 方法.但是对于一些场景确实不适用.例如我的电商项目中,调用详情页的地方非常多,没有办法每一个调用详情页的同事,都对 onhidden 进行一个二次处理. 如果我的详情页被关闭时,能有个回调让我保存一些状态或参数,那就好了.

其实,我认为这正是本框架需要强化的地方. 

该库简化了Fragment 的状态管理,但是并没有给出用户保持一些状态的契机(指的是并未在本 Fragment 里给出回调接口,让开发者保持一些简单的状态). 对于任何的开发场景而言,一般都会有此需求.

现在使用该库的同时,虽然可以使用一些折中的方式来实现,但是却让该库的便利性大打折扣了.

谢谢!

**Comment by YoKeyword** [comment]
@heiyeliuying  感谢建议！

我对你的需求没有特别理解， 保存状态和参数指的是？

目前库有提供同级相邻Fragment的回调方式，可以使用`startForResult()`启动详情页，在`onFragmentResult()`中处理详情页关闭时的回调

Fragment目前一个痛点确实是 通信不便，你的痛点 也属于这个， 没有很理想的通信机制：
1、EventBus吧使用是简单，但是太解耦，在Fragment上运用还有一些坑；
2、通过`onAttach()`、`onAttachFragment()` 是官方推荐，也是我比较推荐的， 但是缺点是 跨栈、跨太多层时，通信繁琐

不管哪种语言的哪种组件化思想，通信都是一个大问题，后面会思考 更适合Fragmentation的通信方式的

**Comment by heiyeliuying** [comment]
非常感谢.
EventBus 虽然通讯很简单,确实是太解耦了.有点问题,都找不到 Bug 是谁引起的....
