### ISSUE TITLE
onActivityCreated与onSupportVisible时序有时候不对

### ISSUE THREAD

**Issue by bangelua** [YoKeyword/Fragmentation#475]
我继承了SupportFragment，在onActivityCreated初始化了一些东西，onSupportVisible内调用初始化的变量方法发生crash。看了下是onSupportVisible先于onActivityCreated执行了。

**Comment by bangelua** [comment]
找到原因了，如果子类要继承onActivityCreated，必须在方法最后调用super.onActivityCreated(savedInstanceState);父类方法会执行回调onSupportVisible

**Comment by YoKeyword** [comment]
@bangelua  嗯，`onSupportVisible()`目前一些情况会在`onActivityCreated()`调用，但是确定会在`onCreateView()`之后调用， 这个后面再优化，保证统一性

**Comment by YoKeyword** [comment]
v1.1.1已放出，调用顺序规范：onActivityCreated() -> onResume() -> onSupportVisible -> onLazyInitView() => onSupportInvisible() -> onPause()
