### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by gyyak46** [YoKeyword/Fragmentation#476]
偶尔会出现这个异常
Fragment already added: BuyApplyListFragment{41a37c00 #2 id=0x7f1000c2 com.fdsf.tFragment}

android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1679)

这个是bugly  抓到来的

**Comment by LonelyMushroom** [comment]
@gyyak46  从你发的错误片段我发现似乎是你重复添加了同一个fragment导致的,你要不排查下你的代码

**Comment by gyyak46** [comment]
测试时 是点击了 一次 没有显示页面 退出当前页面 再次点击就会出现这个错 误

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/444 你参考一下这个对你有没有帮助,没有的话贴下代码片段

**Comment by gyyak46** [comment]
public void onEnterAnimationEnd  之前这个方法 是protected 为什么改成pbulic l呢???

**Comment by YoKeyword** [comment]
@gyyak46 因为现在不再需要强制`SupportActivity/SupportFragment`了， 可以接口＋委托实现， 因为是接口， 所以不得不变成了publish...

**Comment by YoKeyword** [comment]
另外这个issue ,  Duplicate of #426
