### ISSUE TITLE
继承SwipeBackActivity后使用ImmersionBar修改导航栏状态颜色无法生效，SupportActivity无此问题

### ISSUE THREAD

**Issue by flztsj** [YoKeyword/Fragmentation#477]
对应库的地址如下，https://github.com/gyf-dev/ImmersionBar，库里面本身也有侧滑范例。是没有问题的

看附件应该是侧滑layout挡住了自定义的导航栏View
![default](https://user-images.githubusercontent.com/5946178/28915564-1b5a3518-7872-11e7-8707-f1f97b48faba.png)

**Comment by YoKeyword** [comment]
因为是其它三方库，我这边暂时不会处理， 如果你发现更好的兼容方式，欢迎PR :)

**Comment by flztsj** [comment]
目前怀疑是库里面的SwipeBackLayout引起的。。。

**Comment by YoKeyword** [comment]
OK， 我这边关注下

**Comment by flztsj** [comment]
check一下，发现不是Fragmentation的问题，自定义导航栏颜色不显示是因为侧滑界面的android:windowBackground不是透明的导致遮盖了。

    <style name="AppTheme.NoActionBar.SwipeBack">
        <item name="android:windowBackground">@android:color/transparent</item>  之前没有
        <item name="android:windowIsTranslucent">true</item>
    </style>

这么设置会导致整个侧滑页面背景透明，解决办法就是在具体的页面View中设置背景颜色。
