### ISSUE TITLE
onSupportVisible

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#478]
关于onSupportVisible和onSupportInvisible顺序问题。 能不能做成Activity的onResume onPause类似的顺序。

ActivityA-ActivityB  不论是A-B还是B销毁到A都是先调用的onPause  再调用的onResume 

而现在的Frgment 你提供的2个方法，在start的时候是正常的，但是销毁后，调用的顺序正好是反了？ 能不能统一成Activity的模式。  
现在我们在做页面统计来源就会出现错乱，因为pop后是先执行了onSupportVisible，页面的来源就出错了。

**Comment by hcadoid** [comment]
说错了，是pop后先执行了上个页面的onSupportVisible，随后执行销毁页面的onSupportInvisible

**Comment by YoKeyword** [comment]
感谢建议，下个版本规范下这对生命周期   :)

**Comment by hcadoid** [comment]
好，loadMultipleRootFragment加载多个Fragment时候，初始化的时候第一个Fragment算是可见调用onSupportVisible，而其余的多个不可见的Fragment全部都会执行onSupportInvisible，是否合理。

**Comment by YoKeyword** [comment]
有考虑过这个问题，因为考虑到`loadMultipleRootFragment()`是同时加载多个Fragment到栈内， 同时`onHiddeChanged()`也会被回调，所以`onSupportInvisible()`也就被回调了

这个场景你觉的不应该被调用是吧？  如果从Activity的`onResume`,`onPause`类比考虑的话，不调用是合理的

或许可以提供个 `loadMultipleRootFragment(xxx, boolean lazyLoad)`的懒加载load方法？ 只有第一次show时才会加载对应Fragment

**Comment by hcadoid** [comment]
对，`onSupportVisible()``onSupportInvisible()`应该是成对出现才对。      你说的懒加载是对整个Fragment的生命周期？ 这样话可能会好的，毕竟是按需加载。

**Comment by YoKeyword** [comment]
v1.1.1已放出，调用顺序规范了：`onActivityCreated()` -> `onResume()` -> `onSupportVisible` -> `onLazyInitView()`   => `onSupportInvisible()` -> `onPause()`

 另外`loadMultipleRootFragment ()`，第一次加载时其余Fragments不会先回调`onSupportInvisible()`了， 保证一定是成对出现的
