### ISSUE TITLE
大神你好,我的activity继承你的SupportActivity会拦截掉RadioGroup的setOnCheckedChangeListener事件,

### ISSUE THREAD

**Issue by linjhak** [YoKeyword/Fragmentation#479]
反正在SupportActivity跟SupportFragment里面RadioGroup的checked事件没有作用,你看下有没有这个问题,在正常的activity可以点击,不知道是不是dispatchTouchEvent()方法里面没有传递出来,View的onclicker事件没有问题

**Comment by YoKeyword** [comment]
没有问题的，  SupportActivity/Fragment不会拦截这种事件～

RadioGroup, RadioButton 都有`setOnCheckedChangeListener()`，先排查下是否用错

**Comment by linjhak** [comment]
谢谢你的回复,问题我找到了,原来在清单文件里面设置activity的主题了,跟这个有关,我看下怎么解决!
