### ISSUE TITLE
请问同级Fragment场景下的切换可以有动画吗

### ISSUE THREAD

**Issue by Wade-Cai** [YoKeyword/Fragmentation#481]

**Comment by LonelyMushroom** [comment]
[使用场景－ 转场动画](https://github.com/YoKeyword/Fragmentation/wiki/5.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-%E8%BD%AC%E5%9C%BA%E5%8A%A8%E7%94%BB
)

**Comment by Wade-Cai** [comment]
同级下不是只能showHideFragment吗 @LonelyMushroom

**Comment by LonelyMushroom** [comment]
哦,你是说类似于viewpage这种的动画是吧. 这个我也不知道了,我觉得这个应该跟FG没关系,我以为你说的是startFG的问题

**Comment by YoKeyword** [comment]
如果想要ViewPager那种切换动画， 直接用`ViewPager`代替`loadMultiRootFragment()`就好啦

如果想要定制的动画，可以自己实现，切换后 给当前Fragment的View设置动画并播放即可

**Comment by msn465780** [comment]
跳转到带recyclerview的fragment，动画会卡顿，怎么解决

**Comment by YoKeyword** [comment]
@msn465780 
首先 UI逻辑、业务逻辑放到`onEnterAimationEnd()` （该方法在入场动画结束后回调）里执行， 比如Adapter、绑定、请求数据等等

另外 选用竖向动画在视觉上会比横向动画流畅很多
