### ISSUE TITLE
Fragment has not been attached yet

### ISSUE THREAD

**Issue by xiang23** [YoKeyword/Fragmentation#482]
内存回收后fragment重建 下级fragment使用popTo 但此时上级fragment还未attach导致触发异常，请问如何解决？

**Comment by YoKeyword** [comment]
恢复顺序：  
* 从外层栈 -> 内层栈   （从FragmentActivity下的栈开始恢复）
* 栈底 -> 栈顶

所以，`popTo()`时，栈底的Fragment已经attach了，  你检查下栈层级等可疑地方

**Comment by xiang23** [comment]
后来找到的问题所在，是点击过快多次触发点击事件因为执行了多次popTo引起的
