### ISSUE TITLE
#445 衍生出的问题

### ISSUE THREAD

**Issue by flztsj** [YoKeyword/Fragmentation#483]
在#445基础上在盖一层支持侧滑的Fragment，然后上层Fragment侧滑显示出下层Fragment（这个有View是wrap_content并且再不停更新）时，下层Fragment在抖动。

视频见附件
[device-2017-08-05-164354.mp4.zip](https://github.com/YoKeyword/Fragmentation/files/1202237/device-2017-08-05-164354.mp4.zip)

**Comment by flztsj** [comment]
目前用的是1.1.0版本的sdk

**Comment by YoKeyword** [comment]
@flztsj 感谢反馈，库加了视觉差的功能，`setParallaxOffset(float)`， 而#445 解决时没有考虑视觉差，可以暂时通过`setParallaxOffset(1.0)` 来避免该问题    

下个版本会修复  :)

**Comment by YoKeyword** [comment]
v1.1.1 已放出， 修复了该问题
