### ISSUE TITLE
怎么实现全屏右滑退出啊？

### ISSUE THREAD

**Issue by GongZiZhang** [YoKeyword/Fragmentation#485]
继承SwipeBackFragment后好像都是滑动屏幕边沿才会返回，没找到设置全屏右滑退出的方法

**Comment by LonelyMushroom** [comment]
我是这么认为的,如果全屏右划触动事件的话那么你viewpage的事件会不会被阻拦掉,所以边沿滑动我觉得是正常的,如果要改的话估摸你要在你要全屏右划的页面拦截右划事件传递给SwipeBackFragment的滑动事件.我觉得这样比较合理些.

**Comment by YoKeyword** [comment]
是的，可能会有滑动冲突的问题；   如果一定要实现，可以自己拓展
