### ISSUE TITLE
给部分界面设置透明状态栏？有木有好的建议

### ISSUE THREAD

**Issue by xiongke15117937934** [YoKeyword/Fragmentation#486]
我先在利用的eventbus回调主界面，每次设置activity感觉有点麻烦，有木有好的方法。

**Comment by LonelyMushroom** [comment]
这个方法除了维护困难,基本上是最简单的了,还有一种利于维护的方法,也是作者推荐的.你可以看看这个https://github.com/YoKeyword/Fragmentation/issues/474

**Comment by LonelyMushroom** [comment]
等下,你透明状态栏不是直接在fg里面设置就好了么,toolbar别放在ac里面啊.
