### ISSUE TITLE
Fragment has not been attached yet  － SupportActivity設置竖屏crash

### ISSUE THREAD

**Issue by dlmu2001** [YoKeyword/Fragmentation#488]
在Activity onCreate函数调用
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);

crash

08-09 14:46:48.964 18376 18376 E AndroidRuntime: FATAL EXCEPTION: main
08-09 14:46:48.964 18376 18376 E AndroidRuntime: Process: com.mode.app.mode, PID: 18376
08-09 14:46:48.964 18376 18376 E AndroidRuntime: java.lang.IllegalStateException: Fragment has not been attached yet.
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at android.support.v4.app.Fragment.instantiateChildFragmentManager(Fragment.java:2154)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at android.support.v4.app.Fragment.getChildFragmentManager(Fragment.java:704)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.dispatchSupportVisible(VisibleDelegate.java:140)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.access$000(VisibleDelegate.java:19)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at me.yokeyword.fragmentation.helper.internal.VisibleDelegate$1.run(VisibleDelegate.java:126)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
08-09 14:46:48.964 18376 18376 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

版本:
compile 'me.yokeyword:fragmentation:1.0.9'

通过manifest设置不会crash

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/482  你用悬浮球看下你的栈层级是不是有问题

**Comment by dlmu2001** [comment]
检查没有问题，和#482不像一个问题

**Comment by YoKeyword** [comment]
@dlmu2001 
`java.lang.IllegalStateException: Fragment has not been attached yet` 原因是操作了没有`attach`的Fragment，需要判断下`if(mFragment.isAdded()){ //do }`

建议更新到v1.1.1，  库中做了`!mFragment.isAdded()`的判断，应该不会出现该问题了

**Comment by tzizi5566** [comment]
@YoKeyword 你好，[demo](https://github.com/tzizi5566/example) 我测试的项目也遇到同样的问题，竖屏点击下面的按钮切换页面，再横屏点击下面的按钮切换页面，来回2-3次后会出现error。

![qq 20170811223649](https://user-images.githubusercontent.com/14107578/29218494-897887d6-7ee7-11e7-9fa4-b32d022045dc.png)

**Comment by YoKeyword** [comment]
@tzizi5566    升级到v1.1.1，库中作了校验判断，应该不会出现该异常了

**Comment by YoKeyword** [comment]
@tzizi5566  Fragmentation的[Demo](https://www.pgyer.com/fragmentation)有没有和你Demo类似的场景，看下会不会出现该问题

**Comment by tzizi5566** [comment]
@YoKeyword 已经找到问题了 是在rootFragment->firstFragment里加载otherFragment时没有检查是否已经添加过，导致横竖屏切换时重复调用loadRootFragment()方法。
