### ISSUE TITLE
一种实用场景

### ISSUE THREAD

**Issue by Hiram-Y** [YoKeyword/Fragmentation#49]
比如demo里，在微信的一个tab页，进入循环页面，点击一个按钮，需要触发“销毁所有的循环页，并且切换到第二个tab页的第二个标签（陌生人）”，不知道是否能实现这个逻辑？

**Comment by YoKeyword** [comment]
思路：
1、出栈到主页  popTo(MainFragment.class ,false , new Runnable(){ // 建议EventBus通知MainFragment来进行 2 步骤}) 
2、切换到第二个tab页 showHideFragment(mFragment[SECOND, mBottomBar.getCurrentPosition()])   // 建议EventBus通知SecondFragment来进行 3 步骤 （这里mBottombar.getCurrentPosition() 我刚push了一个commit，现在已经有该方法了～）
3、ViewPager.setCurrentItem(1)  // 切换到第二个标签

**Comment by iboying** [comment]
哈哈，就等你的新版把闪烁消除呢，这个逻辑我用的方法和你的思路一样，以前没用过EventBus，用了Fragmentation, 不仅学会了fragment ，还学会了EventBus，这样的开发经历很令人开心，加油
