### ISSUE TITLE
1.0.7版本 通过start方法跳转到另外一个Fragment，想把当前的Fragment弹出栈，怎么实现呢

### ISSUE THREAD

**Issue by Greathfs** [YoKeyword/Fragmentation#490]
1.0.7版本 通过start方法跳转到另外一个Fragment，想把当前的Fragment弹出栈，怎么实现呢

举个例子：
AFragment ：start（new BFragment（））
BFragment : start（new CFragment（））
CFragment中，点击回退键，回到AFragment
我想的做法是：BFragment : start（new CFragment（））时，把BFragment从回收栈中取消

**Comment by LonelyMushroom** [comment]
你试试
```
BFragment : startWithPop（new CFragment（））
```

**Comment by Greathfs** [comment]
可以了
