### ISSUE TITLE
showHide 一体不是很方便

### ISSUE THREAD

**Issue by VipMinF** [YoKeyword/Fragmentation#491]
showHide 用一个方法来处理，自由性太小了，可不可以每个fragment有个show 方法 和 hide方法 ，或者fragment能监听 fragment自身的show 和 hide 事件

**Comment by YoKeyword** [comment]
`showHideFragment()`这个方法内部仅仅就是 `show`和`hide`操作， 所以完全可以自己通过 `fragmentManager.beginTransaction()`自由`show`、`hide`

另外监听的show,hide的话，可以通过`onHiddeChanged()`回调方法来监听

**Comment by VipMinF** [comment]
我自己show hide 不会影响你栈的关系？

**Comment by YoKeyword** [comment]
`show`,`hide`不会，  你可以看下`showHideFragment()`的源码， 就是简单的show hide
