### ISSUE TITLE
多fragment里面的tablayout+viewpager滑动加载不出数据

### ISSUE THREAD

**Issue by gsn516** [YoKeyword/Fragmentation#493]
多fragment里面的tablayout+viewpager滑动加载不出数据，第二个是好的，第三个就滑动卡顿，且加载不出数据，调换位置出现同样的第二个好的，第三个之前好的变成卡顿了

**Comment by YoKeyword** [comment]
参考Demo

**Comment by gsn516** [comment]
我就是参考demo写的，能指导一下可能出现这个问题的情况么？

**Comment by YoKeyword** [comment]
这个场景非常简单，没遇到过类似情况；

遇到这种问题，建议解决思路：把问题简单化， 比如加载3个非常简单的Fragment来调试

**Comment by gsn516** [comment]
谢谢，已经找到问题，问题出在子fragment上
