### ISSUE TITLE
碎片内，放置 Fragment View Pager，点击子碎片，偶尔只显示半个碎片

### ISSUE THREAD

**Issue by haomengjie** [YoKeyword/Fragmentation#495]
碎片内，放置 Fragment View Pager，点击子碎片，偶尔只显示半个碎片
运行环境：AS模拟器
API版本：25
情况：点击上方TabLayout 子标签，偶尔只显示对应碎片的一半视图

**Comment by YoKeyword** [comment]
@haomengjie  既然显示了（虽然是半个），说明加载方面没问题，排查下布局吧
