### ISSUE TITLE
如何startHide

### ISSUE THREAD

**Issue by VipMinF** [YoKeyword/Fragmentation#496]
有一个场景 Activity中有一个View A  ，A的上面被fragment_container完全覆盖 现在栈有一个Fragment 1 他是不透明的 然后点击star Fragment 2 他是透明的 这时候需求是要能看到View A ，但是 目前看到一片空白。如果使用startPop 我又不能满足我后退 返回到Fragment 1 的需求了

**Comment by YoKeyword** [comment]
v1.1.0后提供了`extraTransaction().startDontHideSelf(fragment);`，  启动目标Fragment，但是不`hide`自身

`extraTransaction()`里有几个不常用，但是在特殊场景很实用的方法
