### ISSUE TITLE
关于栈图

### ISSUE THREAD

**Issue by gyyak46** [YoKeyword/Fragmentation#497]
大佬我在appliaction 中加了一下代码  但是 栈视图没有出来 这是怎么回事
  Fragmentation.builder()
                // 设置 栈视图 模式为 悬浮球模式   SHAKE: 摇一摇唤出  默认NONE：隐藏， 仅在Debug环境生效
                .stackViewMode(Fragmentation.BUBBLE)
                // 开发环境：true时，遇到异常："Can not perform this action after onSaveInstanceState!"时，抛出，并Crash;
                // 生产环境：false时，不抛出，不会Crash，会捕获，可以在handleException()里监听到
                .debug(true) // 实际场景建议.debug(BuildConfig.DEBUG)
                // 生产环境时，捕获上述异常（避免crash），会捕获
                // 建议在回调处上传下面异常到崩溃监控服务器
                .handleException(new ExceptionHandler() {
                    @Override
                    public void onException(Exception e) {
                        // 以Bugtags为例子: 把捕获到的 Exception 传到 Bugtags 后台。
                        // Bugtags.sendException(e);
                    }
                })
                .install();

**Comment by LonelyMushroom** [comment]
你看看demo有没有，如果demo有，你项目没有的话，你检查下manifests的name属性是不是没有添加

**Comment by gyyak46** [comment]
哦   我没有检查manifests

**Comment by gyyak46** [comment]
检查了 有
  ` <activity
            android:name=".activity.MainActivity"
            android:launchMode="singleTask" />`

**Comment by LonelyMushroom** [comment]
```
 <application
        android:name="your appliaction ">
```
或者
```
Fragmentation.builder()
                ...省略代码
                .debug(true) // 这里为true才会显示
                .install();
```

**Comment by gyyak46** [comment]
多谢找到 了BuildConfig.debug 引用错了  多谢

**Comment by gyyak46** [comment]
我打开3个页面后 栈视图top显示 SupportRequestManagerFragment* 这个是怎么回事 我回退还是显示 只有重新打开app  才不显示

**Comment by gyyak46** [comment]
我搜了一下发现是 glide里面的 我没有调用图片

**Comment by LonelyMushroom** [comment]
这个你不用管，这个栈视图工具会抓出来项目里面所有初始化的fg，没关系的

**Comment by gyyak46** [comment]
恩   好的

**Comment by ShenWenKey** [comment]
我的也显示不出悬浮球，
我只是复制了Fragmentation.builder()...省略代码 .debug(true).install(); 别的啥都没做
怎么做
