### ISSUE TITLE
非常棒! 但是想知道这个框架有没有被任何一款用户量较大的App充分验证过?

### ISSUE THREAD

**Issue by matrixxun** [YoKeyword/Fragmentation#5]
首先谢谢作者的贡献. 
如题所问, 这个框架是实验室产品还是已经被某个大用户量的App所采用, 经历了Android 多机型适配的考验, 相对稳定可靠了?
再次感谢!

**Comment by YoKeyword** [comment]
@matrixxun 我司的项目就在用，不过我一直是多Activity+多Fragment的使用方式，其实你看源码的话，库里本身并没有很多东西，主要是官方bug的修复、动画修复，以及管理栈和多重Fragment事务的东西，另外封装了几个类似Activity的API，可随意拓展的，使用这个库的前提还是对Fragment有充分的认知，尤其是栈视图的层次问题。
以我的经验来看，如果你的APP比较重度的使用Fragment，你可以参考这个库或者使用这个库，他会帮你解决一些动画、出栈的一些大坑；对这个库而言，目前还在0.4版本，相信依然会有一些BUG，但是会持续维护的。
至于多机型适配、性能问题，这个其实和库本身没任何关系，Activity需要解决的问题，Fragment依然需要解决，性能方面，毫无疑问Fragment比Activity出色太多。
至于单Activity+多fragment的架构使用，是最难的也是最麻烦的一种组件架构，你可以看到我的Demo包括了最常见的一些Fragment页面，其难点还是在于动画、出栈、栈视图这几个部分，还是那句话这个库帮你搞定最坑的动画、出栈以及多重Fragment事务问题，而对于复杂嵌套等情况还需对Fragment有一定的认知，尤其是FragmentManager的栈视图 :)

当然这个库致力于把复杂嵌套以及类似FragmentTabHost的东西也可以封装进去，让使用更加简单，但至少目前还没找到合适的方案  :)

**Comment by YoKeyword** [comment]
@matrixxun 其实如果你的app架构如果是很普通的大量Activity+少量Fragment的话，这个库可能就没什么价值了，因为几乎不会用到pop多个Fragment、复杂Fragment事务等情况；
如果是少量Activity+多Fragment的话（我的APP就是这种）或单Activity+多Fragment，这个库会有大用处；

**Comment by matrixxun** [comment]
YoKeyword你好, 能透露一下你司项目的app目前用户量大概有多少吗?

**Comment by matrixxun** [comment]
另外"完美解决进出栈动画的一些BUG"是指什么bug?

**Comment by YoKeyword** [comment]
@matrixxun 目前这个项目3000+  崩溃率 < 0.01%   没有特别的复杂的页面跳转逻辑
如果你使用popBackStack(tag)方法出栈多个Fragment，然后没做任何措施，在这时来个电话 或回到home，这时恰巧发生了app被强杀，这时再回到app，app被重启，这时就属于非常危险的状态，会发生动画的一个空指针Crash，或者栈内所管理的一些数组顺序有问题（取决于你下一步做了什么 ）

或者说 如果你现在在Fragment B，你上个Fragment是A，你现在需要启动新的Fragment C，但是呢启动之前想把B pop：
如果你直接add C->pop() ， 这样无疑出栈的是C；
如果你pop() -> add(C) 这样的话，C在进来之前时，B会先出栈，即你看到页面变成了A，然后C才动画进来。
而库里提供了一种方案帮你解决了这个问题。

动画上印象中还是有其他坑，暂时想不起来啦  :)

**Comment by YoKeyword** [comment]
@matrixxun 如果你们的项目打算重度使用Fragment的话，谨慎点的话，你可以参考下库，主要是库里几个fix相关的方法，当然如果发现更好的解决方式或BUG，希望能PR   :)

**Comment by matrixxun** [comment]
ok, 了解了. 另外有个事情, 你现在在哪个城市, 有没有兴趣来我们团队? 杭州阿里.

**Comment by YoKeyword** [comment]
@matrixxun O_O  非常感谢～  不过我对自己还是比较了解的，安卓知识体系现在还是有点凌乱，距离阿里应该还有一段距离，等我准备好了我一定会去阿里试试的 :)
我在杭州海创园，你们斜对面. 哈哈～

**Comment by matrixxun** [comment]
请加我QQ或微信详聊: 421883923
