### ISSUE TITLE
[其他问题]error

### ISSUE THREAD

**Issue by ymcao** [YoKeyword/Fragmentation#50]
android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
2 android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
3 android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
4 android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:617)
5 whatsmode.com.mode2.app.Fragmentation.showHideFragment(Fragmentation.java:191)
6 whatsmode.com.mode2.app.SupportFragment.showHideFragment(SupportFragment.java:382)
7 whatsmode.com.mode2.module.feed.view.fragment.MainFragment$1.onTabSelected(MainFragment.java:126)
8 whatsmode.com.mode2.ui.BottomBar$1.onClick(BottomBar.java:74)
9 android.view.View.performClick(View.java:5697)
10 whatsmode.com.mode2.ui.BottomBar$2.run(BottomBar.java:97)
11 android.os.Handler.handleCallback(Handler.java:739)
12 android.os.Handler.dispatchMessage(Handler.java:95)
13 android.os.Looper.loop(Looper.java:158)
14 android.app.ActivityThread.main(ActivityThread.java:7237)
15 java.lang.reflect.Method.invoke(Native Method)
16 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
17 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by YoKeyword** [comment]
@ymcao 
这个异常是因为 你在Fragment的状态被保存之后（即onSaveInstanceState被调用之后），又进行commit一个FragmentTransaction事务导致的；

这种情况解决办法一般是 把逻辑修改下，把事务提交放到Fragment的onResume中，不建议使用网上的commitAllowingStateLoss()方式！

**Comment by ymcao** [comment]
情况是这样的 我在mainfragment中有4个tab，然后第四个tab（使用的是demo中的bottombar），点击去设置页面退出登录，发送了个event，在mainfragment的event接受中，调用setCurrentItem(0)，偶尔会出现上面的异常崩溃

**Comment by YoKeyword** [comment]
你检查下在这个过程中showHideFragment（这个方法本质就是一个FragmentTransaction事务）的调用前，是否已经保存了状态（onSaveInstanceState）

这里给一个链接，对这个异常的描述，以及解决方案：
http://www.cnblogs.com/kissazi2/p/4181093.html
