### ISSUE TITLE
startWithPop 总是闪屏

### ISSUE THREAD

**Issue by heiyeliuying** [YoKeyword/Fragmentation#501]
使用了 startWithPop 和右侧进入动画,但是在页面转场时,总是会闪一下屏幕.请问,有什么解决思路没

**Comment by YoKeyword** [comment]
是动画开始时闪烁，还是结束时闪烁？

`startWithPop`之前做过不少测试，一般情况下应该没问题； 

另外该方法可以通过另一种实现方式替代:  用`A.start(B)`替换`A.startWithPop(B)`，再给B设置标志位，在B退出时，使用`popTo(A,true)`代替`pop()`

**Comment by heiyeliuying** [comment]
谢谢,我用了类似的手段实现了功能.

该问题是偶发性的问题.在我的测试机器上,出现的概率大约占比1/3.
例如从 当前页面A跳转到B页面,A 中调用 startWithPop(B), 在 B 从右侧滑动进入动画马上就结束的时候,页面会突然闪一下,从闪现的页面内容可以看出来是 B.(有点类似于在 把 B 又无动画的显示了一次).

**Comment by YoKeyword** [comment]
@heiyeliuying  OK， 我回头会关注下这个问题  :)

**Comment by heiyeliuying** [comment]
thanks
