### ISSUE TITLE
我想A跳转到B,B调用POP回到A,这时我想刷新一下数据,应该用哪个生命周期的方法?

### ISSUE THREAD

**Issue by colder112** [YoKeyword/Fragmentation#502]
回到A刷新A的数据,A并没有消亡,还是在栈里.只是不知道该用哪个生命周期方法

**Comment by colder112** [comment]
目前我用eventbus来发事件刷新...

**Comment by LonelyMushroom** [comment]
[startForResult](https://github.com/YoKeyword/Fragmentation/wiki/7.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-startForResult%E6%8E%A5%E6%94%B6%E6%95%B0%E6%8D%AE%E8%BF%94%E5%9B%9E&%E5%90%AF%E5%8A%A8%E6%A8%A1%E5%BC%8Fstart)

你看看这样行么，一般来说最好不要在不复杂的流程使用eventbus

**Comment by colder112** [comment]
我现在还有这种情况啊,栈里 A,B C　在Ｃ中做出了修改，Ａ中要刷新一下数据..但是A没消亡,,就是想找个生命周期用一下...这种情况用的是eventbus,其他的情况的话,能用回调接口就用了.

**Comment by LonelyMushroom** [comment]
@colder112 [onSupportVisible](https://github.com/YoKeyword/Fragmentation/wiki/3%E3%80%81onSupportVisible()%E7%AD%89)
