### ISSUE TITLE
startWithPop的问题

### ISSUE THREAD

**Issue by Gundam0079** [YoKeyword/Fragmentation#505]
startWithPop后调用一个start方法
A startWithPop B
A start C
这样栈中情况应该是 B C
实际情况是 C B   

看TransactionDelegate 中 startWithPop在 Handler Post中执行 所以会比start慢造成了这样的结果

**Comment by YoKeyword** [comment]
@Gundam0079  是的，`startWithPop `的原理是mock了一个动画来实现视觉上的正确效果

解决方式也简单：  `A.start(C)`这句代码放到 Post 里执行即可

> `startWithPop `的实现机制还不是特别完美，后续再考虑其他方案

**Comment by Gundam0079** [comment]
好的谢谢  持续关注中  ^-^
