### ISSUE TITLE
How to handle onBackPresSupport, onSupportVisiable, onSupportInVisiable without use this library

### ISSUE THREAD

**Issue by ngochuu90** [YoKeyword/Fragmentation#507]
Dear @YoKeyword 

Your library is great library. I used for many projects
I am having problems needing to handle onSupportVisiable, onSupportInVisiable , and onBackPresSupport in Fragment, But not allowed to use your library

Can you help me to solve this problem, please

Thank you!

**Comment by YoKeyword** [comment]
Hi,
  You can refer to [VisibleDelegate.java](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/helper/internal/VisibleDelegate.java) and [onBackPressedSupport](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/SupportActivityDelegate.java#L143)
