### ISSUE TITLE
生命周期变化以后的问题

### ISSUE THREAD

**Issue by likealeodog** [YoKeyword/Fragmentation#508]
ViewTreeObserver.OnGlobalLayoutListener是视图布局更新之后的回调，会在某view有具体的绘画高度时回调接口。

这是新版(1.1.1)的部分生命周期：

1,容器内加载所有碎片碎片1为开始碎片
--碎片1 onResume>碎片2 onResume>碎片1 onSupportVisible>onLazyInitView
2,碎片1切换到碎片2
-onSupportInvisible>碎片2 onSupportVisible>onLazyInitView
3,碎片2切换到碎片1
--onGlobalLayout()>onSupportInvisible...
注意，一直到碎片2切换到其他碎片时才会执行绘制回调onGlobalLayout才能获取到布局宽高。

这是旧版(1.1.0)的生命周期（举例使用）：

1,容器内加载所有碎片碎片1为开始碎片
--碎片1 onSupportVisible>onLazyInitView>onResume>碎片2 onResume>onSupportInvisible
2,碎片1切换到碎片2
--碎片2 onSupportVisible>onLazyInitView>碎片1 onSupportInvisible>碎片2>onGlobalLayout
注意，此时的回调onGlobalLayout是与碎片2的onSupportVisible周期同步进行的。

这样就存在一个 我要想获取碎片2某个组件的宽高，还必须让用户自己去切换一次？
望回复，现已换回1.1.0，吓死我了，还好我想起了这2天更新了一下库版本，不然又要找好久。

**Comment by YoKeyword** [comment]
v1.1.1 规范了support系列的生命周期：
`onResume` -> `onSupportVisible` -> `onLazyInitView()`

`onSupportVisible`里其实可以直接通过`getHeight`拿到view的宽高， 因为现在该方法会post到队列里执行，所以会在view绘制完成后才会执行`onSupportVisible` 

另外看描述似乎你的`OnGlobalLayoutListener`在`onSupportVisible`里监听的？
`onSupportVisible()`是个会被重复调用(可见时被调用)的生命周期， 你应该放到`onLazyInitView()`里监听， 当然上面说到，在该生命周期里可以直接通过`view.getHeight()`拿到宽高

**Comment by likealeodog** [comment]
我的视图绘制监听是放在onSupportVisible里面的，

2,碎片1切换到碎片2
-onSupportInvisible>碎片2 onSupportVisible>onLazyInitView

这一条中 即使onLazyInitView执行了，也没有回调onGlobalLayout的函数，所以放onLazyInitView和放
onSupportInvisible是一样的，因为onGlobalLayout的函数都没有执行，只有切换的时候才执行。

**Comment by YoKeyword** [comment]
1、在`onSupportVisible `或者`onLazyInitView `里直接通过view.getHeight()拿到宽高

或 2、`onCreateView()`、`onActivityCreated()`等生命周期里监听

建议 1

**Comment by likealeodog** [comment]
这不是监听的问题好不好？监听是回调的，无论你放在什么时候去监听，它的回调都是在某种条件下才会触发的，我所说的问题是之前版本会在onSupportVisible之后回调，但是最新的版本只会在碎片切换的时候才回调，这才是我问题的重点，而不是去哪儿设置监听。

**Comment by YoKeyword** [comment]
@likealeodog 
额， `onSupportVisible()`在 v1.1.1 会post到队列尾，这意味着 在切换回来时（即`show`），虽然布局变化了，但是`onSupportVisible()`还没有被回调，所以此时也就没有回调`OnGlobalLayoutListener `，而在你切换到其他Fragment时(`hide`)，隐藏当前Fragment会导致布局变化，所以此时回调了`OnGlobalLayoutListener `

最重要的是：因为v1.1.1的这个特性，建议直接在`onSupportVisible`里直接获取宽高，不需要通过`OnGlobalLayoutListener`， 如果需要监听，那么放到`onCreateView()、onActivityCreated()`等生命周期里监听会合适  :)

**Comment by likealeodog** [comment]
onActivityCreated、onCreateView()生命周期都试过了，即使回调也获取不到宽高，获取宽高的唯一方式就是在onSupportVisible中直接获取。但是这就存在兼容问题，你之前的版本都会回调该函数，为什么到了1.1.1就不会回调了，给已使用的用户在升级时错误的执行。所以，我建议的话，能在onSupportVisible获取到宽高的同时又能保证OnGlobalLayoutListener正常执行是再好不过了。

**Comment by likealeodog** [comment]
onGlobalLayout的回调我测试过了，android原生碎片是在onCreateView中设置回调，然后会立即执行OnGlobalLayoutListener并且正常获取到宽高，所以现在的这个生命周期对原生碎片是冲突的。

**Comment by yangjieK** [comment]
支持 likealeodog的观点,   与原生碎片冲突是 非常不适合的

**Comment by YoKeyword** [comment]
@likealeodog @yangjieK 
和原生Fragment不冲突的，Fragmentation只是拓展，对原Fragment的机制不会做特殊处理～

我想你是在`loadMultipleRootFragment()`的子Fragment里测试的，这个方法会把所有Fragments先加载进来，但是只显示一个，这会导致其他hide的Fragments回调`onGlobalLayout`，并且此时测量的高度为0 ...    

这个和库无关的，你用原生Fragment去 add所有fragments然后再show,hide也是会出现这情况的，你可以试下哈，这种情况下要做如下判断：
````java
 public void onGlobalLayout() {
      if (view.getHeight() == 0) return;
      ...
      // removeOnGlobalLayoutListener
}
````

另外可以在`start()`的Fragment里做下测试，这种场景比较单纯，上面说到的机制应该都是正确触发的

**Comment by likealeodog** [comment]
我试过了 原生碎片
Frag1 frag1 = new Frag1();
            getSupportFragmentManager().beginTransaction()
                    .add(R.id.main_container, frag1)
                    .add(new Frag1(), "f2")
                    .add(new Frag1(), "f3")
                    .show(frag1)
                    .commit();
这种方式，然后
        rootView = inflater.inflate(R.layout.frag_1, container, false);
        final View view = rootView.findViewById(R.id.f1_v);
        Log.d(TAG, "onCreateView: 设置监听");
        final ViewTreeObserver vo = view.getViewTreeObserver();
        vo.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                Log.d(TAG, "onGlobalLayout: 监听回调");
                Log.d(TAG, "onGlobalLayout: 宽高：" + view.getWidth() + view.getHeight());
                view.getViewTreeObserver().removeOnGlobalLayoutListener(this);
            }
        });
最后执行结果：
onCreateView: 设置监听
onCreateView: 设置监听
onCreateView: 设置监听
监听回调
宽高：7201107
和我用单个碎片加载的结果是一样的，都是在onCreateView中设置监听，等到它show的时候就会回调
而不是我设置监听就直接回调了，所以我说肯定是哪里有问题。

**Comment by YoKeyword** [comment]
````java
Frag1 frag1 = new Frag1();
getSupportFragmentManager().beginTransaction()
.add(R.id.main_container, frag1)
.add(new Frag1(), "f2")
.add(new Frag1(), "f3")
.show(frag1)
.commit();
````

你这里没有 `hide` f2, f3，这种加载方式一般都要hide其他不需要显示的Fragments， `loadMultipleRootFragment()`内部也是show某一个Fragment，hide其余的Fragments

**Comment by likealeodog** [comment]
那我如果给你说即时是hide了，其生命周期依旧照常执行，show的碎片依旧能够在onCreate中设置监听并马上获取到绘制的宽高，怎么说？

**Comment by YoKeyword** [comment]
@likealeodog  不管show,hide，`onGlobalLayout ()`都会执行，只是 show的Fragment高度是测量后的，可以拿到

hide的Fragment因为立即隐藏，所以没有测量高度，回调时 getHeight是0

仔细看下回复， 还有不是辩论谁对谁错， 也许有我没考虑周全的地方， 沟通下共同进步哈

**Comment by likealeodog** [comment]
我的意思是现在库里面在onCreateView函数中获取不到宽高与原生的碎片周期和回调有些区别，我只是证明我所说的问题确实存在。然后onSupportVisible中获取宽高这种方式其实知道的人并不多，就会出现原本是OnGlobalLayoutListener在原生碎片onCreateView下设置并监听，本来是正常执行并且能获取到宽高，但是换成库之后就直接获取不了了，这才是我想说的问题啊。

**Comment by likealeodog** [comment]
“不管show,hide，onGlobalLayout ()都会执行，只是 show的Fragment高度是测量后的，可以拿到”
但是生命周期和流程变了，show之后，1.1.1里面onSupportVisible设置监听，结果OnGlobalLayoutListener回调获取不了宽高，1.1.0里面可以获取到。
然后show、hide之后，原生碎片onCreateView中设置监听OnGlobalLayoutListener可以获取到宽高，
但是1.1.1版本库中监听就获取不到。

**Comment by likealeodog** [comment]
具体的我前面已经把我测试过的生命周期流程都写上去了，OnGlobalLayoutListener设置之后不会立即执行，而是在从当前监听了OnGlobalLayoutListener切换到其他碎片时才会执行。

**Comment by YoKeyword** [comment]
留个QQ或微信吧，好沟通, 我测试的结果确实和预期一致，不管v1.1.1还是v1.1.0
