### ISSUE TITLE
loadRootFragment 进入/退出无动画效果

### ISSUE THREAD

**Issue by cgalaxy** [YoKeyword/Fragmentation#511]
请问下，文档里面我没有找到，关于loadRootFragment前需要做些什么操作，导致现在项目里同一个activity 会loadRoot 不同的fragment，fragment栈回退的时候，有的fragment无法回退，并且点击无效，无法回退的fragment看起来是通过loadFragment的方式加入栈中的～我有试在loadRootFragment之前执行pop（）会将 activity的上所有的fragment销毁，这样就没有问题～但是，loadRootFragment的fragment 没有动画～   现在就是想：root fragment 进入退出可以有动画，怎么办呐～感谢，急急急，么么哒～～

**Comment by LonelyMushroom** [comment]
你是男粉还是女粉? 男粉就别么么哒了

好了,我说说我个人的理解,loadRoot这个方法是用来提供类似底部菜单栏和侧边栏这种show/hide的方便实现,一般来说这样是没有动画的,如果你硬是要加动画的话估摸只能为你fragment里面的最外层的view添加进入和退出动画,这样比较好一点.
至于回退栈的话你可以打开栈视图工具查看,这个很方便,是个很赞的小功能,你可以试试.
还有你可以看看demo,demo里面的实现会告诉你怎么做一个好的fragment app.
然后...emmmmmmmmmm  我不是作者.........hahahahaha

**Comment by YoKeyword** [comment]
@cgalaxy  
可以参考下Demo，大多数情况我们会用第二个Demo的栈设计，强烈建议看下

另外替换rootFragment可以使用`root.startWithPop(newRoot)`来替换（建议更新到v1.1.2）

**Comment by cgalaxy** [comment]
女粉女粉，好的，谢谢大家的及时意见，爱你们
