### ISSUE TITLE
loadRootFragment 不能pop 之前loadRoot的fragment

### ISSUE THREAD

**Issue by cgalaxy** [YoKeyword/Fragmentation#512]
刚刚说着说忘了，其实，我在loadRootFragment之前执行pop（）应该是会销毁所有该activity fragment栈中的fragment，但是如果loadRootFragmentA->starFragmentB->pop()->loadRootFragmentB,此时会是FragmentA-FragmentB，从FragmentB返回FragmentA界面都执行无效，也就留在了activity最上面，只有杀掉app。咋办啊

**Comment by YoKeyword** [comment]
类似问题继续提在 #511 

`loadRootFragment()` 会把Fragment加入到回退栈，所以再次`loadRootFragment()`是不会把A移除回退栈的

使用`A.startWithPop(B)`代替`loadRootFragmentB()`即可 （升级到v1.1.2，之前版本这种情况下动画会有点问题）

**Comment by cgalaxy** [comment]
好的，我真的知道啦，你真好～赞赞赞，通过fragment 依附的viewgroup 孩子个数判断之前是不是有loadRootFragment， 使用loadRootFragment 或者 startWithPop 开启fragment，用getTopFragment判null效果不佳～～ 每个项目都有自己的情况，很谢谢你写了这么好的一个库～
