### ISSUE TITLE
如何关闭viewpager里的fragment动画

### ISSUE THREAD

**Issue by yangjieK** [YoKeyword/Fragmentation#513]
因为不需要viewpager的fragment加载退出的动画,我怎么关闭呢? 

fragmentA有2个view,view有各自的动画, 同时 FragmentA在viewpager里,fragmentA会被移出时会调用退出动画. 此时 View的动画跟fragmentA的退出动画重叠.

**Comment by YoKeyword** [comment]
You can control the Fragment animation like this:
```` 
@Override
public FragmentAnimator onCreateFragmentAnimator() {
      return new DefaultNoAnimator();
}
````

But the fragment in ViewPager does not play animation.

**Comment by yangjieK** [comment]
AnimatorHelper.getViewPagerChildFragmentAnimFixed()...
```
@Nullable
    public Animation getViewPagerChildFragmentAnimFixed(Fragment fragment, boolean enter) {
        if (!enter && fragment.getTag() != null && fragment.getTag().startsWith("android:switcher:")
                && fragment.getUserVisibleHint()) {
            Animation animation = new Animation() {
            };
            animation.setDuration(exitAnim.getDuration());
            return animation;
        }
        return null;
    }
```

if the fragment in viewpager was being exit, the exitAnim will be started

**Comment by YoKeyword** [comment]
哦哦，指的出栈动画

`getViewPagerChildFragmentAnimFixed()`是为了解决ViewPager父Fragment在出栈展示出栈动画时， 子Fragment会空白的问题... 

这里的动画是： 维持`exitAnim.getDuration()`时长的**空动画**，所以在视觉上，看到的是其父Fragment的出栈动画

如果你不想让其有出栈动画，把父Fragment的出栈动画设置为无动画即可

你的场景我们一般是这样实现的： pop()放在 view动画结束的回调里，即 先播放完view动画，然后出栈
