### ISSUE TITLE
自己定制的SupportActivity中，在仿照SwipeBackLayout中获取的SupportFragmentDelegate中的变量mLockAnim 获取不到

### ISSUE THREAD

**Issue by littlezan** [YoKeyword/Fragmentation#514]
![image](https://user-images.githubusercontent.com/5358278/29512387-a4d96ad6-8694-11e7-9522-70d01660e035.png)

**Comment by YoKeyword** [comment]
mLockAnim是包作用域，所以你的`SwipeBackLayout`应该要在`me.yokeyword.fragmentation`这个包目录下

另外，你可以直接依赖`fragmentation-swipeback`，然后参照`SwipeBackActivity/Fragment`的写法实现自己的`SwipeAC/FG`呀

**Comment by littlezan** [comment]
哦，好的，谢谢
