### ISSUE TITLE
回退到首页的问题

### ISSUE THREAD

**Issue by Greathfs** [YoKeyword/Fragmentation#515]
首页Activity有一个按钮，点击后直接跳转到首页Fragment，并清空栈内其他Fragment

代码
 @OnClick(R.id.rl_app_name)
    public void onViewClicked() {
        popTo(HomeFragment.class, false);
        dismissSecondTitle();

    }

使用版本：1.0.7

问题：AFragment--->BFragment--->CFragment--->DFragment
点击首页按钮，回到AFragment 
这时，DFragment会有一个往右侧退出的动画，这边是想把那个动画去掉，直接显示AFragment
求指点下

**Comment by Greathfs** [comment]
还有使用startWithPop（）总感觉有点闪屏，我也看了看别人提的问题，我还是不是很清楚怎么处理比较好

AFragment 调用startWithPop（BFragment），我看解决办法好像是AFragment调用start（BFragment）然后在BFragment退出时 执行popTo（AFragment，true） 这段代码应该写在BFragment哪里比较好呢？

**Comment by YoKeyword** [comment]
1、
````java
getTopFragment().setFragmentAnimator(new DefaultNoAnimator());
popTo(HomeFragment.class, false);

或者   // 现版本需要no_anim，其是个空动画，下个版本优化为传 0即无动画
popTo(HomeFragment.class, false, null, R.anim.no_anim); 
````

2、当BFragment需要出栈的地方，`pop()`替换为`popTo(A, true)`即可

**Comment by Greathfs** [comment]
错了错了  我之前的需求是这样的

AFragment---》BFragment---》CFragment
当BFragment跳转到CFragment后，点击回退键，回退到AFragment，
所以我在BFragment跳转到CFragment使用的是BFragment.startWithPop（CFragment）
