### ISSUE TITLE
Error:(90, 53) 错误: 不兼容的类型: ArrayList<Fragment>无法转换为SparseArray<Fragment>

### ISSUE THREAD

**Issue by Learzhu** [YoKeyword/Fragmentation#517]
尝试了三次以上了，开始导入项目编译需要十几分钟，翻墙状态，显示com.android.support:appcompat-v7:25.4.0 can't found ,不得已修改成为com.android.support:appcompat-v7:25.2.0 出现异常

**Comment by Learzhu** [comment]
Error:(14, 14) Failed to resolve: com.android.support:appcompat-v7:25.4.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:F:/learzhu/AndroidProjectCollections/Fragmentation-master/Fragmentation-master/fragmentation/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/404

**Comment by Learzhu** [comment]
尝试了很久没有解决诶……作者有办法么？AS 2.2.3

**Comment by YoKeyword** [comment]
@Learzhu  能成功拉到v25.4.0, 或者v26.0.0的support包即可，  Demo编译环境需要最少v25.4.0

自己项目依赖 support版本随意

**Comment by Learzhu** [comment]
尝试过了还是不行啊，全部改成了 'com.android.support:appcompat-v7:26.0.0' 在FragmentationHack 类还是有异常 ，我的AS2.2.3         classpath 'com.android.tools.build:gradle:2.3.3'

**Comment by YoKeyword** [comment]
@Learzhu  看下gradle是否成功拉到v26.0.0的包，环境对的话，肯定没问题的

可以新建一个空工程，把support-25.4/ 26.0 的包拉下来，再编译下Demo

**Comment by Learzhu** [comment]
刚刚又试了一次你原本的项目编译正常了，但是改成v26.0.0就不对了，classpath 'com.android.tools.build:gradle:2.3.3' 谢谢 应该是本地网络的问题 之前翻墙试过 最近网络不佳造成的吧！
