### ISSUE TITLE
问一个问题 

### ISSUE THREAD

**Issue by gyyak46** [YoKeyword/Fragmentation#519]
我打开AFragment 初始化变量private int index=1 然后我改变index值改为10,在我关闭Afragment之后,再次点击AFragment index变量的值还是10  (index值是全局的 没有加static 和final) 这是为什么

**Comment by LonelyMushroom** [comment]
1.  贴上关键代码
2.  你看看你是不是在onSaveInstanceState这个生命周期里面恢复了状态

**Comment by gyyak46** [comment]
这是base
`public class BaseBackAFragment extends SwipeBackFragment {

    private static final String TAG = "Fragmentation";

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        setParallaxOffset(0.5f);
    }
.......
}` 
这是listFragment 
` public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fg_buy_apply, container, false);
        unbinder = ButterKnife.bind(this, view);
        initView(inflater);
        initListener();
        return attachToSwipeBack(view);
    }

  @Override
    public void onEnterAnimationEnd(Bundle savedInstanceState) {
        super.onEnterAnimationEnd(savedInstanceState);
        //添加家在逻辑
        Log.e("显示", "指示enter " + index);

        loadMoreData(index, pageSize);
    }

  @Override
    public void onDestroyView() {
        super.onDestroyView();
        unbinder.unbind();
        Log.e("显示", "指示destroy " + index);

        EventBus.getDefault().unregister(this);
        OkHttpUtils.getInstance().cancelTag(this);
        cancelLoadingDialog();
    }
`

**Comment by LonelyMushroom** [comment]
Emmmmmmmm.......感觉你贴了些没用的代码,而且你代码块最好好好整理下,发出来不是很看的明白

**Comment by gyyak46** [comment]
我不知道你需要那一块的代码 EEEe

**Comment by LonelyMushroom** [comment]
.....   就是跟index相关的代码,其实我觉得你好好debug或者log一下就知道了.你先调试下吧

**Comment by gyyak46** [comment]
我又试了一下 还是找不出来  别的界面没有问题  只有3个界面出现这种现象 
好尴尬啊

**Comment by gyyak46** [comment]
这是log 
E/显示: 指示initview 1
 E/显示: 指示enter 1
 E/显示: 指示loadmore 1
 E/显示: 指示process 1
 E/显示: 指示loadmore 2
 E/显示: 指示process 2
 E/显示: 指示destroy 2
再次点进去
 E/显示: 指示initview 2

**Comment by gyyak46** [comment]
这个index只是分页的标识
`  //加载
        mBuyAdapter.setOnLoadMoreListener(new BaseQuickAdapter.RequestLoadMoreListener() {
            @Override
            public void onLoadMoreRequested() {
                int currentSize = mBuyAdapter.getData().size();
                if (!TextUtils.isEmpty(mTotalSize)) {

                    int totalSize = Integer.parseInt(mTotalSize);
                    if (currentSize >= totalSize) {
//                    mBuyAdapter.removeAllFooterView();
                        mBuyAdapter.loadMoreEnd();
//                    mBuyAdapter.addFooterView(footView);
                    } else {
                        index++;
                        loadMoreData(index, pageSize);
                    }
                }

            }
        }, buyRv);

`

**Comment by YoKeyword** [comment]
@gyyak46 我看你在用EventBus，是否用了sticky事件，而又没有及时removeStickyEvent ?

贴下关键处的代码： 声明index的代码、 改变index值的代码、 接收改变index的代码
