### ISSUE TITLE
关于 app 内存重启恢复

### ISSUE THREAD

**Issue by wjehovah** [YoKeyword/Fragmentation#52]
我开启 『开发者选项』->『不保留活动』 运行您的 Demo ，然后按下 Home 键，再次打开 app 没有被杀掉，或者是自动恢复了我没看出来。 
QQ 和 微信 都是 10s 后就重启了。我自己用您的库也会重启，有时候Fragment 可以恢复，但是有些变量报空指针，这样即使 Fragment 恢复 意义也不是很大。
 请问这种问题有什么解决办法。

**Comment by YoKeyword** [comment]
是这样的，[不保留活动] 在占用内存较低的App中，点Home再回来，未必每次都可以被杀，如果想保证更高几率的强杀，尝试再打开一次浏览器，再切回来； 如果回来时发现有一瞬间的空白，则代表被杀了~  

还一种100%可以重启的方式就是通过DDMS。

对于这块，建议多尝试，多思考，很快就可以掌握安卓的恢复机制啦~

**Comment by wjehovah** [comment]
谢谢
