### ISSUE TITLE
startWithPop 的问题

### ISSUE THREAD

**Issue by QuincySx** [YoKeyword/Fragmentation#525]
机型：红米 note3
miui：8.5稳定版
版本：6.0.1
support:25.3.1

使用 startWithPop 开启一个新的 Fragment 旧的不会关闭 会在底部显示

**Comment by YoKeyword** [comment]
必现吗？  库的版本号是？

**Comment by QuincySx** [comment]
我又试了两次，我重新描述一下这个问题，版本 1.1.1：
我有一个Activity使用loadRootFragment(id, delegate,false,boolean) 方法加载根视图，我使用startWithPop() 方法的时候是可以正常打开新的，关闭旧的，当把loadRootFragment()第三个参数改为 true 或者使用loadRootFragment(id, delegate)时，使用startWithPop() 时，就会新的Fragment盖在旧的Fragment上面，旧的不会消失，我不知道这是什么原因，或者是作者有意为之

**Comment by YoKeyword** [comment]
更新到v1.1.3再看下

**Comment by QuincySx** [comment]
非常感谢！
升级版本问题已解决
