### ISSUE TITLE
fragment可见的回调--嵌套fragment的情况

### ISSUE THREAD

**Issue by hoop208** [YoKeyword/Fragmentation#530]
在onpause和onresume中,先判断isFragmentVisibile再做的可见事件分发.isFragmentVisibile这个方法返回的是当前!fragment.isHidden() && fragment.getUserVisibleHint().这个判断不需要考虑parentFragment的状态吗?   因为这个库要继承使用,我目前只需要返回键监听和可见的回调,copy的部分代码,在嵌套的时候子fragment在parentfragment隐藏的情况下,最小化应用or返回应用都会回调可见的监听

**Comment by YoKeyword** [comment]
1、`onSupportVisible()` 代表当Fragment对用户可见时，回调该方法（不管层级如何，只要可见即回调）

2、`onResume`等周期方法回调时，该AC下的**所有Fragments**均会被回调FG的`onResume`，所以不用考虑父Fragment等状态

3、因为你没有使用库，而是copy的代码，所以我无法知晓你是否完整的copy了相关代码； Fragmentation不需要强制继承使用， 你可以通过实现 ＋ 委托来实现自己的SupportActivity/Fragment， 把SupportActivity/Fragment里的代码copy到自己的基类Fragment里

**Comment by programer-liang** [comment]
现在创建了两个AC,里面都有多个FG，两个AC的关系是A -> B（正常启动 ） 
当我app 最小化的时候，B(AC)中的FG onstop 都会调用，A(AC)中的FG的onstop 也会全部调用到，这是什么原因造成的？
