### ISSUE TITLE
关于startWithPop的问题

### ISSUE THREAD

**Issue by Gundam0079** [YoKeyword/Fragmentation#531]
在报错的log中看到   想问问有可能是什么原因导致的呢  
使用场景是的再启动时候把launchFragment  pop 启动homeFragment
launchFragment并没有其他fragment 操作 没想明白是哪里出现的问题

1    Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
2    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
3    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:775)
4    at me.yokeyword.fragmentation.j.c(TransactionDelegate.java:254)
5    at me.yokeyword.fragmentation.j.b(TransactionDelegate.java:245)
6    at me.yokeyword.fragmentation.j.a(TransactionDelegate.java:139)
7    at me.yokeyword.fragmentation.f.c(SupportActivityDelegate.java:234)
8    at me.yokeyword.fragmentation.SupportActivity.c(SupportActivity.java:183)

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/522
