### ISSUE TITLE
进入仿知乎Demo，点击第三个和第四个Tab，页面会闪烁，再次点击就没了

### ISSUE THREAD

**Issue by LuckyStar521** [YoKeyword/Fragmentation#532]
进入仿知乎Demo，点击第三个和第四个Tab，页面会闪烁，再次点击就没了,但是点击第二个Tab不会闪烁

**Comment by YoKeyword** [comment]
原因在于其内的子Fragment是在 `onLazyInitView()`里去加载的，比如[第4个Tab](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_zhihu/ui/fragment/fourth/ZhihuFourthFragment.java#L42)

即在第一次可见时加载（第一次切换时加载）， 这样做可以节省内存资源 :)
