### ISSUE TITLE
onLazyInitView和onSupportVisible的使用问题

### ISSUE THREAD

**Issue by ImHone** [YoKeyword/Fragmentation#534]
不太明白这俩分别应该在什么场景使用

举例这样一个功能场景：   

1.设置标题返回
2.recyclerview增加 头布局，设置 adapter
3.把SwipeRefreshLayout设置为正在刷新状态
4.加载数据

initView(){
    1
}
onSupportVisible(){
   2  , 3
}
onLazyInitView(){
   4
}

是这样使用吗？

**Comment by YoKeyword** [comment]
懒加载 `onLazyInitView()`是第一次可见时回调，`onSupportVisible()`是可见时回调， 所以第一次回调`onSupportVisible()`时，也会触发`onLazyInitView()`

另外还有一个`onEnterAnimationEnd()`，该方法会在入场动画结束时回调，如果你的Fragment动画有卡顿的话，可以考虑把逻辑操作放到这里

具体可以参考wiki，以及建议多看Demo  :)
