### ISSUE TITLE
点击闪屏的问题

### ISSUE THREAD

**Issue by Greathfs** [YoKeyword/Fragmentation#535]
![image](https://user-images.githubusercontent.com/18097997/29866259-7e6ee0e8-8daa-11e7-8922-0687ddd76a9a.png)

版本：1.0.7

代码如下：
public class HomeActivity extends SimpleActivity {

    @BindView(R.id.rl_app_name)
    RelativeLayout mRlAppName;
    @BindView(R.id.tv_user_account)
    TextView mTvUserAccount;
    @BindView(R.id.rl_second_title)
    RelativeLayout mRlSecondTitle;
    @BindView(R.id.tv_home_second_title)
    TextView mTvHomeSecondTitle;

    @Override
    protected int getLayoutId() {
        return R.layout.activity_home;
    }

    @Override
    protected void onViewCreated() {
        super.onViewCreated();
        mTvUserAccount.setText(Constants.USER_BUBBLE_COUNT);
    }

    @Override
    protected void initViewAndData() {

        Fragment fragment = findFragment(HomeFragment.class);
        if (fragment == null) {
            loadRootFragment(R.id.fl_container, HomeFragment.newInstance());
        }
    }

    /**
     * 设置二级标题
     *
     * @param seconditle
     */
    public void setSecondTitle(String seconditle) {
        mRlSecondTitle.setVisibility(View.VISIBLE);
        mTvHomeSecondTitle.setText(seconditle);
    }

    /**
     * 二级标题消失
     */
    public void dismissSecondTitle() {
        mRlSecondTitle.setVisibility(View.INVISIBLE);
    }

    @OnClick({R.id.rl_app_name, R.id.img_home_help})
    public void onViewClicked(View view) {
        switch (view.getId()) {
            case R.id.rl_app_name:
                getTopFragment().setFragmentAnimator(new DefaultNoAnimator());
                popTo(HomeFragment.class, false);
                dismissSecondTitle();
                //        start(TestFragment.newInstance());
                break;
            case R.id.img_home_help:
                ISupportFragment supportFragment=getTopFragment();
                if (HelpFragment.newInstance().getClass() != supportFragment.getClass()){
                    start(HelpFragment.newInstance());
                }

                break;
        }

    }

}

问题：

点击 id是img_home_help这个按钮后，会闪下屏幕，之后跳转到HelpFragment，但是之后再点击就没有这个问题了，只有第一次点击时会出现

**Comment by YoKeyword** [comment]
闪烁问题一般是因为 `show` 和 `hide`没有同步进行，但是`start()`内部是 add + show + hide的联合事务，按道理应该不会存在闪烁问题...

你可以在`start()`后面，加上`getSupportFragment().executePendingTransactions()`让起其立即执行试试看

**Comment by Greathfs** [comment]
那个按钮是在AC中的，是不是因为这个原因；如果不用start这个方法，不知还有其他方法能在AC中切换Fragment吗？ 

另外大神问下，我在AC中getSupportFragment().executePendingTransactions()这个方法找不到啊

**Comment by YoKeyword** [comment]
不好意思，打错了 是：`getSupportFragmentManager().executePendingTransactions();`

`start()`本质是在栈内 add + show +hide，Activity中的`start()`内部是 `getTopFragment().start()`

**Comment by klqxx** [comment]
你好，问题解决了吗，我也遇到这个问题了 。我这边的是每次点都会闪一下 Fragment画面，之后跳转到Fragment
