### ISSUE TITLE
转场动画失效

### ISSUE THREAD

**Issue by strahe** [YoKeyword/Fragmentation#536]
Hi, 
我是新手,  我按照wiki上配置了转场动画,但是无论在mainactivity 还是 单个fragment中都不生效, 默认是没有的, (Fragmentation并不是今天才使用,已经用了一个多月了,其他地方暂时没遇到问题), 
希望能帮我排查一下,谢谢.

**Comment by LonelyMushroom** [comment]
能提供下你配置的代码么

**Comment by strahe** [comment]
@LonelyMushroom hi, 我的项目是仿照demo的wechat来的,结构上看基本是抄过来的, 在 APP.kt里,
```
Fragmentation.builder()
                .debug(BuildConfig.DEBUG)
                .install()
```

然后在MainActivity.kt 里,
```
    override fun onCreateFragmentAnimator(): FragmentAnimator {
        // 设置横向(和安卓4.x动画相同)
        return DefaultVerticalAnimator()
    }
```

我也尝试过单独在fragment里设置,依然没有效果.

**Comment by YoKeyword** [comment]
@strahe 
模拟下场景，简化问题： 新建一个Demo，AC里`load`一个Fragment，然后 `start`另一个Fragment，不做任何动画相关的配置，看下是否有动画

如果依然没有动画，再简化问题: 使用java来模拟上述场景，排查是否有写法问题

**Comment by hadisi5216** [comment]
楼主什么问题？我也怎么设置都不起作用

**Comment by strahe** [comment]
@hadisi5216 按作者的提示, 新建一个demo时是没有问题的, 但在我的项目中一直不起作用, 现在依然没有解决, 关于 Fragmentation 的代码和配置本身代码量不多, 都一一对应检查过了没查出问题, 安卓开发也在学习阶段, 还没有深入研究.

**Comment by YoKeyword** [comment]
@strahe 新建Demo没问题的话，那么检查下 你主工程的AndoridManifest等配置，看是否是可疑配置的问题

**Comment by strahe** [comment]
@YoKeyword @hadisi5216 
Hi, 关于前面说的转场动画失效, 我发现了一个问题, 
我的`MySupportFragment`中的`onCreateAnimation`方法:
```
override fun onCreateAnimation(transit: Int, enter: Boolean, nextAnim: Int): Animation {
        return mDelegate.onCreateAnimation(transit, enter, nextAnim)
```
如果我写成上面这样, 返回的是`null`, 并且会报错,  如果我删掉这部分代码(不override), 不会报错, 但就没有转场动画,如我前面所说, 

我看了下SupportFragmentDelegate中的`onCreateAnimation`实现, 具体实现看不太懂, 但知道有返回null的情况,  所以我在`MySupportFragment`中的`onCreateAnimation`方法中强制去null, 转场动画就有了.
```
override fun onCreateAnimation(transit: Int, enter: Boolean, nextAnim: Int): Animation {
        val m = mDelegate.onCreateAnimation(transit, enter, nextAnim)
        if (m == null){
            val mAnimHelper = AnimatorHelper(_mActivity.applicationContext, fragmentAnimator)
            return mAnimHelper.noneAnim // 这里随便写了一个
        }else{
            return m
        }
```
不知道作者有没有思路这是什么情况?

**Comment by YoKeyword** [comment]
应该和`kotlin`写法有关，看下这个issue #500  是否有帮助
