### ISSUE TITLE
关于内存回收的问题

### ISSUE THREAD

**Issue by yygutn** [YoKeyword/Fragmentation#537]
这几天在排查内存泄漏问题，发现App几乎所有的Activity/Fragment引用都没有被销毁，最后想到是不是跟Fragmentation有关系，所以单独对Demo做了一个内存分析，发现把Demo所有的页面随便点点之后退到选择页面，还有一些Fragment和Activity没有被销毁
![2017-08-31 11 10 08](https://user-images.githubusercontent.com/8274198/29904768-ff2a253e-8e3c-11e7-8aba-899e0392f6d5.png)

![2017-08-31 11 11 15](https://user-images.githubusercontent.com/8274198/29904796-23fd2b90-8e3d-11e7-8235-56848c5df85d.png)

**Comment by YoKeyword** [comment]
之前有集成LeakCanary测试过Demo的内存泄漏情况，情况良好～

你的截图我无法判断是否泄漏，类的图标上没有橙色 GC Roots访问到的标记，也没有显示该类被谁管理的

你的测试结果是HomeFragment和DetailFragment内存泄漏是嘛？ 

另外你的测试结果是EnterActivity也内存泄漏？ EnterActivity继承自AppCompatActivity，内部只是放3个按钮，和3个点击监听

**Comment by yygutn** [comment]
不好意思，忘记给你回复了，Demo内存回收情况良好，就是回收的很慢。。。
我司的App内存泄漏是因为跨平台的原因，涉及到双内存堆+循环引用问题了-_-!!!
