### ISSUE TITLE
回退问题 

### ISSUE THREAD

**Issue by zilingyao** [YoKeyword/Fragmentation#538]
![image](https://user-images.githubusercontent.com/16448548/29909804-244ddc26-8e5a-11e7-82ec-33f411b8b1eb.png)
在栈视图里显示 三个fragment是层级关系 但我在TableManageFragment中点击返回时 getChildFragmentManager().getBackStackEntryCount()=0  这时不应该是返回上一级fragment吗？

**Comment by YoKeyword** [comment]
如果没有复写`onBackPressed()`和`onBackPressedSupport()`的话，Back键默认：
````java
 public void onBackPressedSupport() {
        if (getSupportFragmentManager().getBackStackEntryCount() > 1) {
            pop();
        } else {
            ActivityCompat.finishAfterTransition(mActivity);
        }
    }
````

即判断FragmentActivity的那层回退栈的Fragments数量是否大于1，  你的场景下类似知乎Demo，因为几个`DinnerFragment`,`BasicRootFragment`等都没有加入回退栈，所以走了else，即关闭Activity

如果你期望：在pop `TableManageFragment`后，回到`BasicDataFragment`，只需要在`TableManageFragment`里拦截掉BACK事件即可：
```java
@Override
 public boolean onBackPressedSupport() {
     pop();
     return true;
}
```

**Comment by zilingyao** [comment]
你好 我在TableManageFragment中添加您说的上述代码 并没有生效  断点显示没有走这个方法 不知道怎么回事 TableManageFragment继承的SupportFragment方法！

**Comment by YoKeyword** [comment]
在Activity的 `onBackPressed()`里断点，看下怎么分发的

**Comment by zilingyao** [comment]
这个不太会搞啊 大神 方便qq沟通吗 1961887727 或者您说的稍微详细点 麻烦了 谢谢
