### ISSUE TITLE
隐藏软键盘的方法，在有些机型版本上无效

### ISSUE THREAD

**Issue by GongZiZhang** [YoKeyword/Fragmentation#539]
使用三星n9002 ,在安卓4.3版本上，调用基类封装的隐藏键盘的方法，无效

**Comment by Mr-PolarBear** [comment]
Activity模式设置为 android:windowSoftInputMode="stateUnspecified" 试试

**Comment by YoKeyword** [comment]
@GongZiZhang `hideSoftInput()`写在哪个生命周期里的呢？
尝试调用下`SupportHelper.hideSoftInput(_mActivity.getWindow().getDecorView());`

**Comment by GongZiZhang** [comment]
@YoKeyword hideSoftInput是调用SupportFragment基类里的，尝试了SupportHelper.hideSoftInput(_mActivity.getWindow().getDecorView());也是不能成功关闭键盘

**Comment by YoKeyword** [comment]
> 按照官方文档，第一个参数中的windowToken应当是之前请求显示软键盘的View的windowToken，也就是执行showSoftInput()时第一个参数中的View的windowToken。

> 但是实际情况是，用任意一个当前布局中的已经加载的View的windowToken都可以隐藏软键盘。 所以库中使用的是Fragment的View

最后杀器，使用`SupportHelper.hideSoftInput(editText);`   (editText为你 弹出软键盘对应的那个输入框)

或者postDelay 200ms再hide试试
