### ISSUE TITLE
SwipeBackFragment滑动返回

### ISSUE THREAD

**Issue by 121919251** [YoKeyword/Fragmentation#540]
你好，我在项目中使用SwipeBackFragment滑动返回完成后，界面会闪一下，好像滑动结束后有个动画效果。如果按返回键返回没有这个闪的现象出现，能帮我分析一下可能是什么原因导致的吗？

**Comment by YoKeyword** [comment]
Fragmentation版本， v4版本 提供下
每一个页面滑动返回都有这个问题吗？  
看Demo会有这个问题吗？

**Comment by 121919251** [comment]
Demo没有这个现象，好像是换了ISwipeBackFragment接口实现的方式出现的，无法设置水平移动动画，始终时默认动画。能在Demo中给出这种接口方式实现的示例吗?

**Comment by YoKeyword** [comment]
拷贝`SwipeBackFragment`里的代码到自己的SwipeFragment里即可
