### ISSUE TITLE
loadRootFragment 无动画

### ISSUE THREAD

**Issue by cgalaxy** [YoKeyword/Fragmentation#541]
在activity 布局里有一个占位的framelayout，点击事件会给framelayout 加载 fragment，给framelayout 加载第一个fragment 使用loadRootFragment，没有动画～没有动画～没有动画，使用    public void loadRootFragment(containerId, toFragment,true, true),也没有动画，怎么办 啊啊啊 ，动画去哪里了。试了很多次还是没有辙。请求帮助～～～谢谢

**Comment by cgalaxy** [comment]
如果方便，我的qq 1316760523，这样沟通更直接，麻烦啦～

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/459 你看看这个对你有帮助么

**Comment by cgalaxy** [comment]
#459 是 start( fragment ), 在activity里只能loadRootFragment 呀～ 我在onclick里 这样写试过，没有loadRootFragment 没动画
FragmentA fragmentA = new FragmentA();
 fragmentA.setFragmentAnimator(new FragmentAnimator(R.anim.slide_top_in, R.anim.slide_top_down));
 loadRootFragment(R.id.fl_container, fragmentA, true, true);
再帮我想一下吧～～～麻烦啦

**Comment by iWynn** [comment]
loadRootFragment 并没有提供动画功能，这个动画需要你自己给framelayout 添加动画效果。动画效果是一进一出时才会有，loadRoot显然只有一个fragment，没有动画很正常啊，你可以loadRootFragment先添加一个空白fragment A，然后在这个fragment A里 start(B)，启动真正的fragment.

**Comment by YoKeyword** [comment]
@iWynn  @cgalaxy @LonelyMushroom `loadRootFragment(int containerId, ISupportFragment toFragment, boolean addToBackStack, boolean allowAnim)` 在`loadRootFragment(containerId, toFragment,true, true)`时设计是有动画的，只是这是个BUG...  导致使用该方法时，动画无效了

已修复`compile 'me.yokeyword:fragmentation:1.1.4'`
