### ISSUE TITLE
如何控制 SwipeLayout 滑动的触发位置?

### ISSUE THREAD

**Issue by yangjieK** [YoKeyword/Fragmentation#542]
SwipeLayout  只能在屏幕上的最左侧 和最右侧, 如何能在屏幕中间位置或者 1/3的位置滑动?

**Comment by LonelyMushroom** [comment]
拦截你当前需要屏幕中间位置或者 1/3的位置滑动页面的滑动事件,重写SwipeLayout 的滑动监听,大概是这个思路

**Comment by YoKeyword** [comment]
@yangjieK 这个滑动区域临界是`ViewDragHelper `控制的。
如果想更改，需要你去fork项目并替换成自己实现的`ViewDragHelper`。

另外`ViewDragHelper`这么设计，是为了可以很好的ViewPager等滑动组件并存
