### ISSUE TITLE
startForResult偶尔失效，拿不到返回值

### ISSUE THREAD

**Issue by rch0903** [YoKeyword/Fragmentation#545]
如题，大部分情况下startForResult()是可以正常使用并拿到返回值的，但是偶尔会发生拿不到返回值的情况，请教下这是什么原因？我用的是1.1.3的

**Comment by YoKeyword** [comment]
`startForResult(targetFragment)`  在targetFragment  `setResult()`并且出栈时，回调**上一个Fragment**（不管谁startForResult()的，回调的是targetFragment的上一个Fragment) `onFragmentResult()`

拿不到时的情况，观察下栈视图

**Comment by rch0903** [comment]
![image](https://user-images.githubusercontent.com/13358882/30311894-ecbb9a2c-97c9-11e7-9311-fe8d09db053d.png)
正常在栈视图中，F在E之上，可以拿到值，今天的异常情况是E在F之上，所以拿不到值。
我没有设过启动模式，按理说不应该出现这样的状况啊

**Comment by rch0903** [comment]
这种情况很少见，今天才又遇到一次/(ㄒoㄒ)/~~

**Comment by YoKeyword** [comment]
你的栈视图似乎有点问题，A `start` D，这样是不允许的， 因为A是未加入回退栈的，这样可能会引起栈内顺序的异常

> 记住一个原则： 避免在未加入回退栈的层级内去start()其它Fragment， 比如ViewPager、loadMultiRootFragment()、FragmentTabHost内部的Fragment不可以直接start，这种情况下其内的栈应该保持干净，如果想启动其它Fragment，应该由它们的父Fragment或子Fragment去start

建议使用MainFragment去`start`，即第二个Demo的栈视图,可以参考下第二个Demo

E在F之上的话，说明栈内已经异常错乱了， 栈内顺序对的话`startForResult`才会正常

**Comment by rch0903** [comment]
@YoKeyword 谢谢，我将A-D的start改为getParentFragment.start试下

**Comment by LonelyMushroom** [comment]
getParentFragment.getTop比较好点,到时候你跟main同级的也加了的话不会出现什么问题
