### ISSUE TITLE
新版本BUG

### ISSUE THREAD

**Issue by douya40** [YoKeyword/Fragmentation#546]
新版本进行页面跳转EventBus.getDefault().post(new StartBrotherEvent(LoginFragment.newInstance())); 会报错java.lang.IllegalStateException
Fragment already added: LoginFragment{cf80ce2 #3 id=0x7f0d009e com.laima365.mjmk.ui.fragment.dl.LoginFragment}，之前老版本没有报错

**Comment by YoKeyword** [comment]
Exception: `Fragment already added`

原因是 接收该Event的 接收方Fragment，在栈内不止一个实例， 比如栈内有2个接收方Fragment的实例，此时都会收到该event，去`start(loginFragment)`，导致`already added`

处理方式： 如果层级不深，不建议使用EventBus，建议通过拿到目标层级栈的Fragment直接`start`
比如这个 commit的方式： 9bc0b1f
