### ISSUE TITLE
我的项目都是activity,activity继承SwipeBackActivity 滑动关闭没有联动效果

### ISSUE THREAD

**Issue by kuangzhe** [YoKeyword/Fragmentation#547]
还有滑动关闭页面如果弹出软键盘没有关闭软键盘

**Comment by YoKeyword** [comment]
联动效果是指？

没有关闭软键盘可以在`onDestroyView()`里手动调用`hideSoftInput();`

**Comment by kuangzhe** [comment]
我写了但是没关闭，然后写在滑动监听让消失了。联动效果是就是仿微信的上面有滑动下面的activity也有动画效果，现在下面没有滑动效果光上面有滑动效果。

**Comment by kuangzhe** [comment]
我页面的都是activity,activity包含fragment

**Comment by YoKeyword** [comment]
当前版本不支持`onDestroy()`这个生命周期里`hideSoftInput()`，建议在`onDestroyView()`之前的生命周期调用，一般在`onSupportInvisible()`中调用；
下个版本v1.1.7 会优化，让其在`onDestroy()`中也支持。

Activity没有联动效果（目前的实现机制 无法让Activity有联动效果），仅支持Fragment

**Comment by kuangzhe** [comment]
恩，好的，谢谢大神，我后面键盘关闭写在        /** 滑动关闭页面监听 */
        getSwipeBackLayout().addSwipeListener(new SwipeBackLayout.OnSwipeListener() {
            @Override
            public void onDragStateChange(int state) {
                // Drag state
            }

            @Override
            public void onEdgeTouch(int edgeFlag) {
                // 触摸的边缘flag
                World.getInstance().hideSoftKeyboard(BaseActivity.this);
            }

            @Override
            public void onDragScrolled(float scrollPercent) {
                // 滑动百分比
            }
        });方法里面了，我感觉写到这里效果比较好，以后互相学习多交流
