### ISSUE TITLE
关于loadMultipleRootFragment的问题

### ISSUE THREAD

**Issue by 330676687** [YoKeyword/Fragmentation#548]
我在某个fragment里 通过loadMultipleRootFragment来加载多个子fragment 但是在返回上一个fragment的时候 返回动画中子fragment布局会消失 动画是横向 而通过viewpager加载却没有问题 版本是1.1.4 请问这个问题该怎么修复呢

**Comment by YoKeyword** [comment]
@330676687  这是因为父Fragment出栈时，子Fragment的动画return null，即无动画，所以在父
 Fragment出栈动画时子Fragment因为无动画，所以直接被remove，视觉上布局消失

`viewpager`里做了兼容处理，`loadMultipleRootFragment `遗漏了

已兼容发布，`compile 'me.yokeyword:fragmentation:1.1.5'`
