### ISSUE TITLE
关于切换动画的问题

### ISSUE THREAD

**Issue by Greathfs** [YoKeyword/Fragmentation#549]
版本：1.0.7

操作：
点击回到首页Fragment
 getTopFragment().setFragmentAnimator(new DefaultNoAnimator());
                popTo(HomeFragment.class, false);
点击了几次后发现，以后切换界面动画不对了，好像是变成了默认的那个横向的了，不是按照我自己定义的动画执行了

**Comment by Greathfs** [comment]
问题已解决

发现是这个问题：当我的HomeFragment是TopFragment时，我调用getTopFragment().setFragmentAnimator(new DefaultNoAnimator());
应该就是把全局的切换动画改变了吧

我现在的解决办法是：
点之前加个判断
ISupportFragment topFragment=getTopFragment();
                if (HomeFragment.newInstance().getClass() != topFragment.getClass()){
                    getTopFragment().setFragmentAnimator(new DefaultNoAnimator());
                    popTo(HomeFragment.class, false);
                    dismissSecondTitle();
                }
试了试 好像可以了

**Comment by YoKeyword** [comment]
如果是在使用v1.1.3+，`popTo(HomeFragment.class, false, null, 0);`
如果v1.1.3- ,``popTo(HomeFragment.class, false, null, R.anim.no_anim);``

**Comment by Greathfs** [comment]
嗯 有时间升级下 我现在用的是1.0.7那个版本
