### ISSUE TITLE
ViewPager中添加多个Fragment，在Fragment中startForResult启动以后接收不到返回值呢

### ISSUE THREAD

**Issue by ggchxx** [YoKeyword/Fragmentation#55]
ViewPager中添加多个Fragment，在Fragment中startForResult启动以后接收不到返回值呢
使用场景
1.在ViewPager中添加FragmentA,FragmentB
2.FragmentA使用stratForResult启动ChildFragment
3.ChildFragment中 setFragmentResult然后pop
4.在FragmentA的onFragmentResult方法中接收不到返回值

**Comment by YoKeyword** [comment]
@ggchxx  原则上是：startForResult的目标Fragment的前一个兄弟Fragment可以接收到返回值。
你检查下， 建议在复杂场景下使用EventBus来传递数据   startForResult这部分建议在简单场景下使用 :)
