### ISSUE TITLE
startForResultDontHideSelf 没有返回值

### ISSUE THREAD

**Issue by prayxiang** [YoKeyword/Fragmentation#550]
SupportFragment 内调用， extraTransaction().setCustomAnimations(0, 0)
                .startForResultDontHideSelf(fragment,1)拿不到返回值
 startForResult(fragment,1)正常
用的 1.1.4

**Comment by YoKeyword** [comment]
已Fix ： e1686f7

`compile 'me.yokeyword:fragmentation:1.1.5'`
