### ISSUE TITLE
rootfragment的onEnterAnimationEnd会执行两次

### ISSUE THREAD

**Issue by pye52** [YoKeyword/Fragmentation#551]
#541 修复了rootfragment无动画的问题之后，其onEnterAnimationEnd会执行两次。看了一下源码…发现在onActivityCreated会直接调用notifyEnterAnimEnd，然后动画完了之后又再次调用。而文档里说的是
> 该方法会在转场动画结束后调用，如果没有动画则在onActivityCreated时调用，此时在onEnterAnimtionEnd(Bundle saveInstanceState)里初始化复杂数据，可以避免保证Fragment动画的流畅。

那么数据就会被初始化2次了…

**Comment by YoKeyword** [comment]
感谢，今晚发布 v1.1.6
