### ISSUE TITLE
AC 和FG 的生命周期回调问题

### ISSUE THREAD

**Issue by programer-liang** [YoKeyword/Fragmentation#554]
现在创建了两个AC,里面都有多个FG，两个AC的关系是A -> B（正常启动 ）
当我app 最小化的时候，B(AC)中的FG onstop 都会调用，A(AC)中的FG的onstop 也会全部调用到，这是什么原因造成的？

我的项目中 BaseActivity 继承  ISupportActivity，BaseFragment 继承  ISupportFragment，基本上和Demo 上没区别

**Comment by LonelyMushroom** [comment]
当activity不可见时会执行onStop方法,而fragment是依附于activity的.我觉得这种想象应该是正常的.

> 当我app 最小化的时候

**Comment by programer-liang** [comment]
两个问题
1. 我在Activity  A   启动  Activity  B之后，最小化的时候，B的onstop  回调的同时  A的onstop  也回调了
2.我在Fragment A start    Fragment B   
Fragment B start Fragment C
这个时候最小化的时候 A,B,C 的onstop 都回调的到了

PASS： 同样的请求也发生在Activity 和 Fragment 的onstart 回调里

**Comment by programer-liang** [comment]
两个问题

我在Activity A 启动 Activity B之后，最小化的时候，B的onstop 回调的同时 A的onstop 也回调了
2.我在Fragment A start Fragment B
Fragment B start Fragment C
这个时候最小化的时候 A,B,C 的onstop 都回调的到了
PASS： 同样的情况也发生在Activity 和 Fragment 的onstart 回调里

**Comment by LonelyMushroom** [comment]
你的意思是重复调用了?贴下你的版本号,栈视图

**Comment by programer-liang** [comment]
![image](https://user-images.githubusercontent.com/10324223/30467889-6435636a-9a1a-11e7-8b7e-d93fa9bd4d27.png)
我是clone 源码的，不过底层的代码是没有变过的


这是第一个Activity栈视图
![image](https://user-images.githubusercontent.com/10324223/30467994-1ad089a6-9a1b-11e7-9c4d-f344281e29b7.png)

这是第二个Activity栈视图
![image](https://user-images.githubusercontent.com/10324223/30467921-8e42a9f6-9a1a-11e7-8d9b-2082fb4f3120.png)

我在第二个Activiy ，处在这个界面的时候我把app最小化
onstop 执行顺序是：LoadActivity  ->LoadFragment ->  HomeActivity ->MenuFragment  ->CaocaoMapFragment ->HomeSecondFragment ->HomePageFragment ->SearchFragment ->VipMainFragment -> HomeFragment

**Comment by LonelyMushroom** [comment]
是的,LoginAC在底层,所以先调用login的stop,然后fg的onstop掉用顺序是从栈视图的底层往上调用,有层级数据先调用外层再调用里面底部,但是  我这边调用是先调用完FG的onstop再调用AC的stop.不知道你这个怎么回事,等作者来看看吧
```
onStop: GankTabFragment----
onStop: GirlDetailFragment--------
onStop: GirlDetailFragment--------
onStop: GirlDetailFragment--------
onStop: MainActivity-------
```
MainAC->GankTabFragment->GirlDetailFragment->GirlDetailFragment->GirlDetailFragment

**Comment by programer-liang** [comment]
嗯，我现在是想修改源码，但不知道这个生命周期回调的入口再哪里

**Comment by YoKeyword** [comment]
@programer-liang  测试你的Activity设置了`<item name="android:windowIsTranslucent">true</item>`， 该属性会使Activity在跳转其他Activity时不走`onStop`(`onPause`走的)

库中`SwipeBackActivity`的实现方式基于[SwipeBackLayout](https://github.com/ikew0ng/SwipeBackLayout)，该实现机制需要`<item name="android:windowIsTranslucent">true</item>`，但是会有如上所说的副作用

2个解决方式：  
* 找一种实现策划返回的方式，比如[and_swipeback](https://github.com/XBeats/and_swipeback)，通过 实现＋委托 即可实现
* 考虑是否可以  不使用侧滑返回功能

**Comment by programer-liang** [comment]
好的，非常感谢，我研究一下

**Comment by programer-liang** [comment]
是的，我有几个界面是想做右滑关闭activity 的
如果不配置这个属性的话后面会显示当前界面的window 背景，导致看不到底下的视图
非常感谢你的提醒，现在知道了配置这个属性的意义了
   <item name="android:windowIsTranslucent">true</item>

想了一下还是把这个属性去掉，不集成拖动关闭了
