### ISSUE TITLE
栈视图顺序有疑问

### ISSUE THREAD

**Issue by cizkey** [YoKeyword/Fragmentation#555]
不好意思, 我之前没有弄清问题的本质. 以为是onBackPressedSupport()的问题. 
经查, 是栈视图的顺序问题.

版本 1.0.6   
start页面的方式为EventBus通知MainFragment去startBrother

页面依次打开为  MainFragment -- > BFragment --> CFragment (在最顶层)
此时的栈视图为 
BFragment
CFragment
MainFragment

不知道为啥在启动CFragment后, 并且该Fragment显示在最上层时, 栈视图中是BFragment在栈顶? 

// Note: 原来的问题. 已经查明不是onBackPressedSupport()的问题了. 仅仅是为了以下回复阅读的连贯性. , 暂且留在这里吧
我在A页面重写了onBackPressedSupport(), 点击返回键发现没有回调该方法. 
但是我start()了几个重复的A页面. 点击返回键发现那些重复的页面会回调onBackPressedSupport(). 只有第一个A页面不会执行onBackPressedSupport().  不知道这是为什么? 
另外您写的那个注释  前提是SupportActivity的onBackPressed()方法能被调用  没有看懂.......

**Comment by LonelyMushroom** [comment]
你的 onBackPressedSupport 方法是怎么写的,能贴下代码么
```
    @OnClick(R.id.iv_girl_detail)
    public void onViewClicked() {
        onBackPressedSupport();
    }

    @Override
    public boolean onBackPressedSupport() {
        pop();
        return true;
    }
```

**Comment by cizkey** [comment]
我仅仅是打印了日志而已. 

我发现一个比较疑惑的问题. 


![yemian](https://user-images.githubusercontent.com/14026236/30464331-91c4a7f8-9a03-11e7-8bf5-ac63e6db5078.png)

如上图.  
A --> Activity
B --> BFragment
C --> CFragment
C --> CFragment

我在 BFragment, CFragment 中重写onBackPressedSupport(). 仅仅分别打印B, C页面的名字,直接return super.onBackPressedSupport();
在Activity中重写onBackPressedSupport(), 仅仅打印A页面的名字.

我点击三次返回键依次得到的结果为:
回调了C页面的onBackPressedSupport
回调了Activity的onBackPressedSupport
回调了B页面的onBackPressedSupport
回调了Activity的onBackPressedSupport
回调了B页面的onBackPressedSupport
回调了Activity的onBackPressedSupport

当我再次已相同的方式打开页面, 点击三次返回键依次得到的结果为:
回调了C页面的onBackPressedSupport
回调了Activity的onBackPressedSupport
回调了C页面的onBackPressedSupport
回调了Activity的onBackPressedSupport
回调了B页面的onBackPressedSupport
回调了Activity的onBackPressedSupport

看到这个结果我震惊了?  为什么会有这样的情况出现.  完全弄不清楚. 

我测试了很多次. 发现这两种打印结果总是交替出现. 不知道是什么问题. 

使用版本 1.0.6

**Comment by LonelyMushroom** [comment]
你震惊的原因是因为onBackPressedSupport的回调方式是fg->ac,fg->ac吗,如果是这样的话你可以看看作者的源码,我感觉大概是为了处理1个ac多个fg怎么控制是fg的pop(),还是ac的finish().
至于你onBackPressedSupport失效的原因大概知道了
```
@Override
    public boolean onBackPressedSupport() {
        pop();
        return true; //你必须返回ture而不是super.onBackPressedSupport();原因是false则继续向上传递, true则消费掉该事件
    }
```

**Comment by cizkey** [comment]
不是的. 另我震惊的是我执行的操作一样.  页面展示出来的层次是  A - B - C - C ,但是返回的结果却不同. 
 
您可以看到我第一种打印的结果依次是   C - A - B - A - B - A
而我第二种打印的结果却是                    C - A - C - A - B - A

显然, 在一般的需求下, 第二种才算是正确的backpress键调用的结果.  可是却有几率出现第一种的情况. 
我不是很理解这个问题.

**Comment by LonelyMushroom** [comment]
你贴下start,以及onBackPressedSupport等关键代码,还有你的版本号,和栈视图.

**Comment by cizkey** [comment]
您好, 我看了下我的栈视图.  确实发现可能不是onBackPressedSupport()的问题.
是栈中Fragment位置的问题. 不知道为什么, 我界面上显示的最上层是CFragment.  
但是栈顶确实BFragment. 

界面显示层次
C - B - A   (越左边越显示在上面)

栈视图为
BFragment
CFragment
MainFragment

我start()的方式和demo中一样.  在MainFragment中
    @Subscribe(threadMode = ThreadMode.MAIN)
    public void startBrother(Event.StartBrother event) {
        start(event.targetFragment);
    }

不知道为什么BFragment会跑到CFragment的顶上, 而且在界面上看不到.  

版本 1.0.6

**Comment by YoKeyword** [comment]
@cizkey  首先建议升级到最新版v1.1.6

栈视图顺序异常，看到你用了EventBus，在新的Demo里，不是很建议使用EventBus来跳转了，（除非层级比较深、复杂）， 建议使用[这样的方式启动](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_wechat/ui/fragment/first/WechatFirstTabFragment.java#L105)

因为EventBus虽然是个使用起来很简单的库，但是在Fragment中，处理不好可能会导致一些问题

B和C的顺序异常：B是Main通过eventbus启动的， C是怎么被启动的呢？    B和C是否同时被`start()`？

**Comment by cizkey** [comment]
@YoKeyword 感谢您的回复.   我刚更新到最新的v1.1.6, 因为页面跳转太多, 所以还是使用的eventbus方式.

B和C都是已同样的方式启动的,都是在MainFragment通过Eventbus启动的. 不是同时启动B和C. 
先启动的B页面, 在B页面中有一个按钮, 点击启动C页面.  在界面上展示出来为C在B的上面.

大致流程如下:
![default](https://user-images.githubusercontent.com/14026236/30506176-61119086-9aac-11e7-94c2-d6a3f7868817.png)
 
我却在数次点击之间得到了两种不同的栈视图. 这个让我比较困惑. 
![11](https://user-images.githubusercontent.com/14026236/30506202-967dc816-9aac-11e7-9e3a-acf6ea4656b2.png)
![22](https://user-images.githubusercontent.com/14026236/30506207-a19bb8b6-9aac-11e7-9bbf-ae286fedfe89.png)

**Comment by Koihik** [comment]
@cizkey 我这边把android的support包升级到25.4.0以后解决了这个问题.

**Comment by YoKeyword** [comment]
@cizkey  你可以看下wechat_demo， 和你场景一样，栈顺序一直是正确的， 另外Main到B用EventBus可以理解， B到C，直接`B.start(C)`就可以了

@Koihik  25.4.0后，官方内部机制进行了一个优化，避免绝大部分 栈顺序可能异常的坑

**Comment by cizkey** [comment]
@Koihik @YoKeyword 深表感谢. 我更新了support包, 25.4.0之后, 确实没有这个问题了. 我再研究研究一下demo. 谢谢.
