### ISSUE TITLE
状态恢复后，showHideFragment 出现空白页

### ISSUE THREAD

**Issue by LichFaker** [YoKeyword/Fragmentation#556]
布局结构跟`demo_wechat`一致，栈视图为：

1. MainFragment
1.1 FirstFragment
1.2 SecondFragment
1.3 ThirdFragment
1.4 FourthFragment

在内存不足的情况下，
* 若当前显示页面为`FirstFragment`， 且`ThirdFragment`未曾显示过， 则`MainFragment`销毁重建后，调用`showHideFragment`显示`ThirdFragment`页面为空白；
* 若`ThirdFragment`显示过则能正常恢复显示，但在布局背景色未指定的情况下有布局重叠问题，指定背景色后正常

**Comment by YoKeyword** [comment]
既然是和wechat一致，下载Demo：https://www.pgyer.com/fragmentation

看Demo是否有你所描述的问题

**Comment by LichFaker** [comment]
找到原因了，销毁时`ThirdFragment `中的`onSaveInstanceState` 没有调用， 但`onLazyInitView 中的savedInstanceState不为null`.
导致有些数据为空了没有显示出来。
