### ISSUE TITLE
app插件化有计划支持吗

### ISSUE THREAD

**Issue by douya40** [YoKeyword/Fragmentation#557]
https://github.com/Qihoo360/RePlugin  最近这个慢火的，测试对接了，发现不activity-->fragment的模式不加载出页面

**Comment by YoKeyword** [comment]
RePlugin很cool, 初步看了下，讲道理应该是支持的， 回头我会研究下  :)

**Comment by 456838** [comment]
Replugin实例化Fragment感觉比较坑，然后想通过路由来实例化Fragment，结果360的开发跟我说不支持artouter，Replugin这方面有待提高。我打算放弃replugin了，改用atlas+artouter做组件化了。
