### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by anddzk** [YoKeyword/Fragmentation#558]
作者你好，不知道你有没有遇到过这个问题，我在项目中并没有重写onAnimationEnd方法，但是不断有项目报这个错误。
android.os.Handler.enqueueMessage(Handler.java:626)
--
 android.os.Handler.sendMessageAtTime(Handler.java:595)
 android.os.Handler.sendMessageDelayed(Handler.java:566)
 android.os.Handler.post(Handler.java:326)
 android.view.View.post(View.java:11123)
 android.support.v4.app.FragmentManagerImpl$AnimateOnHWLayerIfNeededListener.onAnimationEnd(FragmentManager.java:476)
android.support.v4.app.FragmentManagerImpl$AnimateOnHWLayerIfNeededListener.onAnimationEnd(FragmentManager.java:487)
~~~~
~~~~
~~~~重复
[Stack over limit size :20000 , has been cutted !]

**Comment by YoKeyword** [comment]
没遇到过该问题， StackOverflowError一般是因为循环调用，检查下相关代码吧
