### ISSUE TITLE
popto()的动画问题

### ISSUE THREAD

**Issue by nicholaszhou** [YoKeyword/Fragmentation#559]
您好，感谢您开源了这么优秀的fragment管理库。在使用1.1.6版本中我发现了一个问题。
      我现在用继承了SupportActivity的单activity+多fragment的方式创建了工程，在activity中重载了onCreateFragmentAnimator()方法设置了setEnter(),setExit,setPopEnter,setPopExit切换动画。

现在发现调用popTo(Class<?> targetFragmentClass, boolean includeTargetFragment, Runnable afterPopTransactionRunnable, int popAnim)方法切换fragment的时候设置的setPopEnter()动画没有效果，但是用pop()方法是有效的。

**Comment by YoKeyword** [comment]
`popTo(Class<?> targetFragmentClass, boolean includeTargetFragment, Runnable afterPopTransactionRunnable, int popAnim)` 该方法的popAnim是控制当前显示的那个Fragment的离开动画

比如：栈内有A,B,C,D,  在D里 popTo(A,false,null, R.anim.xxx),  这个xxx动画是控制D的离开动画

**Comment by nicholaszhou** [comment]
意思就是说popto()到的页面就没有办法加进入的动画呗？

**Comment by YoKeyword** [comment]
进入动画 ？ 这是个出栈方法为什么会有进入动画... 

或者你的意思是afterPopTransactionRunnable里 你start了newFragment？   如果是这样的话，newFragment的动画是可以通过`onCreateFragmentAnimator `或者`setFragmentAnimator()` 来设置

或许你贴下 设置动画和`popTo`代码  或 gist 会更方便帮你定位问题

**Comment by nicholaszhou** [comment]
您好，我做了个简单的demo，您看一下：https://github.com/nicholaszhou/fragmenttest，现在点击BlankFragment2里的pop和popto按钮的效果是不一样的~

**Comment by YoKeyword** [comment]
emmm，是我遗忘了，目前`popTo()`到的页面确实是没有动画的：
原因是v4-25.4.0以下的版本，同时出栈多个Fragment可能会引起栈顺序异常的官方BUG，所以Fragmentation的修复方式是：`popTo()`无动画（看到的出栈动画其实是模拟的），接着栈内第一时间纠正顺序，相关源码在[这里](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java#L519)

在25.4.0后官方修复了栈顺序异常的BUG，所以理论上是可以在高版本上优化`popTo()`的，但是还不确定在 动画执行期间，再执行其他Fragment事务会不会异常，后续会进行测试的

**Comment by nicholaszhou** [comment]
好的，多谢~
