### ISSUE TITLE
关于demo 知乎 的写法。

### ISSUE THREAD

**Issue by wjehovah** [YoKeyword/Fragmentation#56]
@YoKeyword 发现 四个Fragment 都只是一个容器，里面都用子 Fragment 来实现。

请问下 这样写 是 为了演示 嵌套 Fragment 吗？  这种写法 和 直接用 ，比如 ZhihuFirstFragment  直接 改为 FirstHomeFragment  各有什么 优劣？

**Comment by YoKeyword** [comment]
@wjehovah 新版知乎的交互方式 你可以研究下， 如果想做到它那种交互方式，就得用我仿知乎Demo里的Fragment结构设计～

其实我们大多数用的交互设计是 仿微信／QQ的那个Demo

优势的话：其实就是独特的交互方式。 劣势就是栈关系比较复杂，从栈视图也可以看出来，构建难度比较大 :)

**Comment by wjehovah** [comment]
![2016-08-12 2 53 36](https://cloud.githubusercontent.com/assets/5822929/17614908/caeef39a-609c-11e6-8bd2-bac2917b44d0.png)

请问这个 ```BottomBar```的```onTabReselected()``` 怎么没有回调，我反复按了好几次。最新的代码

**Comment by YoKeyword** [comment]
我的Demo上表现正常诶～

**Comment by wjehovah** [comment]
@YoKeyword  icon 按两下 才会回调，是这样么？

**Comment by wjehovah** [comment]
@YoKeyword 那就是正常，我理解不对。不好意思
