### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by sunzq19931016** [YoKeyword/Fragmentation#561]
你好 ，我在引导页中倒计时秒钟后用在Activity中用startWithPop()去启动一个Fragment。
但是我在引导页倒计时内按Home退出，会出下如下错误
FATAL EXCEPTION: main
Process: com.sunzq.festec.example, PID: 27865
 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                             android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
                                                                         android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:775)
                                                                          me.yokeyword.fragmentation.TransactionDelegate.executeStartWithPop(TransactionDelegate.java:258)
                                                                       me.yokeyword.fragmentation.TransactionDelegate.startWithPop(TransactionDelegate.java:249)
                                                                          me.yokeyword.fragmentation.TransactionDelegate.dispatchStartTransaction(TransactionDelegate.java:142)
                                                                      me.yokeyword.fragmentation.SupportActivityDelegate.startWithPop(SupportActivityDelegate.java:234)
                                                                         me.yokeyword.fragmentation.SupportActivity.startWithPop(SupportActivity.java:183)

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/522
