### ISSUE TITLE
大神，怎么在子fragment下监听系统返回键？

### ISSUE THREAD

**Issue by andy91310** [YoKeyword/Fragmentation#563]
我需要监听系统返回键，处理具体的业务啊

**Comment by LonelyMushroom** [comment]
监听返回键,并且pop()
```
@Override
    public boolean onBackPressedSupport() {
        pop();
        return true;
    }
```

**Comment by andy91310** [comment]
是不是edittext，这个方法就不走了，我这个fragment下有输入框，我需要监听返回键关闭输入框处理业务操作

**Comment by LonelyMushroom** [comment]
键盘弹出来的时候,返回键会关闭键盘,再按才退出.

**Comment by YoKeyword** [comment]
软键盘问题，不管你用Fragment还是Activity， 在软键盘弹出时，点击返回键`onKeyDown()`,`onBackPressed()`都不会被调用的，这里有个[解决方案](http://blog.csdn.net/wuyinlei/article/details/53844208)

`pop()`返回后到空白页的问题，你需要检查你是否复写了`onBackPressedSupport()`， `onBackPressedSupport()`默认处理是 栈内Fragment数量大于1时，pop()会执行出栈操作，小于等于1时，关闭Activity；  如果你复写了，这个默认处理就会改变

**Comment by andy91310** [comment]
onBackPressedSupport()我的确是复写了这个方法，为了一次把打开的子页面都关闭，只要返回就回到主页面

**Comment by YoKeyword** [comment]
源码中是这么处理的，可以参考下修改
````java
 public void onBackPressedSupport() {
        if (getSupportFragmentManager().getBackStackEntryCount() > 1) {
            pop();
        } else {
            ActivityCompat.finishAfterTransition(mActivity);
        }
    }
````

**Comment by andy91310** [comment]
public boolean onBackPressedSupport() {
        FragmentManager fm = _mActivity.getSupportFragmentManager();
        String tagName = fm.getBackStackEntryAt(fm.getBackStackEntryCount() - 1).getName();
        if (tagName.equals(ArticleDetailFragment.class.getName())) {
            boolean result = fm.popBackStackImmediate(ArticleDetailFragment.class.getName(), FragmentManager.POP_BACK_STACK_INCLUSIVE);
            if (!result) {
                onBackPressedSupport();
            }
        } else {
            super.onBackPressedSupport();
        }
        return true;
    }
我是这么处理的，是不是不好

**Comment by YoKeyword** [comment]
@andy91310 具体处理方式看你的需求和业务场景了, 能达到你的预期就可以 :)
