### ISSUE TITLE
动画时间设置长一些，背景会闪白

### ISSUE THREAD

**Issue by flztsj** [YoKeyword/Fragmentation#564]
h_fragment_enter.xml 和 h_fragment_exit.xml 中的duration从300改成600，会出现动画中页面闪白的情况。
[device-2017-09-20-152457.zip](https://github.com/YoKeyword/Fragmentation/files/1316898/device-2017-09-20-152457.zip)

这应是动画没做完，FragmentManager就将上个fragment hide掉导致的，又没又什么版本可以解决这个问题？

**Comment by YoKeyword** [comment]
转场动画： h_fragment_enter.xml  和 h_fragment_pop_exit.xml 对应， pop_enter 和 exit对应， 所以改动画时长时，也要把对应的动画市场改变， 比如改了enter,那么pop_exit时长也要更改

**Comment by flztsj** [comment]
了解 谢谢了
