### ISSUE TITLE
为什么 loadRootFragment(R.id.menu_frame, currentFragment, true, false); 动画会生效？

### ISSUE THREAD

**Issue by zhenian** [YoKeyword/Fragmentation#565]
为什么 ``` loadRootFragment(R.id.menu_frame, currentFragment, true, false); ``` 动画会生效？

`1.1.3` 时，是正常的，但升级到最新的 `1.1.6`， 原本没动画的，出现了动画

看到 #541 的变更，同这个有关？？

**Comment by zhenian** [comment]
回滚测试，发现是 `1.1.4` 即 #541 引用的问题了。

**Comment by YoKeyword** [comment]
`loadRootFragment(R.id.menu_frame, currentFragment, true, false)` 等同于 `loadRootFragment(R.id.menu_frame, currentFragment)`

第4个参数代表是否允许展示入场动画（仅控制入场动画），true的话会显示**入场动画**，false不显示

我刚在Demo中测试了，和期望是一样的， v1.1.3不管怎样 Root Fragment的4个动画都不显示的BUG，在1.1.4中修复了

如果你想让RootFragment都无动画，可以设置其：
````java
 @Override
    public FragmentAnimator onCreateFragmentAnimator() {
        return new DefaultNoAnimator();
    }
````

**Comment by zhenian** [comment]
`SubSupportActivity`中设置:

```
    @Override
    public FragmentAnimator onCreateFragmentAnimator() {
        // 设置横向(和安卓4.x动画相同)
        return new DefaultHorizontalAnimator();
    }
```
和 

```
loadRootFragment(R.id.menu_frame, currentFragment, true, false);
```

产生的效果是...？？

**Comment by YoKeyword** [comment]
只要第4个参数是false，rootFragment产生的效果就是无**入场**动画，但是出场、转场等动画都是有的

你的场景我模拟了下，正常，  或许贴下Demo工程？
