### ISSUE TITLE
Activity 执行 onResumes生命周期后  Fragment 显示错乱

### ISSUE THREAD

**Issue by zs1973** [YoKeyword/Fragmentation#567]
Activity A里面有一个fatherFragment，fatherFragment里面有四个childFragment  顺序为 A-B-C-D，当我从Activity A跳转到 Activity B再到Activity C，在Activity C 里面执行逻辑成功之后，用EventBus 刷新 Activity A里面的 childFragment D的数据。之后返回的Activity A界面，这个时候D Fragment就会覆盖A Fragment（之前展示的是A Fragment） 。 不解呢。

**Comment by LonelyMushroom** [comment]
应该不会有这种情况的,我的项目有这种操作方式,一直没有问题,你贴下你的代码块还有库的版本,v4包的版本
