### ISSUE TITLE
replace动画

### ISSUE THREAD

**Issue by AIlll** [YoKeyword/Fragmentation#569]
请问如何给replaceFragment加动画呢

**Comment by YoKeyword** [comment]
Fragmentation的`replace`没有赋予动画的功能，原因是在`replace`情况下，假设A.replace(B)， 会发现转场时，A的动画在B的动画上面（期望是：B 在 A上），这样导致动画显示异常，除非它们的动画不重叠（比如A是100%右移动，B从-100％左移）

虽然在5.0+ 可以通过控制Z轴来解决该问题，但是在5.0-的系统上没有很好的方式解决，同时考虑到带动画的`replace`场景不多，同时有`startWithPop()`来替代，所以`replace`就禁掉了动画
