### ISSUE TITLE
弹窗里面跳fragment不能覆盖

### ISSUE THREAD

**Issue by DuoLa512** [YoKeyword/Fragmentation#571]
一个fragment里面使用BottomSheetDialog进行底部弹窗，当点击弹窗里面的某个控件，跳转到另外一个fragment，这是跳转的fragment不能覆盖在弹窗之上，跳转activity可以覆盖，求解，谢谢

**Comment by LonelyMushroom** [comment]
有个这么的说法,你start跳转的fg,它与你现在的fg共享的是同一个xml的id,所以会导致出现这种想象,你可以看下知乎demo,他是在mainfg里面进行跳转的,你可以尝试着往上一层的fg跳转试试,也就是父fg.start(要跳转的fg)

**Comment by YoKeyword** [comment]
@DuoLa512 Dialog是window级别，Fragment是View级别， 自然Dialog会在Fragment上面

**Comment by DuoLa512** [comment]
有什么好的解决方法
