### ISSUE TITLE
动画出问题

### ISSUE THREAD

**Issue by KinaZhen** [YoKeyword/Fragmentation#572]
activity 内通过loadRootFragment 加载一个fragment ,fragment 内部 start(newFragment)  根界面变白屏

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/444
参考下这个iss

**Comment by KinaZhen** [comment]
这个配合glide 使用 ，栈上会多出个 SupportRequestManagerFragment  所以导致这个问题，有解决方法吗

**Comment by YoKeyword** [comment]
`SupportRequestManagerFragment` 并不是引起白屏的原因

看你描述的场景非常简单， 可以查看Demo的写法
