### ISSUE TITLE
这个配合glide 使用 ，栈上会多出个 SupportRequestManagerFragment 

### ISSUE THREAD

**Issue by KinaZhen** [YoKeyword/Fragmentation#573]
glide.with  方法为了监听fragment 的生命周期，会创建SupportRequestManagerFragment ，导致栈上对了个fragment 这个直接导致动画空白，onfragmentResult 失效 ，又解决方案吗？

**Comment by YoKeyword** [comment]
`SupportRequestManagerFragment ` 不是引起空白的原因， 这仅仅是一个无UI的状态Fragment，并不影响栈内其他Fragment

可以查看Demo的写法，另外请贴下栈视图，并描述场景

**Comment by KinaZhen** [comment]
发现配置问题，fragment 和 activity 同时配置onCreateFragmentAnimator 会出现

**Comment by YoKeyword** [comment]
同时配置的话，会优先使用Fragment配置的`onCreateFragmentAnimator` 

是否已解决？    如还未解决，可以贴下栈视图，如果能贴代码片段 、gist更佳

**Comment by KinaZhen** [comment]
已经解决，谢谢，还是上层fragment hide 问题
