### ISSUE TITLE
上层fragment 透明 ，下层fragment hide

### ISSUE THREAD

**Issue by KinaZhen** [YoKeyword/Fragmentation#574]
如题，看您的源码，在start(fragment)  代码回调用到hide ，我这边出现，上层fragment 是半透明，下层是空白的

**Comment by YoKeyword** [comment]
`start()`类比Activity的`startActivity()`， 所以都是启动目标&隐藏自身， 如果不隐藏自身，View的绘制的压力会越来越大，打开较多个Fragment后绘制就会卡成画

如果你不想隐藏自身，可以使用下面的代码：
````java
extraTransaction().startDontHideSelf(targetFragment);
````
