### ISSUE TITLE
swipeback 过程，上层fragment 空白

### ISSUE THREAD

**Issue by KinaZhen** [YoKeyword/Fragmentation#575]
如题，这个是有一定很大概率会出现这个问题，请问是什么原因？ 我是上层fragment 是不可swipe 所以没有 new SwipeBackFragmentDelegate ，没有嵌入 swipelayout.

**Comment by YoKeyword** [comment]
> swipeback 过程，上层fragment 空白
> 我是上层fragment 是不可swipe

听起来是矛盾的： 滑动过程中 上层Fragment空白，说明滑动的是上层Fragment，但是上层Fragment又是不可滑动的....    不理解

如果想禁止滑动，有2个方式：
1、`setSwipeBackEnable(false)`
2、不继承SwipeBackFragment/Activity

**Comment by KinaZhen** [comment]
可能我表达的有问题，现在我的activity 里 有个根fragment1 , 根fragment 上start(fragment2) ， 那么fragment2 swipeback 时 ，偶尔出现空白； 现在我把start(fragment2)  改成 extraTransaction().startDontHideSelf（fragment2） 则不会出现

**Comment by YoKeyword** [comment]
出现空白的化，应该是在滑动开始时，上一个Fragment的View没有`setVisibility(View.VISIBLE);`， 之前没有收到过相关反馈， 建议你断点调试下，是否没有调用`setVisibility(View.VISIBLE);`

相关代码在[这里](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_swipeback/src/main/java/me/yokeyword/fragmentation/SwipeBackLayout.java#L379)

**Comment by Jiiiiiin** [comment]
@YoKeyword 如果是Fragment里面嵌套的webview，就不支持类似webView.goBack()，就是说在嵌套一层判断 哈哈，要求是不是有点离谱了，不过现在混合开发也蛮多的，关注中，谢谢

**Comment by YoKeyword** [comment]
@Jiiiiiin 在Fragment的`onBackPressedSupport()`中 判断是否webview可goBack，然后选择处理并拦截
