### ISSUE TITLE
背景黑色...

### ISSUE THREAD

**Issue by cjcj125125** [YoKeyword/Fragmentation#577]
大佬你好，首先谢谢你，用了你这个库简直爽的不要不要的，从此妈妈再也不用担心我用fragment出问题了，.........另外在看你源码的时候发现你fragment的layout并没有设置背景色，代码中貌似也没看到，apptheme中的parents 是......DarkActionBar，我这样写后如果layout不设置背景色就是黑色的，为什么呢？求指点，谢谢

**Comment by YoKeyword** [comment]
设置背景色源码在[这里](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/SupportFragmentDelegate.java#L553)，可以看到默认是从theme获取背景色的

如果想更改这个默认色，可以通过SupportActivity的`setDefaultFragmentBackground()`来设置该Activity下的全局Fragment背景

**Comment by cjcj125125** [comment]
谢谢楼主

**Comment by cjcj125125** [comment]
我现在是用一个activity作为容器，其他的fragment都是跳转到这个activity根据传进来的type区分加载哪个fragment，但是这样的话加载的时候容器activity背景白色的话会出现一刹那的白色背景，体验不是很友好，把容器的背景设置为透明可以解决这个问题，请问大佬，我这样的设计方式有问题吗？或者有更好的方法吗？望大佬多多指教，万分感谢

**Comment by LonelyMushroom** [comment]
@cjcj125125  可以用replace么,就是说先在AC放一个没用的fg,然后根据type来替换对应的fg.(不成熟的小建议)

**Comment by cjcj125125** [comment]
loadRootFragment();后面加 getSupportFragmentManager().executePendingTransactions();
这样吗？？？好像没有效果呀

**Comment by cjcj125125** [comment]
还是会白屏一下，然后再出现fragment

**Comment by cjcj125125** [comment]
如果用replaceFragment()的话是不是先用loadRootFragment()加载默认的空白fragment，然后再用replaceFragment()，谢谢大佬

**Comment by YoKeyword** [comment]
@cjcj125125 我试下第一个Demo，模拟你的场景（给HomeFragment设置一个大红色背景），不调用`executePendingTransactions()`也不会出现你说的闪烁情况

或许贴下Activity内加载load的代码

**Comment by cjcj125125** [comment]
代码很简单，任何跳转都是跳到ContainerActivity传一个参数type，在create中根据type加载对应的fragment，加载的代码是 loadRootFragment(R.id.content, Fragment.newInstance(),true,true);
就这样，会白屏一下才出现fragment的内容，大佬指点，谢谢

**Comment by YoKeyword** [comment]
@cjcj125125  
` loadRootFragment(R.id.content, Fragment.newInstance(),true,true)` 原因在于你第四个参数`true`, 代表显示入场动画，所以在动画期间会有背景问题...

根据你的场景，`loadRootFragment(R.id.content, Fragment.newInstance())` 即不显示入场动画， 也是可以满足你的需求的， 同时也不会有背景问题
