### ISSUE TITLE
点击事件失效

### ISSUE THREAD

**Issue by Ludejin** [YoKeyword/Fragmentation#58]
在一个Fragment中start(newFragment)，然后pop掉newFragment，Fragment事件失效，无法点击。

**Comment by Ludejin** [comment]
![image](https://cloud.githubusercontent.com/assets/10751355/17646981/4db78682-6211-11e6-8ad3-886c718c09eb.png)
![image](https://cloud.githubusercontent.com/assets/10751355/17646982/5b956a3a-6211-11e6-8cbb-26bb799b7a77.png)
第一张图是HomeFragment的代码，当我SettingFragment通过左边滑动退出时，start(SettingFragment.newInstance());就无效了，而且HomeFragment 任何点击事件都无效，_mActivity.setFragmentClickable();执行这句代码也不行。

**Comment by YoKeyword** [comment]
是最新版吗？

**Comment by Ludejin** [comment]
是的，我SettingFragment执行_mActivity.onBackPressed();这段代码直接退出整个程序，这就是问题所在，没有添加到栈顶。

**Comment by YoKeyword** [comment]
不要调用onBackPressed.  我已经标记为过时
用backSupport的方法

**Comment by Ludejin** [comment]
试了，一样的效果，我现在的是loadMultipleRootFragment，HomeFragment属于Multiple中的一个，在HomeFragment中start SettingFragment，这样的情景

**Comment by YoKeyword** [comment]
额，你确定要用HomeFragment的这个层级去启动SettingFragment？
不是HomeFragment的父级Fragment去启动SettingFragment？

栈层级关系你是怎么设计的

**Comment by Ludejin** [comment]
我看了你wechat的代码，我就是少了MainFragment这一层，你这么一说我想问问这个MainFragment一层有什么好处，为什么不能交给Activity去管理？（接触一个Activity多个Fragment这样的方式不久）

**Comment by YoKeyword** [comment]
一定要有MainFragment这一层 ，你的异常就是出在这里～
栈层级关系，你现在比较模糊，看我推荐的第2篇简书吧，里面有栈层级关系的详细介绍。
单AC＋多FG的核心就是对栈层级关系很熟悉～ 3个Demo的不同处本质就是栈层级设计不一样，
你的需求应该是仿QQ这种的，也就是第2个Demo，Main这层是和SettingFragment是一层级的，
如果和HomeFragment一个层级，就完全错乱了，看下那篇简书再多思考下，一定要多用查看栈视图的那2个API，辅助理解～

**Comment by Ludejin** [comment]
恩恩，通过今天这个问题，貌似对层级有些了解了，谢谢耐心回答，现在可以关闭这个issue了。
