### ISSUE TITLE
似乎无法完成这样的效果

### ISSUE THREAD

**Issue by HouXiaohu** [YoKeyword/Fragmentation#580]
页面分上下两块区域，下面的区域是容器，需要展示Fragment，上面固定不动，但是用loadRoot... 能加载到容器里面，但是是被全屏展示了，挡住了我的A区域？

**Comment by LonelyMushroom** [comment]
你贴下你的xml,还有loadRoot的代码
loadRoot所展示的fragment的大小依赖于xml中容器的大小

**Comment by HouXiaohu** [comment]
Activity的xml:
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
    
  <LinearLayout
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:orientation="vertical"
      >
      
      <RelativeLayout
          android:layout_width="match_parent"
          android:layout_height="213px"
          android:background="#EF6B51"
          >

          <FrameLayout
              android:layout_width="46px"
              android:layout_height="46px"
              android:layout_marginTop="50px"
              android:layout_marginLeft="68px"
              android:id="@+id/frame1"

              android:background="@drawable/shape_cicle_whitestoke_normal"
              >

              <TextView
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:textSize="22px"
                  android:layout_gravity="center"
                  android:text="1"
                  android:id="@+id/tv_1"
                  android:textColor="@color/white"
                  />
          </FrameLayout>

          <View
              android:layout_width="145px"
              android:layout_height="2px"
              android:background="#BCD3F3"
              android:layout_toRightOf="@id/frame1"
              android:layout_marginTop="72px"
              android:id="@+id/view_1"
              />

          <TextView
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:text="个人信息"
              android:layout_marginTop="18px"
              android:textSize="24px"
              android:layout_below="@id/frame1"
              android:layout_marginLeft="47px"
              android:id="@+id/tv_1_title"
              android:textColor="@color/white"
              />

          

          <FrameLayout
              android:layout_width="46px"
              android:layout_height="46px"
              android:layout_marginTop="50px"
              android:layout_toRightOf="@id/view_1"
              android:id="@+id/frame2"
              android:background="@drawable/shape_cicle_whitestoke_normal"
              >

              <TextView
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:textSize="22px"
                  android:layout_gravity="center"
                  android:text="2"
                  android:id="@+id/tv_2"
                  android:textColor="@color/white"
                  />
          </FrameLayout>

          <View
              android:layout_width="145px"
              android:layout_height="2px"
              android:background="#BCD3F3"
              android:layout_toRightOf="@id/frame2"
              android:layout_marginTop="72px"
              android:id="@+id/view_2"
              />

          <TextView
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:text="绑定银行卡"
              android:layout_marginTop="18px"

              android:textSize="24px"
              android:layout_below="@id/frame2"
              android:layout_marginLeft="81px"
              android:layout_toRightOf="@id/tv_1_title"
              android:id="@+id/tv_2_title"
              android:textColor="@color/white"
              />

          

          <FrameLayout
              android:layout_width="46px"
              android:layout_height="46px"
              android:layout_marginTop="50px"
              android:layout_toRightOf="@id/view_2"
              android:id="@+id/frame3"
              android:background="@drawable/shape_cicle_whitestoke_normal"
              >

              <TextView
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:textSize="22px"
                  android:layout_gravity="center"
                  android:text="3"
                  android:id="@+id/tv_3"
                  android:textColor="@color/white"
                  />
          </FrameLayout>

          <View
              android:layout_width="145px"
              android:layout_height="2px"
              android:background="#BCD3F3"
              android:layout_toRightOf="@id/frame3"
              android:layout_marginTop="72px"
              android:id="@+id/view_3"
              />

          <TextView
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:text="绑定银行卡"
              android:layout_marginTop="18px"

              android:textSize="24px"
              android:layout_below="@id/frame2"
              android:layout_marginLeft="81px"
              android:layout_toRightOf="@id/tv_2_title"
              android:id="@+id/tv_3_title"
              android:textColor="@color/white"
              />

          
          <FrameLayout
              android:layout_width="46px"
              android:layout_height="46px"
              android:layout_marginTop="50px"
              android:layout_toRightOf="@id/view_3"
              android:id="@+id/frame4"
              android:background="@drawable/shape_cicle_whitestoke_normal"
              >

              <TextView
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:textSize="22px"
                  android:layout_gravity="center"
                  android:text="4"
                  android:id="@+id/tv_4"
                  android:textColor="@color/white"
                  />
          </FrameLayout>

          <TextView
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:text="确认信息"
              android:layout_marginTop="18px"

              android:textSize="24px"
              android:layout_below="@id/frame2"
              android:layout_marginLeft="81px"
              android:layout_toRightOf="@id/tv_3_title"
              android:id="@+id/tv_4_title"
              android:textColor="@color/white"
              />
      </RelativeLayout>
        
      
      <FrameLayout
          android:layout_width="match_parent"
          android:layout_marginTop="21px"
          android:id="@+id/frame_main1"
          android:layout_height="match_parent">


      </FrameLayout>

  </LinearLayout>
    
</ScrollView>

Activity中加载的代码：
    @Override
    public void initData(Bundle saveInstanceState) {
        initView();
//        getSupportFragmentManager().beginTransaction()
//                .replace(R.id.frame_main1, MyBasicInfoFragment.newInstance(Constant.RouterTag.EMPLOYSERVICES_INPUTMYBASICINFO))
//                .commit();

        loadRootFragment(R.id.frame_main1,MyBasicInfoFragment.newInstance(Constant.RouterTag.EMPLOYSERVICES_INPUTMYBASICINFO));

   
    }

**Comment by LonelyMushroom** [comment]
@HouXiaohu 你没贴全  xml的代码  根节点都没有

**Comment by HouXiaohu** [comment]
@LonelyMushroom  不好意思，已经更新，您再看下

**Comment by LonelyMushroom** [comment]
你可以参考微信demo中的MainActivity,我按照你发的xml改变了demo中的xml进行测试,没有发现你所说的问题
``` xml
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ImageView
        android:src="@color/bg_app"
        android:layout_width="match_parent"
        android:layout_height="213px"/>

    <FrameLayout
        android:layout_marginTop="21px"
        android:id="@+id/fl_container"
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</LinearLayout>
```

``` java
@Override
protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.wechat_activity_main);

        if (findFragment(MainFragment.class) == null) {
            loadRootFragment(R.id.fl_container, MainFragment.newInstance());
        }
}
```

**Comment by HouXiaohu** [comment]
我并没有完全贴出xml,但是看到你说的后，我彻底的检查了一下我的xml,结果是： A区域的marginTop导致的。  解释： 由于我的xml跟节点是一个Scrollview嵌套着这个LinearLayout，然后A区域是一个RelativeLayout并且设置了 marginTop=20， 刚才上网上搜了一下这个，发现了这个问题，同时也感谢你们

**Comment by HouXiaohu** [comment]
@LonelyMushroom  我并没有完全贴出xml,但是看到你说的后，我彻底的检查了一下我的xml,结果是： A区域的marginTop导致的。 解释： 由于我的xml跟节点是一个Scrollview嵌套着这个LinearLayout，然后A区域是一个RelativeLayout并且设置了 marginTop=20， 刚才上网上搜了一下这个，发现了这个问题，同时也非常感谢你

**Comment by LonelyMushroom** [comment]
嗯嗯  没事的 问题解决就好
