### ISSUE TITLE
使用Frescon的SimpleDraweeView在切换fragment的时候出现空白

### ISSUE THREAD

**Issue by sumaro** [YoKeyword/Fragmentation#584]
手机型号:HUAWEI NXT-TL00
Android版本:7.0
EMUI版本5.0
问题描述:
使用SupportActivity的loadRootFragment(R.id.container, fragment1, true, false)加载fragmeng1,然后在fragment1中使用start(fragment2).在切换过程中fragmeng1中的Recycleview中使用SimpleDraweeView加载完成的图片会消失并显示空白.
SupportActivity使用动画DefaultHorizontalAnimator
![1](https://user-images.githubusercontent.com/8817011/31005820-e7a63144-a52c-11e7-87c8-a6cef3bceacc.jpg)
![2](https://user-images.githubusercontent.com/8817011/31005840-fed3fb62-a52c-11e7-94a2-c0bba5c12d3f.jpg)

**Comment by YoKeyword** [comment]
#341 提到Andorid 7.0+会有这个问题

要看Fresco的解决方案 或者 考虑使用竖直动画代替横向， 这样视觉上是看不出来的，同时视觉上竖直动画会显得更流畅
