### ISSUE TITLE
被打开Fragment共享动画丢失

### ISSUE THREAD

**Issue by MartinDong** [YoKeyword/Fragmentation#585]
Demo中的ZhihuFirstFragment.java演示的共享动画，效果显示的被开启的FirstDetailFragment.java动画丢失；但是返回上一页面FirstHomeFragment.java确实可以正常动画回位。

期望被打开页面也能有动画进入，希望作者能够解答一下。

**Comment by YoKeyword** [comment]
Duplicate of #256  :)
