### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by douya40** [YoKeyword/Fragmentation#587]
主页面进入详情页面有个ViewPager 加载的页面，只能使用EventBus.getDefault().post（）页面跳转，现在从其他页面进入详情页面（比如外部推送），使用activity,将原先的详情页面加载进来。发现之前的ViewPager 加载的页面点击无效。

**Comment by YoKeyword** [comment]
先不用EventBus来跳转试下，如果没问题， 那原因就是EventBus有多处发送或接收Event 进行Fragment事务引起的问题（比如App内有同一个Fragment的不同实例,ActivityA中有FragmentA，ActivityB也有FragmentA）  
> PS： 除非比较复杂的场景，一般不建议使用EventBus来跳转
