### ISSUE TITLE
想要一份详细的使用文档

### ISSUE THREAD

**Issue by idealcn** [YoKeyword/Fragmentation#589]
想要一份详细的使用文档,公司项目比较多,想使用这个框架去管理fragment,麻烦楼主能出一份详细的使用文档,谢谢!!!

**Comment by LonelyMushroom** [comment]
[wiki](https://github.com/YoKeyword/Fragmentation/wiki)

**Comment by YoKeyword** [comment]
参考 wiki + demo

**Comment by idealcn** [comment]
demo只能模仿调用Api，我想知道你们这个开源库的思路和原理，方便我集成后的后期维护。谢谢
发自网易邮箱大师
在2017年10月10日 16:29，YoKey 写道： 参考 wiki + demo

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/YoKeyword/Fragmentation","title":"YoKeyword/Fragmentation","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/YoKeyword/Fragmentation"}},"updates":{"snippets":[{"icon":"PERSON","message":"@YoKeyword in #589: 参考 wiki + demo"}],"action":{"name":"View Issue","url":"https://github.com/YoKeyword/Fragmentation/issues/589#issuecomment-335399914"}}}

**Comment by YoKeyword** [comment]
@idealcn Fragmentation只是帮助管理Fragment，减少一些坑和痛点； 更深入的话，建议你可以翻看下源码， 源码并不多

> PS：Fragmentation适用于重度使用Fragment的场景，如果轻度使用，可以考虑参考Fragmentation的一些实现 来封装

**Comment by idealcn** [comment]
我这边做的商城类app，里面大量用到fragmen做页面切换，所以想使用这个库来减轻开发压力。所以想深入学习一下，便于自己项目后期维护。

发自网易邮箱大师
在2017年10月11日 16:46，YoKey 写道： @idealcn Fragmentation只是帮助管理Fragment，减少一些坑和痛点； 更深入的话，建议你可以翻看下源码， 源码并不多

PS：Fragmentation适用于重度使用Fragment的场景，如果轻度使用，可以考虑参考Fragmentation的一些实现 来封装


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/YoKeyword/Fragmentation","title":"YoKeyword/Fragmentation","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/YoKeyword/Fragmentation"}},"updates":{"snippets":[{"icon":"PERSON","message":"@YoKeyword in #589: @idealcn Fragmentation只是帮助管理Fragment，减少一些坑和痛点； 更深入的话，建议你可以翻看下源码， 源码并不多\r\n\r\n\u003e PS：Fragmentation适用于重度使用Fragment的场景，如果轻度使用，可以考虑参考Fragmentation的一些实现 来封装"}],"action":{"name":"View Issue","url":"https://github.com/YoKeyword/Fragmentation/issues/589#issuecomment-335738758"}}}
