### ISSUE TITLE
你这个框架有考虑过内存泄漏的问题吗？

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#59]
@YoKeyword 
你这个框架有考虑过内存泄漏的问题吗？
我用你这个框架有一段时间了，最近项目收尾，在优化，有些内存泄漏的问题都已经找到并解决了，现在就是在想，你这个框架是不是有做过这方面的处理，或者请问能给点fragment防止内存泄漏的建议吗？
单纯想到这里所以过来咨询一下，想你学习。^_^

**Comment by YoKeyword** [comment]
这个框架涉及到的功能和内存泄漏方面基本没什么联系，所以是没有进行特殊处理的。

内存泄漏处理方式还是需要根据业务自行处理的。
Fragment更容易引起内存泄漏，毕竟生命周期比Activity复杂。

内存泄漏主要的原因大部分是异步任务引起的：
在onDestroyView/onDestroy里及时取消异步任务，比如使用RxJava或者各种Volley、OkHttp的cancel()系列方法等等

另外说一个图片相关，和OOM关系比较大的一个tip：
图片框架一般都有一个自己的内存缓存，并且在AC／FG退出时并不会移除这部分内存（为了下次更快的展现），所以如果图片资源较多时，可以考虑在AC／FG销毁时手动释放当前图片的资源，目前主流图片框架都有对应的API可以移除，缺点就是下次打开该页面时，需要从磁盘获取，要慢点～
