### ISSUE TITLE
使用start(ISupportFrgment toFragment)会丢失点击回馈动画

### ISSUE THREAD

**Issue by sumaro** [YoKeyword/Fragmentation#590]
使用Activity+Fragment展示一个界面
在activity使用loadRootFragment(id,fragment,ture,false)加载FragmentA，
FragmentA中包含一个Recyclerview,我在每个item中都设置了点击事件的selector.
点击item调用start(FragmentB).FragmentB正常跳转.但是item的press效果一直没有反应
如果执行其他操作，例如Toast或者启动一个Activity，item正常的显示press效果

**Comment by YoKeyword** [comment]
见 #175

**Comment by sumaro** [comment]
谢谢

**Comment by sumaro** [comment]
另外我使用extraTransaction().startDontHideSelf()可以出现ripple动画

**Comment by YoKeyword** [comment]
当然， 因为`startDontHideSelf()`， 当前Fragment并不会hide，所有会有ripple
