### ISSUE TITLE
start（）方法问题

### ISSUE THREAD

**Issue by isqing** [YoKeyword/Fragmentation#592]
当我在主页有四个fragment时在其中一个fragmentA里面有个按钮，点击跳转到另一个fragmentB时，start（fragmentB）为啥还在fragmentA里面，底部的四个导航按钮都在，用evetnbus就可以新开一个页面来显示fragmentB，请问是什么问题

**Comment by YoKeyword** [comment]
根据描述 你可以参考第二个Demo
