### ISSUE TITLE
过渡动画：SharedElement 使用时的一些问题

### ISSUE THREAD

**Issue by CcSimple** [YoKeyword/Fragmentation#595]
仿微信栈设计模式  使用--->  extraTransaction() 
addSharedElement 时,  我想从子frament  start新的Fragment, -->这里 子fragment replace且 空白了
当我使用getParentFragment()调用extraTransaction() 时, -->开启了新的fragment,但返回再次 start 时,出现
( Unique transitionNames are required for all sharedElements ) 错误..

**Comment by YoKeyword** [comment]
假设MainFragment下有子 ChildFragment ， 你想用ChildFragment启动TargetFragment

首先ChildFragment不能直接start， 而是需要通过 MainFragment( `getParentFragment()`)来启动，原因看[wiki](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager)

所以只能通过`getParentFragment()`来启动，但是`SharedElements` 此时是对MainFragment和TargetFragment动画生效的，即ChildFragment的共享元素和TargetFragment的共享元素是无法关联的

解决方式有2个： 
* childFragment需要和TargetFragment同一层级， 但是该方式改动较大
* 自己实现类似`SharedElements`效果， 可以参考相关文章实现，也比较简单
