### ISSUE TITLE
Crashed issuse

### ISSUE THREAD

**Issue by zubinxiong** [YoKeyword/Fragmentation#596]
E/AndroidRuntime(  698): FATAL EXCEPTION: main
E/AndroidRuntime(  698): java.lang.NullPointerException
E/AndroidRuntime(  698): 	at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2022)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1833)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2244)
E/AndroidRuntime(  698): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1907)
E/AndroidRuntime(  698): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1938)
E/AndroidRuntime(  698): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1392)
E/AndroidRuntime(  698): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2408)
E/AndroidRuntime(  698): 	at me.yokeyword.fragmentation.SupportActivity.dispatchTouchEvent(SupportActivity.java:59)
E/AndroidRuntime(  698): 	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
E/AndroidRuntime(  698): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1886)
E/AndroidRuntime(  698): 	at android.view.View.dispatchPointerEvent(View.java:7323)
E/AndroidRuntime(  698): 	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3563)
E/AndroidRuntime(  698): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3493)
E/AndroidRuntime(  698): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4643)
E/AndroidRuntime(  698): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4603)
E/AndroidRuntime(  698): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4755)
E/AndroidRuntime(  698): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
E/AndroidRuntime(  698): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(  698): 	at android.os.MessageQueue.next(MessageQueue.java:125)
E/AndroidRuntime(  698): 	at android.os.Looper.loop(Looper.java:140)
E/AndroidRuntime(  698): 	at android.app.ActivityThread.main(ActivityThread.java:5014)
E/AndroidRuntime(  698): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  698): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(  698): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
E/AndroidRuntime(  698): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/AndroidRuntime(  698): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by zubinxiong** [comment]
- 版本信息
com.android.support:appcompat-v7:22.2.0
com.android.support:recyclerview-v7:22.2.0
me.yokeyword:fragmentation:1.1.6

- 启动时偶尔会出现崩溃

**Comment by zubinxiong** [comment]
<img width="933" alt="qq20171013-114353 2x" src="https://user-images.githubusercontent.com/7650970/31529460-06ef7638-af9f-11e7-9f85-e58e2a33997c.png">

**Comment by YoKeyword** [comment]
>E/AndroidRuntime( 698): java.lang.NullPointerException
E/AndroidRuntime( 698): at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2022)

该Crash和Fragmentation无关， 崩溃原因应该是在 RecyclerView 数据加载完成前 点击导致的Crash，建议在初始化之后立即`setLayoutManager`， 该问题可以参考https://stackoverflow.com/questions/28179494/cause-for-nullpointerexception-android-support-v7-widget-recyclerview-onmeasure
