### ISSUE TITLE
大佬能不能留个qq，问你下问题

### ISSUE THREAD

**Issue by cjcj125125** [YoKeyword/Fragmentation#598]
大佬您好，用一个activity作为容器，其他activity跳转到fragment的时候都是通过这个activity加载的fragment，但是屏幕会稍微闪一下，过度不是很好，希望大佬指点下，我是在activity里直接用的loadRootFragment()方法加载的，求教，麻烦留个qq，便于请教，谢谢

**Comment by YoKeyword** [comment]
或许你的问题和这位同学类似， #577
