### ISSUE TITLE
右滑退出fragment时经常会误操作

### ISSUE THREAD

**Issue by Andrew-Shi** [YoKeyword/Fragmentation#6]
在右滑退出的fragment中滑动时，如果不从边缘触发，那么滑动左右滑动手势会被识别成点击，从而触发点击事件，而且必现

**Comment by YoKeyword** [comment]
@Andrew-Shi 是用的Fragmentation-swipeback库里的滑动退出是吧～
因为DEMO里的界面是全屏都可以点击（其实是为了说明 库解决了事件冲突）,实际app中我们页面很少有这样的情况，Demo中有个页面是RecyclerView页面，你可以发现这个页面不容易误操作；
SwipeBackLayout那个库，包括使用该库的简书、SF等app其实都没刻意控制这个滑动操作，真实app下，应该是很少发现误操作的，当然这块你也是可以通过自己处理touch事件完全解决该问题，不过好像没有必要 :)
