### ISSUE TITLE
ViewPager+多个Fragment

### ISSUE THREAD

**Issue by Destiny01** [YoKeyword/Fragmentation#60]
ViewPager+多个Fragment实现懒加载，能使用你那个BaseLazyFragment吗？还是自己在 public void setUserVisibleHint(boolean isVisibleToUser) {}里面判断？

**Comment by YoKeyword** [comment]
不能！BaseLazy只适合同级的那种情况～
 ViewPager+Fragment的懒加载，你可以自己通过setUserVisibleHint()实现或者搜索下，回头有空我再补上这个懒加载的示例 :)

**Comment by Destiny01** [comment]
好的！
