### ISSUE TITLE
Fragment往后退2级

### ISSUE THREAD

**Issue by qfzhang123** [YoKeyword/Fragmentation#602]
Fragment往后退2级 怎么实现呢？

谢谢。

**Comment by Deepblue1996** [comment]
这个问题我遇过,我尝试笨方法,写了两次pop(),动画执行了一次,但是后退了二级

**Comment by qfzhang123** [comment]
我写两次pop() 没有用，还是只返回了上一级。

**Comment by adminLiu-s** [comment]
直接指定pop到上上级的fragment

**Comment by Deepblue1996** [comment]
当然也可以popTo;

**Comment by YoKeyword** [comment]
是 上上**个**Fragment 还是 上上**层**Fragment？

* 如果是上上个Fragment，假设A ,B,C ，可以使用c.popTo(B,true)或者c.popTo(A,false)

* 如果是上上层Fragment，要到指定层的Fragment上pop()， 比如`((SupportFragment)getParentFragment().getParentFragment()).pop()`

**Comment by NFLeo** [comment]
你这上上个 和 上上层分别指什么意思@YoKeyword  pop回去之后能刷新当前界面数据吗？例如上文的c.popTo(A, false),此时能刷新A界面数据吗？在哪个方法回调？

**Comment by qfzhang123** [comment]
我也想知道这个问题回退后怎么刷新界面的数据?

**Comment by YoKeyword** [comment]
同一栈层 和 不同栈层 的区别, 建议看[这篇文章](http://www.jianshu.com/p/d9143a92ad94)

刷新数据可以使用EventBus（更建议使用[EventBusActivityScope](https://github.com/YoKeyword/Fragmentation/blob/master/eventbus_activity_scope/README.md)），`startForResult()`
