### ISSUE TITLE
onFragmentResult问题

### ISSUE THREAD

**Issue by cjcj125125** [YoKeyword/Fragmentation#603]
你好，本来的onactivityResult在你这里面被换成了onFragmentResult后参数本来的Intent被换成了bundle，那么我之前的intent里面传过来的值我怎么取出来呢》？谢谢

**Comment by YoKeyword** [comment]
`onFragmentResult ()`是Fragmentation对startForResult(Fragment)的回调方法， 不影响原有的`onActivityResult()`

对于`startActivityForResult()`仍旧使用`onActivityResult()`接收回调
