### ISSUE TITLE
start问题

### ISSUE THREAD

**Issue by Deepblue1996** [YoKeyword/Fragmentation#604]
orderfragment, start orderinfofragment,顺序竟然在orderfragment下面
![qq 20171020163852](https://user-images.githubusercontent.com/16926380/31812445-9130f18e-b5b5-11e7-97de-8387f119f52b.jpg)

**Comment by Deepblue1996** [comment]
好吧,代码写着写着,现在又正常了...

**Comment by YoKeyword** [comment]
栈视图顺序错乱， 一般是进行进行了非法操作引起的， 即在`start(orderinfofragment)`前，栈内已经异常

若能复现，检查是否正确操作了栈
