### ISSUE TITLE
pop动画问题

### ISSUE THREAD

**Issue by Deepblue1996** [YoKeyword/Fragmentation#605]
pop(); 假如布局里面存在子fragment, 返回动画的时候子fragment突然消失,出现空白的情况,影响用户体验

**Comment by YoKeyword** [comment]
是指 在pop嵌套Fragment时， 子Fragment会直接消失吗？

这个问题在v1.1.5已兼容修复

**Comment by Deepblue1996** [comment]
我用的好像就是最新版本哦

**Comment by YoKeyword** [comment]
检查下是否对 子Fragment  设置了`DefaultNoAnimator` 或 无动画

**Comment by Deepblue1996** [comment]
我专门弄了个demo试验,发现原来子fragment不能嵌套android.support.v4.app.Fragment,子fragment也必须嵌套您的SupportFragment,ok

**Comment by YoKeyword** [comment]
对的， 官方的Fragment本身在这种情况 子Fragment会直接消失， SupportFragment中做了兼容处理 :)
