### ISSUE TITLE
How to delete fragment in backStack?

### ISSUE THREAD

**Issue by fvermeulen** [YoKeyword/Fragmentation#606]
Hey I have a problem in my stack I want to delete to fragments which are **not on the top of the stack**, while I push onto a different. How would you do this?

> val firstSuggestion = fragmentManager.fragments.first { it.javaClass.name == SuggestionSearchFragment::class.java.name }
> val firstSearchResult = fragmentManager.fragments.first { it.javaClass.name == GreenSearchResultsFragment::class.java.name }
> val indexFirst = fragmentManager.fragments.indexOf(test)
> fragmentManager.beginTransaction().remove(firstSuggestion).commitNow()
> fragmentManager.beginTransaction().remove(firstSearchResult).commitNow()
> fragmentManager.fragments[indexFirst] = null

it removes the fragment, but then when i pop back the hole stack, I see empty pages on the positions, where the fragments were before removing

**Comment by YoKeyword** [comment]
If your Fragment is already in the backStack, you can't delete the Fragment by `remove()`.
And you can only delete Fragment from the top of the stack.

**Comment by fvermeulen** [comment]
mhh yeah already read that it is only allowed to delete fragments from top of the stack, but I thought there is maybe an option to update the backstack after deleting fragments, which is possible....only the backstack is the problem :(

but thanks I will search for a workaraound or solution for my problem
