### ISSUE TITLE
Fragment移除的问题

### ISSUE THREAD

**Issue by CSnowStack** [YoKeyword/Fragmentation#61]
怎么移除当前栈内,除了当前Fragment的其他Fragment

**Comment by YoKeyword** [comment]
额，既然是栈结构，自然是不能让当前Fragment下的Fragment先出栈的.

不过你可以通过设计栈结构来曲线实现，具体看你的业务需求了～

**Comment by CSnowStack** [comment]
意思是 A到B到C,不能在C里面取出A和B吗

**Comment by YoKeyword** [comment]
是的～ 栈结构只有一个方向的出口～   这种情况你可以复写C的BACK事件，点击直接popTo这3个Fragment，或者使用startWithPop关闭B打开C～  具体看业务需求了～

**Comment by CSnowStack** [comment]
好吧,谢谢了
