### ISSUE TITLE
Transition动画问题

### ISSUE THREAD

**Issue by Deepblue1996** [YoKeyword/Fragmentation#612]
最近在研究过渡动画,发现共享元素有问题,并没有效果,不知道我写的过程是否有错,
第一步,styles添加
![image](https://user-images.githubusercontent.com/16926380/32130365-8b3da41a-bbc9-11e7-8de4-a1fe93bd863c.png)
第二步,两个xml添加
![image](https://user-images.githubusercontent.com/16926380/32130373-ae2f584c-bbc9-11e7-9d48-4fc6d55ce0c6.png)
第三步,代码
![image](https://user-images.githubusercontent.com/16926380/32130385-c5d54dbc-bbc9-11e7-8bf9-fff8f034d5e1.png)
最后,效果只有界面有动画,共享元素没有动画显示

**Comment by Deepblue1996** [comment]
我查看了一下之前的Issue, 发现说使用25.2.0正常,测试了一下,的确, 我现在使用的是com.android.support:appcompat-v7:26.0.0-beta1,但是我在网上下载测试的demo都正常的, 是不是Fragmentation未完善导致的问题?

**Comment by Deepblue1996** [comment]
打错25.1.0正常

**Comment by YoKeyword** [comment]
官方`add()`方法上的共享元素动画在最近的每个v4版本表现都不同... (`replace()`一直正常)

官方的BUG，Fragmentation没有特意去处理，所以等待Google的v4包修复
