### ISSUE TITLE
过度绘制问题

### ISSUE THREAD

**Issue by Jeff518** [YoKeyword/Fragmentation#613]
问一下，当一个app界面层级很多的时候，你有没有碰到过度绘制的问题？

**Comment by YoKeyword** [comment]
通过搜索引擎你可以找到优化方案 :)

**Comment by Jeff518** [comment]
你的开源项目有做这方面的优化嘛？ 搜索不到优化方案，我的过渡绘制问题；
![guoduhuizhi](https://user-images.githubusercontent.com/26729374/32151321-03661f10-bd57-11e7-9b9d-2626f29bd14b.png)

**Comment by LonelyMushroom** [comment]
[解决方案](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=0&rsv_idx=1&tn=baidu&wd=android%20%E8%BF%87%E6%B8%A1%E7%BB%98%E5%88%B6&rsv_pq=aecfb41d0002f251&rsv_t=c22aI%2BEHyfIRtwmw8WJy3wEkOwFADWBd6T90JhmXBzrvMnUi6ERzNHBZxck&rqlang=cn&rsv_enter=1&rsv_sug3=5&rsv_sug1=3&rsv_sug7=100&rsv_sug2=0&inputT=4993&rsv_sug4=5640)

**Comment by Jeff518** [comment]
这问题，显然不是因为背景的问题，是上下曾经的两个fragment的view重叠造成的！ # @LonelyMushroom

**Comment by LonelyMushroom** [comment]
那你贴下怎么load或者start Fg的代码不.你可以拿demo去看看,没有过渡绘制的情况.原来是会多一层,但是很久之前的几个版本更新后这个就修复了

**Comment by Jeff518** [comment]
@LonelyMushroom 
``
   /**
     * 显示fragment
     * @param id  容器id
     * @param fragment fragment对象
     * @param tag   fragment的标记
     */
    public void go2(int id, BaseFragment fragment,String tag){
        fragment.setContainterViewId(id);
        if (mFragmentManager == null){
            L.i("mFragmentManager is null");
            mFragmentManager = getSupportFragmentManager();//为了重复使用FragmentManager
        }

        Fragment ft = mFragmentManager.findFragmentByTag(tag);//根据tag 获取List中的的fragment
        if (ft != null && !ft.isDetached()){//如果List内有这个Fragment，则显示
            L.i("Fragment is not null");
            FragmentTransaction transaction = mFragmentManager.beginTransaction();
            //动画属性  int enter 将要打开的界面的进入动画,int exit  当前界面的退出动画,
        //   int popEnter 退出时，将要显示的上一个界面的进入动画, int popExit  退出时，当前界面的退出动画

            doChangeFragment(transaction,ft,tag);
            return;
        }

        //没有就把新的fragment  add 进去
        FragmentInfo info=new FragmentInfo(fragment,tag);
        mFragments.add(info);
        FragmentTransaction transaction = mFragmentManager.beginTransaction();
        transaction.add(id,fragment,tag);
        transaction.addToBackStack(tag);
        doChangeFragment(transaction,fragment,tag);
    }
``
    /**
     * 显示目标Fragment 隐藏其它的Fragment 方便重复使用
     */
    private void doChangeFragment(FragmentTransaction transaction,Fragment fragment,String tag){

        L.i("mFragmentList size= "+mFragments.size());
        transaction.setCustomAnimations(R.anim.slide_in_right, R.anim.slide_left_out,
                R.anim.slide_left_in, R.anim.slide_out_right);
        for (FragmentInfo info : mFragments){
            if (info.getTag().equals(tag)){
                transaction.show(fragment);
                continue;
            }
            transaction.hide(info.getFragment());
        }
       // transaction.commit();
        transaction.commitAllowingStateLoss();
    }
`
`
跳转的代码都在这，都是统一用的这个方法

**Comment by Jeff518** [comment]
是我自己的问题，这个重绘是fragment重叠造成的！打搅了！对不起！
