### ISSUE TITLE
关于intent到一个新activity的问题

### ISSUE THREAD

**Issue by Mr-PolarBear** [YoKeyword/Fragmentation#615]
大佬你好,   我开发的项目中 需要用到几个activity  
这个库在 intent到一个新activity  的时候转场动画   不同机型都不一样    
当finish的时候 直接没有动画了  
想问下 以后版本是否有统一activity动画的打算(开始/结束 )

**Comment by YoKeyword** [comment]
Activity动画和Fragmentation无关， 和ROM以及安卓版本有关；

如果需要统一，可以通过设置theme等方式
