### ISSUE TITLE
SupportFragmen能继承v13包里的Fragment吗

### ISSUE THREAD

**Issue by shuaimango** [YoKeyword/Fragmentation#616]
能再增加一个继承v13包里的Fragment的SupportFragment 吗

**Comment by YoKeyword** [comment]
v13包没有Fragment， 你是指的`andorid.app.Fragment` ? 
因为Fragment是跟随安卓系统版本迭代的，所以很多新特性，低版本不支持，所以一般为了保持统一，我们都是使用v4包的
