### ISSUE TITLE
setParallaxOffset not working for SupportActivity

### ISSUE THREAD

**Issue by tyzero** [YoKeyword/Fragmentation#617]
Activity之间跳转，滑动返回没有Parallax效果，翻看源码没差出原因，望解答

**Comment by tyzero** [comment]
Parallax效果Fragment是有效的

**Comment by tyzero** [comment]
if (mPreFragment != null && mPreFragment.getView() != null) 

看到了，才发现这个视差效果是肥Fragment用的😟

**Comment by YoKeyword** [comment]
是的，Activity的视觉差效果以目前的实现机制是不能实现的 

换成`ActivityLifecycleCallbacks`的机制可以实现，但是据说有兼容问题，暂时不打算换实现机制，因为现在的机制对于Fragment是友好的，而Fragmentation主要是为了Fragment :)

如果有兴趣，可以自己更换实现机制

**Comment by tyzero** [comment]
好多，我去试试ActivityLifecycleCallbacks ， thanks 😁
