### ISSUE TITLE
demo的懒加载是如何一回事

### ISSUE THREAD

**Issue by dyfan** [YoKeyword/Fragmentation#62]
demo中微信的有一个懒加载的基类，懒加载不是只适用于viewpager和fragment，你的这个懒加载貌似不是那样的。
有点不懂，你的这个懒加载，和viewpager的哪个懒加载不一样吧。

**Comment by YoKeyword** [comment]
嗯 绝大多数情况 Fragment的懒加载有2种情况：
1、ViewPager的情况
2、类微信QQ主页那种同级的情况

Demo里的是用于主页同级的情况，即：进主页时Fragment都被创建，但是非当前Fragment的其他Fragments里的数据之类的并没有被初始化，仅第一次进入其他Fragment页面时才会走数据的初始化，从而起到节省内存资源的目的～

**Comment by dyfan** [comment]
这个想法很好，我一直想这样写都不知道如何去懒加载，谢谢啦。还有就是viewpager的懒加载，你没有在库里面封装吧。

**Comment by YoKeyword** [comment]
ViewPager的懒加载 demo里没有演示，可以自己实现下，回头闲下来再加上

**Comment by dyfan** [comment]
好的，谢谢啦，营养价值很高，我用的你的bottombar，修改了一个晚上，才改到我要的效果，感觉好糟心哎。

**Comment by YoKeyword** [comment]
Bottombar只是个简单的示例嘛    可能相比我们常用的场景，还缺少消息气泡的显示之类的，不过应该挺容易拓展的～  
或者也可以用第三方开源的～

**Comment by dyfan** [comment]
为嘛有个鄙视的表情，心累。。。我需要加气泡，还有一个圆形的按钮，新手容易踩坑。多谢了。随时关注你。

**Comment by YoKeyword** [comment]
...... 哪个小伙伴踩的，不要总这么消极 － －    没啥解决不了的问题 ＝。＝
