### ISSUE TITLE
栈视图问题

### ISSUE THREAD

**Issue by hcadoid** [YoKeyword/Fragmentation#620]
Activity loadRootFragment GroupMainFragment
GroupMainFragment中根据类型去replaceFragmentA/B/C
ApplyGroupFragment start GroupListFragment
GroupListFragmentstart(ApplyGroupFragment ,SINGLETASK);此时就空白页面了

还有为什么replaceFragment后，GroupMainFragment还存在吗？

最后的栈视图：
![qq 20171101100422](https://user-images.githubusercontent.com/10434110/32256663-59020584-beeb-11e7-8875-b409d1d13c9d.png)

**Comment by hcadoid** [comment]
FragmentA replaceFragment后的FragmentB,FragmentB不能在startWithPop了吗?
日志显示：

FragmentA 's FragmentManager is null,  Please check if FragmentA is destroyed!

我不是在FragmentB里面去start的吗？？怎么去检查A了？

**Comment by hcadoid** [comment]
是Activity中的第一个Fragment受限吗

**Comment by YoKeyword** [comment]
Fragment的回退栈是非常严格的栈，对于加入回退栈的Fragment，是不可能直接操作栈内的任何Fragment的，所以`replaceFragment`并不能替换加入回退栈的Fragment

`startWithPop()` , `popTo(Fragment f, boolean includeF, runnable )`这两个方法可能会满足你的需求

此外，找好场景，对应Demo，查看Demo写法以及wiki会方便很多

**Comment by hcadoid** [comment]
好，我用loadRootFragment和  popChild() 解决了目前的场景。但是动画有有点问题，暂时去除动画。这几个页面的场景需求设计的比较复杂，startWithPop和popTo不能满足，看Demo没有合适的。
