### ISSUE TITLE
怎么pop指定fragment,或者pop之前的所有fragment

### ISSUE THREAD

**Issue by Deepblue1996** [YoKeyword/Fragmentation#622]
如题, 我该怎么pop指定fragment,或者pop之前的所有fragment

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/593

**Comment by Deepblue1996** [comment]
我想在Fragment C, pop Fragment A, 不是popTo

**Comment by YoKeyword** [comment]
在C上关闭前面的A、B，即使在Activity的场景来看，也是奇怪的

你可以在关闭C时，替换成`popTo(A,true)`， 将ABC同时关闭掉

> Fragment的回退栈是非常严格的栈结构，只能从栈顶出栈
