### ISSUE TITLE
使用Butterkinfe引起的crash bug

### ISSUE THREAD

**Issue by bbiii** [YoKeyword/Fragmentation#623]
在项目中用Butterkinfe,生成代码时会自动在onDestroyView()里生成unbinder.unbind方法.我项目做完才发现如果在start(fragment)时快速点击回退就会crash.看了log,应该是fragment销毁之后,view已经被unbind,但是我联网操作的数据还在执行填充到view的步骤.
我现在把unbinder.unbind删除掉.暂时没出现crash了.但是感觉这样不利于内存的回收.不知道有没有的解决办法?

**Comment by YoKeyword** [comment]
Fragment销毁时及时停止异步任务， 否则会造成内存泄漏，以及如果回调后操作View，还会引起View层的Crash

不建议通过删除`unbind`来解决这个问题，务必要停止异步任务
