### ISSUE TITLE
viewpager 中使用的问题

### ISSUE THREAD

**Issue by KinaZhen** [YoKeyword/Fragmentation#624]
在viewpager 中使用fragmentStatePagerAdapter  ,共有6个卡页，在调用viewPager.setAdapter 后，继续调用viewPager.setCurrentItem(4) ，（默认显示第5个卡页的意思）, 这时 这个卡页下fragment显示正常，然后通过点击第一个卡页tab , 回到第一个卡页下的fragment时， 这个fragment不走onLazyInitView;  请问为什么？

**Comment by LonelyMushroom** [comment]
`onLazyInitView`:
```
     /**
     * Lazy initial，Called when fragment is first called.
     * <p>
     * 同级下的 懒加载 ＋ ViewPager下的懒加载  的结合回调方法
     */
    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        mDelegate.onLazyInitView(savedInstanceState);
    }
```
源码里面有注释........

**Comment by YoKeyword** [comment]
@KinaZhen  
> 然后通过点击第一个卡页tab , 回到第一个卡页下的fragment时， 这个fragment不走`onLazyInitView`

经测试，切回第1个Fragment时 正常回调`onLazyInitView`

**Comment by YoKeyword** [comment]
@KinaZhen 
`viewPager.setAdapter`在哪里调用的，`onActivityCreated()`? `onLazyInitView()`?    

代码贴下

**Comment by KinaZhen** [comment]
代码如下

@Override
    public void onEnterAnimationEnd(Bundle savedInstanceState) {
        super.onEnterAnimationEnd(savedInstanceState);
        initView();
    }

    private void initView(){
        ProductCatPagerAdapter productCatPagerAdapter = new     ProductCatPagerAdapter(getChildFragmentManager());
        productCatPagerAdapter.setProductTypeCategories(productTypeCategories);
        productCatPagerAdapter.setiProductCatListener(this);
        viewPager.setAdapter(productCatPagerAdapter);
        viewPager.setCurrentItem(4,false);
    }

**Comment by YoKeyword** [comment]
在`onEnterAnimationEnd()`中模拟了下， 在切回第一个Fragment时，可以正常回调`onLazyInitView()`

**Comment by KinaZhen** [comment]
不是在 onEnterAnimationEnd() 中切回第一个，而是 手动点击 tab 切回第一个

**Comment by YoKeyword** [comment]
@KinaZhen 是手动切回,  在`onEnterAnimationEnd()`中init，  然后手动切回第一个Fragment, 第一个Fragment的`onLazyInitView()`正常回调

但是确实存在BUG，在这种场景下`FragmentStatePagerAdapter `正常，但是`FragmentPagerAdapter `第一次不回调，  你再确认下是`FragmentStatePagerAdapter`还是`FragmentPagerAdapter `

**Comment by YoKeyword** [comment]
@KinaZhen 排查了下，是v1.1.7这个commit 8b1d7b4ce7c7568812e1ebd18be264be03bfa687 引起的，已修复：commit 6017d60f273bf1fdd3799d79ee34329cff338d3c

请更新至v1.1.8
