### ISSUE TITLE
不能获取正确的resultCode

### ISSUE THREAD

**Issue by abings** [YoKeyword/Fragmentation#626]
三个fragment a b c, a 到 b,然后b到c,两次setResultPhoto，从c通过popTo到a.设置了setFragmentResult。  依此顺序 b先获取到正确的onFragmentResult－－，然后b设置setFragmentResult，a无法获取到正确的resultCode

**Comment by YoKeyword** [comment]
在你的场景下，B的 `setFragmentResult()`写在B的`onFragmentResult()`里即可正常回调给A

**Comment by abings** [comment]
我就是在B的onFragmentResult()里面设置的setFragmentResult()，a无法获取。请验证，谢谢，辛苦了。

**Comment by YoKeyword** [comment]
我验证后回复的，是可以正常回调的...
