### ISSUE TITLE
SupportFragment.start问题

### ISSUE THREAD

**Issue by keternity** [YoKeyword/Fragmentation#629]
SupportFragment.start在oppo（oppo R9tm）和vivo部分手机上会出现无数据或者EditText无法输入（用Layout Inspector解析布局时，能看到布局框子，然而手机上就是白屏），但是换成一个Activity加载一个Fragment，就没这个问题了

**Comment by LonelyMushroom** [comment]
你贴下代码片段,版本号,详细描述下

**Comment by keternity** [comment]
在SupportFragment中调用start(SubordinateFriendFragment_.builder().level(groupPosition + 1).title(adapter.getTitle(groupPosition)).build());
SubordinateFriendFragment中有一个toolbar和Recycleview，toolbar能显示，但是Recycleview里面的内容数据就显示不了了
版本号是1.1.8

**Comment by LonelyMushroom** [comment]
那么检查下RV的初始化.demo里面也有你这种情况,我平时使用也没有问题

**Comment by keternity** [comment]
找到问题了。。。。是之前不知道哪个前任在Manifest的application标签中加了android:hardwareAccelerated="false"这句，就会导致fragment.start时，新加载的fragment就会白屏，不显示数据
