### ISSUE TITLE
请教一个问题，viewPager+FragmentPagerAdapter+懒加载实现知乎Demo与Fragmentation的异同

### ISSUE THREAD

**Issue by AnyLifeZLB** [YoKeyword/Fragmentation#63]
知乎那个demo,使用Show,hide 的方式处理Fragment，也可以用viewPager+FragmentPagerAdapter+懒加载实现几乎一致的效果。
我要请教的问题是：两者之间有什么异同点？性能啊，开发维护成本啊，交互效果啊等等，谢谢。

**Comment by YoKeyword** [comment]
这个要看个人习惯和产品需求，
开发上ViewPager比较简单，毕竟FragmentAdapter帮助处理了恢复问题，只需设置setOffscreenPageLimit()+懒加载就可以实现可滑动的show/hide交互效果，当然ViewPager也可以设置为不可滑动。
性能和维护成本感觉无明显区别。
