### ISSUE TITLE
怎么返回父级并刷新父级页面

### ISSUE THREAD

**Issue by isqing** [YoKeyword/Fragmentation#630]
A->B,B返回后，A的页面刷新

**Comment by LonelyMushroom** [comment]
[使用场景－-startForResult接收数据返回&启动模式start](https://github.com/YoKeyword/Fragmentation/wiki/7.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-startForResult%E6%8E%A5%E6%94%B6%E6%95%B0%E6%8D%AE%E8%BF%94%E5%9B%9E&%E5%90%AF%E5%8A%A8%E6%A8%A1%E5%BC%8Fstart)

**Comment by YoKeyword** [comment]
或者 跨层级太多时，考虑EventBus，建议使用[eventbus_activity_scope](https://github.com/YoKeyword/Fragmentation/tree/master/eventbus_activity_scope)
