### ISSUE TITLE
能弄个fragment嵌套的demo么

### ISSUE THREAD

**Issue by liupeng110** [YoKeyword/Fragmentation#632]
库很棒,我用的时候遇到一些小问题
架构是单activity+多fragment(用的继承supporactivity/fragment的方式)
1.在activity设置rootFragment之后,用start方式启动其他fragment ，之后 按返回键 下层的rootfragment会有透明 能看到桌面(滑动时正常)  如何才能back键时候 下面也不透明  或者说如何才能去掉rootfragment的各种淡入淡出效果 
2.在start之后的fragment里面viewpager的滑动事件冲突   滑动返回无效  
(需要的效果是 viewpager滑动到第一个之后 再滑动退出fragment)
类似demo里面仿微信那里：  消息 发现 朋友圈  可以依次滑动 ，滑动到发现的时候  里面有两个子fragment (子fragment可以滑动)  ,子fragment滑动到最右边 继续右滑   可以滑动到朋友圈          这样的效果能实现么

3.两层fragment    两层都需要可以替换  需求场景类似qq音乐播放器底部bottom
在bottom下面有个rootfragment可以正常调start启动各个fragment ，启动的fragment现在都在bottom下面 ，然后还需要再启动一个fragment在所有fragment上面,但是直接start（fragment）就还在rootfragment这一层  （还在bottom下面）    
最好可以给个demo啊老哥   fragment嵌套处理这里
4.滑动时候的视差如何去掉.

**Comment by YoKeyword** [comment]
1、对RootFragment的动画设置下即可（不过好像默认情况下不会透明，可以看下Demo）

2、滑动返回依赖于v4包的ViewDragHelper，它的默认滑动冲突机制就是如此，如果需要定制滑动事件，需要自己去解决

3、没太懂场景，不过看起来可以参考知乎Demo的栈设计， 先理清栈结构，考虑好分层问题

4、滑动视差去掉：
````java
setParallaxOffset(0.0f)
````
