### ISSUE TITLE
不依赖FragmentManager获取对应 fragment 的实例

### ISSUE THREAD

**Issue by VankaIn** [YoKeyword/Fragmentation#633]
- 场景：在不使用 eventbus 的情况下，每次 start 都要关注层级结构使用 ，不同页面 start 一个 fragment 有不同的层级关系，造成start 一个 fragment 的代码不统一，比如有可能是getParentFragment().start()或是getParentFragment().getParentFragment().start()等，而且当 fragment 的层级关系发生改变的时候（比如提前一个层级），就得把start()代码做更改  和界面层次耦合。

- 疑问：那么遇到这样的情况，为什么不提供根据 class 获取全栈内的Fragment 呢？利用SupportHelper.findFragment(Class<T> fragmentClass) 获取对应的实例，从而简化调用方法（简化为只要确定启动的层级，那么每个地方都可以这样调用：（SupportHelper.findFragment(Main Fragment.class).start(new LoginFragment.class) ）

- 解决方案：而这些 Fragment 在 onCreateView 的时候入栈，在 onDestoryView 的时候出栈。

**Comment by YoKeyword** [comment]
想法很棒！

但是不得不解决一个问题，加入多个栈都有同一个FragmentA的不同实例， 那么这时通过`SupportHelper.findFragment(AFragment.class)` 将得不到正确的实例...

不过当然也有相应的解决上面问题的方案：
````java
// 启动
extraTransaction()
.setTag(tag)
.start(AFragmentInstance)

// 获取
SupportHelper.findFragment(tag)
````

但是仍会存在一个问题，假设用户手抖 连续启动2个tag为A的FragmentA， 在获取时依然会存在问题

目前没有特别好的方式解决这些隐患，如果有好的方式，继续在这里探讨哈

**Comment by VankaIn** [comment]
首先谢谢 @YoKeyword  解答和思路。

针对多个实例的问题，我认为可以提供两个方法：
一个是只有一个实例的情况：
```
ISupportFragment SupportHelper.findFragment(AFragment.class)
```

多个实例的情况：
```
List<ISupportFragment> SupportHelper.findFragment(AFragment.class)
```

一个实例的情况返回栈底的第一个实例; 而多个实例的情况可以返回所有栈中的所有实例，用户就可以根据入栈的顺序来利用 ``` get(int index) ``` 获取对应的ISupportFragment实例了。这样就可以根据这两个方法来找到对应启动者来 start 对应的 fragment ，而不用每次 start 的时候都要确认启动者到底是 parent，还是 parent 的 parent，还是...， 也不怕中间突然多一个层级的问题导致对应很多 ```getParentFragment().start() ```的页面的代码做```getParentFragment().getParentFragment().star()```很多这样的修改。

**Comment by YoKeyword** [comment]
但是问题是 很多情况 我们并不能确定 所需要的Fragment是List中的哪一个，容错率低   

考虑实际场景中，Tag是更好的方式，但是上面也提到，依然会存在一些隐患，这个想法后面会再考虑

你也可以自己先通过`FragmentLifecycleCallbacks`实现这个`findFragment`功能，看看效果如何

**Comment by VankaIn** [comment]
好的，谢谢
