### ISSUE TITLE
仿微信那个案例，在Mainactivity 中启动MainFragment ，在 Fragment中设置 onBackPressedSupport 方法无效

### ISSUE THREAD

**Issue by ming0101** [YoKeyword/Fragmentation#634]
在Mainactivity 中启动MainFragment ，在 Fragment中设置 onBackPressedSupport 方法无效，

**Comment by YoKeyword** [comment]
应该是`BaseMainFragment`拦截了，相关代码在[这里](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_wechat/base/BaseMainFragment.java)

从子栈、栈顶开始触发，过程中如果被拦截，那么父栈或栈底的Fragment就不会收到`onBackPressedSupport `回调

具体BACK处理机制可以参考[wiki](https://github.com/YoKeyword/Fragmentation/wiki/6.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-Back%E9%94%AE%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E6%9C%BA%E5%88%B6)
