### ISSUE TITLE
锁屏生命周期的问题

### ISSUE THREAD

**Issue by VankaIn** [YoKeyword/Fragmentation#635]
在单个 activity（MainActivity） 的情况下，锁屏后解锁 ，会导致该 MainActivity 下的所有 fragment 的 onSupportVisible和onResume 都会调用一遍，请问楼主有具体的解决具体方案吗？

**Comment by YoKeyword** [comment]
Android系统的机制就是这样的： 解锁后 Activity走`onResume`，其下的Fragment自然也走对应生命周期；

这样设计是有意义的，锁屏前走了`onPause`，解锁走`onResume`

**Comment by VankaIn** [comment]
@YoKeyword  你好，Android系统的机制的确是这样的。

- 问题：但是这样会造成 单个Activity + 多个 fragmnet 这种模式开发的情况下，缺少了一个像 activity 的 onresume（）的生命周期， 开发起一些业务来就很鸡肋，比如：有一个业务，每个界面由不可见到可见的时候调用一次，那么```onSupportVisible()```和```onResume()```都不能实现了，因为锁屏->解锁的时候在栈底下的不可见的 fragment 的这两个方法也调用了，显然不是我想要的不可见到可见。

- 建议：我的思路是，不知道是否可以在 ```onSupportVisible()``` 的方法里面加上判断
```
if(SupportHelper.getTopFragment() == this){
            this.onRealResume();
}
```
这样这个```onRealResume()```应该就可以和 activity 的生命周期一样。当然如果当前页面有多个 fragment 同时显示在界面的时候会有问题（比如上边一个 fragment，下边一个 fragment），会造成锁屏->解锁的时候只调用了有一个 fragment 的onRealResume（）。还有就是 ```replace()``` 的时候也有问题，不过这个只要换一下栈内的位置就好。

以上是我的想法，谢谢

**Comment by YoKeyword** [comment]
`onSupportVisible()`  对于在栈底的Fragment 在解锁时 是不会回调的，你可以测试下

`onSupportVisible()`的含义就是 在该Fragment可见时触发，`onSupportInvisible()`不可见时触发

**Comment by alienzh** [comment]
我发现一个现象，按电源键以后页面黑屏，当前fragment走onSupportInvisible；再次按电源键，屏幕亮了，显示手机屏保页面，当前fragment会先走onSupportVisible，再走onSupportInvisible；划走屏保当起那fragment再次走onSupportVisible
等于是走了两次onSupportVisible，理论上打开电源键，屏幕并没有进入app，不应该走onSupportVisible
请问下这个怎么处理

**Comment by chaxiaomao** [comment]
最近项目用了横屏（必要前提，横屏才会这样），之后使用单Activity + 多Fragment的方式来实现业务，但是后来测试时候发现手机在锁屏之际，Fragment会重新调用生命周期，而且会执行2次生命周期，调试很多方式，最后找到问题，连接给上https://my.oschina.net/u/246578/blog/165434，就是在activity中configChanges配置screenSize|keyboardHidden|orientation，针对api13以上横屏生命周期问题。
