### ISSUE TITLE
fragment会机率性产生重叠现象

### ISSUE THREAD

**Issue by weizai** [YoKeyword/Fragmentation#636]
猜测是内存泄漏了，咨询下复现方式和解决方式？

**Comment by LonelyMushroom** [comment]
[9行代码让你App内的Fragment对重叠说再见](http://www.jianshu.com/p/c12a98a36b2b)
[demo 代码](https://github.com/YoKeyword/Fragmentation/blob/94e95a812505c8d06edea43979a8deba0233bf89/demo/src/main/java/me/yokeyword/sample/demo_wechat/ui/fragment/MainFragment.java#L60)

**Comment by weizai** [comment]
目前项目用的就是fragmentation库，按特性来说应该已经考虑了这样的问题。用monkey test测试工具会比较容易复现

**Comment by YoKeyword** [comment]
@weizai  如果你使用高版本v4包的话，重叠的原因几乎都是 重复加载了Fragment，比如屏幕旋转等页面重启的情况

建议开启开发者模式-> 不保留活动 来测试复现

**Comment by weizai** [comment]
感谢提供解决思路，再测试一下，如果是因为高版本v4导致，能否更版本解决这个问题？

**Comment by YoKeyword** [comment]
额对，你使用的Fragmentation， 那么低版本官方重叠的BUG 是兼容了的， 所以猜测重叠的原因应该是重复加载了同Fragment的不同实例
