### ISSUE TITLE
使用懒加载viewpager加载多个tab标签页面布局 其中出现广告条切换白屏

### ISSUE THREAD

**Issue by zuojianjian** [YoKeyword/Fragmentation#637]
就是切换多个tab页面之后再次切换回第一个界面的广告图片加载不出来是白屏但可见可点击广告条切换正常，求大神给点建议

**Comment by LonelyMushroom** [comment]
你第一个页面的内容只有广告么,如果其他的可以正常展示,请检查广告部分代码.
