### ISSUE TITLE
深入研究发现2个问题

### ISSUE THREAD

**Issue by aaatttcccc** [YoKeyword/Fragmentation#638]
大神你好，我有个项目已经用你的框架用了3个月了，也更新新版本解决了一些新问题，但目前我研究了动画，发现基于你这个框架实现的话，有些问题，不知道你可以提供你联系方式来一起研究下这个问题吗？

你现在这个框架的Transaction共享控件动画是只有返回，没有进入的

如果是类似这种写法：
fromFragment.getFragmentManager().beginTransaction()
.replace(R.id.flContainer, toFragment)
.addToBackStack(null)
.addSharedElement(swipeLayout, "Content")
.commit();

就能完美呈现出进入和退出的共享动画

还有个问题：
感觉是官方问题，我直接在你的demo上修改的。在CycleFragment添加一个edittext。运行之后，点击仿知乎app，然后点击列表的其中一项，再点击FloatingActionButton按钮跳转到CycleFragment，点击刚才新添加的edittext显示出软键盘。然后返回，会发现FloatingActionButton默认在最下面。。过几秒又跳回原来的位置

望一起研究！谢谢大神！能否私信我添加qq或者微信吗

**Comment by YoKeyword** [comment]
1、`replace`官方一直支持的，`add`在v4包的v25.1.0时支持，后续又不支持，暂时只能等官方修复了
2、官方的`add`和`CoordinatorLayout`的冲突
