### ISSUE TITLE
onEnterAnimationEnd 方法中不是建议设置数据吗 为什么会执行两次这个方法

### ISSUE THREAD

**Issue by zuojianjian** [YoKeyword/Fragmentation#639]
onEnterAnimationEnd 方法中不是建议设置数据吗 为什么会执行两次

**Comment by YoKeyword** [comment]
哪种场景下 执行了2次？  可否复现？

**Comment by zuojianjian** [comment]
每次启动加载fragment都会去所有的方法中执行两次

**Comment by YoKeyword** [comment]
@zuojianjian  无法复现，可以查看下Demo的调用情况。  

如果是每次启动都会加载两次，检查下写法
