### ISSUE TITLE
fragment回退问题

### ISSUE THREAD

**Issue by galileolvpo** [YoKeyword/Fragmentation#64]
![1111](https://cloud.githubusercontent.com/assets/18024983/17829713/03acfba2-66ea-11e6-9d74-76737e01cb42.png)

我想从最上面的fragment 回退到 startFragment, 执行了popTo(SettingFragment.class,true); 后的确是回退过去了，但是没有动画

**Comment by YoKeyword** [comment]
@galileolvpo popTo方法是不带动画的，最主要的原因是为了性能，如果一次出栈较多Fragment，带动画的话会不同程度的卡顿，不带动画则是瞬间出栈。
还有一些其他原因~

在这个issue上我也有回答~[issues45](https://github.com/YoKeyword/Fragmentation/issues/45)

**Comment by galileolvpo** [comment]
多谢解答~
