### ISSUE TITLE
eventbus是怎么实现主页上打开的是一个新页面

### ISSUE THREAD

**Issue by isqing** [YoKeyword/Fragmentation#640]
当在主页我用start启动一个Fragment时，老是在这个页面跳转，底部导航还在，用eventbus就会打开一个新页面，请问这个原理是什么？

**Comment by YoKeyword** [comment]
EventBus发送事件后，接收方是当前Fragment的父Fragment， 所以父Fragment再`start(A)`自然是打开父Fragment所在栈的A，即打开了当前Fragment的父栈的Fragment
