### ISSUE TITLE
熄屏后启动loadRootFragment()报Fragment has not been attached yet

### ISSUE THREAD

**Issue by NeverMorer** [YoKeyword/Fragmentation#643]
override fun onLazyInitView(savedInstanceState: Bundle?) {
        super.onLazyInitView(savedInstanceState)

        if (findChildFragment(BabiesFragment::class.java) == null) {
            val babiesFragment = BabiesFragment()
            babiesFragment.arguments = arguments
            loadRootFragment(R.id.layoutFragmentHome, babiesFragment)
        }
    }

当前Fragment是在MainActivity下的四个tab fragment 之一，都是一loadRoot的方式attach的

**Comment by YoKeyword** [comment]
首先4个TabFragment 好像用`loadMultipleRootFragment()`更合适

其次`Fragment has not been attached yet` 这个异常是指 Fragment还没有被加载完成，你就操作了Fragment的内部生命周期相关方法， 报错指向的行 应该不是这个地方， 因为`find==null`的情况下，`load`应该是安全的， 你再检查下

**Comment by NeverMorer** [comment]
目前了解到的原因是，息屏后过了一段时间，homeFragment被回收了，唤醒时报的这个异常，没有手动干预生命周期，4个TabFragment是以loadMultipleRootFragment()的方式load的

**Comment by YoKeyword** [comment]
Fragment如果被回收，那么在唤醒时 会被恢复，此时 `findFragment()`会找回那个Fragment。

你需要再次定位出现问题的代码

**Comment by dx-berry** [comment]
这个要如何避免，最好的处理结果呢？
