### ISSUE TITLE
用8.1测试的时候发现这样一个问题，导致app直接启动不了

### ISSUE THREAD

**Issue by xicong** [YoKeyword/Fragmentation#644]
![image](https://user-images.githubusercontent.com/11675597/32876594-7e79669c-cad8-11e7-83d6-f5aac626b3f7.png)

**Comment by LonelyMushroom** [comment]
[stackoverflow1](https://stackoverflow.com/questions/47093127/facebook-android-only-fullscreen-opaque-activities-can-request-orientation)
[stackoverflow2](https://stackoverflow.com/questions/46992843/interstitial-admob-ads-illegalstateexception-only-fullscreen-activities-can-r)

你可以参考下这个回答.

**Comment by xicong** [comment]
ok，可以了，谢谢
