### ISSUE TITLE
Activity销毁时，画面卡顿一下，才消失

### ISSUE THREAD

**Issue by littlezan** [YoKeyword/Fragmentation#645]
现象和demo中，仿GooglePlay交互中，从侧边栏打开SwipeBackActivity,返回退出效果类似。
在SwipeBackSampleActivity销毁的时候，会看到一个明显的卡顿现象。
请问是什么原因造成的，有什么解决方案吗？

**Comment by YoKeyword** [comment]
Demo是否有该问题？

**Comment by littlezan** [comment]
嗯，是的，我的现象和demo一样的(不知道是不是和我手机有关系)，还有就是，我发现使用SwipebackActivity的时候，当activity栈内activity比较多的时候，退出时，会有明显的卡顿。

**Comment by YoKeyword** [comment]
Fragmentation的侧滑滑动机制是参考[SwipeBackLayout](https://github.com/ikew0ng/SwipeBackLayout)的，这个机制虽然兼容性良好，但是缺点是SwipeBackActivity不会走`onStop`，这代表当Activity比较多时，绘制压力会很大，导致卡顿

所以该机制并不适合可能会打开很多Activity的场景，Fragmentation选用该机制的原因是：
* 稳定，兼容性好
* Fragmentation出发点在于 少Activity多Fragment
