### ISSUE TITLE
这是什么问题啊 fragment 里面的dialogfragment引发的错误

### ISSUE THREAD

**Issue by k354250377** [YoKeyword/Fragmentation#646]
1 android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
--
2 android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
3 android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
4 android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
5 android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
6 com.example.yixixinapp.ui.fragment.NewHomeFragment.initSginDialog(NewHomeFragment.java:232)
7 com.example.yixixinapp.ui.fragment.NewHomeFragment.access$1100(NewHomeFragment.java:81)
8 com.example.yixixinapp.ui.fragment.NewHomeFragment$3.onSuccess(NewHomeFragment.java:216)
9 com.example.yixixinapp.ui.fragment.NewHomeFragment$3.onSuccess(NewHomeFragment.java:208)
10 com.lzy.okgo.adapter.CacheCall$3.run(CacheCall.java:247)
11 android.os.Handler.handleCallback(Handler.java:751)
12 android.os.Handler.dispatchMessage(Handler.java:95)
13 android.os.Looper.loop(Looper.java:185)
14 android.app.ActivityThread.main(ActivityThread.java:6493)
15 java.lang.reflect.Method.invoke(Native Method)

**Comment by LonelyMushroom** [comment]
你是不是在onResume里面提交事务了？
[chekStateLss](http://blog.chengyunfeng.com/?p=522)
