### ISSUE TITLE
banner跟viewpager+tab切换时出现图片不显示白屏的情况

### ISSUE THREAD

**Issue by zuojianjian** [YoKeyword/Fragmentation#647]
第一个tab头部是banner轮播，当轮播未完成一次循环时，进行tab页面切换使用懒加载的方式加载的其他页面，快速切换后重新回到第一个tab页面出现未完成第一次显示的图片为空白图片，已完成切换的正常显示。如果等待所有的banner图片完成一次轮播后，再进行tab切换则一切正常，问下这个是什么原因造成的呢，拜谢！！！

**Comment by LonelyMushroom** [comment]
> 第一个tab页面出现未完成第一次显示的图片为空白图片

初步怀疑是你banner库，或者你自己处理banner的问题。
[我的项目banner](https://github.com/LonelyMushroom/Architecture/blob/97ebde136c23dbb738cb0383750315a19e415657/RxArchitecture/app/src/main/java/com/minister/architecture/ui/zhihu/child/DailyListFragment.java#L110)
你可以看看我是怎么处理的，场景跟你一样的。
还有你发起了两次相同的iss，下次尽量避免。
