### ISSUE TITLE
FragmentPagerAdapter 里remove白屏

### ISSUE THREAD

**Issue by abings** [YoKeyword/Fragmentation#648]
请教什么原因？这和上一个兄弟提的banner里白屏可能一样的原因吧。辛苦

原因描述：
   在FragmentPagerAdapter里面更新fragment出现白屏不能显示，
````java
private void setFragments(ArrayList<Fragment> mFragmentList) {
            if (this.mFragmentList != null) {
                FragmentTransaction fragmentTransaction = mFragmentManager.beginTransaction();
                for (Fragment f : this.mFragmentList) {
                    fragmentTransaction.remove(f);
                }
                fragmentTransaction.commit();
                mFragmentManager.executePendingTransactions();
            }
            this.mFragmentList = mFragmentList;
            notifyDataSetChanged();
        }
````

**Comment by LonelyMushroom** [comment]
这个场景有点奇怪，你要不然先 `pop` 这个父级fragment，接着重新 `start` 可以实现么？

**Comment by abings** [comment]
这个场景其实蛮常见的，因为要动态更新viewpage的页面数量。没有父fragment.如果直接关掉重建父类肯定可以，但是资源消耗不合理。或者 有什么你确认可行的其他建议？谢谢

**Comment by LonelyMushroom** [comment]
>但是资源消耗不合理

可是你。。。
```
for (Fragment f : this.mFragmentList) {
      fragmentTransaction.remove(f);
}
```
把所有的fragment都移除了呀。。。我去试试看看有没有你这种情况才，等下哈

**Comment by LonelyMushroom** [comment]
```
        // if (this.mFragmentList != null) {
        //     FragmentTransaction fragmentTransaction = mFragmentManager.beginTransaction();
        //     for (Fragment f : this.mFragmentList) {
        //         fragmentTransaction.remove(f);
        //     }
        //     fragmentTransaction.commit();
        //     mFragmentManager.executePendingTransactions();
        // }
```
这一段注释掉就不会白屏了，但是我觉得这么写不合适，看看作者的回复吧。

**Comment by abings** [comment]
如果不做remove操作，重新加数据页面时  以前的fragment不会释放掉。谢谢回复，等作者看看了。

**Comment by abings** [comment]
我上面的操作对普通fragmen时候是正常的。SupportFragment下才会有问题

**Comment by YoKeyword** [comment]
@abings @LonelyMushroom  

动画的原因，因为remove会触发动画，动画不结束的情况下`notify/setAdapter`，因为依旧持有对象，导致Fragment并不能立即从FM中移除

解决方案：
````java
public void setFragments(final ViewPager viewPager, ArrayList<Fragment> mFragmentList) {
        FragmentTransaction fragmentTransaction = mFragmentManager.beginTransaction();
        if (this.mFragmentList != null) {
            for (Fragment f : this.mFragmentList) {
                fragmentTransaction.remove(f);
            }
            fragmentTransaction.commit();
            mFragmentManager.executePendingTransactions();
        }

        this.mFragmentList = mFragmentList;

        viewPager.postDelayed(() -> viewPager.setAdapter(YourAdapter.this), 0-300);
    }
````

**延迟0-300ms取决于你 子Fragment的动画模式， 如果是DefaultNoAnimator，则延迟0ms，此时可以使用viewPager.post()**

**Comment by abings** [comment]
非常感谢，希望越来越好！

**Comment by abings** [comment]
发现还是有问题，onLazyInitView次数不对，多了一次，我把测试代码发出来请验证。
public class MainActivity extends AppCompatActivity implements ISupportActivity {


    final SupportActivityDelegate mDelegate = new SupportActivityDelegate(this);

    ViewPager viewPager;
    List<Integer> mList;
    MyAdapter adapter;
    View view;

    private int aaa = 100;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mDelegate.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        view = findViewById(R.id.btn);
        view.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                viewPager.setCurrentItem(0);
                mList.add(aaa++);
                adapter.updateData(mList);
                viewPager.post(new Runnable() {
                    @Override
                    public void run() {
                        viewPager.setAdapter(adapter);
                    }
                });
               // adapter.addClear();
            }
        });

        findViewById(R.id.btn111).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mList.remove(0);
                adapter.updateData(mList);
               // adapter.add();
                viewPager.post(new Runnable() {
                    @Override
                    public void run() {
                        viewPager.setAdapter(adapter);
                    }
                });
            }
        });

        findViewById(R.id.btn222).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                getSupportDelegate().logFragmentStackHierarchy("abings");
            }
        });
        viewPager = (ViewPager) findViewById(R.id.pager);
        ((TabLayout) findViewById(R.id.tab)).setupWithViewPager(viewPager,true);
        mList = new ArrayList<>();
        for (int i = 1; i < 5; i++) {
            mList.add(i);
        }
        adapter = new MyAdapter(getSupportFragmentManager(), mList);
        viewPager.setAdapter(adapter);

    }


    @Override
    public SupportActivityDelegate getSupportDelegate() {
        return mDelegate;
    }

    @Override
    public ExtraTransaction extraTransaction() {
        return mDelegate.extraTransaction();
    }

    @Override
    public FragmentAnimator getFragmentAnimator() {
        return mDelegate.getFragmentAnimator();
    }

    @Override
    public void setFragmentAnimator(FragmentAnimator fragmentAnimator) {
        mDelegate.setFragmentAnimator(fragmentAnimator);
    }

    @Override
    public FragmentAnimator onCreateFragmentAnimator() {
        return mDelegate.onCreateFragmentAnimator();
    }

    @Override
    public void onBackPressedSupport() {
        mDelegate.onBackPressedSupport();
    }


    public class MyAdapter extends FragmentPagerAdapter {

        private ArrayList<Fragment> mFragmentList;
        private FragmentManager mFragmentManager;

        public MyAdapter(FragmentManager fm, List<Integer> types) {
            super(fm);
            this.mFragmentManager = fm;
            mFragmentList = new ArrayList<>();
            for (int i = 0, size = types.size(); i < size; i++) {
                mFragmentList.add(MyFirstFragment.newInstance(types.get(i)));
            }
            setFragments(mFragmentList);
        }

        private void setFragments(ArrayList<Fragment> mFragmentList) {
            if(this.mFragmentList != null){
                FragmentTransaction fragmentTransaction = mFragmentManager.beginTransaction();
                for(Fragment f:this.mFragmentList){
                    fragmentTransaction.remove(f);
                }
                fragmentTransaction.commit();
                mFragmentManager.executePendingTransactions();
            }
            this.mFragmentList = mFragmentList;
            notifyDataSetChanged();
        }

        public void updateData(List<Integer> dataList) {
            ArrayList<Fragment> fragments = new ArrayList<>();
            for (int i = 0, size = dataList.size(); i < size; i++) {
                Log.e("FPagerAdapter1", dataList.get(i).toString());
                fragments.add(MyFirstFragment.newInstance(dataList.get(i)));
            }
            setFragments(fragments);
        }

        public void add() {
            mFragmentList.add(MyFirstFragment.newInstance(mFragmentList.size() + 100));
            notifyDataSetChanged();
        }

        public void addClear() {
            mFragmentList.clear();
            mFragmentList.add(MyFirstFragment.newInstance(mFragmentList.size() + 100));
            mFragmentList.add(MyFirstFragment.newInstance(mFragmentList.size() + 100));
            notifyDataSetChanged();
        }


        @Override
        public Fragment getItem(int position) {
            return mFragmentList.get(position);
        }

        @Override
        public int getCount() {
            return this.mFragmentList.size();
        }

        public int getItemPosition(Object object) {
            return POSITION_NONE;
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return  mFragmentList.get(position).getArguments().getString("searchType","tab");
        }
    }


}




******************************************** 这是更换page数据后的debug,  每行后面的数字是页面的名称
11-23 13:49:04.892 8792-8792/com.example.administrator.debug E/abings: onCreateView: 1
11-23 13:49:04.897 8792-8792/com.example.administrator.debug E/abings: onCreateView: 2
11-23 13:49:04.900 8792-8792/com.example.administrator.debug E/abings: onDestroy: 2
11-23 13:49:04.901 8792-8792/com.example.administrator.debug E/abings: onDestroy: 4
11-23 13:49:04.901 8792-8792/com.example.administrator.debug E/abings: onDestroy: 100
11-23 13:49:04.902 8792-8792/com.example.administrator.debug E/abings: onCreate: 2
11-23 13:49:04.902 8792-8792/com.example.administrator.debug E/abings: onCreate: 4
11-23 13:49:04.903 8792-8792/com.example.administrator.debug E/abings: onCreate: 100
11-23 13:49:04.904 8792-8792/com.example.administrator.debug E/abings: onCreate: 2
11-23 13:49:04.910 8792-8792/com.example.administrator.debug E/abings: onCreateView: 2
11-23 13:49:04.941 8792-8792/com.example.administrator.debug E/abings: onLazyInitView: 1
11-23 13:49:04.949 8792-8792/com.example.administrator.debug E/abings: onDestroy: 1
11-23 13:49:04.950 8792-8792/com.example.administrator.debug E/abings: onCreate: 1
11-23 13:49:04.951 8792-8792/com.example.administrator.debug E/abings: onCreate: 1
11-23 13:49:04.956 8792-8792/com.example.administrator.debug E/abings: onCreateView: 2
11-23 13:49:04.961 8792-8792/com.example.administrator.debug E/abings: onCreateView: 1
11-23 13:49:04.992 8792-8792/com.example.administrator.debug E/abings: onLazyInitView: 1

**Comment by YoKeyword** [comment]
Demo中模拟 自测正常

第一次`onLazyInitView: 1` 应该是上次销毁时触发的，因为后面紧跟个`onDestroy: 1`
