### ISSUE TITLE
在demo中的第一个demo_flow中登陆问题

### ISSUE THREAD

**Issue by smarthityou** [YoKeyword/Fragmentation#65]
该demo中实现登陆功能，在LoginFragment中登陆成功后，调用mOnLoginSuccessListener.onLoginSuccess(strAccount);  但是必须在MainActivity中实现LoginFragment.OnLoginSuccessListener，而我现在是其他页面（fragment）跳转到登陆页面，然后登陆成功后返回该fragment，该fragment实现了LoginFragment.OnLoginSuccessListener就不能正常的“收到”登陆成功的消息，只有在MainActivity中才能收到，请问大神  这个怎么解决或者是思路。不想用广播的形式。 @YoKeyword

**Comment by YoKeyword** [comment]
@smarthityou  这种场景建议用EventBus，这个是重度使用Fragment必备的～

**Comment by smarthityou** [comment]
好的  已经解决了   谢谢
