### ISSUE TITLE
关于onSupportVisible回调问题

### ISSUE THREAD

**Issue by HulkHou** [YoKeyword/Fragmentation#650]
版本：
compile 'me.yokeyword:fragmentation:1.1.6'
compile 'me.yokeyword:fragmentation-swipeback:1.1.6'
compile 'me.yokeyword:eventbus-activity-scope:1.1.0'

结构：
仿知乎结构 1个Activity + 4个主Fragment + 若干 子Fragment

问题场景：
1.从主A  Fragment 中进入 A1 子Fragment页面；
2.从A1子Fragment页面中，通过底部导航tab进入主 D Fragment页面，会调用主A页面中的onSupportVisible方法；
3.从主D Fragment页面中，通过底部导航tab进入主 A Fragment页面时，未调用主A页面中的onSupportVisible方法.

**Comment by HulkHou** [comment]
补充几点：
1.主A Fragment，其实是两个Fragment嵌套的，因为有懒加载的存在，外层继承是BaseFragment，嵌套的继承SupportFragment；
2.当“从主D Fragment页面中，通过底部导航tab进入主 A Fragment页面时，未调用主A页面中的onSupportVisible方法.”其实调用了外层的onSupportVisible方法，没有调用嵌套的该方法；

**Comment by YoKeyword** [comment]
我在知乎Demo中 模拟了你的场景，发现`onSupportVisible()`调用正常，你的场景和知乎Demo有不同之处吗？

**Comment by HulkHou** [comment]
首先感谢您的回复！
再次说明一下：
1.已经升级到了v1.18
2.我就是仿造知乎demo来做的

以下是我的代码结构：
MainActivity 
MainActivity extends SupportActivity
loadMultipleRootFragment(R.id.fl_container, FIRST,
                    mFragments[FIRST], mFragments[SECOND], mFragments[THIRD], mFragments[FOURTH], mFragments[FIVE]);
----------------------------------
mFragments[FIRST]就是之前所谓的主A Fragment （HomePageFragment ）
HomePageFragment extends BaseMainFragment
@Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        super.onLazyInitView(savedInstanceState);

        if (findChildFragment(HomeFragment.class) == null) {
            loadRootFragment(R.id.fl_homepage_container, HomeFragment.newInstance());
        }
    }

----------------------------------
HomeFragment就是之前的所谓的嵌套的Fragment
HomeFragment extends SupportFragment

--------------------------------------------
//这段是我之前没有描述清楚的地方，so sorry
MessageFragment  是是嵌套在HomeFragment里面的Fragment

######################
Fragment调用流程是：
HomePageFragment  --->(懒加载)  HomeFragment  --->(Start) MessageFragment  --->(Tab切换)  ProfileHomeFragment--->(Tab切换) HomePageFragment   --->(懒加载) HomeFragment  


问题是：
ProfileHomeFragment--->(Tab切换) HomePageFragment   --->(懒加载) HomeFragment
未调用HomeFragment的onSupportVisible方法，只调用了HomePageFragment  的onSupportVisible方法！


感谢阅读！感恩！

**Comment by YoKeyword** [comment]
> MessageFragment 是是嵌套在HomeFragment里面的Fragment
> HomeFragment --->(Start) MessageFragment

上面的2个描述看起来矛盾，如果是`MessageFragment`和`HomeFragment`同级，那么就是和知乎Demo一样的栈结构，经测试 没有发现该问题

**Comment by HulkHou** [comment]
谢谢你的回复！我大概知道什么问题了！我的描述还是不够清晰！

MessageFragment和HomeFragment不是同级，MessageFragment跟HomePageFragment同级，MessageFragment里面还是嵌套着MessagePlatformFragment.

######################
Fragment调用流程是：
HomePageFragment --->(懒加载) HomeFragment --->(Start) MessageFragment ---> MessagePlatformFragment --->(Tab切换) ProfileHomeFragment--->(Tab切换) HomePageFragment --->(懒加载) HomeFragment
