### ISSUE TITLE
关于clearAccessibilityFocus()处报空指针的问题,很急!

### ISSUE THREAD

**Issue by bbiii** [YoKeyword/Fragmentation#651]
现在的情况是主界面是HomeFragment,loadRootView加载了3个根据底部栏切换的fragment.在里面的第一个fragment1(主页)里面打开fragmen2,再打开fragmen3.在fragment3里面接受预定功能,成功后跳转到一个fragment4(预定成功界面),在fragment4里面延迟2s执行操作: popTo(HomeFragment.class,false);退回主页.

这样的逻辑流程有个很严重的问题,虽然大部分情况没问题,但偶尔会出现致命的空指针,是clearAccessibilityFocus()这个地方的问题.

搜索了issues发现有相关的问题但是都没有给出具体的解决方案,请问怎么样能避免崩溃?

fragmentation版本:'me.yokeyword:fragmentation:1.1.6'
其他:Support相关: 'com.android.support:appcompat-v7:25.1.1'
'com.android.support:design:25.1.1'

**Comment by YoKeyword** [comment]
猜测是栈视图层级有问题，可以关注下栈视图结构是否科学

> loadRootView加载了3个根据底部栏切换的fragment

听描述，感觉更适合使用`loadMultipleRootFragment`， 另外使用时注意[这个事项](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager)

此外建议在Demo中寻找和自己场景类似的设计，参考下Demo写法

**Comment by bbiii** [comment]
我描述的不严谨,我用的确实是loadMutipleRootFragment : loadMultipleRootFragment(R.id.fl_tab_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD]);

我主体框架就是按您微信demo写的

**Comment by YoKeyword** [comment]
这个异常的原因可以确定是栈视图顺序是异常的， 最好能复现，然后排查原因解决

**Comment by bbiii** [comment]
最近又排查了这个问题 ,定位到了 fragment3里,在预定成功后 我是调用了startWithPop(ReserveSucessFragment.newInstance());跳转到预定成功界面;
而且这个问题是和App后台内存回收相关,现在可以复现,打开不保留活动.进行一次预定的流程,第一次没问题,然后Home键返回桌面,再打开App,第二次就会在上面说的startWithPop的地方报unFocus(android.view.View)的空指针;
因为实在不知道怎么处理,目前只能再startWithPop的地方捕获了异常,然后不跳转到预定成功fragment,直接pop(),但这样也会出问题,pop到上一层fragment2,fragment2只有界面,所有点击没反应,点击返回会退出app....
总之现在完全没头绪啊,应该是内存回收的问题,但是大概看了一下demo,没找到是怎么处理这个问题的

**Comment by YoKeyword** [comment]
打开不保留活动 再次回到App后，时刻观察栈视图是否符合预期

另外务必注意[该事项](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager)

可以贴下异常前的栈视图，并说明

**Comment by YoKeyword** [comment]
建议更新到v1.2.0，新增队列机制，彻底解决Fragment多点触控、极端事务问题，提高稳定性，见[更新日志](https://github.com/YoKeyword/Fragmentation/wiki)
