### ISSUE TITLE
fragment中点击按钮弹出DialogFragment，然后在DialogFragment使用startActivityForResult()启动Activity回执有问题

### ISSUE THREAD

**Issue by xiaocuicui1937** [YoKeyword/Fragmentation#652]
你好，我最近碰到一个问题，fragment（是框架中framgent）中点击按钮弹出DialogFragment，然后在DialogFragment使用startActivityForResult()启动Activity扫二维码，通过调用setResult(Activity.RESULT_OK,Intetent);Activity.finish();,fragment中重写onActivityForResult()并没有进行回调，DialogFragment中重写onActivityForResult()也没有进行回调；然后通过getActivity().startActivityForResult()启动Activity进行扫码，在包含有fragment的activity的onActivityForReuslt（）方法进行回调，能够拿到数据，请大佬在百忙中解惑

**Comment by YoKeyword** [comment]
谁（Fragment／Activity）`startActivityForResult(Activity)`， 回调谁的`onActivityForResult()`
