### ISSUE TITLE
使用ViewPager的问题

### ISSUE THREAD

**Issue by zhaoxuyan** [YoKeyword/Fragmentation#655]
<img width="263" alt="qq20171127-213906 2x" src="https://user-images.githubusercontent.com/29044917/33269381-69e327f4-d3bb-11e7-9894-c906b29654d2.png">
我换成这种布局过后，点击无反应。
栈中的情况如下：
<img width="293" alt="qq20171127-214304 2x" src="https://user-images.githubusercontent.com/29044917/33269517-f78c733a-d3bb-11e7-947e-0bd1f9a0f3a6.png">
DetialFragment存在且多个，（因为点击多次）但是视图却没有变化。
此时再点击另一个ViewPager, 正常情况应该显示More，但是变成了空白。
<img width="271" alt="qq20171127-215912 2x" src="https://user-images.githubusercontent.com/29044917/33270275-6b7aab84-d3be-11e7-8e33-4e3602ad1bef.png">

**Comment by YoKeyword** [comment]
> 记住一个原则： 避免在未加入回退栈的层级内去start()其它Fragment， 比如ViewPager、loadMultiRootFragment()、FragmentTabHost内部的Fragment不可以直接start，这种情况下其内的栈应该保持干净，如果想启动其它Fragment，应该由它们的父Fragment或子Fragment去start

详情看wiki [ViewPager、loadMultiRootFragment注意事项](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager)

**Comment by zhaoxuyan** [comment]
您好，我根据你的提示解决了上述问题。但是又出现了新的问题。
我把结果更改成了这样（把DetailFragment移到了上一级Fragment）：
<img width="216" alt="11" src="https://user-images.githubusercontent.com/29044917/33305595-d5eee74c-d449-11e7-927d-fb3e14e6e619.png">
在FirstPagerFragment里通过以下代码实现：
<img width="785" alt="22" src="https://user-images.githubusercontent.com/29044917/33305641-f9b2d8a0-d449-11e7-8179-b4073b716b48.png">
成功进入了DetailFragment，但是在按返回按钮时却出现了新的bug,直接退出了程序:
<img width="264" alt="33" src="https://user-images.githubusercontent.com/29044917/33305674-16d64f02-d44a-11e7-966f-53171c3b2f36.png">

**Comment by YoKeyword** [comment]
看起来是BACK事件设置问题，参考下Demo

另外 [BACK键机制](https://github.com/YoKeyword/Fragmentation/wiki/6.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-Back%E9%94%AE%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E6%9C%BA%E5%88%B6)

> 多看wiki 和demo
