### ISSUE TITLE
多个fragment  在activity监听返回按钮，如果是不是第一个fragment则pop  ，如果是第一个则finishActivity。。会有fragment退出不及时问题导致getTopFragment永远获取不到第一个fragment

### ISSUE THREAD

**Issue by w525721508** [YoKeyword/Fragmentation#656]
多个fragment  在activity监听返回按钮，如果是不是第一个fragment则pop  ，如果是第一个则finishActivity。。会有fragment退出不及时问题导致getTopFragment永远获取不到第一个fragment

**Comment by LonelyMushroom** [comment]
1. 默认，`fragment` 数目大于1，关闭 `fragment` ，否则关闭 `activity`
2. 退出时有动画的影响，第一时间 `getTopFragment` 可能不准确的，退出时 延迟一个动画时间再 `getTopFragment` 是准确的
