### ISSUE TITLE
能否添加对DialogFragment的支持

### ISSUE THREAD

**Issue by github-tongchen** [YoKeyword/Fragmentation#659]
Google 现在不是推荐用DialogFragment取代Dialog吗？不知道这里能不能也支持下DialogFragment。

**Comment by YoKeyword** [comment]
可以通过 实现接口 ＋ 委托 实现任意自己的Fragment

可以参考Demo的[MySupportFragment](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_flow/base/MySupportFragment.java)
