### ISSUE TITLE
关于知乎demo的bottombar，根据情况自定义显示或隐藏。

### ISSUE THREAD

**Issue by yanweidtc** [YoKeyword/Fragmentation#66]
比如我从FirstPageFragment 跳到 DetailFragment，不希望底部导航栏显示。

是否只有采用你的wechat-demo去写？写一个MainFragment?

**Comment by YoKeyword** [comment]
如果你希望每个主Fragment跳转后的Fragment都不显示底部导航栏，那就应该考虑用wechat-demo的栈设计； 如果只是个别的，那你可以给BottomBar添加对应的show/hide方法，通过EventBus控制其显示和隐藏的状态

**Comment by yanweidtc** [comment]
恩，我准备换成wecha-demo的设计。 我看到你zhihu-demo的Mainactivity似乎有一段 设定bottombar的显示和隐藏，但好像没有实现。是不是准备下一个迭代增加这个功能？

**Comment by YoKeyword** [comment]
wecha-demo的设计实现更简单，栈结构更清晰，用这种开发难度简单很多。
有显示和隐藏的方法，后续可能会增加这个交互～

**Comment by yanweidtc** [comment]
恩恩，谢谢你的及时回应。希望以后能多多交流，关了issue了。
