### ISSUE TITLE
如何通过代码实现切换tab？

### ISSUE THREAD

**Issue by cnsms** [YoKeyword/Fragmentation#662]
WechatSecondTabFragment中TabLayout，本来在第一个mTab，我想实现点击里面的内容，然后跳转到第二个mTab界面。能实现吗？

**Comment by LonelyMushroom** [comment]
可以通过eventbus实现

**Comment by YoKeyword** [comment]
或者父Fragment提供切换方法`switchTab()`，`((Parent)getParentFragment()).switchTab()`

**Comment by cnsms** [comment]
好的，谢谢

**Comment by cnsms** [comment]
这个方法怎样？
public static void goSecond(boolean one){
        TabLayout.Tab tab = mTab.getTabAt(one?1:0);
        if (tab != null) {
            tab.select();
        }

**Comment by YoKeyword** [comment]
不建议使用`static`去操作， 建议通过 `getParentFragment()`找到父Fragment引用再去执行其方法，或者EventBus

**Comment by cnsms** [comment]
恩，我认为也是，但是试了半天都不行，父Fragment弄不了， 不会了……

**Comment by YoKeyword** [comment]
切换Tab的代码是：  `viewPager.setCurrentItem(index);`

**Comment by cnsms** [comment]
恩
