### ISSUE TITLE
关于FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by Gundam0079** [YoKeyword/Fragmentation#663]
用的是最新的1.1.8

项目是这样实现的  这个Activity  上面有一个HomeFragment
中间逻辑是这样的  用URI打开某个fragment  比如  app://HomeFragment/Afragment/Bfragment 按照这个顺序打开fragment放入栈中  这个URI用Intent启动 
Activity 是 singleTask模式   HomeFragment用FLAG_PAGE_CLEAR_TOP 启动 保证这两个类是不用从新new的

执行代码顺序
Activity resume 执行 handler.post HomeFragment FLAG_PAGE_CLEAR_TOP
                           然后再handler.post 打开Afragment Bfragment
如果Activity 已经存在 会走Activity onNewIntent 然后会post到resume中去执行
这会报这个FragmentManager is already executing transactions 是log里面报的 报在Activity resume这行

看到之前的issue说 不能再fragment生命周期内执行pop操作 
FLAG_PAGE_CLEAR_TOP 会执行pop 所以后续打开Afragment Bfragment 都post执行还是报了这个错

百思不得解  是不是可以确认这个错确定报在 fragment生命周期内执行pop操作？ 跟Activity resume 有什么关系？

**Comment by YoKeyword** [comment]
你的描述没太理解， 贴下代码吧

`FragmentManager is already executing transactions` 这个异常一般发生在生命周期的地方调用了`fm.executePendingTransactions()`

**Comment by Gundam0079** [comment]
是fragment生命周期中不能调用fm.executePendingTransactions()？
Activity是可以调用的吗？

**Comment by YoKeyword** [comment]
是的，这个机制是25.3.0+ 新引入的，可以看下源码里的`FragmentManager`的`mExecutingActions`字段
