### ISSUE TITLE
单Activity情况下,其中一个Fragment页面必须横屏显示,如何才能实现

### ISSUE THREAD

**Issue by wxyass** [YoKeyword/Fragmentation#664]
情况是: 在单Activity中有多个Fragment页面, 其中有一个Fragment默认要横屏显示的, 使用Fragmentation库应该如何处理?

**Comment by sunshu** [comment]
getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
