### ISSUE TITLE
还是界面空白问题

### ISSUE THREAD

**Issue by ImHone** [YoKeyword/Fragmentation#667]
![p](https://user-images.githubusercontent.com/17943065/33694008-cbc986a8-db30-11e7-89cf-1bea9bc5fc5b.png)
流程就是这个样子，我查看了之前的Issues，得知不要从ChildFragment直接start新的fragment，但我是从MainFragment中start的，DetailFragment还是有一定几率出现空白，其他界面均无此情况

**Comment by YoKeyword** [comment]
嗯，栈视图没问题的

是否可以稳定复现呢？    先使用[EventBusActivityScope](https://github.com/YoKeyword/Fragmentation/tree/master/eventbus_activity_scope)代替下EventBus试下

另外其他页面无此情况，可以检查下DetailFragment页面是否有特殊的布局，可以替换成简单的布局排查下

**Comment by Ryan2Archibald** [comment]
@uHone 你这个bug解决了么，我现在从MainFragment 调用 start（）启动任意一个fragment，都有概率出现问题，如果设置了windowIsTranslucent为true则显示桌面，否则就是黑屏了。就像是fragment加载了，也加入回退栈里面了，但就是无法显示出来

**Comment by Ryan2Archibald** [comment]
@YoKeyword 麻烦看一下，出现这个问题的时候，应用返回桌面，再打开应用却又能显示栈顶的fragment了
