### ISSUE TITLE
仿微信的demo为啥MainActivity在放一个MainFragment？

### ISSUE THREAD

**Issue by Destiny01** [YoKeyword/Fragmentation#668]
仿微信的demo为啥MainActivity在放一个MainFragment？为啥不直接在MainActivit直接加载呢？     SupportFragment firstFragment = findChildFragment(WechatFirstTabFragment.class);
        if (firstFragment == null) {
            mFragments[FIRST] = WechatFirstTabFragment.newInstance();
            mFragments[SECOND] = WechatSecondTabFragment.newInstance();
            mFragments[THIRD] = WechatThirdTabFragment.newInstance();

            loadMultipleRootFragment(R.id.fl_tab_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD]);
        } else {
            // 这里库已经做了Fragment恢复,所有不需要额外的处理了, 不会出现重叠问题

            // 这里我们需要拿到mFragments的引用
            mFragments[FIRST] = firstFragment;
            mFragments[SECOND] = findChildFragment(WechatSecondTabFragment.class);
            mFragments[THIRD] = findChildFragment(WechatThirdTabFragment.class);
        }

**Comment by YoKeyword** [comment]
阅读[wiki:同级未加入回退栈的Fragments的栈视图处理](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager)
