### ISSUE TITLE
Fragment animation

### ISSUE THREAD

**Issue by dvasea1** [YoKeyword/Fragmentation#670]
you can put animation for fragment, but if i want to open fragment from bottom to top, like popup, i don't want pervious fragment to animate horizontally, how can i do that? THX

**Comment by YoKeyword** [comment]
Hi,  if you want to put animation for a specified Fragment:
````java
 extraTransaction()
                .setCustomAnimations(R.anim.target_enter, 0, 0, R.anim.target_exit)
                .start(targetFragment);
````


If you want to put animation for all Fragment:
````java
Activity:
    @Override
    public FragmentAnimator onCreateFragmentAnimator() {
        FragmentAnimator fragmentAnimator = new FragmentAnimator();
        fragmentAnimator.setEnter(R.anim.enter);
        fragmentAnimator.setPopExit(R.anim.pop_exit);
        fragmentAnimator.setPopEnter(R.anim.pop_enter);
        fragmentAnimator.setExit(R.anim.exit);
        return fragmentAnimator;
    }
````

**Comment by dvasea1** [comment]
YoKeyword thx for your response. your response was what i want to do. GOOD.THX

**Comment by Widiyanto** [comment]
How use in Casting?
extraTransaction()
                .setCustomAnimations(R.anim.anim_left_to_right, 0, 0, R.anim.anim_right_to_left)
                .((SupportFragment) getParentFragment()).start(HAddLocationFragment.newInstance());
