### ISSUE TITLE
Fragment Color

### ISSUE THREAD

**Issue by dvasea1** [YoKeyword/Fragmentation#671]
I do "start(FragmentTest.newInstance())" why my fragment has white color background, i want transparent color, how i can do that? thx

**Comment by YoKeyword** [comment]
You can set attribute for FragmentTest's root layout:
````xml
android: background = "@ android: color/transparent"
````

If you also want to see the previous Fragment:
````java
extraTransaction()
                .startDontHideSelf(FragmentTest.newInstance());
````

**Comment by dvasea1** [comment]
Cool. thx
