### ISSUE TITLE
EventBus 回调问题

### ISSUE THREAD

**Issue by lkliu** [YoKeyword/Fragmentation#674]
首先我创建一个AActivity +多个fragment（A模块） ，这个时候EventBus发消息是能收到回调的。然后我在某一个fragment 里面启动另外一个BActivity+fragment（B模块） ，在同一进程，这个时候，我从B的fragment 里面EventBus post一个消息，在A的Activity 或者fragment里面接收,收取不到这个回调。日志打印No subscribers registered for event class  但是我在A模块里面是有注册的 postSticky(event)也试过了还是不行 ，请问下是什么原因呢？

**Comment by LonelyMushroom** [comment]
你用的是这个么？如果是这个的话那么EventBus的作用域只在一个AC的里面。
```
compile 'me.yokeyword:eventbus-activity-scope:1.1.0'
compile 'org.greenrobot:eventbus:{version}'
```

**Comment by lkliu** [comment]
是的，不要用这个就行了吗？

**Comment by lkliu** [comment]
谢谢解答 可以了 换成普通的EventBus post就行了
