### ISSUE TITLE
关闭转场动画

### ISSUE THREAD

**Issue by LittleWaver** [YoKeyword/Fragmentation#676]
fragmentation的版本为：0.10.1
需求：
FatherFragment（继承自SupportFragment）跳转至SonFragment（继承自SupportFragment）时，FatherFragment可见[通过设置SonFragment的getPreFragment().getView().setVisibility(View.VISIBLE)]，SonFragment的背景为透明。
问题：
FatherFragment跳转至SonFragment时，FatherFragment显示布局会往左偏移一点又回来占据屏幕，SonFragment pop的时候FatherFragment同样会出现此现象。
请教：
请问，如何实现FatherFragment和SonFragment相互跳转时不觉得它们是两个界面，也就是如何能够关闭FatherFragment的这个跳转动画（试过其它issue中的重写onCreateFragmentAnimator()的方法，但是无效）？

**Comment by YoKeyword** [comment]
在1.0+的版本中，有：
````java
extraTransaction(
).setCustomAnimations() // 自定义转场之间动画
.startDontHideSelf()  // 启动目标Fragment的同时不隐藏自身
````

0.10.1的话，我猜测你只是偶尔需要这种场景，可以直接操作FragmentManager去加载sonFragment
````java
fm.add(sonFragment)...
````

另外，复写**FatherFragment**的`onCreateFragmentAnimator()`设置为无动画应该是有效的，只是一直让前一个Fragment保持可见状态在0.10.X 是没有现成方法的

**Comment by LittleWaver** [comment]
好的，谢谢(⊙o⊙)…
