### ISSUE TITLE
点击进入然后马上点击回退键闪退

### ISSUE THREAD

**Issue by VankaIn** [YoKeyword/Fragmentation#677]
具体场景：
打开 fragment，立马按回退键，崩溃。
原因：在 onEnterAnimationEnd 初始化一些 view，防止 fragment 转场动画卡顿。但是当点击回退键fragment 结束之后 onEnterAnimationEnd 里面的函数还是会运行，导致 view 报空指针错误

**Comment by VankaIn** [comment]
现在解决就是，在 baseFragment 里面加一个标志位isAnimateFinish = false，当做完onEnterAnimationEnd，这个标志为isAnimateFinish = true, 然后在回退栈时候判断，基本能解决以上问题，但是缺陷就是做转场过程的时候不能回退，希望楼主能给出更好的方案

**Comment by YoKeyword** [comment]
`onEnterAnimationEnd`里的代码贴一下， 因为内部是post，所以理论上是不会view为空的

一种原因是`onEnterAnimationEnd`里有异步操作，然后回调里操作了View导致崩溃

**Comment by VankaIn** [comment]
![image.png](http://upload-images.jianshu.io/upload_images/2223304-b182d038a6225b1f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

你好，以上是具体报错和代码截图。
我这边已经定位到问题，原因是使用 Bufferknife 的时候在 ```onDestroyView()``` 上使用了 ```unbinder.unbind()```导致的，具体解决方案还需要探究，也希望大佬能指导一下

**Comment by LonelyMushroom** [comment]
```
    Handler handler = new Handler(Looper.myLooper());

    @Override
    public void onEnterAnimationEnd(Bundle savedInstanceState) {
        super.onEnterAnimationEnd(savedInstanceState);
        // 我是这样测试的
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                initDataToView();
            }
        },3000);
        // 你可以这样写
        handler.post(new Runnable() {
            @Override
            public void run() {
                initDataToView();
            }
        });
    }

    private void initDataToView(){
        toolbar.setVisibility(View.GONE);
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        handler.removeCallbacksAndMessages(null);
        handler = null;
    }

```

**Comment by YoKeyword** [comment]
ButterKnife的`Unbinder.unbind()`里，是强制把@BindView的 View置为`null`，所以在出栈情况下(先调用了`onDestroyView()`)，再回调`onEnterAnimEnd()`导致了空指针

已经发布 v1.1.10，兼容了ButterKnife的`Unbinder.unbind()`

**Comment by VankaIn** [comment]
666， 效率真的是高
