### ISSUE TITLE
更改系统语言后app会闪退

### ISSUE THREAD

**Issue by yangxiaoge** [YoKeyword/Fragmentation#68]
Unable to start activity ComponentInfo{com.ztesoft.zsmart.datamall.app.mpt/com.ztesoft.zsmart.datamall.app.ui.MainActivity}: java.lang.IllegalStateException: Fragment already added: HomeContainer{e1e91d2 #0 id=0x7f0d008b com.ztesoft.zsmart.datamall.app.ui.fragment.home.HomeContainer}

求大神解救

**Comment by YoKeyword** [comment]
看异常应该是 加载了一个已经被加载的Fragment 
更换语言会引起页面重启的，你检查下是否没有判断saveInstanceState
