### ISSUE TITLE
swipebackfragment没有反应.但是swipebackactivity有反应

### ISSUE THREAD

**Issue by colder112** [YoKeyword/Fragmentation#681]
自己按照你的demo写了个例子没啥问题.fragment滑动出栈正常,有反应的...我在实际项目中使用的话,fragment滑动没反应...我用的是最新版的1.1.9

**Comment by colder112** [comment]
你看你需要那部分的代码,我贴出来给你瞧瞧...

**Comment by YoKeyword** [comment]
建议再看下使用方法，仔细和Demo再比较下

**Comment by colder112** [comment]
搞定了...是我忘记使用attachToSwipeBack(view)....尴尬尴尬......
