### ISSUE TITLE
调用popTo卡死bug

### ISSUE THREAD

**Issue by kartyjoin** [YoKeyword/Fragmentation#682]
调用popTo方法卡死，Fragment内操作无反应，但是不是ANR，点击回退键onBackPressed能触发关闭activity

做了compileSdkVersion 25->26   buildToolsVersion 25->26.0.1   supportLibrary 25->26.0.1
googleLibrary 10.2.0->11.6.2
fragmentation版本是1.1.9
造成这个原因只有这些变化

**Comment by YoKeyword** [comment]
触摸无反应的`popTo()`的那块代码发下，看描述应该是防抖动机制引起的

**Comment by kartyjoin** [comment]
popTo(MainRootFragment.class, false);
只有这些，在onClick内
关系是 MainRootFragment->B->CurrentFragment(onClick)

**Comment by YoKeyword** [comment]
support-v4版本号提供下，看起来场景非常简单

**Comment by kartyjoin** [comment]
应该是26.0.1，supportLibrary 的版本都统一了

**Comment by kartyjoin** [comment]
试过了，4个用到popTo的地方都是这个情况，A->B这种的还好说，可以用finish替代，A->B->C这种的就有些麻烦了，替代可能用事件总线来发消息。
这个情况是升级google的gms库和相关的compileSdk 26 对应升级 buildTools 和 supportLibrary引发的

还需要我提供什么信息吗？用的场景都比较简单，也没太多的操作

**Comment by YoKeyword** [comment]
v26.0.1经过测试，无法复现

测试分支：[test_2601](https://github.com/YoKeyword/Fragmentation/tree/test_2601)
测试Demo包：[这里](https://github.com/YoKeyword/Fragmentation/blob/test_2601/demo-debug-2601.apk)

你可以在测试分支的环境测试下，  另外你可以使用系统的`fragmentManager.popBackStack(tag, flag);`来测试下

**Comment by kartyjoin** [comment]
十分感谢，使用原生的popBackStack可以的，有空余时间时尽量能寻找的复现的配置，提供给你，工程比较大也不排除其他因素导致

**Comment by YoKeyword** [comment]
好的，我先关闭issue，有任何问题 可以继续在该issue下回复  :)
