### ISSUE TITLE
startForResultDontHideSelf 背景是黑的

### ISSUE THREAD

**Issue by kk00346** [YoKeyword/Fragmentation#683]
oldFragment 内调用， extraTransaction().setCustomAnimations(R.anim.v_fragment_enter, 0, 0, R.anim.v_fragment_exit)
.startForResultDontHideSelf(newFragment,1)

newFragment的背景已設定為透明，卻無法顯示oldFragment的畫面

但調用 startDontHideSelf 則可以顯示oldFragment的畫面

使用版本1.1.10

是使用錯誤嗎？
感謝解答

**Comment by YoKeyword** [comment]
@kk00346  听描述看起来是个BUG，明天我会测试并给回复 :)

**Comment by YoKeyword** [comment]
@kk00346 不好意思，前两天忘记了，确实是个BUG，下一版本会修复

**Comment by kk00346** [comment]
@YoKeyword 
非常感謝～
辛苦了  :)

**Comment by YoKeyword** [comment]
已修复，v1.2.0：见[更新日志](https://github.com/YoKeyword/Fragmentation/wiki)
