### ISSUE TITLE
IllegalStateException: Cannot perfom action after onSaveInstanceState

### ISSUE THREAD

**Issue by zubinxiong** [YoKeyword/Fragmentation#684]
<img width="1001" alt="qq20171218-183403 2x" src="https://user-images.githubusercontent.com/7650970/34101856-15f30804-e422-11e7-8c82-1118216b7eda.png">

- fragmentation : 1.1.7
- supportv4 : 22.2.1
- BottomBar 是 Demo 中的代码，MainActivity 是代码中合并了 MainFragment 的功能，布局类似 Demo 中的微信

- 当从 service 中启动 MainActivity 时出现上述问题，Nexus5 ，Android 6.0 不是必现

**Comment by zubinxiong** [comment]
- Demo 中 wechat 是 MainActivity -> MainFragment -> A/B/C Fragment 的形式
- 我在实际使用过程中 把 MainFragment 的功能合并到了 MainActivity 中，这样便是 MainActivity -> A/B/C Fragment ，通过调用是通过 showHideFragment 的方式执行，是不是因为这个原因，导致 fragment  启动时的状态异常

**Comment by YoKeyword** [comment]
看Log，在调用`showHideFragment()`方法时，Fragment的宿主MainActivity在 `after onSaveInstanceState`状态（即不可见状态，onPause -> onResume之间的状态）

调用时间保证在`onResume`之后即可
