### ISSUE TITLE
Fragment start

### ISSUE THREAD

**Issue by dvasea1** [YoKeyword/Fragmentation#685]
start(Fragment1) -> start(Fragment2)->  start(Fragment3) and hide Fragment1 and Fragment2,
how can i do that? if i do startWithPop(Fragment3) it hide Fragment2, but Fragment1 not.

**Comment by YoKeyword** [comment]
`start(Fragment1) -> startWithPop(Fragment2)-> startWithPop(Fragment3) `

or
`start(Fragment1) -> start(Fragment2)-> start(Fragment3)`
````java
// Fragment3.java：
@Override
public boolean onBackPressedSupport(){
       if (ok)  popTo(Fragment1.class , true)
}
````
