### ISSUE TITLE
如何在fragment 中拦截返回键点击事件

### ISSUE THREAD

**Issue by ming0101** [YoKeyword/Fragmentation#686]

**Comment by LittleWaver** [comment]
覆写SupportFragment的onBackPressedSupport()方法

**Comment by YoKeyword** [comment]
[Wiki: BACK事件](https://github.com/YoKeyword/Fragmentation/wiki/6.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-Back%E9%94%AE%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E6%9C%BA%E5%88%B6)
