### ISSUE TITLE
详情页的无限循环

### ISSUE THREAD

**Issue by LittleWaver** [YoKeyword/Fragmentation#687]
页面逻辑：
         点击商品RecyclerView中任意一个item，进入"商品详情页"。而"商品详情页"中又有一个推荐商品的RecyclerView，点击该RecyclerView中任意一个item时，也是进入相应的"商品详情页"。
问题描述：
        如果，频繁地点击当前"商品详情页"中推荐商品RecyclerView的任意一个item，那fragment栈不是会无限的扩张下去，请问这种情况下该如何优化，谢谢！

**Comment by LonelyMushroom** [comment]
```
Launch a fragment while poping self.
startWithPop
```

**Comment by luyun181** [comment]
能具体点吗？
