### ISSUE TITLE
start fragment not display

### ISSUE THREAD

**Issue by DanteAndroid** [YoKeyword/Fragmentation#689]
系统代码可以
```
        transaction.setCustomAnimations(android.R.anim.slide_in_left, android.R.anim.slide_out_right, android.R.anim.slide_in_left, android.R.anim.slide_out_right)
        transaction.hide(this)
        transaction.add(R.id.container, fragment, "aPost")
        transaction.addToBackStack(null)
        transaction.commit()
```
但是         `start(fragment)`不行。可以看到多了一个fragment，但是就是没有显示。生命周期也走了
![image](https://user-images.githubusercontent.com/10005563/34240334-295f7102-e648-11e7-9880-cdd7640519fd.png)

**Comment by DanteAndroid** [comment]
结构是：Drawer+fragments
先`loadMultipleRootFragment`，然后点击`drawer`的menu进行`showHideFragment`。
然后在该menu的fragment中点击item，进入详情fragment，也就是问题中start(fragment)的这个fragment

**Comment by LonelyMushroom** [comment]
[看看重点大字](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager)

**Comment by DanteAndroid** [comment]
大概可以理解。考不考虑添加方便TabFragment调用的方法呢~

**Comment by LonelyMushroom** [comment]
没办法确定每个调用的父类fg,太麻烦了,个个项目不同,所以每个人自己实现~

**Comment by DanteAndroid** [comment]
3q~

**Comment by DanteAndroid** [comment]
又发现一个问题。我start之后，点击返回，并没有回到之前的fragment。。而是退出程序了。主activity已集成supportActivity

**Comment by LonelyMushroom** [comment]
理论上不会有这种情况的,你把关键代码贴出来看看不

**Comment by DanteAndroid** [comment]
startFragment的代码：
![image](https://user-images.githubusercontent.com/10005563/34249121-7c9d9d1e-e673-11e7-845a-8d497911a1d6.png)
MainActivity:SupportActivity中的代码
![image](https://user-images.githubusercontent.com/10005563/34249133-8d0ab63c-e673-11e7-8f71-46697c67d50a.png)
![image](https://user-images.githubusercontent.com/10005563/34240334-295f7102-e648-11e7-9880-cdd7640519fd.png)

**Comment by YoKeyword** [comment]
@DanteAndroid  听描述是BACK事件的问题，可以参考[wiki－BACK机制](https://github.com/YoKeyword/Fragmentation/wiki/6.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-Back%E9%94%AE%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E6%9C%BA%E5%88%B6)

另外可以多看看Demo  :)

**Comment by DanteAndroid** [comment]
@YoKeyword 代码看起来没问题啊~
但是我用系统的transaction就没毛病
```
        transaction.setCustomAnimations(android.R.anim.slide_in_left, android.R.anim.slide_out_right, android.R.anim.slide_in_left, android.R.anim.slide_out_right)
        transaction.hide(this)
        transaction.add(R.id.container, fragment, "aPost")
        transaction.addToBackStack(null)
        transaction.commit()
```

**Comment by YoKeyword** [comment]
@DanteAndroid  直接退出，说明走了Activity的`finish()`，而不是Fragment的`pop`

可以通过查看栈视图， 断点调试下，很好排查的

**Comment by DanteAndroid** [comment]
![image](https://user-images.githubusercontent.com/10005563/34285046-8d7a4774-e711-11e7-9dd0-d25c02255b0c.png)
看样子rootFragment不在backStack里面，所以走了finish。
这我有点不太理解啊。从rootFragment（这里是一个TabFragment）中startFragment，逻辑上，点击返回应该返回到root才对啊。

**Comment by YoKeyword** [comment]
@DanteAndroid  从栈试图看，回退栈内只有CPictureFragment，所以走了 Activity的`finish()`

这个栈结构有问题， wiki上[同级未加入回退栈的Fragments](https://github.com/YoKeyword/Fragmentation/wiki/8.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-loadMultiRootFragment%E7%9A%84%E4%BD%BF%E7%94%A8-&-ViewPager#%E5%90%8C%E7%BA%A7%E6%9C%AA%E5%8A%A0%E5%85%A5%E5%9B%9E%E9%80%80%E6%A0%88%E7%9A%84fragments)里的加粗字 务必遵守

可以看下Demo的3个示例，找到和你需求类似的Demo，然后模拟其栈结构

**Comment by DanteAndroid** [comment]
@YoKeyword Demo里的flow布局（Google play），关于抽屉的点击事件我有个疑问：
```
              DiscoverFragment fragment = findFragment(DiscoverFragment.class);
                    if (fragment == null) {
                        popTo(HomeFragment.class, false, new Runnable() {
                            @Override
                            public void run() {
                                start(DiscoverFragment.newInstance());
                            }
                        });
                    } else {
                        // 如果已经在栈内,则以SingleTask模式start
                        start(fragment, SupportFragment.SINGLETASK);
                    }
```
就是这种写法。我现在抽屉里的menu每个item点击后都是TabsFragment，也就是说判断`findFragment(TabsFragment.class)`是否等于null无意义。（因为第一个menu就是TabsFragment）
那么该怎么写呢，有没有考虑过这种不同的menu，但是相同的fragment的情况

**Comment by YoKeyword** [comment]
可以自定义Tag:
````java
// 自定义Tag
extraTransaction().setTag("yourTag")
                    .start(fragment);

// 根据Tag寻找
f = SupportHelper.findFragment(fm, "yourTag")
````

如果可以确定TabsFragment的数量，建议通过继承，设置为不同的Fragment，可以降低繁琐度
 ````java
class OtherTabsFragment extends TabsFragment{}
````

抱歉，Wiki之前没有及时更新，现已更新:
````java
// 出栈targetFragment之上的所有Fragments
popTo(Class targetFragment, boolean includeTargetFragment);
````
