### ISSUE TITLE
startForResult 好像存在问题

### ISSUE THREAD

**Issue by CSnowStack** [YoKeyword/Fragmentation#69]
A activiy 启动 B activity ,B 里的 Fragment 1 startForResult  Fragment 2 ,Fragment 2 startForResult  Fragment 3, fragment 3 pop,Fragment 2 pop ,Fragment 1 原本的逻辑是收到 Fragment 2 返回的 Bundle 后
跳 Fragment4 ,结果是 收到 Fragment 2 pop 后,B activity 也退掉了 ,在 A activity startForResult  到 Fragment 4 了

**Comment by YoKeyword** [comment]
我刚跑了个Demo，没出现问题 ～
A -> B    B内的FG1 startForResult FG2 ，FG2 startForResult FG3  然后FG3 pop ,FG2 pop, FG1接收到后跳转FG4

不知道有没理解错，按这个流程可以正常跳转； 你确定下是最新版本，然后理下代码

还有建议过度复杂的组建通信逻辑用EventBus～

**Comment by CSnowStack** [comment]
我这边的问题.....
