### ISSUE TITLE
SwipeBackLayout设置成全屏有效 和 横向可滑动的布局产生了冲突

### ISSUE THREAD

**Issue by flztsj** [YoKeyword/Fragmentation#690]
SwipeBackLayout设置成全屏有效 和 横向可滑动的布局产生了冲突。

我的页面是开启了全屏可侧滑推出，并且页面里面有一个横向滑动的recyclerView，现在的问题就是横向滑动的recyclerView的触摸事件被SwipeBackLayout吃掉了，这个有办法解决吗？

**Comment by YoKeyword** [comment]
这种场景的滑动冲突需要自己解决， 另外如果可以的话，用边界滑动模式代替全屏
