### ISSUE TITLE
本身调用了Pop()但是在栈中还是存在的

### ISSUE THREAD

**Issue by Wade-Cai** [YoKeyword/Fragmentation#691]
本身调用了Pop()但是在栈中还是存在的，请问有办法完全弹出吗

**Comment by Wade-Cai** [comment]
刚才看了#665的issue，发现造成这个的原因是我先隐藏了rootFragment再弹栈导致的，如果我先弹栈再隐藏rootFragment就没有问题了，请问下大神造成这个问题的原因是什么

**Comment by YoKeyword** [comment]
建议先断点调试下，周末有空我模拟下你的场景看下

**Comment by YoKeyword** [comment]
@Wade-Cai  看描述好像栈结构有问题，栈视图贴一下，并描述流程
