### ISSUE TITLE
是否不能使用EventBus了？

### ISSUE THREAD

**Issue by stoneLee81** [YoKeyword/Fragmentation#692]
升级了您的最新版本，发现原来的
EventBus.getDefault().register(this); 报错，是否这个不能用了

**Comment by YoKeyword** [comment]
EventBus和Fragmentation是完全独立的， 建议排查下环境配置

**Comment by stoneLee81** [comment]
我之前旧的fragmentation用的eventbus是3.1.1的版本，升级到最新的fragmetation就报错了，但我减低eventbus版本到3.0.0就可以了

**Comment by stoneLee81** [comment]
是我搞错了
