### ISSUE TITLE
startActivity with options 滑动返回会黑屏

### ISSUE THREAD

**Issue by weiyf** [YoKeyword/Fragmentation#695]
startActivity with options 滑动返回会黑屏

**Comment by YoKeyword** [comment]
> Following information can help us to resolve the issue faster.
> * Library version
> * Support-v4 version
> * Logs
> * Screenshots

相关代码贴一下

**Comment by weiyf** [comment]
就是demo， 滑动退出那个Activity
``` java
Bundle options = ActivityOptionsCompat.makeSceneTransitionAnimation(MainActivity.this,
                            findViewById(R.id.fl_container), "transition_top_bar").toBundle();
                    startActivity(new Intent(MainActivity.this, SwipeBackSampleActivity.class), options);
```

**Comment by YoKeyword** [comment]
好像是Options配置问题，对Options不是很熟，可以查下

**Comment by ruanbaojun1105** [comment]
加了转场动画就会返回黑屏，转场动画依旧能正常，就是背景成黑屏了，这是返回库的问题大兄弟，SwipeBackLayout的背景成黑色了？我还没找到方法

**Comment by ruanbaojun1105** [comment]
@weiyf @YoKeyword 我刚看了源码，找到了解决方法：
onCreate 初始化的时候加入下面这句代码可让转场动画正常
getWindow().getDecorView().setBackgroundColor(Color.TRANSPARENT);
以为源码中把这个背景设置成了null当然成黑色背景了

**Comment by YoKeyword** [comment]
@weiyf  @ruanbaojun1105 研究了一下 `R.id.fl_container`这个View作为`makeSceneTransitionAnimation`的View在滑动时会看不到该View，换成nav_view或其他View 滑动返回时正常

点返回键会黑屏，如 @ruanbaojun1105 所说，需要把`DecorView`的background设置为透明即可解决，下一版本修复

**Comment by YoKeyword** [comment]
已修复 v1.2.7
