### ISSUE TITLE
界面卡顿

### ISSUE THREAD

**Issue by BlainPeng** [YoKeyword/Fragmentation#697]
我在onEnterAnimationEnd方法里面加载数据，在第一次打开一个Fragment时会有一点卡顿感，第二次以后却很流畅。不知道是怎么回事？我的耗时任务都是放在子线程中的。

**Comment by YoKeyword** [comment]
页面复杂的情况，`onCreateView()`加载会稍微耗时，导致可能会卡顿

优化方案是： 
1、尽可能多的把初始化逻辑放到 `onEnterAnimationEnd()`
2、采用竖直动画替代横向等动画，在视觉上会比较流畅
3、如果要求很高，复杂的View可以在 `onEnterAnimationEnd()`里动态创建

**Comment by BlainPeng** [comment]
恩。采用了竖直动画还没种卡顿的感觉了

**Comment by BlainPeng** [comment]
恩。采用竖直动画后没那种卡顿的感觉了。
