### ISSUE TITLE
swipebacklayout 设置全屏响应，触发太灵敏了，能降低灵敏度吗？ 现在非水平情况下很容易就触发了。

### ISSUE THREAD

**Issue by flztsj** [YoKeyword/Fragmentation#698]

**Comment by YoKeyword** [comment]
触发灵敏度是v4库的`ViewDragHelper`控制的，想更改的话，可能需要自己动手了，不是很建议全屏响应（全屏响应另外还可能存在 滑动冲突问题），可以边缘响应，或自定义范围响应

**Comment by flztsj** [comment]
[BetterViewDragHelper.zip](https://github.com/YoKeyword/Fragmentation/files/1654579/BetterViewDragHelper.zip)
把库内部使用的ViewDragHelper换成BetterViewDragHelper就可以解决这个问题，现在全屏侧滑太灵敏的问题基本ok，关键代码就是
![image](https://user-images.githubusercontent.com/5946178/35258202-d9c14250-0038-11e8-9b7e-8921b12bc4cf.png)

**Comment by flztsj** [comment]
@YoKeyword  可以看看 合适的话可以考虑合入到库里面去，源码是参考
![image](https://user-images.githubusercontent.com/5946178/35258256-21fd9b36-0039-11e8-9596-5f28907a335f.png)

**Comment by flztsj** [comment]
[BetterViewDragHelper.zip](https://github.com/YoKeyword/Fragmentation/files/1654750/BetterViewDragHelper.zip)

 请使用这个最新的，强烈建议导入库中
