### ISSUE TITLE
问个细节问题

### ISSUE THREAD

**Issue by yemade** [YoKeyword/Fragmentation#7]
1. AS 里有个 Monitors 可以监控内存使用情况。
2. ViewPager with 3个Fragment。
3. 无论使用 FragmentPagerAdapter 或是 FragmentStatePagerAdapter，每一次 swipe viewpager 后，内存消耗都会有 0.01 或 0.02 MB 的增长，持续增长。
4. setOffscreenPageLimit(2) 后就不会有这个情况。
5. 是 Viewpager populate 的过程中消耗了内存，还是 destoryItem 时释放的内存和 instantiateItem 是申请的内存不对等。
6. 我是没找到答案，也许你能帮我。

**Comment by YoKeyword** [comment]
@yemade  ViewPager默认缓存相邻的1个页面，你是3个Fragment，所以在使用FragmentPagerAdapter时，会有一个Fragment被销毁视图（即回调onDestoryView方法，是否销毁取决于你从第几个Fragment移动到第几个Fragment，比如从第2个移动到第3个，第1个Fragment就会被销毁视图），而当你移动回来时，会重新创建视图，所有内存会小幅度增长。

而如果你使用FragmentStatePagerAdapter，它会直接销毁Fragment实例，当你返回时，会重新创建该Fragment的实例，所以内存会相比FragmentPagerAdapter增长更多一点。

setOffscreenPageLimit(2)方法会让ViewPager缓存相邻的2个页面，这样不管你怎么切换Fragment都还在，不会调用销毁视图等生命周期，当然也不会有内存变化情况啦

这些增长的内存你不必担心，当下次GC时，会重新释放掉这些内存的，你可以手动GC试试哈 (除非你的Fragment使用中有内存泄漏)

**Comment by yemade** [comment]
@YoKeyword  明白了，destoryItem 不是及时释放内存，要等到 GC 才能看到效果。 谢谢啦！
