### ISSUE TITLE
onFragmentResult 会收到两次

### ISSUE THREAD

**Issue by CSnowStack** [YoKeyword/Fragmentation#70]
DetailFragment :

@Override
    public void onFragmentResult(int requestCode, int resultCode, Bundle data) {
        super.onFragmentResult(requestCode, resultCode, data);
        Log.e("-->>","收到了");
        if (requestCode == REQ_MODIFY_FRAGMENT && resultCode == RESULT_OK && data != null) {
            mTitle = data.getString(KEY_RESULT_TITLE);
            mToolbar.setTitle(mTitle);
            // 保存被改变的 title
            getArguments().putString(ARG_TITLE, mTitle);
            Toast.makeText(_mActivity, "修改标题成功!", Toast.LENGTH_SHORT).show();
        }
    }  

ModifyDetailFragment :

  mBtnModify.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Bundle bundle = new Bundle();
                bundle.putString(DetailFragment.KEY_RESULT_TITLE, mEtModiyTitle.getText().toString());
                setFramgentResult(RESULT_OK, bundle);
                Log.e("-->>","发射数据");
                Toast.makeText(_mActivity, "修改成功!", Toast.LENGTH_SHORT).show();
                pop();
            }
        });
        mBtnNext.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startForResult(ModifyDetailFragment.newInstance("标题"),100);
            }
        });

   @Override
    protected void onFragmentResult(int requestCode, int resultCode, Bundle data) {
        super.onFragmentResult(requestCode, resultCode, data);
        Log.e("-->>","ModifyDetailFragment  收到了");
        setFramgentResult(RESULT_OK, data);
        pop();
    }
DetailFragment 进入 ModifyDetailFragment 点 mBtnNext 进入 ModifyDetailFragment 1 ,ModifyDetailFragment 1 里面 点 mBtnModify  

打印结果:
08-29 09:17:45.674 14063-14063/me.yokeyword.sample E/-->>: 发射数据
08-29 09:17:45.994 14063-14063/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 09:17:46.314 14063-14063/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 09:17:46.634 14063-14063/me.yokeyword.sample E/-->>: 收到了

**Comment by YoKeyword** [comment]
@CSnowStack 按你的写法，在demo里写了下，只调用一次啊～  

目前result机制好像会在一个特殊场景下（应该不是这种正常的场景）会重复调用，目前result机制还不够完善，回头会优先重构这块～

**Comment by CSnowStack** [comment]
又试了下,刚开始调用一次,多试几次就会调用两次
08-29 10:53:48.730 14607-14607/me.yokeyword.sample E/-->>: 发射数据
08-29 10:53:49.050 14607-14607/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 10:53:49.370 14607-14607/me.yokeyword.sample E/-->>: 收到了
08-29 10:53:52.910 14607-14607/me.yokeyword.sample E/-->>: 发射数据
08-29 10:53:53.220 14607-14607/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 10:53:53.530 14607-14607/me.yokeyword.sample E/-->>: 收到了
08-29 10:53:59.720 14607-14607/me.yokeyword.sample E/-->>: 发射数据
08-29 10:54:00.040 14607-14607/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 10:54:00.350 14607-14607/me.yokeyword.sample E/-->>: 收到了
08-29 10:54:08.990 14607-14607/me.yokeyword.sample E/-->>: 发射数据
08-29 10:54:09.320 14607-14607/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 10:54:09.640 14607-14607/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 10:54:09.960 14607-14607/me.yokeyword.sample E/-->>: 收到了
08-29 10:54:38.710 14607-14607/me.yokeyword.sample E/-->>: 发射数据
08-29 10:54:39.020 14607-14607/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 10:54:39.340 14607-14607/me.yokeyword.sample E/-->>: 收到了
08-29 10:54:56.800 14607-14607/me.yokeyword.sample E/-->>: 发射数据
08-29 10:54:57.120 14607-14607/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了
08-29 10:54:57.460 14607-14607/me.yokeyword.sample E/-->>: ModifyDetailFragment  收到了

**Comment by YoKeyword** [comment]
额，我刚看了下重复点击，是一次啊～  😅
如果是你描述的那样，可能栈内已经不正常了～  加我QQ沟通吧QQ：328903522   :)
