### ISSUE TITLE
在子Fragment中如何重新加载数据

### ISSUE THREAD

**Issue by wxyass** [YoKeyword/Fragmentation#701]
我在MainFragment中添加了4个子Fragment (AFragment,BFragment,CFragment,DFragment),使用的是loadMultipleRootFragment(), 而4个子Fragment都会初始化数据  

现在的问题是 我想在切换这4个Fragment时(showHideFragment()),  让他们每次都重新加载数据,而不是显示刚刚加载的. 需要重写什么方法?

**Comment by LonelyMushroom** [comment]
>4个子Fragment都会初始化数据

 你是在onCreateView里面获取数据的么,如果你不想初始化获取数据你可以
```
    @Override
    public void onLazyInitView(@Nullable Bundle savedInstanceState) {
        // 不想初始化获取数据
        getData();
    }
    @Override
    public void onSupportVisible() {
        super.onSupportVisible();
         // 每次都重新加载数据
         getData();
    }
```

**Comment by YoKeyword** [comment]
如果想每次可见时加载数据：
````java
    @Override
    public void onSupportVisible() {
        super.onSupportVisible();
         // 每次都重新加载数据
         getData();
    }
````

如果想切换Tab时加载数据：
````java
    @Override
    public void onHiddenChanged(booelan hidden) {
        super.onHiddenChanged();
         if(!hidden){
               getData();
         }
    }
````

**Comment by zhenian** [comment]
`loadRootFragment(R.idmenu_frame, currentFragment, false, false);`

通过 `loadRootFragment` 切换 `currentFragment`时，当`currentFragment`不变，还是前一个时，并没有调用  `onSupportVisible()`

**Comment by YoKeyword** [comment]
@zhenian  如果是连续加载同一个Fragment的话，因为该Fragment已经被FragmentManager加载了，所以不会走任何生命周期

另外 v1.2.0 已放出，内部新增队列机制，提高了极端情况下的稳定性 🍺
