### ISSUE TITLE
手机屏幕锁屏的时候，调用startedWithPop  崩溃

### ISSUE THREAD

**Issue by programer-liang** [YoKeyword/Fragmentation#702]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference

debug 断点的时候提示是：onsaveInstance（）之后不能做这样的操作，大概意思是这样

**Comment by programer-liang** [comment]
大神看的出问题是什么原因导致的吗？

**Comment by YoKeyword** [comment]
在`onSaveInstanceState()`之后（即Activity宿主不可见时），默认不允许执行事务，`commit()`有`commitAllowingStateLoss()`可以绕过检查，`pop`没有类似绕过检查的API

一种解决方案是在执行`startWithPop()`时检查`isResume()`，如果是则执行，否则标记一下，延迟到下次`onResume()`回调时再执行

> 最近几天会放出v1.2.0，彻底解决`after onSaveInstanceState`问题，不再需要自己处理，可以关注下

**Comment by YoKeyword** [comment]
已放出v1.2.0， 彻底解决`after onSaveInstanceState`问题
