### ISSUE TITLE
栈显示和界面显示不一致的问题

### ISSUE THREAD

**Issue by VankaIn** [YoKeyword/Fragmentation#705]
版本：1.1.10
系统：android7.1.1
描述：使用代码 ```_mActivity.moveTaskToBack(true)``` 按返回键返回桌面，再打开 app，栈试图和实际界面不一致。具体重现已经发到大大的邮箱

**Comment by YoKeyword** [comment]
建议先更新到v1.2.0试试，内部新增队列机制，提高了极端情况下的稳定性，见[更新日志](https://github.com/YoKeyword/Fragmentation/wiki) 🍺

另外打开开发者模式->不保留活动，然后通过Home键测试下，如果栈视图顺序依然有问题，那么可能是操作栈 错误
