### ISSUE TITLE
在4.4.3上（更老的没试），侧滑返回（Activity），下面的Activity看不见，会直接看到桌面

### ISSUE THREAD

**Issue by LinusLi** [YoKeyword/Fragmentation#706]
如图，这个Activity下面还有Activity的，但是侧滑返回的时候看不见，看到的是桌面，完全滑完之后，下面的Activity会有动画再出现
![image](https://user-images.githubusercontent.com/562553/34431242-7942f5ca-eca8-11e7-9c45-2970ef58c591.png)

**Comment by YoKeyword** [comment]
参考 https://github.com/ikew0ng/SwipeBackLayout/issues/108
