### ISSUE TITLE
关于getFragmentManager().getFragments()问题

### ISSUE THREAD

**Issue by isqing** [YoKeyword/Fragmentation#708]
当我的MainFragment有4个fragmentA，fragmentB，fragmentC，fragmentD，当点击fragmentA中跳到新界面，打开多级页面，在fragmentA下子界面fragmentA-N中用getFragmentManager().getFragments()获取回退栈，为什么在回退栈中得不到fragmentA而是得到MainFragment，有什么办法得到fragmentA吗

**Comment by YoKeyword** [comment]
使用`getChildFragmentManager().getFragments()`可以获取到

另外建议打开栈视图悬浮球来观察栈内Fragment情况： (v1.2.0开始，默认会显示悬浮球)
````java
 Fragmentation.builder()
                // 设置 栈视图 模式为 （默认）悬浮球模式   SHAKE: 摇一摇唤出  NONE：隐藏， 仅在Debug环境生效
                .stackViewMode(Fragmentation.BUBBLE)
                .debug(true) // 实际场景建议.debug(BuildConfig.DEBUG)
                .install();
````
