### ISSUE TITLE
出现了这个异常，很少出现，今天出现了2次。不知道怎么找。

### ISSUE THREAD

**Issue by dyfan** [YoKeyword/Fragmentation#71]
![image](https://cloud.githubusercontent.com/assets/15817271/18122919/356423f2-6f9e-11e6-95c4-94b1a8775430.png)

**Comment by dyfan** [comment]
在切换tab的时候出现了这个异常，用的是微信那种懒加载的方式

**Comment by YoKeyword** [comment]
@dyfan 
> 如果你遇到Fragment的mNextAnim空指针的异常（通常是在你的Fragment被重启的情况下），那么你首先需要检查是否操作的Fragment是否为null；其次在你的Fragment转场动画还没结束时，你是否就执行了其他事务等方法；解决思路就是延迟一个动画时间再执行事务，或者临时将该Fragment设为无动画

**Comment by YoKeyword** [comment]
根据你的描述，应该是在页面重启后导致的，可以将页面设置可旋转横竖屏来快速复现这个异常

**Comment by dyfan** [comment]
没有做其他事务操作吧，我现在刚刚搭完框架，今天做应用的时候发现的这个问题。fragment应该不会为null，我在mainactivity oncreat中做了savedInstanceState的判断。不理解你说的页面设置可旋转横竖屏是什么意思。这个bug只出现了2次 - - 。
还有就是我在fragment的启动fragment的时候，第二个fragment进入的时候会闪一下，而且在第二个fragment进入的时候第一个页面的控件可以出发点击事件。

**Comment by YoKeyword** [comment]
多看下demo，有些细节wiki是可能没说明，demo里都有相应的处理

**Comment by YoKeyword** [comment]
@dyfan 页面重启就是 旋转屏幕等系统配置变化，或者APP在后台内存不足被杀死导致的 恢复情况，可以参见README里的2篇文章，最好学习该库的方式还是该库DEMO~  可以看下DEMO里如果处理的~
