### ISSUE TITLE
首页四个页面错乱

### ISSUE THREAD

**Issue by isqing** [YoKeyword/Fragmentation#710]
mainFragment四个子fragmentA,B,C,D，分别对应底部bottombar  b1,b2,b3,b4,会出现点b4对应B，这种错乱的情况

**Comment by YoKeyword** [comment]
检查下代码，是否引用指向错误

另外可以参考Demo写法

**Comment by isqing** [comment]
这是我的代码： if (savedInstanceState == null) {
            homeFragment = HomeFragment.newInstance(HtmlUrl.homeUrl, true);
            mFragments[FIRST] = homeFragment;
            treatmentFragment = TreatmentFragment.newInstance(HtmlUrl.treatUrl, true);
            mFragments[SECOND] = treatmentFragment;
            healthFragment = HealthFragment.newInstance(HtmlUrl.healthUrl, true)；
            mFragments[THIRD] = healthFragment;
            personFragment = PersonFragment.newInstance(HtmlUrl.personUrl, false);
            mFragments[FOUR] = personFragment;

            loadMultipleRootFragment(R.id.fl_tab_container, FIRST,
                    mFragments[FIRST],
                    mFragments[SECOND],
                    mFragments[THIRD],
                    mFragments[FOUR]);
        } else {
            mFragments[FIRST] = findChildFragment(HomeFragment.class);
            mFragments[SECOND] = findChildFragment(TreatmentFragment.class);
            mFragments[THIRD] = findChildFragment(HealthFragment.class);
            mFragments[FOUR] = findChildFragment(PersonFragment.class);
        }
在点击事件 mBottomBar.setOnTabSelectedListener中 showHideFragment(mFragments[position], mFragments[prePosition]);和你之前的demo版本用的是一样的写法

这种错乱是偶然的，50次大约出现个一次这种情况

**Comment by YoKeyword** [comment]
`showHideFragment()`内部源码是单纯的 `show().hide()` 代码在[这里](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java#L376)，没有做其他的事

最好可以复现排查下原因

> 另外建议先尝试更新到v1.2.0试试，1.2.0新增队列机制，极端情况下更稳定
