### ISSUE TITLE
标签切换时 onpause方法遇到的问题

### ISSUE THREAD

**Issue by wxyass** [YoKeyword/Fragmentation#712]
宿主Fragment 有4个子Fragment标签 , 在每次切换时需要保存前一个Fragment的数据  , 使用onHiddenChanged方法保存前一个标签页的数据,(4个标签页随意切换,问题在于最后一个标签上)

最后一个子Fragment数据,有什么方法在用户输填写完数据 保存呢?

**Comment by LonelyMushroom** [comment]
可以全部保存在activity或者父层的fragment里面么?

**Comment by YoKeyword** [comment]
@wxyass 没明白你的意思，你的保存数据是指怎么保存呢？

输入完数据的时机／回调，我相信你是知道的，直接在回调里保存数据不就可以了？

如果是状态的保存和恢复，那么全局变量保存，然后在`onSaveInstanceState()`里保存即可
