### ISSUE TITLE
侧滑的 bug

### ISSUE THREAD

**Issue by VankaIn** [YoKeyword/Fragmentation#714]
版本：1.2.0
描述：栈结构是 OneFragment - TwoFragment - TwoFragment 。这时候做侧滑，理论结果应该是：OneFragment - TwoFragment。 但实际结果是 OneFragment。还有，按返回键是可以得到正确结果的（ OneFragment - TwoFragment）

**Comment by YoKeyword** [comment]
@VankaIn  Oh!  v1.2.0的BUG，内部由`pop()`换成了`popTo(CurrentFragment.class ,true)`引起的，稍后修复
