### ISSUE TITLE
清除loadRootFragment的中的fragment

### ISSUE THREAD

**Issue by yanshihao3** [YoKeyword/Fragmentation#715]
加载根fragment后，startFragment 如何让根fragment的pop

**Comment by LonelyMushroom** [comment]
我猜你可以使用 `startWithPop` 这个api ,建议更新到最新的1.2.0版本

**Comment by yanshihao3** [comment]
startWithPop 这个方法，对于根fragment，没有效果。

**Comment by YoKeyword** [comment]
v1.2.2已修复根Fragment的`startWithPop()`无效问题，  #717
