### ISSUE TITLE
startWithPop方法，

### ISSUE THREAD

**Issue by yanshihao3** [YoKeyword/Fragmentation#717]
加载根fragment后，startFragment 如何让根fragment的pop

**Comment by yanshihao3** [comment]
使用startwithpop方法，有时候会出行 当前的fragment不会隐藏，要跳转的不会显示，但是栈中存在的是要跳转的fragment

**Comment by YoKeyword** [comment]
@yanshihao3   是v1.2.0添加了队列机制的原因，pop后`start()`的时机变了，稍后修复该问题

**Comment by yanshihao3** [comment]
@YoKeyword             loadRootFragment(R.id.fl_container, SplashFragment.newInstance());
如何把SplashFragment pop出栈，使用startWithPop无效果，是在activity中重新loadRootFragment一下吗

**Comment by YoKeyword** [comment]
@yanshihao3  `startWithPop()`已支持RootFragment,   v1.2.2

另外也可以使用下面的方法达到目的（这种方法的NextFragment的根布局需要指定一个`background`）：
````java
// SplashFragment中控制（若在Activity控制，参考下面写法对应替换即可）：
popTo(SplashFragment.class,true,new Runnable(){
      @Override
      public void run() {
            // 若想有动画，popTo(fg,true,runnable,R.anim.fragment_pop_exit) + loadRootFragment(container,fg,true,true)即可
           ((SupportActivity) _mActivity).loadRootFragment(R.id.fl_container, NextFragment.newInstance());
      }
});
````
