### ISSUE TITLE
第三方控件的应用

### ISSUE THREAD

**Issue by Freedomhxb** [YoKeyword/Fragmentation#72]
大神，你好，我现在遇到一些问题，比如 高德地图 的mapview使用，它会跟随activity的每个生命周期实现它的生命周期的方法，比如 在 activity的onresume 方法，mapview也要实现mapview.onresume ，在activity的onpause中，mapview也要实现mapview.onpause 等，还有好多第三的控件也是这种设计，那么，如何在fragment，更好的使用这些控件呢？ 谢谢大神，小弟不更感激

**Comment by YoKeyword** [comment]
我的项目也用到了地图， 处理方式除了在onResume,onPause里调用地图对应的生命周期外，在onHiddenChanged里也要对应调用这2个方法~  这里要考虑的多点，考虑页面（内存）重启的情况下，是否需要特别处理~

**Comment by Freedomhxb** [comment]
谢谢，我试试看
