### ISSUE TITLE
compile error : Fragmentation:fragmentation_core:unspecified.

### ISSUE THREAD

**Issue by niulinguo** [YoKeyword/Fragmentation#720]
Could not find Fragmentation:fragmentation_core:unspecified.
Required by:
    project :latte-core > me.yokeyword:fragmentation:1.2.2

**Comment by YoKeyword** [comment]
v1.2.2的包没有上传成功，明早重新上传 ：）

**Comment by liyungui** [comment]
现在还没上传啊

**Comment by YoKeyword** [comment]
已上传  😅

**Comment by niulinguo** [comment]
之前有问题的1.2.2是不是没有删除？现在gradle下载到了两个版本的1.2.2，还是编译不通过。

> ➜  1.2.2 ll
total 0
drwxr-xr-x  3 niulinguo  staff    96B  1  3 10:50 7d3063943121cddfa53360235c90e31916f4536
drwxr-xr-x  3 niulinguo  staff    96B  1  3 10:50 9bfc0e299a908b5847b3c7d1b81b1fc7f2815919
➜  1.2.2 pwd
**/.gradle/caches/modules-2/files-2.1/me.yokeyword/fragmentation/1.2.2

**Comment by niulinguo** [comment]
问题没有解决？我把缓存清除了，再试还是一样的错误？

**Comment by YoKeyword** [comment]
@niulinguo  maven上已经删除了，是缓存原因，把.gradle/cache/modules-2/filesxx 下的me.yokeyword删除下 即可

**Comment by niulinguo** [comment]
➜  1.2.2 ll
total 0
drwxr-xr-x  3 niulinguo  staff    96B  1  3 12:48 7d3063943121cddfa53360235c90e31916f4536
drwxr-xr-x  3 niulinguo  staff    96B  1  3 12:49 9bfc0e299a908b5847b3c7d1b81b1fc7f2815919
➜  1.2.2 pwd
**/.gradle/caches/modules-2/files-2.1/me.yokeyword/fragmentation/1.2.2

能帮我看一下这个签名对吗，缓存删过了重新下载的，还是有问题

**Comment by YoKeyword** [comment]
emmm 为了体验，下午我更新到v1.2.3吧  :)

**Comment by YoKeyword** [comment]
已经发布 v1.2.3  @niulinguo @liyungui

**Comment by liyungui** [comment]
可以了。感谢 @YoKeyword

**Comment by niulinguo** [comment]
感谢 @YoKeyword
