### ISSUE TITLE
1.2.3 startWithPop crash

### ISSUE THREAD

**Issue by niulinguo** [YoKeyword/Fragmentation#722]
error info

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.diabin.fastec.example, PID: 30325
                                                                           java.lang.NullPointerException: Attempt to invoke interface method 'me.yokeyword.fragmentation.SupportFragmentDelegate me.yokeyword.fragmentation.ISupportFragment.getSupportDelegate()' on a null object reference
                                                                               at me.yokeyword.fragmentation.TransactionDelegate.startWithPop(TransactionDelegate.java:153)
                                                                               at me.yokeyword.fragmentation.SupportActivityDelegate.startWithPop(SupportActivityDelegate.java:250)
                                                                               at me.yokeyword.fragmentation.SupportActivity.startWithPop(SupportActivity.java:188)

    /**
     * Start the target Fragment and pop itself
     */
    public void startWithPop(ISupportFragment toFragment) {
        mTransactionDelegate.startWithPop(getSupportFragmentManager(), null, toFragment);
    }

这个方法调用了mTransactionDelegate.startWithPop，from为null

 /**
     * Start the target Fragment and pop itself
     */
    void startWithPop(final FragmentManager fm, final ISupportFragment from, final ISupportFragment to) {
        int containerId = from.getSupportDelegate().mContainerId;
        bindContainerId(containerId, to);

但是这个方法里面，使用了from

空指针异常

**Comment by LonelyMushroom** [comment]
你这个看起来是没TopFragment  在 `startWithPop` 前把栈视图贴下上来不?

**Comment by niulinguo** [comment]
我看1.2.3版本中  startWithPop 的源代码，fromFragment传的就是null，应该是源代码的问题吧

**Comment by YoKeyword** [comment]
是的，v1.2.2为了解决 #717  引出的问题，没有考虑到，稍晚修复  [捂脸]

**Comment by YoKeyword** [comment]
已修复 v1.2.4，此外在你的 PR #723 的基础上可以看下这个[commit](https://github.com/YoKeyword/Fragmentation/commit/07d088e02be9d91d24bacdc2eba2da7a8652be4e)， 增强兼容性，在同时执行多事务时依然可以正常工作
