### ISSUE TITLE
求教，在栈顶会多出一个SupportRequestManagerFragment，是怎么回事？

### ISSUE THREAD

**Issue by DuoLa512** [YoKeyword/Fragmentation#724]
![1](https://user-images.githubusercontent.com/20768073/34514826-2d29e86e-f0aa-11e7-8f82-f34807d1eaf6.jpeg)

**Comment by LonelyMushroom** [comment]
[碰到问题先搜索下iss ,可能就解决了](https://github.com/YoKeyword/Fragmentation/issues?utf8=%E2%9C%93&q=SupportRequestManagerFragment)

**Comment by DuoLa512** [comment]
已解决
