### ISSUE TITLE
unFocus(android.view.View)' on a null object

### ISSUE THREAD

**Issue by NicChongMy** [YoKeyword/Fragmentation#725]
Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference

从notification进入app过后加载几个fragment就会遇到这个问题了

 Library version - 1.2.4

**Comment by LonelyMushroom** [comment]
问题描述太模糊了,最好具体点.错误日志最好贴全

**Comment by YoKeyword** [comment]
@NicChongMy  该异常一般是栈视图出现问题，崩溃前的栈视图提供下

**Comment by Gundam0079** [comment]
我也经常碰到这个问题 线上的崩溃步骤不太好复现

**Comment by FightingLarry** [comment]
@YoKeyword  怎么关闭了，怎么解决的？

**Comment by YoKeyword** [comment]
@FightingLarry   没有提供栈视图 和 复现步骤， 暂时关闭了， 可以先尝试升级到最新版

如果有相同问题，请重新创建issue
