### ISSUE TITLE
我采用的时单Activity + 多Fragment的形式，返回主页面时会出现闪退，什么原因？是因为onBackPressedSupport（）方法码？

### ISSUE THREAD

**Issue by jackandroid2016** [YoKeyword/Fragmentation#726]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by LonelyMushroom** [comment]
Library version
Support-v4 version
Logs
Screenshots
请提供上面这些东西

**Comment by jackandroid2016** [comment]
implementation 'me.yokeyword:fragmentation-core:1.2.3'
implementation 'com.android.support:appcompat-v7:26.1.0'

**Comment by jackandroid2016** [comment]
![image](https://user-images.githubusercontent.com/19246186/34547950-b84a6d12-f139-11e7-9ab5-a3c1222472f6.png)

**Comment by LonelyMushroom** [comment]
看你的代码感觉你可能需要使用这个api `pop`

**Comment by YoKeyword** [comment]
@jackandroid2016 崩溃日志？
