### ISSUE TITLE
1.1.10升级到1.2.4后，fitsSystemWindows无效了

### ISSUE THREAD

**Issue by gjjofsfe** [YoKeyword/Fragmentation#728]
1.1.10升级到1.2.4后，fitsSystemWindows无效了

**Comment by YoKeyword** [comment]
1.2.x没有改动相关的东西，仅仅添加一个队列机制，一些事务的执行时机可能稍微靠后点 

是否有使用其它第三方和状态栏相关的库，相关代码贴一下看看

**Comment by gjjofsfe** [comment]
我的代码没有动，只是替换一下依赖版本，就会造成fitsSystemWindows失效，我先研究一下
