### ISSUE TITLE
在fragment中嵌套使用 ViewPager + fragment 时，SharedElement Transition好像有点问题

### ISSUE THREAD

**Issue by zhangluya** [YoKeyword/Fragmentation#73]
我在overflow上搜了一下，貌似这样的情况确实会有异常现象 http://stackoverflow.com/questions/30628543/fragment-shared-element-transitions-dont-work-with-viewpager

**Comment by YoKeyword** [comment]
嗯啊 感谢提醒 目前SharedElement属于实验性阶段，我也没在ViewPager里试过，回头看下  :)
