### ISSUE TITLE
作者你好：AnimateOnHWLayerIfNeededListener导致fragment无法进行回收请问应该怎么解决

### ISSUE THREAD

**Issue by ximenGG** [YoKeyword/Fragmentation#730]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by ximenGG** [comment]
使用这个DefaultVerticalAnimator就有内存泄漏，DefaultHorizontalAnimator和DefaultNoAnimator是没有这个情况，夜神模拟器上测试的。请大神解释一波。

**Comment by YoKeyword** [comment]
库中 `DefaultVerticalAnimator`  `DefaultHorizontalAnimator`  `DefaultNoAnimator` 的区别在于加载的anim.xml组员不同，其他无任何区别， 你可以查看它们的代码看下

另外`AnimateOnHWLayerIfNeededListener`是v4包里和硬件加速有关的类，建议针对硬件加速的问题使用真机调试下
