### ISSUE TITLE
MainFragment 的viewpager  不能响应滑动

### ISSUE THREAD

**Issue by quanquan521** [YoKeyword/Fragmentation#731]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by LonelyMushroom** [comment]
可以详细的描述下么

**Comment by quanquan521** [comment]
是这样的  我在MainFragment  里放的一个viewpager，  viewpager  添加的Fragment   滑动的时候或点击底部线性布局导航 提示ViewPostImeInputStage ACTION_DOWN

**Comment by LonelyMushroom** [comment]
https://stackoverflow.com/questions/30968660/viewpostimeinputstage-action-down
https://www.jianshu.com/p/3b6de3c61dca

你看看这个能行么?

**Comment by YoKeyword** [comment]
@quanquan521 参考Demo写法：[WechatSecondTabFragment](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_wechat/ui/fragment/second/WechatSecondTabFragment.java)

**Comment by quanquan521** [comment]
public class MainFragment extends CoreBaseFragment<MainFragmentPresenter,MainFragmentModle> implements MainContract.MainFragmentView {
    List<Fragment> fragments = new ArrayList<>();
    @BindView(R.id.viewpager)
    ViewPager  viewpager;
    @BindView(R.id.id_rg)
    RadioGroup radioGroup;


    @Override
    public int getLayoutId() {
        return R.layout.fragment_main;
    }

    @Override
    public void initUI(View view, @Nullable Bundle savedInstanceState) {

        radioGroup.setOnCheckedChangeListener((group,checkedId)->{
            switch (checkedId){
                case R.id.id_firstpage:
                    viewpager.setCurrentItem(0);
                    break;
                case R.id.id_shop:
                    viewpager.setCurrentItem(1);
                    break;
                case R.id.id_car:
                    viewpager.setCurrentItem(2);
                    break;
                case R.id.id_my:
                    viewpager.setCurrentItem(3);
                    break;
            }
        });



    }

    @Override
    public void showError(String msg) {

    }
    @Override
    public void showTabList(String[] mTabs) {
        for (int i = 0; i < mTabs.length; i++) {
            switch (i) {
                case 0:
                    fragments.add(new FirstPageFragment());
                    break;
                case 1:
                    fragments.add(new StoreFragmet());
                    break;
                case 2:
                    fragments.add(new CarFragment());
                    break;
                default:
                    fragments.add(new UserFragment());
                    break;
            }
        }
        int position = getArguments().getInt(Constants.ARG_POSITION, 1);
        viewpager.setAdapter(new FragmentAdapter(getChildFragmentManager(), fragments));
        viewpager.setCurrentItem(position);//要设置到viewpager.setAdapter后才起作用
       if (0==position){
           radioGroup.check(R.id.id_firstpage);
       }else if (1==position){
           radioGroup.check(R.id.id_shop);
       }else if (2==position){
           radioGroup.check(R.id.id_car);
       }else if (3==position){
           radioGroup.check(R.id.id_my);
       }

    }
    public static MainFragment newInstance(int position) {
        MainFragment fragment = new MainFragment();
        Bundle bundle = new Bundle();
        bundle.putInt(Constants.ARG_POSITION, position);
        fragment.setArguments(bundle);
        return fragment;
    }

**Comment by quanquan521** [comment]
请指导

**Comment by LonelyMushroom** [comment]
没看出有什么问题,你贴下xml看看

**Comment by quanquan521** [comment]
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    >
    <LinearLayout
        android:orientation="vertical"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">
        <android.support.v4.view.ViewPager
            android:layout_weight="1"
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
        <RelativeLayout
            android:background="#ffffff"
            android:layout_width="match_parent"
            android:layout_height="@dimen/hight_50dp">
            <RadioGroup
                android:paddingTop="3dp"
                android:id="@+id/id_rg"
                android:orientation="horizontal"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <RadioButton
                    android:id="@+id/id_firstpage"
                    android:checked="true"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_home_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="首页"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton

                    android:id="@+id/id_shop"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_shop_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="门店"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton
                    android:id="@+id/id_car"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_car_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="租物车"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton
                    android:id="@+id/id_my"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_my_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="我的"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />

            </RadioGroup>
            <LinearLayout
                android:layout_width="fill_parent"
                android:layout_height="50dp"
                android:orientation="horizontal"
                android:background="#00000000"

                >
                
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    android:background="#00000000"
                    />
                
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
                
                <Button
                    android:layout_marginLeft="30dp"
                    android:id="@+id/bt"
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
            </LinearLayout>



        </RelativeLayout>






    </LinearLayout>
</FrameLayout>

**Comment by quanquan521** [comment]
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    >
    <LinearLayout
        android:orientation="vertical"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">
        <android.support.v4.view.ViewPager
            android:layout_weight="1"
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
        <RelativeLayout
            android:background="#ffffff"
            android:layout_width="match_parent"
            android:layout_height="@dimen/hight_50dp">
            <RadioGroup
                android:paddingTop="3dp"
                android:id="@+id/id_rg"
                android:orientation="horizontal"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <RadioButton
                    android:id="@+id/id_firstpage"
                    android:checked="true"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_home_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="首页"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton

                    android:id="@+id/id_shop"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_shop_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="门店"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton
                    android:id="@+id/id_car"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_car_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="租物车"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton
                    android:id="@+id/id_my"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_my_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="我的"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />

            </RadioGroup>
            <LinearLayout
                android:layout_width="fill_parent"
                android:layout_height="50dp"
                android:orientation="horizontal"
                android:background="#00000000"

                >
                
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    android:background="#00000000"
                    />
                
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
                
                <Button
                    android:layout_marginLeft="30dp"
                    android:id="@+id/bt"
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
            </LinearLayout>
        </RelativeLayout>

    </LinearLayout>
</FrameLayout>

**Comment by LonelyMushroom** [comment]
```
<FrameLayout <---root layout
   <LinearLayout <-- parent wrap start
   ...
       <!-- your content -->
   </LinearLayout> <-- parent wrap end
</FrameLayout> <-- root layout end
```

你改成这样试下 还有xml要贴全哟

**Comment by quanquan521** [comment]
<LinearLayout
        android:orientation="vertical"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">
        <android.support.v4.view.ViewPager
            android:layout_weight="1"
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
        <RelativeLayout
            android:background="#ffffff"
            android:layout_width="match_parent"
            android:layout_height="@dimen/hight_50dp">
            <RadioGroup
                android:paddingTop="3dp"
                android:id="@+id/id_rg"
                android:orientation="horizontal"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <RadioButton
                    android:id="@+id/id_firstpage"
                    android:checked="true"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_home_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="首页"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton

                    android:id="@+id/id_shop"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_shop_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="门店"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton
                    android:id="@+id/id_car"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_car_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="租物车"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />
                <RadioButton
                    android:id="@+id/id_my"
                    android:textColor="@drawable/selector_text"
                    android:drawableTop="@drawable/selector_my_pho"
                    android:gravity="center"
                    android:button="@null"
                    android:text="我的"
                    android:layout_weight="1"
                    android:layout_width="0dp"
                    android:layout_height="match_parent" />

            </RadioGroup>
            <LinearLayout
                android:layout_width="fill_parent"
                android:layout_height="50dp"
                android:orientation="horizontal"
                android:background="#00000000"

                >
                
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    android:background="#00000000"
                    />
                
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
                
                <Button
                    android:layout_marginLeft="30dp"
                    android:id="@+id/bt"
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
                <Button
                    android:visibility="invisible"
                    android:layout_height="fill_parent"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    />
            </LinearLayout>
        </RelativeLayout>

    </LinearLayout>

**Comment by quanquan521** [comment]
外面是Framelayout   试过了

**Comment by LonelyMushroom** [comment]
你加下我的qq 846760637

**Comment by quanquan521** [comment]
有问题验证

**Comment by quanquan521** [comment]
我QQ593099895

**Comment by LonelyMushroom** [comment]
我加你的?

**Comment by LonelyMushroom** [comment]
原因找到了,由于fragmentation版本号太低了,升级到
`compile 'me.yokeyword:fragmentation:1.2.4'`就好了
原版本号: `compile 'me.yokeyword:fragmentation:0.7.13'`
