### ISSUE TITLE
关于数据重新加载问题

### ISSUE THREAD

**Issue by wuconghui** [YoKeyword/Fragmentation#732]
作者您好，我用一个mainfragment嵌套4个fragment，并使用了viewpager，我在fragment1里面加载了一个列表，当我从fragment1滑动到fragment2在回来时，没有问题，fragment1的数据还在，当我从fragment1滑动到fragment2在滑动到fragment3在回来时，fragment1会重新走onCreateView（）方法，重新加载了一遍数据，请问这种问题要如何解决

**Comment by LonelyMushroom** [comment]
有两种解决办法
1. 设置viewpager的setOffscreenPageLimit(4),这个最简单,如果嵌套的多的话不推荐
2. 做数据保存在onSaveInstanceState把你获取到的数据保存起来,然后再onActivityCreated里面判断savedInstanceState!=null时恢复数据,思路是这样的.

原因:
>  FragmentPagerAdapter是采用attach和detach.
