### ISSUE TITLE
启动Activity时会有短暂的白屏，demo中也存在这个问题

### ISSUE THREAD

**Issue by devxj** [YoKeyword/Fragmentation#733]
RT  ，版本号1.2.4

**Comment by YoKeyword** [comment]
v1.2.x加入了队列机制，因为为了线程安全，所有事务都会post到主线程队列

这样在启动Activity时，`loadRootFragment()`这个事务会post到主线程队列，即：Activity绘制完成后才加载，导致动画时是空白的，因为还没有执行加载

因为考虑到影响不大，所以目前是这样的

**Comment by devxj** [comment]
非常感谢作者的解答 @YoKeyword

**Comment by YoKeyword** [comment]
@devxj   已发布v1.2.5， 解决了该问题 🍺

**Comment by devxj** [comment]
@YoKeyword 收到，谢谢🍺
