### ISSUE TITLE
我从github下载进来之后，报错

### ISSUE THREAD

**Issue by LiuSolomon** [YoKeyword/Fragmentation#734]
Error:Cause: unable to find valid certification path to requested target
有人知道解决办法吗？我查了一下代理的问题

**Comment by LonelyMushroom** [comment]
你有梯子么?里面有些是要代理才能下载的.
也就是说你查查你的梯子看看有没有问题

**Comment by LiuSolomon** [comment]
什么叫梯子？我是默认的

**Comment by LiuSolomon** [comment]
依赖没问题，但是不怎么会用。我本意想看源码怎么搞的
