### ISSUE TITLE
Swipeback有侧滑关闭当前页的判断方法吗

### ISSUE THREAD

**Issue by Alexyulu** [YoKeyword/Fragmentation#735]
SwipeBackLayout的三个监听感觉没办法检测是否由侧滑关闭了当前页，监听暴露出来的状态或者滑动距离没有办法知晓滑动是否达到了关闭的阈值。

**Comment by YoKeyword** [comment]
@Alexyulu  抱歉才回复， 目前确实`SwipeBackLayout`没有方法可以判断是否由侧滑关闭了当前页，下一版本会添加该支持

暂时可以通过曲线方式来得知是否由滑动引起的关闭页面：
````java
    boolean backPop = false;

    @Override
    public boolean onBackPressedSupport() {
        backPop = true;
        return super.onBackPressedSupport();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
       // backPop ? 非侧滑关闭 : 侧滑关闭
    }
````

**Comment by YoKeyword** [comment]
v1.2.6， 对`OnSwipeListener`的`onDragStateChange`添加了`STATE_FINISHED`状态，在侧滑完成即将关闭Activity/Fragment时回调
