### ISSUE TITLE
Android 7.0 Fragment has not been attached yet

### ISSUE THREAD

**Issue by mavisli** [YoKeyword/Fragmentation#737]
这是我们从bugly收集到的出错堆栈。设备系统都在Android 7.0以上。请问大家有出现类似情况吗，求教。

* Library version - 1.0.8
* Support-v4 version - 25.3.1
* Logs - 

java.lang.IllegalStateException
Fragment has not been attached yet.

android.support.v4.app.Fragment.instantiateChildFragmentManager(Fragment.java:2154)
 android.support.v4.app.Fragment.getChildFragmentManager(Fragment.java:704)
me.yokeyword.fragmentation.helper.internal.c.d(VisibleDelegate.java:140)
me.yokeyword.fragmentation.helper.internal.c.a(VisibleDelegate.java:19)
me.yokeyword.fragmentation.helper.internal.c$1.run(VisibleDelegate.java:126)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5669)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/607

**Comment by mavisli** [comment]
@LonelyMushroom 我更新一下版本再观察一下数据。谢谢！

**Comment by dx-berry** [comment]
1.3.7 版本还是会出现。
