### ISSUE TITLE
点击RecyclerView跳转Fragment时，无法响应item的水波纹效果

### ISSUE THREAD

**Issue by dingputongxi** [YoKeyword/Fragmentation#738]
# Issues Guideline
Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
`start`时，当前Fragment会立即处于hidden状态，即View本身已经隐藏了，所以看不到水波纹效果；
如果想要的该效果的话，点击后延迟200ms-300ms再`start()` ....

**Comment by dingputongxi** [comment]
好，我也觉得是这个问题，谢谢解答，两个线上项目都在用Fragmentation,谢谢
