### ISSUE TITLE
BaseFragment  重写 onBackPressedSupport     _mActivity.finish();   要点击好几次才退出

### ISSUE THREAD

**Issue by quanquan521** [YoKeyword/Fragmentation#739]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by quanquan521** [comment]
@Override
    public boolean onBackPressedSupport() {
       /* if (getChildFragmentManager().getBackStackEntryCount() > 1) {
            popChild();
        } else {
          //  _mBackToFirstListener.onBackToFirstFragment();
            _mActivity.finish();
        }*/
        _mActivity.finish();
        return true;
    }

**Comment by quanquan521** [comment]
@Override
    public boolean onBackPressedSupport() {
       /* if (getChildFragmentManager().getBackStackEntryCount() > 1) {
            popChild();
        } else {
          //  _mBackToFirstListener.onBackToFirstFragment();
            _mActivity.finish();
        }*/
        _mActivity.finish();
        return true;
    }

**Comment by quanquan521** [comment]
是这样的   但是要点几次

**Comment by LonelyMushroom** [comment]
你贴下栈视图?

**Comment by quanquan521** [comment]
![Uploading Screenshot_2018-01-16-16-02-41-861_com.comefilm.k.png…]()

**Comment by quanquan521** [comment]
上传出错    就是一个MainFragment   底下四个子Fragment

**Comment by quanquan521** [comment]
![screenshot_2018-01-16-16-02-41-861_com comefilm k](https://user-images.githubusercontent.com/20299679/34978012-c3420a98-fad7-11e7-92f1-e1fdde89c213.png)

**Comment by LonelyMushroom** [comment]
我在微信demo测试没有问题 `WechatFirstTabFragment` 你参考demo排查下是不是哪里多写导致覆盖

**Comment by quanquan521** [comment]
![wnu8 yuzeg 6 sj c 5n](https://user-images.githubusercontent.com/20299679/34978855-961196c6-fada-11e7-84fa-4d11b5bf7e49.png)
我的问题  没设置singleTask  导致启动了多个

**Comment by LonelyMushroom** [comment]
```
rxPermissions
    .requestEachCombined(Manifest.permission.CAMERA,
             Manifest.permission.READ_PHONE_STATE)
    .subscribe(permission -> { // will emit 1 Permission object
        if (permission.granted) {
           // All permissions are granted !
        } else if (permission.shouldShowRequestPermissionRationale)
           // At least one denied permission without ask never again
        } else {
           // At least one denied permission with ask never again
           // Need to go to the settings
        }
    });
```
看你的样子是因为RxPermission多个权限时调用多次导致,你可以使用这个api,如果用的是rxjava1的话你可以看看源码重写  不难的

**Comment by quanquan521** [comment]
好的

**Comment by yuanshenbin** [comment]
Library version 1.2.4
直接下的demo， 走的zhihu，onBackPressedSupport 这个一直不会执行，

**Comment by YoKeyword** [comment]
@yuanshenbin 没走应该是被 上层Fragment或子栈Fragment拦截处理了
