### ISSUE TITLE
FragmentA启动FragmentB问题

### ISSUE THREAD

**Issue by dyfan** [YoKeyword/Fragmentation#74]
通过start的方式启动，启动前通过eventBus传递了一个对象过去，我在B中接收到这个对象，然后改变对象的一些属性，通过set方法，但是返回到A之后，A的对象就业跟着变化，不知道为什么。
而且在B中，拿到对象之后，我不去调用B中recycleview的notify方法，也会显示出来recycleview。
困扰了一天了。

**Comment by YoKeyword** [comment]
EventBus  post的对象 和 接收的对象  是同一个对象（指向同一个堆内存地址） ，所以你修改对象，接收方和发送方的对象都会跟着被修改

**Comment by dyfan** [comment]
谢谢啦，我也刚刚理解这个，java比较薄弱，谢谢作者耐心解答。这个lssues我关啦。
