### ISSUE TITLE
startForResult不好使，前段时间还好好的，现在返回之后没有返回值

### ISSUE THREAD

**Issue by fanfan1009** [YoKeyword/Fragmentation#740]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by LonelyMushroom** [comment]
请提供以下资料
Library version
Support-v4 version
Logs
Screenshots

**Comment by fanfan1009** [comment]
Library version 1.2.4
Support-v4 version 26.1.0

截图传不上去

**Comment by fanfan1009** [comment]
这是第一个页面：
 @OnClick(R2.id.setting_user_email_ll)
    void onClickUserEmail() {
        getSupportDelegate().startForResult(ChangeUserInfoDelegate.create("修改邮箱", mUserEmail.getText().toString().trim()), 2);
    }

    @Override
    public void onFragmentResult(int requestCode, int resultCode, Bundle data) {
        super.onFragmentResult(requestCode, resultCode, data);
        if (requestCode == 0 && resultCode == 4) {
            String userName = data.getString("value");
            mUserName.setText(userName);
        } else if (requestCode == 2 && requestCode == 4) {
            String userEmail = data.getString("value");
            mUserEmail.setText(userEmail);
        }
    }

这是第二个页面：
    @OnClick(R2.id.change_user_info_save)
    void onClickSave() {
        Bundle args = new Bundle();
        args.putString("value", mEdit.getText().toString().trim());
        getSupportDelegate().setFragmentResult(4, args);
        getSupportDelegate().pop();
    }

**Comment by LonelyMushroom** [comment]
其实我想看的是栈视图,因为最新版的话是完全依照activity的result逻辑来的.

**Comment by fanfan1009** [comment]
我写的那个也是按照activity的逻辑，就是以前用着没问题，现在就不行了  不知道原因是啥

**Comment by LonelyMushroom** [comment]
我模拟了下发现正常,栈视图由下至上,使用的是微信demo中的第一个tab页
MainFragment-->MsgFragment-->TestFragment

MsgFragment
```MsgFragment
// OnClickListener
startForResult(TestFragment.newInstance(), 2);

    @Override
    public void onFragmentResult(int requestCode, int resultCode, Bundle data) {
        super.onFragmentResult(requestCode, resultCode, data);
        Log.d("onFragmentResult", "onFragmentResult: requestCode+" + requestCode + " -resultCode+" + resultCode);
    }
```

TestFragment
```TestFragment
// OnClickListener
Bundle args = new Bundle();
args.putString("value", "233333");
setFragmentResult(4, args);
pop();
```
