### ISSUE TITLE
getParentFragment请教

### ISSUE THREAD

**Issue by yuanshenbin** [YoKeyword/Fragmentation#742]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version 1.24
* Support-v4 version  26.10
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

拿demo中的zhihu，tab2来说，tab2实际时个viewpager+tablayout，推荐，热门... 我点击推荐列表的某个item，我想开启一个新的fragment，但是我不想覆盖tablayout的指示器，((SupportFragment) getParentFragment())。这种只能返回父亲的片段，如果我想返回父亲下的儿子的片段该怎么取，取出来的片段，star后 不要覆盖viewpager的指示器

**Comment by yuanshenbin** [comment]
没事了，已经想到迂回的方法解决了，在viewpager下的tab1里在loadRootFragment个根目录就可以了，虽然解决了，但是浪费的多嵌套一层，还是觉得怪怪的，viewpager-page1root-page1child

**Comment by YoKeyword** [comment]
是的，但是需求是漏出`tablayout `，嵌套一层也是正常做法
