### ISSUE TITLE
very buggy library

### ISSUE THREAD

**Issue by kashifansari786** [YoKeyword/Fragmentation#744]
this is very use-full library u made i appreciate it but it is very very buggy library list is below if u can solve this issue that is appreciated and use-full to other also:
1)i made 5 child fragment inside 1 parent fragment and one child fragment is call by another child fragment inside same parent fragment and if i declare a global array and if i clear this global array in first child fragment the global array is not clear in next four child fragment.
2)if i want to clear child fragment data inside parent fragment that is not possible while navigate to one child fragment to another, thats is only possible when i call parent fragment and that parent fragment clear data of only one child fragment which is linked to parent fragment other child fragment is still that data which they have .
3)if i call onsupportvisible() method and want to clear global array it is not clear coz global array is first call and that global array data is fix and not clear why this is happen.
4)library is not fully documented so that it is a thought task to understand it and solve it.
if this issue is solved i m very much thankful to you, guys you done very excellent job and sorry for my grammatical mistake.
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by kashifansari786** [comment]
and when child fragment have and server call and data which is process take time the fragment which is call that fragment is stuck on there and if i press many time it is crash and if i call that server call and other stuff in background task then also it take long time to process.

**Comment by YoKeyword** [comment]
I think these five Fragment did not use the same reference to the global array， you can use `Paremt Fragment` or `EventBus` to control the same global array.
