### ISSUE TITLE
有关内存重启时的问题.小米6   7.1.1

### ISSUE THREAD

**Issue by colder112** [YoKeyword/Fragmentation#747]
偶尔会出现,app后台一段后,在进入app,内存重启后,没有走onLazyInitView.....导致有时候从后台再次点进app时,没有访问接口...版本是1.2.4,我的华为6.0系统没有任何问题.. 是在mainfragment中的子fragment,  bagfragment的数据问题

**Comment by YoKeyword** [comment]
可以通过打开 开发者模式 -> 不保留活动 断点模拟调试  或者 模拟杀进程调试下； 讲道理Fragment是v4包的，应该不存在兼容问题

如果确定存在该问题，提供下 v4版本，和栈视图并指明哪个Fragment不走 `onLazy`

**Comment by colder112** [comment]
v4版本是25.3.1    大概情况是这样子的mainfragment里面有一个viewpager,viewpager里有4个fragment,分别为A,B,C,D.     当内存从启后,首先看到的是A,没有走onLazy访问接口,只有下啦刷新A或者切换到B在切换到A的时候,才会走onLazy

**Comment by colder112** [comment]
![screenshot_2018-01-23-10-40-14](https://user-images.githubusercontent.com/19330653/35255435-f735b082-0029-11e8-80f7-c3f63804ecf0.png)

**Comment by colder112** [comment]
版本号1.2.5又出现这个问题了...就是mainFragment中的viewpager里的四个子fragment.内存重启时,默认看到的是第一个fragment,不走onlazy...当切换第二个然后再切换到第一个时,会走onlazy

**Comment by YoKeyword** [comment]
@colder112 已经明确该场景了，我使用远程真机测试（小米6, 7.1.1），回调依然正常
测试包：https://fir.im/ffg ，  WechatDemo -> 第二个Tab -> ViewPager下的第一个FirstPagerFragment会在`onLazyInitView()`里弹一个Toast， 你可以试试

**Comment by colder112** [comment]
@YoKeyword 可能我的意思没有表达好....我的意思是,内存重启后,首先看到的是第一个bagFragment,偶尔会发生不走onLazy的情况.就是刚进去app,什么都不动,第一个bagFragment的第一次显示,不走onLazy....切换tab的话,是肯定会走onlazy的

**Comment by colder112** [comment]
在一个fragment中使用ZXingView扫描二维码的控件....返回键我设置的是popto(mainFragment.clas,false),小米6会出现下巴黑屏的现象.华为没问题.
![aaaaaaaaddd](https://user-images.githubusercontent.com/19330653/35423558-3da6f312-0289-11e8-882d-40da8bd727b2.jpg)

**Comment by YoKeyword** [comment]
@colder112 
> @colder112 已经明确该场景了，我使用远程真机测试（小米6, 7.1.1），回调依然正常
测试包：https://fir.im/ffg ，  WechatDemo -> 第二个Tab -> ViewPager下的第一个FirstPagerFragment会在`onLazyInitView()`里弹一个Toast， 你可以试试

这个demo就是模拟你描述的场景，你可以用小米6模拟下

黑下巴问题应该和Fragment无关

**Comment by colder112** [comment]
@YoKeyword  黑下巴的解决方案就是不用popTo,使用pop.. demo我试一下=.=

**Comment by colder112** [comment]
@YoKeyword demo是可以走的.但是我要详述的给你描述一下场景......小米6     短期放置后台app内存重启没问题,长期放置后台,内存重启后,不走mainFragment中viewpager下的第一个fragment的onLazy.

**Comment by YoKeyword** [comment]
长期放到后台，应该是进程被杀的场景， 你可以通过AS的强杀进程功能模拟

![image](https://user-images.githubusercontent.com/9691640/35808223-108f840e-0ac0-11e8-8192-b812b3d5ce1a.png)

**Comment by colder112** [comment]
@YoKeyword 小米6这个  内存重启请求数据放到oncreateview里就ok了....虽然这个界面用不了懒加载了..反正是底层界面无所谓..算是解决了...
