### ISSUE TITLE
关于在onDestoryView里取消网络请求的问题

### ISSUE THREAD

**Issue by bbiii** [YoKeyword/Fragmentation#749]
在Fragment的onDestoryView中做了ButterKnife的unbinder.unbind();和取消该页面对应网络请求的操作.
但问题是还是偶尔有可能出现view的空指针.看log应该是网络请求成功了但这一刻点了返回.然后我这边任然操作了ui导致的空指针.一般网络状态比较差的时候容易复现这个问题.
问一下有没有什么办法能避免这一状况发生?

**Comment by LonelyMushroom** [comment]
你先取消再解绑不就好了么,把事件优先级整理下就没问题了

**Comment by bbiii** [comment]
解绑不是unbinder.unbind()里的吗.是先取消请求然后解绑的

**Comment by LonelyMushroom** [comment]
伪代码 大概就是这个意思
```
    @Override
    public void onDestroyView() {
        super.onDestroyView();
        unSubscribe(); // 取消网络
        unbinder.unbind(); // 解绑
    }
```

**Comment by bbiii** [comment]
我的代码:
    @Override
    public void onDestroyView() {
        super.onDestroyView();
        OkHttpUtils.getInstance().cancelTag(this);
        unbinder.unbind();
    }

我问题描述写了:大部分情况没有问题,在请求网络时pop可以取消网络请求.但问题是在已经获取了数据的那一刻pop 还是会出现空指针.

**Comment by LonelyMushroom** [comment]
也就是说: 
获取数据成功-->调用pop-->OkHttpUtils.getInstance().cancelTag(this);-->unbinder.unbind();-->
获取数据成功后调用了View导致Null  
是上面这个流程么?
如果是这样的话那么就应该: 
1. 等调用完view后才能执行pop,这种用户体验不好
2. 执行pop之前取消调用view的操作,推荐这种方案

**Comment by bbiii** [comment]
我是想到了第二种方案,但是不知道怎么具体操作.请问您有没有什么思路可以提供一下,我一般会把返回的数据写在loadData()里面,在里面集中操作view展示数据,怎么样pop前停止或者在方法执行时停止;
我试了下在loadData开头加入判断是否add().没有add()就return不操作view.不知道这个方法是否可行

**Comment by YoKeyword** [comment]
可以在网络数据回调的地方判断下`if(view==null) return;`，另外推荐： 既然使用了okhttp 为何不一并使用Retrofit + RxJava呢， 你的问题可以通过取消RxJava的订阅事件来解决，RxJava会吞并你描述的这种极端情况的异常，而不用自己特殊处理
