### ISSUE TITLE
关于类知乎的结构的使用

### ISSUE THREAD

**Issue by montycoding** [YoKeyword/Fragmentation#75]
公司项目是一个Activity+多个Fragment的结构，刚好跟您的类知乎的结构差不多。但是在一个child fragment中启动一个新的fragment为什么却无法返回到上一个fragment，而是直接退出了整个应用（切换之后底部导航栏可以正常切换Fragment)

**Comment by YoKeyword** [comment]
可以看下仿知乎demo的做法，监听back键

**Comment by montycoding** [comment]
多谢，之前没有注意监听back键
