### ISSUE TITLE
swipebacklayout 设置全屏响应，触发太灵敏了，能降低灵敏度吗？ 现在非水平情况下很容易就触发了。

### ISSUE THREAD

**Issue by flztsj** [YoKeyword/Fragmentation#750]
#698 给出了解决类，是否可以评估再下个版本合入？

**Comment by flztsj** [comment]
#698

**Comment by flztsj** [comment]
还有是否可以SwipeBackLayout中加入下面方面，
    public void abortSwipeBack() {
        mHelper.abort();
    }

有类似检测侧滑后处理相关逻辑需要还原页面状态的。

**Comment by YoKeyword** [comment]
cool ，周末评估下

`abortSwipeBack()`方法可以提PR哈
> ps: 如果周末前没有提PR，那么我会在周末加上该方法

**Comment by flztsj** [comment]
[BetterViewDragHelper.zip](https://github.com/YoKeyword/Fragmentation/files/1684528/BetterViewDragHelper.zip)
最新的BetterViewDragHelper，解决快速滑动过程中莫名触发侧滑

**Comment by YoKeyword** [comment]
v1.2.6， 已替换`BetterViewDragHelper`，此外给`SwipeBackLayout`添加了`getViewDragHelper()`， 可以通过`getSwipeBackLayout().getViewDragHelper().abort();`等API来控制`ViewDragHelper`

**Comment by YoKeyword** [comment]
[v1.3.0](https://github.com/YoKeyword/Fragmentation/wiki#1%E7%89%B9%E6%80%A7)回滚了`ViewDragHelper`，回滚原因是 滑动过程中如果角度偏斜，会导致活动卡住 视觉上不连贯
