### ISSUE TITLE
startWithPop問題

### ISSUE THREAD

**Issue by kk00346** [YoKeyword/Fragmentation#751]
在LandingFragment內呼叫start與呼叫startWithPop
```
LoginFragment fragment = LoginFragment.newInstance();
        extraTransaction()
                .setCustomAnimations(R.anim.v_fragment_enter, 0, 0, R.anim.v_fragment_exit)
                .start(fragment);
//             .startWithPop(fragment);
```
兩個方法的棧視圖分別為

**startWithPop**
<img width="386" alt="2018-01-23 2 48 14" src="https://user-images.githubusercontent.com/5547943/35261827-e52e7c20-004c-11e8-866d-e5514000aa9a.png">

**start**
<img width="378" alt="2018-01-23 2 48 05" src="https://user-images.githubusercontent.com/5547943/35261847-f76e2ebc-004c-11e8-8fda-8082977b8c7d.png">

我的認知是startWithPop會退出當前的fragment並且呼叫下一個fragment，預想startWithPop應該會有LoginFragment跟MenuContainerFragment

是我的使用方法錯誤嗎？
感謝告知

版本為me.yokeyword:fragmentation:1.2.5

**Comment by YoKeyword** [comment]
是的，正常情况应该栈内只有：`LoginFragment`， 我试了下无法复现

可以贴下更多的代码片段吗？

**Comment by kk00346** [comment]
有一個Landing Page，進入後兩秒後要跳至LoginFragment，在LoginFragment判斷是否登入過，如果已登入會跳轉至MenuContainerFragment

在LandingPage的代碼為
```

public class LandingFragment extends BaseFragment {
    Handler handler;
    View view;
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_landing, container, false);
        handler = new Handler();
        handler.postDelayed(runnable, 2000);
        return view;
    }

    final Runnable runnable = new Runnable() {
        @Override
        public void run() {
            goLogin();
            handler.removeCallbacks(runnable);
        }
    };

    public static LandingFragment newInstance() {
        Bundle args = new Bundle();

        LandingFragment fragment = new LandingFragment();
        fragment.setArguments(args);
        return fragment;
    }

    private void goLogin() {
        LoginFragment fragment = LoginFragment.newInstance();
        extraTransaction()
                .setCustomAnimations(R.anim.v_fragment_enter, 0, 0, R.anim.v_fragment_exit)
                .start(fragment);
//             .startWithPop(fragment);

    }


}

```
把LoginFragment的跳轉邏輯拿掉，只單純顯示Login的畫面，呼叫後的棧視圖如下
**start**
<img width="381" alt="2018-01-23 8 39 47" src="https://user-images.githubusercontent.com/5547943/35276235-b85224e6-007d-11e8-94a5-2104da865667.png">
**startWithPop**
<img width="386" alt="2018-01-23 2 48 14" src="https://user-images.githubusercontent.com/5547943/35276255-c2722386-007d-11e8-9b51-f771a4ad73cc.png">

請問有什麼地方需要調整或者是要提供什麼其他資訊呢？

謝謝回覆

**Comment by YoKeyword** [comment]
场景很简单，但是还是没有复现，我推了一个测试分支用来模拟该场景：[test751](https://github.com/YoKeyword/Fragmentation/tree/test751)，对应commit：https://github.com/YoKeyword/Fragmentation/commit/776792475aae1c530f18272a06e55d17889f793c

**Comment by kk00346** [comment]
那可能是我這邊的架構出了什麼問題，我再找找看原因好了

感謝回覆
