### ISSUE TITLE
单Activity+FragmentMain->ViewPager

### ISSUE THREAD

**Issue by dushicai** [YoKeyword/Fragmentation#754]
1.Activity中添加RootFragment（FragmentMain）,
2.FragmentMain中包含一个ViewPager
3.ViewPager中包含多个子Fragment
4.动态添加删除ViewPager中的fragment

结果：ViewPager中的Fragment不会变化（依然是初始化时的数量）

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/648

**Comment by dushicai** [comment]
谢谢，不行。
麻烦作者回复一下

**Comment by YoKeyword** [comment]
参考 #648
