### ISSUE TITLE
模拟内存重启  fragment重叠问题

### ISSUE THREAD

**Issue by yiranLWS** [YoKeyword/Fragmentation#755]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version    1.2.5
* Support-v4 version   com.android.support:support-v4:26.0.0-alpha1
* Logs
* Screenshots 
![default](https://user-images.githubusercontent.com/16138685/35428883-5db8f9f2-02ac-11e8-8fd1-7ad54a2e561d.png)
![default](https://user-images.githubusercontent.com/16138685/35428898-702189ce-02ac-11e8-9d28-f557cc60def0.png)
在首页旋转屏幕模拟内存重启后fragment页面重叠，是需要写什么额外的逻辑么 我只是在
![default](https://user-images.githubusercontent.com/16138685/35428944-aa9ad416-02ac-11e8-8198-6c1e1685ef91.png)
这里判断了下saveinstens  还需要在哪判断么？ 求大神指点

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by LonelyMushroom** [comment]
请参考demo

**Comment by yiranLWS** [comment]
您好  我有个框架API的使用问题请教下您
类似微信的底部有三个tab对应三个同级的fragment  在第一个fragment中启动了二级页面   请问

如何在这个二级页面消失后跳到一级页面的第三个tab显示？ 框架里有直接的API调用么？没有的话可否
给说下思路(●'◡'●)

**Comment by LonelyMushroom** [comment]
1. 使用eventbus 在2fg pop()时调用切换tab的方法
2. 在父fg写切换tab的方法,2fg pop()时调用 getparentFragment.updateTab()

**Comment by yiranLWS** [comment]
非常感谢

**Comment by yiranLWS** [comment]
大佬，有本库的讨论QQ群么？

**Comment by yiranLWS** [comment]
大佬，问一个关于fragment状态恢复的问题，内存重启后，框架中是否对fragment里的控件状态也做了保存？比如recycview的滑动位置，我的现象是我把recycview滑动到底部fragment恢复后，recycview显示在最开始的位置，这个是需要手动保存下recycview的位置状态么

**Comment by YoKeyword** [comment]
@yiranLWS Fragmentation不干涉控件的恢复， RecyclerView控件内部是会帮忙恢复状态的，  你可以看到Demo是可以正常恢复位置的， 检查下对应RecyclerView的初始化代码

**Comment by yiranLWS** [comment]
好的，非常感谢您的回复

**Comment by yiranLWS** [comment]
您好，demo的知乎第一个页面是可以恢复位置的，但是微信的第一个页面好像不可以，这是什么原因啊

**Comment by YoKeyword** [comment]
@yiranLWS 原因在于`mRecy.setHasFixedSize(true);`，如果设置了 不恢复位置
