### ISSUE TITLE
升级到最新的报 onBackPressed() overrides final method 

### ISSUE THREAD

**Issue by stoneLee81** [YoKeyword/Fragmentation#757]
01-27 17:30:52.145 11826-11826/trip.com.tomato E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.LinkageError: Method void trip.com.tomato.mvpvm.ui.activity.mydayplan.MyDayplanActivity.onBackPressed() overrides final method in class Lme/yokeyword/fragmentation/SupportActivity; (declaration of 'trip.com.tomato.mvpvm.ui.activity.mydayplan.MyDayplanActivity' appears in /data/data/jra.trip.com.tomato/files/data/load-bundles/classes499_4.zip)
但在这个类里面没有用onBackPressed

**Comment by stoneLee81** [comment]
1.1.10版本没问题，升到了最新的就出现了这个异常

**Comment by YoKeyword** [comment]
应该和升级无关系，1.2.x相比较1.1.10，`onBackPressed()`一直是final， 检查下是否复写了`onBackPressed()`， 使用`onBackPressedSupport()`代替`onBackPressed()`
