### ISSUE TITLE
如何关闭所有切换动画？

### ISSUE THREAD

**Issue by dongweiq** [YoKeyword/Fragmentation#76]
最近在fragment里嵌套使用高德地图，使用动画的时候非常卡，所以想要把动画关掉，有没有对应的方法？

**Comment by YoKeyword** [comment]
可以参考wiki: [转场动画](https://github.com/YoKeyword/Fragmentation/wiki/3.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-%E8%BD%AC%E5%9C%BA%E5%8A%A8%E7%94%BB)

卡顿是因为Fragment的初始化机制和Activity机制不一样，但是是可以避免卡顿的，思路是懒加载，在动画结束后开始加载初始化地图等资源，库中也提供了动画结束后的懒加载回调`onEnterAnimationEnd()`，详情可以参考wiki:[优化](https://github.com/YoKeyword/Fragmentation/wiki/7.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-Fragment%E7%9A%84%E4%BC%98%E5%8C%96%E4%BD%BF%E7%94%A8)

**Comment by jeffer0323** [comment]
小米4.4系统，继承SwipeBackActivity后运行报错，华为6.0系统，运行正常，望大神赐教

**Comment by dongweiq** [comment]
谢谢，这个库非常棒
