### ISSUE TITLE
在RootFragment中使用loadMultipleRootFragment添加的子Fragment能否删除

### ISSUE THREAD

**Issue by Jeromeer** [YoKeyword/Fragmentation#761]
# Issues Guideline
作者您好,麻烦请教一下 
在RootFragment中使用loadMultipleRootFragment添加到容器内的子Fragment能否删除?
我使用findChildFragment然后pop之后,fragment还在,我重复添加某个子fragment报异常,提示我已经添加过,不能再添加

**Comment by Jeromeer** [comment]
谢谢,已经解决,使用getChildFragmentManager().beginTransaction().remove(fragment).commitAllowingStateLoss();解决,建议作者可以加一下这种remove的api进去,貌似目前只看见replease的,remove的需求还是有的,这样封装一下会更友好,再次感谢

**Comment by YoKeyword** [comment]
可以使用`extraTransaction()`，其内部有一些不常用的封装事务方法：
````java
extraTransaction()
.remove();
````
