### ISSUE TITLE
多层fragment,侧滑关闭失效

### ISSUE THREAD

**Issue by shaycormac** [YoKeyword/Fragmentation#762]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version       1.2.5
* Support-v4 version  26.1.0
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**
嗨，作者你好，我用你的最新库，使用一个模块单activity+多Fragment模式，activity，fragment仿照demo分别继承swipeActivity和swipeBackFragment现在问题是当进入这个activity时，fragmen使用start（）方法进入了3层，栈顶和第2个侧滑都失效，只有在activity的最底层那个fragment侧滑有效，同时关闭了当前的activity.  谢谢。

**Comment by shaycormac** [comment]
解决了。

**Comment by gaojian89** [comment]
怎么解决的？ @shaycormac
