### ISSUE TITLE
onDestoryView 后还有一定几率运行onEnterAnimationEnd方法

### ISSUE THREAD

**Issue by VankaIn** [YoKeyword/Fragmentation#764]
Library version 1.2.5

Demo 中的 MsgFragment 的 onDestoryView 改成以下代码可以重现：
```
@Override
public void onDestroyView() {
    super.onDestroyView();
    //change start
    mRecy = null;
    //change end
    _mActivity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN);
    hideSoftInput();
}
```

**Comment by VankaIn** [comment]
导致 onEnterAnimationEnd 里面对 view 操作时候有一定几率报空指针错误

**Comment by YoKeyword** [comment]
是的，`mNotifyEnterAnimEndRunnable`的内部还有个`post`，而只移除了`mNotifyEnterAnimEndRunnable`，所以可能导致该问题，感谢PR  🍺

**Comment by YoKeyword** [comment]
Cool,  PR已Merge，另外`getHandler().removeCallbacksAndMessages(null);`略微有些暴力，补了个commit重构了下：https://github.com/YoKeyword/Fragmentation/commit/729b36d09820234cae3c4db305777311b3ff2eff
