### ISSUE TITLE
自定义view在fragment 中显示异常

### ISSUE THREAD

**Issue by istarvip** [YoKeyword/Fragmentation#765]
[自定义view](https://github.com/qinjiahong/ColorProgress/blob/master/app/src/main/java/qjh/com/colorprogress/SportProgressView.java
) 在activity中显示正常，但在fragment中使用时，scrollview 嵌套它，scrollview 的视图没有超过一屏正常显示，超过一屏，显示异常，

**Comment by YoKeyword** [comment]
应该和自定义View相关，排查相关测量绘制等代码
