### ISSUE TITLE
Fragment 由于 使用了 getView().setClickable(true) 引出的问题。

### ISSUE THREAD

**Issue by zhangchaojiong** [YoKeyword/Fragmentation#766]
由于 getView().setClickable(true) ，我的 getLayoutId 里面的布局的控件并没有设置点击的 监听。但是在点击屏幕的时候，控件的 state_pressed 仍然被响应。这是为什么呢？

**Comment by zhangchaojiong** [comment]
我把 在 `initData` 做了 `getView().setClickable(false);  ` 处理，就正常了。不过这样子就有 点击事件穿透问题？这个要怎么破？

```
 @Override
    public void initData(Bundle savedInstanceState) {

        getView().setClickable(false);  
initViews();
        getP().getExtNetWorkConfig();
    }
```

**Comment by YoKeyword** [comment]
`state_pressed `被响应后导致了什么副作用？

你可以在确保上个Fragment被hide后再`setClickable(false)`，这样就可以解决所有问题

**Comment by zhangchaojiong** [comment]
我看到 SupportFragment 在 onActivityCreated 进行 setClickable(true) ，然后并没有在上一个fragment hide 的时候再进行 setClickable（false）回来。

**Comment by YoKeyword** [comment]
@zhangchaojiong `setClickable(true)`的目的是防止加载下一个Fragment动画中的穿透问题，所以理论上在动画结束时，再把`setClickable(原值)`即可， 之前尝试过这么做，后来忘记什么原因放弃了，下一版会尝试把clickable恢复

**Comment by zhangchaojiong** [comment]
OK

**Comment by YoKeyword** [comment]
[v1.3.0](https://github.com/YoKeyword/Fragmentation/wiki#1%E7%89%B9%E6%80%A7)
