### ISSUE TITLE
回退栈问题

### ISSUE THREAD

**Issue by CoKoOne** [YoKeyword/Fragmentation#767]
你好，我想请问一下，使用Fragmentation，如何才能实现像淘宝一样的效果：点击首页的某个商品，开启商品的详情页，然后商品详情页中有购物车按钮，点击商品详情页的购物车按钮，去到首页的购物车；然后点击了首页的购物车中的返回键又回到之前的商品详情页，这样的逻辑怎样实现呢？谢谢！
如果大佬肯指点一下，请致信@我 ，再次感谢！

**Comment by YoKeyword** [comment]
购物车页面是单独的Fragment，而不是首页的Fragment 即可

**Comment by CoKoOne** [comment]
附件是我写了的部分代码，能帮我看看吗？谢谢！
![1](https://user-images.githubusercontent.com/31817795/35787203-7a93ac4e-0a67-11e8-9aba-4e9fcb033760.jpg)
![2](https://user-images.githubusercontent.com/31817795/35787211-847eacea-0a67-11e8-85e1-34b7e10d81af.jpg)
[BottomFragmentTest.zip](https://github.com/YoKeyword/Fragmentation/files/1693734/BottomFragmentTest.zip)

**Comment by YoKeyword** [comment]
我的意思是： 从详情页跳转的购物车页面，是个单独的Fragment，没有BottomBar的，这样就可以轻松解决问题（你会发现iOS的淘宝就是这种交互，当然首页的购物车依然存在）

**Comment by CoKoOne** [comment]
@ YoKeyword Android端的淘宝就是共用一个购物车的，也不知道是怎么做的，我当前解决方案是当用户在商品详情页点击了购物车的时候，我就用Intent startActivity再次开启了首页底部标签栏的Fragmentactivity,然后在切换到购车fragment，但是这样任务栈会有两个Fragmentactivity，并且重走Fragmentactivity的生命周期，不太好掌控，感觉这个做法非常的low。也就是说现在Fragmentation 暂时没有什么良好的办法，实现这种功能，是吗？

**Comment by YoKeyword** [comment]
Android端淘宝首页是伪Tab， 还是看正常的交互吧， 新开一个购物车页面，不要复用首页的购物车，页面的“栈”结构决定了新开页面是最简单的，同时在交互上也更容易理解

**Comment by CoKoOne** [comment]
看了一下京东，跟你说的一样，单独做了一个购物车页面，不复用首页的购物车；既然大佬都说是这样了，只能建两个购物车了，谢谢！
