### ISSUE TITLE
我的应用是单activity模式的，如何一下回到栈顶？请告知

### ISSUE THREAD

**Issue by cjqq354139968** [YoKeyword/Fragmentation#768]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
`popTo(栈顶RootFragment,false)`  即可  (PS:注意要控制正确的栈层)
