### ISSUE TITLE
你好，又来打扰你了，请问如何让栈顶的fragment背景是透明的，可以顺利的看到底部fragment。

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#77]
@YoKeyword 
你好，又来打扰你了，请问如何让栈顶的fragment背景是透明的，可以顺利的看到底部fragment。

我现在使用您的框架，想在某一时刻触发一个fragment，这个fragment是透明的，只有少许地方放一些控件。能看到底下的fragment。这个用Activity很好实现，就把Activity的style设置成透明的就行。可是我用你的demo做了个试验，就是以SwipeBackFragment为试验对象，将SwipeBackFragment的背景设置成透明，但是启动这个Fragment时，一瞬间是透明的，紧接着有个白色背景填充了，背景就成白色的了，用手指点一下左侧边缘，白色背景就立马消失了，就能看到底部的homefragment，我好郁闷，为什么要点一下左侧边缘才可以达到我想要的效果。

我用的是小米5做的测试。

请问是有什么要注意的地方吗？有点急^_^

**Comment by YoKeyword** [comment]
@leguang 是这样的，start(fragment)是封装了add+show+hide ，之所以透明Fragment进入时先透明后白色背景填充，是因为上个Fragment在透明Fragment进入后hide了，其实Fragment一直是透明的，你看到的白色背景其实是Activity或者windowbackground的。

这里有3个方案，一个是提供startWithoutHide之类的方法，不过加入后start系列的所有方法都要加，好像不合适...  
还一种是暴露一个方法，自己做Fragment事务，这个回头好好考虑下有没有好的封装方式；

最后一种，你现在可以直接使用，在透明Fragment的onCreateView里执行下面的代码（具体用哪个FragmentManager看实际场景）：
````java
 public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        getFragmentManager().beginTransaction()
                .show(getPreFragment())
                .commit();
        ....
    }
````

**Comment by leguang** [comment]
@YoKeyword 
嗯，我用你提供的第三种方案可以达到我预期的效果。
原来你的start(fragment)==add+show+hide，没反映过来要去看源码。
你可以考虑一下我的这种需求，提供相应的封装，当然不是必需。
非常感谢你的方案，你可以关闭这个issues了^_^

**Comment by YoKeyword** [comment]
嗯  你的这种需求 一般来说很少的  我回头考虑下怎么用第二种方案来处理 ~
