### ISSUE TITLE
eventbus_activity_scope中的RuntimeTrojanProvider冲突

### ISSUE THREAD

**Issue by niulinguo** [YoKeyword/Fragmentation#773]
eventbus_activity_scope这个Library有点问题

`
 <provider
            android:name=".RuntimeTrojanProvider"
            android:authorities="${applicationId}.eventbus_activity_scope_trojan"
            android:exported="false"
            android:multiprocess="true"/>
`

这里的${applicationId}在Library中不起作用。
我有两个项目同时使用这个Library，不能同时安装，报错说这里冲突了。

附上资料
https://stackoverflow.com/questions/30790768/using-applicationid-in-library-manifest

**Comment by niulinguo** [comment]
我两个工程的applicationId不一样
我Build了一个Apk，发现Build之后的AndroidManifest文件中

`
 <provider
            android:name="me.yokeyword.eventbusactivityscope.RuntimeTrojanProvider"
            android:exported="false"
            android:multiprocess="true"
            android:authorities="me.yokeyword.eventbusactivityscope.trojan" />
`

我发现每个依赖包的ApplicationId都不是主项目的ApplicationId


![201518165354_ pic_hd](https://user-images.githubusercontent.com/11833706/36018635-68101d0c-0db7-11e8-8955-761fd5726341.jpg)

**Comment by YoKeyword** [comment]
`README`蒲公英上的APK，authorities正确， 检查下相关配置？

PS： 另外该写法和Google的[Android Architecture Components](https://developer.android.com/topic/libraries/architecture/index.html)中的provider写法一致

![image](https://user-images.githubusercontent.com/9691640/36019497-757ae924-0dba-11e8-8d10-2adfb199c8e4.png)

**Comment by niulinguo** [comment]
可能跟构建工具有关，我检查一下

**Comment by YoKeyword** [comment]
是的，1.1.7的是写死author，那个版本是我的问题， 1.1.10就是动态的了 :)
