### ISSUE TITLE
onDestoryView 设空 view 后发生 NullPointException

### ISSUE THREAD

**Issue by VankaIn** [YoKeyword/Fragmentation#775]
Library version：1.2.6。
因为第三方 api 返回的 callback 在异步线程，那么为了确保 UI 的处理能在 mainHandler 中运行，我处理是：
```
doSomeThings(new Callback() {
            @Override
            public void onSuccess() {
                post(() -> {
                    //UI 操作
                });
            }

            @Override
            public void onError() {
                post(() -> {
                     //UI 操作
                });
            }
        });
```
因为 onDestoryView  的时候只移除了mNotifyEnterAnimEndRunnable，所以手动 post 的操作是还有机会在 onDestoryView 之后调用的，当 view 在 onDestoryView 被设空后，会发生NullPointException

**Comment by YoKeyword** [comment]
使用方的手动post不属于Fragmentation的管理范围，  Fragmentation只处理库内部的`mNotifyEnterAnimEndRunnable

使用方需要自己处理， 比如上次你提到的`removeCallbacksAndMessages(null)`， 或者使用RxJava来轻松避免该问题

**Comment by VankaIn** [comment]
谢谢回复，对于故意泄露的场景，我也想不出具体的场景，因为post里面的操作都是ui操作，所以当ondestoryview结束之后，个人认为post的操作就没必要了。祝新年快乐哈
