### ISSUE TITLE
findFragment查找不到栈内fragment

### ISSUE THREAD

**Issue by liunewshine** [YoKeyword/Fragmentation#776]
* me.yokeyword:fragmentation:1.2.6
* com.android.support:design:27.0.2
![image](https://user-images.githubusercontent.com/7698511/36070607-9eb56442-0f39-11e8-9387-e433f790f570.png)

findFragment(MainFragment.class)为空
![image](https://user-images.githubusercontent.com/7698511/36070627-0cc41640-0f3a-11e8-89bf-23428758695a.png)

**Comment by YoKeyword** [comment]
`findFragment()`寻找的是同一层级的Fragment, `MainFragment`是最外层的栈级，和`ModelClassifyFragmentItem`不是同一层级， 可以使用:
`getParentFragment().getParentFragment()`来获取`Main Fragment`

**Comment by liunewshine** [comment]
了解
