### ISSUE TITLE
小米开发者平台中的云测

### ISSUE THREAD

**Issue by Deepblue1996** [YoKeyword/Fragmentation#777]
版本1.2.6 
提交的打包版本，云测中很多机型返回的截图中都是白屏，这是什么原因

**Comment by YoKeyword** [comment]
云测一般是Money Test， 白屏的话一般是栈层级出现问题，建议充分自测后寻找原因

**Comment by Deepblue1996** [comment]
云测，安卓6.0及以上版本会出现空白，以下版本不会，我怀疑是因为获取权限造成的。

**Comment by Deepblue1996** [comment]
获取权限问题
