### ISSUE TITLE
SupportFragment里面没有newInstance()这个方法啊

### ISSUE THREAD

**Issue by KingSingleDog** [YoKeyword/Fragmentation#779]
我的MyFragment已经继承了SupportFragment了，没有找到newInstance()这个方法

**Comment by YoKeyword** [comment]
`newInstance()` 是使用方自己添加的方法，很灵活，可以传递参数等
见[Demo](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_flow/ui/fragment/home/DetailFragment.java#L31)
