### ISSUE TITLE
你好，有没有方法像Activity一样finish()掉某个Fragment？

### ISSUE THREAD

**Issue by leguang** [YoKeyword/Fragmentation#78]
@YoKeyword 
你好，有没有方法像Activity一样finish()掉某个Fragment？

还是跟上午的需求关联，就是栈顶的Fragment是透明的，在栈顶fragment中的View做完动画之后想去除掉下面的Fragment，也就是想在栈中去除掉preFragment。如果是Activity栈，则Activity本身的finish()就可以结束自身。我在SupportFragment里面找了一下，没有类似的，只有pop()或者popTo()方法，这些都把栈顶的透明Fragment也弹栈了。

**Comment by YoKeyword** [comment]
Activity内处理其他Activity的生命周期 本身就是不推荐的，这样代表Activity持有其他Activity的引用，Activity的Task本身也是栈结构
非要实现的话 也是比较困难的 Fragment本身是更加标准的栈结构，操作Fragment是通过FragmentManager，而FragmentManager是没有相关方法让你关闭任意一个Fragment的，一般这种场景都是可以通过科学方式的设计去解决的~

还有如果实在想实现某个功能，而Fragment又比较难实现，就考虑用Activity，没必要坚持单AC+多FG，可以自由灵活配合使用，毕竟没任何冲突的，需要综合考虑下 :)

**Comment by leguang** [comment]
@YoKeyword 
嗯，确实是的，是得综合考虑一下技术栈再做决定。谢谢你的提议。我没问题了^_^
