### ISSUE TITLE
直接使用不带fragment的activity显示白屏

### ISSUE THREAD

**Issue by risechen** [YoKeyword/Fragmentation#780]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by risechen** [comment]
怎么使用不带fragment的activity

**Comment by YoKeyword** [comment]
当作普通的Activity使用即可，不过没有Fragment的话建议使用官方的AppcompatActivity
