### ISSUE TITLE
Activity的生命周期多执行了一次..

### ISSUE THREAD

**Issue by colder112** [YoKeyword/Fragmentation#781]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version 1.2.5
* Support-v4 version 25.3.1
* Logs
* Screenshots
因为正好在调试就打印了一下...发现
从logoActiivty中跳转到MainAcitivity ..onResume    onPause   onResume
貌似多执行了一轮....
只有第一次进入MainActivity会出现这种情况
**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
Activity/Fragment的生命周期，库没有做任何干涉，你可以再排查下
