### ISSUE TITLE
viewPager的嵌套onLazyInitView不执行

### ISSUE THREAD

**Issue by yihuajia** [YoKeyword/Fragmentation#783]
库的版本是1.2.7   
是一个平板项目，某个模块最外层A是一个tab+viewPager，然后左侧B也是tab+viewPager，在正常左右滑动A的时候B中的onLazyInitView是可以执行到的，但是如果是点击tab的话，不会执行onLazyInitView方法

**Comment by YoKeyword** [comment]
是否使用的`FragmentStatePagerAdapter` ?

**Comment by yihuajia** [comment]
@YoKeyword 是的

**Comment by YoKeyword** [comment]
`FragmentStatePagerAdapter`的`mUserVisibleHint`在切换时有个BUG (`FragmentPagerAdapter`是正常的) 获取的值会被重置掉，导致Fragment的`getUserVisibleHint()`不准确， 之前想到了处理方法，还没放到新版本中， 下一版本会修复

在这之前，建议不要使用`onLazyInitView()`，自己配合`setUserVisibleHint()`等方法实现懒加载回调，或者可以的话使用`FragmentPagerAdapter`

**Comment by yihuajia** [comment]
好的，修改了缓存大小，先将就着用了

**Comment by yihuajia** [comment]
好的，谢谢了，回头有空我试试

**Comment by Simon1121** [comment]
我用这个adapter出现了卡屏的情况
v4 27.1.1
fragmentation 1.3.7

viewpager offset 设置了 2，滑到第4张，然后往回滑一张，卡住
