### ISSUE TITLE
Fragment栈问题

### ISSUE THREAD

**Issue by LinusLi** [YoKeyword/Fragmentation#784]
一个Activity里start了多个Fragment，然后在最上面这个Fragment上start一个Acitivity后pop自己。
结果：把start的那个Activity结束后，pop自己的那个Fragment的视图还能看的到，但已经不在堆栈里了，而且视图已经完全没有响应了，按导航栏的back键还能继续操作Fragment的堆栈，视图不会变化了。

**Comment by LinusLi** [comment]
怀疑是和pop自己的时候，加入了队列有关，可能不能分开来操作，需要把start Activity的操作一起放到队列里面

**Comment by YoKeyword** [comment]
无法复现，库版本、v4包版本、机型系统以及代码贴下

**Comment by LinusLi** [comment]
1.2.6的版本，v4的版本是26.1.0，机型目前是手里有的华为都这样（5.0，6.0，7.0），代码很简单，就是startActivity(intent);

**Comment by YoKeyword** [comment]
只有华为系统有该问题？ 
我试了下华为6.0系统，仍然没有复现...

或者你使用
````java
popTo(CurrentFragment.class , true, ()-> { startActivity() } )
````
来代替你现在的写法试试

**Comment by LinusLi** [comment]
`/**
	 * Start the activity and pop itself
	 */
	void startWithPop(final FragmentManager fm, final ISupportFragment from, final Intent to)
	{
		enqueue(fm, new Action(Action.ACTION_POP)
		{
			@Override
			public void run()
			{
				ISupportFragment top = getTopFragmentForStart(from, fm);
				if (top == null)
				{
					throw new NullPointerException("There is no Fragment in the FragmentManager, maybe you need to call loadRootFragment() first!");
				}

				from.getSupportDelegate().getActivity().startActivity(to);

				Fragment topFragment = SupportUtils.getTopFragment(fm);
				ISupportFragment preFragment = SupportUtils.getPreFragment(topFragment);
				// 没有界面了，不做退栈操作
				if (null != preFragment)
				{
					FragmentTransaction ft = fm.beginTransaction().setTransition(FragmentTransaction.TRANSIT_FRAGMENT_CLOSE).remove(topFragment);

					ft.show((Fragment) preFragment);
					supportCommit(fm, ft);
					FragmentationMagician.popBackStackImmediateAllowingStateLoss(fm);
				}
			}
		});
	}`

我在TransactionDelegate里加了这么一个函数，暂时实现了功能，这里跳Activity跳的是其他app的Acitivity，不是自己app里的，不知道是否和这个也有关系

**Comment by YoKeyword** [comment]
跳转其他App的Activity依旧无法复现，建议你在Demo工程模拟场景来测试吧

**Comment by LinusLi** [comment]
试过了，做了一个简单的demo，如果用1.2.6之前的版本（出栈没有放到队列）的话，是没问题的，但是1.2.6上是有问题的，要实现想要的功能，只能是：
startActivity(intent);
getSupportDelegate().remove(this);
getSupportDelegate().pop();

必须先要remove自己，然后调用pop出栈才行
remove自己后，视图是前一个Fragment，但是还在栈里，这时候pop自己的话，视图不变，但是栈已经是对的了

**Comment by YoKeyword** [comment]
@LinusLi 可以把你的Demo上传然后发我下地址吗？  我需要先复现才好排查问题

**Comment by YoKeyword** [comment]
已解决，原因是在启动外部App的Activity时，在v4-27以下的版本中，存在该问题，解决方式：

1、使用`popTo(CurrentFragment.class, true, ()-> startActivity())`  （需要v1.2.7+） （推荐）

2、在低于v4-27时，使用
````java
startActivity(intent);
getFragmentManager().beginTransaction()
          .remove(this)
          .commitAllowingStateLoss()
pop();
````

3、升级v4到27.0.0+  （推荐）
