### ISSUE TITLE
请问如何移除路由栈中的fragment?

### ISSUE THREAD

**Issue by weiyongcheng** [YoKeyword/Fragmentation#785]
正常使用start方法进行跳转，现在想直接移除路由栈中的某一个路由，该如何实现呢？试过remove，好像不行。

**Comment by YoKeyword** [comment]
加入回退栈的Fragment 是无法通过remove移除的， 一旦加入回退栈，那么就是严格的栈结构，遵从栈的数据结构，不能移除栈中某个Fragment，只能从栈顶开始移除

建议的解决方式： 在WillPopFragment的上个Fragment `pop`时，同时把WillPopFragment关闭
