### ISSUE TITLE
ViewPager里的Fragment生命周期有问题

### ISSUE THREAD

**Issue by LinusLi** [YoKeyword/Fragmentation#786]
使用ViewPager，并且动态更新（使用了 notifyDataSetChanged()）时，Fragment的生命周期不对，使用的是FragmentPagerAdapter，具体可以看贴图

正常log：
![01](https://user-images.githubusercontent.com/562553/36823883-58d3cf04-1d3a-11e8-912b-48aeccc1b110.png)

异常log：
![02](https://user-images.githubusercontent.com/562553/36823893-6ed2d44e-1d3a-11e8-8bca-270ed1d8a6ba.png)

异常发生的时候的调用堆栈：
![03](https://user-images.githubusercontent.com/562553/36823896-72942bdc-1d3a-11e8-80a8-31872898ace8.png)

会发生的异常代码：
![04](https://user-images.githubusercontent.com/562553/36823899-7546a9b8-1d3a-11e8-99d6-8b8a73d3172a.png)

Following information can help us to resolve the issue faster.

* Library version 1.2.6
* Support-v4 version 26.1.0

**Comment by LinusLi** [comment]
现在可以确定的是，换了adapter的数据源，但是数据源里的id没有换的话，必现这种问题

**Comment by YoKeyword** [comment]
可否不使用SupportFragment，使用官方的Fragment来测试下？

**Comment by LinusLi** [comment]
用这个框架之前就是用官方的Fragment，没有这个问题，如果我更换数据源的时候，把id也换了，就没问题

**Comment by YoKeyword** [comment]
> 如果我更换数据源的时候，把id也换了，就没问题

指的是哪个id呢?

**Comment by LinusLi** [comment]
FragmentPagerAdapter里的函数，下面是我的重写实现
![qq 20180302141020](https://user-images.githubusercontent.com/562553/36885708-9b5695a2-1e23-11e8-9650-f07be138a4a5.png)

**Comment by LinusLi** [comment]
刚发现，换新的id也有没用的时候，哎，只要是动态的去改变ViewPager里的Fragment（当前界面），就会有问题

**Comment by LinusLi** [comment]
调试了一下框架，发现
![qq 20180302160539](https://user-images.githubusercontent.com/562553/36889897-e0469186-1e36-11e8-8dd6-8fb1f02430c2.png)

**Comment by YoKeyword** [comment]
想起来了，https://github.com/YoKeyword/Fragmentation/issues/648
你是不是和这个issue有相同的问题？ 

> 动画的原因，因为remove会触发动画，动画不结束的情况下`notify/setAdapter`，因为依旧持有对象，导致Fragment并不能立即从FM中移除

> 解决方案：
````java
public void setFragments(final ViewPager viewPager, ArrayList<Fragment> mFragmentList) {
        FragmentTransaction fragmentTransaction = mFragmentManager.beginTransaction();
        if (this.mFragmentList != null) {
            for (Fragment f : this.mFragmentList) {
                fragmentTransaction.remove(f);
            }
            fragmentTransaction.commit();
            mFragmentManager.executePendingTransactions();
        }

        this.mFragmentList = mFragmentList;
        // 这里使用viewPager.setAdapter()代替 notifyDataSetChanged()
        viewPager.postDelayed(() -> viewPager.setAdapter(YourAdapter.this), 0-300);
    }
````

> **延迟0-300ms取决于你 子Fragment的动画模式， 如果是DefaultNoAnimator，则延迟0ms，此时可以使用viewPager.post()**

**Comment by LinusLi** [comment]
还是有点不一样的，我这边的情况是：假如一开始主界面的ViewPager里有A,B,C三个Fragment，停留在C Fragment上的时候离开主界面再返回的时候，刷新了ViewPager（notifyDataChanged()），ViewPager里的界面变成了D,E,C，这个时候，C Fragment不会调用onSupportVisible，因为刷新的时候，先把C移除，这个时候执行了C的onDestroyView，mIsFirstVisible = true这个执行了，然后再加回来的时候就没调用onSupportVisible。

**Comment by LinusLi** [comment]
VisibleDelegate里有一个函数是：
