### ISSUE TITLE
start()空指针

### ISSUE THREAD

**Issue by xiaozhengxiansheng** [YoKeyword/Fragmentation#787]
在启动页fragment.startwithpop()后进去主fragment，在主fragment里start启动别的fragment时报空指针,请问是因为根布局出栈的原因吗？需要如何处理，需要再调用loadrootfragment()方法吗？

**Comment by YoKeyword** [comment]
不需要再`load`， 直接`start`即可，start会传递容器id的，应该不是这个原因

空指针Log贴下

**Comment by xiaozhengxiansheng** [comment]
java.lang.IllegalStateException: Can't find container, please call loadRootFragment() first!
在根fragment.startWithPop()进到fragmentA，在fragmentA调用start()跳转到FragmentB时报的这个错误
版本时1.2.6

**Comment by YoKeyword** [comment]
按你描述的场景，应该不会存在该问题，我在Demo中也测试了下，没问题

错误代码在[这里](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java#L339)，建议DEBUG调试下from的containerId为何空，  即startWithPop()时，根Fragment为何没有把contianerId传递过来

**Comment by wangzici** [comment]
这个和我最近遇到的情况类似，后来发现是我自己在Fragment中声明了一个SupportFragmentDelegate，但是却没有在Fragment的onCreate中手动调用这个SupportFragmentDelegate的onCreate方法导致的。SupportFragmentDelegate的onCreate方法中实现了对mContainerId的赋值操作，没调用就会导致containerId为空的问题。
