### ISSUE TITLE
使用popTo退回登录页面后，再次进入Main页面没有进行初始化

### ISSUE THREAD

**Issue by zy888802** [YoKeyword/Fragmentation#788]
执行这段代码
popTo(MainFragment.class, true, () -> {
          start(LoginFragment.newInstance());
 });
日志如下
![image](https://user-images.githubusercontent.com/16602562/36931361-f7f69444-1eee-11e8-80da-68a202585975.png)

**Comment by YoKeyword** [comment]
> 使用popTo退回登录页面后，再次进入Main页面没有进行初始化

看你的描述不应该是`popTo(LoginActivity.class, false, ()-> start(Main))`吗？

没理解你的意思

**Comment by zy888802** [comment]
我是想退出 Main页面 重新登录 ，但是登录界面已经被我关闭了

**Comment by YoKeyword** [comment]
````java
popTo(MainFragment.class, true, ()-> start(LoginFragment.newInstance()))

// LoginFragment 登录时：
start(MainFragment.newInstance())
````

PS : 确保操作的栈是正确的

**Comment by zy888802** [comment]
登陆后 我从栈视图里面只看到了LoginFragment

**Comment by YoKeyword** [comment]
是否在  `start()`时又调用了`pop()`?   应该用`startWithPop(Main)`代替

另外
````java
popTo(MainFragment.class, true, () -> {
    // start(LoginFragment.newInstance()); 建议使用下面的方法代替 －
    // v1.2.7之后 runnable会在完全出栈后执行，此时需要重新 load
    ((SuppportActivity/SupportFragment)_mActivity/getParentFragment()).loadRootFragment(Login);
});
````

**Comment by zy888802** [comment]
登录成功是 使用 startWithPop(Main) 跳转 
注销后 使用  popTo(MainFragment.class, true, () -> {
                         loadRootFragment(R.id.fl_content,LoginFragment.newInstance());
                     }); 
登录成功后 栈内还是只有 LoginFragment

**Comment by YoKeyword** [comment]
看是否有Log提示，或者起一个demo测试下，如果demo依然不行，上传到github并贴上链接

**Comment by Jiiiiiin** [comment]
我也遇到相同问题：
```java
 case POP_TO_ROOT:
                final SupportFragment finalSignInDelegate = signInDelegate;
                supportFragment.popTo(BottomDelegate.class, false, () -> {
                    LoggerProxy.e("TODO POP_TO_ROOT 拉起登录 %s", finalSignInDelegate);
                    supportFragment.start(finalSignInDelegate, ISupportFragment.SINGLETASK);
                });
                break;
```
本来想这样弹出所有页面到root，紧接着拉起登录，但是实际是pop到root，登录没有被拉起来。

**Comment by Jiiiiiin** [comment]
LoggerProxy.e("TODO POP_TO_ROOT 拉起登录 %s", finalSignInDelegate);
这一句logo输出了，但是没有拉起登录，难道我要supportFragment.popTo(BottomDelegate.class, false）-》start(loginFragment)?

**Comment by Jiiiiiin** [comment]
最后只能是这样：
```java
case POP_TO_ROOT:
//                final SupportFragment finalSignInDelegate = signInDelegate;
//                supportFragment.popTo(BottomDelegate.class, false, () -> {
//                    LoggerProxy.e("TODO POP_TO_ROOT 拉起登录 %s", finalSignInDelegate);
//                    supportFragment.start(finalSignInDelegate, ISupportFragment.SINGLETASK);
//                });

                supportFragment.popTo(BottomDelegate.class, false);
                supportFragment.start(signInDelegate, ISupportFragment.SINGLETASK);
```

会存在【闪耀】；

**Comment by YoKeyword** [comment]
@Jiiiiiin  
使用`startWithPopTo(signInDelegate, BottomDelegate.class, false)`即可

另外启动失败的原因是popTo()会先出栈，再执行runnable， 这样在执行runnable时因为已经出栈，所以FM为null， 所以报警告：`FragmentManager is null, skip the action!`

````java
   final SupportFragment finalSignInDelegate = signInDelegate;
               supportFragment.popTo(BottomDelegate.class, false, () -> {
                   // 使用还在栈内的BottomDelegate去start即可
                   BottomDelegate.start(finalSignInDelegate, ISupportFragment.SINGLETASK);
               });
````

**Comment by Jiiiiiin** [comment]
@YoKeyword thx

**Comment by Jiiiiiin** [comment]
`startWithPopTo `没有在api里面哦，建议能不能好好整整api文档哈哈，我只是个写js的，打打酱油，很难去读大神的源码咯。
提个小建议。
可以试试[QingWei-Li/docsify](https://github.com/QingWei-Li/docsify)

**Comment by YoKeyword** [comment]
Cool，感谢！  我的失误，只在[HOME](https://github.com/YoKeyword/Fragmentation/wiki#1%E7%89%B9%E6%80%A7)里标注，没有及时更新到API

**Comment by Jiiiiiin** [comment]
thx!
