### ISSUE TITLE
Fragment上打开一个新的Activity,下面的Activity闪现

### ISSUE THREAD

**Issue by shaycormac** [YoKeyword/Fragmentation#789]
# Issues Guideline
版本 1.2.5
v4 25.4.0

作者你好，我在使用该框架的过程中，有个问题，比如从A这个HomeActivity启动到B这个Activity（支持swipeback），B是单Activity+多Fragment的架构，然后在B中某个Fragment（支持swipeback的）启动一个Activity,譬如常见业务打开系统通讯录，这时候HomeActivity的内容会闪现，而当关闭系统通讯录的Activity时，HomeActivity又会短暂闪现，然后被B的顶部Fragment所遮盖。我想可能是在打开新的Activity的时候，支持滑动的这个Activity中所有的Fragment都不可见，而支持Activity滑动主题又设置为透明的有关系，可是没有想出来解决办法，希望有时间看一下，谢谢~

**Comment by YoKeyword** [comment]
嗯，你的猜想是对的，但是Fragment不可见是Activity控制的行为，我这边暂时做不了什么...

Activity用竖直动画（记得fragmentaion升级到v1.2.6+）可以在视觉上避免该问题

如果你有好的解决方式，可以提供给我哈

**Comment by shaycormac** [comment]
好的，谢谢你，我研究研究，有没有什么好的办法。
