### ISSUE TITLE
跳转到Activity的onActivityResult怎么获取结果?

### ISSUE THREAD

**Issue by weilixing00** [YoKeyword/Fragmentation#79]
现在项目用到一个第三方的拍照 跳转到指定的Activity,但是onActivityResult  和onFragmentResult都没获取到结果,该用什么样的方法?

**Comment by YoKeyword** [comment]
@weilixing00 在Fragment中，如果你使用mActivity.startActivityForResult()，那会回调Activity的onActivityResult()

如果你使用startActivityForResult()，则会回调Fragment的onActivityResult()

**Comment by weilixing00** [comment]
ok 试过了  自己粗心了 谢谢

**Comment by waterpotter** [comment]
也解决了我的问题  蟹蟹
