### ISSUE TITLE
作者你好，我有个关于fragment启动模式的疑问

### ISSUE THREAD

**Issue by yiranLWS** [YoKeyword/Fragmentation#790]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by yiranLWS** [comment]
，场景是这样的  有A,B,C三个fragment，A的启动模式是SINGLTASK  B,C没有指定启动模式   从其他fragment启动A，然后启动B，启动C，最后从C  startwithpop启动A，最后的现象是   在A按返回键显示B   再按返回键显示A   我想问A是SINGLETAS模式不应该把B弹出栈么，官网demo里有这样的场景么？用的是最新的版本

**Comment by YoKeyword** [comment]
`C.start(A.class, SINGLETASK);` 即可

Fragmentation的启动模式机制类似Activity的Intent的机制， 而非AndroidManifest.xml上的机制
