### ISSUE TITLE
滑动返回问题

### ISSUE THREAD

**Issue by ruanbaojun1105** [YoKeyword/Fragmentation#799]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version最新版
* Support-v4 version 27
* Logs
* Screenshots

![6cqtyf1c4 z7jtv c3 y8](https://user-images.githubusercontent.com/7459297/37238141-edd283e4-245a-11e8-87ca-a27f523d184a.png)

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by ruanbaojun1105** [comment]
我tm也是醉了，写了反射还不说要混淆，

**Comment by YoKeyword** [comment]
@ruanbaojun1105  
该设置可滑动区域的方法是一位热心同学的PR，我们都疏忽这个混淆了； 之前没问题 应该是大部分人没有使用该方法

抱歉，目前混淆配置目前手动添加下吧，下一版这个混淆配置会集成到库里
````
-keepclasseswithmembernames class android.support.v4.widget.ViewDragHelper{ *; }
````

**Comment by ruanbaojun1105** [comment]
@YoKeyword -dontwarn me.yokeyword.fragmentation.**
-keep class me.yokeyword.fragmentation.**{*;}
这样应该也OK

**Comment by YoKeyword** [comment]
keep fragmentation包的话应该还不行，`mEdgeSize` 是ViewDragHelper里的属性，混淆后变了，但是Framentation里的mEdgeSize是硬编码，所以应该还是找不到，需要keep `ViewDragHelper`

**Comment by ruanbaojun1105** [comment]
我看调用明明是你库里面的包，反射的也是那个类啊 怎么到android.support.v4.widget.ViewDragHelper

**Comment by ruanbaojun1105** [comment]
我这刚才按我的混淆后没报错了
