### ISSUE TITLE
Error:Failed to resolve: Fragmentation:fragmentation:unspecified

### ISSUE THREAD

**Issue by BlueYan** [YoKeyword/Fragmentation#8]
我在build.gradle导入了compile 'me.yokeyword:fragmentation:0.5.3'
却报如题的错误。怎么解决？
gradle的版本是2.10
classpath 'com.android.tools.build:gradle:2.0.0'

**Comment by BlueYan** [comment]
发现是导入了这个库 compile 'me.yokeyword:fragmentation-swipeback:0.2.6'  才报错的。单单使用
compile 'me.yokeyword:fragmentation:0.5.3' 是不会的

**Comment by YoKeyword** [comment]
@BlueYan 你要是需要用到滑动返回就只用fragmentation-swipeback就好了，里面包含fragmentation哈，不用滑动返回的特性就只用fragmentation就行啦（请用最新版0.5.4哦）

**Comment by YoKeyword** [comment]
@BlueYan 这个倒是提醒了我，下次版本会把fragmentation-swipeback单独拿出来，在使用时再去依赖Fragmentation（需要再 compile 'me.yokeyword:fragmentation:xxx'） 这样就不再就组件化啦
感谢提醒啦   :)

**Comment by YoKeyword** [comment]
@BlueYan 好啦，fragmentation-swpieback最新版0.3.0，从这个版本开始，使用滑动返回功能你就需要2个都要依赖啦
`
compile 'me.yokeyword:fragmentation:最新版' 
compile 'me.yokeyword:fragmentation-swipeback:0.3.0'
`

**Comment by BlueYan** [comment]
@YoKeyword 好的。麻烦你修改了这么多

**Comment by YoKeyword** [comment]
@BlueYan  太客气啦，还要感谢你的提醒～   :)

**Comment by BlueYan** [comment]
哈哈 那倒不用 要跟你这个大神学习学习。
