### ISSUE TITLE
fragment中调用系统相册，不走onActivityResult

### ISSUE THREAD

**Issue by GavinSong91** [YoKeyword/Fragmentation#800]
fragment中调用系统相册，不走onActivityResult

fragment中调用系统相册，不走onActivityResult

**Comment by YoKeyword** [comment]
如果你是在Fragment中直接`startActivityForResult ()`，那么会回调你Fragment内的`onActivityResult ()`；

如果是`mActivity.startActivityForResult ()`，那么会回调Activity内的`onActivityResult ()`
