### ISSUE TITLE
我在华为mate8手机上使用这个框架时发现，我的当前这个界面可以看得见下一个界面的影子，有时候清晰点我能清楚的看见下一个界面的文字，请问这个是为什么，你们有遇到过么，还是要设置什么的，求解答。

### ISSUE THREAD

**Issue by yedashen** [YoKeyword/Fragmentation#801]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by yedashen** [comment]
八百里加急快件。

**Comment by LonelyMushroom** [comment]
你主题是不是弄成透明的

**Comment by YoKeyword** [comment]
@yedashen 动画期间发生的，还是何种情况发生，  另外截图来看下

**Comment by yedashen** [comment]
看我标题栏哪里。。能看见下一个界面，

**Comment by yedashen** [comment]
![_20180314181712](https://user-images.githubusercontent.com/20877584/37396586-49e0a7a4-27b4-11e8-817f-de4c0545c01c.jpg)
![_20180314181706](https://user-images.githubusercontent.com/20877584/37396596-4ff986ce-27b4-11e8-88bb-5975c681fb75.jpg)
![_20180314181712](https://user-images.githubusercontent.com/20877584/37396606-5585e3bc-27b4-11e8-8a54-5a45c977a5b2.jpg)

**Comment by 56858752** [comment]
应该是你的start用错了，你看下你的堆栈信息。我也出现过这样的情况。是start层级结构错了。
