### ISSUE TITLE
loadRootFragment(addToBackStack:false) 后无法 replaceFragment 与 start

### ISSUE THREAD

**Issue by Qixingchen** [YoKeyword/Fragmentation#802]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version 1.3.1
* Support-v4 version 27.1.0
* Logs  `There is no Fragment in the FragmentManager, maybe you need to call loadRootFragment()!`
* Screenshots

目前的使用方法是 在 activity 上 `loadRootFragment(containerId,rootFragment,addToBackStack:false,anima:flase)` ,加载 rootFragment,后续操作都是通过 `replaceFragment(toFragment,addToBackStack)` 来操作的.  
从 1.2.4 升到 1.3.1 后,无法通过 replaceFragment 来替换 rootFragment,提示`There is no Fragment in the FragmentManager, maybe you need to call loadRootFragment()!`  
 用 loadRootFragment 来替代.但是在 rootFragment 上使用 loadRootFragment 会在新的 fragment 下方显示 rootFragment 的内容,并不是使用 replace 来替换的.  

另外在 rootFragment 上使用 start 和 startWithPop 也都报 `There is no Fragment in the FragmentManager, maybe you need to call loadRootFragment()!`

目前发现不在返回栈的 frgment 都无法进行 replace 和 start,  
https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_flow/MainActivity.java#L53  修改为 ` loadRootFragment(R.id.fl_container, HomeFragment.newInstance(), false, false);` 可以复现问题.

请问这是刻意设计的特性还是 bug 呢?

**Comment by YoKeyword** [comment]
@Qixingchen 是一次误伤的BUG，原因在[这里](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/TransactionDelegate.java#L399)，之前是从FragmentManager里找栈顶的Fragment，误伤成在回退栈里找Fragment了， 晚上修复，感谢反馈

**Comment by YoKeyword** [comment]
v1.3.2已修复
