### ISSUE TITLE
横屏状态下出现重叠

### ISSUE THREAD

**Issue by Lrony** [YoKeyword/Fragmentation#805]
<img src="https://i.loli.net/2018/03/16/5aab6294dceb3.png" height="400" width="270">
<img src="https://i.loli.net/2018/03/16/5aab6294e5f76.png" height="400" width="270">
<img src="https://i.loli.net/2018/03/16/5aab6294e6e9c.png" height="400" width="270">

**Comment by YoKeyword** [comment]
截图上来看是第二个Activity没有完全覆盖第一个Activity，倒不是Fragments的重叠，你使用的是模拟器？

**Comment by Lrony** [comment]
恩，是模拟器，Studi自带的，这么说来确实是Activity重叠了，实机我没有测过
Pixel API 26
Android8.0 x86
