### ISSUE TITLE
当首页为Tablayout+Viewpager时，从其他fragment返回时无法加载视图

### ISSUE THREAD

**Issue by VanXNF** [YoKeyword/Fragmentation#807]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

您好，您的库给我带来了很大的帮助，十分感谢您的付出。但是，与此同时也发现了一个问题：
我的app结构基本如同您demo中demo_flow的结构，我的HomeFragment是一个TabLayout+ViewPager的情况，（基本结构如同您demo中的discoverFragment），我在其中联网加载图片，当我从homeFragment跳转到其他Fragment后再按back键返回或是从侧边栏返回后就会出现无法加载的情况。
代码的话我改动了您demo_flow中的discoverFragment下加载的子页面，并将discoverFragment设为默认启动的Fragment，模仿了一下我的情况，并上传在这个仓库中：https://github.com/VanXNF/Fragmentation-issues.git
同时在demo_flow文件夹下还有我生成的apk文件与问题展示录屏，方便您查看

compileSdkVersion 27
implementation 'com.android.support:appcompat-v7:27.0.2'
implementation 'com.android.support:design:27.0.2'
implementation 'com.android.support:recyclerview-v7:27.0.2'
implementation 'com.android.support:cardview-v7:27.0.2'
implementation 'me.yokeyword:fragmentation-core:1.3.2'
implementation 'me.yokeyword:eventbus-activity-scope:1.1.0'
implementation 'org.greenrobot:eventbus:3.1.1'
implementation 'com.github.bumptech.glide:glide:4.6.1'

**Comment by YoKeyword** [comment]
@VanXNF  感谢反馈，发现是`startPopTo()`方法把Glide的`SupportRequestManagerFragment`给remove了，是一个BUG，今晚修复

**Comment by VanXNF** [comment]
十分感谢您，我后来尝试使用fresco确实没有这个问题了

**Comment by YoKeyword** [comment]
@VanXNF 已修复 v1.3.3

**Comment by VanXNF** [comment]
非常感谢您的及时修复
