### ISSUE TITLE
how to animate bottom bar to hide and show 

### ISSUE THREAD

**Issue by ahmadmiraj** [YoKeyword/Fragmentation#809]
i am working on a app and i want to animate bottom bar to hide and show on the scroll recycle view.
Can you help me out ?

**Comment by LonelyMushroom** [comment]
**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
U can use `recyclerView.addOnScrollListener()`

> **In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by ahmadmiraj** [comment]
These issue is related to Fragmentation sir @LonelyMushroom . So you should accommodate every issue of the user and atleast guide them instead of being rude !!
I have the solve the issue in case user want it, mention me in comment and i will send the code directly !

**Comment by mobilegeekkk** [comment]
@ahmadmiraj  Can you help me out to sort this animation issue ?
