### ISSUE TITLE
如何在一个View中加载多个Fragment的问题

### ISSUE THREAD

**Issue by dai-xun** [YoKeyword/Fragmentation#810]
现在做平板应用，左边是导航条，右边是一个容器rootView，rootView中会根据情况显示不同的fragment，但是我希望的是当有需要的时候才加载fragment到rootView中，而不是使用loadMultipleRootFragment一次把所有fragment全加载进去，请问有什么好的办法吗？我试过使用loadRootFragment 方法，但是这样做。两个fragment切换的时候明显是先显示了两个新老两个fragment然后过了几百毫秒旧fragment才被隐藏，请问应该如何解决

**Comment by YoKeyword** [comment]
我这边有2个方案：
1、`loadRootFragment(id,fg,false,false)`加载根Fragment，然后切换通过`replaceFragment(fg,false)`切换，这种处理方式会每次切换时都replace
2、不使用`loadMultipleRootFragment()`，该方法确实一次性加载所有Fragment，没有懒加载机制，你可以自己构建一个自己的`load`方法，达到懒加载的目的
