### ISSUE TITLE
是否可以不使用EventBus，不使用的话会带来什么问题

### ISSUE THREAD

**Issue by gmfbilu** [YoKeyword/Fragmentation#811]
是否可以不使用EventBus，不使用的话会带来什么问题
ps   因为我的项目中用了Rxjava，就是代替eventbus的，我现在想使用您的库，但是不想加eventbus

**Comment by YoKeyword** [comment]
当然可以，但最好构建一个Activity作用域的RxBus，类似[eventbus_activity_scope](https://github.com/YoKeyword/Fragmentation/tree/master/eventbus_activity_scope)

**Comment by gmfbilu** [comment]
((MainFragment) getParentFragment().getParentFragment()).start()，这种写法总感觉怪怪的，如果层级深了就更怪了，大神有没有其他的更好更优美的启动方法啊

**Comment by YoKeyword** [comment]
@gmfbilu  
* 在栈设计阶段，尽可能少的嵌套
* 使用Activity域的事件总线 控制跳转，一定要做好注释
