### ISSUE TITLE
HomeFragment另类的重叠BUG

### ISSUE THREAD

**Issue by java-programmer** [YoKeyword/Fragmentation#813]
我用了 你的微信的那个DEMO
 有个主页的HomeFragment   然后因为业务 我需要跳转到ConnectFragment   在ConnectionFragment  中 有个按钮事件  点击后会进入HomeFragment 的一个监听方法中 然后  HomeFragment 跳转到 TalkActivity里面，TalkActivity有个挂电话的事件  点击会跳转到HomeFragment 的监听方法之中 。   点击后ConnectionFragment  的布局完全挡住了HomeFragment  ，但是实际上操作的是HomeFragment  页面的元素

问题:  TalkActivity销毁的时候 进入HomeFragment ，但是 ConnectionFragment  的布局却挡在了HomeFragment 上面。 
解决方法:  在startBrotherFragment方法中  有没有目标fragment不加入返回栈的  参数？类似于activity中的FLAG_ACTIVITY_NO_HISTORY

附录:  Home跳到Connect  代码如下 : ((MainFragment)getParentFragment()).startBrotherFragment(ConnectFragmant.newInstance(true,dialUri,outCall));
Home跳到activity
  Intent intent = new Intent();    intent.setClass(_mActivity,TalkActivity,this);  _mActivity.startActivity(intent);

**Comment by YoKeyword** [comment]
打开`TalkActivity`的同时关闭`ConnectionFragment` 这样处理符合你的业务场景吗？
````java
popTo(HomeFragment.class,false,()->startActivity());
````


不加入回退栈的方法：
````java
extraTransaction()
                .dontAddToBackStack()
                .start(fragment);
````

**Comment by java-programmer** [comment]
嗯，我试下，ConnectionFragment  只是接听电话的中间一层  当按下接听键  跳转到 TalkActivity(通话层)，在通话层挂掉电话  我肯定不希望他又回到 ConnectionFragment那边, 而是回到   ConnectionFragment的上一层
