### ISSUE TITLE
加载数据loading时显示各种页面效果封装位置

### ISSUE THREAD

**Issue by zuojianjian** [YoKeyword/Fragmentation#814]
有这样一个需求，要求在数据加载出来之前不显示UI效果，像苹果那样有一个加载空白页，失败显示错误页面，我要封装这样的效果，应该在哪个位置动手修改？

**Comment by LonelyMushroom** [comment]
[StatusView](https://www.jianshu.com/p/ae23e84d414d)可以参考下这个博客.
