### ISSUE TITLE
onLazyInitView 页面闪烁

### ISSUE THREAD

**Issue by Lrony** [YoKeyword/Fragmentation#815]
使用onLazyInitView第一次加载页面会有明显闪烁现象，不知有啥好的解决方案

**Comment by Lrony** [comment]
Demo中的 知乎 可以看到这个现象

**Comment by YoKeyword** [comment]
倒不是闪烁，其实是从空白到直接出现View，显得突兀； 原因是第一次可见时才 `loadRootFragment()`

解决方式：
1、可以使用`loadRootFragment(id, fragment, true, true)` 带动画加载子Fragment，然后给子Fragment一个过渡动画
2、或者给一个Toolbar在FrameLayout下面，有了Toolbar视觉上就不会有闪烁的错觉
