### ISSUE TITLE
打开activity同时关闭当前fragment

### ISSUE THREAD

**Issue by cloudzyy** [YoKeyword/Fragmentation#819]
当打开一个activity时候，同时向关闭当前fragment 使activity关闭后回退上一级界面出现出现空白界面bug

**Comment by timmy008** [comment]
我使用的        getSupportDelegate().loadRootFragment(R.id.content_frame_layout, fragment, false, false);可以解决你说的这个问题

**Comment by cloudzyy** [comment]
我选择当先调用关闭fragment的方法，然后在onDestroy（）方法中调用启动方法。但是没有找到直接的解决方案

**Comment by cloudzyy** [comment]
我的迂回战术 是先调用fragment的关闭方法 然后在onDestroy中启动activity 但是没有找到根本解决方案

**Comment by YoKeyword** [comment]
@cloudzyy 
````java
startActivity(new Intent(_mActivity, MainActivity.class));
pop();

或

popTo(DetailFragment.class, true, new Runnable() {
                    @Override
                    public void run() {
                        _mActivity.startActivity(new Intent(_mActivity, MainActivity.class));
                    }
                });
````

**Comment by 494928699** [comment]
打开你的demo 使用
startActivity(new Intent(_mActivity, MainActivity.class));
pop(); 还是无效
