### ISSUE TITLE
仿微信交互demo与仿知乎交互的demo区别？

### ISSUE THREAD

**Issue by Destiny01** [YoKeyword/Fragmentation#82]
仿微信交互demo与仿知乎交互的demo区别？哪个用起来简单？

**Comment by YoKeyword** [comment]
@Destiny01 仿微信交互demo的栈设计，很像我们平时用Activity的方式，推荐

仿知乎的demo，比较复杂，嵌套关系较复杂，用于特定交互的场景，偏向Material Design的交互方式，比如知乎， 不是很推荐，除非变态产品经理要求 － －

**Comment by Destiny01** [comment]
好的，谢谢大神！
