### ISSUE TITLE
BroadcastReceiver中如何获得当前页面的fragment，点击后跳转到指定界面

### ISSUE THREAD

**Issue by zuojianjian** [YoKeyword/Fragmentation#820]
推送任务：接收到消息后，在receiver中处理跳转到指定界面，但是不知道怎么获取到当前的fragment

**Comment by YoKeyword** [comment]
**建议**新启动一个容器Activity来装载该Fragment， 或者栈级简单的情况下 发送事件 让对应容器Activity去装载

**Comment by SSSSunrise** [comment]
我重新搞了一下，然后获得了一个灵感，实验后，可行
API文档不是有获取当前栈顶的Fragment吗？
我们直接获取当前栈顶的Fragment，然后`start(ISupportFragment toFragment);`
就可以实现功能了
_**把广播改成内部静态类写在在MainFragment里，在里面做监听**_
第一步
`public static MainFragment mainFragment;`
第二步
`@Override`
`public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {`
`        View view = inflater.inflate(R.layout.fragment_main, container, false);`
        **mainFragment = this;**
`        return view;`
 `   }`
第三步
`mainFragment.getTopFragment().extraTransaction().start(ISupportFragment toFragment);`

**Comment by YoKeyword** [comment]
cool ， 对应类似Wechat栈结构的App是个不错的方案

**Comment by SSSSunrise** [comment]
是的，因为根据推送的使用场景来看
在任何页面都能启动一个新的页面来做推送业务功能
那就可以直接拿目前所看到的Fragment(也就是栈顶的Fragment)重新启动一个新的Fragment

**Comment by zuojianjian** [comment]
假如程序位于后台推送任务直接唤起，会报异常，onSaveInstance实例能获取到吗

**Comment by YoKeyword** [comment]
@zuojianjian 什么异常？ 用的Fragmentation版本是？
