### ISSUE TITLE
转场动画SharedElement没有效果

### ISSUE THREAD

**Issue by JasonLee0722** [YoKeyword/Fragmentation#821]
示例中的me.yokeyword.sample.demo_zhihu.ui.fragment.first.child.**FirstHomeFragment**中的108行使用了Android5.0新特性SharedElement，但是并没有效果？

**Comment by qq524787275** [comment]
+1,我也是这样问题。

**Comment by LonelyMushroom** [comment]
fragment对共享动画的支持不太友好，推荐自己实现动画或者使用activity

**Comment by liuzitong123a** [comment]
同样的问题，试了下add就不行，入栈没动画，replace没什么问题

**Comment by LonelyMushroom** [comment]
哦~忘记了，fragment的replace支持共享 add不支持

**Comment by YoKeyword** [comment]
见 #612 暂时等待google解决
