### ISSUE TITLE
参照流程式demo，用startWithPopTo以及Popto切换切面，会出现空白页面

### ISSUE THREAD

**Issue by richfuns** [YoKeyword/Fragmentation#826]
您好，作者，感谢提供这么优秀的开源库。

库版本： 1.3.3

我最近开始使用这个库遇到一个问题，参考您第一个flow Demo案例（反复对比过了，基本都一样），采用startWithPopTo以及Popto切换切面，都会出现空白页，采用的是自定义SupportFragment的方式，不知道是哪里的问题，麻烦大家看一下，谢谢

**测试Demo源码已经上传到了百度云：**
https://pan.baidu.com/s/1X-NfkX_CN4_QydQRG2l69A

`
 private Button btn1;
    private Button btn2;
    private Button btn3;
    private ISupportFragment topFragment;
    private CustomSupportFragment topHome;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        btn1 = findViewById(R.id.btn1);
        btn2 = findViewById(R.id.btn2);
        btn3 = findViewById(R.id.btn3);

        //初始化默认的Fragment
        Fragment1 fragment = findFragment(Fragment1.class);
        if (fragment == null) {
            loadRootFragment(R.id.ll_container, Fragment1.newInstance());
        }

        //首页
        btn1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                topFragment = getTopFragment();
                topHome = (CustomSupportFragment) topFragment;

                Fragment1 targetFragment=findFragment(Fragment1.class);
                start(targetFragment, SupportFragment.SINGLETASK);
            }
        });

        btn2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                topFragment = getTopFragment();
                topHome = (CustomSupportFragment) topFragment;

                Fragment2 targetFragment = findFragment(Fragment2.class);
                if (targetFragment == null) {
                    topHome.startWithPopTo(Fragment2.newInstance(), Fragment1.class, false);
                } else {
                    topHome.start(targetFragment, SupportFragment.SINGLETASK);
                }
            }
        });

        btn3.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                topFragment = getTopFragment();
                topHome = (CustomSupportFragment) topFragment;

                Fragment3 targetFragment = findFragment(Fragment3.class);
                if (targetFragment == null) {
                    topHome.startWithPopTo(Fragment3.newInstance(), Fragment1.class, false);
                } else {
                    topHome.start(targetFragment, SupportFragment.SINGLETASK);
                }
            }
        });
    }
`

**Comment by YoKeyword** [comment]
一般我们都会使用FrameLayout作为Fragment容器，原因在于该布局的特性（一层一层往上铺），这样的特性在加载多个Fragment时自然也会一个一个铺上去，Fragment的切换等也更合理
