### ISSUE TITLE
开启扫描二维码界面之前如果进过地图fragment，会在扫码界面出现部分地图重叠，请问怎么解决？

### ISSUE THREAD

**Issue by xionger0520** [YoKeyword/Fragmentation#827]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
穿透可以看到地图?   尝试给二维码Fragment的跟布局一个背景色试试

**Comment by xionger0520** [comment]
换了背景色也不行 @YoKeyword

**Comment by YoKeyword** [comment]
换背景的代码发一下看看，另外用的哪种转场动画

**Comment by haoyh** [comment]
布局文件中可以将 MapView 替换为 TextureView，使用高德地图亲测有效。
