### ISSUE TITLE
一级Fragment的onSupportVisible方法里有网络请求，二级Fragment出栈动画会卡顿

### ISSUE THREAD

**Issue by SSSSunrise** [YoKeyword/Fragmentation#828]
场景描述：
当我一级Fragment的onSupportVisible方法里做了网络请求
那么当我启动二级Fragment后，再次让二级Fragment出栈，此时一级Fragment会调用onSupportVisible方法
导致二级Fragment出栈动画有稍微的卡顿

**Comment by YoKeyword** [comment]
`onSupportVisible()` 里应该做了较重的UI操作，导致和二级Fragment出栈动画抢夺线程资源，导致卡顿

解决方案：可以延迟到动画结束后做UI操作，或者看看是否减轻UI操作

> PS：使用竖直动画，在视觉上会更流畅

**Comment by SSSSunrise** [comment]
我用了 
```
new Handler().postDelayed(() -> {
        }, 500);
```

延迟500毫秒操作   然后好多了

**Comment by YoKeyword** [comment]
@SSSSunrise  OK，或者在这种敏感的地方 使用无动画也可以解决该问题 啊哈哈

**Comment by SSSSunrise** [comment]
出栈无动画太low了，视觉体验很差，有进有出才好，嘿嘿
