### ISSUE TITLE
如果要做推送,使用广播监听,然后跳转新的Fragment,应该怎么做

### ISSUE THREAD

**Issue by SSSSunrise** [YoKeyword/Fragmentation#829]
使用场景:
需要用到推送，然后给用户提示一个页面，那么这个页面是Fragment的时候，应该如何做，广播的内部类写到哪里，在哪个Fragment层启动新的Fragment
我在MainActivity里写的广播内部类，启动和 MainFragment 同级的Fragment 会出问题

**Comment by YoKeyword** [comment]
#820

**Comment by SSSSunrise** [comment]
我已经搞定了，简单来说一下就是，我把推送监听的广播换成了内部静态类，写到了MainFragment里面
然后在MainFragment里直接  `start(ISupportFragment toFragment);`

第一步
`public static MainFragment mainFragment;`
第二步
`@Override`
    `public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {`
       ` View view = inflater.inflate(R.layout.fragment_main, container, false);`
        `mainFragment = this;`
        `return view;`
   ` }`
第三步 在内部广播类里启动
`mainFragment.start(ISupportFragment toFragment);`
