### ISSUE TITLE
你好  关于内存的问题

### ISSUE THREAD

**Issue by jttttttttttttt** [YoKeyword/Fragmentation#83]
你好  我在知乎threeFragment界面上点击进入循环fragment  点击10个  这时候内存是增加的 点击标题返回键进入 _mActivity.onBackPressed()方法  
 在
 if (mFragmentation.dispatchBackPressedEvent(activeFragment))
            return;
这里跳转到dispatchBackPressedEvent这里一直返回不了flase值   这里一直在增加内存

**Comment by YoKeyword** [comment]
不明白你的意思，你指的是内存没释放？  你点下强制GC，这部分内存会回收的...

**Comment by jttttttttttttt** [comment]
是的  这部分内存没释放   点击还是增加内存

**Comment by YoKeyword** [comment]
你强制GC下看看，我刚试过了强制GC，会回收的..~

**Comment by jttttttttttttt** [comment]
....怎么强制GC？  新手      我debug的时候一直跳不到onBackPressed里的 onBackPressedSupport();

**Comment by jttttttttttttt** [comment]
讲道理   点击返回会增加内存不应该把

**Comment by YoKeyword** [comment]
Activity返回也会增加少量内存，返回时也要创建一些对象的...
不过都是可以在下次GC时清理掉的，不用担心，  强制GC就是按下那个 小卡车 图标的按钮～

Debug应该是可以跳到onBackPressedSupport()里的， 库中里有3个demo，有些Fragment类可能有3个，它们隶属不同的包，不要把断点打错~

**Comment by jttttttttttttt** [comment]
强制GC可以减少，但是不强制GC 会在长时间保持     我想问下  android内存不足  应该不会强制回收的吧？ 再说，可以强制回收，回收之前这部分内存好像释放不了？  还有我打的断点在SupportActivity里面，就是跳不进去onBackPressedSupport();    求解

**Comment by YoKeyword** [comment]
你看下java的内存回收机制...

断点的问题，你再看下，我Fragment里打断点都可以走到，Activity的onBackPressed作为分发者必然可以走的，  参考[wiki库中的回退机制](https://github.com/YoKeyword/Fragmentation/wiki/4.-%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%8D-Back%E9%94%AE%E7%9A%84%E4%BA%8B%E4%BB%B6%E4%BC%A0%E9%80%92%E6%9C%BA%E5%88%B6)

**Comment by jttttttttttttt** [comment]
问个小白问题，  我看了垃圾回收在什么时候是机子说了算的   那就代表强制GC内存算是自动回收所有未引用的内存吧

**Comment by YoKeyword** [comment]
嗯 是的    多看看这部分 比较重要..~

**Comment by jttttttttttttt** [comment]
谢谢了  ( ▼-▼ )
