### ISSUE TITLE
在一个Activity中，有一个根布局，根布局start()一个新的Fragment包含WebView,

### ISSUE THREAD

**Issue by Sirhu173977450** [YoKeyword/Fragmentation#832]
在一个Activity中，有一个根布局，根布局start()一个新的Fragment包含WebView,在webView的setWebViewClient()监听拦截一个请求之后调用pop();会把整个Fragment栈清空，退出之后就白屏了，请问是什么原因

**Comment by YoKeyword** [comment]
你的意思是在WebviewFragment中调用`pop()`，会让所有其它Fragments都出栈？

**Comment by Jiiiiiin** [comment]
我也遇到了 不过我那个是在webview的perosess还木有跑完 用户就弹掉webview的delegate和父的delegate，再次进入任何一个webview 都白屏，只能杀掉进程

**Comment by Jiiiiiin** [comment]
https://www.zhihu.com/answer/77837954
和知乎的这个评论里面的情况类似，不过感觉是webview内核自己的坑...

**Comment by YoKeyword** [comment]
嗯对的，内核的问题，我们项目也有检测到这种情况...

**Comment by Jiiiiiin** [comment]
@YoKeyword 你们是怎么缓解的？我是做了一个webview渲染标识，然后控制‘延迟返回’，想听听大佬是怎么玩的。

**Comment by Jiiiiiin** [comment]
其实虽然不是Fragmention的问题，但是我觉得这个问题很值得讨论哎 哈哈哈哈
