### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by qzqs** [YoKeyword/Fragmentation#833]
想问下作者，如果我想在MainaActivity直接跳转其他的fragment该怎么做呢？不想像作者一样还要跳转一个MainFragment才能跳转其他的fragment，但是如果直接在MainaActivity跳转其他的fragment的话没有findChildFragment()方法，因为MainaActivity是继承SupportActivity的。

**Comment by YoKeyword** [comment]
Fragment的宿主是Activity，你说的MainActivity跳转Fragment，不管怎样该Fragment一定会有一个Activity宿主。  

直接跳的话可以参考第一个Demo，但是其本质还是在FragmentActivity栈里跳转的

MainFragment跳转是为了保证新Fragment和MainFragment在一个层级，这样后续维护会很方便

这个栈层级不是三言两语可以表述的，建议看我关于Fragment的文章理解下
