### ISSUE TITLE
FragmentManager is null, skip the action!

### ISSUE THREAD

**Issue by yuanliu666** [YoKeyword/Fragmentation#836]
* Library version
1.3.3
* Support-v4 version
27.1.0
* Logs
W/Fragmentation: FragmentManager is null, skip the action!
* Screenshots
N/A

在使用`popTo`的时候出上述Warning，popTo动作实现了但是`afterPopTransactionRunnable`没有被执行。
使用场景大致是MainFragment下,start(A),然后A里面start(B)，B要popTo(A, true, ()->{start(C)})
此外AB里面都重写了onBackPressedSupport方法：
```kotlin
  override fun onBackPressedSupport(): Boolean {
    pop()
    return true
  }
```
求解,谢谢！

**Comment by YoKeyword** [comment]
因为该层级的Fragment都出栈了，所以FM为null，再进行`start()`就会有问题（不过库应该可以处理，下个版本我看下是否可以优化）

解决方案： 使用`B.startWithPopTo(C, A, true)`

**Comment by yuanliu666** [comment]
多谢！

**Comment by YoKeyword** [comment]
看了下库很难处理， 因为popTo()里的Runnable 库是不知道的，所以不能帮你持有FM，  还是建议使用
`startWithPopTo()` 或 
````java
setFragmentAnimator(getFragmentAnimator().setExit(R.anim.h_fragment_pop_exit));
popTo();  
do事务()
````
