### ISSUE TITLE
有出现fragment队列没有移除，导致无法调用start函数

### ISSUE THREAD

**Issue by xiongxiaosong** [YoKeyword/Fragmentation#837]
![image](https://user-images.githubusercontent.com/8437008/38655703-c26b412a-3e48-11e8-9701-97fc17ba237f.png)
再项目中使用发现队列没有正确移除，无法继续调用start函数

**Comment by YoKeyword** [comment]
复现步骤是否麻烦提供下

**Comment by xiongxiaosong** [comment]
连续调用两次start，然后队列里面就会一直保留一个，后面再调用start，里面的queue就会一直往上添加了，就是连续调用两次的时候，有一个没有从队列里面移除

**Comment by xiongxiaosong** [comment]
说错了，是连续调用两次pop();

    @Override
    public boolean onBackPressedSupport() {
        pop();
        pop();
        return true;
    }

**Comment by YoKeyword** [comment]
@xiongxiaosong 还是无法复现，可否提供下联系方式，更方便沟通

**Comment by xiongxiaosong** [comment]
当栈里面只有两个Fragment的时候，连续调用两次pop就出问题了，我是在4.4的平台上发现的

**Comment by sumaro** [comment]
我这边有一个类似的问题,Activity  'A' 作为容器装在Fragment 'B' 和'C'，首先loadRootFragment(addToBackStack false)加载B,然后loadRootFragment((addToBackStack true))加载C,然后在C中发送EventBus并pop(),A收到EventBus需要加载B的一个新实例,调用loadRootFragment(addToBackStack false),A中一直显示的 都是B的第一个实例,并且在B中调用replaceFragment不再生效.我的解决办法是在C中不再调用pop,其它不变,能正常加载B的第二个实例

**Comment by YoKeyword** [comment]
@sumaro 
环境：v1.3.3
复现方式：
A.loadRoot(B,false) -> 
A.loadRoot(C,true) -> 
C中操作A.loadRoot(B,false) + C.pop()

结果： A中存在2个B实例，  无法复现

**Comment by YoKeyword** [comment]
@xiongxiaosong 4.4平台还是无法复现 [捂脸]， 留下联系方式吧，我们沟通下哈

**Comment by YoKeyword** [comment]
v1.3.6试试
