### ISSUE TITLE
大神，关于使用透明状态栏后SwipeBackActivty/Fragment兼容性问题

### ISSUE THREAD

**Issue by jeffer0323** [YoKeyword/Fragmentation#84]
4.4 透明状态栏 decorView.getChildAt(0)获取到的是StatusBar所在的View，所以会报类型转换异常
5.0+ 可以通过代码设置StatusBar颜色， decorView.getChildAt(0)获取到的也就是activity/fragment所在的根布局（ViewGroup）

以下是我暂时的解决方式，希望大神能给出更好的方案
 if(Build.VERSION.SDK_INT == Build.VERSION_CODES.KITKAT){
            decorChild =  (ViewGroup)decor.getChildAt(1);
        }else{
            decorChild =  (ViewGroup)decor.getChildAt(0);
       }

**Comment by YoKeyword** [comment]
库中这部分代码  出自 [SwipeBackLayout](https://github.com/ikew0ng/SwipeBackLayout)库， 倒不清楚你的4.4版本的状态栏是如何实现的，是hack方式还是科学方式？  因为我还没遇到你说的这个问题~

**Comment by jeffer0323** [comment]
hack  唉

**Comment by YoKeyword** [comment]
要么考虑用科学的方式搞定这个问题，要么4.4就不适配状态栏...
