### ISSUE TITLE
平板上的fragment切换

### ISSUE THREAD

**Issue by lilongfeng2010** [YoKeyword/Fragmentation#841]
请教一下，如果在平板上左侧是导航栏，右侧是空白页面，点击左侧导航栏，切换右侧fragment。有个难点是右侧的fragment需要很多层级，点击按钮可能进入十几层页面。但是我这个时候点击左侧的导航栏，还必须切换到其他的页面，切换回来还得显示刚才进入的第十几层页面。这个时候需要判断的逻辑好像特别复杂。能加大神的qq或者qq群吗？

**Comment by YoKeyword** [comment]
和第三个Demo 知乎栈设计一样，  左侧导航栏当作Bottombar的几个菜单，  具体Tab(右侧Fragment)是一个Fragment容器， Tab内跳转的几十个页面都是该容器内的子Fragment

**Comment by lilongfeng2010** [comment]
多谢啊，我使用一下看看。太谢谢啦

**Comment by gxh-apologize** [comment]
你好，我遇到了跟你同样的问题，想问下你是怎么解决的，左侧是个列表，每个item对应自己的fragment，是用loadMultipleRootFragment一次都加载进去吗？我这边有十几个item呢.....
