### ISSUE TITLE
如何让顶部的出栈按钮拥有和返回键一样的属性

### ISSUE THREAD

**Issue by SSSSunrise** [YoKeyword/Fragmentation#843]
如题
就是自定义返回键的功能，和系统回退键的功能一样
能否做到

**Comment by xshengcn** [comment]
`
_mActivity.onBackPressed()
`

**Comment by SSSSunrise** [comment]
这个不行啊，当页面有弹起输入法的是时候，调用这个不会先隐藏输入法，而是直接出栈Fragment，系统的返回键是有输入法先隐藏输入法

**Comment by summertravel** [comment]
可以判断输入法是否弹起来

**Comment by lazy-play** [comment]
因为Fragment被出栈时，不会自动隐藏软键盘，以及弹出软键盘有些麻烦，故提供下面2个方法

// 隐藏软键盘 一般用在hide时
hideSoftInput();

// 显示软键盘，调用该方法后，会在onPause时自动隐藏软键盘
showSoftInput(View view);
