### ISSUE TITLE
有没有类似ActivityManager这样的fragment管理器啊

### ISSUE THREAD

**Issue by gmfbilu** [YoKeyword/Fragmentation#847]
小公司设计上很随意，开发平板项目，整个项目是单Activity多Fragment。假如有一个功能是退出登录，这个功能的层次有点深，要跳转到LoginFragment中去，同时要把其他Fragment关闭，这种情况下该怎么处理呢，我是小白，如果问的问题很蠢，请谅解

**Comment by YoKeyword** [comment]
建议Wechat栈结构，此时只要用 startWithPopTo(LoginFragment, rootFragment.class , true)
