### ISSUE TITLE
输入法压缩Fragment布局

### ISSUE THREAD

**Issue by hope320** [YoKeyword/Fragmentation#848]
# Issues Guideline
大神好，我在项目中遇到了一个问题：
输入法弹出状态下进行返回操作（FragmentActivity）的onBackPressed（），或者切换到其他fragment的时候，就会出现MainFragment布局被压缩的情况，[效果](https://i.imgur.com/K8bQb30.png)。此时再进入或者回退到其他页面的时候都是这个被压缩的尺寸。
我在Activity中设置了  android:windowSoftInputMode="adjustPan|stateAlwaysHidden" 和 android:configChanges="keyboardHidden|orientation|screenSize"。在问题Fragment界面的onDestoryView()里也调用了hideSoft()和_mActivity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN);
        hideSoftInput();
想问下大神，可能会是什么原因？

**Comment by YoKeyword** [comment]
Android软键盘是个小坑，建议搜索相关资料使用 相应布局＋softInputMode来调整达到预期效果， 需要注意的是 建议在Fragment上动态设置`_mActivity.getWindow().setSoftInputMode`

**Comment by hope320** [comment]
好的，谢谢大佬
