### ISSUE TITLE
从v1.1.0升级1.3.3后回退fragment异常

### ISSUE THREAD

**Issue by ywp0919** [YoKeyword/Fragmentation#849]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version     1.3.3
* Support-v4 version     27.1.1
* Logs 
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**
去年就在用这个了，但是现在项目用的是1.1.0版本的，现在想升级1.3.3版本，看了下demo和wiki，用法上没有什么改变，但是在项目里面出现了问题，start fragment的时候正常，但是回退fragment的时候就会异常了，不管是pop还是按返回键都会报异常，麻烦大佬给分析一下，谢谢

CatchCrash : java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    ║ 	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
    ║ 	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
    ║ 	at android.support.v4.app.FragmentManagerImpl.popBackStack(FragmentManager.java:791)

	at android.support.v4.app.FragmentationMagician$1.run(FragmentationMagician.java:87)
    ║ 	at android.support.v4.app.FragmentationMagician.hookStateSaved(FragmentationMagician.java:186)
    ║ 	at android.support.v4.app.FragmentationMagician.popBackStackAllowingStateLoss(FragmentationMagician.java:84)
    ║ 	at me.yokeyword.fragmentation.TransactionDelegate$9.run(TransactionDelegate.java:251)
    ║ 	at me.yokeyword.fragmentation.queue.ActionQueue.handleAction(ActionQueue.java:53)
    ║ 	at me.yokeyword.fragmentation.queue.ActionQueue.access$200(ActionQueue.java:17)
    ║ 	at me.yokeyword.fragmentation.queue.ActionQueue$2.run(ActionQueue.java:69)

**Comment by ywp0919** [comment]
找到这个异常发生的原因了，因为在baseFragment的onDestroy里面使用了 popChild()这个方法，现在这个方法不能随意用了么？之前是想用这个来pop掉一些viewPager之类的fragment。。

**Comment by YoKeyword** [comment]
相比1.1.x版本，高版本现在内置了队列机制，事务会排队执行，这样可以解决极端情况下（多点操作、频繁事务）不稳定的情况， 所以在`onDestroy()`里`popChild()`的话， pop的时机其实因为入队，会在Fragment真正销毁时执行，这样就会出现问题， 建议更改下实现方案哈

**Comment by ywp0919** [comment]
嗯，已处理掉了，暂时没有发现在别的问题了
