### ISSUE TITLE
在逐步的搭建项目中报了一个错，log也没有

### ISSUE THREAD

**Issue by adminLiu-s** [YoKeyword/Fragmentation#85]
主界面4个tab对应4个fragment，现在一进主页就报这个错，toast弹出的：

Attempt to invoke virtual method 'java.util.List android support.v4.app.FragmentManager.getFragments()' on a null object reference

**Comment by YoKeyword** [comment]
FragmentManager这个对象为空了...  检查下这个对象～

**Comment by adminLiu-s** [comment]
问题解决了  原因是splashfragment中执行了两次startWithPop...导致第二次取值为空,谢谢大神
