### ISSUE TITLE
页面保活问题

### ISSUE THREAD

**Issue by douya40** [YoKeyword/Fragmentation#851]
目前公司做一个及时通讯项目，发现这个框架使用的app在点击home键的时候。过一会再去打开APP发现页面被初始化了，之前页面被回到主页面了。没有保存之前的页面状态，对比微信QQ都有保存，不知道这个框架怎么调整能同步上需求

**Comment by LonelyMushroom** [comment]
开发者选项-》不保留应用，进行调试，像这种一般涉及到数据保存和view位置的数据保存之类的 
你可以
```
onCreate{
if (savedInstanceState != null) {
// 取出数据
}
}

onSaveInstanceState{
// 保存数据
}
```
