### ISSUE TITLE
contentFragment.replaceFragment(fragment, false);

### ISSUE THREAD

**Issue by gmfbilu** [YoKeyword/Fragmentation#852]
在您的demo中有一个页面是左侧RecrclerView的MenuFragment，右侧是一个内容的Fragment,左侧每次切换的时候都是新建，这样做就无法保存右侧相应Fragment的状态了，请问有什么好的办法吗

**Comment by YoKeyword** [comment]
加入回退栈 使用show hide 可保存， 可参考WechatDemo方式（把侧滑控件 当作 底部Bottombar）
