### ISSUE TITLE
Fragment数据刷新的问题

### ISSUE THREAD

**Issue by deanxd** [YoKeyword/Fragmentation#857]
# Issues Guideline
App首页是一个 MainActivity ， 然后loadRootFragment 一个MainFragment,  在MainFragment中loadMultipleRootFragment 多个Fragment显示不同的tab页面， 现在出现一个问题，就是在首页startActivity 进入其他Activity 修改数据后， 返回MainActivity 时， MainActivity中这些tab Fragment 更新界面异常，比如在tab fragment中，使用View.setVisiable()方法，无效

Following information can help us to resolve the issue faster.

* Library version
me.yokeyword:fragmentation:1.3.3

* Support-v4 version
 '27.0.2'

* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
避免 直接操作Fragment的根View， 因为show/hide等操作，Fragment内部也会操作该View，很有可能会被其替换掉， 建议使用事务来操作
