### ISSUE TITLE
startWithPop有白屏

### ISSUE THREAD

**Issue by LinkZhang** [YoKeyword/Fragmentation#86]
与微信demo类似，只不过增加了一个SplashFragment
在MainActivity中使用loadRootFragment(SplashFragment.newInstance())
SplashFragment使用startWithPop方法启动MainFragment会有白屏一闪而过

**Comment by YoKeyword** [comment]
startWithPop内部实现是这样的，假设A startWithPop B，  A先出栈，B再进栈，如果你不进行任何处理A和B的出栈和进栈动画显示是不正常的（你可以自己实现下看看），之所以动画看起来正常是因为A之前的那个FG会暂时显示A的界面，整个动画结束后，会复原，这样就达到一个很正常的start并且关闭当前FG的动画效果

而你的场景是Splash之前是没有FG的，Splash本身就是根FG，所以startWithPop会空白一下，这个比较难搞定，考虑到实际场景中，这个需求不是很多，也暂时不打算特别的兼容这个问题。

2个方案解决该问题：
1、SplashFragment防止在单独的Activity
2、SplashFragment的popExit动画设置为 持续时间为B进栈动画的时长 行为上不进行任何渐变移动 即可

**Comment by LinkZhang** [comment]
@YoKeyword 嗯，考虑放在单独的Activity
