### ISSUE TITLE
个数不确定的fragment，这时候怎么写？

### ISSUE THREAD

**Issue by shiyuexun** [YoKeyword/Fragmentation#865]
public void loadMultipleRootFragment(int containerId, int showPosition, ISupportFragment... toFragments) {
        mDelegate.loadMultipleRootFragment(containerId, showPosition, toFragments);
    }

这个方法为什么写成变长参数呢？当个数不确定的时候，怎么调用？如果个数是动态的

**Comment by YoKeyword** [comment]
`ISupportFragment... toFragments`接收一个数组， 或者 A,B,C,... 这样的参数格式；

你说的动态是指什么场景呢？

**Comment by YoKeyword** [comment]
可以接收 SupportFragment[]  这种数组， 如果是List可以先转成 []

**Comment by shiyuexun** [comment]
我写的数组就报错，这个参数是变长数组啊， A,B,C,... ，没有见接受数组的方法啊

**Comment by shiyuexun** [comment]
val array = arrayOf(mFragments[0],mFragments[1],mFragments[2])
            loadMultipleRootFragment(R.id.fl, 0, mFragments[0], mFragments[1], mFragments[2])

            loadMultipleRootFragment(R.id.fl, o,array)
第二行可以，第三行就报错，参数不对

**Comment by YoKeyword** [comment]
![image](https://user-images.githubusercontent.com/9691640/40160711-0a072400-59e1-11e8-981e-e79baf4e0375.png)

java代码如上， kotlin的话`arrayOf()`返回的可能是List， 需要查下如何转成Java的 数组[]

**Comment by Abvatous** [comment]
@YoKeyword @shiyuexun 大神你们好~是这样子的，我想问下：
现在我有一个业务的需求:mBottomBar 在初始化的时候loadMultipleRootFragment已经填充了对应的Fragment和icon了，但是后面我需要动态地将原来的icon 新的Fragment绑定,请问可以吗？
