### ISSUE TITLE
判断是否登陆，如何使用frag?

### ISSUE THREAD

**Issue by stoneLee81** [YoKeyword/Fragmentation#867]
请教下，这种情况该如何使用？
我现在有在一个activity里使用了3个buttomtab，每个tab对应一个fragment, 在用户的tab这有个判断，如果用户没登陆，切换到用户中心是提示的登陆fragment,如果登陆了就是用户的frag,这个该怎么使用？

**Comment by stoneLee81** [comment]
大致逻辑是，activity里面initview
if (savedInstanceState == null) {
            UsersDTO user = new UsersDTO();user.setId(DataManager.getPreferences().getLong(C.Type.Prefer.APP_USERID));
            user = (UsersDTO)CacheUtils.getInstance().getSerializable(String.valueOf(user.getId()));
            mFragments[FIRST] = PaletteFragment.newInstance(wrapped1);
            mFragments[SECOND] = DayPlanFragment.newInstance(wrapped2);
            if(user == null) {
                mFragments[THIRD] = LoginFragment.newInstance(Crital.builder().build());
            }else {
                mFragments[THIRD] = ProfileTestFragment.newInstance(wrapped3);
            }
        } else {
            mFragments[FIRST] = findFragment(PaletteFragment.class);
            mFragments[SECOND] = findFragment(DayPlanFragment.class);
            if(user == null) {
                mFragments[THIRD] = findFragment(LoginFragment.class);
            }else {
                mFragments[THIRD] = findFragment(ProfileTestFragment.class);
            }
        }
判断，如果用户未登陆，家在loginFragment,然后在登陆的presenter里，登陆成功，发送消息给这个activity,
@Override
    public void receiveEvent(Event event) {
        switch (event.getCode()) {
            case C.Type.EVENT.ACTION.DESTROY_LOGIN:
                startWithPop(LoginFragment.newInstance(Crital.builder().build()));
                mFragments[THIRD] = ProfileTestFragment.newInstance(wrapped3);
                break;
        }
    }
登陆的fragment是没了，但是花屏，请问，这种情况该怎么处理，多谢

**Comment by YoKeyword** [comment]
**建议的栈层级，这样的设计会很简单实现你的场景**
- LoginFragment
- MainFragment
      - TabAFragment
      - TabBFragment
      - TabCFragment

**Comment by YoKeyword** [comment]
>当我点击tabA，tabB时部分操作不会触发login的提醒，部分会触发login提醒，如果点击tabC一定会触发login的提醒； 这个该如何操作，在所有的逻辑里面增加login的判断，如果没登陆，打开loginFragment,是么？

给MainFragment一个监听事件， 在收到登录信号时，`Main.start(Login)`即可； 不同Fragment需要跳转时 发送该信号即可

----
> 登陆成功了，是否用消息广播提醒重要的界面做相关的状态/数据更新？

一般来说 建议使用观察者模式来处理该问题

**Comment by stoneLee81** [comment]
可以了，多谢
