### ISSUE TITLE
在子fragment中 重写onBackPressedSupport()按下回调的时候未回调这个方法，请问大神怎么回事

### ISSUE THREAD

**Issue by PeanutZhang** [YoKeyword/Fragmentation#868]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version 1.3.3
* Support-v4 version 
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

用重写 ISupportActivity 和ISupportFragment  集成的， 按下返回键时在fragment没走onBackPressedSupport 方法

   @Override
    public boolean onBackPressedSupport() {
        EzpUtil.Log("ezp----> onBackPressedSupport is gongi");
        if(mKeyboard_util !=null){
            if(mKeyboard_util.isShow()){
                mKeyboard_util.hideKeyboard();
            }
        }
        return super.onBackPressedSupport();
    }

**Comment by qianshengta** [comment]
你知道问题出在哪了吗？我的也是这样？重写了Fragment中的onBackPressedSupport，直接返回true，吧事件截断掉。但是结果还是会传到Acrivity里去
