### ISSUE TITLE
如何标记启动的fragment 

### ISSUE THREAD

**Issue by zuojianjian** [YoKeyword/Fragmentation#869]
场景：多个推送来临，点击第一个启动一个推送对应的fragment，点击其他都是如此每次都启动一个新的fragment，如此产生问题会产生多个返回推送界面，我的想法统一给推送过来启动的fragment做一个标记，点击推送时获取栈顶的fragment标记是否是推送启动，如果是则替换，如果不是则启动新的，如何解决？

**Comment by YoKeyword** [comment]
比较推荐的做法是：推送Fragment都放到 单独的容器Activity里，  只管理这个容器就好了
