### ISSUE TITLE
fragment使用过程中白屏

### ISSUE THREAD

**Issue by ronniesun** [YoKeyword/Fragmentation#87]
@YoKeyword 你好，看了你的文章写得非常不错。
我暂时还没用你的lib，我说下我现在遇到的问题。

类似大多数app底部五个tab，点击tab切换；现在遇到的问题是其中一个tab对应的fragment可能会占用很高的内存（个人怀疑内存问题），然后当我切换到最后一个tab时（该tab第一次加载），出现白屏，不知道这个是什么原因引起的，请帮分析一下。

**Comment by YoKeyword** [comment]
这标题起的...还以为库的BUG呢～

内存占用问题，你通过内存监控来综合观察下，以及该Fragment是否有大量图片等资源，有的话需要对图片缓存进行管理；

白屏问题，因为不清楚你的用法，很难推测什么原因。。。不过有个建议是可以用懒加载，第一次把5个Fragment都加载进来，但是数据等占资源占内存的操作走懒加载，在第一次选中该Tab时，再初始化这些数据...

**Comment by ronniesun** [comment]
@YoKeyword  就您这边的经验来看，fragment都有哪些情况会引发白屏。

另外建议您写一篇  fragment oncreateview 加载view的写法，还有网上一直写的
protected void breakParent() {
        ViewGroup parent = (ViewGroup) view.getParent();
        if (parent != null) {
            parent.removeView(view);
        }
    }

**Comment by YoKeyword** [comment]
@ronniesun 
白屏大部分情况下说Fragment的栈视图 异常了～  你可以通过FragmentManager.getFragments()来观察其List结构里的Fragment顺序 :)

加载View我并没有特别注意有什么问题，一直是标准写法的~

**Comment by ronniesun** [comment]
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        if (view == null) {
            view = inflater.inflate(R.layout.fragment_circle, container, false);
            
            initUI();
            initData();
            
        }
        breakParent();
        return view;
    }

这是我的写法，您看下对吗？你是否用到breakParent

**Comment by ronniesun** [comment]
因为 多个fragment 切换时重复执行onCreateView

**Comment by YoKeyword** [comment]
@ronniesun 
没有使用， 多个切换会重复执行onCreateView？  你的切换是使用replace的吧
你把view作为全局变量，并且判断了view==null，这样是为了下次进来时不重新创建视图？ 不说这是可能引起白屏的原因...既然这样使用了，为何不用add show/hide方式...

**Comment by ronniesun** [comment]
现在是使用的 add hide show，不过生命周期打印的log来看，确实走了多次onCreateView；您那边的onCreateView不会判断 view==null是吗，如果内存过大，fragment里的view不会被销毁吗，如果销毁您怎么再创建，我是打算保存之前view停留的位置，所以不是每次onCreateView都对view重新赋值

**Comment by YoKeyword** [comment]
Fragment的view是个强引用啊，不涉及到内存不足被销毁；你遇到的可能是“页面重启”的场景吧，建议你从标准写法的Demo测试起，一步步看各种情况的Fragment状态，通过getFragments来监控Fragment栈内的视图

**Comment by ronniesun** [comment]
谢谢

**Comment by ronniesun** [comment]
如果不做 initLazyView 直接在 oncreateview赋值 也可以对吗

**Comment by YoKeyword** [comment]
是的，当然可以，主页一般情况下的onCreateView只会走一次（show/hide的方式下），不过懒加载还是很重要的，建议做下处理 :)

**Comment by ronniesun** [comment]
我这边处理方式是这样的，当点击底部某个tab才去加载，而不是用viewpager去预加载，另外在main里的布局<Fragment>，也可以吧

**Comment by YoKeyword** [comment]
嗯？！  我好像知道你为何会重复调用onCreateView了... 你用了ViewPager.... VP默认预加载左右相邻的一个Fragment，如果你没设置setOffscreenPageLimit的话；
VP的特性就是移动到不相邻的Fragment会走onCreateView（即使这个Fragment之前被create了），你取看下ViewPager和Fragment时搭配使用时的一些细节问题～ 可以搜索下，Viewpager的懒加载实现和正常show/hide的不同的

**Comment by ronniesun** [comment]
我没用 Viewpager，给您看下我的代码

**Comment by ronniesun** [comment]
private void changeTab(int tabId) {
        MainBottomMenuManager.getInstract().setMainBottomMenu(tabId);
        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
        hideFragments(transaction); // 隐藏所有的，下面的case在show当前的
        switch (tabId) {
            case R.id.rl1: {
                imageview1.setSelected(true);
                imageview2.setSelected(false);
                imageview3.setSelected(false);
                imageview4.setSelected(false);

                if (mFragmentMsg == null) {
                    mFragmentMsg = new FragmentMsg();
                    transaction.add(R.id.content, mFragmentMsg);
                } else {
                    transaction.show(mFragmentMsg);
                }
            }
            break;
。。。。。。。。。。

transaction.commitAllowingStateLoss();

就是点击tab加载所需要的fragment

**Comment by ronniesun** [comment]
还有我的fragment是new出来，并不是您那种单例模式

**Comment by YoKeyword** [comment]
建议你封装BottomBar... 这样控制切换很不优雅, 可以参考下我demo中BottomBar的封装...
Fragment的创建随便的，newInstance的好处是如果有需要的传参，调用者无需关心Argument的Key是什么，只要传value即可

**Comment by ronniesun** [comment]
谢谢

**Comment by iFarSeer** [comment]
@YoKeyword 你白屏的问题最后有分析到原因吗？
