### ISSUE TITLE
有谁知道怎么制定删除frg吗

### ISSUE THREAD

**Issue by edcedc** [YoKeyword/Fragmentation#870]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by edcedc** [comment]
怎么指定删除某个已经在栈内的frg

**Comment by LonelyMushroom** [comment]
fragment栈层管理非常严格，只能一层层pop 不能指定其中一个删除

**Comment by YoKeyword** [comment]
A->B->C->D，  比如想关闭B， 那么建议在关闭C时，使用`popTo(B,true)`代替`pop()`
