### ISSUE TITLE
有没人回答下怎么指定关闭栈内frg呀

### ISSUE THREAD

**Issue by edcedc** [YoKeyword/Fragmentation#871]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
`pop()`, 'popTo()' 详情可参考Demo或[wiki](https://github.com/YoKeyword/Fragmentation/wiki)
