### ISSUE TITLE
onEnterAnimationEnd回调

### ISSUE THREAD

**Issue by 330676687** [YoKeyword/Fragmentation#875]
sdk从1.2.7更新到1.3.0及以上版本，
通过转场动画
extraTransaction()
   .setCustomAnimations(targetFragmentEnter, currentFragmentPopExit, currentFragmentPopEnter, targetFragmentExit)
   .start(targetFragment);
跳转的界面，不走onEnterAnimationEnd回调
低于1.3.0版本没问题

**Comment by YoKeyword** [comment]
感谢反馈！！  稍后看下

**Comment by Jhanay** [comment]
大佬什么时候提交版本，现在用onLazyInitView初始化复杂UI，有点卡顿
if (savedInstanceState != null
            || mRootStatus == STATUS_ROOT_ANIM_DISABLE
            || (mFragment.getTag() != null && mFragment.getTag().startsWith("android:switcher:"))
            || (mReplaceMode && !mFirstCreateView)) {
            notifyEnterAnimEnd();
        } else if (mCustomEnterAnim != Integer.MIN_VALUE) {
            fixAnimationListener(mCustomEnterAnim == 0 ?
                mAnimHelper.getNoneAnim()
                : AnimationUtils.loadAnimation(_mActivity, mCustomEnterAnim));
        }

**Comment by YoKeyword** [comment]
@Jhanay  预计周末提交新版本

如果你的Fragment是`start`进来的，推荐在`onEnterAnimEnd()`中初始化视图和逻辑

**Comment by YoKeyword** [comment]
已修复 v1.3.5，源自这个[commit](https://github.com/YoKeyword/Fragmentation/commit/59b649f10da0a1253bf38c3f64d5771348539919#diff-54afdb21635223656b63ef24b8a22829L176)的误删除 :)
