### ISSUE TITLE
ViewPager+SupportFragment 使用时，延迟加载异常

### ISSUE THREAD

**Issue by KevinChang007** [YoKeyword/Fragmentation#876]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version ：27.1.0
* Support-v4 version：27.1.0
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

在me.yokeyword.fragmentation.helper.internal.VisibleDelegate#dispatchSupportVisible() 中:
if (visible) {
            if (checkAddState()) {
                return;
            }
            mSupportF.onSupportVisible();
            if (mIsFirstVisible) {
                mIsFirstVisible = false;
                mSupportF.onLazyInitView(mSaveInstanceState);
            }
            dispatchChild(true);
 } 
其中，onSupportVisible()函数的调用早于onLazyInitView(),这样会造成在onLazyInitView() 初始化VIew的时候，在onSupportVisible()中提前不能进行数据异步加载。

 能否把onSupportVisible()放在onLazyInitView(mSaveInstanceState)之后？

谢谢~

**Comment by YoKeyword** [comment]
解决方案1：添加一个全局变量`isLazyInited`, `onLazyInitView()`中设置为true，  在`onSupportVisible()`中判断该变量为true则直接return， 否则做你的逻辑

解决方案2：不使用`onLazyInitView()`，第一次走`onSupportVisible()`即代表`onLazyInitView()`
