### ISSUE TITLE
使用Drawerlayout做侧边栏，应该用loadRootFragment还是loadMultipleRootFragment？

### ISSUE THREAD

**Issue by Ayanokouji-Kenn** [YoKeyword/Fragmentation#878]
怎么觉得用哪个都不太合适呢，还是loadRootFragment调用两遍？一次加载主页面，一次加载侧边栏的fragment？
还有就是按返回键能走onBackPressedSupport,也能正常pop。但是手动调用onBackPressedSupport为啥没反应呢

**Comment by YoKeyword** [comment]
看业务需求了， 大多数会用`loadMultipleRootFragment()` 因为可以保存其它Tab的状态
