### ISSUE TITLE
startWithPop B 页面跳转到C时，顶部会闪现A页面，然后才到C页面

### ISSUE THREAD

**Issue by AlexZQS** [YoKeyword/Fragmentation#879]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by AlexZQS** [comment]
看了下，把fitsSystemWindows 去掉就好了，但是去掉了，沉浸式就无法实现了

**Comment by YoKeyword** [comment]
Demo中也有类似的场景，并且也有沉浸式，看下是否有哪里冲突的地方，  或者使用三方库来实现沉浸式

比如[ImmersionBar](https://github.com/gyf-dev/ImmersionBar)或[StatusBarUtil](https://github.com/laobie/StatusBarUtil)
