### ISSUE TITLE
up,我的主页有4个fragment,我想知道第一个fragment页面的可见，不可见状态有什么好的方案吗？

### ISSUE THREAD

**Issue by galileolvpo** [YoKeyword/Fragmentation#88]
onHiddenChanged 这个方法，在切换这4个fragment的时候会被调用
但是在第一个fragment中startFragment跳转到别的页面，这个方法就不会被调用了
因为用的都是一个activity,所以 onResume,onPause这些方法就不起作用了。。
up,怎么知道这个页面当前的可见状态？？

**Comment by YoKeyword** [comment]
是这样的, A start B是必然回调A的onHiddenChanged()的；
如果发现没回调，肯定你没回调的Fragment不是A，比如是A内ViewPager里的一个子Fragment...但是A是必然会被回调的。

解决的办法，建议通过EventBus在A的onHiddenChanged()里通知子Fragment ～ 这也是嵌套Fragment比较复杂的一个点～

**Comment by galileolvpo** [comment]
嗯，没有回调的fragment的确不是A,
你一说，我想起来A中用的是RxBus.getDefault().post(new StartBrotherEvent());，所以onHidden没有被调用~多谢up！
