### ISSUE TITLE
华为系列手机出现的问题

### ISSUE THREAD

**Issue by mutoujun** [YoKeyword/Fragmentation#887]
当**windowIsTranslucent**设置为true时，华为手机在app切换到多任务窗口时会闪出桌面图标然后再显示任务列表

**Comment by YoKeyword** [comment]
最底部的Activity不要设置透明

windowIsTranslucent的侧滑机制不是很好，如果追求完美建议[这种方案](https://github.com/XBeats/and_swipeback)， 但据说在一些ROM上有点问题

**Comment by mutoujun** [comment]
蟹蟹大神
