### ISSUE TITLE
showSoftInput not working

### ISSUE THREAD

**Issue by CC-LU** [YoKeyword/Fragmentation#888]
Library version ：1.3.3
Support-v4 version：27.1.1

我在ISupportFragment的Fragment中
在View onCreateView()中調用showSoftInput(View view);無法顯示軟鍵盤
試著在onEnterAnimationEnd中使用也是沒顯示

後來發現在根Fragment中調用getActivity().getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_VISIBLE);
可以顯示軟鍵盤
但是除了根Fragment之外的Fragment調用一樣的方法卻無法顯示

請問是哪裡出問題?
謝謝

**Comment by YoKeyword** [comment]
参考下[Demo](https://github.com/YoKeyword/Fragmentation/blob/master/demo/src/main/java/me/yokeyword/sample/demo_flow/ui/fragment/account/RegisterFragment.java#L61)， 排查下相关设置

**Comment by CC-LU** [comment]
可以成功運作
雖然onPause时不會自动隐藏软键盘
謝謝

**Comment by YoKeyword** [comment]
可以在`onSupportInvisble()`里代码指定隐藏
