### ISSUE TITLE
loadMultipleRootFragment后能不能动态切换其中一个Fragment

### ISSUE THREAD

**Issue by bbiii** [YoKeyword/Fragmentation#889]
目前主页loadMultipleRootFragment中有4个页面.项目的需求是打开后根据接口切换第一个Fragment,即默认是oldFragment,如果接口返回为true则是newFragment.
现在如果loadMultipleRootFragment已经加载好了oldFragment,如果我想把第一个fragment切换成newFragment有没有什么方法提供呢?我重新调用loadMultipleRootFragment的话会造成oldFragment和newFragment都显示的错误

**Comment by weiaiCmeng** [comment]
同问，没法在切换回来了

**Comment by LonelyMushroom** [comment]
现在的情况是true为AFg,false为BFg.
那么我们可以写一个无逻辑的CFg,这个Fg的作用就是用来replace
A,B的作用.在主页调用接口过后,进行调用CFg对应的方法去replace,A和B.

**Comment by YoKeyword** [comment]
`loadMultipleRootFragment()` 这个是同时加载多个Fragment，因为这多个Fragment并不加入回退栈，所有是可以通过replace来替换，但是因为Fragment是栈，所以只能从栈顶来替换Fragment

如果向替换栈中任意Fragment，采用 @LonelyMushroom 提供的方案：
```java
- A
- B
- C
````
的栈结构换成
```java
- A
- BContainer
   - B
   - ReplaceB
- C
````

**Comment by YoKeyword** [comment]
@OnlyTerminator  可以使用`startWithPop()`

**Comment by zhupengxiang** [comment]
我现在是在mainFragament里面动态替换两个fragment   调用startWithPopTo或者replacefragment后导致替换的fragment直接覆盖到主界面了    导致主界面切换tab全是被替换的fragment  请问怎么解决

![image](https://user-images.githubusercontent.com/17894209/60003413-33869280-969d-11e9-9f9c-610ec4d2542b.png)

**Comment by SanChunAndrroid** [comment]
replacefragment会变空白

**Comment by zhupengxiang** [comment]
@SanChunAndrroid   兄弟威武   库不维护了

**Comment by JantHsueh** [comment]
@SanChunAndrroid  可以详细描述一下你的问题吗

@zhupengxiang  这个库，我在继续维护，已经发布了新版 https://github.com/YoKeyword/Fragmentation/issues/1237
