### ISSUE TITLE
SupportRequestManagerFragment 

### ISSUE THREAD

**Issue by pclckk** [YoKeyword/Fragmentation#890]
悬浮球里边 一直有 这个 SupportRequestManagerFragment 
![98 e6nk30jl 3o0bjj7 x](https://user-images.githubusercontent.com/28282864/40894173-47e2f004-67da-11e8-83ec-6456d0f3fe04.png)

**Comment by LonelyMushroom** [comment]
https://github.com/YoKeyword/Fragmentation/issues/597
