### ISSUE TITLE
锤子 Y7 手机   

### ISSUE THREAD

**Issue by luyun181** [YoKeyword/Fragmentation#892]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
 1.3.3
* Screenshots

 Android 7.0 底部导航栏不显示图标。红米4   Android 6.0上也有这个问题
![Uploading TIM图片20180605104914.png…]()

**Comment by luyun181** [comment]
![tim 20180605104914](https://user-images.githubusercontent.com/19603477/40952658-b2f6b432-68ae-11e8-8abd-88dfd846bafb.png)

**Comment by LonelyMushroom** [comment]
额.请问这个跟库有什么关系么
