### ISSUE TITLE
startWithPop怎样才能销毁当前fragment？

### ISSUE THREAD

**Issue by dongweiq** [YoKeyword/Fragmentation#90]
我使用startWithPop(SupportFragment fragment)的时候，由于使用了高德地图，从一个地图切换到另外一个地图，当前的地图应该关闭掉，但是我在生命周期打log发现，当前的fragment并没有关闭，而是一直在，导致了在程序里有两个高德地图对象，这样内存扛不住了，设备差一点的基本都是内存溢出。目前解决方法是不再使用stack，都用replace，但是就木有动画了，好桑心，大神求助

**Comment by dongweiq** [comment]
或者我就只能使用pop＋start方式了

**Comment by YoKeyword** [comment]
使用地图控件时，startWithPop()导致地图控件不能正确pop是吗？ 在栈视图里地图FG一直存在？

你先检查下onDestroy/onDestroyView里是否有比较异常的操作，导致出栈失败～
地图是有点特殊的控件，需要绑定它的生命周期，你先排查下～
实在搞不定，可以pop+start 动画方面其实可以自由设定，达到预期效果～

我回头再有空看下哈～ 最近非常忙 不能立马实践去看看～

**Comment by dongweiq** [comment]
并不是因为地图才不销毁，是所有的都不销毁，我打日志从a startwithpop b，a中的onpause、ondestroy等方法都不执行

**Comment by YoKeyword** [comment]
那就需要检查代码啦～ 看有没有奇怪的代码，pop是可以正常销毁哒

**Comment by ghost** [comment]
同样的问题。调用startWithPop 根据不走onDestroyView。调用pop正常走onDestroyView
