### ISSUE TITLE
1.3.4，如果界面里包含listview，在pop的时候会报异常

### ISSUE THREAD

**Issue by TraceabilityChain** [YoKeyword/Fragmentation#901]
1.3.4，如果界面里包含listview，在pop的时候会报异常
“parameter must be a descendant of this view”
1.1.10版本没有这个问题

**Comment by YoKeyword** [comment]
看下 [这个](https://stackoverflow.com/questions/7100555/preventing-catching-illegalargumentexception-parameter-must-be-a-descendant-of)是否对你有帮助

**Comment by designDo** [comment]
如果pop之后要做其它的操作，就在pop() 之后用  post 保证fragment被pop完成， 比如pop 之后的数据库操作。
post(new Runnable() {
                            @Override
                            public void run() {
                                Realm realm = Realm.getDefaultInstance();
                                realm.beginTransaction();
                                realm.deleteAll();
                                realm.commitTransaction();
                                realm.close();
                            }
                        });
