### ISSUE TITLE
supportFragment周期的问题

### ISSUE THREAD

**Issue by pye52** [YoKeyword/Fragmentation#91]
WechatSecondTabFragment和下面的FirstPagerFragment、OtherPagerFragment的生命周期是怎么样的呢？

**Comment by YoKeyword** [comment]
WechatSecondTabFG是FirstPagerFG和OtherPagerFG的父Fragment～

生命周期的问题和栈层级有直接的关系，父Fragment接收到的onHiddenChanged这种生命周期回调，不会传递给子Fragment， 当然对于onResume,onPause这种依赖Activity的生命周期 不管父 还是子FG都会回调～

这个问题建议写个demo，打上log测测纪录下，就很明白了～

**Comment by pye52** [comment]
谢谢~
