### ISSUE TITLE
有出栈动画 结束时的回调吗？

### ISSUE THREAD

**Issue by ltym2016** [YoKeyword/Fragmentation#910]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
出栈动画期间，Fragment其实已经走完了生命周期，所以不适合给出 结束的回调

一般在上一个Fragment可见时 post 一个出栈时间来实现你的需求
