### ISSUE TITLE
fragment点击事件通透

### ISSUE THREAD

**Issue by chengxuyuan112** [YoKeyword/Fragmentation#912]
我上个fragment有一个有个Button按钮，使用startWithPop打开一个新的fragment，还是可以监听到上一个fragment的点击事件

**Comment by MrWangChong** [comment]
对对，我的是ViewPager冲突了

**Comment by chengxuyuan112** [comment]
是因为你的fragment没有隐藏的原因吗？

**Comment by MrWangChong** [comment]
不是吧，我的问题现在依然还没解决，你的问题解决了吗？

**Comment by chengxuyuan112** [comment]
你的问题没有解决吗？我的解决了你给每个布局的跟布局添加 android:clickable="true"这个就可以解决

**Comment by MrWangChong** [comment]
我的问题解决了，和你的不一样，我的不是透传，是滑动冲突，是因为前面的ViewPager再判断canScroll的时候子View有ViewPager这时候会返回ture就导致一直不会拦截触摸事件，拿不到就滑不动
