### ISSUE TITLE
发现frg的生命周期指走一次了，比如onResume都不走了

### ISSUE THREAD

**Issue by edcedc** [YoKeyword/Fragmentation#916]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by LonelyMushroom** [comment]
信息量太少了....

**Comment by YoKeyword** [comment]
Fragment的`onResume`等生命周期是跟随宿主Activity的，   正常Fragment之间的切换一般回调的是`onHiddenChanged()` or `setUserVisibleHint()`
