### ISSUE TITLE
RecyclerView item 里面用Fresco加载网络图片，点击item到下一个fragment，图片会消失

### ISSUE THREAD

**Issue by ltym2016** [YoKeyword/Fragmentation#918]
## RecyclerView item 里面用Fresco加载网络图片，点击item到下一个fragment，图片会消失
- 我在你的demo中引入fresco 1.9.0 ，在ChatAdapter 里用SimpleDraweeView加载网络图片
- 点击item，在横向转场动画过程中，问题也重现，图片消失
- 目前只有Android 8.0 以上的机型上出现
- 如果不是到fragment而是跳转的Activity也是没问题的
- [gift演示](https://note.youdao.com/share/?id=6d9fc508e1f1df48fba32d32b05affed&type=note#/)

**Comment by YoKeyword** [comment]
duplicate of #584
