### ISSUE TITLE
Fragment 持久化问题

### ISSUE THREAD

**Issue by douya40** [YoKeyword/Fragmentation#920]
Fragment 持久化问题，当前fragment页面，按住home页面，过一会在回到之前fragment，发现之前的fragment已经销毁，被重新进入主页面。这是个大问题

**Comment by LonelyMushroom** [comment]
onsaveinstancestate的数据备份和恢复做下试试

**Comment by douya40** [comment]
没弄过这个，怎么搞呢

**Comment by LonelyMushroom** [comment]
onsaveinstancestate 去百度查下

**Comment by YoKeyword** [comment]
框架只操作Fragment相关，  你的场景连Activity都被销毁，应该是恢复机制没做好， 建议断点／Log调试下

**Comment by FeeAlan** [comment]
@douya40 我也遇到这个问题了，请问你是如何解决的这个问题的？
