### ISSUE TITLE
如何判断当前activity中启动了多少个framgent

### ISSUE THREAD

**Issue by Novice9527** [YoKeyword/Fragmentation#921]
如何判断当前activity中启动了多少个framgent ,在剩下最后一个fragment的时候点击返回的时候finsh当前activity

**Comment by LonelyMushroom** [comment]
[参考onBackPressedSupport方法](https://github.com/YoKeyword/Fragmentation/blob/master/fragmentation_core/src/main/java/me/yokeyword/fragmentation/SupportActivityDelegate.java)
