### ISSUE TITLE
进入mainfragment之后打开多个fragment，当最后一个fragment点击返回的时候，如何回到mainfragment页面？

### ISSUE THREAD

**Issue by Jacky-Xu** [YoKeyword/Fragmentation#923]

**Comment by YoKeyword** [comment]
`popTo(RootFragment.class, false);`
or
`start(rootFragment, SINGLETASK);`

**Comment by Jacky-Xu** [comment]
@YoKeyword  使用你上面的方法，打开是空白页面

**Comment by YoKeyword** [comment]
@Jacky-Xu 可以看下Demo或wiki， 如果栈层级正确的话，上面的方法可以达到你的预期
