### ISSUE TITLE
fragment监听

### ISSUE THREAD

**Issue by cgt1994** [YoKeyword/Fragmentation#925]
activity展示一个通用的actionbar。然后下面的容器用来作为fragment的容器。在fragment替换 add pop操作后 如何能根据当前fragment动态更换actionbar标题

**Comment by YoKeyword** [comment]
建议搜索ActionBar的相关操作方式

PS: 这种场景下操作ActionBar还是比较繁琐的， 可以考虑ActionBar在自己Fragment里维护
