### ISSUE TITLE
栈视图中多了一个SupportRequestManagerFragment,求解

### ISSUE THREAD

**Issue by maniu-ltd** [YoKeyword/Fragmentation#926]
app运行正常，但是打开栈视图发现多了一个SupportRequestManagerFragment，如图：
![tim 20180712225026](https://user-images.githubusercontent.com/36794003/42641045-3dac485a-8626-11e8-853c-d4f08de98b5e.jpg)

app是参照demo中的wechat结构构建的

**Comment by Peretrate** [comment]
这是glide创建的，用来同步生命周期的
