### ISSUE TITLE
从activity跳回到首页某个tab时，会先跳到homeFragment,再跳转到指定的fragment

### ISSUE THREAD

**Issue by Spring1901** [YoKeyword/Fragmentation#927]
录频地址 ：https://image.poempz.com/worldcup/9a9efc57b8fda4ab4a34b803f201b033.mp4

 在Vivo,魅族手机上都有该问题，但在有些手机上又是正常的。

**Comment by Spring1901** [comment]
首界面设置为singleTask,由其它页面跳转到首页第二个tab的时候，在首页面的onNewIntent方法中判断 ，并选中对应的tab,就出现上面视频 的情况

**Comment by YoKeyword** [comment]
可能是因为队列机制， 如果敏感的话使用标准方式切换tab：
````java
fm.beginTransaction().show().hide().commitAllowingStateLoss()
````
