### ISSUE TITLE
我想从fragment C pop 直接回到fragment A 使用popTo() 无效

### ISSUE THREAD

**Issue by zwonb** [YoKeyword/Fragmentation#928]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version 1.3.3
* Support-v4 version 27.1.1
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

我想从fragment C pop 直接回到fragment A 使用popTo() 无效，
如果想要实现这样的功能需要怎么操作？
在fragment C中栈内有 fragment A、 fragment B、 fragment C、

**Comment by hejun041** [comment]
getParentFragment.pop

**Comment by onyx-hehai** [comment]
我也有同样的需求，一个tab上进入了fragmentA ——>fragmentB——>fragmentC,  再次点击tab直接回到fragmentA。感觉没什么有效的api。

**Comment by HuChundong** [comment]
同样的需求，使用popto，发现 a收不到onSupportVisible回调

**Comment by zwonb** [comment]
回复二楼，Fragment不是嵌套关系，标准的叠层上去的，目前我找不到可以优雅的关闭多个Fragment回到较前的Fragment，目前采用activity包含这些Fragment来一次性关闭多个

**Comment by AlexZQS** [comment]
fragment.start(mainTabFragment,SINGLETASK) 可以解决优雅的关闭多个Fragment回到较前的Fragment

**Comment by zwonb** [comment]
回复楼上，虽然这样可以关闭多个Fragment，但是好像存在一个bug，回到较前的Fragment之后，界面显示出现了偏移！只显示了一部分
![tim 20180803155110](https://user-images.githubusercontent.com/22101549/43631330-7de0f5d6-9735-11e8-8461-0597abdd8454.png)

**Comment by zwonb** [comment]
@YoKeyword 不知道是不是bug

**Comment by YoKeyword** [comment]
`C.popTo(A.class,false)`即可， 建议参考Demo， Demo中有多处类似该需求的场景

若不生效，检查是存在多个栈层级，必须`popTo()`只针对 同一层栈级的Fragments， 比如 `A.start(B); B.start(C); C.start(D)`，此时`C.popTo(A.class,false)`是可以正常工作的

若A，B，C不在同一个层级， 在C中通过`getParentFragment/getChildFragment`拿到A的层级的兄弟Fragment，然后再调用`popTo()`
