### ISSUE TITLE
onPause、onStop里popTo会闪屏闪屏

### ISSUE THREAD

**Issue by pye52** [YoKeyword/Fragmentation#93]
fragment3
fragment2
fragment1
rootfragment

在fragment3里onpause或者onstop的时候popTo(rootfragment.class, false)
屏幕会闪一下，请问有什么办法避免呢？

**Comment by YoKeyword** [comment]
我这边试了下，不会闪诶， 你用的最新版本吗？
我的测试方式： 在fragment3里点Home键，表现的行为是：回到root的一瞬间回到home页面
看起来很正常～

**Comment by pye52** [comment]
额…不好意思，没说清楚
我在activity里重写了onkeydown，按下返回键的时候会先pop掉topfragment
然后fragment3在onpause、onstop又会popTo到rootfragment

我自己做了个demo都没闪屏
但是放在项目里pop完之后再popTo就会闪一下

我再调试一下……
