### ISSUE TITLE
ViewPage+TabLayout设置缓存第一次加载多个页面

### ISSUE THREAD

**Issue by strugglelin** [YoKeyword/Fragmentation#938]
mTab.setupWithViewPager(mViewPager);
mViewPager.setCurrentItem(1);
mViewPager.setOffscreenPageLimit(4);
问题：第 1 SupportVisible->1 onLazyInitView-> 0 SupportVisible->0 onLazyInitView
希望结果：1 SupportVisible->1 onLazyInitView

**Comment by YoKeyword** [comment]
这个是ViewPager的机制， 即使你`setCurrentItem(1)`  第0个item依然是先可见的...  可以使用标志位等处理下

**Comment by strugglelin** [comment]
原来放 onLazyInitView方法，现在放在 onActivityCreated设置 可以解决了
