### ISSUE TITLE
startBrotherFragment 中startForResult问题

### ISSUE THREAD

**Issue by hejun041** [YoKeyword/Fragmentation#939]
AFragment下的子A1Fragment通过getParentFragment的startForResult跳转到BFragment，BFragment处理完之后setFragmentResult ，回到了A1Fragment，但是onFragmentResult是在AFragment里面，怎么将数据传递到A1Fragment？换句话说就是父Fragment怎么传递数据给loadRootFragment的子Fragment，在子Fragment已经加载好的情况下
又或者说这种“getParentFragment的startForResult”怎么回调？
@YoKeyword

**Comment by hejun041** [comment]
目前是通过EventBus来解决的，但是总是不太方便

**Comment by YoKeyword** [comment]
建议2种方式： `Eventbus ` or `通过宿主Activity传递通信`
