### ISSUE TITLE
关于DebugHierarchyViewContainer类的removeView(int hierarchy)方法

### ISSUE THREAD

**Issue by Rylynee** [YoKeyword/Fragmentation#94]
关于DebugHierarchyViewContainer类的removeView(int hierarchy)方法
在显示栈视图的时候，如果某个标签是展开状态的，点击该标签，那么该标签下面的子标签都会从LinearLayout里面移除，从而达到“关闭”标签的效果。
但是当我把多个标签都展开，然后点击其中一个标签时，全部展开的标签都会关闭，并且左边的箭头图标没有从“指向下面”变回“指向右边”。查看removeView（）的实现方法，发现实现原理是把层次比父标签高的子标签全部移除了，这样会把其他层次相同的的已经展开的父标签的子标签给全部移除了的。

**Comment by YoKeyword** [comment]
哈哈～ DebugHierarchyViewContainer是比较早实现的了，一直没时间优化重构，你能优化的话非常非常欢迎提PR哈～  

这块回头闲下来会重构下，理想情况是RecyclerView/ListView来做～
