### ISSUE TITLE
Splash Screen Animation Problem

### ISSUE THREAD

**Issue by powext** [YoKeyword/Fragmentation#947]
I get this animation with 
`startActivity(new Intent(this, MainActivity.class)); `
in SplashScreen activity:
https://streamable.com/0gypa

Main activity extends SupportActivity

How to fix this?
Thank you.

**Comment by YoKeyword** [comment]
@powext  Check your Activity theme.

**Comment by powext** [comment]
Resolved removing 
```
<item name="android:windowNoTitle">true</item>
<item name="android:windowFullscreen">true</item> 
```
from my theme
