### ISSUE TITLE
虚拟键盘遮挡Edittext问题

### ISSUE THREAD

**Issue by ningjiaqi** [YoKeyword/Fragmentation#948]
大神，RelativeLayout Edittext底部显示，当弹出软键盘时候出现下图情况，这是Fragmentation问题吗，谢谢！
![a16973e6-af16-e69e-fb2b-8c185deb278c](https://user-images.githubusercontent.com/8966240/43386041-004f545a-9415-11e8-8235-3c1e85249efe.jpg)

**Comment by YoKeyword** [comment]
可以动态设置Activity的软键盘模式， 具体搜索下
