### ISSUE TITLE
extraTransaction().setCustomAnimations

### ISSUE THREAD

**Issue by dvasea1** [YoKeyword/Fragmentation#949]
setFragmentAnimator(new DefaultHorizontalAnimator());
but on single fragment i set : ` extraTransaction().setCustomAnimations(me.yokeyword.fragmentation.R.anim.v_fragment_enter,me.yokeyword.fragmentation.R.anim.v_fragment_pop_exit,me.yokeyword.fragmentation.R.anim.v_fragment_pop_enter,me.yokeyword.fragmentation.R.anim.v_fragment_exit).start(...)`
On version 1.1.8 worked but now whit version 1.3.5 on pop, the animation is horizontal. Why?

**Comment by YoKeyword** [comment]
v1.3.6 :)
