### ISSUE TITLE
popTo 不能指定关闭某个fragment吗？

### ISSUE THREAD

**Issue by yanglin18810778879** [YoKeyword/Fragmentation#95]
popTo 不能指定关闭某个fragment吗
执行老是关闭最上层的
启动方式是这样 
SuperSummerFragment fragment = SuperSummerFragment.newInstance();
start(fragment);
两种都不关闭 只能关掉最顶层的
popTo(SuperSummerFragment.this.getClass(),true);
popTo(SuperSummerFragment.this.getClass(),false);

**Comment by YoKeyword** [comment]
popTo(Fragment.class, boolean) 第一个参数是：想关闭的Fragment的class（因为Fragment的严格栈特性，会关闭该Fragment栈上的所有Fragment）；
第二个参数为true时，包含该Fragment一起出栈，false则出栈该Fragment之上的Fragment

同时因为FragmentManager的特性，如果出现重名的Fragment，会从栈顶开始遍历，遍历到第一个则认为找到该Fragment，所以检查是否有复用重名的Fragment

关闭指定的某个栈内部的Fragment，这个因为Fragment的栈特性，不能实现，但是可以通过栈设计达到同样的效果～

**Comment by yanglin18810778879** [comment]
非常感谢回答，
 /**
     * 让Activity中某一个fragment出栈
     */
    public void pop(Fragment fragment) {
        mFragmentation.back(getFragmentManager(),fragment);
    }
如果我想做一个这样的功能 有什么建议吗？

**Comment by YoKeyword** [comment]
不建议.... Fragment的栈很严格，不像Activity，你即使强制性把这个Fragment出栈了，感觉会很有风险，建议用官方标准做法， 实在解决不了用其他思路解决...
