### ISSUE TITLE
 start(topFragment,SINGLETASK); 会关闭页面

### ISSUE THREAD

**Issue by AlexZQS** [YoKeyword/Fragmentation#951]
这个方法可以跳转到目标fragment，且关闭之前的fragment，有没有办法能跳转到目标fragment，且不会关闭其他的fragment

**Comment by YoKeyword** [comment]
Fragment是严格的栈，如果这些Fragment在回退栈里是达不到你的需求的

但是可以不加入回退栈的方式，通过show/hide 实现你的需求
