### ISSUE TITLE
1.3.5版本栈视图不显示

### ISSUE THREAD

**Issue by a1067111756** [YoKeyword/Fragmentation#952]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version： 1.3.5
* Support-v4 version ： 26.1.0
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

如题，翻阅了之前的issues，操作应该都设置了

1. 在application中初始化
 Fragmentation.builder()
                // 设置 栈视图 模式为 悬浮球模式   SHAKE: 摇一摇唤出   NONE：隐藏
                .stackViewMode(Fragmentation.BUBBLE)
                .debug(true)
                // 在遇到After onSaveInstanceState时，不会抛出异常，会回调到下面的ExceptionHandler
                .handleException(new ExceptionHandler() {
                    @Override
                    public void onException(Exception e) {
                        // 建议在该回调处上传至我们的Crash监测服务器
                        // 以Bugtags为例子: 手动把捕获到的 Exception 传到 Bugtags 后台。
                        // Bugtags.sendException(e);
                    }
                })
                .install();
 2. 在AndroidMainfest声明application

    <application
        android:name=".ExampleApp"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="android:icon,android:theme,android:allowBackup" >

**Comment by YoKeyword** [comment]
看设置好像没问题， clone下Demo看下， 应该哪里细节有问题
