### ISSUE TITLE
Viewpager+Tablayout形式添加多个fragment, mViewPager.setCurrentItem(index)不生效（在该index的fragment未出现过的时候）

### ISSUE THREAD

**Issue by zhang461382599** [YoKeyword/Fragmentation#955]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment]
ViewPager使用问题，试试放到post里执行
