### ISSUE TITLE
AndroidX兼容包

### ISSUE THREAD

**Issue by voctex** [YoKeyword/Fragmentation#958]
能基于AndroidX兼容包出个新版本吗？现在support包google基本转移到AndroidX里面了

**Comment by powext** [comment]
I'm waiting for the support too 😄 
Android X is the future!

**Comment by yuxiujuan** [comment]
@voctex，请问您做好兼容了吗？咋做？

**Comment by voctex** [comment]
> @voctex，请问您做好兼容了吗？咋做？

我没处理，坐等作者兼容一个新版本

**Comment by yuxiujuan** [comment]
> > @voctex，请问您做好兼容了吗？咋做？
> 
> 我没处理，坐等作者兼容一个新版本
 
好的，谢谢，那我直接当moudle用吧，升级个androidx，好多个坑，一抹辛酸泪啊，2天多，终于完事了

**Comment by voctex** [comment]
> > > @voctex，请问您做好兼容了吗？咋做？
> > 
> > 
> > 我没处理，坐等作者兼容一个新版本
> 
> 好的，谢谢，那我直接当moudle用吧，升级个androidx，好多个坑，一抹辛酸泪啊，2天多，终于完事了

哈哈，作者也忙呢，能自己搞就自己折腾吧，话说你也可以弄个分支出来

**Comment by ruzhan123** [comment]
@YoKeyword 报告作者, 在升级到 androidx， androidx.fragment.app.FragmentManagerImpl 是个内部类无法直接使用，在 FragmentationMagician 出现了问题...

**Comment by xiaoleidontgo** [comment]
希望出androidX兼容包

**Comment by f-liutao** [comment]
实在是不想做module，能尽快兼容一下androidx就好了。

**Comment by tyzero** [comment]
求同，出个官方  AndroidX Support 呗

**Comment by taurin1979** [comment]
把FragmentationMagician的包名改成androidx.fragment.app就好了

**Comment by YoKeyword** [comment]
已释出fragmentationx: v1.0.0（以后`androidx`分支为默认分支, `master`继续作为android.support的支持分支），[使用方式](https://github.com/YoKeyword/Fragmentation/blob/androidx/README_CN.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)
````gradle
compile 'me.yokeyword:fragmentationx-core:1.0.0'
compile 'me.yokeyword:fragmentationx:1.0.0'
compile 'me.yokeyword:fragmentationx-swipeback:1.0.0'
````
