### ISSUE TITLE
tablayout里面的fragment要去另外一个fragment选择数据返回，返回值无法取到

### ISSUE THREAD

**Issue by douya40** [YoKeyword/Fragmentation#96]
tablayout里面的fragment要去另外一个fragment选择数据，返回更新，好像目前实现不了

**Comment by YoKeyword** [comment]
你的是TabLayout里的子FragmentA 通过getParentFragment.start(另外一个Fragment B)吗？

如果是的话，数据接收者是FragmentA的父Fragment，因为是父Fragment去启动的，所以B和父Fragment是同一级，数据的传递也是那一级，

如果想让子Fragment收到数据，可以让父Fragment通过EventBus传递数据～

**Comment by douya40** [comment]
EventBus.getDefault().post(new StartBrotherEvent(CycleFragment.newInstance(1)));   我要去CycleFragment选择一个数据返回tablayoutd的fragment进行数据更新，不行，求解决方案

**Comment by YoKeyword** [comment]
EventBus的用法有问题...  你这个写法看不懂...

ParentFG.start(CyclerFG, REQ)，
CyclerFG里把数据通过eventBus.post(new Event)，
然后子Fragment里 onEvent(Event event)里接收；

**Comment by douya40** [comment]
739944391 能加个QQ吗？我把详细的流程和你说下

**Comment by YoKeyword** [comment]
验证不过～ 加我吧 328903522

**Comment by douya40** [comment]
好的
