### ISSUE TITLE
Action Queue快速点击的时候，会导致ActionQueue的size大于1，然后就不会执行handleAction了

### ISSUE THREAD

**Issue by 56858752** [YoKeyword/Fragmentation#960]
`
  
        mMainHandler.post(new Runnable() {
            @Override
            public void run() {
                enqueueAction(action);
            }
        });

    private void enqueueAction(Action action) {
        mQueue.add(action);
        if (mQueue.size() == 1) {
            handleAction();
        }
    }
`

如题，这里会出现一个bug，如果快速操作start或者pop等action方法，会导致queue的size大于1,此时handleAction就不会执行了，然后现象就是点击任何选项卡都没反应了。

**Comment by YoKeyword** [comment]
v1.3.6 试试 :)
