### ISSUE TITLE
一次性返回多个几面，有这个方法么？

### ISSUE THREAD

**Issue by yedashen** [YoKeyword/Fragmentation#967]
# Issues Guideline

Following information can help us to resolve the issue faster.

* V1.3.1

  是这样的，我目前用您的框架V1.3.1 版本的，我现在遇到的需求是 比如我开启了界面1、在界面1的基础上再开启界面2、在界面2的基础上去打开界面3、然后再界面3的基础上再开启4，我现在可不可以在关闭4的同时关闭 2 和 3。我目前自己想到一种办法，就是在开启界面2的时候开启一个activity，后面的操作在这个Activity 完成，然后我可以关闭 界面4 的时候直接关闭Activity。但是我想知道您的框架有没有现成的办法，我找了没找到。。。。能抽空告诉我一下么？谢谢

**Comment by beilo** [comment]
startWithPopTo能满足么

**Comment by yedashen** [comment]
我自己目前用SupportActivity 开启了了一个新的容器来解决问题了，并且目前感觉还不错，我这段时间忙完项目之后去看一下作者的项目源代码好好学习一下。
