### ISSUE TITLE
最新代码 TransactionDelegate pop 和 popQuiet中  FragmentationMagician.popBackStackAllowingStateLoss(fm);  removeTopFragment(fm); 调用顺序不同   pop中的调用顺序有问题吧

### ISSUE THREAD

**Issue by weikaiyun** [YoKeyword/Fragmentation#973]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by Mr-PolarBear** [comment]
老哥没空来解答吧   我也遇到这个问题
