### ISSUE TITLE
嵌套百度地图的Fragment，在打开和关闭新的Fragment时会闪白屏

### ISSUE THREAD

**Issue by yangjiechina** [YoKeyword/Fragmentation#974]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by yangjiechina** [comment]
这是录屏gif地址:https://img-blog.csdn.net/20180824171300284?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NpbmF0XzM1OTM4MDEy/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70
真机和模拟器都会出现。

**Comment by yangjiechina** [comment]
还有一个问题大佬，打开Fragment想支持侧滑和普通，两种方式该怎么办？

**Comment by yangjiechina** [comment]
才试了一下，跳转Activity不会闪白屏。

**Comment by jisuz** [comment]
想问一下，我在继承百度地图SDK后，通过Tab切换，第一次也会出现闪一下桌面，然后才正常显示，请问你是怎么解决这个问题的？

**Comment by yangjiechina** [comment]
> 想问一下，我在继承百度地图SDK后，通过Tab切换，第一次也会出现闪一下桌面，然后才正常显示，请问你是怎么解决这个问题的？

TextureMapView

**Comment by zhangjianwei1** [comment]
是不是设置了背景透明，加载地图的时候可以在动画结束那个方法里初始化，退出页面执行webView.Destory()才会白屏，和框架无关，需要自己处理

**Comment by yangjiechina** [comment]
> 是不是设置了背景透明，加载地图的时候可以在动画结束那个方法里初始化，退出页面执行webView.Destory()才会白屏，和框架无关，需要自己处理

嗯，谢谢。我等会试下。
