### ISSUE TITLE
Fragmentation INSTANCE 应该有个是否install方法吧供外部使用

### ISSUE THREAD

**Issue by Colcode** [YoKeyword/Fragmentation#992]
错误日志：
java.lang.RuntimeException: Unable to start receiver com.alibaba.sdk.android.push.SystemEventReceiver: java.lang.RuntimeException: Unable to create application com.stub.StubApp: java.lang.RuntimeException: Default instance already exists. It may be only set once before it's used the first time to ensure consistent behavior.

源码:
public Fragmentation install() {
            synchronized (Fragmentation.class) {
                if (Fragmentation.INSTANCE != null) {
                    throw new RuntimeException("Default instance already exists." +
                            " It may be only set once before it's used the first time to ensure consistent behavior.");
                }
                Fragmentation.INSTANCE = new Fragmentation(this);
                return Fragmentation.INSTANCE;
            }
        }

**Comment by YoKeyword** [comment]
v1.3.7，允许多次`install`，考虑了下 即使多次install也没什么副作用
