### ISSUE TITLE
跳转不流畅

### ISSUE THREAD

**Issue by meipeng** [YoKeyword/Fragmentation#994]
fragment之间跳转不流畅

**Comment by meipeng** [comment]
onEnterAnimationEnd 在动画完成后再进行复杂的处理，页面有设置开关按钮的控件，进入这个类型的页面都有些卡顿

**Comment by YoKeyword** [comment]
竖直动画视觉上更流畅，特别追求性能的话，考虑动态创建易引起卡顿的组件
