### ISSUE TITLE
showHideFragment(newFragment,oldFragment)出现异常

### ISSUE THREAD

**Issue by Maskedheroe** [YoKeyword/Fragmentation#998]
你好  
我使用的版本是 compile 'me.yokeyword:fragmentation:1.3.4'
                                         'me.yokeyword:fragmentation-swipeback:1.3.4'
在使用showHideFragment出现异常了,新的fragment的UI不会显示,只有空白,如果换成start()就会正常

**Comment by Maskedheroe** [comment]
1.3.6版也是如此

**Comment by YoKeyword** [comment]
确保栈展示没问题， 可以参考Demo
