### ISSUE TITLE
1.3.6 版本，仿GooglePlay交互Demo(流式栈设计)模块中Fragment显示错乱

### ISSUE THREAD

**Issue by AndyXuan** [YoKeyword/Fragmentation#999]
您好，我下载了您的demo ,然后我把sample中的代码copy 到demo 中
引入的包：
compile 'me.yokeyword:fragmentation:1.3.6'
compile 'me.yokeyword:fragmentation-swipeback:1.3.6'
compile 'org.greenrobot:eventbus:3.0.0'
compile 'me.yokeyword:eventbus-activity-scope:1.1.0'
然后在仿GooglePlay交互Demo(流式栈设计)模块中  
我从 首页 ---》切换到    商店页，正常显示 ShopFragment ，此时 我看stack 视图栈  效果如下

  ∨ ShopFragment 
           ContentFragment *
           MenuListFragmentt
   HomeFragment

这时再切换到首页，显示的是HomeFragment    此时我看  stack 视图栈  效果如下

  ∨ ShopFragment *
           ContentFragment *
           MenuListFragmentt
   HomeFragment

**这时再切换到商店页，显示的却是首页Fragment，而不是 ShopFragment**   。 此时我看  stack 视图栈  效果如下

  ∨ ShopFragment *
           ContentFragment *
           MenuListFragmentt
   HomeFragment

问题是这个复现的评率还是有点高的。但是我用您的 fragmentation.apk,就是蒲公英上下载的没出现这个问题。就是很奇怪。
对了。我的环境  和 v7 包：
    compileSdkVersion 26
    buildToolsVersion "26.0.3"

    compile 'com.android.support:appcompat-v7:25.3.1'

希望大大能帮我解答。

**Comment by AndyXuan** [comment]
用的是 start  .
我修改好了。我发现问题是 我之前的gradle 版本是
classpath 'com.android.tools.build:gradle:2.3.0'
后来我升级了 gradle  
classpath 'com.android.tools.build:gradle:3.1.2'
这样，我编译后生成的apk 就不会出现之前的那个显示错乱问题了。
之前的那个 在 仿知乎那里也会有问题。

但就是不明白，为什么升级了 gradle 到3.1.2 后 ，就好用了。

**Comment by yygood1000** [comment]
老哥 你解决了就把issues关了。
